(()=>{
'use strict';
const access=window.TT_ACCOUNT_ACCESS||{},api='../api/brokerage_master.php',q=s=>document.querySelector(s);
let master=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Karachi',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function style(){if(q('#ttBrokerageStyle'))return;const s=document.createElement('style');s.id='ttBrokerageStyle';s.textContent=`.ttbr-inline{margin:14px 18px 18px;border:1px solid #dfe6ec;border-radius:12px;background:#fff;padding:14px}.ttbr-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.ttbr-grid label{font-size:11px;font-weight:800;color:#526173}.ttbr-grid input{width:100%;margin-top:5px;padding:9px;border:1px solid #ccd5df;border-radius:8px}.ttbr-note{font-size:11px;color:#6f7a89;margin:6px 0 12px}.ttbr-table{width:100%;border-collapse:collapse;margin-top:12px}.ttbr-table th,.ttbr-table td{padding:8px 9px;border-bottom:1px solid #edf0f3;text-align:left;font-size:12px}.ttbr-table th{font-size:10px;text-transform:uppercase;color:#687686;background:#f8fafc}.ttbr-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:10px}@media(max-width:850px){.ttbr-grid{grid-template-columns:1fr 1fr}}@media(max-width:540px){.ttbr-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
async function get(){const r=await fetch(api,{credentials:'same-origin',headers:{Accept:'application/json'}});let d={};try{d=await r.json()}catch{}if(!r.ok||!d.ok)throw new Error(d.error||'Could not load Brokerage Master.');master=d;return d}
async function post(body){const r=await fetch(api,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({...body,csrf:access.csrf})});let d={};try{d=await r.json()}catch{}if(!r.ok||!d.ok)throw new Error(d.error||'Brokerage Master could not be updated.');return d}
function productRows(){const rows=master?.productRates||[];return rows.length?`<table class="ttbr-table"><thead><tr><th>Product / Variety</th><th>Brokerage / 100 kg</th><th>Effective From</th><th>Effective To</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${esc(r.product)}</b></td><td>Rs ${esc(r.ratePer100Kg)}</td><td>${esc(r.effectiveFrom)}</td><td>${esc(r.effectiveTo||'Open')}</td></tr>`).join('')}</tbody></table>`:'<div class="ttbr-note">No product brokerage rates saved yet.</div>'}
function whtRows(){const rows=master?.whtRates||[];return rows.length?`<table class="ttbr-table"><thead><tr><th>Brokerage WHT %</th><th>Effective From</th><th>Effective To</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${esc(r.whtPercent)}%</b></td><td>${esc(r.effectiveFrom)}</td><td>${esc(r.effectiveTo||'Open')}</td></tr>`).join('')}</tbody></table>`:'<div class="ttbr-note">No brokerage withholding rate saved yet.</div>'}
function panel(){return `<div class="ttbr-inline" id="ttBrokerageMasterInline"><h3 style="margin:0 0 6px">Brokerage</h3><div class="ttbr-note">Brokerage stays as a normal broker ledger. This master only controls product-wise brokerage rates and brokerage WHT. The Soda date decides the applicable rate.</div><div class="ttbr-grid"><label>Product / Variety<input id="ttbrProduct" placeholder="e.g. IRRI-6 Raw Rice"></label><label>Brokerage Rate (Rs per 100 kg)<input id="ttbrRate" inputmode="decimal"></label><label>Effective From<input id="ttbrFrom" type="date" value="${today()}"></label><label>Effective To <span style="font-weight:400">optional</span><input id="ttbrTo" type="date"></label></div><div class="ttbr-actions"><button class="btn primary" id="ttbrSaveProduct">Save Product Brokerage</button></div>${productRows()}<hr style="border:0;border-top:1px solid #edf0f3;margin:18px 0"><div class="ttbr-grid"><label>Brokerage WHT %<input id="ttbrWht" inputmode="decimal" value="12"></label><label>Effective From<input id="ttbrWhtFrom" type="date" value="${today()}"></label><label>Effective To <span style="font-weight:400">optional</span><input id="ttbrWhtTo" type="date"></label><div></div></div><div class="ttbr-actions"><button class="btn primary" id="ttbrSaveWht">Save Brokerage WHT</button></div>${whtRows()}</div>`}
function bind(){q('#ttbrSaveProduct')?.addEventListener('click',async()=>{try{await post({action:'save_product_rate',product:q('#ttbrProduct').value.trim(),ratePer100Kg:q('#ttbrRate').value,effectiveFrom:q('#ttbrFrom').value,effectiveTo:q('#ttbrTo').value,active:true});await get();mount()}catch(e){alert(e.message||e)}});q('#ttbrSaveWht')?.addEventListener('click',async()=>{try{await post({action:'save_wht_rate',whtPercent:q('#ttbrWht').value,effectiveFrom:q('#ttbrWhtFrom').value,effectiveTo:q('#ttbrWhtTo').value,active:true});await get();mount()}catch(e){alert(e.message||e)}})}
async function mount(){style();q('#ttBrokerageTile')?.remove();q('#ttBrokerageRoot')?.remove();const body=q('#masterBody');if(!body)return;try{if(!master)await get()}catch(e){console.error(e);return}q('#ttBrokerageMasterInline')?.remove();body.insertAdjacentHTML('beforeend',panel());bind()}
function isRulesOpen(){return !!q('[data-master="rules"].active')}
document.addEventListener('click',e=>{if(e.target.closest('[data-master="rules"]'))setTimeout(mount,60);if(e.target.closest('[data-key="payables"]'))setTimeout(()=>{q('#ttBrokerageTile')?.remove();q('#ttBrokerageRoot')?.remove()},60)});
new MutationObserver(()=>{q('#ttBrokerageTile')?.remove();q('#ttBrokerageRoot')?.remove();if(isRulesOpen()&&!q('#ttBrokerageMasterInline'))setTimeout(mount,30)}).observe(document.documentElement,{childList:true,subtree:true});
})();
