(()=>{
'use strict';
const access=window.TT_ACCOUNT_ACCESS||{},txApi='../api/brokerage_transactions.php',bankApi='../api/bank_accounts.php';
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],entity=()=>localStorage.getItem('tt_accounts_entity')||'TTI';
let tx=null,banks=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n||0).toLocaleString('en-PK',{maximumFractionDigits:2});
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Karachi',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
async function getJson(url){const r=await fetch(url,{credentials:'same-origin',headers:{Accept:'application/json'}});let d={};try{d=await r.json()}catch{}if(!r.ok||!d.ok)throw new Error(d.error||'Could not load Brokerage WHT data.');return d}
async function load(){[tx,banks]=await Promise.all([getJson(txApi+'?entity='+encodeURIComponent(entity())),getJson(bankApi+'?entity='+encodeURIComponent(entity()))])}
function bankLabel(a){const custom=String(a.settings?.displayName||'').trim(),tail=a.accountLast5?` · •••${a.accountLast5}`:'';return custom||`${a.bankName||a.accountTitle||'Bank'}${tail}`}
function bankOptions(){const rows=(banks?.accounts||[]).filter(a=>a.settings?.active&&a.settings?.allowPayments&&!a.needsCompletion&&String(a.currency||'').toUpperCase()==='PKR');return rows.length?rows.map(a=>`<option value="${esc(a.id)}">${esc(bankLabel(a))}</option>`).join(''):'<option value="">No PKR bank enabled for payments</option>'}
function brokerOptions(){const rows=tx?.brokers||[];return rows.length?rows.map(x=>`<option value="${esc(x.broker)}">${esc(x.broker)} · WHT outstanding Rs ${fmt(x.outstanding)}</option>`).join(''):'<option value="">No broker WHT outstanding</option>'}
function render(){const body=q('#ttbrTabBody');if(!body)return;const rows=tx?.brokers||[];body.innerHTML=`<div><h3 style="margin:0 0 10px">Broker WHT Deposit</h3><div class="ttbr-note" style="margin-bottom:12px">Partial deposits are allowed. Transtrade automatically clears the oldest outstanding brokerage WHT for the selected broker first.</div><div class="ttbr-grid"><label>Broker<select id="ttbwBroker">${brokerOptions()}</select></label><label>Amount<input id="ttbwAmount" inputmode="decimal"></label><label>Payment Date<input id="ttbwDate" type="date" value="${today()}"></label><label>Payment Source<select id="ttbwSource"><option value="BANK">Transtrade Bank</option><option value="CASH">Cash</option><option value="OTHER">Other Source</option></select></label><label id="ttbwBankWrap">Bank Account<select id="ttbwBank">${bankOptions()}</select></label><label id="ttbwOtherTypeWrap" style="display:none">Other Source Type<select id="ttbwOtherType"><option value="THIRD_PARTY">Third Party</option><option value="DIRECTOR_FAMILY">Director / Family</option><option value="GROUP_ENTITY">Group Entity</option><option value="OTHER_ADJUSTMENT">Other Adjustment</option></select></label><label id="ttbwNameWrap" style="display:none">Name / Source<input id="ttbwName"></label><label>Reference <span style="font-weight:400">optional</span><input id="ttbwRef"></label></div><div class="ttbr-actions"><button class="btn primary" id="ttbwPost" ${rows.length?'':'disabled'}>Post WHT Deposit</button></div>${rows.length?`<table class="ttbr-table"><thead><tr><th>Broker</th><th>WHT Outstanding</th><th>Oldest Open Item</th></tr></thead><tbody>${rows.map(x=>`<tr><td><b>${esc(x.broker)}</b></td><td>Rs ${fmt(x.outstanding)}</td><td>${esc(x.rows?.[0]?.date||'—')} · ${esc(x.rows?.[0]?.source||'')}</td></tr>`).join('')}</tbody></table>`:'<div class="ttbr-note">No brokerage WHT is currently outstanding.</div>'}</div>`;bind()}
function sourceType(){const s=q('#ttbwSource')?.value||'BANK';if(s!=='OTHER')return s;return q('#ttbwOtherType')?.value||'THIRD_PARTY'}
function toggle(){const s=q('#ttbwSource')?.value||'BANK';if(q('#ttbwBankWrap'))q('#ttbwBankWrap').style.display=s==='BANK'?'block':'none';if(q('#ttbwOtherTypeWrap'))q('#ttbwOtherTypeWrap').style.display=s==='OTHER'?'block':'none';if(q('#ttbwNameWrap'))q('#ttbwNameWrap').style.display=s==='OTHER'?'block':'none'}
function bind(){q('#ttbwSource')?.addEventListener('change',toggle);q('#ttbwOtherType')?.addEventListener('change',toggle);toggle();q('#ttbwPost')?.addEventListener('click',post)}
async function post(){const b=q('#ttbwPost');if(b)b.disabled=true;try{const payload={action:'deposit_wht',csrf:access.csrf,entity:entity(),broker:q('#ttbwBroker')?.value||'',amount:q('#ttbwAmount')?.value||'',date:q('#ttbwDate')?.value||'',sourceType:sourceType(),bankAccountId:q('#ttbwBank')?.value||'',sourceName:q('#ttbwName')?.value?.trim()||'',reference:q('#ttbwRef')?.value?.trim()||''};const r=await fetch(txApi,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(payload)});let d={};try{d=await r.json()}catch{}if(!r.ok||!d.ok)throw new Error(d.error||'WHT deposit could not be posted.');await load();render();window.dispatchEvent(new CustomEvent('tt:brokerage-updated'));alert('Broker WHT deposit posted.')}catch(e){alert(e.message||e)}finally{if(b)b.disabled=false}}
async function openWht(){try{await load();render()}catch(e){const body=q('#ttbrTabBody');if(body)body.innerHTML='<div class="ttbr-note">'+esc(e.message||e)+'</div>'}}
document.addEventListener('click',e=>{if(e.target.closest('[data-br-tab="WHT"]'))setTimeout(openWht,0);if(e.target.closest('.entityBtn')&&q('[data-br-tab="WHT"].sel'))setTimeout(openWht,120)});
})();

