(()=>{
'use strict';
const access=window.TT_ACCOUNT_ACCESS||{},api='../api/brokerage_master.php',q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
let master=null,open=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Karachi',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function style(){if(q('#ttBrokerageStyle'))return;const s=document.createElement('style');s.id='ttBrokerageStyle';s.textContent=`.ttbr-card{border:1px solid #dbe2ea;background:#fff;border-radius:14px;padding:15px;cursor:pointer}.ttbr-card:hover{background:#f8fafc}.ttbr-root{margin:14px 18px 18px;border:1px solid #dfe6ec;border-radius:12px;background:#fff;overflow:hidden}.ttbr-head{padding:13px 14px;border-bottom:1px solid #edf0f3;display:flex;align-items:center;gap:10px}.ttbr-head .sp{flex:1}.ttbr-body{padding:14px}.ttbr-tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px}.ttbr-tab{border:1px solid #dbe2ea;background:#fff;border-radius:999px;padding:7px 10px;font-weight:800;cursor:pointer}.ttbr-tab.sel{background:#102a46;color:#fff;border-color:#102a46}.ttbr-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.ttbr-grid label{font-size:11px;font-weight:800;color:#526173}.ttbr-grid input{width:100%;margin-top:5px;padding:9px;border:1px solid #ccd5df;border-radius:8px}.ttbr-note{font-size:11px;color:#6f7a89;margin-top:8px}.ttbr-table{width:100%;border-collapse:collapse;margin-top:12px}.ttbr-table th,.ttbr-table td{padding:8px 9px;border-bottom:1px solid #edf0f3;text-align:left;font-size:12px}.ttbr-table th{font-size:10px;text-transform:uppercase;color:#687686;background:#f8fafc}.ttbr-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:10px}@media(max-width:850px){.ttbr-grid{grid-template-columns:1fr 1fr}}@media(max-width:540px){.ttbr-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
async function get(){const r=await fetch(api,{credentials:'same-origin',headers:{Accept:'application/json'}});let d={};try{d=await r.json()}catch{}if(!r.ok||!d.ok)throw new Error(d.error||'Could not load Brokerage Master.');master=d;return d}
async function post(body){const r=await fetch(api,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({...body,csrf:access.csrf})});let d={};try{d=await r.json()}catch{}if(!r.ok||!d.ok)throw new Error(d.error||'Brokerage Master could not be updated.');return d}
function productRows(){const rows=master?.productRates||[];return rows.length?`<table class="ttbr-table"><thead><tr><th>Product</th><th>Rate / 100 kg</th><th>Effective From</th><th>Effective To</th><th>Status</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${esc(r.product)}</b></td><td>Rs ${esc(r.ratePer100Kg)}</td><td>${esc(r.effectiveFrom)}</td><td>${esc(r.effectiveTo||'Open')}</td><td>${r.active?'Active':'Inactive'}</td></tr>`).join('')}</tbody></table>`:'<div class="ttbr-note">No product brokerage rates saved yet.</div>'}
function whtRows(){const rows=master?.whtRates||[];return rows.length?`<table class="ttbr-table"><thead><tr><th>Brokerage WHT %</th><th>Effective From</th><th>Effective To</th><th>Status</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${esc(r.whtPercent)}%</b></td><td>${esc(r.effectiveFrom)}</td><td>${esc(r.effectiveTo||'Open')}</td><td>${r.active?'Active':'Inactive'}</td></tr>`).join('')}</tbody></table>`:'<div class="ttbr-note">No brokerage withholding rate saved yet. Current policy discussed is 12%.</div>'}
function masterPanel(){return `<div><h3 style="margin:0 0 10px">Brokerage Master</h3><div class="ttbr-note" style="margin-bottom:12px">All brokerage-related controls stay here. Applicable rate is determined by the Soda date.</div><div class="ttbr-grid"><label>Product<input id="ttbrProduct" placeholder="e.g. IRRI-6 Raw Rice"></label><label>Brokerage Rate (Rs per 100 kg)<input id="ttbrRate" inputmode="decimal"></label><label>Effective From<input id="ttbrFrom" type="date" value="${today()}"></label><label>Effective To <span style="font-weight:400">optional</span><input id="ttbrTo" type="date"></label></div><div class="ttbr-actions"><button class="btn primary" id="ttbrSaveProduct">Save Product Brokerage</button></div>${productRows()}<hr style="border:0;border-top:1px solid #edf0f3;margin:18px 0"><div class="ttbr-grid"><label>Brokerage Withholding %<input id="ttbrWht" inputmode="decimal" value="12"></label><label>Effective From<input id="ttbrWhtFrom" type="date" value="${today()}"></label><label>Effective To <span style="font-weight:400">optional</span><input id="ttbrWhtTo" type="date"></label><div></div></div><div class="ttbr-actions"><button class="btn primary" id="ttbrSaveWht">Save Brokerage WHT</button></div>${whtRows()}</div>`}
function overview(){return `<div><h3 style="margin:0 0 8px">Brokerage</h3><div class="ttbr-note">One continuous brokerage ledger per broker. Separate brokerage bills can cover one or many Sodas, one or many products, but only one broker. Separate brokerage bills are paid separately from commodity supplier bills. Partial brokerage-WHT deposits are allowed broker-by-broker.</div><div class="ttbr-tabs" style="margin-top:14px"><button class="ttbr-tab sel" data-br-tab="MASTER">Brokerage Master</button><button class="ttbr-tab" data-br-tab="LEDGER">Brokerage Ledger</button><button class="ttbr-tab" data-br-tab="BILLS">Separate Brokerage Bills</button><button class="ttbr-tab" data-br-tab="WHT">Broker WHT Deposit</button></div><div id="ttbrTabBody">${masterPanel()}</div></div>`}
function render(){style();const ws=q('#ws-payables');if(!ws)return;let root=q('#ttBrokerageRoot');if(!root){root=document.createElement('div');root.id='ttBrokerageRoot';root.className='ttbr-root hidden';const head=ws.querySelector('.panelHead');head?.insertAdjacentElement('afterend',root)}if(!open){root.classList.add('hidden');return}root.classList.remove('hidden');root.innerHTML=`<div class="ttbr-head"><div><b>Brokerage</b><div class="ttbr-note">Brokerage master, broker-wise ledger, separate brokerage bills and WHT settlement.</div></div><div class="sp"></div><button class="btn" id="ttbrClose">Close</button></div><div class="ttbr-body">${overview()}</div>`;bind()}
function injectTile(){const ws=q('#ws-payables');if(!ws)return;let grid=ws.querySelector('.subGrid');if(!grid){grid=document.createElement('div');grid.className='subGrid';ws.querySelector('.panelHead')?.insertAdjacentElement('afterend',grid)}if(!q('#ttBrokerageTile')){const b=document.createElement('button');b.id='ttBrokerageTile';b.className='subCard ttbr-card';b.innerHTML='<div class="miniIcon">%</div><h3>Brokerage</h3><p>Brokerage master, broker ledger, separate brokerage bills and broker-wise withholding.</p>';grid.appendChild(b);b.onclick=async()=>{open=true;try{await get();render()}catch(e){alert(e.message||e)}}}}
function bind(){q('#ttbrClose')?.addEventListener('click',()=>{open=false;render()});q('#ttbrSaveProduct')?.addEventListener('click',async()=>{try{await post({action:'save_product_rate',product:q('#ttbrProduct').value.trim(),ratePer100Kg:q('#ttbrRate').value,effectiveFrom:q('#ttbrFrom').value,effectiveTo:q('#ttbrTo').value,active:true});await get();render()}catch(e){alert(e.message||e)}});q('#ttbrSaveWht')?.addEventListener('click',async()=>{try{await post({action:'save_wht_rate',whtPercent:q('#ttbrWht').value,effectiveFrom:q('#ttbrWhtFrom').value,effectiveTo:q('#ttbrWhtTo').value,active:true});await get();render()}catch(e){alert(e.message||e)}});qa('[data-br-tab]').forEach(b=>b.onclick=()=>{qa('[data-br-tab]').forEach(x=>x.classList.remove('sel'));b.classList.add('sel');const body=q('#ttbrTabBody');if(!body)return;if(b.dataset.brTab==='MASTER')body.innerHTML=masterPanel();else if(b.dataset.brTab==='LEDGER')body.innerHTML='<div class="ttbr-note">Broker-wise Brokerage Ledger will show gross brokerage, withholding, net payable, payments and WHT balance.</div>';else if(b.dataset.brTab==='BILLS')body.innerHTML='<div class="ttbr-note">Separate Brokerage Bills will link one broker to selected Sodas/trucks and compare expected brokerage with the broker bill before posting.</div>';else body.innerHTML='<div class="ttbr-note">Broker WHT Deposit will allow broker-by-broker partial deposits against outstanding brokerage withholding.</div>';bind()})}
const obs=new MutationObserver(injectTile);obs.observe(document.documentElement,{childList:true,subtree:true});document.addEventListener('click',e=>{if(e.target.closest('[data-key="payables"]'))setTimeout(injectTile,80)});injectTile();
})();