(()=>{
'use strict';
const access=window.TT_ACCOUNT_ACCESS||{},api='../api/donations.php',q=s=>document.querySelector(s),fmt=n=>Number(n||0).toLocaleString('en-PK',{maximumFractionDigits:2}),today=()=>new Date().toISOString().slice(0,10),entity=()=>localStorage.getItem('tt_accounts_entity')||'TTI',currency=()=>entity()==='TG'?'AED':'Rs',esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data={donations:[],totals:{},paymentAccounts:[]},selected='ZAKAT',busy=false;
const labels={ZAKAT:'Zakat',SADQA:'Sadqa',FI_SABILILLAH:'Fi Sabilillah'};
function toast(m,ok=true){let e=q('#ttDonToast');if(!e){e=document.createElement('div');e.id='ttDonToast';e.style.cssText='position:fixed;left:50%;bottom:22px;transform:translateX(-50%);z-index:100020;padding:10px 14px;border-radius:9px;color:#fff;font:700 12px Arial;box-shadow:0 7px 22px #0003';document.body.appendChild(e)}e.style.background=ok?'#147a5b':'#a93a34';e.textContent=m;e.hidden=false;clearTimeout(e._t);e._t=setTimeout(()=>e.hidden=true,3200)}
function style(){if(q('#ttDonStyle'))return;let s=document.createElement('style');s.id='ttDonStyle';s.textContent='.ttdon{margin-top:16px}.ttdon-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:14px}.ttdon-card{border:1px solid #dfe6ec;background:#fff;border-radius:12px;padding:13px}.ttdon-card span{display:block;color:#6f7a89;font-size:10px;text-transform:uppercase}.ttdon-card strong{display:block;font-size:20px;margin-top:5px}.ttdon-tabs{display:flex;gap:7px;flex-wrap:wrap;margin:12px 0}.ttdon-tabs button{border:1px solid #d5dde5;background:#fff;border-radius:999px;padding:7px 11px;font-weight:700;cursor:pointer}.ttdon-tabs button.active{background:#102a46;color:#fff}.ttdon-form{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.ttdon-form label{font-size:10px;font-weight:800;color:#657487}.ttdon-form input,.ttdon-form select{width:100%;padding:8px;border:1px solid #d5dde5;border-radius:7px}.ttdon-actions{display:flex;justify-content:flex-end;margin-top:10px}@media(max-width:760px){.ttdon-grid,.ttdon-form{grid-template-columns:1fr}}';document.head.appendChild(s)}
async function req(body){let opt={method:body?'POST':'GET',credentials:'same-origin',headers:{Accept:'application/json'}};if(body){opt.headers['Content-Type']='application/json';opt.body=JSON.stringify({csrf:access.csrf,entity:entity(),...body})}let r=await fetch(api+'?entity='+encodeURIComponent(entity()),opt),d={};try{d=await r.json()}catch{}if(!r.ok||!d.ok)throw new Error(d.error||'Could not update Donations.');return d}
function payOpts(){return (data.paymentAccounts||[]).map(x=>`<option value="${esc(x.id)}">${esc(x.label)} · Balance ${currency()} ${fmt(x.bookBalance)}</option>`).join('')}
function rows(){let list=(data.donations||[]).filter(x=>x.type===selected);return list.length?list.map(x=>`<tr><td>${esc(x.date)}</td><td><b>${esc(x.payee)}</b></td><td>${esc(x.id)}</td><td>${currency()} ${fmt(x.amount)}</td><td>${esc(x.notes||'—')}</td></tr>`).join(''):'<tr><td colspan="5">No entries in this ledger.</td></tr>'}
function render(){style();let ed=q('#expenseEditor');if(!ed)return;ed.innerHTML=`<div class="ttdon"><div class="ttdon-grid">${Object.keys(labels).map(k=>`<div class="ttdon-card"><span>${labels[k]} Ledger</span><strong>${currency()} ${fmt(data.totals?.[k])}</strong></div>`).join('')}</div><div class="formCard"><h3>Record Donation</h3><div class="ttdon-form"><label>Donation Type<select id="donType">${Object.keys(labels).map(k=>`<option value="${k}">${labels[k]}</option>`).join('')}</select></label><label>Beneficiary / Payee<input id="donPayee"></label><label>Payment Date<input id="donDate" type="date" value="${today()}"></label><label>Amount (${currency()})<input id="donAmount" inputmode="decimal"></label><label>Pay From<select id="donBank">${payOpts()}</select></label><label>Notes<input id="donNotes"></label></div><div class="ttdon-actions"><button class="btn green" id="donSave">Save Donation</button></div></div><div class="ttdon-tabs">${Object.keys(labels).map(k=>`<button class="${k===selected?'active':''}" data-don-tab="${k}">${labels[k]} Ledger</button>`).join('')}</div><article class="panel"><div class="panelHead"><div><h2>${labels[selected]} Ledger</h2><p>Kept separate from the other donation categories.</p></div></div><div class="tableWrap"><table><thead><tr><th>Date</th><th>Beneficiary / Payee</th><th>Reference</th><th>Amount</th><th>Notes</th></tr></thead><tbody>${rows()}</tbody></table></div></article></div>`;q('#donType').value=selected;q('#donSave').onclick=save;document.querySelectorAll('[data-don-tab]').forEach(b=>b.onclick=()=>{selected=b.dataset.donTab;render()})}
async function load(){if(busy)return;try{busy=true;data=await req();render()}catch(e){toast(String(e.message||e),false)}finally{busy=false}}
async function save(){let type=q('#donType').value,payee=q('#donPayee').value.trim(),date=q('#donDate').value,amount=Number(q('#donAmount').value||0),paymentAccountId=q('#donBank').value,notes=q('#donNotes').value.trim();if(!payee||!date||amount<=0||!paymentAccountId)return toast('Complete the donation payment details.',false);try{busy=true;data=await req({action:'record_donation',type,payee,date,amount,paymentAccountId,notes});selected=type;render();toast(labels[type]+' donation saved to its separate ledger.')}catch(e){toast(String(e.message||e),false)}finally{busy=false}}
document.addEventListener('click',e=>{let c=e.target.closest('[data-expense="donations"]');if(!c)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();load()},true);
document.addEventListener('click',e=>{if(e.target.closest('.entityBtn')&&q('.ttdon'))setTimeout(load,120)},false);
window.TT_DONATIONS_UI={refresh:load};
})();

