(() => {
  'use strict';
  const access=window.TT_ACCOUNT_ACCESS||{}, q=(s,r=document)=>r.querySelector(s), entity=()=>localStorage.getItem('tt_accounts_entity')||'TTI', today=()=>new Date().toISOString().slice(0,10), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), money=v=>Number(v||0).toLocaleString('en-PK',{minimumFractionDigits:2,maximumFractionDigits:2});
  let generation=0;
  function can(action){const p=access.permissions;if(access.super||p==='all')return true;if(!p)return false;const icons=Array.isArray(p)?p:p.expenses||[];const scoped=!Array.isArray(p)&&['entity-tti','entity-brm','entity-tg'].some(k=>Object.hasOwn(p,k));return icons.includes(action)&&(!scoped||(p['entity-'+entity().toLowerCase()]||[]).includes(action));}
  async function request(company,body){const r=await fetch('../api/expenses_v1.php?entity='+encodeURIComponent(company),{method:body?'POST':'GET',credentials:'same-origin',headers:{Accept:'application/json',...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify({...body,entity:company,csrf:access.csrf})}:{})});const d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'Expenses could not be loaded.');return d;}
  function shell(title){q('#ttExpenseDesk')?.remove();const host=document.createElement('div');host.id='ttExpenseDesk';host.style.cssText='position:fixed;inset:0;z-index:900;background:#17374766;display:flex;justify-content:center;padding:3vh 12px;overflow:auto';host.innerHTML=`<section style="background:#f5f7f9;border-radius:14px;padding:22px;width:min(1100px,100%);overflow:auto"><div style="display:flex;justify-content:space-between;gap:15px"><h2>${esc(title)}</h2><button class="btn" data-close type="button">Close</button></div><div data-body role="region"></div></section>`;document.body.appendChild(host);q('[data-close]',host).onclick=()=>{if(host.dataset.busy==='1')return;generation++;host.remove();};return host;}
  function label(text,html){return `<label style="display:grid;gap:5px">${text}${html}</label>`;}
  const grid='display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:14px;margin:16px 0';
  function rowHtml(row={}){return `<article class="dex-row" style="background:white;border:1px solid #d1dde3;padding:14px;border-radius:9px;margin:12px 0"><div style="${grid}">${label('Expense type',`<select data-category>${['HOME','OFFICE','MEDICAL','MILL','RENT','DONATION','OTHER'].map(x=>`<option value="${x}">${x[0]+x.slice(1).toLowerCase()}</option>`).join('')}</select>`)}${label('Head of Accounts','<select data-account><option value="">Use expense type treatment</option></select>')}${label('Subaccount / further level (optional)','<select data-subaccount><option value="">Use expense type treatment</option></select>')}${label('Purpose','<input data-purpose required maxlength="500" placeholder="What was this expense for?">')}${label('Amount','<input data-amount type="number" min="0.01" max="100000000000" step="0.01" required>')}<label data-detail style="display:none"></label></div><button class="btn" data-remove type="button">Remove expense</button></article>`;}
  function details(row,values={}){const category=q('[data-category]',row).value,box=q('[data-detail]',row);const fields={MEDICAL:['medicalFor','Medical expense',['HOUSEHOLD','Household'],['COMPANY_STAFF','Company / Staff']],RENT:['rentFor','Rent location',['HOME','Home'],['OFFICE','Office'],['MILL','Mill']],DONATION:['donationType','Donation type',['ZAKAT','Zakat'],['SADQA','Sadqa'],['FI_SABILILLAH','Fi Sabilillah']]};const f=fields[category];box.style.display=f?'grid':'none';box.innerHTML=f?`${f[1]}<select data-detail-key="${f[0]}">${f.slice(2).map(([v,n])=>`<option value="${v}">${n}</option>`).join('')}</select>`:'';if(f&&values[f[0]])q('select',box).value=values[f[0]];}
  async function open(id=''){
    const company=entity(),token=++generation,host=shell(id?'Correct Expense Payment':'Pay Expense'),body=q('[data-body]',host);body.textContent='Loading expenses…';let data,subaccounts=[],heads=[];
    try{[data,subaccounts]=await Promise.all([request(company),fetch('../api/accounts_subaccounts.php?entity='+encodeURIComponent(company),{credentials:'same-origin'}).then(async r=>{const d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'Subaccounts could not load.');heads=(d.heads||[]).filter(a=>!['heading','system'].includes(a.level)&&(a.class==='Expense'||a.code.startsWith('FAM-')||a.code==='3200'));return d.subaccounts||[];})]);}catch(e){body.textContent=e.message;return;}
    if(token!==generation||!host.isConnected||entity()!==company)return;
    const old=id?(data.generalExpenses||[]).find(x=>x.id===id&&x.expenseType==='DIRECT'):null;if(id&&!old){body.textContent='This payment is unavailable or has already been corrected.';return;}
    body.innerHTML=`<p>Pay anyone from a company bank or cash account. Add all expenses covered by this single payment.</p><form data-form><div style="${grid}">${label('Paid to','<input id="dexPayee" data-master-role="parties" required maxlength="180" placeholder="Person or organisation">')}${label('Payment date',`<input id="dexDate" type="date" required value="${today()}">`)}${label('Pay from',`<select id="dexPayAccount" required><option value="">Choose bank / cash account</option>${(data.paymentAccounts||[]).map(a=>`<option value="${esc(a.id)}">${esc(a.label)} · ${esc(a.currency)} ${money(a.bookBalance)}</option>`).join('')}</select>`)}${label('Reference (optional)','<input id="dexReference" maxlength="180">')}</div><div data-rows></div><button class="btn" data-add type="button">+ Add expense</button><p style="font-size:20px">Total payment: <strong data-total>0.00</strong></p>${old?label('Reason for correction','<input id="dexReason" required minlength="5" maxlength="500">'):''}<p data-message role="status"></p><button class="btn primary" data-post type="submit">${old?'Save Correction & Print Voucher':'Post & Print Voucher'}</button></form><details style="margin-top:24px"><summary>Previous expense payments</summary><div data-history></div></details>`;
    const form=q('[data-form]',body),rows=q('[data-rows]',body);let busy=false,pending=null;
    const total=()=>{const n=[...rows.children].reduce((s,r)=>s+Math.round(Number(q('[data-amount]',r).value||0)*100),0)/100;q('[data-total]',body).textContent=money(n);return n;};
    const add=(values={})=>{
      rows.insertAdjacentHTML('beforeend',rowHtml());const row=rows.lastElementChild,head=q('[data-account]',row),sub=q('[data-subaccount]',row);
      head.innerHTML='<option value="">Use expense type treatment</option>'+heads.map(a=>`<option value="${esc(a.code)}">${esc(a.code)} · ${esc(a.name)}</option>`).join('');
      head.value=values.accountCode||values.account||'';
      const populate=(selected='')=>{sub.innerHTML='<option value="">Post to selected head</option>'+subaccounts.filter(a=>a.active&&(a.class==='Expense'||a.parentCode.startsWith('FAM-')||a.parentCode==='3200')&&(!head.value||a.parentCode===head.value)).map(a=>`<option value="${esc(a.id)}">${esc(a.path||a.name)}</option>`).join('');sub.value=selected;};
      populate(values.subaccountId||'');head.onchange=()=>populate();sub.onchange=()=>{const a=subaccounts.find(a=>a.id===sub.value);if(a){head.value=a.parentCode;populate(a.id);}};
      q('[data-category]',row).value=values.category||'OFFICE';q('[data-purpose]',row).value=values.purpose||'';q('[data-amount]',row).value=values.amount||'';details(row,values);
      q('[data-category]',row).onchange=()=>{head.value='';populate();details(row);};q('[data-remove]',row).onclick=()=>{if(rows.children.length>1){row.remove();total();}};q('[data-amount]',row).oninput=total;total();
    };
    (old?.expenseLines||[{}]).forEach(add);q('[data-add]',body).onclick=()=>{if(rows.children.length<50)add();};
    window.TT_BANK_PAYMENT_DETAILS?.mount('dexPayAccount',data.paymentAccounts||[]);
    if(old){q('#dexPayee',body).value=old.payee;q('#dexDate',body).value=old.paymentDate;q('#dexPayAccount',body).value=old.paymentAccountId;q('#dexPayAccount',body).dispatchEvent(new Event('change'));q('#dexReference',body).value=old.reference||'';const box=q('#dexPayAccountDetails',body);if(box&&old.bankPaymentMethod){q('[data-method]',box).value=old.bankPaymentMethod==='BANK_TRANSFER'?'ONLINE_BANKING':old.bankPaymentMethod;q('[data-method]',box).dispatchEvent(new Event('change'));q('[data-reference]',box).value=old.bankPaymentMethod==='CHEQUE'?old.chequeNo||old.bankReference||'':old.bankReference||'';q('[data-narration]',box).value=old.paymentNarration||'';}}
    window.TT_ACCOUNTS_MASTER_CHOICES?.refresh();
    if(!can(old?'Edit':'Create'))q('[data-post]',body).disabled=true;
    form.onsubmit=async event=>{event.preventDefault();if(busy)return;const message=q('[data-message]',body);if(entity()!==company){message.textContent='Company changed. Reopen Pay Expense in the intended company.';return;}
      let payload;try{payload={action:old?'amend_expense':'pay_expense',...(old?{id:old.id,reason:q('#dexReason',body).value.trim()}:{}),payee:q('#dexPayee',body).value.trim(),paymentDate:q('#dexDate',body).value,paymentAccountId:q('#dexPayAccount',body).value,reference:q('#dexReference',body).value.trim(),amount:total(),expenseLines:[...rows.children].map(row=>{const detail=q('[data-detail-key]',row);return {accountCode:q('[data-account]',row).value,subaccountId:q('[data-subaccount]',row).value,category:q('[data-category]',row).value,purpose:q('[data-purpose]',row).value.trim(),amount:Number(q('[data-amount]',row).value),...(detail?{[detail.dataset.detailKey]:detail.value}:{})};}),...window.TT_BANK_PAYMENT_DETAILS?.read('dexPayAccount',q('#dexDate',body).value)};}catch(e){message.textContent=e.message;return;}
      const signature=JSON.stringify(payload);if(!pending||pending.signature!==signature)pending={signature,key:'dex-'+(crypto.randomUUID?.()||Date.now()+'-'+Math.random().toString(16).slice(2))};payload.requestKey=pending.key;
      const popup=window.open('','_blank');if(popup)popup.document.write('<title>Expense voucher</title>Posting payment…');busy=true;host.dataset.busy='1';[...form.elements].forEach(el=>el.disabled=true);message.textContent='Posting payment…';
      try{const result=await request(company,payload);const saved=result.generalExpenses?.find(x=>x.id===(result.result?.generalExpenseId))||result.generalExpenses?.find(x=>x.payee===payload.payee&&x.reference===payload.reference&&x.amount===payload.amount&&x.paymentDate===payload.paymentDate);const journalId=result.result?.journalId||saved?.journalId;if(!journalId)throw Error('Payment response did not include its saved voucher. Reopen Previous expense payments before retrying.');
        pending=null;body.innerHTML=`<h3>Payment posted</h3><p>Paid to ${esc(payload.payee)} · ${money(payload.amount)}</p><p>Post ID: ${esc(journalId)}</p><button class="btn" data-print>Print voucher again</button> <button class="btn primary" data-another>Pay another expense</button>`;q('[data-print]',body).onclick=()=>window.TT_ACCOUNTING_DESK?.printVoucher({data:{entity:company,journalId}});q('[data-another]',body).onclick=()=>open();await window.TT_ACCOUNTING_DESK?.printVoucher({popup,data:{entity:company,journalId}});window.TT_ACCOUNTING_DESK?.refreshAttention?.();
      }catch(e){popup?.close();message.textContent=e.message;[...form.elements].forEach(el=>el.disabled=false);}finally{busy=false;host.dataset.busy='0';}
    };
    const history=q('[data-history]',body);history.innerHTML=(data.generalExpenses||[]).map(r=>`<article style="padding:12px;border-bottom:1px solid #cbd9e1"><b>${esc(r.paymentDate)} · ${esc(r.payee)} · ${money(r.amount)}</b><p>${esc(r.description)}</p><button class="btn" data-print="${esc(r.journalId)}">Print</button>${r.expenseType==='DIRECT'&&can('Edit')?` <button class="btn" data-edit="${esc(r.id)}">Edit</button>`:''}${can('Edit')?` <button class="btn" data-delete="${esc(r.id)}">Delete</button>`:''}</article>`).join('')||'<p>No expense payments.</p>';
    history.querySelectorAll('[data-print]').forEach(b=>b.onclick=()=>window.TT_ACCOUNTING_DESK?.printVoucher({data:{entity:company,journalId:b.dataset.print}}));history.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>open(b.dataset.edit));history.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(busy)return;const reason=prompt('Reason for deleting this expense (accounting entries will be reversed)?');if(reason===null)return;b.disabled=true;try{await request(company,{action:'delete_expense',collection:'generalExpenses',id:b.dataset.delete,reason});await open();window.TT_ACCOUNTING_DESK?.refreshAttention?.();}catch(e){q('[data-message]',body).textContent=e.message;b.disabled=false;}});
  }
  function bills(){generation++;const host=shell('Bills & Credit Cards');q('[data-body]',host).innerHTML='<p>Choose the bills you want to record or pay.</p><button class="btn primary" data-utility>Utilities</button> <button class="btn primary" data-card>Credit Cards</button>';q('[data-utility]',host).onclick=()=>{host.remove();openNative('utility','Utilities');};q('[data-card]',host).onclick=()=>{host.remove();openNative('card','Credit Cards');};}
  async function openNative(mode,title){if(mode==='general')return open();const token=++generation,company=entity(),ws=q('#ws-expenses'),ed=q('#expenseEditor');if(!ws||!ed)return;const host=shell(title);q('[data-body]',host).textContent='Loading…';ed.replaceChildren();ed.classList.add('tt-editor-stage');ed.hidden=false;ed.style.display='block';try{if(['salary','rent'].includes(mode))await window.TT_RENT_SALARY_UI.open(mode);else if(mode==='donations'){window.TT_EXPENSE_EDITOR?.claim(mode);await window.TT_DONATIONS_UI.refresh();}else await window.TT_EXPENSES_V1.open(mode);if(token!==generation||company!==entity()||!host.isConnected){window.TT_EXPENSE_EDITOR?.claim('');return;}document.querySelectorAll('.workspace.active').forEach(w=>w.classList.remove('active'));q('#entityHome').style.display='none';ws.classList.add('active');q('.panelHead h2',ws).textContent=title;q('.subGrid',ws).style.display='none';host.remove();document.dispatchEvent(new CustomEvent('tt:accounts-desk-form-opened',{detail:{title}}));}catch(e){q('[data-body]',host).textContent=e.message;}}
  window.TT_EXPENSE_DESK={open,bills,openNative};
})();
