(()=>{
'use strict';
const access=window.TT_ACCOUNT_ACCESS||{},api='../api/expenses_v1.php',q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],today=()=>new Date().toISOString().slice(0,10),thisMonth=()=>today().slice(0,7),entity=()=>localStorage.getItem('tt_accounts_entity')||'TTI',esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=v=>Number(v||0).toLocaleString('en-PK',{maximumFractionDigits:2});
const utilityTypes={ELECTRICITY:'Electricity',GAS:'Gas',WATER:'Water',INTERNET:'Internet',TELEPHONE_MOBILE:'Telephone / Mobile',OTHER_UTILITY:'Other Utility'};
const people={'FAM-SALMAN':'Salman','FAM-TALHA':'Talha','FAM-ABU':'Abu','FAM-TAYYAB':'Tayyab'};
const expenseAccounts={'6110':'Electricity','6120':'Gas','6130':'Water','6140':'Internet','6150':'Telephone & Mobile','6190':'Other Utilities','6400':'Repairs & Maintenance','6500':'Travel & Conveyance','6600':'Company Cars / Fuel','6700':'Professional Fees','6800':'Bank & Finance Charges','6900':'Office & General Administration'};
let data={utilityMasters:[],utilityPayments:[],creditCardMasters:[],creditCardStatements:[],reminders:[],paymentAccounts:[]},month=thisMonth(),mode='',editingUtility='',editingCard='',editingStatement='',allocationSeed=[];

function toast(message,ok=true){let e=q('#ttExpenseToast');if(!e){e=document.createElement('div');e.id='ttExpenseToast';e.style.cssText='position:fixed;left:50%;bottom:22px;transform:translateX(-50%);z-index:100020;padding:10px 14px;border-radius:9px;color:#fff;font:700 12px Arial;box-shadow:0 7px 22px #0003';document.body.appendChild(e)}e.style.background=ok?'#147a5b':'#a93a34';e.textContent=message;e.hidden=false;clearTimeout(e._t);e._t=setTimeout(()=>e.hidden=true,3500)}
function style(){if(q('#ttExpenseStyle'))return;const s=document.createElement('style');s.id='ttExpenseStyle';s.textContent='.tte{padding:18px}.tte-head{display:flex;align-items:center;gap:10px;margin-bottom:12px}.tte-head h3{margin:0}.tte-head .sp{flex:1}.tte-box{border:1px solid #dfe6ec;border-radius:12px;padding:13px;margin-bottom:12px;background:#fff}.tte-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px}.tte-grid label,.tte label{font-size:10px;font-weight:800;color:#657487}.tte input,.tte select,.tte textarea{width:100%;padding:8px;border:1px solid #d5dde5;border-radius:7px;background:#fff}.tte table{width:100%;border-collapse:collapse}.tte th,.tte td{padding:8px;border-bottom:1px solid #edf0f3;text-align:left;font-size:11px}.tte th{font-size:9px;text-transform:uppercase;color:#6d7987}.tte-actions{display:flex;gap:7px;justify-content:flex-end;margin-top:10px}.tte-note{padding:9px 11px;border-radius:8px;background:#f4f8fb;color:#526274;font-size:11px;margin:8px 0}.tte-warn{color:#8a5b00;font-weight:800}.tte-bad{color:#a93a34;font-weight:800}.tte-good{color:#147a5b;font-weight:800}.tte-pill{display:inline-block;padding:4px 7px;border-radius:999px;background:#eef3f7;font-size:10px;font-weight:800}.tte-row-actions{display:flex;gap:5px}.tte-alloc{display:grid;grid-template-columns:.8fr 1fr 1.2fr .65fr 34px;gap:7px;margin:7px 0}.tte-hidden{display:none!important}@media(max-width:900px){.tte-grid{grid-template-columns:1fr 1fr}.tte-alloc{grid-template-columns:1fr 1fr}}@media(max-width:560px){.tte{padding:12px}.tte-grid,.tte-alloc{grid-template-columns:1fr}.tte-head{flex-wrap:wrap}}';document.head.appendChild(s)}
async function req(body){const url=api+'?entity='+encodeURIComponent(entity())+'&month='+encodeURIComponent(month),opt={method:body?'POST':'GET',credentials:'same-origin',headers:{Accept:'application/json'}};if(body){opt.headers['Content-Type']='application/json';opt.body=JSON.stringify({csrf:access.csrf,entity:entity(),month,...body})}const r=await fetch(url,opt);let d={};try{d=await r.json()}catch{}if(!r.ok||!d.ok)throw new Error(d.error||'Expenses could not be updated.');return d}
async function refresh(){try{data=await req();render()}catch(e){toast(String(e.message||e),false)}}
async function post(body,message){try{data=await req(body);toast(message);render();return true}catch(e){toast(String(e.message||e),false);return false}}
function payOptions(){return (data.paymentAccounts||[]).map(x=>'<option value="'+esc(x.id)+'">'+esc(x.label)+' · '+esc(x.currency||'')+' '+fmt(x.bookBalance)+'</option>').join('')}
function typeOptions(selected='ELECTRICITY'){return Object.entries(utilityTypes).map(([v,n])=>'<option value="'+v+'" '+(v===selected?'selected':'')+'>'+esc(n)+'</option>').join('')}
function personOptions(selected='FAM-SALMAN'){return Object.entries(people).map(([v,n])=>'<option value="'+v+'" '+(v===selected?'selected':'')+'>'+esc(n)+' — Personal / Family</option>').join('')}
function expenseOptions(selected='6900'){return Object.entries(expenseAccounts).map(([v,n])=>'<option value="'+v+'" '+(v===selected?'selected':'')+'>'+v+' · '+esc(n)+'</option>').join('')}
function statusClass(v){return v==='Paid'?'tte-good':v==='Overdue'?'tte-bad':'tte-warn'}

function utilityView(){
 const edit=(data.utilityMasters||[]).find(x=>x.id===editingUtility)||{};
 const reminders=(data.reminders||[]).filter(x=>x.type==='UTILITY');
 return '<div class="tte"><div class="tte-head"><h3>Utilities & Bills</h3><span class="sp"></span><label>Reminder month <input id="evMonth" type="month" value="'+esc(month)+'"></label></div>'+
 '<div class="tte-box"><b>'+(editingUtility?'Edit':'Add')+' Recurring Utility Reminder</b><div class="tte-note">A reminder does not create an accounting entry. The expense is recorded only when payment is saved.</div><div class="tte-grid">'+
 '<label>Utility<select id="evUmType">'+typeOptions(edit.utilityType)+'</select></label><label>Location Type<select id="evUmLoc">'+['MILL','OFFICE','HOME','OTHER'].map(v=>'<option '+(v===(edit.location||'OFFICE')?'selected':'')+'>'+v+'</option>').join('')+'</select></label>'+
 '<label>Location Name<input id="evUmLocName" value="'+esc(edit.locationName||'')+'" placeholder="Karachi Office / TTI Rice Mill"></label><label>Provider<input id="evUmPayee" value="'+esc(edit.payee||'')+'"></label>'+
 '<label>Consumer / Account Reference<input id="evUmRef" value="'+esc(edit.accountReference||'')+'"></label><label>Monthly Due Day<input id="evUmDay" type="number" min="1" max="31" value="'+esc(edit.dueDay||10)+'"></label><label style="grid-column:span 2">Notes<input id="evUmNotes" value="'+esc(edit.notes||'')+'"></label></div><div class="tte-actions">'+(editingUtility?'<button class="btn" id="evUmCancel">Cancel</button>':'')+'<button class="btn green" id="evUmSave">'+(editingUtility?'Save Changes':'Add Reminder')+'</button></div></div>'+
 '<div class="tte-box"><b>Pay Utility / Bill</b><div class="tte-grid" style="margin-top:9px"><label>Recurring Reminder — optional<select id="evPayMaster"><option value="">Manual payment</option>'+(data.utilityMasters||[]).filter(x=>x.status==='Active').map(x=>'<option value="'+esc(x.id)+'">'+esc(x.utilityTypeName)+' · '+esc(x.locationName)+'</option>').join('')+'</select></label><label>Utility<select id="evPayType">'+typeOptions()+'</select></label><label>Location Type<select id="evPayLoc"><option>MILL</option><option selected>OFFICE</option><option>HOME</option><option>OTHER</option></select></label><label>Location Name<input id="evPayLocName"></label><label>Provider<input id="evPayee"></label><label>Bill Month<input id="evBillMonth" type="month" value="'+esc(month)+'"></label><label>Amount<input id="evPayAmount" type="number" min="0.01" step="0.01"></label><label>Payment Date<input id="evPayDate" type="date" value="'+today()+'"></label><label>Treatment<select id="evTreatment"><option value="BUSINESS_EXPENSE">Business Expense</option><option value="FAMILY_ALLOCATION">Personal / Family Allocation</option></select></label><label id="evPersonWrap" class="tte-hidden">Allocate To<select id="evPerson">'+personOptions()+'</select></label><label>Pay From<select id="evPayAccount">'+payOptions()+'</select></label><label>Bill / Transaction Reference<input id="evPayRef"></label><label style="grid-column:span 2">Notes<input id="evPayNotes"></label></div><div class="tte-actions"><button class="btn green" id="evPayUtility">Save Utility Payment</button></div></div>'+
 '<div class="tte-box"><b>Due Reminders</b><div class="tableWrap"><table><thead><tr><th>Utility</th><th>Due Date</th><th>Status</th><th></th></tr></thead><tbody>'+(reminders.length?reminders.map(x=>'<tr><td>'+esc(x.label)+'</td><td>'+esc(x.dueDate)+'</td><td class="'+statusClass(x.status)+'">'+esc(x.status)+'</td><td>'+(x.paid?'':'<button class="btn" data-pay-utility-master="'+esc(x.masterId)+'">Pay</button>')+'</td></tr>').join(''):'<tr><td colspan="4">No recurring utility reminders yet.</td></tr>')+'</tbody></table></div></div>'+
 '<div class="tte-box"><b>Recurring Masters</b><div class="tableWrap"><table><thead><tr><th>Utility</th><th>Location</th><th>Provider</th><th>Due Day</th><th>Status</th><th></th></tr></thead><tbody>'+((data.utilityMasters||[]).length?(data.utilityMasters||[]).map(x=>'<tr><td>'+esc(x.utilityTypeName)+'</td><td>'+esc(x.locationName)+'</td><td>'+esc(x.payee)+'</td><td>'+esc(x.dueDay)+'</td><td><span class="tte-pill">'+esc(x.status)+'</span></td><td><div class="tte-row-actions"><button class="btn" data-edit-utility="'+esc(x.id)+'">Edit</button>'+(x.status==='Active'?'<button class="btn danger" data-remove-utility="'+esc(x.id)+'">Remove</button>':'')+'</div></td></tr>').join(''):'<tr><td colspan="6">No utility masters added.</td></tr>')+'</tbody></table></div></div>'+
 '<div class="tte-box"><b>Utility Payment Ledger</b><div class="tableWrap"><table><thead><tr><th>Date</th><th>Bill Month</th><th>Utility</th><th>Location</th><th>Provider</th><th>Treatment</th><th>Amount</th><th>Journal</th></tr></thead><tbody>'+((data.utilityPayments||[]).length?(data.utilityPayments||[]).map(x=>'<tr><td>'+esc(x.paymentDate)+'</td><td>'+esc(x.billMonth)+'</td><td>'+esc(x.utilityTypeName)+'</td><td>'+esc(x.locationName)+'</td><td>'+esc(x.payee)+'</td><td>'+esc(x.accountingTreatment==='FAMILY_ALLOCATION'?'Personal / Family':'Business')+'</td><td>'+fmt(x.amount)+'</td><td>'+esc(x.journalId)+'</td></tr>').join(''):'<tr><td colspan="8">No utility payments recorded.</td></tr>')+'</tbody></table></div></div></div>';
}

function allocationRow(a={}){
 const kind=a.kind||'BUSINESS',account=a.expenseAccount||a.account||'6900',person=a.personAccount||a.account||'FAM-SALMAN';
 return '<div class="tte-alloc"><select class="evAllocKind"><option value="BUSINESS" '+(kind==='BUSINESS'?'selected':'')+'>Business Expense</option><option value="PERSONAL" '+(kind==='PERSONAL'?'selected':'')+'>Personal / Family</option></select><select class="evAllocAccount" data-business="'+esc(account)+'" data-person="'+esc(person)+'">'+(kind==='PERSONAL'?personOptions(person):expenseOptions(account))+'</select><input class="evAllocDetail" placeholder="Expense category / details" value="'+esc(a.detail||'')+'"><input class="evAllocAmount" type="number" min="0.01" step="0.01" value="'+esc(a.amount??'')+'" placeholder="Amount"><button class="xBtn evAllocRemove">×</button></div>';
}
function cardView(){
 const edit=(data.creditCardMasters||[]).find(x=>x.id===editingCard)||{},st=(data.creditCardStatements||[]).find(x=>x.id===editingStatement)||{};
 const active=(data.creditCardMasters||[]).filter(x=>x.status==='Active'),rows=allocationSeed.length?allocationSeed:(st.allocations||[]);
 return '<div class="tte"><div class="tte-head"><h3>Credit Cards</h3><span class="sp"></span><label>Month <input id="evMonth" type="month" value="'+esc(month)+'"></label></div>'+
 '<div class="tte-box"><b>'+(editingCard?'Edit':'Add')+' Credit Card Master</b><div class="tte-grid" style="margin-top:9px"><label>Card Name<input id="evCardName" value="'+esc(edit.cardName||'')+'" placeholder="Meezan Visa"></label><label>Card Holder<input id="evCardHolder" value="'+esc(edit.holder||'')+'"></label><label>Issuing Bank<input id="evCardBank" value="'+esc(edit.issuerBank||'')+'"></label><label>Last 4 Digits<input id="evCardLast4" maxlength="4" inputmode="numeric" value="'+esc(edit.last4||'')+'"></label><label>Normal Due Day<input id="evCardDay" type="number" min="1" max="31" value="'+esc(edit.dueDay||10)+'"></label><label style="grid-column:span 3">Notes<input id="evCardNotes" value="'+esc(edit.notes||'')+'"></label></div><div class="tte-actions">'+(editingCard?'<button class="btn" id="evCardCancel">Cancel</button>':'')+'<button class="btn green" id="evCardSave">'+(editingCard?'Save Changes':'Add Card')+'</button></div></div>'+
 '<div class="tte-box"><b>'+(editingStatement?'Edit':'Enter')+' Statement & Due-Date Reminder</b><div class="tte-note">Saving a statement creates the reminder only. No ledger entry is made until the statement is actually paid.</div><div class="tte-grid"><label>Credit Card<select id="evStatementCard">'+active.map(x=>'<option value="'+esc(x.id)+'" '+(x.id===st.cardMasterId?'selected':'')+'>'+esc(x.cardName)+' · '+esc(x.holder)+' · '+esc(x.last4)+'</option>').join('')+'</select></label><label>Statement Month<input id="evStatementMonth" type="month" value="'+esc(st.statementMonth||month)+'"></label><label>Statement Date<input id="evStatementDate" type="date" value="'+esc(st.statementDate||today())+'"></label><label>Due Date<input id="evDueDate" type="date" value="'+esc(st.dueDate||today())+'"></label><label>Statement Total<input id="evStatementTotal" type="number" min="0.01" step="0.01" value="'+esc(st.total??'')+'"></label><label style="grid-column:span 3">Notes<input id="evStatementNotes" value="'+esc(st.notes||'')+'"></label></div><div class="tte-note">Allocate the full statement. Personal amounts go directly to the selected personal ledger.</div><div id="evAllocRows">'+(rows.length?rows.map(allocationRow).join(''):allocationRow()+allocationRow())+'</div><div class="tte-actions"><span id="evAllocBalance" class="tte-warn" style="margin-right:auto"></span><button class="btn" id="evAddAllocation">+ Add Allocation</button>'+(editingStatement?'<button class="btn" id="evStatementCancel">Cancel</button>':'')+'<button class="btn green" id="evStatementSave">Save Reminder</button></div></div>'+
 '<div class="tte-box"><b>Statements & Payment Reminders</b><div class="tableWrap"><table><thead><tr><th>Card</th><th>Month</th><th>Due Date</th><th>Total</th><th>Status</th><th>Journal</th><th></th></tr></thead><tbody>'+((data.creditCardStatements||[]).length?(data.creditCardStatements||[]).map(x=>'<tr><td>'+esc(x.cardName)+' · '+esc(x.last4)+'</td><td>'+esc(x.statementMonth)+'</td><td>'+esc(x.dueDate)+'</td><td>'+fmt(x.total)+'</td><td class="'+statusClass(x.status==='Pending'&&x.dueDate<today()?'Overdue':x.status)+'">'+esc(x.status==='Pending'&&x.dueDate<today()?'Overdue':x.status)+'</td><td>'+esc(x.journalId||'—')+'</td><td><div class="tte-row-actions">'+(x.status==='Pending'?'<button class="btn" data-edit-statement="'+esc(x.id)+'">Edit</button><button class="btn green" data-pay-statement="'+esc(x.id)+'">Pay</button>':'')+'</div></td></tr>').join(''):'<tr><td colspan="7">No statements recorded.</td></tr>')+'</tbody></table></div></div>'+
 '<div class="tte-box"><b>Credit Card Masters</b><div class="tableWrap"><table><thead><tr><th>Card</th><th>Holder</th><th>Issuer</th><th>Last 4</th><th>Due Day</th><th>Status</th><th></th></tr></thead><tbody>'+((data.creditCardMasters||[]).length?(data.creditCardMasters||[]).map(x=>'<tr><td>'+esc(x.cardName)+'</td><td>'+esc(x.holder)+'</td><td>'+esc(x.issuerBank)+'</td><td>'+esc(x.last4)+'</td><td>'+esc(x.dueDay)+'</td><td><span class="tte-pill">'+esc(x.status)+'</span></td><td><div class="tte-row-actions"><button class="btn" data-edit-card="'+esc(x.id)+'">Edit</button>'+(x.status==='Active'?'<button class="btn danger" data-remove-card="'+esc(x.id)+'">Remove</button>':'')+'</div></td></tr>').join(''):'<tr><td colspan="7">Add a credit card before entering a statement.</td></tr>')+'</tbody></table></div></div></div>';
}

function render(){style();const ed=q('#expenseEditor');if(!ed)return;ed.innerHTML=mode==='card'?cardView():utilityView();bindCommon();mode==='card'?bindCard():bindUtility();ed.scrollIntoView({block:'start'})}
function bindCommon(){q('#evMonth').onchange=async e=>{month=e.target.value||thisMonth();await refresh()}}
function bindUtility(){
 q('#evUmSave').onclick=()=>post({action:'save_utility_master',id:editingUtility,utilityType:q('#evUmType').value,location:q('#evUmLoc').value,locationName:q('#evUmLocName').value,payee:q('#evUmPayee').value,accountReference:q('#evUmRef').value,dueDay:q('#evUmDay').value,notes:q('#evUmNotes').value},editingUtility?'Utility reminder updated.':'Utility reminder added.').then(ok=>{if(ok)editingUtility=''});
 if(q('#evUmCancel'))q('#evUmCancel').onclick=()=>{editingUtility='';render()};
 qa('[data-edit-utility]').forEach(b=>b.onclick=()=>{editingUtility=b.dataset.editUtility;render()});
 qa('[data-remove-utility]').forEach(b=>b.onclick=async()=>{if(confirm('Remove this recurring reminder? Historical payments will remain.'))await post({action:'deactivate_utility_master',id:b.dataset.removeUtility},'Utility reminder removed.')});
 const syncTreatment=()=>{const personal=q('#evTreatment').value==='FAMILY_ALLOCATION';q('#evPersonWrap').classList.toggle('tte-hidden',!personal)};
 q('#evTreatment').onchange=syncTreatment;q('#evPayLoc').onchange=()=>{if(q('#evPayLoc').value==='HOME')q('#evTreatment').value='FAMILY_ALLOCATION';syncTreatment()};
 const fill=id=>{const m=(data.utilityMasters||[]).find(x=>x.id===id);if(!m)return;q('#evPayMaster').value=id;q('#evPayType').value=m.utilityType;q('#evPayLoc').value=m.location;q('#evPayLocName').value=m.locationName;q('#evPayee').value=m.payee;if(m.location==='HOME')q('#evTreatment').value='FAMILY_ALLOCATION';syncTreatment()};
 q('#evPayMaster').onchange=e=>fill(e.target.value);qa('[data-pay-utility-master]').forEach(b=>b.onclick=()=>{fill(b.dataset.payUtilityMaster);q('#evPayAmount').focus()});
 q('#evPayUtility').onclick=()=>post({action:'pay_utility',utilityMasterId:q('#evPayMaster').value,utilityType:q('#evPayType').value,location:q('#evPayLoc').value,locationName:q('#evPayLocName').value,payee:q('#evPayee').value,billMonth:q('#evBillMonth').value,amount:q('#evPayAmount').value,paymentDate:q('#evPayDate').value,accountingTreatment:q('#evTreatment').value,personAccount:q('#evPerson')?.value||'',paymentAccountId:q('#evPayAccount').value,reference:q('#evPayRef').value,notes:q('#evPayNotes').value},'Utility payment posted.');
 syncTreatment();
}
function allocationData(){return qa('.tte-alloc').map(r=>{const kind=r.querySelector('.evAllocKind').value,account=r.querySelector('.evAllocAccount').value;return{kind,expenseAccount:kind==='BUSINESS'?account:'',personAccount:kind==='PERSONAL'?account:'',detail:r.querySelector('.evAllocDetail').value,amount:r.querySelector('.evAllocAmount').value}})}
function calcAllocation(){const total=Number(q('#evStatementTotal')?.value||0),allocated=qa('.evAllocAmount').reduce((s,x)=>s+Number(x.value||0),0),balance=total-allocated,e=q('#evAllocBalance');if(!e)return;e.textContent='Unallocated: '+fmt(balance);e.className=Math.abs(balance)<.005&&total>0?'tte-good':'tte-warn'}
function bindAllocationRow(r){const kind=r.querySelector('.evAllocKind'),account=r.querySelector('.evAllocAccount'),remove=r.querySelector('.evAllocRemove');kind.onchange=()=>{account.innerHTML=kind.value==='PERSONAL'?personOptions(account.dataset.person||'FAM-SALMAN'):expenseOptions(account.dataset.business||'6900');calcAllocation()};account.onchange=()=>{if(kind.value==='PERSONAL')account.dataset.person=account.value;else account.dataset.business=account.value};r.querySelector('.evAllocAmount').oninput=calcAllocation;remove.onclick=()=>{r.remove();calcAllocation()}}
function bindCard(){
 q('#evCardSave').onclick=()=>post({action:'save_card_master',id:editingCard,cardName:q('#evCardName').value,holder:q('#evCardHolder').value,issuerBank:q('#evCardBank').value,last4:q('#evCardLast4').value,dueDay:q('#evCardDay').value,notes:q('#evCardNotes').value},editingCard?'Credit card updated.':'Credit card added.').then(ok=>{if(ok)editingCard=''});
 if(q('#evCardCancel'))q('#evCardCancel').onclick=()=>{editingCard='';render()};qa('[data-edit-card]').forEach(b=>b.onclick=()=>{editingCard=b.dataset.editCard;render()});qa('[data-remove-card]').forEach(b=>b.onclick=async()=>{if(confirm('Remove this card? Paid statement history will remain.'))await post({action:'deactivate_card_master',id:b.dataset.removeCard},'Credit card removed.')});
 qa('.tte-alloc').forEach(bindAllocationRow);q('#evAddAllocation').onclick=()=>{q('#evAllocRows').insertAdjacentHTML('beforeend',allocationRow());bindAllocationRow(q('#evAllocRows').lastElementChild);calcAllocation()};q('#evStatementTotal').oninput=calcAllocation;
 q('#evStatementSave').onclick=async()=>{const total=Number(q('#evStatementTotal').value||0),allocated=allocationData().reduce((s,x)=>s+Number(x.amount||0),0);if(total<=0||Math.abs(total-allocated)>.005){toast('Allocate the complete statement total before saving.',false);return}const ok=await post({action:'save_card_statement',id:editingStatement,cardMasterId:q('#evStatementCard').value,statementMonth:q('#evStatementMonth').value,statementDate:q('#evStatementDate').value,dueDate:q('#evDueDate').value,total,allocations:allocationData(),notes:q('#evStatementNotes').value},'Statement reminder saved. No ledger entry was created.');if(ok){editingStatement='';allocationSeed=[]}};
 if(q('#evStatementCancel'))q('#evStatementCancel').onclick=()=>{editingStatement='';allocationSeed=[];render()};
 qa('[data-edit-statement]').forEach(b=>b.onclick=()=>{editingStatement=b.dataset.editStatement;allocationSeed=[];render()});
 qa('[data-pay-statement]').forEach(b=>b.onclick=async()=>{const st=(data.creditCardStatements||[]).find(x=>x.id===b.dataset.payStatement);if(!st)return;const accounts=(data.paymentAccounts||[]);if(!accounts.length){toast('Enable a company bank or cash account for payments first.',false);return}const paymentDate=prompt('Payment date (YYYY-MM-DD)',today());if(!paymentDate)return;const labels=accounts.map((x,i)=>(i+1)+'. '+x.label).join('\n'),choice=prompt('Pay from:\n'+labels,'1'),selected=accounts[Number(choice)-1];if(!selected){toast('Select a valid payment account number.',false);return}if(confirm('Post full payment of '+fmt(st.total)+' for '+st.cardName+'?'))await post({action:'pay_card_statement',statementId:st.id,paymentDate,paymentAccountId:selected.id},'Credit-card payment posted.')});
 calcAllocation();
}

async function open(next){mode=next;editingUtility='';editingCard='';editingStatement='';allocationSeed=[];month=thisMonth();await refresh()}
function install(){style();const utility=q('[data-expense="utility"]'),card=q('[data-expense="card"]');if(utility)utility.onclick=()=>open('utility');if(card)card.onclick=()=>open('card');qa('.entityBtn').forEach(b=>b.addEventListener('click',()=>{if(mode)setTimeout(refresh,0)}))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();