(()=>{
'use strict';
const access=window.TT_ACCOUNT_ACCESS||{},api='../api/expenses_v1.php',q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],today=()=>new Date().toISOString().slice(0,10),thisMonth=()=>today().slice(0,7),entity=()=>localStorage.getItem('tt_accounts_entity')||'TTI',esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=v=>Number(v||0).toLocaleString('en-PK',{maximumFractionDigits:2});
const utilityTypes={ELECTRICITY:'Electricity',GAS:'Gas',WATER:'Water',INTERNET:'Internet',TELEPHONE_MOBILE:'Telephone / Mobile',CLUB:'Club Bill',OTHER_UTILITY:'Other Utility'};
const people={'FAM-SALMAN':'Salman','FAM-TALHA':'Talha','FAM-ABU':'Abu','FAM-TAYYAB':'Tayyab'};
const reimbursementPeople={'REIMB-SALMAN':'Salman','REIMB-TALHA':'Talha','REIMB-ABU':'Abu','REIMB-TAYYAB':'Tayyab'};
const expenseAccounts={'6110':'Electricity','6120':'Gas','6130':'Water','6140':'Internet','6150':'Telephone & Mobile','6190':'Other Utilities','6400':'Repairs & Maintenance','6500':'Travel & Conveyance','6600':'Company Cars / Fuel','6700':'Professional Fees','6800':'Bank & Finance Charges','6900':'Office & General Administration'};
let data={utilityMasters:[],utilityPayments:[],creditCardMasters:[],creditCardStatements:[],reimbursements:[],generalExpenses:[],reminders:[],paymentAccounts:[]},month=thisMonth(),mode='',editingUtility='',editingCard='',editingStatement='',settlingReimbursement='',allocationSeed=[],busy=false,pendingRequests={},utilityFormOpen=false,cardFormOpen=false,statementFormOpen=false,editingUtilityPayment='';
const postingActions=new Set(['amend_utility','pay_utility','capture_reimbursement','settle_reimbursement','pay_general_expense','pay_card_statement','save_card_statement']);
function requestKey(prefix){return globalThis.crypto?.randomUUID?.()||(prefix+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2))}

function toast(message,ok=true){let e=q('#ttExpenseToast');if(!e){e=document.createElement('div');e.id='ttExpenseToast';e.style.cssText='position:fixed;left:50%;bottom:22px;transform:translateX(-50%);z-index:100020;padding:10px 14px;border-radius:9px;color:#fff;font:700 12px Arial;box-shadow:0 7px 22px #0003';document.body.appendChild(e)}e.style.background=ok?'#147a5b':'#a93a34';e.textContent=message;e.hidden=false;clearTimeout(e._t);e._t=setTimeout(()=>e.hidden=true,3500)}
function style(){if(q('#ttExpenseStyle'))return;const s=document.createElement('style');s.id='ttExpenseStyle';s.textContent='.tte{padding:18px}.tte-head{display:flex;align-items:center;gap:10px;margin-bottom:12px}.tte-head h3{margin:0}.tte-head .sp{flex:1}.tte-box{border:1px solid #dfe6ec;border-radius:12px;padding:13px;margin-bottom:12px;background:#fff}.tte-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px}.tte-grid label,.tte label{font-size:10px;font-weight:800;color:#657487}.tte input,.tte select,.tte textarea{width:100%;padding:8px;border:1px solid #d5dde5;border-radius:7px;background:#fff}.tte table{width:100%;border-collapse:collapse}.tte th,.tte td{padding:8px;border-bottom:1px solid #edf0f3;text-align:left;font-size:11px}.tte th{font-size:9px;text-transform:uppercase;color:#6d7987}.tte-actions{display:flex;gap:7px;justify-content:flex-end;margin-top:10px}.tte-note{padding:9px 11px;border-radius:8px;background:#f4f8fb;color:#526274;font-size:11px;margin:8px 0}.tte-warn{color:#8a5b00;font-weight:800}.tte-bad{color:#a93a34;font-weight:800}.tte-good{color:#147a5b;font-weight:800}.tte-pill{display:inline-block;padding:4px 7px;border-radius:999px;background:#eef3f7;font-size:10px;font-weight:800}.tte-row-actions{display:flex;gap:5px}.tte-alloc{display:grid;grid-template-columns:.8fr 1fr 1.2fr .65fr 34px;gap:7px;margin:7px 0}.tte-hidden{display:none!important}@media(max-width:900px){.tte-grid{grid-template-columns:1fr 1fr}.tte-alloc{grid-template-columns:1fr 1fr}}@media(max-width:560px){.tte{padding:12px}.tte-grid,.tte-alloc{grid-template-columns:1fr}.tte-head{flex-wrap:wrap}}';document.head.appendChild(s)}
async function req(body){const url=api+'?entity='+encodeURIComponent(entity())+'&month='+encodeURIComponent(month),opt={method:body?'POST':'GET',credentials:'same-origin',headers:{Accept:'application/json'}};if(body){opt.headers['Content-Type']='application/json';opt.body=JSON.stringify({csrf:access.csrf,entity:entity(),month,...body})}const r=await fetch(url,opt);let d={};try{d=await r.json()}catch{}if(!r.ok||!d.ok)throw new Error(d.error||'Expenses could not be updated.');return d}
async function refresh(){const token=window.TT_EXPENSE_EDITOR?.token();try{const result=await req();if(window.TT_EXPENSE_EDITOR&&!window.TT_EXPENSE_EDITOR.current(mode,token))return;data=result;render()}catch(e){toast(String(e.message||e),false)}}
async function post(body,message){if(busy)return false;const token=window.TT_EXPENSE_EDITOR?.token();try{const id={amend_utility:'evPayAccount',pay_utility:'evPayAccount',settle_reimbursement:'evReimbPayAccount',pay_general_expense:'evGeneralPayAccount',pay_card_statement:'evCardPayAccount'}[body.action];if(id)body={...body,...window.TT_BANK_PAYMENT_DETAILS?.read(id,body.paymentDate||body.settlementDate)};}catch(error){toast(error.message,false);return false;}let pending=null;if(postingActions.has(body.action)){let signature=JSON.stringify(body);pending=pendingRequests[body.action];if(!pending||pending.signature!==signature)pending=pendingRequests[body.action]={signature,key:requestKey(body.action)};body={...body,requestKey:pending.key}}try{busy=true;const result=await req(body);if(pending)delete pendingRequests[body.action];toast(message);if(window.TT_EXPENSE_EDITOR&&!window.TT_EXPENSE_EDITOR.current(mode,token))return false;data=result;render();return true}catch(e){toast(String(e.message||e),false);return false}finally{busy=false}}
function payOptions(){return (data.paymentAccounts||[]).map(x=>'<option value="'+esc(x.id)+'">'+esc(x.label)+' · '+esc(x.currency||'')+' '+fmt(x.bookBalance)+'</option>').join('')}
function typeOptions(selected='ELECTRICITY'){return Object.entries(utilityTypes).map(([v,n])=>'<option value="'+v+'" '+(v===selected?'selected':'')+'>'+esc(n)+'</option>').join('')}
function personOptions(selected='FAM-SALMAN'){return Object.entries(people).map(([v,n])=>'<option value="'+v+'" '+(v===selected?'selected':'')+'>'+esc(n)+' — Personal / Family</option>').join('')}
function reimbursementPersonOptions(selected='REIMB-SALMAN'){return Object.entries(reimbursementPeople).map(([v,n])=>'<option value="'+v+'" '+(v===selected?'selected':'')+'>'+esc(n)+'</option>').join('')}
function expenseOptions(selected='6900'){return Object.entries(expenseAccounts).map(([v,n])=>'<option value="'+v+'" '+(v===selected?'selected':'')+'>'+v+' · '+esc(n)+'</option>').join('')}
function statusClass(v){return v==='Paid'?'tte-good':v==='Overdue'?'tte-bad':'tte-warn'}

function locationOptions(selected=''){
 const rows=data.locations||[],offices=rows.filter(x=>x.location==='OFFICE');const fallback=offices.length===1?offices[0].id:(rows.length===1?rows[0].id:'');
 selected=rows.some(x=>x.id===selected)?selected:(rows.find(x=>x.name.toUpperCase()===String(selected).toUpperCase())?.id||fallback);
 return '<option value="">Select company location</option>'+rows.map(x=>'<option value="'+esc(x.id)+'" '+(x.id===selected?'selected':'')+'>'+esc(x.name)+'</option>').join('');
}
function selectedLocation(id){return (data.locations||[]).find(x=>x.id===q('#'+id)?.value)}
function utilityView(){
 const edit=(data.utilityMasters||[]).find(x=>x.id===editingUtility)||{};
 const reminders=(data.reminders||[]).filter(x=>x.type==='UTILITY');
 return '<div class="tte"><div class="tte-head"><h3>Utilities & Bills</h3><span class="sp"></span><button class="btn" id="evAddUtility">+ Utility Bill</button><label>Reminder month <input id="evMonth" type="month" value="'+esc(month)+'"></label></div>'+
 (utilityFormOpen?'<div class="tte-box" id="evUtilityForm"><b>'+(editingUtility?'Edit':'Add')+' Recurring Utility Reminder</b><div class="tte-note">A reminder does not create an accounting entry. The expense is recorded only when payment is saved.</div><div class="tte-grid">'+
 '<label>Utility<select id="evUmType">'+typeOptions(edit.utilityType)+'</select></label><label>Location Name<select id="evUmLocName">'+locationOptions(edit.locationId||edit.locationName)+'</select></label><input id="evUmLoc" type="hidden" value="'+esc(edit.location||'OFFICE')+'">'+
 '<label>Provider<input id="evUmPayee" value="'+esc(edit.payee||'')+'"></label>'+
 '<label>Remind days before due date<input id="evUmLead" type="number" min="1" max="31" value="'+esc(edit.remindDays||7)+'"></label><label>Consumer / Account Reference<input id="evUmRef" value="'+esc(edit.accountReference||'')+'"></label><label>Monthly Due Day<input id="evUmDay" type="number" min="1" max="31" value="'+esc(edit.dueDay||10)+'"></label><label style="grid-column:span 2">Notes<input id="evUmNotes" value="'+esc(edit.notes||'')+'"></label></div><div class="tte-actions">'+'<button class="btn" id="evUmCancel">Cancel</button>'+'<button class="btn green" id="evUmSave">'+(editingUtility?'Save Changes':'Add Reminder')+'</button></div></div>':'')+
 '<div class="tte-box"><b>Pay Utility / Bill</b><div class="tte-grid" style="margin-top:9px"><label>Recurring Reminder — optional<select id="evPayMaster"><option value="">Manual payment</option>'+(data.utilityMasters||[]).filter(x=>x.status==='Active').map(x=>'<option value="'+esc(x.id)+'">'+esc(x.utilityTypeName)+' · '+esc(x.locationName)+'</option>').join('')+'</select></label><label>Utility<select id="evPayType">'+typeOptions()+'</select></label><input id="evPayLoc" type="hidden" value="OFFICE"><label>Location Name<select id="evPayLocName">'+locationOptions()+'</select></label><label>Provider<input id="evPayee"></label><label>Bill Month<input id="evBillMonth" type="month" value="'+esc(month)+'"></label><label>Amount<input id="evPayAmount" type="number" min="0.01" step="0.01"></label><label>Payment Date<input id="evPayDate" type="date" value="'+today()+'"></label><label>Treatment<select id="evTreatment"><option value="BUSINESS_EXPENSE">Business Expense</option><option value="FAMILY_ALLOCATION">Personal / Family Allocation</option></select></label><label id="evPersonWrap" class="tte-hidden">Allocate To<select id="evPerson">'+personOptions()+'</select></label><label>Pay From<select id="evPayAccount">'+payOptions()+'</select></label><label>Bill / Transaction Reference<input id="evPayRef"></label><div id="evMeterPeriod" class="tte-grid" style="grid-column:1/-1" hidden><label>Previous Reading Date<input id="evReadFrom" type="date"></label><label>Current Reading Date<input id="evReadTo" type="date"></label><label>Previous Meter Reading<input id="evPreviousReading" type="number" min="0" step="0.001"></label><label>Current Meter Reading<input id="evCurrentReading" type="number" min="0" step="0.001"></label></div><label style="grid-column:span 2">Notes<input id="evPayNotes"></label></div><div class="tte-actions"><button class="btn green" id="evPayUtility">Save Utility Payment</button></div></div>'+
 '<div class="tte-box"><b>Due Reminders</b><div class="tableWrap"><table><thead><tr><th>Utility</th><th>Due Date</th><th>Status</th><th></th></tr></thead><tbody>'+(reminders.length?reminders.map(x=>'<tr><td>'+esc(x.label)+'</td><td>'+esc(x.dueDate)+'</td><td class="'+statusClass(x.status)+'">'+esc(x.status)+'</td><td>'+(x.paid?'':'<button class="btn" data-pay-utility-master="'+esc(x.masterId)+'">Pay</button>')+'</td></tr>').join(''):'<tr><td colspan="4">No recurring utility reminders yet.</td></tr>')+'</tbody></table></div></div>'+
 '<div class="tte-box"><b>Recurring Masters</b><div class="tableWrap"><table><thead><tr><th>Utility</th><th>Location</th><th>Provider</th><th>Due Day</th><th>Status</th><th></th></tr></thead><tbody>'+((data.utilityMasters||[]).length?(data.utilityMasters||[]).map(x=>'<tr><td>'+esc(x.utilityTypeName)+'</td><td>'+esc(x.locationName)+'</td><td>'+esc(x.payee)+'</td><td>'+esc(x.dueDay)+'</td><td><span class="tte-pill">'+esc(x.status)+'</span></td><td><div class="tte-row-actions"><button class="btn" data-edit-utility="'+esc(x.id)+'">Edit</button>'+(x.status==='Active'?'<button class="btn danger" data-remove-utility="'+esc(x.id)+'">Remove</button>':'')+'</div></td></tr>').join(''):'<tr><td colspan="6">No utility masters added.</td></tr>')+'</tbody></table></div></div>'+
 '<div class="tte-box"><b>Utility Payment Ledger</b><div class="tableWrap"><table><thead><tr><th>Date</th><th>Bill Month</th><th>Utility</th><th>Location</th><th>Provider</th><th>Treatment</th><th>Amount</th><th>Journal</th></tr></thead><tbody>'+((data.utilityPayments||[]).length?(data.utilityPayments||[]).map(x=>'<tr><td>'+esc(x.paymentDate)+'</td><td>'+esc(x.billMonth)+'</td><td>'+esc(x.utilityTypeName)+'</td><td>'+esc(x.locationName)+'</td><td>'+esc(x.payee)+'</td><td>'+esc(x.accountingTreatment==='FAMILY_ALLOCATION'?'Personal / Family':'Business')+'</td><td>'+fmt(x.amount)+'</td><td>'+esc(x.journalId)+'</td></tr>').join(''):'<tr><td colspan="8">No utility payments recorded.</td></tr>')+'</tbody></table></div></div></div>';
}

function allocationRow(a={}){
 const kind=a.kind||'BUSINESS',account=a.expenseAccount||a.account||'6900',person=a.personAccount||a.account||'FAM-SALMAN';
 return '<div class="tte-alloc"><select class="evAllocKind"><option value="BUSINESS" '+(kind==='BUSINESS'?'selected':'')+'>Business Expense</option><option value="PERSONAL" '+(kind==='PERSONAL'?'selected':'')+'>Personal / Family</option></select><select class="evAllocAccount" data-business="'+esc(account)+'" data-person="'+esc(person)+'">'+(kind==='PERSONAL'?personOptions(person):expenseOptions(account))+'</select><input class="evAllocDetail" placeholder="Expense category / details" value="'+esc(a.detail||'')+'"><input class="evAllocAmount" type="number" min="0.01" step="0.01" value="'+esc(a.amount??'')+'" placeholder="Amount"><button class="xBtn evAllocRemove">×</button></div>';
}
function cardView(){
 const edit=(data.creditCardMasters||[]).find(x=>x.id===editingCard)||{},st=(data.creditCardStatements||[]).find(x=>x.id===editingStatement)||{};
 const cardReminders=(data.reminders||[]).filter(x=>x.type==='CREDIT_CARD');
 const active=(data.creditCardMasters||[]).filter(x=>x.status==='Active'),rows=allocationSeed.length?allocationSeed:(st.allocations||[]);
 return '<div class="tte"><div class="tte-head"><h3>Credit Cards</h3><span class="sp"></span><button class="btn" id="evAddCard">+ Credit Card</button><button class="btn" id="evAddStatement">+ Statement</button><label>Month <input id="evMonth" type="month" value="'+esc(month)+'"></label></div>'+
 (cardFormOpen?'<div class="tte-box" id="evCardForm"><b>'+(editingCard?'Edit':'Add')+' Credit Card Master</b><div class="tte-grid" style="margin-top:9px"><label>Card Name<input id="evCardName" value="'+esc(edit.cardName||'')+'" placeholder="Meezan Visa"></label><label>Card Holder<input id="evCardHolder" value="'+esc(edit.holder||'')+'"></label><label>Issuing Bank<input id="evCardBank" value="'+esc(edit.issuerBank||'')+'"></label><label>Last 4 Digits<input id="evCardLast4" maxlength="4" inputmode="numeric" value="'+esc(edit.last4||'')+'"></label><label>Remind days before due date<input id="evCardLead" type="number" min="1" max="31" value="'+esc(edit.remindDays||7)+'"></label><label>Normal Due Day<input id="evCardDay" type="number" min="1" max="31" value="'+esc(edit.dueDay||10)+'"></label><label style="grid-column:span 3">Notes<input id="evCardNotes" value="'+esc(edit.notes||'')+'"></label></div><div class="tte-actions">'+'<button class="btn" id="evCardCancel">Cancel</button>'+'<button class="btn green" id="evCardSave">'+(editingCard?'Save Changes':'Add Card')+'</button></div></div>':'')+
 (statementFormOpen?'<div class="tte-box" id="evStatementForm"><b>'+(editingStatement?'Edit':'Enter')+' Statement & Due-Date Reminder</b><div class="tte-note">Posting a statement books its allocations and the credit-card payable. Payment later clears that payable.</div><div class="tte-grid"><label>Credit Card<select id="evStatementCard">'+active.map(x=>'<option value="'+esc(x.id)+'" '+(x.id===st.cardMasterId?'selected':'')+'>'+esc(x.cardName)+' · '+esc(x.holder)+' · '+esc(x.last4)+'</option>').join('')+'</select></label><label>Statement Month<input id="evStatementMonth" type="month" value="'+esc(st.statementMonth||month)+'"></label><label>Statement Date<input id="evStatementDate" type="date" value="'+esc(st.statementDate||today())+'"></label><label>Due Date<input id="evDueDate" type="date" value="'+esc(st.dueDate||today())+'"></label><label>Statement Total<input id="evStatementTotal" type="number" min="0.01" step="0.01" value="'+esc(st.total??'')+'"></label><label style="grid-column:span 3">Notes<input id="evStatementNotes" value="'+esc(st.notes||'')+'"></label></div><div class="tte-note">Allocate the full statement. Personal amounts go directly to the selected personal ledger.</div><div id="evAllocRows">'+(rows.length?rows.map(allocationRow).join(''):allocationRow()+allocationRow())+'</div><div class="tte-actions"><span id="evAllocBalance" class="tte-warn" style="margin-right:auto"></span><button class="btn" id="evAddAllocation">+ Add Allocation</button>'+'<button class="btn" id="evStatementCancel">Cancel</button>'+'<button class="btn green" id="evStatementSave">Post Statement</button></div></div>':'')+
 '<div class="tte-box"><b>Monthly Reminders</b><table><tbody>'+cardReminders.map(x=>'<tr><td>'+esc(x.label)+'</td><td>'+esc(x.dueDate)+'</td><td>'+esc(x.status)+'</td></tr>').join('')+'</tbody></table></div>'+
 '<div class="tte-box"><b>Statements & Payment Reminders</b><div class="tableWrap"><table><thead><tr><th>Card</th><th>Month</th><th>Due Date</th><th>Total</th><th>Status</th><th>Journal</th><th></th></tr></thead><tbody>'+((data.creditCardStatements||[]).length?(data.creditCardStatements||[]).map(x=>'<tr><td>'+esc(x.cardName)+' · '+esc(x.last4)+'</td><td>'+esc(x.statementMonth)+'</td><td>'+esc(x.dueDate)+'</td><td>'+fmt(x.total)+'</td><td class="'+statusClass(x.status==='Pending'&&x.dueDate<today()?'Overdue':x.status)+'">'+esc(x.status==='Pending'&&x.dueDate<today()?'Overdue':x.status)+'</td><td>'+esc(x.journalId||'—')+'</td><td><div class="tte-row-actions">'+(x.status==='Pending'?'<button class="btn" data-edit-statement="'+esc(x.id)+'">Edit</button><button class="btn green" data-pay-statement="'+esc(x.id)+'">Pay</button>':'')+'</div></td></tr>').join(''):'<tr><td colspan="7">No statements recorded.</td></tr>')+'</tbody></table></div></div>'+
 '<div class="tte-box"><b>Credit Card Masters</b><div class="tableWrap"><table><thead><tr><th>Card</th><th>Holder</th><th>Issuer</th><th>Last 4</th><th>Due Day</th><th>Status</th><th></th></tr></thead><tbody>'+((data.creditCardMasters||[]).length?(data.creditCardMasters||[]).map(x=>'<tr><td>'+esc(x.cardName)+'</td><td>'+esc(x.holder)+'</td><td>'+esc(x.issuerBank)+'</td><td>'+esc(x.last4)+'</td><td>'+esc(x.dueDay)+'</td><td><span class="tte-pill">'+esc(x.status)+'</span></td><td><div class="tte-row-actions"><button class="btn" data-edit-card="'+esc(x.id)+'">Edit</button>'+(x.status==='Active'?'<button class="btn danger" data-remove-card="'+esc(x.id)+'">Remove</button>':'')+'</div></td></tr>').join(''):'<tr><td colspan="7">Add a credit card before entering a statement.</td></tr>')+'</tbody></table></div></div></div>';
}

function reimbursementView(){
 const settling=(data.reimbursements||[]).find(x=>x.id===settlingReimbursement);
 return '<div class="tte"><div class="tte-head"><h3>Expense Reimbursements</h3><span class="sp"></span><label>Month <input id="evMonth" type="month" value="'+esc(month)+'"></label></div>'+
 '<div class="tte-box"><b>Record a Business Expense Paid Personally</b><div class="tte-note">This records the business expense once and creates an amount payable to the person. Paying them later clears that payable; it does not record the expense again.</div><div class="tte-grid">'+
 '<label>Person<select id="evReimbPerson">'+reimbursementPersonOptions()+'</select></label><label>Expense Account<select id="evReimbAccount">'+expenseOptions()+'</select></label><label>Expense Date<input id="evReimbDate" type="date" value="'+today()+'"></label><label>Amount<input id="evReimbAmount" type="number" min="0.01" step="0.01"></label>'+
 '<label>Location<select id="evReimbLocation"><option>MILL</option><option selected>OFFICE</option><option>OTHER</option></select></label><label>Payee / Vendor<input id="evReimbPayee"></label><label>Reference<input id="evReimbRef" placeholder="Invoice / receipt no."></label><label>Description<input id="evReimbDescription"></label></div><div class="tte-actions"><button class="btn green" id="evCaptureReimbursement">Record Expense & Payable</button></div></div>'+
 (settling?'<div class="tte-box"><b>Settle '+esc(settling.personName)+'</b><div class="tte-note">Outstanding: '+fmt(settling.outstanding)+' from '+esc(settling.description)+'. Partial settlement is allowed.</div><div class="tte-grid"><label>Settlement Date<input id="evReimbSettleDate" type="date" value="'+today()+'"></label><label>Amount<input id="evReimbSettleAmount" type="number" min="0.01" max="'+esc(settling.outstanding)+'" step="0.01" value="'+esc(settling.outstanding)+'"></label><label>Pay From<select id="evReimbPayAccount">'+payOptions()+'</select></label><label>Payment Reference<input id="evReimbSettleRef"></label></div><div class="tte-actions"><button class="btn" id="evReimbSettleCancel">Cancel</button><button class="btn green" id="evSettleReimbursement">Post Settlement</button></div></div>':'')+
 '<div class="tte-box"><b>Reimbursement Ledger</b><div class="tableWrap"><table><thead><tr><th>Expense Date</th><th>Person</th><th>Expense / Payee</th><th>Location</th><th>Total</th><th>Settled</th><th>Outstanding</th><th>Status</th><th>Journals</th><th></th></tr></thead><tbody>'+((data.reimbursements||[]).length?(data.reimbursements||[]).map(x=>'<tr><td>'+esc(x.expenseDate)+'</td><td>'+esc(x.personName)+'</td><td>'+esc(x.expenseAccountName)+'<br>'+esc(x.payee)+' — '+esc(x.description)+'</td><td>'+esc(x.location)+'</td><td>'+fmt(x.amount)+'</td><td>'+fmt(x.settled)+'</td><td>'+fmt(x.outstanding)+'</td><td><span class="tte-pill">'+esc(x.status)+'</span></td><td>'+esc(x.captureJournalId)+(x.settlements||[]).map(s=>'<br>'+esc(s.journalId)).join('')+'</td><td>'+(Number(x.outstanding)>0?'<button class="btn green" data-settle-reimbursement="'+esc(x.id)+'">Settle</button>':'')+'</td></tr>').join(''):'<tr><td colspan="10">No reimbursements recorded.</td></tr>')+'</tbody></table></div></div></div>';
}
function generalView(){
 return '<div class="tte"><div class="tte-head"><h3>General Office / Mill Expenses</h3><span class="sp"></span><label>Month <input id="evMonth" type="month" value="'+esc(month)+'"></label></div>'+
 '<div class="tte-box"><b>Pay a Direct Business Expense</b><div class="tte-note">Use this only when the company pays now. If Salman, Talha, Abu or Tayyab paid personally, record it under Reimbursements instead.</div><div class="tte-grid">'+
 '<label>Expense Account<select id="evGeneralAccount">'+expenseOptions()+'</select></label><label>Location<select id="evGeneralLocation"><option>MILL</option><option selected>OFFICE</option><option>OTHER</option></select></label><label>Payment Date<input id="evGeneralDate" type="date" value="'+today()+'"></label><label>Amount<input id="evGeneralAmount" type="number" min="0.01" step="0.01"></label>'+
 '<label>Payee / Vendor<input id="evGeneralPayee"></label><label>Reference<input id="evGeneralRef" placeholder="Invoice / receipt no."></label><label>Pay From<select id="evGeneralPayAccount">'+payOptions()+'</select></label><label>Description<input id="evGeneralDescription"></label></div><div class="tte-actions"><button class="btn green" id="evPayGeneralExpense">Post Expense Payment</button></div></div>'+
 '<div class="tte-box"><b>General Expense Ledger</b><div class="tableWrap"><table><thead><tr><th>Date</th><th>Location</th><th>Expense</th><th>Payee / Description</th><th>Amount</th><th>Reference</th><th>Journal</th></tr></thead><tbody>'+((data.generalExpenses||[]).length?(data.generalExpenses||[]).map(x=>'<tr><td>'+esc(x.paymentDate)+'</td><td>'+esc(x.location)+'</td><td>'+esc(x.expenseAccountName)+'</td><td>'+esc(x.payee)+'<br>'+esc(x.description)+'</td><td>'+fmt(x.amount)+'</td><td>'+esc(x.reference||'—')+'</td><td>'+esc(x.journalId)+'</td></tr>').join(''):'<tr><td colspan="7">No general expenses recorded.</td></tr>')+'</tbody></table></div></div></div>';
}
function bindReimbursement(){
 q('#evCaptureReimbursement').onclick=()=>post({action:'capture_reimbursement',personAccount:q('#evReimbPerson').value,expenseAccount:q('#evReimbAccount').value,expenseDate:q('#evReimbDate').value,amount:q('#evReimbAmount').value,location:q('#evReimbLocation').value,payee:q('#evReimbPayee').value,reference:q('#evReimbRef').value,description:q('#evReimbDescription').value},'Expense recorded and reimbursement payable created.');
 qa('[data-settle-reimbursement]').forEach(b=>b.onclick=()=>{settlingReimbursement=b.dataset.settleReimbursement;render()});
 if(q('#evReimbSettleCancel'))q('#evReimbSettleCancel').onclick=()=>{settlingReimbursement='';render()};
 if(q('#evSettleReimbursement'))q('#evSettleReimbursement').onclick=()=>post({action:'settle_reimbursement',reimbursementId:settlingReimbursement,settlementDate:q('#evReimbSettleDate').value,amount:q('#evReimbSettleAmount').value,paymentAccountId:q('#evReimbPayAccount').value,reference:q('#evReimbSettleRef').value},'Reimbursement settlement posted.').then(ok=>{if(ok){settlingReimbursement='';render()}});
}
function bindGeneral(){
 q('#evPayGeneralExpense').onclick=()=>post({action:'pay_general_expense',expenseAccount:q('#evGeneralAccount').value,location:q('#evGeneralLocation').value,paymentDate:q('#evGeneralDate').value,amount:q('#evGeneralAmount').value,payee:q('#evGeneralPayee').value,reference:q('#evGeneralRef').value,paymentAccountId:q('#evGeneralPayAccount').value,description:q('#evGeneralDescription').value},'General expense payment posted.');
}

function canExpense(action){const p=access.permissions;if(access.super||p==='all')return true;if(!p)return false;const icon=Array.isArray(p)?p:(p.expenses||[]);const scoped=!Array.isArray(p)&&['entity-tti','entity-brm','entity-tg'].some(key=>Object.hasOwn(p,key));return icon.includes(action)&&(!scoped||(p['entity-'+entity().toLowerCase()]||[]).includes(action));}
function applyExpensePermissions(){qa('#expenseEditor button').forEach(button=>{const text=button.textContent.trim();let action=/^(Edit|Delete|Remove)/i.test(text)||button.matches('[data-edit-utility],[data-remove-utility],[data-edit-card],[data-remove-card],[data-edit-statement]')?'Edit':/^\+|^(Post|Pay|Save)/i.test(text)?'Create':'';if(button.id==='evUmSave')action=editingUtility?'Edit':'Create';if(button.id==='evCardSave')action=editingCard?'Edit':'Create';if(button.id==='evStatementSave')action=editingStatement?'Edit':'Create';if(button.id==='evPayUtility'&&editingUtilityPayment)action='Edit';if(action&&!canExpense(action))button.hidden=true;});}
function render(){if(window.TT_EXPENSE_EDITOR&&!window.TT_EXPENSE_EDITOR.current(mode))return;style();const ed=q('#expenseEditor');if(!ed)return;ed.innerHTML=mode==='card'?cardView():mode==='reimburse'?reimbursementView():mode==='general'?generalView():utilityView();bindCommon();if(mode==='card')bindCard();else if(mode==='reimburse')bindReimbursement();else if(mode==='general')bindGeneral();else bindUtility();bindExpenseRows();applyExpensePermissions();window.TT_FORM_VIEWPORT?.open?.(q('#evUtilityForm,#evCardForm,#evStatementForm')||ed)}
function bindCommon(){['evPayAccount','evReimbPayAccount','evGeneralPayAccount','evCardPayAccount'].forEach(id=>window.TT_BANK_PAYMENT_DETAILS?.mount(id,data.paymentAccounts||[]));q('#evMonth').onchange=async e=>{month=e.target.value||thisMonth();await refresh()}}
function bindUtility(){q('#evAddUtility').onclick=()=>{editingUtility='';utilityFormOpen=true;render()};
 if(q('#evUmSave'))q('#evUmSave').onclick=()=>post({action:'save_utility_master',id:editingUtility,utilityType:q('#evUmType').value,location:selectedLocation('evUmLocName')?.location||'OFFICE',locationId:q('#evUmLocName').value,locationName:selectedLocation('evUmLocName')?.name||'',payee:q('#evUmPayee').value,accountReference:q('#evUmRef').value,dueDay:q('#evUmDay').value,remindDays:q('#evUmLead').value,notes:q('#evUmNotes').value},editingUtility?'Utility reminder updated.':'Utility reminder added.').then(ok=>{if(ok){editingUtility='';utilityFormOpen=false;render()}});
 if(q('#evUmCancel'))q('#evUmCancel').onclick=()=>{editingUtility='';utilityFormOpen=false;render()};
 qa('[data-edit-utility]').forEach(b=>b.onclick=()=>{editingUtility=b.dataset.editUtility;utilityFormOpen=true;render()});
 qa('[data-remove-utility]').forEach(b=>b.onclick=async()=>{if(confirm('Remove this recurring reminder? Historical payments will remain.'))await post({action:'deactivate_utility_master',id:b.dataset.removeUtility},'Utility reminder removed.')});
 const syncTreatment=()=>{q('#evPayLoc').value=selectedLocation('evPayLocName')?.location||'OFFICE';q('#evMeterPeriod').hidden=!(q('#evPayLoc').value==='MILL'&&q('#evPayType').value==='ELECTRICITY');const businessOption=q('#evTreatment option[value="BUSINESS_EXPENSE"]');if(businessOption)businessOption.textContent=q('#evPayLoc').value==='MILL'?'Production Expense':'Business Expense';const personal=q('#evTreatment').value==='FAMILY_ALLOCATION';q('#evPersonWrap').classList.toggle('tte-hidden',!personal)};
 q('#evPayLocName').onchange=syncTreatment;q('#evPayType').onchange=syncTreatment;q('#evTreatment').onchange=syncTreatment;q('#evPayLoc').onchange=()=>{if(q('#evPayLoc').value==='HOME')q('#evTreatment').value='FAMILY_ALLOCATION';syncTreatment()};
 const fill=id=>{const m=(data.utilityMasters||[]).find(x=>x.id===id);if(!m)return;q('#evPayMaster').value=id;q('#evPayType').value=m.utilityType;q('#evPayLoc').value=m.location;q('#evPayLocName').value=m.locationId||(data.locations||[]).find(x=>x.name.toUpperCase()===String(m.locationName).toUpperCase())?.id||'';q('#evPayee').value=m.payee;if(m.location==='HOME')q('#evTreatment').value='FAMILY_ALLOCATION';syncTreatment()};
 q('#evPayMaster').onchange=e=>fill(e.target.value);qa('[data-pay-utility-master]').forEach(b=>b.onclick=()=>{fill(b.dataset.payUtilityMaster);q('#evPayAmount').focus()});
 q('#evPayUtility').onclick=()=>post({action:editingUtilityPayment?'amend_utility':'pay_utility',id:editingUtilityPayment,reason:editingUtilityPayment?(prompt('Reason for correcting this utility payment:')||''):'',utilityMasterId:q('#evPayMaster').value,utilityType:q('#evPayType').value,location:selectedLocation('evPayLocName')?.location||'OFFICE',locationId:q('#evPayLocName').value,locationName:selectedLocation('evPayLocName')?.name||'',payee:q('#evPayee').value,billMonth:q('#evBillMonth').value,amount:q('#evPayAmount').value,paymentDate:q('#evPayDate').value,accountingTreatment:q('#evTreatment').value,personAccount:q('#evPerson')?.value||'',paymentAccountId:q('#evPayAccount').value,reference:q('#evPayRef').value,...(selectedLocation('evPayLocName')?.location==='MILL'&&q('#evPayType').value==='ELECTRICITY'?{readFrom:q('#evReadFrom').value,readTo:q('#evReadTo').value,previousReading:q('#evPreviousReading').value,currentReading:q('#evCurrentReading').value}:{}),notes:q('#evPayNotes').value},editingUtilityPayment?'Utility payment corrected.':'Utility payment posted.').then(ok=>{if(ok){editingUtilityPayment='';render()}});
 syncTreatment();
}
function bindExpenseRows(){
 const sources={'Utility Payment Ledger':['utilityPayments',data.utilityPayments||[]],'General Expense Ledger':['generalExpenses',data.generalExpenses||[]],'Reimbursement Ledger':['reimbursements',data.reimbursements||[]],'Statements & Payment Reminders':['creditCardStatements',data.creditCardStatements||[]]};
 qa('.tte-box').forEach(box=>{const found=sources[box.querySelector(':scope > b')?.textContent];if(!found)return;const [collection,rows]=found;const head=box.querySelector('thead tr');if(head&&!head.querySelector('[data-expense-actions]')){const th=document.createElement('th');th.dataset.expenseActions='1';th.textContent='Actions';head.appendChild(th)}
 box.querySelectorAll('tbody tr').forEach((tr,index)=>{const row=rows[index];if(!row)return;const td=document.createElement('td');td.className='tte-row-actions';const journal=row.journalId||row.captureJournalId||row.statementJournalId;if(journal){const view=document.createElement('button');view.className='btn';view.textContent='View';view.onclick=()=>window.TT_ALL_LEDGERS?.showPost(journal);td.appendChild(view);const edit=document.createElement('button');edit.className='btn';edit.textContent='Edit';edit.onclick=()=>collection==='utilityPayments'?editUtilityPayment(row):window.TT_ALL_LEDGERS?.editPosting(journal);td.appendChild(edit)}const remove=document.createElement('button');remove.className='btn danger';remove.textContent='Delete';remove.onclick=()=>{const reason=prompt('Reason for deleting this expense? Its accounting entries will be reversed; history will remain.');if(reason===null)return;void post({action:'delete_expense',collection,id:row.id,reason},'Expense deleted and accounting entries reversed.')};td.appendChild(remove);tr.appendChild(td);});});
}
function editUtilityPayment(row){
 editingUtilityPayment=row.id;q('#evPayMaster').value=row.utilityMasterId||'';q('#evPayType').value=row.utilityType;q('#evPayLocName').value=row.locationId||(data.locations||[]).find(x=>x.name.toUpperCase()===String(row.locationName).toUpperCase())?.id||'';q('#evPayee').value=row.payee;q('#evBillMonth').value=row.billMonth;q('#evPayAmount').value=row.amount;q('#evPayDate').value=row.paymentDate;q('#evTreatment').value=row.accountingTreatment;if(q('#evPerson'))q('#evPerson').value=row.personAccount||'FAM-SALMAN';q('#evPayAccount').value=row.paymentAccountId;q('#evPayRef').value=row.reference||'';q('#evPayNotes').value=row.notes||'';for(const [id,key] of [['evReadFrom','readFrom'],['evReadTo','readTo'],['evPreviousReading','previousReading'],['evCurrentReading','currentReading']])q('#'+id).value=row[key]??'';q('#evPayLocName').dispatchEvent(new Event('change'));q('#evPayUtility').textContent='Save Utility Correction';window.TT_FORM_VIEWPORT?.open(q('#evPayUtility').closest('.tte-box'));
}
function allocationData(){return qa('.tte-alloc').map(r=>{const kind=r.querySelector('.evAllocKind').value,account=r.querySelector('.evAllocAccount').value;return{kind,expenseAccount:kind==='BUSINESS'?account:'',personAccount:kind==='PERSONAL'?account:'',detail:r.querySelector('.evAllocDetail').value,amount:r.querySelector('.evAllocAmount').value}})}
function calcAllocation(){const total=Number(q('#evStatementTotal')?.value||0),allocated=qa('.evAllocAmount').reduce((s,x)=>s+Number(x.value||0),0),balance=total-allocated,e=q('#evAllocBalance');if(!e)return;e.textContent='Unallocated: '+fmt(balance);e.className=Math.abs(balance)<.005&&total>0?'tte-good':'tte-warn'}
function bindAllocationRow(r){const kind=r.querySelector('.evAllocKind'),account=r.querySelector('.evAllocAccount'),remove=r.querySelector('.evAllocRemove');kind.onchange=()=>{account.innerHTML=kind.value==='PERSONAL'?personOptions(account.dataset.person||'FAM-SALMAN'):expenseOptions(account.dataset.business||'6900');calcAllocation()};account.onchange=()=>{if(kind.value==='PERSONAL')account.dataset.person=account.value;else account.dataset.business=account.value};r.querySelector('.evAllocAmount').oninput=calcAllocation;remove.onclick=()=>{r.remove();calcAllocation()}}
function bindCard(){q('#evAddCard').onclick=()=>{editingCard='';cardFormOpen=true;render()};q('#evAddStatement').onclick=()=>{editingStatement='';allocationSeed=[];statementFormOpen=true;render()};
 if(q('#evCardSave'))q('#evCardSave').onclick=()=>post({action:'save_card_master',id:editingCard,cardName:q('#evCardName').value,holder:q('#evCardHolder').value,issuerBank:q('#evCardBank').value,last4:q('#evCardLast4').value,dueDay:q('#evCardDay').value,remindDays:q('#evCardLead').value,notes:q('#evCardNotes').value},editingCard?'Credit card updated.':'Credit card added.').then(ok=>{if(ok){editingCard='';cardFormOpen=false;render()}});
 if(q('#evCardCancel'))q('#evCardCancel').onclick=()=>{editingCard='';cardFormOpen=false;render()};qa('[data-edit-card]').forEach(b=>b.onclick=()=>{editingCard=b.dataset.editCard;cardFormOpen=true;render()});qa('[data-remove-card]').forEach(b=>b.onclick=async()=>{if(confirm('Remove this card? Paid statement history will remain.'))await post({action:'deactivate_card_master',id:b.dataset.removeCard},'Credit card removed.')});
 qa('.tte-alloc').forEach(bindAllocationRow);if(q('#evAddAllocation'))q('#evAddAllocation').onclick=()=>{q('#evAllocRows').insertAdjacentHTML('beforeend',allocationRow());bindAllocationRow(q('#evAllocRows').lastElementChild);calcAllocation()};if(q('#evStatementTotal'))q('#evStatementTotal').oninput=calcAllocation;
 if(q('#evStatementSave'))q('#evStatementSave').onclick=async()=>{const total=Number(q('#evStatementTotal').value||0),allocated=allocationData().reduce((s,x)=>s+Number(x.amount||0),0);if(total<=0||Math.abs(total-allocated)>.005){toast('Allocate the complete statement total before saving.',false);return}const ok=await post({action:'save_card_statement',id:editingStatement,cardMasterId:q('#evStatementCard').value,statementMonth:q('#evStatementMonth').value,statementDate:q('#evStatementDate').value,dueDate:q('#evDueDate').value,total,allocations:allocationData(),notes:q('#evStatementNotes').value},'Statement posted to credit-card payable.');if(ok){editingStatement='';statementFormOpen=false;allocationSeed=[];render()}};
 if(q('#evStatementCancel'))q('#evStatementCancel').onclick=()=>{editingStatement='';statementFormOpen=false;allocationSeed=[];render()};
 qa('[data-edit-statement]').forEach(b=>b.onclick=()=>{editingStatement=b.dataset.editStatement;statementFormOpen=true;allocationSeed=[];render()});
 qa('[data-pay-statement]').forEach(button=>button.onclick=()=>{const statement=(data.creditCardStatements||[]).find(x=>x.id===button.dataset.payStatement);if(!statement)return;q('#evCardPayment')?.remove();const form=document.createElement('div');form.id='evCardPayment';form.className='tte-box';form.innerHTML='<h3>Pay '+esc(statement.cardName)+'</h3><div class="tte-grid"><label>Payment date<input id="evCardPayDate" type="date" value="'+today()+'"></label><label>Pay from<select id="evCardPayAccount">'+payOptions()+'</select></label></div><div class="tte-actions"><button class="btn" data-cancel>Cancel</button><button class="btn green" data-save>Post Payment '+fmt(statement.total)+'</button></div>';q('#expenseEditor').appendChild(form);window.TT_BANK_PAYMENT_DETAILS?.mount('evCardPayAccount',data.paymentAccounts||[]);form.querySelector('[data-cancel]').onclick=()=>form.remove();form.querySelector('[data-save]').onclick=()=>post({action:'pay_card_statement',statementId:statement.id,paymentDate:q('#evCardPayDate').value,paymentAccountId:q('#evCardPayAccount').value},'Credit-card payment posted.');form.scrollIntoView({block:'nearest'})});
 calcAllocation();
}

async function open(next){window.TT_EXPENSE_EDITOR?.claim(next);mode=next;const ed=q('#expenseEditor');if(ed)ed.innerHTML='<div class="tte-box" role="status">Loading…</div>';utilityFormOpen=cardFormOpen=statementFormOpen=false;editingUtilityPayment='';editingUtility='';editingCard='';editingStatement='';settlingReimbursement='';allocationSeed=[];month=thisMonth();await refresh()}
function install(){style();const utility=q('[data-expense="utility"]'),card=q('[data-expense="card"]'),reimburse=q('[data-expense="reimburse"]'),general=q('[data-expense="general"]');document.addEventListener('click',event=>{const icon=event.target.closest?.('[data-expense="utility"],[data-expense="card"],[data-expense="reimburse"],[data-expense="general"]');if(!icon)return;event.preventDefault();event.stopImmediatePropagation();void open(icon.dataset.expense)},true);qa('.entityBtn').forEach(b=>b.addEventListener('click',()=>{mode=''}))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
