(()=>{
'use strict';
const access=window.TT_ACCOUNT_ACCESS||{},api='../api/nonwoven_bag_bills.php';
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],entity=()=>localStorage.getItem('tt_accounts_entity')||'TTI';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Karachi',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n||0).toLocaleString('en-PK',{maximumFractionDigits:2});
let data=null;
async function load(){const r=await fetch(api+'?entity='+encodeURIComponent(entity()),{credentials:'same-origin',headers:{Accept:'application/json'}});let d={};try{d=await r.json()}catch{}if(!r.ok||!d.ok)throw new Error(d.error||'Could not load Non-Woven bag bills.');data=d;return d}
async function post(body){const r=await fetch(api,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({...body,csrf:access.csrf})});let d={};try{d=await r.json()}catch{}if(!r.ok||!d.ok)throw new Error(d.error||'Non-Woven bag update failed.');await load();return d}
function ensureStyle(){if(q('#ttNwStyle'))return;const s=document.createElement('style');s.id='ttNwStyle';s.textContent=`.ttnw{margin:14px 18px;border:1px solid #dfe6ec;border-radius:12px;background:#fff}.ttnw-h{padding:13px 14px;border-bottom:1px solid #edf0f3}.ttnw-b{padding:14px}.ttnw-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.ttnw-grid label{font-size:11px;font-weight:800;color:#526173}.ttnw-grid input,.ttnw-grid select{width:100%;margin-top:5px;padding:9px;border:1px solid #cfd8e1;border-radius:8px}.ttnw-note{background:#f7f9fb;border:1px solid #dde5eb;border-radius:9px;padding:10px;margin:10px 0;font-size:12px}.ttnw-table{width:100%;border-collapse:collapse}.ttnw-table th,.ttnw-table td{padding:8px;border-bottom:1px solid #edf0f3;text-align:left;font-size:12px}.ttnw-table th{font-size:10px;text-transform:uppercase;background:#f8fafc;color:#687686}.ttnw-actions{display:flex;justify-content:flex-end;margin-top:10px}@media(max-width:760px){.ttnw-grid{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
function purchasePanel(){const ed=q('#purchaseEditor');if(!ed||q('#ttNwPurchase'))return;const box=document.createElement('div');box.id='ttNwPurchase';box.className='ttnw';ed.appendChild(box);renderPurchase()}
function renderPurchase(){const box=q('#ttNwPurchase');if(!box)return;const ls=data?.lines||[];box.innerHTML=`<div class="ttnw-h"><h3 style="margin:0">Non-Woven Bag Bills</h3><div style="font-size:11px;color:#6f7a89;margin-top:4px">Simple bag supplier bill. No GST and no Sales Tax Refund Receivable.</div></div><div class="ttnw-b"><div class="ttnw-note">PO quantity, Mill-received quantity and approved PO rate are still checked. Non-Woven bags never enter the sales-tax refund report.</div><div class="ttnw-grid"><label>PO / Packing Size<select id="nwLine"><option value="">Select Non-Woven PO line</option>${ls.map((x,i)=>`<option value="${i}">${esc(x.po.poNo)} · ${esc(x.packingSize)} · ${esc(x.brand)} · Ordered ${fmt(x.orderedQty)} · Received ${fmt(x.receivedQty||0)}</option>`).join('')}</select></label><label>Supplier<input id="nwSupplier" readonly></label><label>Seller's Invoice No.<input id="nwInv"></label><label>Seller's Invoice Date<input id="nwDate" type="date" value="${today()}"></label><label>No. of Bags<input id="nwQty" inputmode="numeric"></label><label>Rate / Bag<input id="nwRate" inputmode="decimal"></label><label>Total Bill<input id="nwTotal" readonly value="Rs 0"></label></div><div class="ttnw-actions"><button class="btn green" id="nwSave">Save / Post Non-Woven Bill</button></div><div style="overflow:auto;margin-top:14px"><table class="ttnw-table"><thead><tr><th>Date</th><th>Supplier</th><th>Invoice</th><th>PO</th><th>Packing</th><th>Bags</th><th>Rate</th><th>Total</th><th>Status</th></tr></thead><tbody>${(data?.bills||[]).length?(data.bills||[]).map(b=>`<tr><td>${esc(b.sellerInvoiceDate)}</td><td>${esc(b.supplier)}</td><td>${esc(b.sellerInvoice)}</td><td>${esc(b.poNo)}</td><td>${esc(b.packingSize)}</td><td>${fmt(b.bags)}</td><td>${fmt(b.ratePerBag)}</td><td>Rs ${fmt(b.totalAmount)}</td><td>${esc(b.status)}</td></tr>`).join(''):'<tr><td colspan="9">No Non-Woven bag bills yet.</td></tr>'}</tbody></table></div></div>`;
const ln=q('#nwLine');if(ln)ln.onchange=()=>{const x=ls[Number(ln.value)];if(!x)return;q('#nwSupplier').value=x.po.supplier||'';q('#nwRate').value=x.ratePerBag||'';calc()};['nwQty','nwRate'].forEach(id=>q('#'+id)?.addEventListener('input',calc));q('#nwSave')?.addEventListener('click',saveBill)}
function calc(){const a=Number(q('#nwQty')?.value||0),r=Number(q('#nwRate')?.value||0);if(q('#nwTotal'))q('#nwTotal').value='Rs '+fmt(a*r)}
async function saveBill(){const ls=data?.lines||[],x=ls[Number(q('#nwLine')?.value)];if(!x)return alert('Select a Non-Woven PO line.');const qty=Number(q('#nwQty')?.value||0),rate=Number(q('#nwRate')?.value||0);if(!(qty>0&&rate>0))return alert('Enter number of bags and rate.');try{await post({action:'create_bill',entity:entity(),poNo:x.po.poNo,lineKey:x.lineKey,supplier:x.po.supplier||q('#nwSupplier').value,sellerInvoice:q('#nwInv').value||'',sellerInvoiceDate:q('#nwDate').value,bags:qty,ratePerBag:rate});renderPurchase()}catch(e){alert(e.message||e)}}
function payPanel(){const ws=q('#ws-payables');if(!ws)return;let box=q('#ttNwPay');if(!box){box=document.createElement('div');box.id='ttNwPay';box.className='ttnw';const host=q('#ttBagPayBox')||q('#ttPayCommodityBar')||ws.querySelector('.panelHead');host?.insertAdjacentElement('afterend',box)}const visible=window.TT_PAYABLES_COMMODITY?.get?.()==='OTHER';box.classList.toggle('hidden',!visible);if(!visible)return;renderPay()}
function renderPay(){const box=q('#ttNwPay');if(!box)return;const rows=data?.payables||[],banks=data?.banks||[];box.innerHTML=`<div class="ttnw-h"><h3 style="margin:0">Non-Woven Bag Supplier Payables</h3><div style="font-size:11px;color:#6f7a89;margin-top:4px">Full invoice payment only. Bank only. No GST.</div></div><div class="ttnw-b"><div style="overflow:auto"><table class="ttnw-table"><thead><tr><th>Supplier</th><th>Invoice</th><th>PO</th><th>Packing</th><th>Total Bill</th><th>Outstanding</th><th></th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr><td>${esc(r.supplier)}</td><td>${esc(r.sellerInvoice)}</td><td>${esc(r.poNo)}</td><td>${esc(r.packingSize)}</td><td>Rs ${fmt(r.totalAmount)}</td><td><b>Rs ${fmt(r.outstanding)}</b></td><td><button class="btn small" data-nw-pay="${esc(r.id)}">Pay</button></td></tr>`).join(''):'<tr><td colspan="7">No outstanding Non-Woven bag bills.</td></tr>'}</tbody></table></div><div id="nwPayForm"></div></div>`;qa('[data-nw-pay]').forEach(b=>b.onclick=()=>payForm(b.dataset.nwPay,banks))}
function payForm(id,banks){const r=(data?.payables||[]).find(x=>x.id===id);if(!r)return;const el=q('#nwPayForm');el.innerHTML=`<div class="formCard" style="margin-top:12px"><h3>Pay ${esc(r.supplier)} — ${esc(r.sellerInvoice)}</h3><div class="ttnw-grid"><label>Payment Date<input id="nwPayDate" type="date" value="${today()}"></label><label>Bank Account<select id="nwBank"><option value="">Select bank</option>${banks.map(x=>`<option value="${esc(x.id)}">${esc(x.display)}</option>`).join('')}</select></label><label>Amount<input id="nwPayAmt" readonly value="${r.outstanding}"></label><label>Reference / Cheque No.<input id="nwPayRef"></label></div><div class="ttnw-note">Exact full outstanding amount only. Cash and partial payment are not allowed.</div><div class="ttnw-actions"><button class="btn green" id="nwPayPost">Post Full Bank Payment</button></div></div>`;q('#nwPayPost').onclick=async()=>{if(!q('#nwBank').value)return alert('Select bank account.');try{await post({action:'pay_bill',entity:entity(),billId:id,date:q('#nwPayDate').value,bankId:q('#nwBank').value,amount:Number(r.outstanding),reference:q('#nwPayRef').value||''});renderPay()}catch(e){alert(e.message||e)}}}
async function refresh(){if(entity()==='TG')return;try{await load();if(q('#purchaseEditor')&&q('[data-purchase="bags"]'))purchasePanel();payPanel()}catch(e){console.error(e)}}
ensureStyle();document.addEventListener('click',e=>{if(e.target.closest('[data-purchase="bags"]'))setTimeout(refresh,80);if(e.target.closest('[data-pay-commodity="OTHER"]'))setTimeout(refresh,80);if(e.target.closest('.appCard[data-key="payables"]'))setTimeout(refresh,100)});new MutationObserver(()=>{if(q('#ws-purchases')||q('#ws-payables'))setTimeout(()=>{if(!data)refresh();else payPanel()},30)}).observe(document.documentElement,{childList:true,subtree:true});setTimeout(refresh,120);
})();
