(()=>{
  'use strict';
  const access=window.TT_MODULE_ACCESS||{};
  const accountsApi='api/accounts.php', exportApi='api/export_accounting.php', localApi='api/local_sales_control.php', localPayApi='api/local_sales_payments.php', millBanksApi='api/mill_visible_banks.php', outboxApi='api/bridge_outbox.php';
  const OUTBOX='tt39accountsoutbox';
  const parse=(k,d)=>{try{const v=JSON.parse(localStorage.getItem(k));return v??d}catch{return d}};
  const put=(k,v)=>localStorage.setItem(k,JSON.stringify(v));

  function outbox(){const a=parse(OUTBOX,[]);return Array.isArray(a)?a:[]}
  function saveOutbox(a){put(OUTBOX,a)}
  async function outboxReq(body){const opt={method:body?'POST':'GET',credentials:'same-origin',headers:{Accept:'application/json'}};if(body){opt.headers['Content-Type']='application/json';opt.body=JSON.stringify({csrf:access.csrf,...body})}const r=await fetch(outboxApi,opt);let d={};try{d=await r.json()}catch{}if(!r.ok||!d.ok)throw new Error(d.error||'Accounts handoff outbox is unavailable.');return d}
  async function persistItem(item){return outboxReq({action:'enqueue',key:item.key,kind:item.kind,body:item.body})}
  async function markSent(item,result){return outboxReq({action:'mark_sent',key:item.key,result})}
  async function recordFailure(item,error){try{await outboxReq({action:'record_failure',key:item.key,error:String(error?.message||error)})}catch{}}
  async function mergeServerOutbox(){try{const d=await outboxReq(),a=outbox();for(const server of (d.items||[])){if(!server?.key||!server?.kind||!server?.body)continue;const old=a.find(x=>x.key===server.key);if(old){old.kind=server.kind;old.body=server.body;old.status='Pending';old.tries=Math.max(Number(old.tries||0),Number(server.tries||0));old.lastError=server.lastError||old.lastError||''}else a.push({key:server.key,kind:server.kind,body:server.body,status:'Pending',createdAt:server.createdAt||new Date().toISOString(),tries:Number(server.tries||0),lastError:server.lastError||''})}saveOutbox(a)}catch(e){console.error('Accounts server outbox sync',e)}}
  function addItem(event){const a=outbox(),old=a.find(x=>x.key===event.key);if(old){const changed=JSON.stringify(old.body)!==JSON.stringify(event.body);if(old.status!=='Posted'||changed){old.body=event.body;old.kind=event.kind;old.status='Pending';old.updatedAt=new Date().toISOString();old.lastError='';saveOutbox(a);persistItem(old).catch(()=>{});flush()}return}const item={...event,status:'Pending',createdAt:new Date().toISOString(),tries:0,lastError:''};a.push(item);saveOutbox(a);persistItem(item).catch(()=>{});flush()}
  async function postItem(item){
    await persistItem(item);
    let endpoint=accountsApi,body={action:'post_event',csrf:access.csrf,...item.body};
    if(item.kind==='exportCandidate'){endpoint=exportApi;body={action:'queue_candidate',csrf:access.csrf,...item.body}}
    else if(item.kind==='loadingProgramme'){endpoint='api/accounts_workflows_v1.php';body={csrf:access.csrf,...item.body}}
    else if(item.kind==='localSaleCandidate'){endpoint=localApi;body={action:'queue_candidate',csrf:access.csrf,...item.body}}
    else if(item.kind==='localPaymentCandidate'){endpoint=localPayApi;body={action:'queue_payment',csrf:access.csrf,...item.body}}
    const r=await fetch(endpoint,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(body)});let d={};try{d=await r.json()}catch{}
    if(r.status===409&&d.existing)return {ok:true,duplicate:true,journal:d.existing?.journalId||'',candidate:d.existing?.id||''};
    if(!r.ok||!d.ok)throw new Error(d.error||'Automatic Accounts handoff failed.');
    return {ok:true,journal:d.journal?.id||'',candidate:d.candidate?.id||d.payment?.id||''};
  }
  let flushing=false;
  async function flush(){if(flushing)return;flushing=true;try{let a=outbox();for(const item of a.filter(x=>x.status!=='Posted')){try{const d=await postItem(item);await markSent(item,d);item.status='Posted';item.postedAt=new Date().toISOString();item.journalId=d.journal||item.journalId||'';item.candidateId=d.candidate||item.candidateId||'';item.lastError=''}catch(e){item.tries=(item.tries||0)+1;item.lastError=String(e.message||e);item.lastTriedAt=new Date().toISOString();await recordFailure(item,e)}saveOutbox(a)}}finally{flushing=false}}
  function signal(msg,good=true){if(typeof window.showNonBlockingMessage==='function')return window.showNonBlockingMessage(msg);let e=document.getElementById('ttAccountingBridgeNotice');if(!e){e=document.createElement('div');e.id='ttAccountingBridgeNotice';e.style.cssText='position:fixed;left:50%;bottom:20px;transform:translateX(-50%);z-index:100001;color:#fff;padding:10px 14px;border-radius:10px;font:700 12px Arial;box-shadow:0 7px 24px #0003';document.body.appendChild(e)}e.style.background=good?'#147a5b':'#a93a34';e.textContent=msg;e.hidden=false;clearTimeout(e._t);e._t=setTimeout(()=>e.hidden=true,2400)}
  function commodityFromVariety(v){const s=String(v||'').toUpperCase();if(/CORN|MAIZE/.test(s))return 'CORN';if(/SESAME/.test(s))return 'SESAME';return 'RICE'}
  function provisionalReceiptValue(s){const kg=Number(s.payableWeight||0),rate=Number(s.purchaseRate||0),katPaisa=['brokenKat','moistureKat','damageKat','chalkyKat','paddyKat'].reduce((n,k)=>n+Number(s[k]||0),0),netRate=Math.max(0,rate-katPaisa/100);return {kg,rate,katPaisa,netRate,amount:Math.round(kg*netRate*100)/100}}

  function bridgePohanch(){
    if(access.moduleId!=='milling'||typeof window.saveSlip!=='function'||window.saveSlip._ttAccountsWrapped)return;
    const original=window.saveSlip;
    function wrappedSaveSlip(){const before=parse('tt30slips',[]),ids=new Set((Array.isArray(before)?before:[]).map(x=>String(x.id))),result=original.apply(this,arguments),after=parse('tt30slips',[]),saved=(Array.isArray(after)?after:[]).find(x=>!ids.has(String(x.id)));if(saved){const v=provisionalReceiptValue(saved);if(v.kg>0&&v.amount>0){const sourceKey='POHANCH|'+String(saved.slip||saved.id);addItem({key:'TTI|COMMODITY_RECEIPT_ACCEPTED|'+sourceKey,kind:'accountEvent',body:{eventType:'COMMODITY_RECEIPT_ACCEPTED',entity:'TTI',date:saved.unloadingDate||saved.arrivalDate||new Date().toISOString().slice(0,10),sourceKey,reference:saved.slip||sourceKey,narration:(commodityFromVariety(saved.variety)==='RICE'?'Rice':commodityFromVariety(saved.variety)==='CORN'?'Corn':'Sesame')+' receipt — Soda '+(saved.soda||'')+' — '+(saved.truck||''),amount:v.amount,commodity:commodityFromVariety(saved.variety),meta:{soda:saved.soda||'',pohanch:saved.slip||'',truck:saved.truck||'',broker:saved.broker||'',party:saved.party||'',variety:saved.variety||'',payableWeightKg:v.kg,grossRatePerKg:v.rate,katPaisaPerKg:v.katPaisa,provisionalNetRatePerKg:v.netRate,valuation:'Provisional receipt value; final bill clears GRNI and posts authorized differences.'}}});signal('Pohanch saved · Accounts receipt queued')}}return result}
    wrappedSaveSlip._ttAccountsWrapped=true;wrappedSaveSlip._ttOriginal=original;window.saveSlip=wrappedSaveSlip;
  }

  function exportState(){try{return typeof state!=='undefined'?state:null}catch(e){return null}}
  function exportRefs(s){let fi=[],st=exportState();try{fi=(s.customs?.fiAllocations||[]).map(a=>st?.fi?.find(f=>f.id===a.fiId)?.number).filter(Boolean)}catch(e){}let gd=[...(s.commercial?.gd||[]),...(s.bl?.gd||[])].map(g=>g?.no).filter(Boolean);gd=[...new Set(gd)];return {fi,gd}}
  function exportNetAmount(s,c){const qty=Number(s.actualShippedQty||((typeof window.shipmentActualQtyFor==='function')?window.shipmentActualQtyFor(s):s.plannedQty)||0),rate=Number(s.commercial?.rate||c?.packings?.[0]?.price||c?.price||0),adj=(s.commercial?.adjustments||[]).reduce((n,a)=>n+(a.sign==='+'?1:-1)*Number(a.amount||0),0);return {qty,rate,amount:Math.round((qty*rate+adj)*100)/100}}
  function bridgeExportCompletion(){
    if(access.moduleId!=='exports'||typeof window.markComplete!=='function'||window.markComplete._ttAccountsWrapped)return;
    const original=window.markComplete;
    function wrappedMarkComplete(){let s=null,c=null,before=false;try{s=window.getShip();c=window.getContract(s.contractRef);before=!!s.completed}catch(e){}const result=original.apply(this,arguments);try{if(s&&!before&&s.completed){const val=exportNetAmount(s,c),refs=exportRefs(s),sourceKey='EXPORT|'+String(s.id||s.lotNo||s.contractRef),seller=String(s.seller||c?.seller||'TTI').toUpperCase();if(val.qty>0&&val.amount>0&&s.bl?.onBoardDate){addItem({key:seller+'|EXPORT_CANDIDATE|'+sourceKey,kind:'exportCandidate',body:{sellerEntity:seller,sourceKey,lotRef:String(s.lotNo||s.id||s.contractRef),contractRef:String(s.contractRef||''),customer:String(s.buyer||c?.customer||''),product:String(c?.product||''),currency:String(c?.currency||'USD'),transactionAmount:val.amount,actualQtyMT:val.qty,incoterm:String(c?.incoterm||'OTHER'),onBoardDate:String(s.bl.onBoardDate),blNo:String(s.bl?.blNo||''),commercialInvoiceDate:String(s.commercial?.date||''),fiRefs:refs.fi,gdRefs:refs.gd,tgInternalValue:seller==='TG'?Number(s.customs?.tgInternalValue||0):0}});signal('Export lot completed · Accounts review queued')}}}catch(e){console.error('Export → Accounts bridge',e)}return result}
    wrappedMarkComplete._ttAccountsWrapped=true;wrappedMarkComplete._ttOriginal=original;window.markComplete=wrappedMarkComplete;
  }

  let millBankChoices=[];
  async function loadMillBanks(){try{const r=await fetch(millBanksApi,{credentials:'same-origin',headers:{Accept:'application/json'}});const d=await r.json();if(r.ok&&d.ok)millBankChoices=Array.isArray(d.banks)?d.banks:[]}catch(e){millBankChoices=[]}}
  function localFrame(){const f=document.querySelector('#partySaleWrap iframe');try{return f?.contentWindow||null}catch(e){return null}}
  function bankById(id){return millBankChoices.find(x=>String(x.id)===String(id))||null}
  function saleEntity(sale){const e=String(sale?.accountEntity||'').toUpperCase();if(['TTI','BRM'].includes(e))return e;const found=new Set((sale?.pay||[]).map(p=>String(p?.bankEntity||bankById(p?.bankAccountId)?.entity||'').toUpperCase()).filter(x=>['TTI','BRM'].includes(x)));return found.size===1?[...found][0]:''}
  function fillLocalBankChoices(w){const sel=w?.document?.getElementById('payBank');if(!sel)return;const oldId=sel.selectedOptions?.[0]?.dataset?.bankId||'',old=sel.value;sel.innerHTML='<option value="">Select Transtrade Bank Account</option>'+millBankChoices.map(x=>`<option value="${String(x.display).replace(/"/g,'&quot;')}" data-bank-id="${String(x.id).replace(/"/g,'&quot;')}" data-entity="${String(x.entity).replace(/"/g,'&quot;')}">${x.display}</option>`).join('');const match=[...sel.options].find(o=>o.dataset.bankId===oldId||o.value===old);if(match)sel.value=match.value}
  function queueLocalLoad(w,sale,load,index){if(!load||!load.printed)return;const entity=saleEntity(sale);if(!['TTI','BRM'].includes(entity)){load.accounts='Waiting for bank/company';try{w.persistSales?.()}catch(e){}return}sale.accountEntity=entity;if(!load.bridgeId)load.bridgeId='LSL-'+Date.now()+'-'+Math.random().toString(36).slice(2,7);if(!load.gatePassRef)load.gatePassRef='LGP-'+String(sale.soda||'SALE')+'-'+String(index+1).padStart(2,'0');try{w.persistSales?.()}catch(e){}const kg=Number(load.kg||0),rate=Number(sale.rate||0),amount=Math.round(kg*rate*100)/100;if(kg<=0||rate<=0||amount<=0)return;const sourceKey='LOCAL|'+String(sale.soda||'')+'|'+load.bridgeId;addItem({key:entity+'|LOCAL_SALE|'+sourceKey,kind:'localSaleCandidate',body:{entity,sourceKey,soda:String(sale.soda||''),saleDate:String(load.date||sale.date||new Date().toISOString().slice(0,10)),party:String(sale.party||''),product:String(sale.product||''),loadedKg:kg,ratePerKg:rate,amount,truck:String(load.truck||''),gatePass:String(load.gatePassRef||''),stockLocation:String(window.currentMill?.name||'TTI Rice Mills'),stockReference:String(sale.product||'')}});load.accounts='Pending';signal('Local Gate Pass saved · Accounts review queued')}
  function queueLocalPayment(w,sale,payment){if(!payment)return;const entity=String(payment.bankEntity||saleEntity(sale)||'').toUpperCase();if(!['TTI','BRM'].includes(entity)){payment.accounts='Waiting for bank/company';try{w.persistSales?.()}catch(e){}return}sale.accountEntity=entity;if(!payment.bridgeId)payment.bridgeId='LSP-'+Date.now()+'-'+Math.random().toString(36).slice(2,7);try{w.persistSales?.()}catch(e){}const sourceKey='LOCALPAY|'+String(sale.soda||'')+'|'+payment.bridgeId;addItem({key:entity+'|LOCAL_PAYMENT|'+sourceKey,kind:'localPaymentCandidate',body:{entity,sourceKey,soda:String(sale.soda||''),party:String(sale.party||''),product:String(sale.product||''),paymentDate:String(payment.date||sale.date||new Date().toISOString().slice(0,10)),amount:Number(payment.amount||0),paymentType:String(payment.type||''),reference:String(payment.where||''),bankAccountId:String(payment.bankAccountId||''),sourceSoda:String(payment.sourceSoda||''),sourceProduct:String(payment.sourceProduct||''),sourceParty:String(payment.sourceParty||'')}});payment.accounts='Pending'}
  function queueKnownLocalItems(w,sale){if(!['TTI','BRM'].includes(saleEntity(sale)))return;(sale.pay||[]).forEach(p=>queueLocalPayment(w,sale,p));(sale.loads||[]).forEach((l,i)=>{if(l.printed)queueLocalLoad(w,sale,l,i)});try{w.persistSales?.()}catch(e){}}
  function bridgeLocalSales(){
    if(access.moduleId!=='milling')return;const w=localFrame();if(!w||!w.document||!Array.isArray(w.sales))return;fillLocalBankChoices(w);
    if(typeof w.openSale==='function'&&!w.openSale._ttAccountsWrapped){const original=w.openSale;function wrapped(){const result=original.apply(this,arguments);setTimeout(()=>fillLocalBankChoices(w),0);return result}wrapped._ttAccountsWrapped=true;wrapped._ttOriginal=original;w.openSale=wrapped}
    if(typeof w.paymentTypeChanged==='function'&&!w.paymentTypeChanged._ttAccountsWrapped){const original=w.paymentTypeChanged;function wrapped(){const result=original.apply(this,arguments);fillLocalBankChoices(w);return result}wrapped._ttAccountsWrapped=true;wrapped._ttOriginal=original;w.paymentTypeChanged=wrapped}
    if(typeof w.savePay==='function'&&!w.savePay._ttAccountsWrapped){const original=w.savePay;function wrapped(){if(!w.sel)return original.apply(this,arguments);const type=String(w.document.getElementById('payType')?.value||''),bankSel=w.document.getElementById('payBank'),bankOpt=bankSel?.selectedOptions?.[0],bankId=bankOpt?.dataset?.bankId||'',bankEntity=String(bankOpt?.dataset?.entity||'').toUpperCase(),existing=saleEntity(w.sel);if(type==='Transtrade Bank'){if(!bankId||!['TTI','BRM'].includes(bankEntity))return w.alert('Select the Transtrade bank account receiving this payment.');if(existing&&existing!==bankEntity)return w.alert('This Local Soda is already linked to '+existing+'. Please use a '+existing+' bank account for this Soda.')}const before=(w.sel.pay||[]).map(x=>JSON.parse(JSON.stringify(x))),result=original.apply(this,arguments),after=w.sel.pay||[];let changed=-1;if(after.length>before.length)changed=after.length-1;else for(let i=0;i<after.length;i++){if(JSON.stringify(after[i])!==JSON.stringify(before[i])){changed=i;break}}if(changed>=0){const p=after[changed],old=before[changed];if(old?.bridgeId&&!p.bridgeId)p.bridgeId=old.bridgeId;if(type==='Transtrade Bank'){p.bankAccountId=bankId;p.bankEntity=bankEntity;p.where=bankSel?.value||p.where||'';w.sel.accountEntity=bankEntity}else if(existing){p.bankEntity=existing;w.sel.accountEntity=existing}queueLocalPayment(w,w.sel,p);queueKnownLocalItems(w,w.sel);w.persistSales?.();w.renderPayments?.()}return result}wrapped._ttAccountsWrapped=true;wrapped._ttOriginal=original;w.savePay=wrapped}
    if(typeof w.gate==='function'&&!w.gate._ttAccountsWrapped){const original=w.gate;function wrapped(i){if(!w.sel)return original.apply(this,arguments);const load=w.sel.loads?.[i];if(load&&!load.bridgeId)load.bridgeId='LSL-'+Date.now()+'-'+Math.random().toString(36).slice(2,7);if(load&&!load.gatePassRef)load.gatePassRef='LGP-'+String(w.sel.soda||'SALE')+'-'+String(i+1).padStart(2,'0');w.persistSales?.();const result=original.apply(this,arguments);queueLocalLoad(w,w.sel,w.sel.loads?.[i],i);w.persistSales?.();return result}wrapped._ttAccountsWrapped=true;wrapped._ttOriginal=original;w.gate=wrapped}
  }

  let statusSyncing=false;
  function simpleStatus(s){s=String(s||'');if(/Approved|Posted/.test(s))return 'Approved';if(/Returned|Rejected/.test(s))return 'Returned';if(/Needs/.test(s))return 'Needs Details';return 'Pending'}
  async function syncLocalStatuses(){if(access.moduleId!=='milling'||statusSyncing)return;const w=localFrame();if(!w||!Array.isArray(w.sales))return;statusSyncing=true;try{const r=await fetch(localPayApi+'?r='+Date.now(),{credentials:'same-origin',headers:{Accept:'application/json'}});let d={};try{d=await r.json()}catch{}if(!r.ok||!d.ok)return;const pm=new Map((d.paymentStatuses||[]).map(x=>[x.sourceKey,x])),sm=new Map((d.saleStatuses||[]).map(x=>[x.sourceKey,x]));let changed=false;for(const sale of w.sales){for(const p of (sale.pay||[])){if(!p.bridgeId)continue;const st=pm.get('LOCALPAY|'+String(sale.soda||'')+'|'+p.bridgeId);if(!st)continue;const label=simpleStatus(st.status);if(p.accounts!==label){p.accounts=label;changed=true}if((p.accountsNote||'')!==(st.note||'')){p.accountsNote=st.note||'';changed=true}}for(const l of (sale.loads||[])){if(!l.bridgeId)continue;const st=sm.get('LOCAL|'+String(sale.soda||'')+'|'+l.bridgeId);if(!st)continue;const label=simpleStatus(st.status);if(l.accounts!==label){l.accounts=label;changed=true}}}if(changed){w.persistSales?.();const ae=w.document?.activeElement,editing=ae&&/INPUT|TEXTAREA|SELECT/.test(ae.tagName);if(!editing){w.renderPayments?.();w.renderLoads?.();w.render?.()}}}catch(e){console.error('Local Sales Accounts status sync',e)}finally{statusSyncing=false}}

  function showOutboxAttention(){document.getElementById('ttAccountsOutboxBadge')?.remove()}
  async function boot(){bridgePohanch();bridgeExportCompletion();await loadMillBanks();bridgeLocalSales();await mergeServerOutbox();await flush();await syncLocalStatuses();showOutboxAttention()}
  addEventListener('DOMContentLoaded',boot);setTimeout(boot,300);setTimeout(boot,1200);setInterval(()=>{bridgePohanch();bridgeExportCompletion();bridgeLocalSales();mergeServerOutbox().then(flush).then(showOutboxAttention);syncLocalStatuses()},10000);window.TT_ACCOUNTS_SOURCE_BRIDGE={flush,outbox,syncLocalStatuses,mergeServerOutbox};
  if(access.moduleId==='milling'){const s=document.createElement('script');s.src='accounts/local-sales-entity-rule.js?v=20260908-1';document.head.appendChild(s)}
})();
