<?php
declare(strict_types=1);
require __DIR__ . '/auth_store.php';
$user=tt_require_login();
if (($user['role'] ?? '')==='Super Admin') { header('Location: index.php'); exit; }
if (!empty($user['must_change_password'])) { header('Location: change-password.php'); exit; }
$modules=[];
if(tt_user_can_open_module($user,'Directors'))$modules[]=['name'=>'Directors','href'=>'directors/index.php','icon'=>'◆','desc'=>'Management controls, TG Master and renewal alerts.'];
if(tt_user_can_open_module($user,'Accounts'))$modules[]=['name'=>'Accounts','href'=>'accounts/index.php','icon'=>'▤','desc'=>'Accounts, banking, receivables, payables and reporting.'];
if(tt_user_can_open_module($user,'Exports'))$modules[]=['name'=>'Exports','href'=>'module.php?id=exports','icon'=>'⇢','desc'=>'Export sales, shipments and documentation.'];
if(tt_user_can_open_module($user,'Mill'))$modules[]=['name'=>'Milling','href'=>'module.php?id=milling','icon'=>'▦','desc'=>'Mill, stock, production and operational workflows.'];
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Transtrade</title><link rel="stylesheet" href="admin/auth.css?v=20260907-2"><style>.launcher{width:min(880px,94vw);margin:8vh auto;background:#fff;border:1px solid #e1e6eb;border-radius:18px;padding:26px;box-shadow:0 18px 55px #102a4615}.modules{display:grid;grid-template-columns:repeat(2,1fr);gap:13px;margin-top:20px}.module{display:block;text-decoration:none;color:#142033;border:1px solid #dce3e9;border-radius:14px;padding:17px;background:#fff}.module:hover{box-shadow:0 8px 24px #102a4615;transform:translateY(-1px)}.module .ico{width:42px;height:42px;border-radius:11px;background:#edf3f8;display:grid;place-items:center;font-size:20px;margin-bottom:13px}.module b{display:block;font-size:15px}.module span{display:block;color:#6f7a89;font-size:12px;margin-top:4px}@media(max-width:620px){.modules{grid-template-columns:1fr}}</style></head><body><a href="logout.php" title="Log out" aria-label="Log out" style="position:fixed;right:16px;top:16px;width:38px;height:38px;display:grid;place-items:center;border:1px solid #e4c5c2;border-radius:10px;background:#fff;color:#b42318;text-decoration:none;font-size:20px;font-weight:900;line-height:1">⏻</a><main class="launcher"><div class="brand">TT</div><p class="eyebrow">TRANSTRADE INTERNATIONAL</p><h1>Module access</h1><p class="intro"><?=htmlspecialchars((string)($user['full_name']??''))?> · <?=htmlspecialchars((string)($user['role']??''))?></p><?php if($modules):?><div class="modules"><?php foreach($modules as $m):?><a class="module" href="<?=htmlspecialchars($m['href'])?>"><div class="ico"><?=htmlspecialchars($m['icon'])?></div><b><?=htmlspecialchars($m['name'])?></b><span><?=htmlspecialchars($m['desc'])?></span></a><?php endforeach;?></div><?php else:?><p class="intro" style="margin-top:18px">No module has been assigned to this user yet. Please contact Super Admin.</p><?php endif;?></main></body></html>