<?php
declare(strict_types=1);
require __DIR__.'/auth_store.php';
require_once __DIR__.'/inventory_reconciliation.php';
$user=tt_require_login();
$entities=array_values(array_filter(['TTI','BRM'],static fn($e)=>tt_inv_can_report($user,$e)));
$entity=strtoupper((string)($_GET['entity']??($entities[0]??'')));
if(!in_array($entity,$entities,true)){http_response_code(403);exit('Accounts or Directors report permission for this company is required.');}
header('Cache-Control: no-store, no-cache, must-revalidate');header('X-LiteSpeed-Cache-Control: no-cache');header('Vary: Cookie');
$origin=($_GET['origin']??'')==='directors'?'directors':'accounts';$today=(new DateTimeImmutable('now',new DateTimeZone('Asia/Karachi')))->format('Y-m-d');
$escape=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');$number=static fn($v)=>number_format((float)$v,3,'.',',');
$date=static function($v):string{$s=(string)$v;return preg_match('/^(\d{4})-(\d{2})-(\d{2})/',$s,$m)?$m[3].'-'.$m[2].'-'.$m[1]:$s;};
try{$values=tt_inv_read_values();$report=tt_inv_statement($values,$entity);$rate=tt_inv_rate($values,$entity,$today);}
catch(Throwable $error){error_log('Stock reconciliation: '.$error->getMessage());http_response_code(503);exit('The reconciliation report could not be read. No figures have been assumed.');}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Stock Reconciliation — <?=$escape($entity)?></title>
<style>body{margin:0;background:#f3f6f5;color:#192c27;font:15px/1.5 Arial,sans-serif}header{padding:16px 24px;background:#155d47;color:#fff;display:flex;gap:20px;align-items:center}header a{color:#fff}main{max-width:1250px;margin:24px auto;padding:0 18px}h1{font-size:25px}h2{font-size:20px;margin-top:28px}.summary{display:flex;gap:14px;flex-wrap:wrap}.card{background:#fff;border:1px solid #d8e3de;border-radius:10px;padding:16px;flex:1;min-width:210px}.card strong{display:block;font-size:24px}.note{color:#4c6259}.table{overflow:auto;background:#fff;border:1px solid #d8e3de;border-radius:10px}table{border-collapse:collapse;width:100%;font-size:13px}th,td{padding:10px;border-bottom:1px solid #e1e8e5;text-align:left;vertical-align:top}th{background:#edf4f0}select,button{font:inherit;padding:7px;border:1px solid #9fb8ac;border-radius:6px;background:#fff}form{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.fixed{font-weight:bold}.warning{color:#8a311d}.empty{padding:15px;color:#52645c}@media print{header a,form{display:none}body{background:#fff}.card,table{break-inside:avoid}}</style></head><body>
<header><strong>TRANSTRADE</strong><span>Accounts / Directors</span><a href="/<?=$origin?>/index.php">Return to <?=$escape(ucfirst($origin))?></a></header><main>
<h1>Ghati &amp; Stock Reconciliation</h1>
<form method="get"><input type="hidden" name="origin" value="<?=$escape($origin)?>"><label>Company <select name="entity"><?php foreach($entities as$e):?><option <?=$e===$entity?'selected':''?>><?=$escape($e)?></option><?php endforeach;?></select></label><button type="submit">Refresh report</button><span><?=$escape($date($today))?></span></form>
<p class="note">Informational reconciliation, not physical inventory. Gains first offset Ghati; unused gain carries forward. Actual loading is not blocked while current-shift production is pending. Figures below do not create a purchase or a journal.</p>
<div class="summary"><div class="card">Net Ghati / weight loss<strong><?=$number($report['ghatiKg'])?> kg</strong></div><div class="card">Carry-forward gain<strong><?=$number($report['carryForwardGainKg'])?> kg</strong></div><div class="card">10-day weighted Raw Rice rate<strong><?=$rate===null?'Not available':'PKR '.number_format($rate,2).' / kg'?></strong></div></div>
<?php if($rate!==null):?><p class="note">Indicative weight-loss exposure: PKR <?=number_format($report['ghatiKg']*$rate,2)?>. This is a management valuation, not another booked expense.</p><?php endif;?>
<h2>Pending production and physical confirmations</h2><div class="table"><table><thead><tr><th>Date / shift</th><th>Mill</th><th>Product / brand</th><th>Physical kg</th><th>Status</th></tr></thead><tbody>
<?php foreach($report['confirmations']as$r):?><tr><td><?=$escape($date($r['shiftDate']??$r['date']??''))?> · <?=$escape($r['shift']??'Shift needs review')?></td><td><?=$escape($r['millName']??'')?></td><td><?=$escape($r['stockName']??'')?></td><td><?=$number($r['physicalKg']??0)?></td><td class="<?=empty($r['reviewRequired'])?'':'warning'?>"><?=$escape($r['reviewRequired']??$r['status']??'')?></td></tr><?php endforeach;?>
<?php if(!$report['confirmations']):?><tr><td colspan="5">No physical confirmations recorded.</td></tr><?php endif;?></tbody></table></div>
<h2>Reconciled events</h2><div class="table"><table><thead><tr><th>Date</th><th>Mill / product</th><th>Reference / description</th><th>Shortage kg</th><th>Gain kg</th><th>Ghati after</th><th>Gain carried</th></tr></thead><tbody>
<?php foreach($report['events']as$r):?><tr><td><?=$escape($date($r['date']??''))?></td><td><?=$escape($r['millName']??'')?> · <?=$escape($r['product']??'')?></td><td><?=$escape($r['ref']??'')?><br><?=$escape($r['narration']??'')?></td><td><?=($r['kind']??'')==='shortage'?$number($r['kg']):'—'?></td><td><?=($r['kind']??'')==='gain'?$number($r['kg']):'—'?></td><td><?=$number($r['ghatiAfter'])?></td><td><?=$number($r['gainAfter'])?></td></tr><?php endforeach;?>
<?php if(!$report['events']):?><tr><td colspan="7">No reconciled gain or shortage.</td></tr><?php endif;?></tbody></table></div>
<h2>Fixed production reconciliation rows</h2><p class="note">These rows belong to the management view of the linked production report. They are not shown in Mill entry screens and are excluded from stock, Raw Rice consumption and all purchase postings.</p><div class="table"><table><thead><tr><th>Production date / shift</th><th>Production ID</th><th>Product</th><th>kg</th><th>Control</th></tr></thead><tbody>
<?php foreach($report['fixedProductionRows']as$r):?><tr><td><?=$escape($date($r['appliedDate']??''))?> <?=$escape($r['appliedShift']??'')?></td><td><?=$escape($r['productionId']??'First subsequent report pending')?></td><td><?=$escape($r['product']??'')?></td><td><?=$number($r['kg']??0)?></td><td class="fixed">Last loading excess — fixed / no stock posting</td></tr><?php endforeach;?>
<?php if(!$report['fixedProductionRows']):?><tr><td colspan="5">No fixed reconciliation rows.</td></tr><?php endif;?></tbody></table></div></main></body></html>
