'use strict';

const fs = require('fs');
const assert = require('assert');

const desk = fs.readFileSync('accounts/accounts-accounting-desk.js', 'utf8');
const bundle = fs.readFileSync('accounts/app-bundle.php', 'utf8');
const sodaApi = fs.readFileSync('api/purchase_sodas.php', 'utf8');
const billUi = fs.readFileSync('accounts/bill-smart-ui-v2.js', 'utf8');
const bridge = fs.readFileSync('accounts/source-bridge.js', 'utf8');
const milling = fs.readFileSync('milling/Transtrade_Master_Milling_V3_3_2_AUDITED.html', 'utf8');
const searchApi = fs.readFileSync('api/accounts_search.php', 'utf8');
const auth = fs.readFileSync('auth_store.php', 'utf8');
const dashboardApi = fs.readFileSync('api/accounts_dashboard.php', 'utf8');
const salesTaxApi = fs.readFileSync('api/accounts_sales_tax.php', 'utf8');
const exportDocumentsApi = fs.readFileSync('api/export_documents.php', 'utf8');
const receiptUi = fs.readFileSync('accounts/export-receipts-ui.js', 'utf8');
const receiptFileApi = fs.readFileSync('api/accounts_receipt_file.php', 'utf8');

assert(bundle.includes("'accounts-accounting-desk.js'"), 'professional Accounts desk must be loaded last');
assert(desk.includes("master.id = 'ttMasterTop'"), 'Masters must be available through top-bar M');
assert(desk.includes('New Soda') && desk.includes('Search / Amend Soda'), 'Soda Centre must have New and Search/Amend choices');
assert(desk.includes('Saving a Soda creates an open purchase commitment only'), 'Soda form must explain that no GL entry is made');
assert(desk.includes('Reason for Amendment'), 'Soda amendment reason must be visible and compulsory');
assert(desk.includes("title:'ARRIVAL BILLS'") && !desk.includes("title:'Arrival / Rice Bill'"), 'purchase entry must use the commodity-neutral Arrival Bills label');
assert(!desk.includes('class="btn tt-prev-direct"'), 'duplicate Search Previous button must not appear in the Purchases workspace');
assert(desk.includes('data-soda-delete') && sodaApi.includes("$action === 'delete'"), 'Super Admin must be able to delete an unused Soda from Search/Amend');
assert(billUi.includes('data-open-receipt') && !billUi.includes('type="checkbox" class="ttsb-select"'), 'Arrival Bills must open from a receipt row without tick boxes');
assert(bridge.includes("'POHANCH|' + String(saved.millId") || bridge.includes("'POHANCH|'+String(saved.millId"), 'Pohanch handoff identity must not rely on the reusable printed number');
assert(milling.includes('function editSlip') && milling.includes('Save Amendment'), 'saved unprinted Pohanch must provide an edit workflow');
assert(desk.includes('Search Previous Accounts Entry'), 'every workspace must expose previous-entry search');
assert(desk.includes('Print Voucher'), 'third-party accounting search results must expose voucher print');
assert(desk.includes('Export Receipts & Payments') && desk.includes('Bank Receipt / Credit Advice') && desk.includes('Local Sale Receipts'), 'receipt work must be grouped under the approved broad areas');
assert(desk.includes("title:'Sales Tax'") && !desk.includes("title:'Sales Tax Export File'"), 'report must use the exact Sales Tax name');
assert(desk.includes('const tgAreas') && !desk.includes("key:'tg-purchases'"), 'TG must have the simplified receipt, payment, bank, ledger and report menu without Pakistan purchase workflows');
assert(desk.includes('accounts_dashboard.php') && desk.includes('accounts_sales_tax.php'), 'dashboard summaries and Sales Tax search must use linked read-only endpoints');
assert(dashboardApi.includes("['1110','1120']") || (dashboardApi.includes("$a==='1110'") && dashboardApi.includes("$a==='1120'")), 'dashboard bank summary must come from posted bank and cash ledger lines');
assert(dashboardApi.includes("$a==='1220'") && dashboardApi.includes("$a==='1210'"), 'local and export receivable summaries must come from their posted ledgers');
assert(salesTaxApi.includes('tt_export_documents') && salesTaxApi.includes("$accounts['exportReceipts']"), 'Sales Tax search must link Export documents with Accounts receipts');
assert(exportDocumentsApi.includes("tt_user_can_open_module($user,'Accounts')"), 'Accounts users must be able to read linked Export documents without gaining Export write access');
assert(receiptUi.includes('id="erAdviceFile"') && receiptUi.includes('uploadAdvice'), 'export receipts must accept a bank credit advice upload');
assert(receiptUi.includes('accounts_receipt_file.php') && receiptFileApi.includes('move_uploaded_file'), 'credit advice uploads must use the protected Accounts document endpoint');
assert(receiptUi.includes('bankAdvicePaperRef') && fs.readFileSync('api/export_receipts.php', 'utf8').includes('bankAdvicePaperRef'), 'optional paper advice references must be retained separately from uploaded files');
assert(desk.includes('Freight') && desk.includes('Clearing') && desk.includes('Fumigation') && desk.includes('Inspection') && desk.includes('Transport'), 'shipment bill categories must remain available');
assert(desk.includes(".workspace.tt-clean-modal .accountPreview{display:block!important"), 'live accounting preview must not be hidden');
assert(desk.includes("box.id = 'ttUtilityTreatment'") && desk.includes('Accounting treatment before posting'), 'utility entry must render a live Debit/Credit preview');
assert(desk.includes('Generated automatically'), 'Soda/internal number must be system-generated');
assert(sodaApi.includes("$action === 'amend'"), 'Soda API must support amendments');
assert(sodaApi.includes("'reason'=>$reason") && sodaApi.includes("'changes'=>$changes"), 'Soda audit must retain reason and old/new changes');
assert(sodaApi.includes('tt_purchase_product_profiles()'), 'Soda must use the approved Purchase Product master instead of free-text commodity choices');
assert(searchApi.includes("'voucherNo','journalId','billNo','invoiceNo','sodaNo','pohanch','chequeNo','reference'"), 'universal search must cover accounting and operational references');
assert(searchApi.includes("as_text($row)"), 'universal search must include linked shipment fields such as container, B/L, vessel, line and port');
assert(auth.includes("if (($user['role'] ?? '') === 'Super Admin') return 'index.php'"), 'Super Admin must land in the Control Centre');
assert(auth.includes("if (tt_user_can_open_module($user, 'Accounts')) return 'accounts/index.php'"), 'Accounts staff must still land directly in Accounts');

console.log('Accounts professional desk: passed');
