'use strict';
const fs=require('fs'),assert=require('node:assert/strict'),{chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({headless:true});try{
 const shot=async(locator,name)=>{if(process.env.TT_QA_OUTPUT){fs.mkdirSync(process.env.TT_QA_OUTPUT,{recursive:true});await locator.screenshot({path:process.env.TT_QA_OUTPUT+'/'+name+'.png'});}};
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('http://layout.test/**',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><div id="entityHome"><div id="homeGrid"></div></div><section class="workspace" id="ws-jv"></section><section class="workspace" id="ws-expenses"><div id="expenseEditor"></div></section>'}));await page.goto('http://layout.test/');
 await page.addStyleTag({content:fs.readFileSync('brand-theme.css','utf8')});
 await page.evaluate(()=>{
  localStorage.setItem('tt_accounts_entity','TTI');window.confirm=()=>true;window.posted=[];window.confirmed=[];
  window.TT_ACCOUNT_ACCESS={super:true,csrf:'fixture',masters:{business_parties:[{id:'HKM',values:['Haji Khushi Muhammad','HKM','Supplier','','','','','','','','Active']} ]}};
  window.TT_POST_CONFIRMATION={showJournal:j=>confirmed.push(j),show:ids=>confirmed.push(ids)};
  window.fixture={ok:true,revision:0,canCreate:true,canEdit:true,canDelete:true,canWrite:true,canApprove:true,banks:[{id:'B1',label:'Meezan Bank · 123456',currency:'PKR'}],facilities:[],history:[],payees:[{id:'P1',name:'Haji Khushi Muhammad',configured:true,kind:'BUSINESS',accountCode:'2110'},{id:'P2',name:'Asif Razzak',configured:true,kind:'BUSINESS',accountCode:'2190'}],subaccounts:[],heads:[{code:'2110',name:'Supplier',class:'Liability'},{code:'6900',name:'Office Expense',class:'Expense'}],jvs:[],targets:[],accounts:[{code:'2110',name:'Supplier',requiresSubledger:true},{code:'1120',name:'Petty Cash',requiresSubledger:false}],opening:{allowed:true,enabled:true,management:true,entities:['TTI'],parties:[],entries:[],currency:'PKR',date:'2026-07-01',accounts:[],targets:[],banks:[],balances:[]},salaryMasters:[],salarySheet:{version:0,status:'Draft',rows:{}},paymentAccounts:[]};
  window.fetch=async(url,options={})=>{if(options.body){const b=JSON.parse(options.body);posted.push(b);return {ok:true,json:async()=>({...fixture,result:{journalId:'POST-2026-00999',journal:{id:'POST-2026-00999',lines:[]}}})};}return {ok:true,json:async()=>structuredClone(fixture)};};
 });
 for(const file of ['brand-theme.js','accounts/accounts-clean-ui.js','accounts/master-autocomplete.js','accounts/bank-payment-details.js','accounts/account-management-ui.js','accounts/jv-workflow-ui.js','accounts/rent-salary-ui.js'])await page.addScriptTag({content:fs.readFileSync(file,'utf8')});
 await page.evaluate(()=>TT_BANK_ENTRIES.open());await page.waitForSelector('#amBankForm');
 const form=page.locator('#amBankForm'),party=form.locator('[data-payee-choice]').first().locator('..').locator('input[type=text]').first();
 await party.fill('');await party.press('ArrowDown');assert.equal(await page.locator('.tt-keyboard-active').textContent(),'Haji Khushi Muhammad');await party.press('ArrowDown');await party.press('Enter');assert.equal(await form.locator('[data-payee-choice]').first().inputValue(),'P2');assert.equal(await page.locator('#amBankForm').count(),1);
 const date=form.locator('[name=date]').locator('..').locator('input[type=text]');await date.press('ControlOrMeta+A');await date.pressSequentially('07102026');assert.equal(await date.inputValue(),'07-10-2026');assert.equal(await form.locator('[name=date]').inputValue(),'2026-10-07');
 const typeBox=await form.locator('[name=type]').locator('..').boundingBox(),dateBox=await date.boundingBox();assert(Math.abs(typeBox.y-dateBox.y)<4,'Entry type and date align');
 const row=form.locator('.am-debit-row').first();await row.locator('[data-row-reference]').fill('101');await row.locator('[data-row-narration]').fill('Payment one');await row.locator('[data-debit]').fill('10');await form.locator('[data-add-debit]').click();await form.locator('[data-payee-choice]').nth(1).selectOption('P1');await form.locator('[data-row-reference]').nth(1).fill('102');await form.locator('[data-debit]').nth(1).fill('20');
 assert.equal(await form.locator('[name=amount]').inputValue(),'30.00');assert.equal(await form.locator('[name=amount]').isVisible(),false);assert.equal(await form.locator('[name=reference]').isVisible(),false);
 const boxes=await row.locator(':scope>label').evaluateAll(labels=>labels.map(l=>{const r=l.getBoundingClientRect();return {x:r.x,right:r.right,y:r.y};}));assert(boxes.every(b=>Math.abs(b.y-boxes[0].y)<2));assert(boxes.every((b,i)=>!i||b.x>=boxes[i-1].right),'Payment columns do not overlap');const tops=await row.locator(':scope>label').evaluateAll(labels=>labels.map(l=>l.querySelector('input:not([type=hidden])').getBoundingClientRect().y));assert(tops.every(y=>Math.abs(y-tops[0])<2),'Payment input boxes align');
 await shot(page.locator('.am-box'),'bank-payment-rows');await form.locator('[type=submit]').click();await page.waitForFunction(()=>confirmed.length===1);assert.equal(await page.locator('#amWindow').count(),0,'Only compact confirmation remains');assert.deepEqual(await page.evaluate(()=>posted[0].debitRows.map(r=>[r.chequeNo,r.narration,r.amount])),[['101','Payment one',10],['102','',20]]);
 await page.evaluate(()=>TT_BANK_ENTRIES.open('', 'PETTY_CASH'));await page.waitForSelector('#amBankForm');assert.equal(await form.locator('[name=narration]').isVisible(),false);await form.locator('[name=amount]').fill('50');await form.locator('[type=submit]').click();await page.waitForFunction(()=>confirmed.length===2);assert.equal(await page.evaluate(()=>posted[1].reference),'');
 await page.evaluate(()=>{document.querySelector('#ws-jv').classList.add('active');return TT_JV_WORKFLOW.load();});await page.waitForSelector('.jvw-line');const jv=page.locator('#jvwLines .jvw-line').first();await page.waitForTimeout(60);assert.equal(await jv.locator('.tt-row-remove').count(),1);
 const columns=await jv.locator(':scope>*:not([type=hidden])').evaluateAll(nodes=>nodes.map(n=>{const r=n.getBoundingClientRect();return{x:r.x,right:r.right,y:r.y};}));assert(columns.every((b,i)=>!i||b.x>=columns[i-1].right),'JV columns do not overlap');
 await shot(page.locator('.jvw'),'journal-voucher');await page.evaluate(()=>TT_ACCOUNTS_MASTER_CHOICES.manageParty('Haji Khushi Muhammad'));await page.waitForSelector('#ttPartyInlineEditor[open]');assert(await page.locator('.tt-party-role').count()>5);assert(await page.locator('.tt-party-role').first().evaluate(label=>{const box=label.querySelector('input').getBoundingClientRect(),r=label.getBoundingClientRect();return box.width<24&&Math.abs(box.y+(box.height/2)-r.y-(r.height/2))<3;}));await shot(page.locator('#ttPartyInlineEditor'),'party-roles');await page.locator('#ttPartyInlineEditor [data-cancel]').click();
 await page.evaluate(()=>{document.querySelector('#ws-jv').classList.remove('active');document.querySelector('#ws-expenses').classList.add('active');return TT_RENT_SALARY_UI.open('salary');});await page.waitForSelector('#rsPrepare');assert.equal(await page.locator('#rsMasterSetup,#rsSalaryBack').count(),0);await page.locator('#rsPrepare').click();assert.equal(await page.locator('#rsSalaryBack').count(),0);await shot(page.locator('.ttrs'),'salary-sheet');const plus=await page.locator('#rsAddSheetPerson').boundingBox();assert(plus.x<page.viewportSize().width/2,'Salary add is below rows on the left');

 // The remove cell must not span the row and squeeze every input into 30px.
 await page.evaluate(()=>{const host=document.createElement('div');host.id='ttExpenseDesk';host.innerHTML='<section style="width:1000px"><article class="dex-row" style="display:grid;grid-template-columns:30px minmax(0,1fr);gap:10px"><div class="tt-row-remove-slot"><button class="tt-row-remove">−</button></div><div class="dex-fields" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:14px"><label>Expense type<select><option>Office</option></select></label><label>Purpose<input></label><label>Amount<input></label></div></article></section>';document.body.appendChild(host);});
 const expenseBoxes=await page.locator('#ttExpenseDesk .dex-fields>label').evaluateAll(nodes=>nodes.map(n=>{const r=n.getBoundingClientRect();return {x:r.x,right:r.right,y:r.y,width:r.width};}));
 assert(expenseBoxes.every(b=>Math.abs(b.y-expenseBoxes[0].y)<2&&b.width>190),'Expense type, purpose and amount share one readable row');
 assert(expenseBoxes.every((b,i)=>!i||b.x>=expenseBoxes[i-1].right),'Expense fields do not overlap');
 await page.evaluate(()=>document.querySelector('#ttExpenseDesk').remove());
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>TT_BANK_ENTRIES.open());await page.waitForSelector('#amBankForm');assert((await page.locator('.am-box').boundingBox()).width<=390);assert.equal(await page.locator('.am-box').evaluate(el=>el.scrollWidth<=el.clientWidth+2),true,'Bank form fits mobile');assert.deepEqual(errors,[]);
 console.log('PASS actual date typing, keyboard choice, aligned bank/JV/party controls, row cheques, blank petty cash, one confirmation, salary navigation and mobile');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
