const {chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch(),page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>window.print=()=>{});
 await page.goto(process.argv[2]+'/accounts/index.html');await page.locator('#open').click();await page.locator('#ivNewBroker').click();await page.locator('[name=name]').fill('BMA Capital');await page.locator('[name=accountReference]').fill('BMA-100');await page.getByRole('button',{name:'ADD',exact:true}).click();await page.locator('#ivNewRoute').click();await page.locator('[name=name]').fill('Salman');await page.getByRole('button',{name:'ADD',exact:true}).click();await page.locator('#ivNewPost').click();
 let f=page.locator('#ivEntry');await f.locator('[name=routeId]').selectOption({index:1});await f.locator('[name=reference]').fill('BANK-UI-1');await f.locator('[name=amount]').fill('1000');await f.locator('[name=remuneration]').fill('200');await f.locator('[name=remunerationTreatment]').selectOption('NEW_EXPENSE');await f.locator('[name=bankPaymentMethod]').selectOption('ONLINE_BANKING');if(await f.locator('[name=chequeNo]').isVisible())throw Error('Cheque fields did not hide');if(!(await page.locator('#ivTotal').textContent()).includes('1,200.00'))throw Error('Split transfer total incorrect');await f.getByRole('button',{name:'POST & PRINT VOUCHER',exact:true}).click();await page.locator('#ivNewPost').waitFor();await page.locator('#ivNewPost').click();
 f=page.locator('#ivEntry');await f.locator('[name=type]').selectOption('ROUTE_TO_BROKER');await f.locator('[name=routeId]').selectOption({index:1});await f.locator('[name=brokerId]').selectOption({index:1});await f.locator('[name=reference]').fill('ROUTE-UI-1');await f.locator('[name=amount]').fill('1000');if(await f.locator('[name=paymentAccountId]').isVisible())throw Error('Onward transfer shows company bank');await f.getByRole('button',{name:'POST & PRINT VOUCHER',exact:true}).click();await page.locator('#ivNewPost').waitFor();await page.locator('#ivNewPost').click();
 f=page.locator('#ivEntry');await f.locator('[name=type]').selectOption('BUY');await f.locator('[name=brokerId]').selectOption({index:1});await f.locator('[name=reference]').fill('BUY-UI-1');await f.locator('[name=symbol]').fill('ABC');await f.locator('[name=quantity]').fill('100');await f.locator('[name=price]').fill('5');await f.locator('[name=fees]').fill('10');await f.getByRole('button',{name:'POST & PRINT VOUCHER',exact:true}).click();await page.locator('#ivNewPost').waitFor();if(!(await page.locator('main').textContent()).includes('490.00'))throw Error('Broker balance incorrect');await page.locator('summary').click();await page.locator('[data-iv-reverse]').first().click();await page.locator('[name=reason]').fill('Correct purchase price');await page.getByRole('button',{name:'REVERSE & PRINT VOUCHER',exact:true}).click();await page.locator('#ivNewPost').waitFor();await page.locator('#ivRefresh').click();await page.locator('#ivNewPost').waitFor();if(!(await page.locator('main').textContent()).includes('1,000.00'))throw Error('Reversal balance incorrect');
 await page.screenshot({path:process.env.TT_QA_OUTPUT+'/investments-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:process.env.TT_QA_OUTPUT+'/investments-mobile.png',fullPage:true});if((await page.locator('.iv-window').boundingBox()).width>390)throw Error('Mobile overflow');if(errors.length)throw Error(errors.join('\n'));await browser.close();console.log('Investment browser: masters, split transfer, onward transfer, share purchase, voucher, reversal, reload and mobile layout passed.');
})().catch(e=>{console.error(e);process.exit(1)});
