'use strict';
const fs=require('node:fs'),assert=require('node:assert/strict'),read=p=>fs.readFileSync(p,'utf8');
const master=JSON.parse(read('accounts/accounting_master_v1.json')),api=read('api/expenses_v1.php'),ui=read('accounts/expenses-v1-ui.js'),index=read('accounts/index.php'),bundle=read('accounts/app-bundle.php');
const chart=Object.fromEntries(master.chart.map(x=>[String(x.code),x]));
const utilityAccounts={ELECTRICITY:'6110',GAS:'6120',WATER:'6130',INTERNET:'6140',TELEPHONE_MOBILE:'6150',OTHER_UTILITY:'6190'};
for(const [type,account] of Object.entries(utilityAccounts)){assert.ok(chart[account]);assert.equal(chart[account].class,'Expense');assert.match(api,new RegExp("'"+type+"'=>'"+account+"'"))}
const people=new Set((master.peopleSubledgers||[]).map(x=>x.code));
for(const code of ['FAM-SALMAN','FAM-TALHA','FAM-ABU','FAM-TAYYAB'])assert.ok(people.has(code));
const journal=(debits,total)=>({debits,credit:{account:'1110',amount:total}});
const utilityBusiness=journal([{account:utilityAccounts.ELECTRICITY,amount:125000}],125000);
const utilityHome=journal([{account:'FAM-SALMAN',amount:18000}],18000);
const card=journal([{account:'6900',amount:20000},{account:'6600',amount:15000},{account:'FAM-TALHA',amount:25000}],60000);
for(const entry of [utilityBusiness,utilityHome,card])assert.equal(entry.debits.reduce((s,x)=>s+x.amount,0),entry.credit.amount);
assert.equal(card.debits.filter(x=>x.account.startsWith('FAM-')).reduce((s,x)=>s+x.amount,0),25000);
assert.match(api,/sourceType'=>\$source/);
assert.match(api,/'UTILITY_PAYMENT'/);
assert.match(api,/'CREDIT_CARD_PAYMENT'/);
assert.match(api,/journalCreated'=>true/);
assert.match(api,/ev1_line\('2400',\$total,0/);
assert.match(api,/Credit-card allocations must equal the full statement total/);
assert.match(api,/Paid statements cannot be edited/);
assert.match(api,/A statement already exists for this card and month/);
assert.match(api,/tt_user_can_access_entity/);
assert.match(api,/\['TTI','BRM','TG'\]/);
assert.match(ui,/\.\.\/api\/expenses_v1\.php/);
assert.match(ui,/Total bill/);assert.match(ui,/personalAmounts:readPersonal/);assert.doesNotMatch(ui,/Allocate the full statement/);
assert.match(ui,/FAM-SALMAN/);assert.match(ui,/FAM-TALHA/);assert.match(ui,/FAM-ABU/);assert.match(ui,/FAM-TAYYAB/);
assert.match(index,/app-bundle\.php/);
assert.match(bundle,/'expenses-v1-ui\.js'/);
console.log('Utilities and Credit Cards deterministic QA passed.');

console.log(require('node:child_process').execFileSync('php',['-r',"\nfunction tt_current_user(){return $GLOBALS['fixtureUser'];}\nfunction tt_active_location_masters(){return $GLOBALS['fixtureLocations'];}\nfunction tt_normalize_location_type($v){return $v;}\nfunction tt_location_identity($v){return strtolower(preg_replace('/[^a-z0-9]/i','',$v));}\nrequire 'api/expense_locations.php';\nrequire 'api/accounts_subaccounts_core.php';\nfunction check($ok,$message){if(!$ok)throw new RuntimeException($message);}\n$GLOBALS['fixtureUser']=['role'=>'Accounts','location'=>'All authorized locations'];\n$GLOBALS['fixtureLocations']=[['id'=>'OFFICE','values'=>['Karachi Office','','Office','','','','','TTI']]];\n$home=array_values(array_filter(ev1_owned_locations('TTI'),fn($r)=>$r['location']==='HOME'));\ncheck(count($home)===1&&$home[0]['id']==='HOME|TTI','Shared Home is available');\ncheck(ev1_bill_location(['locationId'=>'HOME|TTI'],'TTI')['location']==='HOME','Home validates at posting');\ntry{ev1_bill_location(['locationId'=>'HOME|TTI'],'BRM');throw new RuntimeException('Cross company accepted');}catch(InvalidArgumentException $e){}\n$GLOBALS['fixtureUser']['location']='Karachi Office';\ncheck(count(ev1_owned_locations('TTI'))===1,'Restricted user retains location scope');\n$GLOBALS['fixtureUser']['location']='All authorized locations';\n$GLOBALS['fixtureLocations'][]=['id'=>'HOME-MASTER','values'=>['Home','','Other','','','','','TTI']];\ncheck(count(array_filter(ev1_owned_locations('TTI'),fn($r)=>$r['location']==='HOME'))===1,'Existing Home reused');\n$journal=['id'=>'2026-00123','date'=>'2026-10-10','entity'=>'TTI','status'=>'Posted','lines'=>[['account'=>'6110','debit'=>100,'credit'=>0,'location'=>'HOME','expenseArea'=>'HOME','expenseFor'=>'SHARED'],['account'=>'1120','debit'=>0,'credit'=>100]]];\n$activity=sac_expense_activity(['journals'=>[$journal]],'TTI','2026-07-01','2027-06-30');\ncheck(count($activity)===1&&$activity[0]['homeLedgerName']==='Combined Home Expense'&&$activity[0]['amount']===100.0,'Utility reports once in Combined Home');\necho 'PASS shared Home location, company/location authority, existing master reuse and combined reporting';\n"],{encoding:'utf8'}));
