'use strict';
const fs=require('fs'),assert=require('node:assert/strict'),{chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));let popups=0;page.on('popup',()=>popups++);
 await page.route('http://batch.test/**',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><style>body{font:14px Arial}input,select{padding:10px}label{display:block}.btn{padding:10px}</style><div id="entityHome"></div><section id="ws-expenses"><div class="panelHead"><h2>Expenses</h2></div><div class="subGrid"></div><div id="expenseEditor"></div></section>'}));await page.goto('http://batch.test/');
 await page.evaluate(()=>{
  window.TT_ACCOUNT_ACCESS={super:true,csrf:'fixture',permissions:'all'};localStorage.setItem('tt_accounts_entity','TTI');window.posts=[];window.printEvents=0;window.windowOpens=0;window.open=()=>{windowOpens++;throw Error('Printing opened a new window');};
  window.books={ok:true,canCreate:true,canEdit:true,canDelete:true,revision:0,paymentAccounts:[{id:'BANK1',label:'Meezan PKR',currency:'PKR',bookBalance:5000,isDefault:2}],banks:[{id:'BANK1',label:'Meezan PKR',currency:'PKR',depositType:'CURRENT'}],history:[],facilities:[],recipientProfiles:[],expenseRecipients:['Talha'],expenseAssets:[],generalExpenses:[],heads:[{code:'6900',name:'Office',class:'Expense',level:'control'},{code:'6910',name:'Home',class:'Expense',level:'control'},{code:'5200',name:'Mill overhead',class:'Expense',level:'control'},{code:'6620',name:'Vehicle Tax',class:'Expense',level:'subaccount'}],subaccounts:[{id:'TTI-EXPENSE-TYPE-OFFICE',name:'Office / Administrative Expense',parentCode:'6900',parentId:'',class:'Expense',active:true,builtinCategory:'OFFICE',expenseClassification:'OFFICE'}],brokers:[],routes:[],holdings:[],transactions:[]};
  const reply=d=>new Response(JSON.stringify(d),{status:200,headers:{'Content-Type':'application/json'}});
  window.fetch=async(url,options={})=>{
   if(!options.body)return reply({...structuredClone(books),...(String(url).includes('accounts_ledger_browser')?{post:window.lastJournal}:{})});const b=JSON.parse(options.body);posts.push(b);
   if(String(url).includes('assets_registry')){const a={id:'CAR-NEW',entity:'TTI',name:b.name,registrationNo:b.registrationNo,type:b.type};books.expenseAssets.push(a);return reply({...books,assets:[a],result:{postId:a.id}});}
   if(String(url).includes('accounts_subaccounts')){if(b.operation==='edit'){const a=books.subaccounts.find(a=>a.id===b.id);a.name=b.name;return reply({...books,result:{subaccountId:a.id}});}const a={id:'SUB-NEW',name:b.name,parentCode:b.parentCode,class:'Expense',active:true,expenseClassification:b.expenseClassification};books.subaccounts.push(a);return reply({...books,result:{subaccountId:a.id}});}
   const journal={id:'POST-2026-00096',publicPostId:'POST-2026-00090',entity:'TTI',date:b.paymentDate||b.date,narration:b.paymentNarration||b.narration||'Annual vehicle tax',lines:[{account:'6620',accountName:'Vehicle Tax & Licence Fees',counterparty:b.payee,debit:Number(b.amount),credit:0},{account:'1110',accountName:'Meezan Bank',debit:0,credit:Number(b.amount)}],totalDebit:Number(b.amount),totalCredit:Number(b.amount)};window.lastJournal=journal;books.generalExpenses=[{...b,id:'GEX-NEW',journalId:journal.id,expenseType:'DIRECT',status:'Posted'}];return reply({...books,result:{generalExpenseId:'GEX-NEW',journalId:journal.id,journal,publicPostId:journal.publicPostId}});
  };
  window.TT_ACCOUNTING_DESK={refreshAttention(){},printVoucher(){throw Error('Post invoked printing');}};
 });
 for(const p of ['accounts/print-dialog.js','accounts/post-confirmation-ui.js','accounts/bank-payment-details.js','accounts/assets-registry-ui.js','accounts/account-management-ui.js','accounts/expense-desk-ui.js','accounts/company-investments-ui.js','brand-theme.js'])await page.addScriptTag({content:fs.readFileSync(p,'utf8')});
 await page.evaluate(()=>{const print=TT_PRINT.html;TT_PRINT.html=html=>{const w=print(html);w.__nativePrint=()=>printEvents++;return w;};TT_EXPENSE_DESK.open();});await page.waitForSelector('#dexPayee');await page.fill('#dexPayee','Talha');await page.selectOption('#dexPayAccountDetails [data-method]','ONLINE_BANKING');await page.selectOption('[data-category]','CAR_REPAIRS');await page.fill('[data-purpose]','Brake pads');await page.fill('[data-amount]','100');assert.equal(await page.locator('#dexPayAccountDetails [data-narration]').inputValue(),'Brake pads');await page.fill('#dexPayAccountDetails [data-narration]','Owner edited narration');await page.fill('[data-purpose]','Brake pads and labour');assert.equal(await page.locator('#dexPayAccountDetails [data-narration]').inputValue(),'Owner edited narration');
 await page.click('[data-new-vehicle]');const vehicle=page.getByRole('dialog',{name:'Add Vehicle',exact:true});await vehicle.locator('[name=name]').fill('Toyota Aqua');await vehicle.locator('[name=registrationNo]').fill('ABC-123');await vehicle.getByRole('button',{name:'Save Vehicle',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[data-asset-id]').value==='CAR-NEW');assert.equal(await page.locator('[data-amount]').inputValue(),'100');assert.equal(await page.locator('[data-purpose]').inputValue(),'Brake pads and labour');assert.equal(await page.locator('#dexPayee').inputValue(),'Talha');
 await page.click('[data-types]');const setup=page.locator('#amWindow');await setup.locator('[name=name]').fill('Home gardening');await setup.locator('[name=classification]').selectOption('HOME');assert.equal(await setup.locator('[name=parent]').inputValue(),'6910');await setup.getByRole('button',{name:'Save Expense Type',exact:true}).click();await page.waitForFunction(()=>Array.from(document.querySelector('[data-category]').options).some(o=>o.value==='SUB|SUB-NEW'));assert.equal(await page.locator('[data-category]').inputValue(),'CAR_REPAIRS');assert.equal(await page.locator('[data-amount]').inputValue(),'100');assert.equal(await page.locator('#dexPayAccountDetails [data-narration]').inputValue(),'Owner edited narration');
 await page.click('[data-types]');await setup.locator('[name=existing]').selectOption('TTI-EXPENSE-TYPE-OFFICE');assert.equal(await setup.locator('[name=classification]').isDisabled(),true);await setup.locator('[name=name]').fill('Office Running Costs');await setup.getByRole('button',{name:'Save Expense Type',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[data-category] option[value=OFFICE]').textContent==='Office Running Costs');assert.equal(await page.locator('[data-category]').inputValue(),'CAR_REPAIRS');assert.equal(await page.locator('[data-amount]').inputValue(),'100');
 await page.selectOption('[data-category]','VEHICLE_TAX');await page.selectOption('[data-asset-id]','CAR-NEW');await page.locator('#dexDate').evaluate(el=>{el.value='2026-10-08';});await page.locator('[data-period-from]').evaluate(el=>el.value='2026-07-01');await page.locator('[data-period-to]').evaluate(el=>el.value='2027-06-30');await page.fill('[data-challan]','CHALLAN-1');assert.equal(await page.locator('#dexDate').locator('..').locator('input[type=text]').inputValue(),'08-10-2026');await page.locator('#dexDate').locator('..').locator('input[type=text]').fill('07-10-2026');await page.locator('#dexDate').locator('..').locator('input[type=text]').press('Tab');assert.equal(await page.locator('#dexDate').inputValue(),'2026-10-07');assert.equal(await page.locator('[data-period-to]').inputValue(),'2027-06-30');
 await page.click('[data-post]');await page.waitForSelector('#tt-post-confirmation');assert.equal(await page.locator('iframe').count(),0,'Posting must not invoke printing');assert.equal(await page.evaluate(()=>windowOpens),0);assert.match(await page.locator('#tt-post-confirmation').textContent(),/00090/);assert.match(await page.locator('#tt-post-confirmation').textContent(),/Debit.*Credit/);assert.equal((await page.evaluate(()=>posts.at(-1))).expenseLines[0].periodTo,'2027-06-30');await page.locator('#tt-post-confirmation [data-print]').click();await page.waitForFunction(()=>printEvents===1);assert.equal(popups,0);assert.equal(await page.evaluate(()=>windowOpens),0);assert.match(await page.locator('iframe').evaluate(el=>el.contentDocument.body.textContent),/07-10-2026/);await page.locator('#tt-post-confirmation [data-close]').click();await page.locator('#ttExpenseDesk [data-close]').click();
 // Petty cash is an explicit bank entry type, with one narration field.
 await page.evaluate(()=>TT_BANK_ENTRIES.open());await page.waitForSelector('#amBankForm');await page.selectOption('#amBankForm [name=type]','PETTY_CASH');assert.equal(await page.locator('#amPayBankDetails [data-narration]').isVisible(),false);await page.fill('#amBankForm [name=amount]','500');await page.fill('#amBankForm [name=reference]','CASH-1');await page.fill('#amBankForm [name=narration]','Petty cash replenishment');await page.selectOption('#amPayBankDetails [data-method]','ONLINE_BANKING');await page.locator('#amBankForm [type=submit]').click();await page.waitForSelector('#tt-post-confirmation');assert.equal((await page.evaluate(()=>posts.at(-1))).type,'PETTY_CASH');assert.equal(await page.evaluate(()=>printEvents),1,'Bank posting must not print');await page.locator('#tt-post-confirmation [data-close]').click();await page.locator('#amWindow [data-close]').click();
 // Dates are transaction columns, separate from a broker balance.
 await page.evaluate(()=>{books.brokers=[{id:'BMA',name:'BMA',active:true,balanceCents:1700000}];books.transactions=[{id:'TX1',date:'2026-10-08',journalId:'POST-2026-00092',type:'FUND_DIRECT',reference:'Transfer',brokerName:'BMA',amountCents:1700000,status:'Posted'}];TT_INVESTMENTS_UI.open('TTI');});await page.waitForSelector('#ivNewPost');assert.match(await page.locator('#ttInvestmentsWindow main').textContent(),/08-10-2026/);assert.equal(await page.locator('#ttInvestmentsWindow section th').filter({hasText:/^Date$/}).count(),1);
 assert.deepEqual(errors,[]);console.log('Expense review browser: inline vehicle/type setup, preserved drafts, narration, ISO storage/DD-MM-YYYY display, explicit post/print, petty cash and broker dates passed.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
