'use strict';
const fs=require('node:fs'),assert=require('node:assert/strict'),read=p=>fs.readFileSync(p,'utf8');
const api=read('api/journal_vouchers.php'),legacy=read('api/accounts.php'),ui=read('accounts/jv-workflow-ui.js'),index=read('accounts/index.php'),master=JSON.parse(read('accounts/accounting_master_v1.json'));
const accounts=new Set(master.chart.map(x=>String(x.code)));
for(const code of ['1400','2140','3200','6900'])assert.ok(accounts.has(code));
const draft={status:'Draft',lines:[{account:'6900',debit:100000,credit:0},{account:'2140',debit:0,credit:100000}]};
assert.equal(draft.lines.reduce((s,x)=>s+x.debit,0),draft.lines.reduce((s,x)=>s+x.credit,0));
const reversal=draft.lines.map(x=>({account:x.account,debit:x.credit,credit:x.debit}));
assert.equal(reversal.reduce((s,x)=>s+x.debit,0),reversal.reduce((s,x)=>s+x.credit,0));
assert.equal(reversal[0].credit,draft.lines[0].debit);

assert.match(api,/'jvDrafts'=>\[\]/);
assert.match(api,/save_draft/);
assert.match(api,/submit_jv/);
assert.match(api,/approve_jv/);
assert.match(api,/reject_jv/);
assert.match(api,/cancel_jv/);
assert.match(api,/reverse_jv/);
assert.match(api,/Pending Approval/);
assert.match(api,/The preparer cannot approve their own JV/);
assert.match(api,/Submitted JV must contain at least two lines and total debit must equal total credit/);
assert.match(api,/Bank and cash movements must use their dedicated payment, receipt or transfer workflow/);
assert.match(api,/This JV reference already exists/);
assert.match(api,/This JV has already been reversed/);
assert.match(api,/flock\(\$h,LOCK_EX\)/);
assert.match(api,/tt_user_can_access_entity/);
assert.doesNotMatch(api,/unset\(\$s\['jvDrafts'\]/);
assert.match(legacy,/Direct JV posting has been retired/);
assert.match(ui,/Submit for Approval/);
assert.match(ui,/Approve & Post/);
assert.match(ui,/JV Register & Audit Trail/);
assert.match(ui,/It will remain in the audit trail/);
assert.match(ui,/Post a complete reversing journal/);
assert.match(index,/jv-workflow-ui\.js\?v=20260911-1/);
console.log('Journal Voucher workflow deterministic QA passed.');
