'use strict';
const fs=require('node:fs'),assert=require('node:assert/strict'),{chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({headless:true});
 try{
  const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('http://fixture.test/**',r=>r.fulfill({contentType:'text/html',body:'<div id="entityHome"><div class="entityHero">Accounts</div><div id="homeGrid"><button class="appCard" data-key="payables">Payables</button></div></div>'}));await page.goto('http://fixture.test/');
  await page.evaluate(()=>{
   localStorage.setItem('tt_accounts_entity','TTI');window.TT_ACCOUNT_ACCESS={role:'Super Admin',csrf:'fixture'};window.printed=[];
   window.open=()=>({document:{write:s=>printed.push(s),close(){}},focus(){},print(){}});
   const rows=[{billId:'A',sourceKey:'A-truck',rowKey:'A|A-truck',group:'Broker A',broker:'Supplier A',postId:'POST-2026-00001',truck:'TRUCK-A',dueDate:'2026-09-05',outstanding:100,held:false},{billId:'A',sourceKey:'A-truck|BROKERAGE',rowKey:'A|A-truck|BROKERAGE',group:'Broker A',broker:'Broker A',postId:'POST-2026-00001',truck:'TRUCK-A',dueDate:'2026-09-05',outstanding:20,held:false},{billId:'B',sourceKey:'B-truck',rowKey:'B|B-truck',group:'Supplier B',broker:'Supplier B',postId:'POST-2026-00002',truck:'TRUCK-B',dueDate:'2026-09-06',outstanding:100,held:false}];
   window.fixture={banks:[{id:'BANK1',bankName:'First Bank',accountTitle:'Company',accountNumber:'123456789',currency:'PKR',availableBalance:150},{id:'BANK2',bankName:'Owner Bank',accountTitle:'Personal',iban:'PK00ABC987654321',currency:'PKR',availableBalance:200}],rows,brokerRows:[],plans:[],adjustments:[],advances:[]};window.commits=[];
   window.fetch=async(url,options={})=>{const b=options.body?JSON.parse(options.body):null;if(!b)return {ok:true,json:async()=>({ok:true,...structuredClone(fixture)})};commits.push(b);let result={};if(b.action==='create'){const groups={};for(const row of fixture.rows)if(b.rowKeys.includes(row.rowKey)){groups[row.group]??={rowKeys:[],settlementId:''};groups[row.group].rowKeys.push(row.rowKey)}const plan={id:'PLAN-2026-000001',entity:'TTI',mode:b.mode,bankIds:b.bankIds,status:'Open',version:1,groups};fixture.plans=[plan];result={plan:structuredClone(plan)}}else{const plan=fixture.plans[0];if(b.drafts)plan.drafts=structuredClone(b.drafts);if(b.action==='post'){const allocations=fixture.rows.filter(r=>b.rowKeys.includes(r.rowKey)).map(r=>({...r,amount:r.outstanding,balanceAfter:0}));const set={id:'SP-'+b.group,date:b.date,broker:b.group,journalId:'POST-2026-00100',netPayment:allocations.reduce((n,r)=>n+r.amount,0),allocations,sources:b.sources.map(s=>({...s,label:s.bankAccountId||s.payer}))};if(plan.drafts)delete plan.drafts[b.group];plan.groups[b.group].settlementId=set.id;plan.groups[b.group].voucher=set;fixture.rows=fixture.rows.filter(r=>!b.rowKeys.includes(r.rowKey));result={settlement:set}}else if(b.action==='correct'){const g=plan.groups[b.group];fixture.rows.push(...g.voucher.allocations.map(r=>({...r,outstanding:r.amount})));g.settlementId='';delete g.voucher;}else if(b.action==='change'){if(!b.rowKeys.length)delete plan.groups[b.group];else plan.groups[b.group].rowKeys=b.rowKeys;}else if(b.action==='close'){fixture.plans=[];}plan.version++;result.plan=structuredClone(plan)}return {ok:true,json:async()=>({ok:true,result})};};
  });
  await page.addScriptTag({content:fs.readFileSync('accounts/payment-plans-ui.js','utf8')});await page.waitForSelector('[data-home-plan]');await page.click('[data-home-plan]');await page.waitForSelector('[data-plan-bank]');
  assert.deepEqual(await page.locator('.tt-plan-bank b').allTextContents(),['First Bank · …456789','Owner Bank · …654321']);
  await page.check('[data-plan-bank="BANK1"]');assert.match(await page.locator('#ttPlanNote').textContent(),/05-09-2026/);assert.equal(await page.locator('[data-day="2026-09-05"]:checked').count(),2);assert.equal(await page.locator('[data-day="2026-09-06"]:checked').count(),0);
  await page.check('[data-plan-bank="BANK2"]');assert.match(await page.locator('#ttPlanNote').textContent(),/06-09-2026/);
  await page.locator('details[data-open-key="date:2026-09-05"] > summary').click();await page.locator('.tt-plan-party').first().locator('summary').click();
  assert.equal(await page.locator('tbody tr').count(),2,'included brokerage remains in a single truck row');
  await page.uncheck('[data-party="Broker A"]');assert.equal(await page.locator('[data-row]:checked').count(),1);await page.click('[data-print-plan]');let print=await page.evaluate(()=>printed.at(-1));assert.match(print,/TRUCK-B/);assert.doesNotMatch(print,/TRUCK-A/);
  await page.check('[data-party="Broker A"]');await page.click('[data-confirm-plan]');await page.waitForSelector('[data-party-card]');assert.equal(await page.locator('[data-party-card]').count(),2);assert.equal(await page.locator('[data-resume-plan]').count(),1);
  await page.locator('[data-party-card="Supplier B"] [data-source-reference]').fill('1002');
  let card=page.locator('[data-party-card="Broker A"]');await card.locator('[data-source-reference]').fill('1001');await card.locator('[data-post-party]').click();await page.waitForSelector('[data-party-card="Broker A"] [data-correct]');
  assert.equal(await page.locator('#ttPlanComplete').count(),0,'remaining supplier prevents completion');await page.waitForFunction(()=>printed.at(-1).includes('TRUCK-A')||document.querySelector('.tt-plan-error')?.textContent);assert.equal(await page.locator('.tt-plan-error').textContent(),'');assert.match(await page.evaluate(()=>printed.at(-1)),/TRUCK-A/);
  await page.click('[data-plan-close]');await page.click('[data-resume-plan]');await page.waitForSelector('[data-party-card="Broker A"] [data-correct]');assert.equal(await page.locator('[data-party-card="Broker A"] [data-post-party]').count(),0,'posted payment survives reopening');assert.equal(await page.locator('[data-party-card="Supplier B"] [data-source-reference]').inputValue(),'1002','next party draft survives posting and reopening');
  await page.locator('[data-party-card="Supplier B"] [data-source-reference]').fill('1002-SAFE');page.once('dialog',d=>d.accept('Correct first cheque'));await page.click('[data-party-card="Broker A"] [data-correct]');await page.waitForSelector('[data-party-card="Broker A"] [data-post-party]');assert.equal(await page.locator('[data-party-card="Supplier B"] [data-source-reference]').inputValue(),'1002-SAFE','another party draft survives a correction');card=page.locator('[data-party-card="Broker A"]');await card.locator('[data-source-reference]').fill('1001-NEW');await card.locator('[data-post-party]').click();await page.waitForFunction(()=>printed.at(-1).includes('TRUCK-A')||document.querySelector('.tt-plan-error')?.textContent);assert.equal(await page.locator('.tt-plan-error').textContent(),'');
  card=page.locator('[data-party-card="Supplier B"]');await card.locator('[data-source-bank]').selectOption('BANK2');await card.locator('[data-source-reference]').fill('1002');await card.locator('[data-post-party]').click();await page.waitForSelector('#ttPlanComplete');await page.click('[data-edit-complete]');assert.equal(await page.locator('[data-party-card="Supplier B"] [data-correct]').count(),1);
  page.once('dialog',d=>d.accept('Correct cheque'));await page.click('[data-party-card="Supplier B"] [data-correct]');await page.waitForSelector('[data-party-card="Supplier B"] [data-post-party]');
  card=page.locator('[data-party-card="Supplier B"]');await card.locator('[data-add-source]').click();assert.equal(await card.locator('[data-source]').count(),2);await card.locator('[data-source]').nth(1).locator('[data-source-type]').selectOption('THIRD_PARTY');assert.equal(await card.locator('[data-source]').nth(1).locator('[data-source-payer]').isVisible(),true);assert.equal(await card.locator('[data-source]').nth(1).locator('[data-source-method]').inputValue(),'DIRECT');await card.locator('[data-source]').nth(1).locator('[data-source-method]').selectOption('CHEQUE');
  await card.locator('[data-source]').nth(1).locator('[data-remove-source]').click();await card.locator('[data-source-bank]').selectOption('BANK2');await card.locator('[data-source-reference]').fill('1003');await card.locator('[data-post-party]').click();await page.waitForSelector('#ttPlanComplete');await page.click('[data-close-complete]');await page.waitForSelector('#ttPaymentPlanOverlay',{state:'detached'});assert.equal(await page.locator('#ttActivePaymentPlans').isVisible(),false);assert.deepEqual(errors,[]);
  console.log('PASS bank tails, multi-bank due coverage, hierarchical ticks, combined bill brokerage, selected printing, saved resume, correction, third-party fields and final plan closure');
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
