'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),{chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({headless:true});try{
 const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('http://register.test/**',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><html><body></body></html>'}));await page.goto('http://register.test/');
 await page.evaluate(()=>{
  localStorage.setItem('tt_accounts_entity','TTI');window.TT_ACCOUNT_ACCESS={super:true,csrf:'fixture'};window.sent=[];window.confirmed=[];window.alert=()=>{};window.prompt=()=> 'Duplicate posting entered';window.TT_POST_CONFIRMATION={show:ids=>confirmed.push(ids)};
  window.opening={id:'POST-2026-00075',entity:'TTI',date:'2026-07-01',sourceType:'OPENING_BALANCE_BF',status:'Posted',reference:'Legacy reference',narration:'OPENING BALANCE B/F',meta:{openingBalance:true},lines:[{account:'2110',accountName:'Supplier',subledger:'Haji Khushi Muhammad',credit:100,debit:0},{account:'3400',accountName:'Opening Balance Clearing',memo:'OPENING BALANCE B/F',debit:100,credit:0}],totalDebit:100,totalCredit:100};
  window.fetch=async(url,options={})=>{let body;if(options.body){const b=JSON.parse(options.body);sent.push(b);body={ok:true,result:b.action==='delete_post'?{publicPostId:b.postId,status:'Deleted'}:{replacementPostId:'POST-2026-00096',publicPostId:b.postId}};}else if(String(url).includes('accounts_search'))body={ok:true,results:[]};else if(String(url).includes('postId='))body={ok:true,post:structuredClone(opening),bankAccounts:[]};else body={ok:true,entity:'TTI',currency:'PKR',accounts:[{code:'2110',name:'Supplier'},{code:'3400',name:'Opening Balance Clearing'}],parties:['Haji Khushi Muhammad'],partyAliases:[{name:'Haji Khushi Muhammad',code:'HKM',label:'Haji Khushi Muhammad (HKM)'}],rows:[{voucher:opening.id,publicPostId:opening.id,date:opening.date,account:'POSTS',accountName:'TTI',narration:opening.narration,party:'Haji Khushi Muhammad',debit:100,credit:100,canDelete:true}],opening:0,closing:0};return {ok:true,json:async()=>body};};
 });
 await page.addScriptTag({content:fs.readFileSync('accounts/all-ledgers-ui.js','utf8')});await page.evaluate(()=>TT_ALL_LEDGERS.open('POSTS'));
 await page.waitForSelector('[data-amend-id]');assert.equal(await page.locator('.tal-ledger th').count(),7);assert.equal(await page.locator('#tal-view').count(),0,'Register is a separate view');
 await page.locator('[data-amend-id]').click();await page.waitForSelector('#tal-save');assert.equal(await page.locator('#tal-date').inputValue(),'2026-07-01');assert(await page.locator('#tal-date').evaluate(e=>e.readOnly));assert.equal(await page.locator('.tal-details').nth(1).inputValue(),'','Clearing memo must not become a party');assert.equal(await page.locator('#tal-reference').isVisible(),false);assert.equal(await page.locator('#tal-add').isVisible(),false);assert.equal(await page.locator('.tal-remove:visible').count(),0);
 await page.locator('.tal-credit').first().fill('150');await page.locator('.tal-debit').nth(1).fill('150');await page.locator('#tal-reason').fill('Correct opening figure');await page.locator('#tal-save').click();await page.waitForFunction(()=>confirmed.length===1);assert.equal(await page.evaluate(()=>sent[0].lines[1].subledger),'');assert.equal(await page.evaluate(()=>confirmed[0][0]),'POST-2026-00096');
 await page.locator('[data-delete-id]').click();await page.waitForFunction(()=>sent.some(b=>b.action==='delete_post'));assert.equal(await page.evaluate(()=>sent.at(-1).reason),'Duplicate posting entered');
 await page.evaluate(()=>TT_ALL_LEDGERS.open('','other'));await page.waitForSelector('#tal-view');await page.locator('#tal-view').selectOption('party');await page.waitForSelector('#tal-party');assert(await page.locator('#tal-parties').evaluate(e=>e.innerHTML.includes('HKM')));
 assert.deepEqual(errors,[]);console.log('PASS separate Post ID register, opening correction form, refreshed confirmation, party aliases and audited deletion request');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
