'use strict';
const fs=require('node:fs'),assert=require('node:assert/strict'),{chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({headless:true});try{
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('http://fixture.test/**',r=>r.fulfill({contentType:'text/html',body:'<div id="entityHome"><div id="homeGrid"><button class="appCard" data-key="purchases"><h3>Purchases</h3><p>Purchases</p></button></div></div><section class="workspace active" id="ws-purchases"><div class="panelHead"><h2>Purchases</h2></div><div class="subGrid"><button data-purchase="other">Other</button></div><div id="purchaseEditor"></div></section>'}));await page.goto('http://fixture.test');
 await page.evaluate(()=>{localStorage.setItem('tt_accounts_entity','TTI');window.TT_ACCOUNT_ACCESS={csrf:'fixture',super:true};window.waiting=[];window.posts=[];window.TT_FORM_VIEWPORT={open:()=>{}};window.fetch=async(url,opts={})=>{const company=new URL(url,location.href).searchParams.get('entity')||localStorage.getItem('tt_accounts_entity');if(opts.body){posts.push(JSON.parse(opts.body));return{ok:true,json:async()=>({ok:true,result:{id:'BILL',status:'Posted',journalId:'POST1'}})};}if(url.includes('bag_purchases')||url.includes('commodity_lookup')||url.includes('other_purchases'))return new Promise(resolve=>waiting.push({url,company,resolve}));return{ok:true,json:async()=>({ok:true,attention:[],sodas:[]})};};window.finish=(match,company)=>{const i=waiting.findIndex(r=>r.url.includes(match)&&(!company||r.company===company));if(i<0)throw Error('Missing request '+match);const r=waiting.splice(i,1)[0];r.resolve({ok:true,json:async()=>({ok:true,entity:r.company,bills:[],purchaseOrders:[],taxRates:[{effectiveDate:'2026-07-01',rate:18}],bagSuppliers:[{name:'BAG SUPPLIER'}],receipts:[],sodas:[],rows:[],banks:[],fixedAssets:[]})});};});
 for(const file of ['accounts/accounts-v1-workflow-ui.js','accounts/bill-smart-ui-v2.js','accounts/purchase-commodity-split-ui.js','accounts/bag-ops-sync-ui.js','accounts/bag-purchases-ui.js','accounts/other-purchases-ui.js'])await page.addScriptTag({content:fs.readFileSync(file,'utf8')});
 // Native Purchases timer (170 ms) must not replace Bags opened during that delay.
 await page.click('.appCard[data-key=purchases]');await page.waitForSelector('[data-purchase=bags]');await page.click('[data-purchase=bags]');await page.evaluate(()=>finish('bag_purchases'));await page.waitForSelector('#bgPurpose');await page.waitForTimeout(300);assert.equal(await page.locator('#bgPurpose').count(),1);assert.equal(await page.locator('.ttps-home').count(),0);
 // General bag form posts the actual fields without PO dependencies.
 await page.selectOption('#bgPurpose','GENERAL');await page.selectOption('#bgSupplier','BAG SUPPLIER');await page.fill('#bgInvoice','LOCAL-UI');await page.fill('#bgBagType','PP');await page.fill('#bgQty','100');await page.fill('#bgRate','20');await page.check('#bgSalesTaxInvoice');assert.equal(await page.locator('#bgTotal').innerText(),'Rs 2,360');await page.click('#bgSave');await page.waitForFunction(()=>posts.length===1);const posted=await page.evaluate(()=>posts[0]);assert.equal(posted.action,'create_general_bill');assert.equal(posted.poNo,undefined);assert.equal(posted.bags,100);await page.evaluate(()=>finish('bag_purchases'));await page.waitForSelector('#bgPurpose');
 // A late Bags request cannot overwrite Other Purchases.
 await page.evaluate(()=>{void TT_BAG_PURCHASES_UI.mount();});await page.click('[data-purchase=other]');await page.waitForFunction(()=>waiting.some(x=>x.url.includes('other_purchases')));await page.evaluate(()=>finish('other_purchases'));await page.waitForSelector('#opPost');await page.fill('#opSupplier','KEEP THIS');await page.evaluate(()=>finish('bag_purchases'));await page.waitForTimeout(60);assert.equal(await page.locator('#opSupplier').inputValue(),'KEEP THIS');
 // Late commodity success or failure must not steal Bags.
 await page.evaluate(()=>{document.querySelector('#purchaseEditor').dataset.ttPurchaseMode='arrival';void TT_SMART_COMMODITY_BILLS_V2.mount();});await page.click('[data-purchase=bags]');await page.evaluate(()=>finish('bag_purchases'));await page.waitForSelector('#bgPurpose');await page.evaluate(()=>finish('commodity_lookup'));await page.waitForTimeout(80);assert.equal(await page.locator('#bgPurpose').count(),1);
 // A pending request for another company cannot replace the current company's form.
 await page.evaluate(()=>{void TT_BAG_PURCHASES_UI.mount();localStorage.setItem('tt_accounts_entity','BRM');void TT_BAG_PURCHASES_UI.mount();});await page.evaluate(()=>finish('bag_purchases','BRM'));await page.waitForSelector('#bgPurpose');await page.selectOption('#bgPurpose','GENERAL');await page.fill('#bgInvoice','BRM DRAFT');await page.evaluate(()=>finish('bag_purchases','TTI'));await page.waitForTimeout(60);assert.equal(await page.locator('#bgInvoice').inputValue(),'BRM DRAFT');assert.deepEqual(errors,[]);
 console.log('Purchase icons: delayed native handler, Bags/Other/commodity navigation, local bag posting and company-change races passed');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
