'use strict';
const fs=require('node:fs'),assert=require('node:assert/strict'),{chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({headless:true});try{
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('http://supplier.test/**',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><html><body></body></html>'}));await page.goto('http://supplier.test/');
 await page.evaluate(()=>{localStorage.setItem('tt_accounts_entity','TTI');window.TT_ACCOUNT_ACCESS={csrf:'fixture'};window.posts=[];window.TT_FORM_VIEWPORT={open:()=>{}};
 window.fixtureRows=[{billId:'BF:OPEN:0',sourceKey:'OPENING|0',supplier:'MAPCO',category:'OPENING',openingBalance:true,billNo:'Balance B/F',billDate:'2026-07-01',total:308345,paid:0,outstanding:308345},{billId:'BILL',sourceKey:'SERVICE|BILL',supplier:'MAPCO',category:'CLEARING',billNo:'4233',billDate:'2026-07-11',total:382155,paid:0,outstanding:382155},{billId:'LOCAL',sourceKey:'OPENING|0',supplier:'LOCAL SUPPLIER',category:'OPENING',openingBalance:true,billNo:'Balance B/F',billDate:'2026-07-01',total:100,paid:0,outstanding:100}];
 window.fetch=async(url,options={})=>{if(options.body){const b=JSON.parse(options.body);posts.push(b);return{ok:true,json:async()=>({ok:true,result:{journalId:'POST',netPayment:b.amount,date:b.date},transaction:{journalId:'POST',amountNative:b.amountNative,date:b.date,liabilityAllocations:[]}})};}return{ok:true,json:async()=>String(url).includes('tg_bank_transactions')?{ok:true,banks:[],openLiabilities:[{id:'BF:TG:0',openingBalance:true,source:'Balance B/F',counterparty:'TG SUPPLIER',reference:'Balance B/F',billDate:'2026-07-01',currency:'AED',originalNative:300,outstandingNative:300},{id:'TG-BILL',source:'Supplier / Service Bill',counterparty:'TG SUPPLIER',reference:'BILL',billDate:'2026-07-11',currency:'AED',originalNative:200,outstandingNative:200}]}:String(url).includes('supplier_settlements')?{ok:true,payables:fixtureRows}:{ok:true,accounts:[]}};};});
 await page.addScriptTag({content:fs.readFileSync('accounts/supplier-settlement-ui.js','utf8')});await page.evaluate(()=>TT_SUPPLIER_SETTLEMENT_UI.openBills('CLEARING','MAPCO','BILL'));
 assert.equal(await page.locator('[data-bill]').count(),1,'Opening excluded until explicitly ticked');await page.fill('[data-amount]','690500');await page.check('[data-include-opening]');assert.equal(await page.locator('[data-amount]').inputValue(),'690500');assert.match(await page.locator('.tt-bill-grand').innerText(),/690,500/);assert.equal(await page.locator('[data-bill]:disabled').count(),1);
 await page.selectOption('[data-source]','CASH');await page.fill('[data-narration]','Keep this draft');await page.uncheck('[data-include-opening]');assert.equal(await page.locator('[data-narration]').inputValue(),'Keep this draft');await page.check('[data-include-opening]');await page.click('[type=submit]');await page.waitForFunction(()=>posts.length===1);
 assert.deepEqual(await page.evaluate(()=>posts[0].selectedBills),['BF:OPEN:0|OPENING|0','BILL|SERVICE|BILL']);assert.equal(await page.evaluate(()=>posts[0].includeOpeningBalance),true);
 // A supplier with only an opening balance can be settled too.
 await page.evaluate(()=>TT_SUPPLIER_SETTLEMENT_UI.openBills('OTHER','LOCAL SUPPLIER'));await page.check('[data-include-opening]');await page.fill('[data-amount]','50');assert.match(await page.locator('.tt-bill-grand').innerText(),/PKR 50/);
 // Same tick uses AED openings in the existing TG payment route.
 await page.evaluate(()=>{localStorage.setItem('tt_accounts_entity','TG');return TT_SUPPLIER_SETTLEMENT_UI.openBills('','TG SUPPLIER','TG-BILL');});assert.equal(await page.locator('[data-currency]').inputValue(),'AED');await page.check('[data-include-opening]');await page.fill('[data-amount]','500');await page.selectOption('[data-source]','CASH');await page.click('[type=submit]');await page.waitForFunction(()=>posts.length===2);assert.deepEqual(await page.evaluate(()=>posts[1].selectedBills),['BF:TG:0','TG-BILL']);assert.equal(await page.evaluate(()=>posts[1].includeOpeningBalance),true);assert.deepEqual(errors,[]);
 console.log('Supplier B/F browser: explicit tick, saved drafts, specific bills, opening-only suppliers and TG currency passed.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
