'use strict';
const fs=require('node:fs'),assert=require('node:assert/strict'),{chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1100,height:800}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('http://fixture.test/**',r=>r.fulfill({contentType:'text/html',body:'<div id="entityHome"></div><section id="ws-expenses"><div id="expenseEditor">OLD FORM</div></section>'}));await page.goto('http://fixture.test');await page.addStyleTag({content:fs.readFileSync('brand-theme.css','utf8')});
  await page.evaluate(()=>{window.TT_ACCOUNT_ACCESS={super:true,csrf:'fixture'};localStorage.setItem('tt_accounts_entity','TTI');window.requests=[];window.fixture={ok:true,generalExpenses:[],heads:[],subaccounts:[],utilityMasters:[],utilityPayments:[],reimbursements:[],creditCardMasters:[{id:'CARD1',status:'Active',cardName:'Company Visa',holder:'Salman',last4:'4321',dueDay:20}],creditCardStatements:[],reminders:[],locations:[{id:'OFFICE',name:'Office',location:'OFFICE'},{id:'HOME',name:'Home',location:'HOME'}],paymentAccounts:[{id:'CASH|TTI',label:'Cash',currency:'PKR',bookBalance:100000}],personalLinks:[]};window.fetch=async(url,options={})=>{if(options.body){const b=JSON.parse(options.body);requests.push(b);await new Promise(r=>setTimeout(r,40));if(['save_card_statement','post_and_pay_card_statement'].includes(b.action))fixture.creditCardStatements=[{id:'BILL1',simpleStatement:true,cardName:'Company Visa',last4:'4321',status:b.action==='post_and_pay_card_statement'?'Paid':'Pending',...b}];if(b.action==='pay_card_statement')fixture.creditCardStatements[0].status='Paid';if(b.action==='save_card_adjustments')fixture.creditCardStatements[0].personalAmounts=b.personalAmounts;return{ok:true,json:async()=>({...structuredClone(fixture),result:{statementId:'BILL1',journalId:'2026-00100'}})};}return{ok:true,json:async()=>structuredClone(fixture)};};});
  for(const path of ['accounts/expense-editor-owner.js','accounts/bank-payment-details.js','accounts/expenses-v1-ui.js','accounts/expense-desk-ui.js','brand-theme.js'])await page.addScriptTag({content:fs.readFileSync(path,'utf8')});
  await page.evaluate(()=>TT_EXPENSE_DESK.open());await page.waitForSelector('#dexPayee');assert.equal(await page.locator('[data-expense-mode]').count(),3);
  await page.fill('#dexNarration','School fee');assert.equal(await page.locator('[data-purpose]').inputValue(),'School fee');await page.click('[data-add]');assert.equal(await page.locator('[data-purpose]').nth(1).inputValue(),'');await page.fill('#dexNarration','School fee October');assert.equal(await page.locator('[data-purpose]').first().inputValue(),'School fee October');assert.equal(await page.locator('[data-purpose]').nth(1).inputValue(),'');await page.locator('[data-remove]').last().click();
  await page.fill('#dexPayee','CAS');await page.selectOption('[data-category]','HOME');await page.selectOption('[data-home-ledger]','FAM-TALHA');assert.equal(await page.locator('[data-area]').inputValue(),'HOME');assert.equal(await page.locator('[data-area]').isVisible(),false);assert.equal(await page.locator('[data-for]').isVisible(),false);assert.equal(await page.locator('[data-home-ledger] option').count(),4);await page.selectOption('[data-category]','ARP');assert.equal(await page.locator('[data-for]').inputValue(),'FAM-ABU');assert.equal(await page.locator('[data-home-wrap]').isVisible(),false);assert.equal(await page.locator('[data-arp-wrap]').isVisible(),true);await page.selectOption('[data-category]','HOME');assert(await page.locator('[data-personal-wrap]').isVisible());await page.selectOption('[data-personal-treatment]','REMUNERATION');
  await page.click('[data-expense-mode=card]');await page.waitForSelector('#evAddStatement');assert.equal(await page.locator('#ttExpenseDesk #evStatementTotal').count(),1);
  await page.click('#evAddStatement');assert.equal(await page.locator('.tte-alloc').count(),0,'no transaction-by-transaction breakdown');assert.equal((await page.locator('#evDueDate').inputValue()).slice(8),'20');assert.equal(await page.locator('#evPersonalRows').isVisible(),false);
  await page.fill('#evStatementTotal','100000');await page.check('#evPersonalEnabled');const talha=page.locator('[data-person="FAM-TALHA"]');await talha.locator('[data-tick]').check();await talha.locator('[data-person-amount]').fill('15000');const salman=page.locator('[data-person="FAM-SALMAN"]');await salman.locator('[data-tick]').check();await salman.locator('[data-person-amount]').fill('10000');await salman.locator('[data-person-treatment]').selectOption('CASH');
  await page.evaluate(()=>{document.querySelector('#evStatementSave').click();document.querySelector('#evStatementSave').click();});await page.waitForFunction(()=>!document.querySelector('#ttExpenseDesk'));let bodies=await page.evaluate(()=>requests);assert.equal(bodies.length,1,'double Post saves once');assert.equal(bodies[0].total,'100000');assert.equal(bodies[0].simpleStatement,true);assert.equal(bodies[0].personalAmounts.length,2);assert.equal(bodies[0].personalAmounts[0].amount,'10000');assert.equal(bodies[0].personalAmounts.find(r=>r.expenseFor==='FAM-TALHA').amount,'15000');assert.equal(bodies[0].allocations,undefined);
  assert.equal(bodies[0].action,'post_and_pay_card_statement');assert.equal(bodies[0].paymentAccountId,'CASH|TTI');await page.evaluate(()=>TT_EXPENSE_DESK.open('','card'));await page.waitForSelector('[data-card-adjust]');assert.equal(await page.locator('thead th').filter({hasText:/^Actions$/}).count(),1,'one action column');
  await page.locator('.tte-history').filter({hasText:'Personal Cash Recoveries'}).evaluate(el=>el.open=true);
  await page.click('[data-card-adjust]');await page.fill('#evCardAdjustReason','Correct personal amount');await page.fill('#evPayPersonalRows [data-person="FAM-TALHA"] [data-person-amount]','20000');await page.click('#evCardPayment [data-save]');await page.waitForFunction(()=>requests.length===2);bodies=await page.evaluate(()=>requests);assert.equal(bodies[1].action,'save_card_adjustments');assert.equal(bodies[1].personalAmounts.find(r=>r.expenseFor==='FAM-TALHA').amount,'20000');
  await page.waitForFunction(()=>!document.querySelector('#ttExpenseDesk')?.dataset.busy||document.querySelector('#ttExpenseDesk').dataset.busy==='0');await page.click('[data-expense-mode=utility]');await page.waitForSelector('#evPayUtility');assert.equal(await page.locator('#evUtilityFor').inputValue(),'SHARED');assert.equal(await page.locator('#evUtilityPersonalWrap').isVisible(),false);await page.selectOption('#evPayLocName','HOME');await page.selectOption('#evUtilityFor','FAM-TALHA');assert(await page.locator('#evUtilityPersonalWrap').isVisible());
  assert.deepEqual(errors,[]);console.log('Unified Pay Expense, beneficiary fields, simple card bill, personal ticks, payment and later adjustments passed.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
