const fs=require('fs'),assert=require('assert');
const modulePhp=fs.readFileSync(__dirname+'/../module.php','utf8');
const accounts=fs.readFileSync(__dirname+'/../accounts/accounts-accounting-desk.js','utf8');
const auth=fs.readFileSync(__dirname+'/../auth_store.php','utf8');
const customerMaster=fs.readFileSync(__dirname+'/../customer-master.js','utf8');
const exportIndex=fs.readFileSync(__dirname+'/../exports/index.html','utf8');
const milling=fs.readFileSync(__dirname+'/../milling/Transtrade_Master_Milling_V3_3_2_AUDITED.html','utf8');
const indexPhp=fs.readFileSync(__dirname+'/../index.php','utf8');
const adminApp=fs.readFileSync(__dirname+'/../admin/app.js','utf8');
const accountsCleanUi=fs.readFileSync(__dirname+'/../accounts/accounts-clean-ui.js','utf8');
const exportsApp=fs.readFileSync(__dirname+'/../exports/app.js','utf8');
const directorsIndex=fs.readFileSync(__dirname+'/../directors/index.php','utf8');
const directorsTg=fs.readFileSync(__dirname+'/../directors/tg-master.js','utf8');
const stateDeclaration=adminApp.indexOf('let state = loadState()');

assert.match(modulePhp,/getElementById\('ttMasterTop'\)\|\|document\.getElementById\('masterTop'\)/,'shared header reuses the existing Exports M');
assert.match(modulePhp,/master\.id='ttMasterTop'/);
assert.match(modulePhp,/master\.textContent='M'/);
assert.doesNotMatch(modulePhp,/if\(c\.masterAccess\)/,'ordinary module users always receive M');
assert.doesNotMatch(modulePhp,/getElementById\('ttMasterTop'\)\?\.remove/,'M is not removed from read-only users');
assert.match(modulePhp,/top\.insertBefore\(master,date\)/,'M remains immediately before the date');
assert.match(modulePhp,/window\.location\.href='\/index\.php\?view=masters&from='\+encodeURIComponent\(c\.moduleId\)/,'Mill and Exports preserve their module origin');
assert.match(modulePhp,/#ttMasterTop[^}]*font:900 18px\/1 Arial/,'M remains bold');
assert.match(accounts,/const master = document\.createElement\('button'\)/,'Accounts always creates M');
assert.match(accounts,/window\.location\.href='\/index\.php\?view=masters&from=accounts'/,'Accounts preserves its module origin');
assert.doesNotMatch(accounts,/access\.masterAccess \? document\.createElement\('button'\)/,'Accounts does not permission-gate visibility');
assert.match(auth,/if \(!empty\(\$user\['master_access'\]\)\) return in_array\(\$action,\(array\)\(\$user\['master_permissions'\]\[\$type\] \?\? \[\]\),true\)/,'an explicit Super Admin matrix limits master access');
assert.match(auth,/'Accounts'=>\['companies','banks','export_realization_charges'/,'Accounts has its financial master scope by default');
assert.match(auth,/return in_array\(\$action,\['Use','View'\],true\)/,'accounts without an explicit matrix receive scoped read-only master access');
assert.match(customerMaster,/window\.TTOpenMasterData=openManager/);
assert.match(exportIndex,/customer-master\.js\?v=20260930-active-parties-1/);
assert.doesNotMatch(milling,/data-home-role="admin-only" onclick="openPanel\('masters'\)"/,'Milling has no separate Master Data tile');
assert.match(milling,/<section id="masters" class="panel">/,'the existing workspace remains available behind M');
assert.match(indexPhp,/tt_user_can_open_module\(\$user, \$moduleHomes\[\$requestedModule\]\['permission'\]\)/,'return destinations are permission validated server-side');
assert.match(adminApp,/back\.id='masterBackTop'/,'ordinary Master Records renders a Close control');
assert.match(adminApp,/Close Master Records and return to/,'the Close control names its originating module destination');
assert.match(adminApp,/topActions\.prepend\(back\)/,'the staff Close control stays in the top-right action area');
assert.match(accountsCleanUi,/button\.textContent = '× Close'/,'Accounts forms use the standard Close control');
assert.match(accountsCleanUi,/if \(activeGroup\?\.items\) openGroup\(activeGroup\)/,'closing an Accounts form restores its originating icon group');
assert.match(accountsCleanUi,/back\.textContent = '← Go Back to Main'/,'Accounts second-tier pages retain Go Back to Main');
assert.match(exportsApp,/aria-label="Close form and return to previous screen">× Close/,'Exports dialogs use the standard Close control');
assert.match(exportsApp,/id="backShipments">← Go Back to Main/,'Exports second-tier lot pages retain Go Back to Main');
assert.match(directorsIndex,/← Go Back to Main/,'Directors second-tier pages retain Go Back to Main');
assert.match(directorsTg,/aria-label="Close form and return to previous screen">× Close/,'Directors forms use the standard Close control');
assert.match(adminApp,/if \(!IS_SUPER_ADMIN\) \{/,'Super Admin Console is not changed by staff-only navigation');
assert(stateDeclaration>0,'Master Records state is initialized');
assert(!adminApp.slice(0,stateDeclaration).includes('state.masterOptions'),'static master definitions must not access state before initialization');
console.log('PASS module master scope and explicit permission controls');
