const fs=require('fs'),assert=require('assert');
const outbox=fs.readFileSync(__dirname+'/../offline-outbox.js','utf8');
const auth=fs.readFileSync(__dirname+'/../auth_store.php','utf8');
const guard=fs.readFileSync(__dirname+'/../offline_idempotency.php','utf8');
const modulePhp=fs.readFileSync(__dirname+'/../module.php','utf8');
const accounts=fs.readFileSync(__dirname+'/../accounts/index.php','utf8');
assert.match(outbox,/indexedDB\.open\(DB_NAME,1\)/,'pending submissions persist in IndexedDB');
assert.match(outbox,/X-TT-Transaction-ID/,'stable transaction ID is sent to the server');
assert.match(outbox,/X-TT-Base-Resource-Version/,'known server version accompanies retryable updates');
assert.match(outbox,/finalWords/,'only explicit final-action controls arm recovery');
assert.match(outbox,/TT_SHARED_SYNC\.saveNow/,'Milling and Exports explicit shared commits arm recovery');
assert.doesNotMatch(outbox,/setInterval\s*\(/,'no timed background autosave exists');
assert.match(outbox,/addEventListener\('input',\(\)=>\{explicitAction=null\}/,'typing cancels rather than triggers an armed recovery action');
assert.match(outbox,/confirm\(entries\.length/,'staff choose whether to upload pending entries');
assert.match(outbox,/response\.status===409\?'conflict'/,'conflicts remain pending instead of overwriting');
assert.match(outbox,/if\(await acknowledged\(response\)\)\{await remove/,'local copy clears only after acknowledgement');
assert.match(guard,/X-TT-Idempotent-Replay/,'server replays completed transactions without duplicate writes');
assert.match(guard,/Newer server data exists/,'server rejects stale offline updates');
assert.match(auth,/tt_offline_request_guard\(\$user\)/,'authenticated API requests use the safeguard');
assert.match(modulePhp,/offline-outbox\.js/,'Milling and Exports load the safeguard');
assert.match(accounts,/offline-outbox\.js/,'Accounts loads the safeguard before its application bundle');
console.log('PASS explicit-action offline recovery, idempotent retry, conflict protection, and three-module loading');
