const fs=require('fs'),assert=require('assert');
const modulePhp=fs.readFileSync(__dirname+'/../module.php','utf8');
const accounts=fs.readFileSync(__dirname+'/../accounts/index.php','utf8');
const outbox=fs.readFileSync(__dirname+'/../offline-outbox.js','utf8');
const ledger=fs.readFileSync(__dirname+'/../offline_idempotency.php','utf8');
const status=fs.readFileSync(__dirname+'/../api/offline-status.php','utf8');
const exportsJs=fs.readFileSync(__dirname+'/../exports/app.js','utf8');
const sourceBridge=fs.readFileSync(__dirname+'/../accounts/source-bridge.js','utf8');
const loadingBridge=fs.readFileSync(__dirname+'/../accounts/loading-programme-sync.js','utf8');
const bagBridge=fs.readFileSync(__dirname+'/../accounts/bag-control-bridge.js','utf8');
const bagWorkspace=fs.readFileSync(__dirname+'/../accounts/bag-ops-sync-ui.js','utf8');
const workflowUi=fs.readFileSync(__dirname+'/../accounts/accounts-v1-workflow-ui.js','utf8');

assert.match(modulePhp,/offline-outbox\.js\?v=/,'Milling and Exports load durable recovery');
assert.match(accounts,/offline-outbox\.js\?v=/,'Accounts loads the same recovery runtime');
assert.doesNotMatch(modulePhp,/indexedDB\.deleteDatabase|LEGACY_OUTBOX_DB|LEGACY_QUEUE_STORE/,'the outbox is never erased on boot');
assert.doesNotMatch(modulePhp,/timer=setTimeout\(flush,180\)/,'typing and localStorage changes do not trigger timed/background writes');
assert.match(modulePhp,/only explicit application actions save/i,'shared stores document explicit-action-only persistence');
assert.match(outbox,/indexedDB\.open\(DB_NAME,1\)/,'submitted entries persist in IndexedDB');
assert.match(outbox,/X-TT-Transaction-ID/,'recovered requests carry stable transaction IDs');
assert.match(outbox,/X-TT-Base-Resource-Version/,'retries carry a conflict base version');
assert.match(outbox,/Unsynced entries:/,'the user sees the unsynced count');
assert.match(outbox,/Upload pending entries\?/,'returning users are asked whether to upload');
assert.match(outbox,/Restore form/,'the captured workflow can be restored');
assert.match(outbox,/workflowSnapshot/,'workflow position and form values are captured');
assert.match(outbox,/await put\(entry\);await updateNotice\(\);return entry/,'the local copy is written before submission');
assert.match(outbox,/if\(await acknowledged\(response\)\)\{await remove\(entry\.id\)/,'local data clears only after acknowledgement');
assert.match(outbox,/response\.status===409\?'conflict'/,'conflicts stop replay instead of overwriting');
assert.doesNotMatch(outbox,/addEventListener\('online',\s*offerRecovery/,'connectivity return never auto-uploads');
assert.doesNotMatch(sourceBridge,/setInterval|mergeServerOutbox\(\)\.then\(flush\)/,'source handoffs never retry or post in the background');
assert.doesNotMatch(loadingBridge,/setInterval|addEventListener\('focus'|DOMContentLoaded[^\n]*sync/,'Loading Programme handoff never runs on time, focus or screen open');
assert.match(loadingBridge,/tt:shared-saved/,'Loading Programme handoff follows acknowledged explicit save');
assert.doesNotMatch(bagBridge,/setInterval|addEventListener\('storage'|DOMContentLoaded[^\n]*run/,'bag handoff never runs on time, storage change or screen open');
assert.match(bagBridge,/tt:shared-saved/,'bag handoff follows acknowledged explicit save');
assert.doesNotMatch(bagWorkspace,/method:\s*['"]POST['"]|setInterval/,'opening the Accounts Bags workspace remains read-only');
assert.doesNotMatch(workflowUi,/post\(\{action:'sync_late_holds'\}\)/,'Accounts startup never posts late-hold changes in the background');
assert.match(ledger,/X-TT-Idempotent-Replay/,'duplicate IDs receive the stored acknowledgement');
assert.match(ledger,/Newer server data exists/,'stale recovered submissions are rejected');
assert.match(status,/tt_offline_transaction_status/,'ambiguous acknowledgements can be reconciled without repeating writes');
assert.match(exportsJs,/document\.getElementById\('nextStep'\)\.onclick=async/,'Sales Contract Next waits for the server');
assert.match(exportsJs,/window\.TT_SHARED_SYNC\?\.saveNow\?\.\(\)/,'final Export actions request acknowledgement');
console.log('PASS durable explicit-action offline recovery, idempotency, conflict and workflow restoration');
