const fs=require('fs'),assert=require('assert');
const outbox=fs.readFileSync(__dirname+'/../offline-outbox.js','utf8');
const auth=fs.readFileSync(__dirname+'/../auth_store.php','utf8');
const guard=fs.readFileSync(__dirname+'/../offline_idempotency.php','utf8');
const statusApi=fs.readFileSync(__dirname+'/../api/offline-status.php','utf8');
const modulePhp=fs.readFileSync(__dirname+'/../module.php','utf8');
const accounts=fs.readFileSync(__dirname+'/../accounts/index.php','utf8');
assert.match(outbox,/indexedDB\.open\(DB_NAME,1\)/,'pending submissions persist in IndexedDB');
assert.match(outbox,/X-TT-Transaction-ID/,'stable transaction ID is sent to the server');
assert.match(outbox,/X-TT-Base-Resource-Version/,'known server version accompanies retryable updates');
assert.match(outbox,/finalWords/,'only explicit final-action controls arm recovery');
assert.match(outbox,/TT_SHARED_SYNC\.saveNow/,'Milling and Exports explicit shared commits arm recovery');
assert.doesNotMatch(outbox,/(?:setInterval|setTimeout)\s*\(/,'offline recovery has no timed or background retry/autosave');
assert.match(outbox,/addEventListener\('input',\(\)=>\{explicitAction=null\}/,'typing cancels rather than triggers an armed recovery action');
assert.match(outbox,/getElementById\('ttAccountsOutboxBadge'\)\?\.remove\(\)/,'legacy Accounts handoff badge is removed');
assert.match(outbox,/getElementById\('ttOfflineNotice'\)\?\.remove\(\)/,'offline status badge is removed while recovery remains active');
assert.doesNotMatch(outbox,/createElement\('button'\)[\s\S]{0,400}ttOfflineNotice/,'recovery no longer creates a floating badge');
assert.match(modulePhp,/#ttAccountsOutboxBadge,#ttOfflineNotice,[^\n]+display:none!important/,'module wrapper suppresses stale cached badges');
assert.match(modulePhp,/offline-outbox\.js\?v=20260915-review-1/,'module wrapper cache-busts the reviewed outbox');
assert.doesNotMatch(outbox,/confirm\(entries\.length\+' offline \/ unsynced entr/,'recovery never blindly offers to replay every entry');
assert.match(outbox,/Saved entries awaiting server confirmation/,'recovery uses a proper application review dialog');
assert.match(outbox,/Entries already confirmed by the server have been removed automatically/,'dialog explains server reconciliation');
assert.match(outbox,/ttRecoveryUpload/,'each pending entry has its own upload control');
assert.match(outbox,/ttRecoveryDiscard/,'each pending entry has a protected discard control');
assert.match(outbox,/No entry is uploaded automatically/,'recovery never silently replays pending writes');
assert.match(outbox,/offline-status\.php\?ids=/,'pending entries are reconciled against server transaction state');
assert.match(outbox,/if\(status\.state==='complete'\)\{await remove\(entry\.id\)/,'already-applied entries are removed automatically');
assert.match(statusApi,/tt_offline_transaction_status/,'authenticated status API reads the idempotency ledger');
assert.match(guard,/function tt_offline_transaction_status/,'server exposes transaction status without replaying writes');
assert.doesNotMatch(outbox,/if\(restore\)await restoreUi/,'opening the review does not force the user into an old saved screen');
assert.match(outbox,/if\(entries\.length\)await offerRecovery\(\)/,'returning users are offered pending-entry recovery');
assert.match(outbox,/addEventListener\('online',offerRecovery\)/,'connectivity return offers recovery instead of silently uploading');
assert.match(outbox,/window\.TT_OFFLINE_OUTBOX=\{list,recoverPending,offerRecovery,beginAction\}/,'confirmed recovery remains available to every module');
assert.match(outbox,/response\.status===409\?'conflict'/,'conflicts remain pending instead of overwriting');
assert.match(outbox,/if\(await acknowledged\(response\)\)\{await remove/,'local copy clears only after acknowledgement');
assert.doesNotMatch(outbox,/response\.status>=400[^\n]+remove\(/,'unacknowledged client errors remain in the persistent outbox');
assert.match(guard,/X-TT-Idempotent-Replay/,'server replays completed transactions without duplicate writes');
assert.match(guard,/Newer server data exists/,'server rejects stale offline updates');
assert.match(auth,/tt_offline_request_guard\(\$user\)/,'authenticated API requests use the safeguard');
assert.match(modulePhp,/offline-outbox\.js/,'Milling and Exports load the safeguard');
assert.match(accounts,/offline-outbox\.js/,'Accounts loads the safeguard before its application bundle');
console.log('PASS reviewed offline recovery, server reconciliation, idempotent retry, conflict protection, and three-module loading');
