const fs=require('node:fs');
const assert=require('node:assert/strict');

const modulePhp=fs.readFileSync('module.php','utf8');
const accountsIndex=fs.readFileSync('accounts/index.php','utf8');
const bundle=fs.readFileSync('accounts/app-bundle.php','utf8');
const auth=fs.readFileSync('auth_store.php','utf8');
const login=fs.readFileSync('login.php','utf8');
const recovery=fs.readFileSync('recover-admin.php','utf8');
const qa=fs.readFileSync('qa_account.php','utf8');
const exportDocuments=fs.readFileSync('api/export_documents.php','utf8');
const documentAi=fs.readFileSync('api/document_ai.php','utf8');
for(const dead of ['accounts/bag-po-export-ui.js','accounts/export-receipts-charge-flex-ui.js','accounts/rent-salary-treatment-ui.js','accounts/rice-soda-control-ui.js'])assert.equal(fs.existsSync(dead),false,`${dead} must not remain as an unreachable patch`);
for(const productionQaWritePath of ['api/accounts_bulk_test_cleanup.php','tests/live/accounts-bulk-hostinger-qa.spec.js','tests/live/accounts-bulk-cleanup.spec.js','.github/workflows/accounts-bulk-audit.yml','.github/workflows/accounts-bulk-cleanup.yml'])assert.equal(fs.existsSync(productionQaWritePath),false,`${productionQaWritePath} must not write QA dummy data to production`);
assert.equal(fs.existsSync('accounts/bag-control-bridge.js'),true,'bridge/sync code remains outside this cleanup');

assert.doesNotMatch(modulePhp,/preg_replace\([^\n]+app\\\.js/,'Export JavaScript must not use a PHP replacement string');
assert.match(modulePhp,/tt_replace_html_once/);
assert.match(accountsIndex,/tt_replace_html_once/);
assert.doesNotMatch(accountsIndex,/app-bundle\.php\?v=\d/,'Accounts must not depend on a hand-maintained bundle version');
assert.match(bundle,/private, no-cache, must-revalidate/);
assert.doesNotMatch(bundle,/immutable/);
assert.match(auth,/tt_api_json_error\(401,'Your session has expired\. Sign in again\.'\)/);
assert.match(auth,/\$_GET\['entity'\]\?\?\$_POST\['entity'\]/);
assert.match(auth,/An authorized legal entity is required\./);
assert.match(auth,/tt_api_entity_policy/);
assert.match(auth,/Master type not found\./);
assert.match(auth,/TT_AUTH_RATE_FILE/);
assert.match(auth,/TT_STORE_LOCK_FILE/);
assert.match(auth,/tt_write_store_atomic/);
assert.match(auth,/JSON_THROW_ON_ERROR/);
assert.doesNotMatch(auth,/function tt_mutate_store[\s\S]*?ftruncate\(/,'The main secure store must never be truncated in place');
assert.match(auth,/TT_SETUP_LOCK_FILE/);
assert.match(auth,/TT_SETUP_TOKEN/);
assert.doesNotMatch(qa,/\$2[ayb]\$\d{2}\$/,'QA password hashes must never be committed');
assert.match(qa,/\['Mill'=>\['View'\],'Exports'=>\['View'\],'Accounts'=>\['View'\]\]/);
assert.match(auth,/tt_managed_qa_write_blocked/);
assert.match(auth,/production QA account is read-only/);
assert.match(exportDocuments,/tt_managed_qa_write_blocked/);
assert.match(documentAi,/tt_managed_qa_write_blocked/);
assert.match(auth,/TT_ADMIN_RECOVERY_HASH_FILE/);
assert.doesNotMatch(auth,/const TT_ADMIN_RECOVERY_HASH\s*=/,'recovery hash must remain outside repository code');
assert.match(auth,/password_verify\(\$normalized,\$hash\)/);
assert.doesNotMatch(auth,/hash_equals\('[a-f0-9]{64}',hash\('sha256',\$normalized\)\)/,'recovery code must not use a fast unsalted hash');
assert.match(login,/tt_auth_retry_after\('login-account'/);
assert.match(login,/tt_auth_retry_after\('login-address'/);
assert.match(login,/tt_auth_retry_after\('login-emergency'/);
assert.match(login,/TT_LOGIN_DUMMY_HASH/);
assert.match(login,/tt_auth_record_failure\('login-account'/);
assert.match(recovery,/tt_auth_retry_after\('admin-recovery-address'/);
console.log('PASS runtime and authentication hardening audit');
