(()=>{
'use strict';
const access=window.TT_DIRECTORS_ACCESS||{},api='../api/brokerage_master.php',q=s=>document.querySelector(s);
let data=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Karachi',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function style(){if(q('#ttDirBrokerStyle'))return;const s=document.createElement('style');s.id='ttDirBrokerStyle';s.textContent=`.dbm{padding:16px}.dbm-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.dbm-grid label{font-size:11px;font-weight:800;color:#526173}.dbm-grid input{width:100%;margin-top:5px;padding:9px;border:1px solid #ccd5df;border-radius:8px}.dbm-table{width:100%;border-collapse:collapse;margin-top:12px}.dbm-table th,.dbm-table td{padding:8px 9px;border-bottom:1px solid #edf0f3;text-align:left;font-size:12px}.dbm-table th{font-size:10px;text-transform:uppercase;color:#687686;background:#f8fafc}.dbm-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:10px}.dbm-note{font-size:11px;color:#6f7a89;margin:8px 0 12px}@media(max-width:850px){.dbm-grid{grid-template-columns:1fr 1fr}}@media(max-width:540px){.dbm-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
async function get(){const r=await fetch(api,{credentials:'same-origin',headers:{Accept:'application/json'}});let d={};try{d=await r.json()}catch{}if(!r.ok||!d.ok)throw new Error(d.error||'Could not load Brokerage Master.');data=d}
async function post(body){const r=await fetch(api,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({...body,csrf:access.csrf})});let d={};try{d=await r.json()}catch{}if(!r.ok||!d.ok)throw new Error(d.error||'Brokerage Master could not be updated.');return d}
function products(){const a=data?.productRates||[];return a.length?`<table class="dbm-table"><thead><tr><th>Product</th><th>Rate / 100 kg</th><th>From</th><th>To</th></tr></thead><tbody>${a.map(r=>`<tr><td><b>${esc(r.product)}</b></td><td>Rs ${esc(r.ratePer100Kg)}</td><td>${esc(r.effectiveFrom)}</td><td>${esc(r.effectiveTo||'Open')}</td></tr>`).join('')}</tbody></table>`:'<div class="dbm-note">No product brokerage rates saved yet.</div>'}
function wht(){const a=data?.whtRates||[];return a.length?`<table class="dbm-table"><thead><tr><th>Brokerage WHT %</th><th>From</th><th>To</th></tr></thead><tbody>${a.map(r=>`<tr><td><b>${esc(r.whtPercent)}%</b></td><td>${esc(r.effectiveFrom)}</td><td>${esc(r.effectiveTo||'Open')}</td></tr>`).join('')}</tbody></table>`:'<div class="dbm-note">No brokerage withholding rate saved yet.</div>'}
function render(){style();const root=q('#brokerageMasterRoot');if(!root)return;root.innerHTML=`<div class="dbm"><div class="dbm-note">All brokerage-related controls stay in this master. Product brokerage and brokerage withholding use the Soda date to determine the applicable effective rate.</div><div class="dbm-grid"><label>Product<input id="dbmProduct" placeholder="e.g. IRRI-6 Raw Rice"></label><label>Brokerage Rate (Rs per 100 kg)<input id="dbmRate" inputmode="decimal"></label><label>Effective From<input id="dbmFrom" type="date" value="${today()}"></label><label>Effective To <span style="font-weight:400">optional</span><input id="dbmTo" type="date"></label></div><div class="dbm-actions"><button class="btn primary" id="dbmSaveProduct">Save Product Brokerage</button></div>${products()}<hr style="border:0;border-top:1px solid #edf0f3;margin:18px 0"><div class="dbm-grid"><label>Brokerage Withholding %<input id="dbmWht" inputmode="decimal" value="12"></label><label>Effective From<input id="dbmWhtFrom" type="date" value="${today()}"></label><label>Effective To <span style="font-weight:400">optional</span><input id="dbmWhtTo" type="date"></label><div></div></div><div class="dbm-actions"><button class="btn primary" id="dbmSaveWht">Save Brokerage WHT</button></div>${wht()}</div>`;bind()}
function bind(){q('#dbmSaveProduct')?.addEventListener('click',async()=>{try{await post({action:'save_product_rate',product:q('#dbmProduct').value.trim(),ratePer100Kg:q('#dbmRate').value,effectiveFrom:q('#dbmFrom').value,effectiveTo:q('#dbmTo').value,active:true});await get();render()}catch(e){alert(e.message||e)}});q('#dbmSaveWht')?.addEventListener('click',async()=>{try{await post({action:'save_wht_rate',whtPercent:q('#dbmWht').value,effectiveFrom:q('#dbmWhtFrom').value,effectiveTo:q('#dbmWhtTo').value,active:true});await get();render()}catch(e){alert(e.message||e)}})}
async function open(){try{await get();q('#directorHome')?.classList.add('hidden');q('#brokerageWorkspace')?.classList.remove('hidden');render()}catch(e){alert(e.message||e)}}
document.addEventListener('click',e=>{if(e.target.closest('#openBrokerageMaster'))open();if(e.target.closest('#backBrokerageDirectors')){q('#brokerageWorkspace')?.classList.add('hidden');q('#directorHome')?.classList.remove('hidden')}});
})();
