<?php
declare(strict_types=1);
require __DIR__ . '/../auth_store.php';
$user=tt_require_login();
if (($user['role'] ?? '')!=='Super Admin' && !tt_user_can_open_module($user,'Directors')) {
    http_response_code(403); exit('You do not have permission to open the Directors module.');
}
if (!empty($user['must_change_password'])) { header('Location: ../change-password.php'); exit; }
$access=[
    'module'=>'Directors','user'=>(string)($user['full_name']??''),'role'=>(string)($user['role']??''),
    'permissions'=>$user['permissions']['Directors']??[], 'super'=>(($user['role']??'')==='Super Admin'), 'csrf'=>tt_csrf()
];
?>
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Transtrade Directors</title>
<style>
:root{--navy:#102a46;--ink:#152134;--muted:#6f7a89;--line:#dde4eb;--soft:#f4f7fa;--card:#fff;--green:#147a5b;--amber:#a86b00;--red:#a93a34;--shadow:0 8px 28px rgba(19,40,65,.09)}*{box-sizing:border-box}body{margin:0;background:#eef2f6;color:var(--ink);font:14px/1.45 Arial,Helvetica,sans-serif}.top{height:68px;background:var(--navy);color:#fff;display:flex;align-items:center;padding:0 22px;gap:13px;position:sticky;top:0;z-index:30}.brand{width:40px;height:40px;border-radius:11px;background:#fff;color:var(--navy);display:grid;place-items:center;font-weight:900}.top b{letter-spacing:.6px}.top small{display:block;opacity:.72}.sp{flex:1}.power{width:34px;height:34px;border-radius:9px;background:#fff;color:#b42318;display:grid;place-items:center;text-decoration:none;font-size:18px;font-weight:900}.shell{max-width:1440px;margin:auto;padding:24px}.hero{display:flex;gap:16px;align-items:flex-start;justify-content:space-between}.hero h1{margin:0 0 5px;font-size:29px}.hero p{margin:0;color:var(--muted)}.alertBadge{display:none;padding:8px 11px;border-radius:999px;background:#fff0ee;color:#9c2f28;font-weight:800}.alertBadge.on{display:inline-block}.homeGrid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:15px;margin-top:20px}.tile{border:1px solid var(--line);background:#fff;border-radius:17px;padding:17px;min-height:145px;cursor:pointer;box-shadow:var(--shadow);text-align:left}.tile:hover{transform:translateY(-2px)}.ico{width:46px;height:46px;border-radius:13px;background:#edf3f8;display:grid;place-items:center;font-size:23px;margin-bottom:17px}.tile h3{margin:0 0 5px;font-size:15px}.tile p{margin:0;color:var(--muted);font-size:12px}.panel{margin-top:20px;background:#fff;border:1px solid var(--line);border-radius:17px;box-shadow:var(--shadow);overflow:hidden}.panelHead{padding:16px 18px;border-bottom:1px solid var(--line);display:flex;align-items:flex-start;gap:10px}.panelHead h2{margin:0}.panelHead p{margin:3px 0 0;color:var(--muted);font-size:12px}.btn{border:1px solid var(--line);background:#fff;border-radius:9px;padding:8px 11px;font-weight:800;cursor:pointer}.btn.primary{background:var(--navy);border-color:var(--navy);color:#fff}.hidden{display:none!important}#tgMasterRoot,#brokerageMasterRoot{min-height:150px}.homeAlerts{margin-top:18px}.alarm{padding:11px 13px;border-radius:11px;border:1px solid #ead29a;background:#fff8e8;margin-top:8px}.alarm.critical{border-color:#e0aaa6;background:#fff0ee;color:#8d2a24}.alarm b{display:block}.alarm small{display:block;margin-top:3px}.empty{color:var(--muted);padding:12px 0}@media(max-width:900px){.homeGrid{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.shell{padding:14px}.homeGrid{grid-template-columns:1fr}.hero{display:block}.alertBadge{margin-top:12px}}
</style>
<script>window.TT_DIRECTORS_ACCESS=<?=json_encode($access,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?>;</script></head>
<body><header class="top"><div class="brand">TT</div><div><b>TRANSTRADE</b><small>Directors</small></div><div class="sp"></div><div><?=htmlspecialchars((string)($user['full_name']??''))?> · <?=htmlspecialchars((string)($user['role']??''))?></div><a class="power" href="../logout.php" title="Log out" aria-label="Log out">⏻</a></header>
<main class="shell"><section id="directorHome"><div class="hero"><div><h1>Directors</h1><p>Management controls, alerts and restricted group information.</p></div><span id="tgAlertBadge" class="alertBadge"></span></div><div class="homeGrid"><button class="tile" id="openTgMaster"><div class="ico">TG</div><h3>TG Master</h3><p>Trans Grains bank accounts, USD/AED rates, Trade License, partner Emirates IDs and renewal alarms.</p></button><button class="tile" id="openBrokerageMaster"><div class="ico">%</div><h3>Brokerage Master</h3><p>Product-wise brokerage rates and brokerage withholding, effective by Soda date.</p></button></div><div class="homeAlerts"><h3 style="margin:0">TG Renewal Alerts</h3><div id="tgHomeAlerts" class="empty">Loading TG compliance status…</div></div></section>
<section id="tgWorkspace" class="hidden"><div class="panel"><div class="panelHead"><div><button class="btn" id="backDirectors">← Directors Home</button><h2 style="margin-top:12px">TG Master</h2><p>Restricted TG company, banking, exchange/closing and compliance control.</p></div></div><div id="tgMasterRoot"></div></div></section>
<section id="brokerageWorkspace" class="hidden"><div class="panel"><div class="panelHead"><div><button class="btn" id="backBrokerageDirectors">← Directors Home</button><h2 style="margin-top:12px">Brokerage Master</h2><p>One shared source for product brokerage and brokerage withholding rules.</p></div></div><div id="brokerageMasterRoot"></div></div></section></main>
<script src="tg-master.js?v=20260908-1"></script><script src="brokerage-master.js?v=20260909-1"></script><script src="freight-master.js?v=20260911-1"></script></body></html>