const fs=require('fs');
const assert=require('assert');
const path=require('path');

const root=path.join(__dirname,'..');
const mysql=fs.readFileSync(path.join(root,'main/api/operations.mysql.php'),'utf8');
const modulePhp=fs.readFileSync(path.join(root,'main/module.php'),'utf8');
const login=fs.readFileSync(path.join(__dirname,'../../login.php'),'utf8');
const upload=fs.readFileSync(path.join(root,'main/api/export_documents.php'),'utf8');
const mastersApi=fs.readFileSync(path.join(__dirname,'../../api/masters.php'),'utf8');
const authStore=fs.readFileSync(path.join(__dirname,'../../auth_store.php'),'utf8');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const css=fs.readFileSync(path.join(__dirname,'app.css'),'utf8');
const js=fs.readFileSync(path.join(__dirname,'../../exports/app.js'),'utf8');
const milling=fs.readFileSync(path.join(__dirname,'../../milling/Transtrade_Master_Milling_V3_3_2_AUDITED.html'),'utf8');
const customerMaster=fs.readFileSync(path.join(__dirname,'../../customer-master.js'),'utf8');

assert.match(mysql,/tt_require_login\(\)/);
assert.match(mysql,/tt_verify_csrf/);
assert.match(mysql,/FOR UPDATE/);
assert.match(mysql,/beginTransaction\(\)/);
assert.match(mysql,/baseVersion/);
assert.match(mysql,/409/);
assert.match(mysql,/operations_merge_export/);
assert.match(mysql,/\$merged\['alerts'\]\s*=\s*array_values\(\(array\)\(\$incoming\['alerts'\]/,'an exact-version Exports save must be able to clear acknowledged or deleted alerts');
assert.equal((mysql.match(/\$merged\['alerts'\]\s*=\s*operations_union_rows/g)||[]).length,2,'only Accounts and Milling may additively merge alerts');
assert.match(mysql,/16 \* 1024 \* 1024/);
assert.match(modulePhp,/tt_user_can_open_module/);
assert.match(modulePhp,/'masters'=>tt_list_masters\(\)/);
assert.match(modulePhp,/pending\.set\(key,value\)/,'transient shared-save failures remain pending for retry');
assert.match(modulePhp,/endpoint='api\/operations\.mysql\.php'/);
assert.match(modulePhp,/TG_header\.png/);
assert.match(modulePhp,/TG_footer\.png/);
assert.match(modulePhp,/TG_sign\.png/);
assert.doesNotMatch(modulePhp,/TG_(?:header|footer|sign)\.jpg/);
assert.match(modulePhp,/data:' \. \$mime \. ';base64,/,'server wrapper must inline each artwork with its real MIME type');
assert.match(mysql,/CREATE TABLE IF NOT EXISTS tt_operation_records/);
assert.match(mysql,/CREATE TABLE IF NOT EXISTS tt_operation_history/);
assert.match(mysql,/ENGINE=InnoDB/);
assert.match(upload,/CREATE TABLE IF NOT EXISTS tt_export_documents/);
assert.match(upload,/function export_docs_delete_contract/,'protected shipment documents must have a server deletion path');
assert.match(upload,/action===?'delete-shipment'/,'document API must route confirmed shipment deletion');
assert.match(js,/data-delete-shipment/,'active shipment cards must expose the requested delete control');
assert.match(js,/function deleteShipmentDocuments/,'shipment deletion must remove protected uploads');
assert.match(js,/function deleteShipmentData/,'shipment deletion must remove linked operational data');
assert.doesNotMatch(js,/setInterval\(\(\)=>window\.TT_SHARED_SYNC\?\.poll/,'Exports must not poll or rebuild active forms in the background');
assert.doesNotMatch(js,/Manual save only/,'Exports must not expose technical sync/save-mode wording');
assert.match(modulePhp,/LEGACY_QUEUE_STORE='tt_shared_commit_queue_v1'/,'retired browser queue is cleared on load');
assert.doesNotMatch(modulePhp,/queued:true|settleQueued/,'unconfirmed actions must never continue through an offline queue');
assert.match(js,/const rerender=\(\)=>\{renderShipmentWorkspace\(\)\}/,'Loading Instruction draft controls must not save before the final Send action');
assert.match(js,/window\.TT_SHARED_SYNC\?\.saveNow\?\.\(\)/,'final Loading Instruction send must wait for authoritative shared save acknowledgement');
assert.match(milling,/containerCommitPending=\{s,c,before\};confirmContainerSharedSave\(containerCommitPending\)/,'Save Container must retain one idempotent pending record until shared acknowledgement');
assert.match(milling,/Container Saved — /,'Milling success must appear only after the acknowledged save');
assert.doesNotMatch(modulePhp,/setInterval\(\(\)=>getRemote\(false\),8000\)/,'shared project state must not background-refresh forms');
assert.match(modulePhp,/function checkInbound\(\)/,'shared state must provide a read-only inbound refresh path');
assert.match(modulePhp,/addEventListener\('focus',checkInbound\)/,'returning to a module must check for cross-module updates');
assert.match(modulePhp,/visibilitychange/,'restoring a module tab must check for cross-module updates');
assert.match(modulePhp,/poll:checkInbound/,'legacy manual poll entry point must perform only the inbound check');
assert.match(modulePhp,/function saveNow\(\)/,'shared bridge must expose an awaitable explicit-save acknowledgement');
assert.match(modulePhp,/function refreshNow\(\)/,'receiving modules must expose an explicit authoritative refresh');
assert.match(modulePhp,/if\(access\.moduleId==='exports'\)bridge\(\);else addEventListener\('DOMContentLoaded'/,'Exports must reconcile Mill actuals before loading state while Milling waits until its startup completes');
assert.doesNotMatch(js,/id="refreshMillUpdates"/,'Exports home must not duplicate the shared top-header refresh notice');
assert.doesNotMatch(customerMaster,/nav\.appendChild\(b\)/,'Export must not inject the removed Master Data button beside +FI');
assert.doesNotMatch(customerMaster,/tt-cm-home-button|actions\.insertBefore\(b,actions\.firstChild\)/,'Export home must not duplicate the top Master Data entry');
assert.doesNotMatch(modulePhp,/ttSyncNotice/,'shared synchronization must not render a persistent interface notice');
assert.match(modulePhp,/c\.moduleId==='milling'\?document\.querySelector\('header'\)/,'Milling login and power controls must be placed inside its header');
assert.match(milling,/id="refreshExportInstructions"/,'Milling must provide an explicit Loading Instruction refresh action');
assert.match(js,/RETRY SAME LOADING INSTRUCTION SAVE/,'Exports must retry the same pending lot rather than create a duplicate');
assert.match(milling,/RETRY OR CORRECT CONTAINER SAVE/,'Milling must preserve the pending container so staff can correct validation errors or retry the same save without creating a duplicate');
assert.match(modulePhp,/const markSaveState=\(\)=>\{\}/,'shared saves must remain visually silent');
assert.doesNotMatch(js,/id="saveBadge"/,'Exports header must not expose save or synchronization state');
assert.doesNotMatch(modulePhp,/setInterval\(/,'shared bridge must never use timed background polling or autosave');
assert.match(modulePhp,/x\.poNo\|\|x\.contractRef\|\|'NO-PO'/,'bag bridge identity must not collapse orders when PO number is absent');
assert.match(modulePhp,/x\.line\?\?x\.lineId\?\?index/,'bag bridge identity must remain unique when PO line is absent');
assert.match(js,/class="btn small red shipmentDeleteButton" data-delete-shipment=/,'every active shipment card must expose the top-right red delete control');
assert.match(js,/Are you sure you want to delete this shipment\?/,'shipment deletion must require an explicit in-page confirmation');
assert.match(js,/Yes — Delete Shipment/,'confirmation must require the user to press Yes before deletion');
assert.match(js,/id="cuGDFile"/,'Customs must expose a Goods Declaration upload');
assert.doesNotMatch(js,/MILL CONTAINER ACTUALS/,'Customs must remain separate from Mill container and seal actuals');
assert.match(js,/function renderBL(?:__legacy_v\d+)?\(d\)[\s\S]*?<th>Container<\/th><th>Seal<\/th>[\s\S]*?t\.rows\.map/,'B/L Draft must visibly list the container and seal actuals returned by Milling');
assert.match(js,/uploadDocument\(f,'goods-declaration',s\)/,'GD uploads must use protected document storage');
assert.match(js,/gdRefsFingerprint/,'GD upload must stay bound to its saved GD number and date references');
assert.match(js,/Goods Declaration \(GD\) file matching the saved GD number\(s\) and date\(s\)/,'final lot closure must require a matching GD file');
assert.match(js,/\['goodsDeclaration','Goods Declaration \(GD\)',s\.customs\?\.gdDocument\]/,'final uploaded-document set must include the GD');
assert.match(milling,/shipment:\(s\.contractRef\?s\.contractRef\+' · ':''\)\+\(s\._ttLotId\|\|s\.ref\|\|''\)/,'new reconciliation rows must persist Contract · Lot identity');
assert.match(milling,/shipLabel=match\.contractRef\+' · '\+\(match\._ttLotId\|\|match\.ref\|\|shipLabel\)/,'legacy reconciliation rows must render with full Contract · Lot identity');
assert.match(milling,/matches\.find\(s=>s\.status==='Completed'\)\|\|matches\[0\]/,'ambiguous legacy brand/lot rows must prefer the completed shipment');
for(const id of ['bagReportMode','bagReportFrom','bagReportTo','bagReportBrand','bagReportMovement','exportReportSource','exportReportFrom','exportReportTo','exportReportBrand','exportReportStatus','exportReportMill']) assert.match(milling,new RegExp('id=["\\\']'+id+'["\\\']'),id+' report control must be wired');
assert.match(milling,/brands=\[\.\.\.new Set\(rows\.map\(x=>x\.brand\)/,'report brands must come from live rows');
assert.match(milling,/No export loading records match the filters/,'export loading filters must render an empty state');
assert.match(mastersApi,/action==='manage-option'/,'shared dropdown options must support controlled management');
assert.match(authStore,/product_finishes/,'Product Master must own the approved finishing wording');
assert.match(authStore,/master_options_disabled/,'deleted options must be retired without rewriting historical records');
assert.match(js,/Manage \/ Rename \/ Delete/,'Currency and Inspection lists must be manageable from their dropdowns');
assert.doesNotMatch(mysql,/\b(?:DROP\s+TABLE|TRUNCATE\s+TABLE)\b/i);
assert.match(html,/href="app\.css\?v=/);
assert.match(html,/src="app\.js\?v=/);
assert.match(css,/@page\{size:A4;margin:0\}/);
assert.match(css,/\.docLetterhead\{position:absolute;left:0;right:0/);
assert.match(css,/\.shipmentCardActions\{[^}]*align-items:flex-end/,'shipment delete control must stay at the top-right of each card');
assert.match(css,/\.docAutoSign img\{display:block;width:auto;height:20mm/,'signatures must remain with the document body and not create orphan pages');
assert.match(js,/WITH \$\{label\}/);
assert.match(js,/WITHOUT \$\{label\}/);
assert.match(js,/this company has no footer/);
for(const asset of ['TTI_header.png','TTI_sign.png','BRM_header.png','BRM_sign.png','TG_header.png','TG_footer.png','TG_sign.png']){
  assert.ok(js.includes(`assets/${asset}`),asset+' reference missing');
  assert.ok(fs.existsSync(__dirname+'/assets/'+asset),asset+' file missing');
}
assert.match(js,/As per Pakistan Origin Standards/,'Sales Contract must offer Pakistan Origin Standards');
assert.match(js,/As per Buyer Specification/,'Sales Contract must offer Buyer Specification');
assert.match(js,/No specification chart is required for Pakistan Origin Standards/,'origin-standard contracts must hide the specification chart');
assert.match(js,/As per below specification\./,'buyer-specific contracts must introduce the specification table');
assert.match(js,/On or before/,'contract shipment output must use the approved date wording');
assert.match(js,/TOTAL \$\{esc\(c\.incoterm\)\} VALUE/,'contract price must show the specimen Incoterm calculation');
assert.match(js,/balance on scan copies of shipment documents/,'scan-copy payment summary must use approved wording');
assert.match(js,/shall be received latest by/,'advance clause must use the single payment-validity date');
assert.match(js,/upon receipt of scan copies of shipment documents by Buyer/,'scan balance clause must use approved wording');
assert.match(js,/ADVANCE TO BE REMITTED TO BELOW-MENTIONED ACCOUNT:/,'advance bank details must follow the balance clause');
assert.match(js,/contractSignatureGrid/,'contract must provide aligned Seller and Buyer signature areas');
assert.doesNotMatch(login,/authBrandLogo|TTI_header\.png/,'login must retain text-only Transtrade branding');
console.log('PASS backend/static release audit: auth, CSRF, concurrency, self-initializing schema, links and A4 print controls');
