const fs=require('fs');
const assert=require('assert');
const {JSDOM,VirtualConsole}=require('jsdom');
let app=fs.readFileSync(__dirname+'/app.js','utf8');
app=app.replace('mount();',`window.__DOM_AUDIT__={state,makeShipment,makeLotRecord,render,openShipment,contractSpecRows,defaultDocsFor,millLocations,registerMillLocation};mount();`);
const css=fs.readFileSync(__dirname+'/app.css','utf8');
const html=`<!doctype html><html><head><style>${css}</style></head><body><div id="app"></div><div id="printRoot"></div></body></html>`;
const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));vc.on('error',e=>errors.push(String(e)));
const dom=new JSDOM(html,{runScripts:'dangerously',pretendToBeVisual:true,url:'https://exports.audit.local/',virtualConsole:vc,beforeParse(w){w.TT_MODULE_ACCESS={user:'Jazib',module:'Exports'};w.alert=m=>{throw Error(String(m))};w.confirm=()=>true;w.print=()=>{};w.scrollTo=()=>{};w.setInterval=()=>0;w.structuredClone=value=>JSON.parse(JSON.stringify(value));w.FileReader=class{};}});
dom.window.eval(app);
const w=dom.window,d=w.document,t=w.__DOM_AUDIT__;
assert.ok(t,'test API is available: '+errors.join(' | '));
assert.equal(t.state.contracts.length,0,'release must start without dummy contracts');
const customer={id:'DOM-C',name:'DOM Buyer',code:'DOM',address:'Dubai',packingDefault:'KG',nextSeq:1};
t.state.customers.push(customer);
const contract={id:'DOM-CT',ref:'TTI/DOM/01',seller:'TTI',customerId:customer.id,date:'2026-09-08',product:'IRRI-6 White Rice',broken:5,finish:'Silky Polished & Sortexed',quality:'Free from live insects, bad odour and rice fit for human consumption.',specMode:'Contract Specific',specRows:[{name:'Moisture',value:'14% MAX'}],containers:4,weightPer:27,qty:108,tolerance:5,pol:'Port Qasim',podPort:'Jebel Ali',packingUnit:'KG',currency:'USD',incoterm:'CIF',inspection:'SGS',insurance:"Seller's Account",paymentCode:'LC_SIGHT',docs:t.defaultDocsFor({incoterm:'CIF'}),terms:[],received:true,status:'Contract Received',packings:[{type:'PP Bags',size:25,brand:'DOM BRAND',tare:80,containers:4,weightPer:27,price:400,freight:20,insurance:2,extraBagPct:2,masterBag:{enabled:false,qty:0,tare:0}}]};
t.state.contracts.push(contract);const process=t.makeShipment(contract);process.bagOrders=[{poNo:'PO-DOM',lines:[{packingIndex:0,totalBags:4407}]}];process.production.sentToMill=true;t.state.shipments.push(process);t.render();
assert.equal(d.querySelectorAll('.summaryBox').length,3);
assert.equal(d.querySelector('.millPopover').textContent.trim(),'No unread Mill updates.');
d.querySelector('[data-open-process]').click();
assert.equal(d.querySelector('#workspaceDetail').innerHTML,'','workspace starts closed');
d.querySelector('[data-workspace="contract"]').click();assert.match(d.querySelector('#workspaceDetail').textContent,/Sales Contract/);d.querySelector('[data-workspace="contract"]').click();
d.querySelector('[data-workspace="bags"]').click();assert.match(d.querySelector('#workspaceDetail').textContent,/Uploading a GOOD SIDE bag marking means it is approved/);d.querySelector('[data-workspace="bags"]').click();
d.querySelector('[data-workspace="production"]').click();
assert.match(d.querySelector('#workspaceDetail').textContent,/Contract Specifications/);
assert.match(d.querySelector('#workspaceDetail').textContent,/14% MAX/);
d.querySelector('[data-workspace="production"]').click();
assert.equal(d.querySelector('#workspaceDetail').innerHTML,'','same tile closes accordion');
d.querySelector('[data-workspace="loading"]').click();
assert.ok(d.querySelector('#addLoadingSource'));
const before=d.querySelectorAll('[data-li-name]').length;d.querySelector('#addLoadingSource').click();
assert.equal(d.querySelectorAll('[data-li-name]').length,before+1,'green plus adds another loading source');
assert.ok(d.querySelector('[data-li-dry]')&&d.querySelector('[data-li-craft]')&&d.querySelector('[data-li-dpp]')&&d.querySelector('[data-li-inspect]'));
assert.ok(t.defaultDocsFor({incoterm:'CIF'}).includes('Insurance Policy / Certificate'));
const set=(el,value,event='input')=>{el.value=value;el.dispatchEvent(new w.Event(event,{bubbles:true}))};const names=[...d.querySelectorAll('[data-li-name]')],containers=[...d.querySelectorAll('[data-li-cont]')];assert.equal(d.querySelector('#liLot'),null,'lot reference is generated automatically');assert.equal(d.querySelector('[data-li-type]'),null,'loading type is derived from location');set(d.querySelector('#liProgramme'),'LP-DOM-01');set(d.querySelector('#liDate'),'2026-09-09','change');set(d.querySelector('#liIntendedVessel'),'MV DOM TEST');set(d.querySelector('#liShippingLine'),'DOM SHIPPING LINE');set(names[0],'TTI Rice Mills');set(containers[0],'2');set(names[1],'DOM External Mill');set(containers[1],'2');d.querySelector('#sendLoading').click();
assert.equal(t.state.shipments.filter(x=>x.kind==='lot').length,1,'Loading action creates one separate lot record');assert.equal(t.state.millSync.exportLoading.length,1,'Loading action hands exact lot to Mill');assert.ok(t.millLocations().some(x=>x.name==='DOM External Mill'));
const lot=t.state.shipments.find(x=>x.kind==='lot');
assert.equal(lot.lotId,'TTI/DOM/01/L01','lot reference follows contract sequence');
assert.equal(lot.loadingProgrammeNo,'LP-DOM-01','loading programme is entered by the user');
assert.equal(lot.loadingPlan.intendedVessel,'MV DOM TEST','intended vessel carries from Loading Instructions to the lot');
assert.equal(lot.loadingPlan.shippingLine,'DOM SHIPPING LINE','shipping line carries from Loading Instructions to the lot');
assert.equal(lot.bl.intendedVessel,'MV DOM TEST','B/L Draft receives the intended vessel');
assert.equal(lot.bl.shippingLine,'DOM SHIPPING LINE','B/L Draft receives the shipping line');
assert.equal(t.state.millSync.exportLoading[0].intendedVessel,'MV DOM TEST','Mill handoff receives intended vessel');
assert.equal(t.state.millSync.exportLoading[0].shippingLine,'DOM SHIPPING LINE','Mill handoff receives shipping line');
assert.ok(d.querySelector('.lotSplitWorkspace'),'lot document opens as a split form and preview workspace');
assert.ok(d.querySelector('.lotEditorShell'),'document editor opens above the original Lot icon screen');
assert.ok(d.querySelector('.lotEditorShell').nextElementSibling.matches('.workspacePanel'),'original Lot icon panel remains directly below the editor');
assert.ok(d.querySelectorAll('.workspaceTile').length>=8,'Lot retains its original document icon grid');
assert.ok(d.querySelector('#closeLotEditor'),'split editor has a top-right close control');
lot.lc={saved:true,lcNo:'LC-DOM',lcDate:'2026-09-08',documents:['Commercial Invoice'],conditions:[]};lot.millActuals=[{number:'MSCU123456-7',seal:'S1',bags:1080,netKg:27000,tareKg:86.4,grossKg:27086.4,brand:'DOM BRAND',packing:'25 KG',location:'TTI Rice Mills'}];d.querySelector('[data-workspace="customs"]').click();d.querySelector('[data-workspace="customs"]').click();
const balancingOpenAccount=d.querySelector('#cuOpenAccount').value;
set(d.querySelector('#cuOpenAccount'),'0');
d.querySelector('#saveCustoms').click();
assert.equal(lot.customs.saved,false,'unbalanced Customs payment control is blocked');
assert.ok(errors.length,'unbalanced Customs payment control reports an error');
errors.length=0;
set(d.querySelector('#cuOpenAccount'),balancingOpenAccount);
d.querySelector('#saveCustoms').click();
assert.equal(lot.customs.saved,true,'balanced FI plus open-account control saves Customs master');
assert.equal(d.querySelector('.lotEditorShell'),null,'successful save returns to the Lot icon screen');
d.querySelector('[data-workspace="customs"]').click();
d.querySelector('[data-workspace="bl"]').click();
assert.equal(d.querySelector('.lotFormPane input[readonly]').value,lot.loadingProgrammeNo,'B/L form displays the carried loading programme number');
assert.equal(d.querySelector('.lotPreviewPaper .docBrand img'),null,'B/L Draft preview excludes bag artwork');
d.querySelector('#closeLotEditor').click();
assert.equal(d.querySelector('.lotEditorShell'),null,'top-right cross exits the split editor without leaving the Lot');
d.querySelector('[data-workspace="uploads"]').click();
assert.ok([...d.querySelectorAll('#uploadDocumentType option')].some(x=>x.textContent==='Custom'),'Upload Documents has a known-document dropdown plus Custom');
set(d.querySelector('#uploadDocumentType'),'Custom','change');
assert.equal(d.querySelector('#customUploadNameWrap').classList.contains('hidden'),false,'custom document name opens only for Custom');
d.querySelector('[data-workspace="uploads"]').click();
for(const tile of [...d.querySelectorAll('[data-workspace]')]){tile.click();assert.ok(d.querySelector('#workspaceDetail').textContent.trim(),tile.dataset.workspace+' renders below its icon');d.querySelector(`[data-workspace="${tile.dataset.workspace}"]`).click()}
assert.equal(errors.length,0,errors.join('\n'));
console.log('PASS browser DOM audit: clean home, hover summary, accordion, every process/lot tile, Production and multi-source Loading');
