const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'../..');
const app=fs.readFileSync(path.join(root,'exports/app.js'),'utf8');
const css=fs.readFileSync(path.join(root,'exports/app.css'),'utf8');
const accounts=fs.readFileSync(path.join(root,'accounts/export-recognition-ui.js'),'utf8');
const bridge=fs.readFileSync(path.join(root,'accounts/source-bridge.js'),'utf8');
const api=fs.readFileSync(path.join(root,'api/export_accounting.php'),'utf8');
const finalPacking=app.slice(app.lastIndexOf('function packingListDoc('),app.lastIndexOf('function cooDoc('));
const finalInvoice=app.slice(app.lastIndexOf('function commercialInvoiceDoc('),app.lastIndexOf('function packingSummaryGroups('));
const finalCoo=app.slice(app.lastIndexOf('function cooDoc('),app.lastIndexOf('function renderShipmentWorkspace('));

assert.match(app,/data-commercial-tab="invoice"/);
assert.match(app,/data-commercial-tab="packing"/);
assert.match(app,/Commercial Invoice is the master/);
assert.match(finalInvoice,/commercialWeightSummary\(t,invoiceValue,currency\)/);
assert.match(app,/function commercialWeightSummary[\s\S]*TOTAL INVOICE VALUE/);
assert.match(finalInvoice,/BALANCE RECEIVABLE/);
assert.match(finalInvoice,/AMOUNT IN WORDS — BALANCE RECEIVABLE/);
assert.match(finalInvoice,/adjustmentNet/);
assert.match(app,/3 originals \+ 3 identical copies/);
assert.match(app,/ORIGINAL','DUPLICATE','TRIPLICATE','QUADRUPLICATE/);
assert.match(finalPacking,/<th>TARE<\/th>/);
assert.doesNotMatch(finalPacking,/TOTAL TARE WEIGHT FOR/);
assert.match(finalPacking,/<th>CONTAINER NO\.<\/th><th>SEAL NO\.<\/th><th>PACKAGES<\/th><th>NET WEIGHT<\/th><th>GROSS WEIGHT<\/th>/);
assert.doesNotMatch(finalPacking,/<th>CONTAINER NO\.<\/th>[\s\S]{0,180}<th>TARE/);
assert.match(finalPacking,/PAGE \$\{index\+1\} OF \$\{totalPages\}/);
assert.match(finalCoo,/GOODS OF PAKISTAN ORIGIN/);
assert.match(finalCoo,/cooFixedMembership/);
assert.doesNotMatch(finalCoo,/CERTIFICATE NO\./);
assert.match(css,/\.cooPakistanOrigin/);
assert.match(app,/function tgInternalCommercialInvoiceDoc/);
assert.match(app,/pageDoc\(dc,'COMMERCIAL INVOICE'/);
assert.match(app,/pageDoc\(dc,'PACKING LIST'/);
assert.match(finalInvoice,/commercialInvoiceSingleLine/);
assert.match(finalInvoice,/commercialInvoiceMultiLine/);
assert.match(finalInvoice,/conditionalOutputSignature/);
assert.match(finalPacking,/conditionalOutputSignature/);
assert.match(css,/\.printModeWithout \.conditionalOutputSignature/);
assert.doesNotMatch(app.slice(app.lastIndexOf('function renderTG(')),/Include actual notify party/);
assert.match(app,/freshCustomsDescription[\s\S]*FEET CONTAINERS/);
assert.match(bridge,/queueExportInvoice/);
assert.match(api,/Draft Estimate — Not Posted/);
assert.match(api,/adjustmentAccountMap/);
assert.match(api,/\['TTI','BRM','TG'\]/);
assert.match(accounts,/Tag an existing account/);
console.log('PASS Commercial Invoice, Packing List, COO, TG internal documents and Accounts handoff acceptance');
