const assert=require('node:assert/strict');
const fs=require('node:fs');
const app=fs.readFileSync('exports/app.js','utf8');
const css=fs.readFileSync('exports/app.css','utf8');
const admin=fs.readFileSync('admin/app.js','utf8');
const globalValidation=fs.readFileSync('global-validation.js','utf8');

assert.match(app,/function documentKg[\s\S]*minimumFractionDigits:2,maximumFractionDigits:2/);
assert.match(app,/function documentMTonsFromKg[\s\S]*minimumFractionDigits:3,maximumFractionDigits:3/);
assert.match(app,/TOTAL GROSS WEIGHT[\s\S]*TOTAL TARE WEIGHT[\s\S]*TOTAL NET WEIGHT/);
assert.match(app,/<th>GROSS WEIGHT<\/th><th>TARE<\/th><th>NET WEIGHT<\/th>/);
assert.doesNotMatch(app.slice(app.lastIndexOf('function packingListDoc(')),/TOTAL TARE WEIGHT FOR/);
assert.match(css,/\.commercialInvoiceOnePage\{text-transform:uppercase\}/);
assert.match(css,/\.printModeWithout[\s\S]*\.docAutoSign[\s\S]*\.docSignatures/);
assert.match(app,/One covering letter only, on original company letterhead/);
assert.match(app,/SETTLE\/UTILIZE THE APPLICABLE/);
assert.match(app,/PLEASE ALSO DISPATCH A SET OF DOCUMENTS WHICH IS ATTACHED WITH ORIGINAL DOCUMENTS/);
assert.doesNotMatch(app.slice(app.indexOf('function coveringDoc(s,c,'),app.indexOf('const commercialInvoiceDocEntityAware')),/BANK COPY|TTI RECEIVING COPY/);
for(const label of ['SALES CONTRACT / PROFORMA','COMMERCIAL INVOICE','PACKING LIST','BANK COVERING LETTER','RELATIONSHIP LETTER'])assert.match(app,new RegExp(label.replace('/','\\/')));
assert.match(app,/approved relationship-letter wording only/i);
assert.match(app,/KCCI_COO_letterpad\.jpg/);
const activeCoo=app.slice(app.indexOf('function renderCOO(d){'),app.indexOf('function renderCover(d)'));
assert.doesNotMatch(activeCoo,/Completed \/ Original COO|cooFinalFile/);
assert.match(app,/commercialDescriptionText\(s,dc\)/);
assert.match(app,/<b>BY SEA<\/b><br><b>VESSEL NAME:<\/b>[\s\S]*<b>VOY:<\/b>[\s\S]*<b>B\/L NUMBER:<\/b>/);
assert.match(app,/customsDescriptionHTML\(s,dc\)/);
assert.match(app,/Customs master saved successfully\./);
assert.match(app,/AMEND CUSTOMER DETAILS/,'Sales Contract must expose the agreed customer-detail amendment tab');
assert.match(app,/Customer Name — fixed[\s\S]*readonly/,'customer name must remain locked in the amendment tab');
assert.match(app,/id="cBuyerDetailsPanel" class="field full hidden"/,'customer-detail amendments must remain collapsed until requested');
assert.match(app,/cBuyerAddress:'address'[\s\S]*cBuyerTax:'tax'/,'contract-specific customer details must be persisted in the draft');
const activeCustoms=app.slice(app.indexOf('function renderCustoms(d){'),app.indexOf('function customsBalanced(s,c)'));
assert.match(activeCustoms,/x\.invoiceNo=x\.invoiceNo\|\|c\.ref/,'an existing Customs invoice number must not be reset to the contract reference');
assert.match(activeCustoms,/id="cuNo" value="\$\{esc\(x\.invoiceNo\|\|c\.ref\)\}"/,'Customs Invoice No. must be editable');
assert.match(activeCustoms,/const invoiceNo=d\.querySelector\('#cuNo'\)\.value\.trim\(\)/,'Customs save must read the edited Invoice No.');
assert.match(activeCustoms,/Object\.assign\(x,\{invoiceNo,date:/,'Customs save must persist the edited Invoice No.');
assert.doesNotMatch(activeCustoms,/Object\.assign\(x,\{invoiceNo:c\.ref/,'active Customs save must not force the contract reference');
assert.match(app,/function tgRelationshipLetterDoc[\s\S]*ttApprovedInvoiceReference\(s\.customs\?\.invoiceNo\|\|dc\.ref/,'TG relationship letter must use the saved Customs invoice number');
assert.match(app,/const invoiceNo=\(internalTG\?s\.customs:s\.commercial\)\?\.invoiceNo\|\|c\.ref/,'TG covering letter must use the saved Customs invoice number');
assert.match(app,/packingShowNotify/);
assert.match(app,/3 originals \+ 3 copies/);
assert.match(app,/\['ORIGINAL','ORIGINAL','ORIGINAL','COPY','COPY','COPY'\]/);
assert.match(app,/CORRECT CONTAINER NUMBER/);
assert.match(app,/containerCorrections/);
assert.doesNotMatch(app.slice(app.indexOf('function wireContainerCorrection'),app.indexOf('function renderBL(d)')),/reason/i);
assert.match(app,/function buyerPoApplies\(c\)[\s\S]*sourceDocument\?\.type==='Customer Contract'/);
assert.match(globalValidation,/displayDate[\s\S]*\$3-\$2-\$1/);
for(const label of ['Owners / partners','KCCI membership no.','REAP membership no.','NTN number','Sales tax number','Company number'])assert.match(admin,new RegExp(label.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'));
assert.match(admin,/"36453"/);
console.log('PASS 2026-09-17 document, TG pack, COO and company-master rules');
