const fs=require('fs'),assert=require('assert');
const app=fs.readFileSync('exports/app.js','utf8'),css=fs.readFileSync('exports/app.css','utf8'),admin=fs.readFileSync('index.html','utf8'),exportsIndex=fs.readFileSync('exports/index.html','utf8');
const has=x=>assert(app.includes(x),'Missing acceptance marker: '+x);
has("const TT_PORTS=['Port Qasim, Pakistan','Karachi Port, Pakistan'];");
has('Have you received the signed Sales Contract?');
has('SAVE & REISSUE SAME LOADING INSTRUCTION');
has('const reissueDraft=shipment()?.loading?.draft');
has('Calculated proportionally from the Bag Order');
has('function ttRecoverEmptyManagedOptions(select,group)');
has('At least one '+"'+TT_REMOVABLE_OPTION_GROUPS[group].label+'"+' option must remain available.');
has('Automatically taken from the Sales Contract inspection.');
has("create.textContent='+ FI'");
has('An FI allocation of at least');
has("freshCustomsInvoiceDocument(copy,c,'CUSTOM INVOICE')");
has('freshCustomPackingDocument(copy,c)');
has('freshCustomsInvoiceDocument(copy,c,\'PHYTOSANITARY INVOICE\')');
has('TOTAL NET WEIGHT');
has('TOTAL GROSS WEIGHT');
has('SHOW ALL PRICE COMPONENTS SEPARATELY ON CONTRACT');
has('approvedContractPriceGrid');
has('TOTAL ${incoterm} VALUE');
has('contractPriceGrandTotal');
has('ACCOUNT TITLE:</b>');
has('SWIFT CODE:</b>');
has('TRANSTRADE INTERNATIONAL');
assert(!app.includes("issuePO=function(){const s=shipment(),po=ensureBagDraft();if(!contractByRef(s.contractRef).received"),'Signed gate remains in Bag Order');
const finalStart=app.lastIndexOf('/* 2026-09-14 Document Output Section handover: final authoritative renderers. */');
const mountAt=app.lastIndexOf('mount();');
assert(finalStart>=0&&mountAt>finalStart,'Authoritative final output layer must execute immediately before mount');
const finalLayer=app.slice(finalStart,mountAt);
for(const assignment of ['contractPriceHTML=function','purchaseOrderPrint=function','blDraftDoc=function','phytoInvoiceDoc=function','packingListDoc=function'])assert(finalLayer.includes(assignment),'Final handover layer missing '+assignment);
assert(app.lastIndexOf('packingListDoc=function')>finalStart,'Final Customs Packing renderer must be inside the handover layer');
assert(app.lastIndexOf('phytoInvoiceDoc=function')>finalStart,'Final Phytosanitary renderer must be inside the handover layer');
assert(app.lastIndexOf('liveLotDocument=function')<finalStart,'The handover renderer must execute after the live preview wrapper');
assert(app.includes("d.querySelector('#customsOutputReviews')?.remove()"),'Obsolete duplicate Customs preview is not removed');
assert(app.includes("phytoInvoiceDoc=function(s,c){return freshCustomsInvoiceDocument(s,c,'PHYTOSANITARY INVOICE')}"),'Phytosanitary is not tied to the Customs renderer');
assert(css.includes('.salesContractFlowPage .docTitle'),'Continuous Sales Contract title rule missing');
assert(css.includes('.contractFlowLayout>thead{display:table-header-group}'),'Repeated heading print rule missing');
assert(css.includes('.customsPreviewStack'),'Single Customs preview stack style missing');
assert(admin.includes('brand-theme.css?v=20260914-control-centre-1'),'Control Centre theme missing');
assert(/app\.js\?v=20260914-document-output-handover-2/.test(exportsIndex),'Exports cache-bust marker missing');
console.log('Exports September 14 exact acceptance audit passed.');
