const fs=require('fs');
const assert=require('assert');
const root=__dirname+'/../../';
const app=fs.readFileSync(root+'exports/app.js','utf8');
const api=fs.readFileSync(root+'api/export_documents.php','utf8');
const operations=fs.readFileSync(root+'api/operations.mysql.php','utf8');
const index=fs.readFileSync(root+'exports/index.html','utf8');

assert.match(index,/app\.js\?v=20260912-v3\.12/);
assert.match(app,/deletedShipments/);
assert.match(operations,/applyTombstones/);
assert.match(operations,/contractRef/);
assert.match(app,/Your login session expired\. Please sign in again/);
assert.match(api,/tt_current_user\(\)/);
assert.match(api,/downloadUrl'=>'\/api\/export_documents\.php/);
assert.match(app,/P\.P\. Bags/);
assert.match(app,/BOPP laminated Bags/);
assert.match(app,/Non- Woven Bags/);
assert.match(app,/customPackingTypes/);
assert.match(app,/persistPackingDraft/);
assert.match(app,/All contract containers are already allocated/);
assert.match(app,/HOW MANY CONTAINERS FOR THIS PACKING/);
assert.match(app,/Port Qasim, Pakistan or Karachi Port, Pakistan/);
assert.match(app,/customCurrencies/);
assert.match(app,/customInspections/);
assert.match(app,/Enter freight first/);
assert.match(app,/EMPTY BAGS/);
assert.match(app,/Printed Master Bag/);
assert.match(app,/master-bag-marking/);
assert.match(app,/one white-paper PO/i);
assert.match(app,/nextLotReference/);
assert.match(app,/Loading Programme No/);
assert.match(app,/portOfLoading/);
assert.match(app,/GD reference and issued GD upload are recorded later under Upload Documents/);
assert.match(app,/GD Number and Date — one per line/);
assert.match(app,/Bank \/ Account Number/);
assert.match(app,/mFIExporter/);
assert.match(app,/<option>CAD<\/option>/);
console.log('PASS approved Export operational input, upload and deletion audit');
