const fs=require('fs'),assert=require('assert');
const app=fs.readFileSync('exports/app.js','utf8'),css=fs.readFileSync('exports/app.css','utf8'),admin=fs.readFileSync('index.html','utf8'),exportsIndex=fs.readFileSync('exports/index.html','utf8');
const has=x=>assert(app.includes(x),'Missing acceptance marker: '+x);
has("const TT_PORTS=['Port Qasim, Pakistan','Karachi Port, Pakistan','Port Qasim, Pakistan or Karachi Port, Pakistan'];");
has('Have you received the signed Sales Contract?');
has('SAVE & REISSUE SAME LOADING INSTRUCTION');
has('reissuing=!!p.loading.draft?._reissueLotId');
has('Calculated proportionally from the Bag Order');
has('function ttRecoverEmptyManagedOptions(select,group)');
has('At least one '+"'+TT_REMOVABLE_OPTION_GROUPS[group].label+'"+' option must remain available.');
has('Defaults from the Sales Contract and may be changed before Production Instructions are sent.');
has('Fixed from Production Instructions.');
has("'<option value=\"__ADD_FI__\">+ Add FI</option>'");
has('100% Advance requires FI allocation equal to the full Customs Invoice value');
has('Advance + Cash Against Documents requires an FI advance above zero and below the full invoice value.');
assert(!app.slice(app.lastIndexOf('2026-09-15 TG direct-shipment Customs payment authority.')).includes('An FI allocation of at least'),'Latest TG Customs flow still inherits Sales Contract percentage validation');
has("freshCustomsInvoiceDocument(copy,c,'CUSTOM INVOICE')");
has('freshCustomPackingDocument(copy,c)');
has('freshCustomsInvoiceDocument(copy,c,\'PHYTOSANITARY INVOICE\')');
has('TOTAL NET WEIGHT');
has('TOTAL GROSS WEIGHT');
has('SHOW ALL PRICE COMPONENTS SEPARATELY ON CONTRACT');
has('approvedContractPriceGrid');
has('TOTAL ${incoterm} VALUE');
has('contractPriceGrandTotal');
has('ACCOUNT TITLE:</b>');
has('SWIFT CODE:</b>');
has('TRANSTRADE INTERNATIONAL');
assert(!app.includes("issuePO=function(){const s=shipment(),po=ensureBagDraft();if(!contractByRef(s.contractRef).received"),'Signed gate remains in Bag Order');
const finalStart=app.lastIndexOf('/* 2026-09-14 Document Output Section handover: final authoritative renderers. */');
const mountAt=app.lastIndexOf('mount();');
assert(finalStart>=0&&mountAt>finalStart,'Authoritative final output layer must execute immediately before mount');
const finalLayer=app.slice(finalStart,mountAt);
for(const name of ['contractPriceHTML','purchaseOrderPrint','blDraftDoc','phytoInvoiceDoc','packingListDoc','salesContractPrint','commercialInvoiceDoc','cooDoc'])assert(finalLayer.includes('function '+name+'('),'Final handover layer missing canonical '+name);
assert(app.lastIndexOf('function packingListDoc(')>finalStart,'Final Customs Packing renderer must be inside the handover layer');
assert(app.lastIndexOf('function phytoInvoiceDoc(')>finalStart,'Final Phytosanitary renderer must be inside the handover layer');
assert(app.lastIndexOf('function liveLotDocument(')<finalStart,'The handover renderer must execute after the live preview wrapper');
const customsStart=app.lastIndexOf('function renderCustoms(d)');
const customsEnd=app.indexOf('function customsBalanced(',customsStart);
const customsLayer=app.slice(customsStart,customsEnd);
assert(customsStart>0&&customsEnd>customsStart,'Authoritative Customs renderer is missing');
assert(!customsLayer.includes('renderCustoms__legacy'),'Authoritative Customs renderer still calls an older Customs implementation');
assert(!customsLayer.includes('ttRenderCustoms'),'Authoritative Customs renderer still calls a wrapper chain');
const fiAllocationStart=app.indexOf('function openFIAllocation(id)');
const fiAllocationEnd=app.indexOf('\nfunction removeFIAllocation',fiAllocationStart);
assert(fiAllocationStart>0&&fiAllocationEnd>fiAllocationStart,'FI allocation action is missing');
assert(app.slice(fiAllocationStart,fiAllocationEnd).includes('customsCurrencyFor(lot,c)'),'FI Register allocation does not follow the TG Customs currency');
const lotRecordStart=app.lastIndexOf('function makeLotRecord(process,plan)');
const lotRecordEnd=app.indexOf('\nconst renderLoadingBeforeBooking',lotRecordStart);
assert(lotRecordStart>0&&lotRecordEnd>lotRecordStart,'Authoritative lot creation is missing');
assert(!app.slice(lotRecordStart,lotRecordEnd).includes('makeLotRecord__legacy'),'Lot creation still delegates to a superseded implementation');
const saveContractStart=app.indexOf('function saveContract(print)');
const saveContractEnd=app.indexOf('\nfunction nextBagPoNo',saveContractStart);
assert(!app.slice(saveContractStart,saveContractEnd).includes('saveContract__legacy'),'Sales Contract save still delegates to the superseded save implementation');
const contractStepStart=app.lastIndexOf('function renderContractStep()');
const contractStepEnd=app.indexOf('\nfunction wireContractDocumentsAndTerms',contractStepStart);
assert(contractStepStart>0&&contractStepEnd>contractStepStart,'Authoritative Sales Contract step renderer is missing');
assert(!app.slice(contractStepStart,contractStepEnd).includes('renderContractStep__legacy'),'Sales Contract screens still delegate to a superseded renderer');
const contractValidationStart=app.lastIndexOf('function validateContractStep(n)');
const contractValidationEnd=app.indexOf('\nfunction salesContractPrint__legacy',contractValidationStart);
assert(contractValidationStart>0&&contractValidationEnd>contractValidationStart,'Authoritative Sales Contract validation is missing');
assert(!app.slice(contractValidationStart,contractValidationEnd).includes('validateContractStep__legacy'),'Sales Contract validation still delegates to superseded validation');
const bagOrderStart=app.lastIndexOf('function renderBagOrder(d)');
const bagOrderEnd=app.indexOf('\nfunction purchaseOrderPrint__legacy',bagOrderStart);
assert(bagOrderStart>0&&bagOrderEnd>bagOrderStart,'Authoritative Bag Order renderer is missing');
assert(!app.slice(bagOrderStart,bagOrderEnd).includes('renderBagOrder__legacy'),'Bag Order still delegates to a superseded renderer');
const issuePoStart=app.lastIndexOf('function issuePO()');
const issuePoEnd=app.indexOf('\nfunction purchaseOrderPrint__morning_base',issuePoStart);
assert(issuePoStart>0&&issuePoEnd>issuePoStart,'Authoritative Bag Order issue action is missing');
assert(!app.slice(issuePoStart,issuePoEnd).includes('issuePO__legacy'),'Bag Order issue still delegates to a superseded action');
const loadingStart=app.lastIndexOf('function renderLoading(d)');
const loadingEnd=app.indexOf('\nfunction openLoadingReissue(',loadingStart);
assert(loadingStart>0&&loadingEnd>loadingStart,'Authoritative Loading Instructions renderer is missing');
assert(!app.slice(loadingStart,loadingEnd).includes('renderLoading__legacy'),'Loading Instructions still delegate to a superseded renderer');
const blStart=app.lastIndexOf('function renderBL(d)');
const blEnd=app.indexOf('\nconst renderDocumentOutputBeforeUploadedDocuments',blStart);
assert(blStart>0&&blEnd>blStart,'Authoritative B/L renderer is missing');
assert(!app.slice(blStart,blEnd).includes('renderBL__legacy'),'B/L screen still delegates to a superseded renderer');
const commercialStart=app.lastIndexOf('function renderCommercial(d)');
const commercialEnd=app.indexOf('\nfunction applyNewCustomerContractDefaults',commercialStart);
assert(commercialStart>0&&commercialEnd>commercialStart,'Authoritative Commercial Documents renderer is missing');
assert(!app.slice(commercialStart,commercialEnd).includes('renderCommercial__legacy'),'Commercial Documents still delegate to a superseded renderer');
for(const [name,endMarker] of [['commercialInvoiceDoc','function packingSummaryGroups'],['packingListDoc','function cooDoc'],['blDraftDoc','function ttContractPackingPriceLabel']]){const start=app.lastIndexOf('function '+name+'('),end=app.indexOf('\n'+endMarker,start);assert(start>0&&end>start,'Authoritative '+name+' is missing');assert(!app.slice(start,end).includes(name+'__legacy'),'Authoritative '+name+' still delegates to a superseded document renderer')}
assert(!app.includes('renderCertificates=renderCertificatesApproved'),'Certificates still use a mutable late override');
const tgStart=app.lastIndexOf('function renderTG(d)');
const tgEnd=app.indexOf('\n\n/* 2026-09-12 blank',tgStart);
assert(tgStart>0&&tgEnd>tgStart,'Authoritative TG internal documents renderer is missing');
assert(!app.slice(tgStart,tgEnd).includes('renderTG__legacy'),'TG internal documents still delegate to a superseded renderer');
assert(app.slice(tgStart,tgEnd).includes('currency=customsCurrencyFor(s,c)'),'TG internal-document screen is not using the separate Customs currency');
const cooStart=app.lastIndexOf('function cooDoc('),cooEnd=app.indexOf('\nfunction renderShipmentWorkspace',cooStart);assert(cooStart>0&&cooEnd>cooStart&&!app.slice(cooStart,cooEnd).includes('cooDoc__legacy'),'Certificate of Origin still delegates to a superseded renderer');
const outputStart=app.lastIndexOf('function renderDocumentOutput(d)'),outputEnd=app.indexOf('\nfunction renderTG(d)',outputStart);assert(outputStart>0&&outputEnd>outputStart&&!app.slice(outputStart,outputEnd).includes('renderDocumentOutput__legacy'),'Final Output still delegates to a superseded renderer');
const productionStart=app.lastIndexOf('function renderProduction(d)');
const productionEnd=app.indexOf('\nfunction ttDedupeSelectOptions',productionStart);
assert(!app.slice(productionStart,productionEnd).includes('renderProduction__legacy'),'Production Instructions still delegates to the superseded renderer');
assert(app.includes("return freshCustomsInvoiceDocument(s,c,'PHYTOSANITARY INVOICE')"),'Phytosanitary is not tied to the Customs renderer');
assert(css.includes('.salesContractFlowPage .docTitle'),'Continuous Sales Contract title rule missing');
assert(css.includes('.contractFlowLayout>thead{display:table-header-group}'),'Repeated heading print rule missing');
assert(css.includes('.customsPreviewStack'),'Single Customs preview stack style missing');
assert(admin.includes('brand-theme.css?v=20260914-control-centre-1'),'Control Centre theme missing');
assert(/app\.js\?v=20260915-commercial-docs-1/.test(exportsIndex),'Exports cache-bust marker missing');
assert.equal(app.split('\n').filter(line=>/^[A-Za-z_$][\w$]*\s*=\s*function\s*\(/.test(line)).length,0,'Mutable Export function override remains');
console.log('Exports September 14 exact acceptance audit passed.');
