const fs=require('fs');
const assert=require('assert');
const path=require('path');
const app=fs.readFileSync(path.join(__dirname,'../../exports/app.js'),'utf8');
const operations=fs.readFileSync(path.join(__dirname,'../../api/operations.mysql.php'),'utf8');

assert.ok(!app.includes('class="panel lotFooter"'),'Mark Lot Complete must not render in the global lot workspace footer');
assert.match(app,/workspaceHead[\s\S]*id="cancelLot"/,'Cancel Lot remains available in the lot header');
const outputStart=app.lastIndexOf('function renderDocumentOutput(d)'),outputEnd=app.indexOf('\nfunction renderTG(d)',outputStart),output=app.slice(outputStart,outputEnd);
assert.equal((output.match(/id="completeLot"/g)||[]).length,1,'completion control exists only in the unified final-output renderer');
assert.match(output,/lotCompleteButton.*LOT COMPLETE/,'larger completion button stays in Final Output');
assert.doesNotMatch(output,/id="chooseShipmentFolder"|id="saveShipmentFiles"/,'redundant folder buttons are removed');
const missing=app.slice(app.indexOf('function completionMissing(s,c)'),app.indexOf("document.addEventListener('click',async e=>"));
assert.doesNotMatch(missing,/covering|frozen|dispatched/,'covering letter and freeze must not block closure');
assert.match(app,/s\.completed=true[\s\S]*const confirmed=await confirmLotCompletionSave\(attempted,s\.id\)[\s\S]*await saveShipmentFolder\(completedLot,completedContract\)/,'lot completion is confirmed before the Office Agent folder is queued');
assert.match(app,/if\(e\.target\?\.id==='completeLot'\)[\s\S]*completionMissing\(s,c\)/,'click handler revalidates completion server-side state before closing the lot');
assert.match(app,/function confirmLotCompletionSave\(payload,lotId\)[\s\S]*120000/,'lot completion waits for a slow hosted save before failing');
assert.match(app,/const confirmed=await confirmLotCompletionSave\(attempted,s\.id\)/,'lot completion uses the durable confirmation helper for the final save');
assert.match(app,/function requeueCompletedShipmentFolder\(button,s,c\)[\s\S]*saveShipmentFolder\(s,c,false\)/,'completed lots can requeue the final Office Agent folder without reopening');
assert.match(app,/strictFinal:true/,'Office Agent final package uses the strict final document folder format');
const requeue=app.slice(app.indexOf('function requeueCompletedShipmentFolder'),app.indexOf('\nfunction recordUploadedDocument'));
assert.doesNotMatch(requeue,/saveNow/,'completed lot office-folder requeue must not wait on a new shared save');
assert.match(app,/QUEUE OFFICE FOLDER/,'completed lot view exposes an explicit Office Agent requeue action');
assert.match(app,/function millActualsIssues\(s\)[\s\S]*seal number\(s\) missing/,'Mill loading status reports the exact blocking reason instead of only a count');
assert.match(operations,/function operations_merge_mill_actuals/,'server merge refreshes stale partial Mill actuals instead of preserving old blockers');
assert.equal((operations.match(/operations_merge_mill_actuals/g)||[]).length,3,'Milling and Export saves both use the dedicated Mill actuals merge');
assert.match(app,/phyto:\{label:'Phytosanitary Certificate'[\s\S]*phytosanitary/,'Phytosanitary uploads satisfy phyto certificate requirements');
const uploadHandler=app.slice(app.indexOf('button.onclick=async()=>',app.indexOf('function renderUploadDocuments')),app.indexOf('\n };\n}',app.indexOf('function renderUploadDocuments')));
assert.doesNotMatch(uploadHandler,/saveShipmentFolder/,'document uploads must not build the full office shipment package during normal saves');

console.log('PASS lot completion stage audit: final-output-only placement, upload gates, exact mill/doc checks, completed-lot hiding, click-time revalidation');
