from pathlib import Path
import re

path = Path('exports/app.js')
text = path.read_text(encoding='utf-8')

new_contract_block = r'''function readerBody(kind,shipId=''){return`<div class="notice info"><b>AI document reader: Gemini</b><br>The original document is sent securely from the Transtrade server to Gemini for extraction. Nothing becomes shipment data until a user reviews and confirms it. If Gemini is unavailable, the existing local reader can be used as a fallback.</div>${kind==='lc'?`<div class="field"><label>Shipment / Contract</label><select id="readerShipment">${processes().map(s=>`<option value="${esc(s.id)}" ${shipId===s.id?'selected':''}>${esc(s.contractRef)} · ${esc(s.buyer)}</option>`).join('')}</select></div>`:''}<div class="field"><label>${kind==='lc'?'L/C':'Customer contract'} file</label><input id="readerFile" type="file" accept=".pdf,.docx,.txt,.png,.jpg,.jpeg,.webp"></div><div class="field"><label>Or paste document text</label><textarea id="readerText" style="min-height:150px"></textarea></div><div id="readerSource" class="metaText"></div><div id="readerProgress" class="metaText"></div><div id="readerReview"></div>`}
async function readWithGemini(kind,file,text,progress=()=>{}){const access=window.TT_MODULE_ACCESS||{},body=new FormData();body.append('csrf',access.csrf||'');body.append('kind',kind);let suppliedText=String(text||'').trim();if(file){const url=URL.createObjectURL(file),source=document.getElementById('readerSource');if(source)source.innerHTML=`Original: <a href="${url}" target="_blank" rel="noopener">${esc(file.name)}</a>`;if(/\.docx$/i.test(file.name)){progress('Reading DOCX locally before Gemini analysis…');suppliedText=await readFile(file,progress)}else body.append('file',file)}if(suppliedText)body.append('text',suppliedText);if(!file&&!suppliedText)throw new Error('Choose a document or paste its text.');progress('Gemini is reading the document…');const response=await fetch('api/document_ai.php',{method:'POST',credentials:'same-origin',body}),result=await response.json().catch(()=>({ok:false,error:'AI document reader returned an invalid response.'}));if(!response.ok||!result.ok){const error=new Error(result.error||'Gemini could not read this document.');error.code=result.code||'';throw error}const data=result.data||{};data.sourceText=suppliedText||`[Gemini visual extraction from ${file?.name||'uploaded document'}]`;data._readerProvider=result.provider||'Gemini';data._readerModel=result.model||'';return data}
function readerNotesHTML(x,kind){const notes=Array.isArray(x?.notes)?x.notes.filter(Boolean):[],extras=[];if(kind==='lc'){if(x.tolerance)extras.push(`Amount tolerance: ${x.tolerance}`);if(x.expiryPlace)extras.push(`Expiry place: ${x.expiryPlace}`);if(x.bankCharges)extras.push(`Bank charges: ${x.bankCharges}`);if(x.insuranceRequirement)extras.push(`Insurance: ${x.insuranceRequirement}`);if(x.blInstructions)extras.push(`B/L instructions: ${x.blInstructions}`)}const all=[...notes,...extras];return all.length?`<div class="notice warn"><b>AI review points</b><br>${all.map(esc).join('<br>')}</div>`:''}
function decorateContractAIReview(x){const section=document.querySelector('#readerReview .section');if(section){const note=readerNotesHTML(x,'contract');if(note)section.insertAdjacentHTML('afterbegin',note);section.insertAdjacentHTML('afterbegin',`<div class="metaText">Reader: ${esc(x._readerProvider||'Local')} ${x._readerModel?`· ${esc(x._readerModel)}`:''}</div>`)}const button=document.getElementById('saveContractImport');if(button&&button.onclick){const original=button.onclick;button.onclick=()=>{const existing=new Set(state.contracts.map(c=>c.ref));original();const created=state.contracts.find(c=>!existing.has(c.ref));if(created?.sourceDocument){created.sourceDocument.reader=x._readerProvider||'Local fallback';created.sourceDocument.model=x._readerModel||'';created.sourceDocument.reviewNotes=Array.isArray(x.notes)?x.notes:[];save();window.TT_SHARED_SYNC?.flush?.()}}}}
function openContractUpload(){openModal('Upload Customer Contract',readerBody('contract'),`<button class="btn" data-modal-close>Close</button><button class="btn green" id="readerRun">READ WITH GEMINI</button>`);document.getElementById('readerRun').onclick=async()=>{const progress=document.getElementById('readerProgress'),file=document.getElementById('readerFile').files[0],pasted=document.getElementById('readerText').value.trim();try{progress.textContent='Reading with Gemini…';const x=await readWithGemini('contract',file,pasted,msg=>progress.textContent=msg);progress.textContent='Gemini extraction complete — review every field below.';showContractReview(x);decorateContractAIReview(x)}catch(e){progress.textContent=`Gemini reader unavailable: ${e.message}`;if(!confirm(`${e.message}\n\nUse the local document reader instead?`))return;try{const raw=pasted||await readFile(file,msg=>progress.textContent=msg),x=parseContractText(raw);x._readerProvider='Local fallback';x._readerModel='';progress.textContent='Local fallback extraction complete — review every field below.';showContractReview(x);decorateContractAIReview(x)}catch(localError){progress.textContent='';alert(localError.message)}}}}
'''

pattern_contract = re.compile(r"function readerBody\(kind,shipId=''\)\{.*?\nfunction showContractReview__legacy_v0", re.S)
match = pattern_contract.search(text)
if not match:
    raise SystemExit('Could not locate customer-contract reader block')
text = text[:match.start()] + new_contract_block + 'function showContractReview__legacy_v0' + text[match.end():]

new_lc_block = r'''function openLCUpload(shipId=''){if(!state.shipments.length)return alert('Create or import a contract first.');openModal('Upload L/C',readerBody('lc',shipId),`<button class="btn" data-modal-close>Close</button><button class="btn green" id="readerRun">READ L/C WITH GEMINI</button>`);document.getElementById('readerRun').onclick=async()=>{const progress=document.getElementById('readerProgress'),file=document.getElementById('readerFile').files[0],pasted=document.getElementById('readerText').value.trim();try{progress.textContent='Reading L/C with Gemini…';const x=await readWithGemini('lc',file,pasted,msg=>progress.textContent=msg);progress.textContent='Gemini extraction complete — compare it with the Sales Contract below.';showLCReview(x);decorateLCAIReview(x)}catch(e){progress.textContent=`Gemini reader unavailable: ${e.message}`;if(!confirm(`${e.message}\n\nUse the local document reader instead?`))return;try{const raw=pasted||await readFile(file,msg=>progress.textContent=msg),x=parseLCText(raw);x._readerProvider='Local fallback';x._readerModel='';progress.textContent='Local fallback extraction complete — compare it with the Sales Contract below.';showLCReview(x);decorateLCAIReview(x)}catch(localError){progress.textContent='';alert(localError.message)}}}}
function decorateLCAIReview(x){const section=document.querySelector('#readerReview .section');if(!section)return;section.insertAdjacentHTML('afterbegin',`<div class="metaText">Reader: ${esc(x._readerProvider||'Local')} ${x._readerModel?`· ${esc(x._readerModel)}`:''}</div>${readerNotesHTML(x,'lc')}`);const grid=section.querySelector('.grid3');if(grid){grid.insertAdjacentHTML('beforeend',`<div class="field"><label>L/C Amount Tolerance</label><input id="rlTolerance" value="${esc(x.tolerance||'')}"></div><div class="field"><label>Expiry Place</label><input id="rlExpiryPlace" value="${esc(x.expiryPlace||'')}"></div><div class="field full"><label>Bank Charges</label><textarea id="rlBankCharges">${esc(x.bankCharges||'')}</textarea></div><div class="field full"><label>Insurance Requirement</label><textarea id="rlInsuranceReq">${esc(x.insuranceRequirement||'')}</textarea></div><div class="field full"><label>B/L Instructions</label><textarea id="rlBLInstructions">${esc(x.blInstructions||'')}</textarea></div>`)}const button=document.getElementById('saveLCImport');if(button&&button.onclick){const original=button.onclick;button.onclick=()=>{const shipId=document.getElementById('readerShipment')?.value||'',extra={tolerance:document.getElementById('rlTolerance')?.value.trim()||'',expiryPlace:document.getElementById('rlExpiryPlace')?.value.trim()||'',bankCharges:document.getElementById('rlBankCharges')?.value.trim()||'',insuranceRequirement:document.getElementById('rlInsuranceReq')?.value.trim()||'',blInstructions:document.getElementById('rlBLInstructions')?.value.trim()||'',reader:x._readerProvider||'Local fallback',readerModel:x._readerModel||'',readerNotes:Array.isArray(x.notes)?x.notes:[]};original();const s=state.shipments.find(v=>v.id===shipId);if(s?.lc){Object.assign(s.lc,extra);lotsFor(s).forEach(l=>{if(l.lc)Object.assign(l.lc,structuredClone(extra))});save();window.TT_SHARED_SYNC?.flush?.()}}}}
function lcMovementFields'''

pattern_lc = re.compile(r"function openLCUpload\(shipId=''\)\{.*?\nfunction lcMovementFields", re.S)
match = pattern_lc.search(text)
if not match:
    raise SystemExit('Could not locate L/C reader block')
text = text[:match.start()] + new_lc_block + text[match.end():]

path.write_text(text, encoding='utf-8')
print('Gemini reader patch applied.')
