const {test,expect}=require('@playwright/test');
const base='http://127.0.0.1:8765';
async function caption(page,title,detail,ms=1800){await page.evaluate(({title,detail})=>{document.querySelector('#qaVideoCaption')?.remove();const box=document.createElement('aside');box.id='qaVideoCaption';box.style.cssText='position:fixed;z-index:9999999;bottom:14px;left:14px;max-width:800px;background:#12364f;color:white;border:2px solid #63cda0;border-radius:12px;padding:13px 17px;font:18px/1.35 Arial;box-shadow:0 7px 28px #0007';box.innerHTML='<b>'+title+'</b><br><span style="font-size:15px">'+detail+'</span>';document.body.appendChild(box)},{title,detail});await page.waitForTimeout(ms)}
async function login(page){await page.goto(base+'/login.php');await page.locator('[name="username"]').fill('qa.video');await page.locator('[name="password"]').fill(process.env.QA_VIDEO_PASSWORD);await page.locator('button[type="submit"]').click();await expect(page).toHaveURL(/accounts\/index\.php/)}
test('Remaining Accounts: recognized export receipt and print voucher',async({page})=>{
 test.setTimeout(150000);page.setDefaultTimeout(10000);
 await login(page);
 await caption(page,'Remaining suite: export receipt','The invoice candidate and QA bank are isolated fixture records. Amounts and bank advice are illustrative.');
 await page.locator('[data-tt-area="exports"]').click();
 await page.locator('#ttDeskWork .tt-action').filter({hasText:'Bank Receipt / Credit Advice'}).click();
 await expect(page.locator('#ttExportReceiptDialog')).toBeVisible();
 await caption(page,'Choose bank first','The company account comes from the TTI master. Its identity and currency should be visible.');
 const banks=await page.locator('#erPkrBank option').allTextContents();
 expect(banks.some(x=>x.includes('QA Demonstration Bank')||x.includes('QA Video PKR'))).toBeTruthy();
 const bankValue=await page.locator('#erPkrBank option').evaluateAll(xs=>xs.find(x=>x.value)?.value||'');
 await page.locator('#erPkrBank').selectOption(bankValue);
 await page.locator('[data-payer-type="CUSTOMER"]').click();
 await expect(page.locator('#erPayer')).toBeVisible();
 await page.locator('#erPayer').selectOption({label:'Ladoo General Trading LLC'});
 await expect(page.locator('[data-er-item^="INV|"]').first()).toBeVisible();
 await caption(page,'Outstanding invoice','The recognized commercial invoice is selectable as a balance item. An unposted invoice must not appear as receivable.');
 await page.locator('[data-er-item^="INV|"]').first().check();
 await page.locator('[data-er-applied^="INV|"]').first().fill('10000');
 await page.locator('#erBankRef').fill('QA-CREDIT-ADVICE-001');
 await page.locator('#erForeign').fill('10000');
 await page.locator('#erRate').fill('280');
 await page.locator('#erBankCredit').fill('2800000');
 await caption(page,'Credit Advice entry','USD 10,000 at illustrative PKR 280. The debit and credit preview should be visible before posting.');
 await expect(page.locator('#erAccountingRows')).not.toContainText('Enter receipt amounts to see');
 await page.locator('#erPost').click();
 await expect(page.getByText('Print Receipt Voucher')).toBeVisible({timeout:15000});
 await caption(page,'Receipt posted','The system offers a printable receipt voucher and records a remaining outstanding invoice balance.');
 const data=await page.evaluate(async()=>{const r=await fetch('../api/export_receipts.php?entity=TTI');return r.json()});
 expect(data.receipts.some(x=>x.bankAdviceRef==='QA-CREDIT-ADVICE-001')).toBeTruthy();
});

test('Remaining Accounts: raw, ready and corn purchase commitments',async({page})=>{
 test.setTimeout(180000);page.setDefaultTimeout(12000);
 await login(page);
 await page.locator('[data-tt-area="commodity"]').click();
 const launch=async()=>{await page.locator('#ttDeskWork .tt-action').filter({hasText:'Soda Centre'}).click();await expect(page.locator('#ttSodaForm')).toBeVisible()};
 const selectText=async(id,needle)=>{const value=await page.locator(id+' option').evaluateAll((options,text)=>options.find(x=>x.textContent.includes(text))?.value||'',needle);expect(value,needle+' option').toBeTruthy();await page.locator(id).selectOption(value)};
 const enter=async({product,supplier,broker,route,unit,rate,qty,captionTitle})=>{
  await launch();await caption(page,captionTitle,'A Soda reserves the purchase terms. Saving it must create no ledger posting.');
  await selectText('#ttSdProduct',product);
  if(supplier)await selectText('#ttSdSupplier',supplier);
  if(broker)await selectText('#ttSdBroker',broker);
  if(route){await page.locator('#ttSdRoute').selectOption(route);if(route==='EX_MILL')await selectText('#ttSdExMill','QA Outside Mill')}
  await page.locator('#ttSdTrucks').fill('2');
  if(route==='EX_MILL')await page.locator('#ttSdTarget').fill(qty);
  else {await page.locator('#ttSdMin').fill(qty);await page.locator('#ttSdMax').fill(qty)}
  await page.locator('#ttSdRate').fill(rate);await page.locator('#ttSdUnit').selectOption(unit);
  await page.locator('#ttSdDue').fill('2026-10-10');
  const alert=page.waitForEvent('dialog');await page.locator('#ttSodaForm button[type="submit"]').click();const dialog=await alert;expect(dialog.message()).toContain('No ledger entry was posted');await dialog.accept();
  await expect(page.locator('#ttSodaLayer')).toBeHidden();
 };
 await enter({product:'IRRI-6',supplier:'QA Rice Supplier',broker:'QA Purchase Broker',unit:'KG',rate:'125',qty:'50',captionTitle:'Raw rice · supplier and broker'});
 await caption(page,'Raw rice saved','The supplier receives the commodity liability when the Pohanch bill is approved; brokerage belongs to the broker.');
 await enter({product:'READY',supplier:'QA Rice Supplier',route:'EX_MILL',unit:'KG',rate:'155',qty:'54',captionTitle:'Ready rice · external mill'});
 await caption(page,'Ready EX-MILL saved','Container weight is the purchase quantity for this route. The later bill can select multiple containers.');
 await enter({product:'Corn / Makai',supplier:'QA Corn Supplier',unit:'MAUND',rate:'2600',qty:'30',captionTitle:'Corn · rate per maund'});
 await caption(page,'Corn saved','The rate is entered per 40 kg maund; the arrival bill later follows one Pohanch per bill.');
 const data=await page.evaluate(async()=>{const r=await fetch('../api/purchase_sodas.php?entity=TTI');return r.json()});
 expect(data.sodas.length).toBeGreaterThanOrEqual(3);
});

test('Remaining Accounts: salary advance, adjustment and payment',async({page})=>{
 test.setTimeout(180000);page.setDefaultTimeout(12000);
 await login(page);
 await page.locator('[data-tt-area="routine"]').click();
 await page.locator('#ttDeskWork .tt-action').filter({hasText:'Salaries & Staff'}).click();
 await expect(page.locator('#rsAdvancePerson')).toBeVisible();
 await caption(page,'Staff master','The approved staff list already supplies salary amounts. Select the existing Irfan master for this QA entry.');
 await page.locator('#rsAdvancePerson').selectOption({label:'IRFAN'});
 await caption(page,'Salary advance','An advance is recorded when paid. The month of salary will prompt for adjustment.');
 await page.locator('#rsAdvanceAmount').fill('10000');
 await expect(page.locator('#rsAdvanceAccount option').first()).toBeAttached();
 await page.locator('#rsAdvanceSave').click();
 await expect(page.locator('#ttRsToast')).toContainText('advance posted');
 await caption(page,'Prepare the month','The adjustment box defaults to the suggested advance amount; Accounts can reduce it.');
 await page.locator('#rsPrepare').click();
 await expect(page.locator('#rsAdvanceConfirm')).toBeVisible();
 const suggested=await page.locator('[data-advance-master]').inputValue();
 expect(Number(suggested)).toBeGreaterThan(0);
 await page.locator('[data-advance-master]').fill('6000');
 await caption(page,'Carry forward Rs 4,000','The user adjusts Rs 6,000 now; the unadjusted advance remains for a later salary.');
 await page.locator('#rsAdvanceConfirm').click();
 await expect(page.locator('.ttrs').getByText('Monthly Salary Sheet')).toBeVisible();
 await expect(page.locator('#rsPaySalBtn')).toBeVisible();
 const balance=await page.locator('#rsPaySalMaster option').evaluateAll(xs=>xs.find(x=>x.textContent.includes('IRFAN'))?.value||'');
 expect(balance).toBeTruthy();
 await page.locator('#rsPaySalMaster').selectOption(balance);
 const dueText=await page.locator('#rsPaySalMaster option:checked').textContent();
 const due=Number((dueText.match(/Balance Rs\s*([\d,]+(?:\.\d+)?)/)||[])[1]?.replaceAll(',',''));
 expect(due).toBeGreaterThan(0);
 await page.locator('#rsPaySalAmt').fill(String(due));
 await caption(page,'Salary payment','The prepared salary balance is paid from the selected company account.');
 await page.locator('#rsPaySalBtn').click();
 await expect(page.locator('#ttRsToast')).toContainText('Salary payment saved');
 await caption(page,'Salary closed','Master, advance, editable adjustment and payment have been posted in the disposable QA book.');
});

test('Remaining Accounts: raw Pohanch bill and ready multi-container bill',async({page})=>{
 test.setTimeout(180000);page.setDefaultTimeout(12000);
 await login(page);
 await page.locator('[data-tt-area="commodity"]').click();
 await page.locator('#ttDeskWork .tt-action').filter({hasText:'Bill Posting'}).click();
 await expect(page.locator('#ttsbSupplier')).toBeVisible();
 await caption(page,'Bill Posting','The saved Pohanch and two ready container receipts are local fixtures representing Mill handover.');
 await page.locator('#ttsbSupplier').selectOption({label:'QA Rice Supplier'});
 await page.locator('#ttsbSoda').selectOption({label:'Soda 26901'});
 await page.locator('#ttsbTruck').selectOption({index:1});
 await expect(page.locator('#ttsbFinal')).toHaveValue('3375000.00');
 await caption(page,'Raw rice · one Pohanch','27,000 kg at Rs 125/kg. Supplier gets the commodity payable; the broker gets net brokerage after 15% WHT.');
 await page.locator('#ttsbBillNo').fill('QA-RAW-BILL-01');
 await page.locator('#ttsbRate').fill('50');
 await expect(page.locator('#ttsbWithAmt')).toHaveValue('2025.00');
 await page.locator('#ttsbAddAddition').click();
 await page.locator('[data-line-description]').first().fill('Kanta');await page.locator('[data-line-amount]').first().fill('200');
 await page.locator('#ttsbAddDeduction').click();
 await page.locator('[data-line-description]').last().fill('Filling deduction');await page.locator('[data-line-amount]').last().fill('100');
 await caption(page,'Bill verification','Kanta and filling alter the commodity total. The posting preview separates gross brokerage, broker payable and WHT.');
 await page.locator('#ttsbVerify').click();
 await expect(page.locator('.ttsb-posting')).toBeVisible();
 await caption(page,'Raw bill posted','The application assigns a Post ID for the original supplier bill.');
 await page.locator('.ttsb-posting button').click();
 await page.locator('#ttsbSupplier').selectOption({label:'QA Rice Supplier'});
 await page.locator('#ttsbSoda').selectOption({label:'Soda 26902'});
 await page.locator('#ttsbTruck').selectOption({index:1});
 await expect(page.locator('#ttsbMultiple')).not.toBeChecked();
 await page.locator('#ttsbMultiple').check();
 await expect(page.locator('[data-bill-source]:checked')).toHaveCount(2);
 await caption(page,'Ready rice · two containers','The multiple option begins unticked. When selected, both container receipts are ticked and their weights are added.');
 await page.locator('#ttsbBillNo').fill('QA-READY-BILL-01');
 await page.locator('#ttsbVerify').click();
 await expect(page.locator('.ttsb-posting')).toBeVisible();
 await caption(page,'Ready bill posted','One supplier bill includes both selected containers in the same Soda.');
});

test('Remaining Accounts: Mill local sale approval and ledger reports',async({page})=>{
 test.setTimeout(150000);page.setDefaultTimeout(12000);
 await login(page);
 await page.locator('[data-tt-area="commodity"]').click();
 await page.locator('#ttDeskWork .tt-action').filter({hasText:'Local Sales & Receipts'}).click();
 await expect(page.locator('[data-ttls-approve]')).toBeVisible();
 await caption(page,'Mill → Accounts local sale','The QA Gate Pass candidate is queued by the disposable Mill fixture. Accounts sees the party, quantity and sale value.');
 const dialog=page.waitForEvent('dialog');await page.locator('[data-ttls-approve]').click();const confirmation=await dialog;await confirmation.accept();
 await expect(page.locator('#ttLocalSalesToast')).toContainText('Local Sale approved');
 await caption(page,'Local sale posted','The approved sale becomes an Accounts journal and is removed from the waiting queue.');
 await page.locator('.workspace.active .panelHead [data-back]').click();
 await page.locator('.tt-back-areas').click();
 await page.locator('[data-tt-area="ledgers"]').click();
 await page.locator('#ttDeskWork .tt-action').filter({hasText:'All Ledgers'}).click();
 await expect(page.locator('#tal-print')).toBeVisible();
 await expect(page.locator('#tal-export')).toBeVisible();
 await caption(page,'All Ledgers','Review the posted entries by company, account and date, with print and export controls.');
});
