<?php
declare(strict_types=1);
require dirname(__DIR__).'/auth_store.php';
header('Content-Type: application/json; charset=UTF-8');
header('Cache-Control: no-store, no-cache, must-revalidate');
const AST_OPS_KEY='transtrade_export_v3_operational';

function ast_out(array $v,int $s=200):never{http_response_code($s);echo json_encode($v,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function ast_env(string $n):string{$c='TT_'.$n;if(defined($c))return(string)constant($c);$v=getenv($c);return$v===false?'':(string)$v;}
function ast_db():?PDO{if(ast_env('DB_HOST')===''||ast_env('DB_NAME')===''||ast_env('DB_USER')==='')return null;return new PDO('mysql:host='.ast_env('DB_HOST').';dbname='.ast_env('DB_NAME').';charset=utf8mb4',ast_env('DB_USER'),ast_env('DB_PASS'),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);}
function ast_root():array{$db=ast_db();if($db){$q=$db->prepare('SELECT payload FROM tt_operation_records WHERE storage_key=? LIMIT 1');$q->execute([AST_OPS_KEY]);$raw=$q->fetchColumn();$v=is_string($raw)?json_decode($raw,true):null;return is_array($v)?$v:[];}$p=TT_DATA_DIR.'/operations.json';$raw=is_file($p)?file_get_contents($p):false;$ops=$raw?json_decode($raw,true):null;$v=is_array($ops)?json_decode((string)($ops['values'][AST_OPS_KEY]??''),true):null;return is_array($v)?$v:[];}
function ast_accounts():array{$p=TT_DATA_DIR.'/accounts.json';$raw=is_file($p)?file_get_contents($p):false;$v=$raw?json_decode($raw,true):null;return is_array($v)?$v:[];}
function ast_documents():array{$out=[];$db=ast_db();if($db)try{$rows=$db->query('SELECT id,contract_ref,lot_ref,category,original_name,mime_type,file_size,uploaded_at FROM tt_export_documents WHERE deleted_at IS NULL ORDER BY uploaded_at DESC')->fetchAll();foreach($rows as$r)$out[]=['id'=>(string)$r['id'],'contractRef'=>(string)$r['contract_ref'],'lotRef'=>(string)$r['lot_ref'],'category'=>(string)$r['category'],'name'=>(string)$r['original_name'],'mime'=>(string)$r['mime_type'],'size'=>(int)$r['file_size'],'uploadedAt'=>(string)$r['uploaded_at'],'downloadUrl'=>'/api/export_documents.php?id='.(string)$r['id']];return$out;}catch(Throwable $e){error_log('Sales tax document DB lookup: '.$e->getMessage());}$p=TT_DATA_DIR.'/export_documents/index.json';$raw=is_file($p)?file_get_contents($p):false;$rows=$raw?json_decode($raw,true):[];foreach((array)$rows as$r)if(is_array($r)&&empty($r['deleted_at']))$out[]=['id'=>(string)($r['id']??''),'contractRef'=>(string)($r['contract_ref']??''),'lotRef'=>(string)($r['lot_ref']??''),'category'=>(string)($r['category']??''),'name'=>(string)($r['original_name']??'Document'),'mime'=>(string)($r['mime_type']??''),'size'=>(int)($r['file_size']??0),'uploadedAt'=>(string)($r['uploaded_at']??''),'downloadUrl'=>'/api/export_documents.php?id='.(string)($r['id']??'')];return$out;}
function ast_date(string $v):string{if($v===''||preg_match('/^\d{4}-\d{2}-\d{2}$/',$v))return$v;ast_out(['ok'=>false,'error'=>'Use a valid date range.'],422);}
function ast_exporter(array $s,array $c):string{$seller=strtoupper((string)($s['seller']??$c['seller']??'TTI'));if($seller==='TG')return strtoupper((string)($s['customs']['exporter']??$c['customsExporter']??'TTI'))==='BRM'?'BRM':'TTI';return$seller==='BRM'?'BRM':'TTI';}
function ast_refs(mixed $value):array{$out=[];foreach((array)$value as$x){$v=is_array($x)?(string)($x['no']??$x['number']??$x['ref']??''):(string)$x;if(trim($v)!=='')$out[]=trim($v);}return array_values(array_unique($out));}

try{
 $u=tt_require_login();if(!tt_user_can_open_module($u,'Accounts'))ast_out(['ok'=>false,'error'=>'Accounts permission required.'],403);$entity=strtoupper(trim((string)($_GET['entity']??'')));if(!in_array($entity,['TTI','BRM'],true))ast_out(['ok'=>false,'error'=>'Sales Tax export documents are available for TTI or BRM.'],422);if(($u['role']??'')!=='Super Admin'&&!tt_user_can_access_entity($u,$entity,'View'))ast_out(['ok'=>false,'error'=>'You do not have permission for these company books.'],403);$from=ast_date(trim((string)($_GET['from']??'')));$to=ast_date(trim((string)($_GET['to']??'')));$needle=strtolower(trim((string)($_GET['q']??'')));$root=ast_root();$accounts=ast_accounts();$docs=ast_documents();$contracts=[];foreach((array)($root['contracts']??[])as$c)if(is_array($c))$contracts[(string)($c['ref']??$c['id']??'')]=$c;$rows=[];
 foreach((array)($root['shipments']??[])as$s){if(!is_array($s)||!empty($s['cancelled']))continue;$ref=(string)($s['contractRef']??'');$c=$contracts[$ref]??[];if(ast_exporter($s,$c)!==$entity)continue;$commercial=is_array($s['commercial']??null)?$s['commercial']:[];$customs=is_array($s['customs']??null)?$s['customs']:[];$date=(string)($commercial['date']??$commercial['invoiceDate']??$customs['invoiceDate']??$s['shipmentDate']??'');if($from!==''&&$date!==''&&$date<$from)continue;if($to!==''&&$date!==''&&$date>$to)continue;$lot=(string)($s['lotId']??$s['lotRef']??$s['id']??'');$invoice=(string)($commercial['invoiceNo']??$customs['invoiceNo']??'');$customer=(string)($s['buyer']??$c['customer']??'');$gds=array_values(array_unique(array_merge(ast_refs($customs['gdRefs']??[]),ast_refs($commercial['gd']??[]),ast_refs($commercial['gdRefs']??[]))));$bl=(string)($s['bl']['blNo']??'');$hay=strtolower(implode(' ',[$ref,$lot,$invoice,$customer,$bl,implode(' ',$gds),(string)($s['id']??'')]));if($needle!==''&&!str_contains($hay,$needle))continue;$rowDocs=[];foreach($docs as$d)if(($d['contractRef']??'')===$ref&&(($d['lotRef']??'')===''||($d['lotRef']??'')===$lot||($d['lotRef']??'')===(string)($s['id']??'')))$rowDocs[]=$d;$adv=[];foreach((array)($accounts['exportReceipts']??[])as$r){if(!is_array($r)||($r['entity']??'')!==$entity)continue;$match=false;foreach((array)($r['allocations']??[])as$a)if(is_array($a)&&((string)($a['contractRef']??'')===$ref||($invoice!==''&&(string)($a['invoiceRef']??'')===$invoice))){$match=true;break;}if(!$match)continue;$ded=[];foreach((array)($r['deductions']??[])as$d)if(is_array($d))$ded[]=['name'=>(string)($d['name']??$d['masterCode']??'Tax / charge'),'amount'=>(float)($d['amount']??0),'taxSection'=>(string)($d['taxSection']??'')];$file=(string)($r['bankAdviceFileRef']??'');$adv[]=['receiptNo'=>(string)($r['id']??''),'date'=>(string)($r['date']??''),'bankAdviceRef'=>(string)($r['bankAdviceRef']??''),'fileRef'=>$file,'paperRef'=>(string)($r['bankAdvicePaperRef']??''),'downloadUrl'=>str_starts_with($file,'receipt-')?'/api/accounts_receipt_file.php?file='.rawurlencode($file):'','foreignAmount'=>(float)($r['foreignAmount']??0),'currency'=>(string)($r['transactionCurrency']??''),'pkrCredit'=>(float)($r['pkrBankCredit']??0),'deductions'=>$ded];}$rows[]=['shipmentId'=>(string)($s['id']??$lot),'contractRef'=>$ref,'lotRef'=>$lot,'date'=>$date,'customer'=>$customer,'commercialInvoice'=>$invoice,'customsInvoice'=>(string)($customs['invoiceNo']??''),'gdRefs'=>$gds,'blNo'=>$bl,'documents'=>$rowDocs,'advices'=>$adv];}
 usort($rows,static fn($a,$b)=>strcmp((string)$b['date'],(string)$a['date'])?:strcmp((string)$b['commercialInvoice'],(string)$a['commercialInvoice']));ast_out(['ok'=>true,'entity'=>$entity,'rows'=>$rows,'filters'=>['from'=>$from,'to'=>$to,'q'=>$needle],'serverNow'=>gmdate('c')]);
}catch(Throwable $e){error_log('Accounts Sales Tax: '.$e->getMessage());ast_out(['ok'=>false,'error'=>'Sales Tax documents are temporarily unavailable.'],500);}
