<?php
declare(strict_types=1);
require dirname(__DIR__).'/auth_store.php';require_once __DIR__.'/accounts_subaccounts_core.php';
header('Content-Type: application/json; charset=UTF-8');header('Cache-Control: no-store');
function sac_out(array $v,int $status=200):never {http_response_code($status);echo json_encode($v,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);exit;}
try{
 $u=tt_require_login();$write=$_SERVER['REQUEST_METHOD']==='POST';if(!$write&&$_SERVER['REQUEST_METHOD']!=='GET')sac_out(['ok'=>false,'error'=>'Method not allowed.'],405);$b=$write?json_decode(file_get_contents('php://input')?:'{}',true,512,JSON_THROW_ON_ERROR):[];$e=strtoupper((string)($b['entity']??$_GET['entity']??''));
 if(!in_array($e,['TTI','BRM','TG'],true)||!tt_user_can_access_entity($u,$e,'View')||!(sac_permission($u,'reports','View')||sac_permission($u,'masters','View')||sac_permission($u,'cashbank','View')||sac_permission($u,'expenses','View')))sac_out(['ok'=>false,'error'=>'Company and Accounts view permission required.'],403);
 if($write){if(!tt_verify_csrf((string)($b['csrf']??'')))sac_out(['ok'=>false,'error'=>'Session expired.'],419);$right=($b['operation']??'add')==='delete'?'Delete':(($b['operation']??'add')==='edit'?'Edit':'Create');if(!sac_permission($u,'masters',$right)||!tt_user_can_access_entity($u,$e,$right))sac_out(['ok'=>false,'error'=>'Accounts Masters '.$right.' permission required.'],403);}
 tt_ensure_data_dir();$h=fopen(TT_DATA_DIR.'/accounts.json','c+');if(!$h||!flock($h,$write?LOCK_EX:LOCK_SH))throw new RuntimeException('Accounts storage unavailable.');try{$raw=stream_get_contents($h);$s=$raw!==''?json_decode($raw,true,512,JSON_THROW_ON_ERROR):[];if(!is_array($s))throw new RuntimeException('Invalid Accounts storage.');$result=[];
 if($write){$key=(string)($b['requestKey']??'');if(!preg_match('/^[A-Za-z0-9._:-]{8,128}$/',$key))throw new DomainException('Reopen the form before saving.');$identity=$e.'|'.($u['id']??0).'|'.$key;$fp=hash('sha256',json_encode($b,JSON_THROW_ON_ERROR));$saved=$s['subaccountRequests'][$identity]??null;if($saved){if($saved['fingerprint']!==$fp)sac_out(['ok'=>false,'error'=>'Request key already used.'],409);$result=$saved['result'];}else{if((int)($b['revision']??-1)!==(int)($s['revision']??0))sac_out(['ok'=>false,'error'=>'Accounts changed. Reopen Subaccounts before saving.'],409);$result=sac_master($s,$e,$b,$u);$s['subaccountRequests'][$identity]=['fingerprint'=>$fp,'result'=>$result];$s['revision']=(int)($s['revision']??0)+1;$encoded=json_encode($s,JSON_THROW_ON_ERROR);rewind($h);if(!ftruncate($h,0)||fwrite($h,$encoded)!==strlen($encoded)||!fflush($h))throw new RuntimeException('Save failed.');}}
 $from=isset($_GET['from'])?far_date($_GET['from'],'From date'):'';$to=isset($_GET['to'])?far_date($_GET['to'],'To date'):'';if($from!==''&&$to!==''&&$from>$to)throw new DomainException('From date cannot be after To date.');$out=sac_payload($s,$e,$from,$to)+['result'=>$result];foreach(['Create','Edit','Delete'] as $right)$out['can'.$right]=sac_permission($u,'masters',$right)&&tt_user_can_access_entity($u,$e,$right);
 }finally{flock($h,LOCK_UN);fclose($h);}sac_out($out);
}catch(DomainException $x){sac_out(['ok'=>false,'error'=>$x->getMessage()],422);}catch(Throwable $x){error_log('Subaccounts: '.$x->getMessage());sac_out(['ok'=>false,'error'=>'Subaccounts could not be loaded or saved.'],500);}
