<?php
declare(strict_types=1);
require dirname(__DIR__).'/auth_store.php';
const TT_RECEIPT_UPLOAD_DIR=TT_DATA_DIR.'/accounts-receipt-uploads';
function arf_out(array $d,int $s=200):never{http_response_code($s);header('Content-Type: application/json; charset=UTF-8');header('Cache-Control: no-store');echo json_encode($d,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
try{
 $u=tt_require_login();if(!tt_user_can_open_module($u,'Accounts'))arf_out(['ok'=>false,'error'=>'Accounts permission required.'],403);
 $entity=strtoupper(trim((string)($_SERVER['REQUEST_METHOD']==='GET'?$_GET['entity']??'':$_POST['entity']??'')));if(!in_array($entity,['TTI','BRM'],true))arf_out(['ok'=>false,'error'=>'Select TTI or BRM for this credit advice.'],422);
 if($_SERVER['REQUEST_METHOD']==='GET'){$token=preg_replace('/[^A-Za-z0-9._-]/','',(string)($_GET['file']??''));if($token===''||!str_starts_with($token,'receipt-'))arf_out(['ok'=>false,'error'=>'File reference required.'],422);if(preg_match('/^receipt-(TTI|BRM)-/',$token,$match)&&$match[1]!==$entity)arf_out(['ok'=>false,'error'=>'Credit advice belongs to another company.'],403);$path=TT_RECEIPT_UPLOAD_DIR.'/'.$token;if(!is_file($path)){http_response_code(404);exit('File not found.');}$ext=strtolower(pathinfo($path,PATHINFO_EXTENSION));$types=['pdf'=>'application/pdf','jpg'=>'image/jpeg','jpeg'=>'image/jpeg','png'=>'image/png','webp'=>'image/webp'];header('Content-Type: '.($types[$ext]??'application/octet-stream'));header('Content-Disposition: inline; filename="'.basename($path).'"');header('Content-Length: '.filesize($path));header('X-Content-Type-Options: nosniff');readfile($path);exit;}
 if($_SERVER['REQUEST_METHOD']!=='POST')arf_out(['ok'=>false,'error'=>'Method not allowed.'],405);if(!tt_verify_csrf((string)($_POST['csrf']??'')))arf_out(['ok'=>false,'error'=>'Your session expired. Refresh and try again.'],419);if(!isset($_FILES['adviceFile'])||!is_array($_FILES['adviceFile']))arf_out(['ok'=>false,'error'=>'Select the bank credit advice.'],422);$f=$_FILES['adviceFile'];if((int)($f['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)arf_out(['ok'=>false,'error'=>'Credit advice upload failed.'],422);$size=(int)($f['size']??0);if($size<=0||$size>15*1024*1024)arf_out(['ok'=>false,'error'=>'Credit advice must be smaller than 15 MB.'],422);$mime=(new finfo(FILEINFO_MIME_TYPE))->file((string)$f['tmp_name']);$ext=['application/pdf'=>'pdf','image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'][$mime]??'';if($ext==='')arf_out(['ok'=>false,'error'=>'Upload PDF, JPG, PNG or WebP only.'],415);if(!is_dir(TT_RECEIPT_UPLOAD_DIR)&&!mkdir(TT_RECEIPT_UPLOAD_DIR,0770,true)&&!is_dir(TT_RECEIPT_UPLOAD_DIR))throw new RuntimeException('Upload storage unavailable.');$token='receipt-'.$entity.'-'.gmdate('YmdHis').'-'.bin2hex(random_bytes(8)).'.'.$ext;if(!move_uploaded_file((string)$f['tmp_name'],TT_RECEIPT_UPLOAD_DIR.'/'.$token))throw new RuntimeException('Could not save credit advice.');arf_out(['ok'=>true,'token'=>$token,'originalName'=>substr((string)($f['name']??'credit-advice'),0,255),'size'=>$size,'downloadUrl'=>'/api/accounts_receipt_file.php?entity='.rawurlencode($entity).'&file='.rawurlencode($token)]);
}catch(Throwable $e){error_log('Accounts receipt file: '.$e->getMessage());arf_out(['ok'=>false,'error'=>'The credit advice file could not be saved.'],500);}
