<?php
declare(strict_types=1);
require dirname(__DIR__).'/auth_store.php';
header('Content-Type: application/json; charset=UTF-8');
header('Cache-Control: no-store, no-cache, must-revalidate');
const TT_BAG_FILE=TT_DATA_DIR.'/accounts.json';
const TT_BAG_MASTER=__DIR__.'/../accounts/accounting_master_v1.json';
function out(array $d,int $s=200):never{http_response_code($s);echo json_encode($d,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function def():array{return ['revision'=>0,'journals'=>[],'bagPurchaseOrders'=>[],'bagSupplierBills'=>[],'bagTaxRates'=>[['effectiveDate'=>'2026-07-01','rate'=>18.0,'note'=>'Initial configurable GST rate for eligible export bags.']],'bagExportUsage'=>[]];}
function readStore():array{tt_ensure_data_dir();if(!is_file(TT_BAG_FILE))return def();$h=fopen(TT_BAG_FILE,'r');if($h===false||!flock($h,LOCK_SH))throw new RuntimeException('Accounts storage unavailable.');try{$raw=stream_get_contents($h);}finally{flock($h,LOCK_UN);fclose($h);}$v=$raw?json_decode($raw,true):null;return is_array($v)?array_replace_recursive(def(),$v):def();}
function canAcc(array $u):bool{if(($u['role']??'')==='Super Admin')return true;$p=$u['permissions']['Accounts']??null;if($p==='all')return true;if(!is_array($p))return false;if(in_array('Create',$p,true)||in_array('Edit',$p,true)||in_array('Approve',$p,true))return true;foreach($p as $a)if(is_array($a)&&(in_array('Create',$a,true)||in_array('Edit',$a,true)||in_array('Approve',$a,true)))return true;return false;}
function canApprove(array $u):bool{return ($u['role']??'')==='Super Admin'||stripos((string)($u['role']??''),'director')!==false;}
function ent(string $v):string{$v=strtoupper(trim($v));if(!in_array($v,['TTI','BRM'],true))out(['ok'=>false,'error'=>'Bag purchases are available for TTI or BRM books.'],422);return $v;}
function datev(string $v,string $n='date'):string{if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$v))out(['ok'=>false,'error'=>'Valid '.$n.' required.'],422);return $v;}
function defaultSalesTaxInvoice(string $t):bool{$u=strtoupper(trim($t));return str_contains($u,'PP')||str_contains($u,'BOPP')||str_contains($u,'LAMINAT');}
function taxRate(array $s,string $d):float{$r=null;$a=(array)$s['bagTaxRates'];usort($a,static fn($x,$y)=>strcmp((string)($x['effectiveDate']??''),(string)($y['effectiveDate']??'')));foreach($a as $x)if(is_array($x)&&($x['effectiveDate']??'')<=$d)$r=(float)($x['rate']??0);if($r===null)out(['ok'=>false,'error'=>'No bag GST rate is configured for this invoice date.'],422);return round($r,4);}
function names():array{$raw=file_get_contents(TT_BAG_MASTER);$m=$raw?json_decode($raw,true):null;if(!is_array($m))throw new RuntimeException('Accounting master unavailable.');$o=[];foreach((array)$m['chart'] as $a)if(is_array($a)&&isset($a['code']))$o[(string)$a['code']]=(string)($a['name']??$a['code']);return $o;}
function line(string $a,float $dr,float $cr,array $n,array $x=[]):array{if(!isset($n[$a]))out(['ok'=>false,'error'=>'Required account '.$a.' is not configured.'],422);return array_merge(['account'=>$a,'accountName'=>$n[$a],'debit'=>round($dr,2),'credit'=>round($cr,2)],$x);}
function nextId(array $a,string $p):string{$n=count($a)+1;do{$id=$p.'-'.gmdate('Y').'-'.str_pad((string)$n,6,'0',STR_PAD_LEFT);$n++;}while(isset($a[$id]));return $id;}
function billed(array $s,string $po,string $lk,string $exclude=''):int{$n=0;foreach((array)$s['bagSupplierBills'] as $id=>$b){if(!is_array($b)||$id===$exclude||($b['status']??'')==='Cancelled')continue;if(($b['poNo']??'')===$po&&($b['lineKey']??'')===$lk)$n+=(int)($b['bags']??0);}return $n;}
function findLine(array $po,string $lk):?array{foreach((array)($po['lines']??[]) as $l)if(is_array($l)&&($l['lineKey']??'')===$lk)return $l;return null;}
function postBill(array &$s,array $u,string $id):array{$b=$s['bagSupplierBills'][$id]??null;if(!is_array($b))out(['ok'=>false,'error'=>'Bag bill not found.'],404);if(!empty($b['journalId']))return $b;$po=$s['bagPurchaseOrders'][$b['poNo']]??null;$l=is_array($po)?findLine($po,(string)$b['lineKey']):null;if(!$l)out(['ok'=>false,'error'=>'Linked PO packing line is unavailable.'],409);$before=billed($s,(string)$b['poNo'],(string)$b['lineKey'],$id);if($before+(int)$b['bags']>(int)$l['orderedQty'])out(['ok'=>false,'error'=>'Posting blocked: billed bags exceed the PO quantity for this packing size.'],409);if($before+(int)$b['bags']>(int)($l['receivedQty']??0))out(['ok'=>false,'error'=>'Posting held: supplier invoice quantity is above bags received at Mill.'],409);$poRate=(float)($l['ratePerBag']??0);if($poRate>0&&abs((float)$b['ratePerBag']-$poRate)>.0001&&empty($b['rateExceptionApprovedAt']))out(['ok'=>false,'error'=>'Posting held: invoice rate differs from PO rate and needs Director approval.'],409);$hasTax=array_key_exists('salesTaxInvoice',$b)?!empty($b['salesTaxInvoice']):(float)($b['gstAmount']??0)>0;$n=names();$jl=[line('1340',(float)$b['baseAmount'],0,$n,['poNo'=>$b['poNo'],'lineKey'=>$b['lineKey'],'packingSize'=>$b['packingSize']])];if($hasTax&&(float)$b['gstAmount']>0)$jl[]=line('1230',(float)$b['gstAmount'],0,$n,['subledger'=>'Sales Tax Recoverable / Refund Receivable','sellerInvoice'=>$b['sellerInvoice'],'gstRate'=>$b['gstRate']]);$jl[]=line('2140',0,(float)$b['totalAmount'],$n,['subledger'=>'Packaging Supplier Payable','supplier'=>$b['supplier']]);$jid=nextId((array)$s['journals'],'AUTO');$s['journals'][$jid]=['id'=>$jid,'entity'=>$b['entity'],'date'=>$b['sellerInvoiceDate'],'sourceType'=>'EXPORT_BAG_SUPPLIER_BILL','reference'=>$b['sellerInvoice'],'narration'=>'Export bag purchase — '.$b['supplier'].' — PO '.$b['poNo'].' — '.$b['packingSize'],'lines'=>$jl,'totalDebit'=>round((float)$b['totalAmount'],2),'totalCredit'=>round((float)$b['totalAmount'],2),'status'=>'Posted','meta'=>['bagBillId'=>$id,'poNo'=>$b['poNo'],'lineKey'=>$b['lineKey'],'bags'=>$b['bags'],'bagType'=>$b['bagType'],'packingSize'=>$b['packingSize'],'brand'=>$b['brand'],'salesTaxInvoice'=>$hasTax,'salesTaxRecoverable'=>$hasTax],'createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??$u['username']??'Accounts')];$s['bagSupplierBills'][$id]['journalId']=$jid;$s['bagSupplierBills'][$id]['status']='Posted';$s['bagSupplierBills'][$id]['postedAt']=gmdate('c');return $s['bagSupplierBills'][$id];}
function overview(array $s,string $e,string $from='',string $to=''):array{$pos=[];foreach((array)$s['bagPurchaseOrders'] as $po){if(!is_array($po)||($po['entity']??'TTI')!==$e)continue;$x=$po;foreach($x['lines'] as &$l){$l['billedQty']=billed($s,(string)$po['poNo'],(string)$l['lineKey']);$l['remainingToBill']=max(0,(int)$l['orderedQty']-(int)$l['billedQty']);$l['receivedNotBilled']=max(0,(int)($l['receivedQty']??0)-(int)$l['billedQty']);}unset($l);$pos[]=$x;}$bills=[];$exports=[];$t=['inputBags'=>0,'baseAmount'=>0.0,'gstAmount'=>0.0,'supplierTotal'=>0.0,'exportedBags'=>0];foreach((array)$s['bagSupplierBills'] as $b){if(!is_array($b)||($b['entity']??'')!==$e)continue;$d=(string)$b['sellerInvoiceDate'];if(($from&&$d<$from)||($to&&$d>$to))continue;$bills[]=$b;$t['inputBags']+=(int)$b['bags'];$t['baseAmount']+=(float)$b['baseAmount'];$t['gstAmount']+=(float)$b['gstAmount'];$t['supplierTotal']+=(float)$b['totalAmount'];}foreach((array)$s['bagExportUsage'] as $r){if(!is_array($r)||($r['entity']??'')!==$e)continue;$d=(string)$r['invoiceDate'];if(($from&&$d<$from)||($to&&$d>$to))continue;$exports[]=$r;$t['exportedBags']+=(int)$r['bags'];}foreach(['baseAmount','gstAmount','supplierTotal'] as $k)$t[$k]=round($t[$k],2);usort($bills,static fn($a,$b)=>strcmp($b['sellerInvoiceDate'],$a['sellerInvoiceDate']));usort($exports,static fn($a,$b)=>strcmp($b['invoiceDate'],$a['invoiceDate']));return ['ok'=>true,'entity'=>$e,'purchaseOrders'=>$pos,'bills'=>$bills,'exportUsage'=>$exports,'totals'=>$t,'taxRates'=>$s['bagTaxRates'],'serverNow'=>gmdate('c')];}
try{$u=tt_require_login();$ca=tt_user_can_open_module($u,'Accounts');$ce=tt_user_can_open_module($u,'Exports');$cm=tt_user_can_open_module($u,'Mill');if(!$ca&&!$ce&&!$cm)out(['ok'=>false,'error'=>'Bag-control access required.'],403);if($_SERVER['REQUEST_METHOD']==='GET'){$e=ent((string)($_GET['entity']??'TTI'));$f=trim((string)($_GET['from']??''));$t=trim((string)($_GET['to']??''));if($f)datev($f,'from date');if($t)datev($t,'to date');out(overview(readStore(),$e,$f,$t));}if($_SERVER['REQUEST_METHOD']!=='POST')out(['ok'=>false,'error'=>'Method not allowed.'],405);$b=json_decode(file_get_contents('php://input')?:'{}',true);if(!is_array($b)||!tt_verify_csrf((string)($b['csrf']??'')))out(['ok'=>false,'error'=>'Your session expired. Refresh and try again.'],419);$a=(string)($b['action']??'');tt_ensure_data_dir();$h=fopen(TT_BAG_FILE,'c+');if($h===false||!flock($h,LOCK_EX))throw new RuntimeException('Accounts storage unavailable.');try{rewind($h);$raw=stream_get_contents($h);$s=$raw?json_decode($raw,true):null;if(!is_array($s))$s=def();$s=array_replace_recursive(def(),$s);
if($a==='sync_po'){$e=ent((string)($b['entity']??'TTI'));$po=trim((string)($b['poNo']??''));if(!$po)out(['ok'=>false,'error'=>'PO number required.'],422);$ls=[];foreach((array)($b['lines']??[]) as $i=>$x){if(!is_array($x)||(float)($x['orderedQty']??0)<=0)continue;$lk=trim((string)($x['lineKey']??''))?:'L'.($i+1);$old=findLine((array)($s['bagPurchaseOrders'][$po]??[]),$lk);$bagType=trim((string)($x['bagType']??''));$defaultTax=defaultSalesTaxInvoice($bagType);$ls[]=['lineKey'=>$lk,'bagType'=>$bagType,'packingSize'=>trim((string)($x['packingSize']??'')),'brand'=>trim((string)($x['brand']??'')),'orderedQty'=>(int)round((float)$x['orderedQty']),'ratePerBag'=>round((float)($x['ratePerBag']??0),4),'receivedQty'=>(int)($old['receivedQty']??0),'salesTaxInvoiceDefault'=>$defaultTax,'eligibleForSalesTaxRefund'=>$defaultTax];}$s['bagPurchaseOrders'][$po]=['poNo'=>$po,'entity'=>$e,'supplier'=>trim((string)($b['supplier']??'')),'shipmentRef'=>trim((string)($b['shipmentRef']??'')),'contractRef'=>trim((string)($b['contractRef']??'')),'issuedAt'=>trim((string)($b['issuedAt']??'')),'lines'=>$ls,'updatedAt'=>gmdate('c'),'source'=>'Exports'];$result=$s['bagPurchaseOrders'][$po];}
elseif($a==='sync_receipt_snapshot'){$po=trim((string)($b['poNo']??''));$lk=trim((string)($b['lineKey']??''));if(!isset($s['bagPurchaseOrders'][$po]))out(['ok'=>false,'error'=>'PO not found for Mill receipt sync.'],404);$ok=false;foreach($s['bagPurchaseOrders'][$po]['lines'] as &$l)if(($l['lineKey']??'')===$lk){$l['receivedQty']=max(0,(int)round((float)($b['receivedQty']??0)));$l['lastMillReceiptSyncAt']=gmdate('c');$ok=true;break;}unset($l);if(!$ok)out(['ok'=>false,'error'=>'PO packing line not found for Mill receipt sync.'],404);$result=['poNo'=>$po,'lineKey'=>$lk];}
elseif($a==='sync_export_usage'){$e=ent((string)($b['entity']??'TTI'));$k=trim((string)($b['usageKey']??''));if(!$k)out(['ok'=>false,'error'=>'Export usage key required.'],422);$s['bagExportUsage'][$k]=['usageKey'=>$k,'entity'=>$e,'invoiceDate'=>datev((string)($b['invoiceDate']??''),'commercial invoice date'),'shipmentRef'=>trim((string)($b['shipmentRef']??'')),'contractRef'=>trim((string)($b['contractRef']??'')),'commercialInvoice'=>trim((string)($b['commercialInvoice']??'')),'bags'=>max(0,(int)round((float)($b['bags']??0))),'gdRefs'=>array_values(array_filter(array_map('strval',(array)($b['gdRefs']??[])))),'blNo'=>trim((string)($b['blNo']??'')),'blFile'=>trim((string)($b['blFile']??'')),'updatedAt'=>gmdate('c')];$result=$s['bagExportUsage'][$k];}
elseif($a==='save_tax_rate'){if(!$ca||!canAcc($u))out(['ok'=>false,'error'=>'Accounts permission required.'],403);$d=datev((string)($b['effectiveDate']??''),'effective date');$r=round((float)($b['rate']??0),4);if($r<0||$r>100)out(['ok'=>false,'error'=>'Enter a valid GST percentage.'],422);$found=false;foreach($s['bagTaxRates'] as &$x)if(($x['effectiveDate']??'')===$d){$x=['effectiveDate'=>$d,'rate'=>$r,'note'=>trim((string)($b['note']??'')),'updatedAt'=>gmdate('c'),'updatedBy'=>(string)($u['full_name']??$u['username']??'Accounts')];$found=true;break;}unset($x);if(!$found)$s['bagTaxRates'][]=['effectiveDate'=>$d,'rate'=>$r,'note'=>trim((string)($b['note']??'')),'updatedAt'=>gmdate('c'),'updatedBy'=>(string)($u['full_name']??$u['username']??'Accounts')];$result=$s['bagTaxRates'];}
elseif($a==='create_bill'){if(!$ca||!canAcc($u))out(['ok'=>false,'error'=>'Accounts permission required.'],403);$e=ent((string)($b['entity']??''));$poNo=trim((string)($b['poNo']??''));$lk=trim((string)($b['lineKey']??''));$po=$s['bagPurchaseOrders'][$poNo]??null;$l=is_array($po)?findLine($po,$lk):null;if(!$l||($po['entity']??'')!==$e)out(['ok'=>false,'error'=>'Select a valid PO packing line.'],422);$sup=trim((string)($b['supplier']??$po['supplier']??''));$inv=trim((string)($b['sellerInvoice']??''));$dt=datev((string)($b['sellerInvoiceDate']??''),'seller invoice date');$qty=(int)round((float)($b['bags']??0));$rate=round((float)($b['ratePerBag']??0),4);if(!$sup||!$inv||$qty<=0||$rate<=0)out(['ok'=>false,'error'=>'Supplier, seller invoice, number of bags and rate are required.'],422);foreach((array)$s['bagSupplierBills'] as $o)if(is_array($o)&&($o['entity']??'')===$e&&strcasecmp((string)$o['supplier'],$sup)===0&&strcasecmp((string)$o['sellerInvoice'],$inv)===0)out(['ok'=>false,'error'=>'This supplier invoice is already entered.'],409);$already=billed($s,$poNo,$lk);if($already+$qty>(int)$l['orderedQty'])out(['ok'=>false,'error'=>'Bill rejected: cumulative billed bags exceed the PO quantity. Remaining: '.max(0,(int)$l['orderedQty']-$already).' bags.'],409);$salesTaxInvoice=filter_var($b['salesTaxInvoice']??false,FILTER_VALIDATE_BOOLEAN);$gst=$salesTaxInvoice?taxRate($s,$dt):0.0;$base=round($qty*$rate,2);$tax=$salesTaxInvoice?round($base*$gst/100,2):0.0;$tot=round($base+$tax,2);$id=nextId((array)$s['bagSupplierBills'],'BAGB');$status=$already+$qty>(int)($l['receivedQty']??0)?'Hold - Billed Above Received':(((float)$l['ratePerBag']>0&&abs($rate-(float)$l['ratePerBag'])>.0001)?'Hold - Rate Approval Required':'Ready to Post');$s['bagSupplierBills'][$id]=['id'=>$id,'entity'=>$e,'poNo'=>$poNo,'lineKey'=>$lk,'supplier'=>$sup,'sellerInvoice'=>$inv,'sellerInvoiceDate'=>$dt,'bagType'=>$l['bagType'],'packingSize'=>$l['packingSize'],'brand'=>$l['brand'],'bags'=>$qty,'ratePerBag'=>$rate,'poRatePerBag'=>$l['ratePerBag'],'salesTaxInvoice'=>$salesTaxInvoice,'baseAmount'=>$base,'gstRate'=>$gst,'gstAmount'=>$tax,'totalAmount'=>$tot,'attachmentToken'=>trim((string)($b['attachmentToken']??'')),'status'=>$status,'journalId'=>null,'rateExceptionApprovedAt'=>null,'createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??$u['username']??'Accounts')];if($status==='Ready to Post')$s['bagSupplierBills'][$id]=postBill($s,$u,$id);$result=$s['bagSupplierBills'][$id];}
elseif($a==='approve_rate_exception'){if(!canApprove($u))out(['ok'=>false,'error'=>'Director approval is required.'],403);$id=trim((string)($b['billId']??''));if(!isset($s['bagSupplierBills'][$id]))out(['ok'=>false,'error'=>'Bag bill not found.'],404);$s['bagSupplierBills'][$id]['rateExceptionApprovedAt']=gmdate('c');$s['bagSupplierBills'][$id]['rateExceptionApprovedBy']=(string)($u['full_name']??$u['username']??'Director');$s['bagSupplierBills'][$id]['rateExceptionReason']=trim((string)($b['reason']??''));$bb=$s['bagSupplierBills'][$id];$po=$s['bagPurchaseOrders'][$bb['poNo']]??[];$l=findLine((array)$po,(string)$bb['lineKey']);$before=billed($s,(string)$bb['poNo'],(string)$bb['lineKey'],$id);if($l&&$before+(int)$bb['bags']<=(int)($l['receivedQty']??0))$s['bagSupplierBills'][$id]=postBill($s,$u,$id);else $s['bagSupplierBills'][$id]['status']='Hold - Billed Above Received';$result=$s['bagSupplierBills'][$id];}
elseif($a==='try_post_bill'){if(!$ca||!canAcc($u))out(['ok'=>false,'error'=>'Accounts permission required.'],403);$result=postBill($s,$u,trim((string)($b['billId']??'')));}
else out(['ok'=>false,'error'=>'Unknown bag-purchase action.'],422);$s['revision']=(int)($s['revision']??0)+1;rewind($h);ftruncate($h,0);fwrite($h,json_encode($s,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($h);}finally{flock($h,LOCK_UN);fclose($h);}out(['ok'=>true,'result'=>$result,'revision'=>$s['revision']]);}catch(Throwable $e){out(['ok'=>false,'error'=>'The export-bag purchase action could not be completed.'],500);}
