<?php
declare(strict_types=1);
require dirname(__DIR__) . '/auth_store.php';
header('Content-Type: application/json; charset=UTF-8');
header('Cache-Control: no-store, no-cache, must-revalidate');
const TT_BR_FILE=TT_DATA_DIR.'/accounts.json';
function br_out(array $d,int $s=200):never{http_response_code($s);echo json_encode($d,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function br_can_write(array $u):bool{if(($u['role']??'')==='Super Admin')return true;$p=$u['permissions']['Accounts']??null;if($p==='all')return true;if(!is_array($p))return false;if(in_array('Create',$p,true)||in_array('Edit',$p,true)||in_array('Approve',$p,true))return true;foreach($p as $a)if(is_array($a)&&(in_array('Create',$a,true)||in_array('Edit',$a,true)||in_array('Approve',$a,true)))return true;return false;}
function br_entity(string $v):string{$v=strtoupper(trim($v));if(!in_array($v,['TTI','BRM','TG'],true))br_out(['ok'=>false,'error'=>'Select valid company books.'],422);return $v;}
function br_date(string $v):string{if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$v))br_out(['ok'=>false,'error'=>'Valid statement date required.'],422);return $v;}
function br_def():array{return ['revision'=>0,'journals'=>[],'bankAccountSettings'=>[],'bankReconciliations'=>[]];}
function br_read():array{tt_ensure_data_dir();if(!is_file(TT_BR_FILE))return br_def();$h=fopen(TT_BR_FILE,'r');if($h===false||!flock($h,LOCK_SH))throw new RuntimeException('Accounts storage unavailable.');try{$raw=stream_get_contents($h);}finally{flock($h,LOCK_UN);fclose($h);}$s=$raw?json_decode($raw,true):null;return is_array($s)?array_replace_recursive(br_def(),$s):br_def();}
function br_entity_from_linked(string $v):string{$u=strtoupper($v);if(str_contains($u,'BRM')||str_contains($u,'BUKSH RICE'))return 'BRM';if(str_contains($u,'TG')||str_contains($u,'TRANS GRAINS'))return 'TG';if(str_contains($u,'TTI')||str_contains($u,'TRANSTRADE INTERNATIONAL'))return 'TTI';return '';}
function br_banks(array $s,string $entity):array{$m=tt_list_masters();$out=[];foreach((array)($m['banks']??[]) as $r){if(!is_array($r))continue;$v=array_values((array)($r['values']??[]));while(count($v)<14)$v[]='';$id=(string)($r['id']??'');if(br_entity_from_linked((string)$v[1])!==$entity||trim((string)$v[0])!=='Company Account')continue;$set=is_array($s['bankAccountSettings'][$id]??null)?$s['bankAccountSettings'][$id]:[];if(array_key_exists('reconciliationEnabled',$set)&&empty($set['reconciliationEnabled']))continue;$raw=preg_replace('/\W+/','',trim((string)($v[8]?:$v[9])))??'';$tail=$raw!==''?substr($raw,-5):'';$out[]=['id'=>$id,'bankName'=>(string)$v[4],'accountTitle'=>(string)$v[3],'currency'=>strtoupper(trim((string)$v[7]))?:($entity==='TG'?'USD':'PKR'),'display'=>trim((string)$v[4]).($tail!==''?' — •••'.$tail:'')];}usort($out,static fn($a,$b)=>strcmp($a['bankName'],$b['bankName'])?:strcmp($a['accountTitle'],$b['accountTitle']));return $out;}
function br_txns(array $s,string $entity,string $bankId,string $toDate):array{$rows=[];$book=0.0;foreach((array)($s['journals']??[]) as $jid=>$j){if(!is_array($j)||($j['status']??'')!=='Posted'||($j['entity']??'')!==$entity)continue;$date=(string)($j['date']??'');if($date===''||$date>$toDate)continue;$jm=is_array($j['meta']??null)?$j['meta']:[];foreach((array)($j['lines']??[]) as $i=>$l){if(!is_array($l)||(string)($l['account']??'')!=='1110')continue;$lineBank=(string)($l['bankAccountId']??$jm['bankAccountId']??'');if($lineBank!==$bankId)continue;$dr=(float)($l['debit']??0);$cr=(float)($l['credit']??0);$bankDr=(float)($l['bankDebit']??0);$bankCr=(float)($l['bankCredit']??0);$amt=($bankDr!=0||$bankCr!=0)?$bankDr-$bankCr:$dr-$cr;$book+=$amt;$key=(string)$jid.'|'.$i;$rows[]=['key'=>$key,'date'=>$date,'journalId'=>(string)$jid,'reference'=>(string)($j['reference']??''),'narration'=>(string)($j['narration']??''),'debit'=>round(max(0,$amt),2),'credit'=>round(max(0,-$amt),2),'net'=>round($amt,2)];}}usort($rows,static fn($a,$b)=>strcmp($a['date'],$b['date'])?:strcmp($a['journalId'],$b['journalId']));return ['rows'=>$rows,'bookBalance'=>round($book,2)];}
function br_payload(array $s,string $entity,string $bankId,string $date):array{$banks=br_banks($s,$entity);$bank=null;foreach($banks as $b)if($b['id']===$bankId){$bank=$b;break;}$tx=$bankId!==''?br_txns($s,$entity,$bankId,$date):['rows'=>[],'bookBalance'=>0];$key=$entity.'|'.$bankId;$rec=is_array($s['bankReconciliations'][$key]??null)?$s['bankReconciliations'][$key]:[];$cleared=array_values(array_filter((array)($rec['clearedKeys']??[]),'is_string'));$rows=array_map(static function($r)use($cleared){$r['cleared']=in_array($r['key'],$cleared,true);return $r;},$tx['rows']);return ['ok'=>true,'entity'=>$entity,'banks'=>$banks,'bank'=>$bank,'statementDate'=>$date,'bookBalance'=>$tx['bookBalance'],'statementBalance'=>isset($rec['statementBalance'])?(float)$rec['statementBalance']:null,'difference'=>isset($rec['statementBalance'])?round((float)$rec['statementBalance']-(float)$tx['bookBalance'],2):null,'transactions'=>$rows,'reconciliation'=>$rec,'serverNow'=>gmdate('c')];}
try{$u=tt_require_login();if(!tt_user_can_open_module($u,'Accounts'))br_out(['ok'=>false,'error'=>'Accounts permission required.'],403);$entity=br_entity((string)($_GET['entity']??$_POST['entity']??'TTI'));$today=(new DateTimeImmutable('now',new DateTimeZone('Asia/Karachi')))->format('Y-m-d');if($_SERVER['REQUEST_METHOD']==='GET'){$date=br_date((string)($_GET['statementDate']??$today));$bankId=trim((string)($_GET['bankId']??''));br_out(br_payload(br_read(),$entity,$bankId,$date));}if($_SERVER['REQUEST_METHOD']!=='POST')br_out(['ok'=>false,'error'=>'Method not allowed.'],405);if(!br_can_write($u))br_out(['ok'=>false,'error'=>'Accounts Create / Edit / Approve permission required.'],403);$b=json_decode(file_get_contents('php://input')?:'{}',true);if(!is_array($b)||!tt_verify_csrf((string)($b['csrf']??'')))br_out(['ok'=>false,'error'=>'Your session expired. Refresh and try again.'],419);$entity=br_entity((string)($b['entity']??''));$date=br_date((string)($b['statementDate']??''));$bankId=trim((string)($b['bankId']??''));if($bankId==='')br_out(['ok'=>false,'error'=>'Select a bank account.'],422);$statement=round((float)($b['statementBalance']??0),2);$cleared=array_values(array_unique(array_filter(array_map('strval',(array)($b['clearedKeys']??[])))));$current=br_read();$valid=array_column(br_banks($current,$entity),'id');if(!in_array($bankId,$valid,true))br_out(['ok'=>false,'error'=>'Selected bank is not enabled for reconciliation in these books.'],422);$tx=br_txns($current,$entity,$bankId,$date);$validKeys=array_column($tx['rows'],'key');foreach($cleared as $k)if(!in_array($k,$validKeys,true))br_out(['ok'=>false,'error'=>'One selected transaction is not available for this bank statement. Refresh and try again.'],409);$difference=round($statement-$tx['bookBalance'],2);$status=abs($difference)<=0.005?'Reconciled':'Difference to Review';$rec=['entity'=>$entity,'bankId'=>$bankId,'statementDate'=>$date,'statementBalance'=>$statement,'bookBalance'=>$tx['bookBalance'],'difference'=>$difference,'clearedKeys'=>$cleared,'status'=>$status,'updatedAt'=>gmdate('c'),'updatedBy'=>(string)($u['full_name']??$u['username']??'Accounts')];tt_ensure_data_dir();$h=fopen(TT_BR_FILE,'c+');if($h===false||!flock($h,LOCK_EX))throw new RuntimeException('Accounts storage unavailable.');try{rewind($h);$raw=stream_get_contents($h);$s=$raw?json_decode($raw,true):null;if(!is_array($s))$s=br_def();$s=array_replace_recursive(br_def(),$s);$s['bankReconciliations'][$entity.'|'.$bankId]=$rec;$s['revision']=(int)($s['revision']??0)+1;rewind($h);ftruncate($h,0);fwrite($h,json_encode($s,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($h);}finally{flock($h,LOCK_UN);fclose($h);}br_out(br_payload($s,$entity,$bankId,$date)+['saved'=>$rec,'revision'=>$s['revision']]);}catch(Throwable $e){br_out(['ok'=>false,'error'=>'Bank reconciliation could not be completed.'],500);}
