<?php
declare(strict_types=1);
require_once __DIR__.'/accounts_subaccounts_core.php';require_once __DIR__.'/accounts_bank_payment.php';
function ben_banks(array $s,string $e):array {
 $out=[];foreach((array)(tt_list_masters()['banks']??[]) as $r){$v=array_values((array)($r['values']??[]));$link=strtoupper((string)($v[1]??''));$owner=preg_match('/(^|\W)TG($|\W)/',$link)||str_contains($link,'TRANS GRAINS')?'TG':(str_contains($link,'BUKSH')||preg_match('/(^|\W)BRM($|\W)/',$link)?'BRM':(str_contains($link,'TRANSTRADE INTERNATIONAL')||preg_match('/(^|\W)TTI($|\W)/',$link)?'TTI':''));$id=(string)($r['id']??'');if($owner!==$e||!in_array($v[0]??'',['Company Account','Proprietor / Owner Account','Personal Account'],true)||!tt_bank_can_transact($id))continue;$set=$s['bankAccountSettings'][$id]??[];$out[]=['id'=>$id,'label'=>implode(' · ',array_filter([$v[4]??'',($v[8]??'')?:($v[9]??''),$v[7]??'',$v[3]??''])),'bankName'=>(string)($v[4]??''),'accountNumber'=>(string)($v[8]??''),'iban'=>(string)($v[9]??''),'accountTitle'=>(string)($v[3]??''),'currency'=>strtoupper((string)($v[7]??'')),'depositType'=>$r['depositType']??'CURRENT','isDefault'=>!empty($set['defaultPaymentAccount'])?2:(!empty($set['defaultReceiptAccount'])?1:0)];}usort($out,static fn($a,$b)=>$b['isDefault']<=>$a['isDefault']);return $out;
}
function ben_line(string $code,int $dr,int $cr,array $extra=[]):array {$chart=sac_chart();if(!isset($chart[$code]))throw new RuntimeException('Required account '.$code.' is unavailable.');return ['account'=>$code,'accountName'=>$chart[$code]['name'],'debit'=>$dr/100,'credit'=>$cr/100]+$extra;}
function ben_bank(array $s,string $e,string $id):array {foreach(ben_banks($s,$e) as $a)if($a['id']===$id)return $a;throw new DomainException('Select an active bank belonging to these company books.');}
function ben_rate(array $bank,string $e,mixed $input):float {if($bank['currency']===($e==='TG'?'AED':'PKR'))return 1.0;if(!is_numeric($input)||!is_finite((float)$input)||(float)$input<=0||(float)$input>1000000)throw new DomainException('Enter the bank exchange rate into company books.');return (float)$input;}
function ben_bank_line(array $bank,int $native,float $rate,bool $incoming,array $extra=[]):array {return ben_line('1110',$incoming?(int)round($native*$rate):0,$incoming?0:(int)round($native*$rate),['bankAccountId'=>$bank['id'],'bankName'=>$bank['bankName'],'accountNumber'=>$bank['accountNumber'],'iban'=>$bank['iban'],'accountTitle'=>$bank['accountTitle'],'currency'=>$bank['currency'],'bankCurrency'=>$bank['currency'],'bankDebit'=>$incoming?$native/100:0,'bankCredit'=>$incoming?0:$native/100,'exchangeRate'=>$rate]+$extra);}
function ben_tracking(array $s,string $e,array $bank,array $b):array {
 $t=tt_accounts_bank_payment_details($b+['paymentAccountId'=>$bank['id']]);if(($t['bankPaymentMethod']??'')!=='CHEQUE')return $t;
 foreach((array)($s['journals']??[]) as $j)if(($j['entity']??'')===$e&&($j['status']??'')==='Posted'&&empty($j['reversalOf'])&&empty($j['reversedByPostId'])&&empty($j['amendedByPostId']))foreach((array)($j['lines']??[]) as $l)if(($l['account']??'')==='1110'&&($l['bankAccountId']??'')===$bank['id']&&($l['credit']??0)>0&&strcasecmp((string)($l['chequeNo']??$j['meta']['chequeNo']??''),$t['chequeNo'])===0)throw new DomainException('This bank cheque is already posted.');
 foreach((array)($s['issuedCheques']??[]) as $c)if(($c['entity']??'')===$e&&($c['bankAccountId']??$c['paymentAccountId']??'')===$bank['id']&&strcasecmp((string)($c['chequeNo']??''),$t['chequeNo'])===0&&!in_array($c['status']??'',['Cancelled','Voided','Reversed'],true))throw new DomainException('This cheque is already issued.');return $t;
}
function ben_journal(array &$s,string $e,string $date,string $ref,string $note,array $lines,array $u,array $meta,?string $reversal=null):array {
 $dr=(int)round(array_sum(array_column($lines,'debit'))*100);$cr=(int)round(array_sum(array_column($lines,'credit'))*100);if($dr!==$cr||$dr===0)throw new RuntimeException('Bank entry did not balance.');$id=tt_next_post_id((array)($s['journals']??[]),'Accounts','Journal',$date);$j=['id'=>$id,'entity'=>$e,'date'=>$date,'sourceType'=>$reversal?'BANK_ENTRY_REVERSAL':'BANK_ENTRY','reference'=>$ref,'narration'=>strtoupper($note),'lines'=>$lines,'totalDebit'=>$dr/100,'totalCredit'=>$cr/100,'status'=>'Posted','meta'=>$meta,'createdAt'=>gmdate('c'),'createdBy'=>$u['full_name']??$u['username']??'Accounts','userId'=>$u['id']??0,'reversalOf'=>$reversal];$s['journals'][$id]=$j;return $j;
}
function ben_facility_balance(array $s,string $e,string $id,string $to='9999-12-31'):array {
 $native=0;$book=0;foreach((array)($s['journals']??[]) as $j)if(($j['entity']??'')===$e&&($j['status']??'')==='Posted'&&($j['date']??'')<=$to)foreach((array)($j['lines']??[]) as $l)if(($l['account']??'')==='2610'&&($l['bankFacilityId']??'')===$id){$native+=(int)round(((float)($l['nativeCredit']??0)-(float)($l['nativeDebit']??0))*100);$book+=(int)round(((float)($l['credit']??0)-(float)($l['debit']??0))*100);}return ['nativeCents'=>$native,'bookCents'=>$book];
}
function ben_validate_finance(array $s,string $e):void {
 $rows=[];foreach((array)($s['journals']??[]) as $j)if(($j['entity']??'')===$e&&($j['status']??'')==='Posted')$rows[]=$j;usort($rows,static fn($a,$b)=>strcmp($a['date'],$b['date'])?:strcmp($a['id'],$b['id']));$balance=[];
 foreach($rows as $j)foreach((array)$j['lines'] as $l)if(($l['account']??'')==='2610'&&!empty($l['bankFacilityId'])){$id=$l['bankFacilityId'];$balance[$id]=($balance[$id]??0)+(int)round(((float)($l['nativeCredit']??0)-(float)($l['nativeDebit']??0))*100);if($balance[$id]<0)throw new DomainException('Finance repayment exceeds the drawn principal on that date.');}
}
function ben_facility(array &$s,string $e,array $b,array $u):array {
 $op=$b['operation']??'add';$id=(string)($b['id']??'');$old=$s['bankFacilities'][$id]??null;if($op!=='add'&&(!$old||$old['entity']!==$e))throw new DomainException('Facility not found in these books.');if(!in_array($op,['add','edit','delete'],true))throw new DomainException('Unknown facility action.');
 if($op==='delete'){$a=$old;$a['active']=false;}else{$name=far_text($b['name']??'',180);if($name==='')throw new DomainException('Enter the facility name.');$bank=ben_bank($s,$e,(string)($b['bankId']??''));if($old&&$old['bankId']!==$bank['id']){foreach((array)($s['journals']??[]) as $j)if(($j['meta']['bankFacilityId']??'')===$id)throw new DomainException('An existing facility bank is preserved. Create a separate facility for another bank.');}foreach((array)($s['bankFacilities']??[]) as $r)if($r['entity']===$e&&$r['id']!==$id&&sac_normal($r['name'])===sac_normal($name))throw new DomainException('This finance facility name already exists.');if($op==='add')$id=far_next((array)($s['bankFacilities']??[]),'FIN');$a=['id'=>$id,'entity'=>$e,'name'=>$name,'bankId'=>$bank['id'],'currency'=>$bank['currency'],'reference'=>far_text($b['reference']??'',180),'active'=>!array_key_exists('active',$b)||(bool)$b['active']];}
 $s['bankFacilities'][$id]=$a;$s['bankFacilityAudit'][]=['before'=>$old,'after'=>$a,'operation'=>$op,'by'=>$u['username']??'','at'=>gmdate('c')];return ['facilityId'=>$id];
}
function ben_post(array &$s,string $e,array $b,array $u):array {
 $type=(string)($b['type']??'');if(!in_array($type,['SAVING_PROFIT','BANK_CHARGE','PAYMENT','RECEIPT','TRANSFER','FINANCE_DRAW','FINANCE_REPAY','FINANCE_MARKUP'],true))throw new DomainException('Select the bank entry type.');$date=far_date($b['date']??'');$amount=far_cents($b['amount']??null);$bank=ben_bank($s,$e,(string)($b['bankId']??''));$rate=ben_rate($bank,$e,$b['exchangeRate']??0);$ref=far_text($b['reference']??'',180);$note=far_text($b['narration']??'',500);if($ref===''&&$type==='PAYMENT')$ref=far_text(((string)($b['chequeNo']??''))?:($b['bankReference']??''),180);if(($ref===''&&$type!=='PAYMENT')||$note==='')throw new DomainException('Enter a bank reference and narration.');
 foreach((array)($s['journals']??[]) as $j)if(($j['entity']??'')===$e&&($j['status']??'')==='Posted'&&empty($j['reversalOf'])&&empty($j['reversedByPostId'])&&($j['meta']['bankAccountId']??'')===$bank['id']&&$ref!==''&&strcasecmp((string)($j['reference']??''),$ref)===0)throw new DomainException('This bank reference is already posted.');
 $tracking=[];$incoming=in_array($type,['SAVING_PROFIT','RECEIPT','FINANCE_DRAW'],true);if(!$incoming&&$type!=='BANK_CHARGE')$tracking=ben_tracking($s,$e,$bank,$b);$meta=['bankAccountId'=>$bank['id'],'bankEntryType'=>$type,'currency'=>$bank['currency'],'amountNative'=>$amount/100,'exchangeRate'=>$rate]+$tracking;$lines=[];$book=(int)round($amount*$rate);
 if($type==='SAVING_PROFIT'){
  if($bank['depositType']!=='SAVING')throw new DomainException('Select a Saving bank account for profit.');$tax=far_cents($b['withholdingTax']??0,true);if($tax>$amount)throw new DomainException('Tax exceeds gross saving profit.');$net=(int)round(($amount-$tax)*$rate);if($amount>$tax)$lines[]=ben_bank_line($bank,$amount-$tax,$rate,true);if($tax){$a=sac_resolve($s,$e,(string)($b['taxSubaccountId']??$e.'-DEFAULT-TAX-SAVINGS-RECOVERABLE'));if($a['parentCode']!=='1260'||$a['taxCategory']!=='SAVINGS')throw new DomainException('Select savings withholding tax recoverable.');$lines[]=ben_line('1260',$book-$net,0,sac_extra($a)+['currency'=>$bank['currency'],'nativeDebit'=>$tax/100,'nativeCredit'=>0]);}$lines[]=ben_line('4400',0,$book,['subledger'=>'SAVING ACCOUNT PROFIT','currency'=>$bank['currency'],'nativeDebit'=>0,'nativeCredit'=>$amount/100]);$meta['withholdingTax']=$tax/100;$meta['taxCategory']='SAVINGS';
 }elseif($type==='PAYMENT'&&!empty($b['debitRows'])){
  $rows=$b['debitRows'];if(!is_array($rows)||count($rows)>50)throw new DomainException('Add between one and 50 payment debit rows.');$native=0;$used=0;$payees=[];
  foreach($rows as $row){if(!is_array($row))throw new DomainException('Invalid payment debit row.');$p=sac_payee($s,$e,(string)($row['payeeId']??''));$n=far_cents($row['amount']??null);$native+=$n;$current=(int)round($native*$rate);$dr=$current-$used;$used=$current;$code=(string)$p['accountCode'];$extra=['counterparty'=>$p['name'],'subledger'=>$p['name'],'paymentPayeeId'=>$p['id'],'currency'=>$bank['currency'],'nativeDebit'=>$n/100,'nativeCredit'=>0];
   if(!empty($p['subaccountId'])){$a=sac_resolve($s,$e,$p['subaccountId']);if($a['parentCode']!==$code)throw new DomainException('Recipient account has moved. Update its setup before paying.');$extra=array_replace(sac_extra($a),$extra);}
   if($dr<0)throw new DomainException('Invalid debit allocation.');$lines[]=ben_line($code,$dr,0,$extra);$payees[]=$p['name'];
  }
  if($native!==$amount)throw new DomainException('Bank credit must equal the total payment debits.');$lines[]=ben_bank_line($bank,$amount,$rate,false,$tracking);$meta['payee']=implode(', ',array_unique($payees));$meta['debitRows']=$rows;
 }elseif($type==='TRANSFER'){
  $dest=ben_bank($s,$e,(string)($b['destinationBankId']??''));if($dest['id']===$bank['id'])throw new DomainException('Choose different source and destination banks.');if($dest['currency']!==$bank['currency'])throw new DomainException('Use Inter Account Transfer for currency conversion.');$lines=[ben_bank_line($dest,$amount,$rate,true),ben_bank_line($bank,$amount,$rate,false,$tracking)];$meta['destinationBankId']=$dest['id'];
 }elseif(str_starts_with($type,'FINANCE_')){
  $fid=(string)($b['facilityId']??'');$f=$s['bankFacilities'][$fid]??null;if(!$f||$f['entity']!==$e||!$f['active']||$f['bankId']!==$bank['id'])throw new DomainException('Select an active finance facility linked to this bank.');$meta['bankFacilityId']=$fid;$extra=['bankFacilityId'=>$fid,'subledger'=>$f['name'],'currency'=>$f['currency'],'nativeDebit'=>$type==='FINANCE_REPAY'?$amount/100:0,'nativeCredit'=>$type==='FINANCE_DRAW'?$amount/100:0];
  if($type==='FINANCE_DRAW')$lines=[ben_bank_line($bank,$amount,$rate,true),ben_line('2610',0,$book,$extra)];
  elseif($type==='FINANCE_REPAY'){$balance=ben_facility_balance($s,$e,$fid,$date);if($amount>$balance['nativeCents'])throw new DomainException('Repayment exceeds outstanding principal on this date.');$carrying=$amount===$balance['nativeCents']?$balance['bookCents']:(int)round($balance['bookCents']*$amount/$balance['nativeCents']);$lines=[ben_line('2610',$carrying,0,$extra),ben_bank_line($bank,$amount,$rate,false,$tracking)];$fx=$book-$carrying;if($fx)$lines[]=ben_line('7100',$fx>0?$fx:0,$fx<0?-$fx:0,['bankFacilityId'=>$fid]);}
  else{$a=sac_resolve($s,$e,(string)($b['subaccountId']??$e.'-DEFAULT-FINANCE_MARKUP'));if($a['parentCode']!=='6800')throw new DomainException('Finance markup belongs under Bank & Finance Charges.');$lines=[ben_line('6800',$book,0,sac_extra($a)+['bankFacilityId'=>$fid,'currency'=>$bank['currency'],'nativeDebit'=>$amount/100,'nativeCredit'=>0]),ben_bank_line($bank,$amount,$rate,false,$tracking)];}
  $meta['financeReference']=far_text($b['financeReference']??'',180);$meta['exportReference']=far_text($b['exportReference']??'',180);
 }else{
  $a=sac_resolve($s,$e,(string)($b['subaccountId']??''));if($type==='BANK_CHARGE'&&$a['parentCode']!=='6800')throw new DomainException('Bank charges belong under Bank & Finance Charges.');if(in_array($a['parentCode'],['1110','1120','1430','1440','1610','2610','3400','3300'],true))throw new DomainException('Use the dedicated bank, investment or opening-balance screen.');$extra=sac_extra($a)+['currency'=>$bank['currency'],'nativeDebit'=>$incoming?0:$amount/100,'nativeCredit'=>$incoming?$amount/100:0,'counterparty'=>far_text($b['payee']??'',180)];if(in_array($type,['PAYMENT','RECEIPT'],true)&&$extra['counterparty']==='')throw new DomainException('Enter who this payment or receipt is for.');$lines=[$incoming?ben_line($a['parentCode'],0,$book,$extra):ben_line($a['parentCode'],$book,0,$extra),ben_bank_line($bank,$amount,$rate,$incoming,$tracking)];
 }
 $j=ben_journal($s,$e,$date,$ref,$note,$lines,$u,$meta);ben_validate_finance($s,$e);
 // A repayment cannot be inserted ahead of a later foreign-currency repayment:
 // its historical carrying cost would become inconsistent. Dates after the
 // latest facility principal movement remain freely postable.
 if($type==='FINANCE_REPAY'||$type==='FINANCE_DRAW')foreach((array)$s['journals'] as $later)if($later['id']!==$j['id']&&($later['entity']??'')===$e&&($later['meta']['bankFacilityId']??'')===($meta['bankFacilityId']??'')&&($later['meta']['bankEntryType']??'')==='FINANCE_REPAY'&&empty($later['reversalOf'])&&empty($later['reversedByPostId'])&&($later['date']??'')>$date)throw new DomainException('A later finance repayment already exists. Correct the later repayments before backdating principal movements.');
 return ['journalId'=>$j['id'],'journal'=>$j];
}
function ben_reverse(array &$s,string $e,array $b,array $u):array {
 $id=(string)($b['journalId']??'');$j=$s['journals'][$id]??null;if(!$j||$j['entity']!==$e||$j['sourceType']!=='BANK_ENTRY'||!empty($j['reversedByPostId']))throw new DomainException('Select an unreversed bank entry.');$reason=far_text($b['reason']??'',500);if(strlen($reason)<5)throw new DomainException('Enter the correction reason.');$date=far_date($b['date']??'');if($date<$j['date'])throw new DomainException('Reversal cannot precede the original entry.');$fid=$j['meta']['bankFacilityId']??'';if($fid&&in_array($j['meta']['bankEntryType'],['FINANCE_DRAW','FINANCE_REPAY'],true))foreach((array)$s['journals'] as $later)if($later['id']!==$id&&($later['meta']['bankFacilityId']??'')===$fid&&in_array($later['meta']['bankEntryType']??'',['FINANCE_DRAW','FINANCE_REPAY'],true)&&empty($later['reversalOf'])&&empty($later['reversedByPostId'])&&($later['date']>$j['date']||($later['date']===$j['date']&&strcmp($later['id'],$id)>0)))throw new DomainException('Reverse later facility principal entries first.');
 $lines=[];foreach($j['lines'] as $l){[$l['debit'],$l['credit']]=[$l['credit'],$l['debit']];foreach([['bankDebit','bankCredit'],['nativeDebit','nativeCredit']] as [$d,$c])if(isset($l[$d])||isset($l[$c]))[$l[$d],$l[$c]]=[$l[$c]??0,$l[$d]??0];$lines[]=$l;}$reversal=ben_journal($s,$e,$date,$id,'REVERSAL '.$id.' '.$reason,$lines,$u,$j['meta']+['reason'=>$reason],$id);$s['journals'][$id]['reversedByPostId']=$reversal['id'];ben_validate_finance($s,$e);return ['journalId'=>$reversal['id'],'journal'=>$reversal];
}
function ben_payload(array $s,string $e):array {
 $fac=[];foreach((array)($s['bankFacilities']??[]) as $f)if($f['entity']===$e){$bal=ben_facility_balance($s,$e,$f['id']);$fac[]=$f+['outstanding'=>$bal['nativeCents']/100,'bookBalance'=>$bal['bookCents']/100];}$history=array_values(array_filter((array)($s['journals']??[]),static fn($j)=>($j['entity']??'')===$e&&in_array($j['sourceType']??'',['BANK_ENTRY','BANK_ENTRY_REVERSAL'],true)));usort($history,static fn($a,$b)=>strcmp($b['date'],$a['date'])?:strcmp($b['id'],$a['id']));return ['ok'=>true,'entity'=>$e,'revision'=>(int)($s['revision']??0),'banks'=>ben_banks($s,$e),'payees'=>sac_payees($s,$e),'heads'=>array_values(sac_entity_chart($s,$e)),'facilities'=>$fac,'subaccounts'=>array_values(array_map(static fn($a)=>sac_resolve($s,$e,$a['id'],false),sac_accounts($s,$e))),'history'=>array_slice($history,0,100)];
}

