<?php
declare(strict_types=1);
require dirname(__DIR__).'/auth_store.php';require_once __DIR__.'/bank_entries_core.php';
header('Content-Type: application/json; charset=UTF-8');header('Cache-Control: no-store');
function ben_out(array $v,int $status=200):never {http_response_code($status);echo json_encode($v,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);exit;}
try{
 $u=tt_require_login();$write=$_SERVER['REQUEST_METHOD']==='POST';if(!$write&&$_SERVER['REQUEST_METHOD']!=='GET')ben_out(['ok'=>false,'error'=>'Method not allowed.'],405);$b=$write?json_decode(file_get_contents('php://input')?:'{}',true,512,JSON_THROW_ON_ERROR):[];$e=strtoupper((string)($b['entity']??$_GET['entity']??''));if(!in_array($e,['TTI','BRM','TG'],true)||!tt_user_can_access_entity($u,$e,'View')||!sac_permission($u,'cashbank','View'))ben_out(['ok'=>false,'error'=>'Bank and company View permission required.'],403);
 if($write){if(!tt_verify_csrf((string)($b['csrf']??'')))ben_out(['ok'=>false,'error'=>'Session expired.'],419);$action=(string)($b['action']??'');$right=$action==='reverse'?'Edit':($action==='facility'&&($b['operation']??'add')==='delete'?'Delete':($action==='facility'&&($b['operation']??'add')==='edit'?'Edit':'Create'));if(!sac_permission($u,'cashbank',$right)||!tt_user_can_access_entity($u,$e,$right))ben_out(['ok'=>false,'error'=>'Bank '.$right.' permission required.'],403);}
 tt_ensure_data_dir();$h=fopen(TT_DATA_DIR.'/accounts.json','c+');if(!$h||!flock($h,$write?LOCK_EX:LOCK_SH))throw new RuntimeException('Accounts storage unavailable.');try{$raw=stream_get_contents($h);$s=$raw!==''?json_decode($raw,true,512,JSON_THROW_ON_ERROR):[];if(!is_array($s))throw new RuntimeException('Invalid Accounts storage.');$result=[];
 if($write){$key=(string)($b['requestKey']??'');if(!preg_match('/^[A-Za-z0-9._:-]{8,128}$/',$key))throw new DomainException('Reopen the form before saving.');$identity=$e.'|'.($u['id']??0).'|'.$key;$fp=hash('sha256',json_encode($b,JSON_THROW_ON_ERROR));$saved=$s['bankEntryRequests'][$identity]??null;if($saved){if($saved['fingerprint']!==$fp)ben_out(['ok'=>false,'error'=>'Request key already used.'],409);$result=$saved['result'];}else{if((int)($b['revision']??-1)!==(int)($s['revision']??0))ben_out(['ok'=>false,'error'=>'Accounts changed. Reopen Bank Entry before saving. Your entry has not posted.'],409);$result=match($action){'post'=>ben_post($s,$e,$b,$u),'facility'=>ben_facility($s,$e,$b,$u),'reverse'=>ben_reverse($s,$e,$b,$u),default=>throw new DomainException('Unknown bank action.')};$s['bankEntryRequests'][$identity]=['fingerprint'=>$fp,'result'=>$result];$s['revision']=(int)($s['revision']??0)+1;$encoded=json_encode($s,JSON_THROW_ON_ERROR);rewind($h);if(!ftruncate($h,0)||fwrite($h,$encoded)!==strlen($encoded)||!fflush($h))throw new RuntimeException('Save failed.');}}
 $out=ben_payload($s,$e)+['result'=>$result];foreach(['Create','Edit','Delete'] as $right)$out['can'.$right]=sac_permission($u,'cashbank',$right)&&tt_user_can_access_entity($u,$e,$right);
 }finally{flock($h,LOCK_UN);fclose($h);}ben_out($out);
}catch(DomainException $x){ben_out(['ok'=>false,'error'=>$x->getMessage()],422);}catch(Throwable $x){error_log('Bank entries: '.$x->getMessage());ben_out(['ok'=>false,'error'=>'Bank entries could not be loaded or saved.'],500);}
