<?php
declare(strict_types=1);
require dirname(__DIR__).'/auth_store.php';
header('Content-Type: application/json; charset=UTF-8');
header('Cache-Control: no-store, no-cache, must-revalidate');
const BM_FILE=TT_DATA_DIR.'/accounts.json';
function bm_out(array $x,int $s=200):never{http_response_code($s);echo json_encode($x,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function bm_default():array{return ['revision'=>0,'brokerageMaster'=>['productRates'=>[],'whtRates'=>[]]];}
function bm_read():array{tt_ensure_data_dir();if(!is_file(BM_FILE))return bm_default();$h=fopen(BM_FILE,'r');if($h===false||!flock($h,LOCK_SH))throw new RuntimeException('store');try{$raw=stream_get_contents($h);}finally{flock($h,LOCK_UN);fclose($h);} $s=$raw?json_decode($raw,true):null;return is_array($s)?array_replace_recursive(bm_default(),$s):bm_default();}
function bm_can_view(array $u):bool{return tt_user_can_open_module($u,'Accounts')||tt_user_can_open_module($u,'Directors')||($u['role']??'')==='Super Admin';}
function bm_can_write(array $u):bool{if(($u['role']??'')==='Super Admin')return true;if(tt_user_can_open_module($u,'Directors'))return true;$p=$u['permissions']['Accounts']??null;if($p==='all')return true;if(!is_array($p))return false;if(in_array('Create',$p,true)||in_array('Edit',$p,true)||in_array('Approve',$p,true))return true;foreach($p as $a)if(is_array($a)&&(in_array('Create',$a,true)||in_array('Edit',$a,true)||in_array('Approve',$a,true)))return true;return false;}
function bm_date(string $v,string $label,bool $optional=false):string{$v=trim($v);if($optional&&$v==='')return '';if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$v))bm_out(['ok'=>false,'error'=>$label.' is invalid.'],422);return $v;}
function bm_num(mixed $v,string $label,bool $allowZero=false):float{$n=round((float)$v,4);if($n<0||(!$allowZero&&$n<=0))bm_out(['ok'=>false,'error'=>$label.' is invalid.'],422);return $n;}
function bm_sort(array &$rows):void{usort($rows,static fn($a,$b)=>strcmp((string)($b['effectiveFrom']??''),(string)($a['effectiveFrom']??''))?:strcmp((string)($a['product']??''),(string)($b['product']??'')));}
try{$u=tt_require_login();if(!bm_can_view($u))bm_out(['ok'=>false,'error'=>'Accounts or Directors permission required.'],403);if($_SERVER['REQUEST_METHOD']==='GET'){$s=bm_read();$m=$s['brokerageMaster']??[];$p=array_values((array)($m['productRates']??[]));$w=array_values((array)($m['whtRates']??[]));bm_sort($p);bm_sort($w);bm_out(['ok'=>true,'productRates'=>$p,'whtRates'=>$w,'revision'=>(int)($s['revision']??0)]);}if($_SERVER['REQUEST_METHOD']!=='POST')bm_out(['ok'=>false,'error'=>'Method not allowed.'],405);if(!bm_can_write($u))bm_out(['ok'=>false,'error'=>'Permission to update Brokerage Master is required.'],403);$b=json_decode(file_get_contents('php://input')?:'',true);if(!is_array($b)||!tt_verify_csrf((string)($b['csrf']??'')))bm_out(['ok'=>false,'error'=>'Session expired. Refresh and try again.'],419);$action=(string)($b['action']??'');tt_ensure_data_dir();$h=fopen(BM_FILE,'c+');if($h===false||!flock($h,LOCK_EX))throw new RuntimeException('store');try{rewind($h);$raw=stream_get_contents($h);$s=$raw?json_decode($raw,true):null;if(!is_array($s))$s=bm_default();$s=array_replace_recursive(bm_default(),$s);$s['brokerageMaster']=is_array($s['brokerageMaster']??null)?$s['brokerageMaster']:['productRates'=>[],'whtRates'=>[]];$who=(string)($u['full_name']??$u['username']??'User');if($action==='save_product_rate'){$product=trim((string)($b['product']??''));if($product==='')bm_out(['ok'=>false,'error'=>'Product is required.'],422);$rate=bm_num($b['ratePer100Kg']??0,'Brokerage rate');$from=bm_date((string)($b['effectiveFrom']??''),'Effective From');$to=bm_date((string)($b['effectiveTo']??''),'Effective To',true);if($to!==''&&$to<$from)bm_out(['ok'=>false,'error'=>'Effective To cannot be before Effective From.'],422);$id='BPR-'.substr(hash('sha256',strtoupper($product).'|'.$from),0,16);$s['brokerageMaster']['productRates'][$id]=['id'=>$id,'product'=>$product,'ratePer100Kg'=>$rate,'effectiveFrom'=>$from,'effectiveTo'=>$to,'active'=>(bool)($b['active']??true),'updatedAt'=>gmdate('c'),'updatedBy'=>$who];}
elseif($action==='save_wht_rate'){$rate=bm_num($b['whtPercent']??0,'Brokerage withholding %',true);if($rate>100)bm_out(['ok'=>false,'error'=>'Brokerage withholding % cannot exceed 100.'],422);$from=bm_date((string)($b['effectiveFrom']??''),'Effective From');$to=bm_date((string)($b['effectiveTo']??''),'Effective To',true);if($to!==''&&$to<$from)bm_out(['ok'=>false,'error'=>'Effective To cannot be before Effective From.'],422);$id='BWHT-'.substr(hash('sha256',$from),0,16);$s['brokerageMaster']['whtRates'][$id]=['id'=>$id,'whtPercent'=>$rate,'effectiveFrom'=>$from,'effectiveTo'=>$to,'active'=>(bool)($b['active']??true),'updatedAt'=>gmdate('c'),'updatedBy'=>$who];}
else bm_out(['ok'=>false,'error'=>'Unknown Brokerage Master action.'],422);$s['revision']=(int)($s['revision']??0)+1;rewind($h);ftruncate($h,0);fwrite($h,json_encode($s,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($h);}finally{flock($h,LOCK_UN);fclose($h);}bm_out(['ok'=>true,'revision'=>$s['revision']]);}catch(Throwable $e){bm_out(['ok'=>false,'error'=>'Brokerage Master is temporarily unavailable.'],500);}