<?php
declare(strict_types=1);
require_once __DIR__.'/opening_balance_core.php';
require_once __DIR__.'/accounts_shipment_source.php';

const CF_CUTOFF='2026-07-01';
const CF_LAST_SHIPMENT_DATE='2026-10-01';
class CfAccessException extends RuntimeException {}
function cf_text(mixed $v,int $max=160):string {if(!is_scalar($v)&&$v!==null)throw new DomainException('Invalid text.');$v=trim((string)$v);if(strlen($v)>$max)throw new DomainException('A field is too long.');return $v;}
function cf_date(mixed $v,bool $optional=false):string {$v=cf_text($v,10);if($optional&&$v==='')return ''; $d=DateTimeImmutable::createFromFormat('!Y-m-d',$v);if(!$d||$d->format('Y-m-d')!==$v)throw new DomainException('Enter a valid date.');return $v;}
function cf_number(mixed $v,bool $zero=true):float {if(!is_numeric($v)||!is_finite((float)$v)||(float)$v<0||(float)$v>1e11)throw new DomainException('Enter a valid non-negative amount.');$n=round((float)$v,2);if(!$zero&&$n<=0)throw new DomainException('Amount must be greater than zero.');return $n;}
function cf_rate(mixed $v,bool $zero=false):float {if(!is_numeric($v)||!is_finite((float)$v)||(float)$v<0||(float)$v>1e6||(!$zero&&(float)$v<=0))throw new DomainException('Enter a valid carrying exchange rate.');return round((float)$v,8);}
function cf_currency(mixed $v):string {$v=strtoupper(cf_text($v,3));if(!in_array($v,(array)(tt_master_options()['currencies']??[]),true))throw new DomainException('Choose a currency from Currency Master.');return $v;}
function cf_management(array $u,string $e):bool {return job_authorized($u)&&in_array($e,job_entities($u),true)&&(($u['role']??'')==='Super Admin'||!tt_user_can_open_module($u,'Accounts')||tt_user_can_access_entity($u,$e,'Approve'));}
function cf_can_read(array $u):bool {foreach(['customer','supplier','freight','transport','services','purchases','expenses','tg'] as $icon)if(tt_user_can_module_action($u,'Accounts',$icon,'View'))return true;return false;}
function cf_entities(array $u):array {if(job_authorized($u))return job_entities($u);return tt_user_can_open_module($u,'Accounts')&&cf_can_read($u)?tt_user_accounts_entities($u):[];}
function cf_access(array $u,string $e,bool $management=false):void {if(!in_array($e,cf_entities($u),true)||($management&&!cf_management($u,$e)))throw new CfAccessException('You do not have permission for these company books.');}
function cf_bill_permission(array $u,string $e,string $kind):bool {$icon=$e==='TG'?'supplier':match($kind){'FREIGHT'=>'freight','TRANSPORT'=>'transport','CLEARING','FUMIGATION','INSPECTION'=>'services','BAGS'=>'purchases',default=>'expenses'};return tt_user_can_open_module($u,'Accounts')&&tt_user_can_access_entity($u,$e,'Create')&&(tt_user_can_module_action($u,'Accounts',$icon,'Create')||tt_user_can_module_action($u,'Accounts',$icon,'Approve'));}
function cf_catalog():array {$m=json_decode((string)file_get_contents(__DIR__.'/../accounts/accounting_master_v1.json'),true,512,JSON_THROW_ON_ERROR);$out=[];foreach($m['chart'] as $a)$out[(string)$a['code']]=$a['name'];return $out;}
function cf_party(string $id):array {foreach((array)(tt_list_masters()['business_parties']??[]) as $p)if((string)($p['id']??'')===$id&&strcasecmp((string)($p['values'][10]??'Active'),'Inactive')!==0)return $p;throw new DomainException('Choose an active Business Party.');}
function cf_customer(string $id):string {foreach((array)(tt_list_masters()['export_customers']??[]) as $p)if((string)($p['id']??'')===$id&&strcasecmp((string)($p['values'][10]??'Active'),'Inactive')!==0)return cf_text($p['values'][0]);throw new DomainException('Choose an Export Customer from Master Records.');}
function cf_bill_map(string $kind):array {return match($kind){'FREIGHT'=>['5520','2130',['Freight Forwarder','Shipping Line / Carrier']],'TRANSPORT'=>['5510','2130',['Transporter']],'CLEARING'=>['5530','2130',['Clearing Agent']],'FUMIGATION'=>['5540','2130',['Fumigation']],'INSPECTION'=>['5530','2130',['Inspection']],'BAGS'=>['5550','2140',['Bag Supplier']],'OTHER'=>['5550','2140',['Service Provider','Other','Agent']],default=>throw new DomainException('Rice is paid through Bank Payment. Choose a shipment expense category.')};}
function cf_balance(array $b):array {$invoice=cf_number($b['invoiceAmount']??0);$prior=cf_number($b['receivedBefore']??0);if($prior>$invoice)throw new DomainException('Receipts before July exceed the invoice value.');$open=round($invoice-$prior,2);$mode=(string)($b['mode']??'NEW');if(!in_array($mode,['NEW','LINK'],true))throw new DomainException('Choose new opening balance or an existing opening posting.');return ['invoiceNo'=>cf_text($b['invoiceNo']??''),'invoiceDate'=>cf_date($b['invoiceDate']??'',true),'currency'=>cf_currency($b['currency']??''),'invoiceAmount'=>$invoice,'receivedBefore'=>$prior,'outstanding'=>$open,'mode'=>$mode,'journalId'=>cf_text($b['journalId']??''),'lineIndex'=>(int)($b['lineIndex']??-1)];}
function cf_bill(array $b,array $r):array {
 $entity=strtoupper(cf_text($b['entity']??$r['entity'],3));if(!in_array($entity,$r['tgPack']?[$r['entity'],'TG']:[$r['entity']],true))throw new DomainException('The bill company must be part of this shipment.');
 $kind=strtoupper(cf_text($b['kind']??''));[$expense,$payable,$roles]=cf_bill_map($kind);$party=cf_party(cf_text($b['partyId']??''));$actual=tt_business_party_categories($party['values'][2]??'');if(!array_intersect($roles,$actual))throw new DomainException('The selected party does not have the required supplier/service role.');
 $invoice=cf_text($b['invoiceNo']??'');if($invoice==='')throw new DomainException('Bill invoice/reference is required.');$amount=cf_number($b['amount']??0,false);$paid=cf_number($b['paidBefore']??0);if($paid>$amount)throw new DomainException('Already paid exceeds the bill amount.');$date=cf_date($b['billDate']??'');$treatment=cf_text($b['treatment']??'CURRENT');if(!in_array($treatment,['CURRENT','NEW','LINK','PAID'],true))throw new DomainException('Choose the bill accounting position.');if($treatment==='CURRENT'&&($date<CF_CUTOFF||$paid>0))throw new DomainException('A new current-year bill needs a date from 1 July and no already-paid amount. Link an existing posting for bills already recorded.');if(in_array($treatment,['NEW','LINK'],true)&&$date>=CF_CUTOFF)throw new DomainException('Opening payable bills must be dated before 1 July.');if($treatment==='PAID'&&abs($amount-$paid)>.005)throw new DomainException('A paid bill must have zero balance.');
 $cur=cf_currency($b['currency']??($entity==='TG'?'AED':'PKR'));$rate=cf_rate($b['rate']??1);if($cur===($entity==='TG'?'AED':'PKR'))$rate=1;
 return ['id'=>cf_text($b['id']??''),'entity'=>$entity,'kind'=>$kind,'partyId'=>(string)$party['id'],'vendor'=>(string)$party['values'][0],'invoiceNo'=>$invoice,'billDate'=>$date,'dueDate'=>cf_date($b['dueDate']??'',true),'currency'=>$cur,'amount'=>$amount,'paidBefore'=>$paid,'outstanding'=>round($amount-$paid,2),'rate'=>$rate,'expenseAccount'=>$expense,'payableAccount'=>$payable,'treatment'=>$treatment,'journalId'=>cf_text($b['journalId']??''),'lineIndex'=>(int)($b['lineIndex']??-1),'notes'=>cf_text($b['notes']??'',500),'status'=>'Information only'];
}
function cf_clean(array $b,array $s,array $u):array {
 $e=strtoupper(cf_text($b['entity']??'',3));if(!in_array($e,['TTI','BRM'],true))throw new DomainException('Select the Pakistan exporter TTI or BRM.');cf_access($u,$e,true);$tg=($b['tgPack']??false)===true;if($tg)cf_access($u,'TG',true);
 $date=cf_date($b['shipmentDate']??'');if($date>CF_LAST_SHIPMENT_DATE)throw new DomainException('Invoice and B/L dates must be on or before 1 October 2026.');
 $r=['entity'=>$e,'tgPack'=>$tg,'customerId'=>cf_text($b['customerId']??''),'customer'=>cf_customer(cf_text($b['customerId']??'')),'shipmentDate'=>$date];
 foreach(['contractRef','lotRef','blNo','loadingProgrammeNo','shippingLine','forwarder','vessel','voyage','portOfLoading','portOfDischarge','goods','brand','bagPoNo'] as $key)$r[$key]=cf_text($b[$key]??'');if($r['contractRef']===''||$r['lotRef']===''||$r['blNo']==='')throw new DomainException('Shipment/contract, lot and B/L references are required.');
 $r['quantityMT']=cf_number($b['quantityMT']??0);$r['containerCount']=(int)($b['containerCount']??0);if($r['containerCount']<0||$r['containerCount']>10000)throw new DomainException('Invalid container count.');$r['containers']=array_values(array_unique(array_filter(array_map(static fn($v)=>cf_text($v,25),(array)($b['containers']??[])))));if(count($r['containers'])>$r['containerCount'])throw new DomainException('Container numbers exceed the stated container count.');
 $r['buyerBalance']=cf_balance((array)($b['buyerBalance']??[]));if($r['buyerBalance']['invoiceNo']===''||$r['buyerBalance']['invoiceAmount']<=0)throw new DomainException('Enter the buyer invoice number and value.');
 if($tg){$r['pakistanBalance']=cf_balance((array)($b['pakistanBalance']??[]));$r['tgPayableBalance']=cf_balance((array)($b['tgPayableBalance']??[]));$p=$r['pakistanBalance'];$t=$r['tgPayableBalance'];if($p['invoiceNo']===''||$p['invoiceAmount']<=0||$p['invoiceNo']!==$t['invoiceNo']||$p['currency']!==$t['currency']||abs($p['invoiceAmount']-$t['invoiceAmount'])>.005||abs($p['receivedBefore']-$t['receivedBefore'])>.005)throw new DomainException('Pakistan → TG invoice, currency, value and pre-July settlements must agree on both sides.');}
 foreach(['buyerBalance','pakistanBalance','tgPayableBalance'] as $key)if(isset($r[$key])&&$r[$key]['invoiceDate']>CF_LAST_SHIPMENT_DATE)throw new DomainException('Invoice dates must be on or before 1 October 2026.');
 $r['fiRefs']=[];$r['gdRefs']=[];foreach(['fiRefs','gdRefs'] as $key){if(count((array)($b[$key]??[]))>50)throw new DomainException('Too many FI/GD references.');foreach((array)($b[$key]??[]) as $ref){$number=cf_text($ref['number']??'');if($number==='')continue;$r[$key][]=['number'=>$number,'date'=>cf_date($ref['date']??'',true),'amount'=>cf_number($ref['amount']??0)];}}
 $r['advance100']=($b['advance100']??false)===true;$r['advanceReceiptDate']=$r['advance100']?cf_date($b['advanceReceiptDate']??''):'';if($r['advance100']&&($r['advanceReceiptDate']>=CF_CUTOFF||($tg?$r['pakistanBalance']['outstanding']:$r['buyerBalance']['outstanding'])>.005))throw new DomainException('100% advance before July requires its receipt date and a fully settled Pakistan export invoice.');
 $r['operationalShipmentId']='';foreach(tt_accounts_shipment_rows(tt_accounts_exports_root(),$e) as $source)if(strcasecmp($source['contract'],$r['contractRef'])===0&&strcasecmp($source['lot'],$r['lotRef'])===0){if($r['operationalShipmentId']!=='')throw new DomainException('More than one existing lot matches this reference. Resolve the shipment identity first.');$r['operationalShipmentId']=$source['id'];}
 $r['ricePaymentReferences']=cf_text($b['ricePaymentReferences']??'',1500);$r['notes']=cf_text($b['notes']??'',2000);$r['bills']=[];if(count((array)($b['bills']??[]))>100)throw new DomainException('No more than 100 bills per shipment.');foreach((array)($b['bills']??[]) as $i=>$bill){$x=cf_bill($bill,$r);cf_access($u,$x['entity'],true);$x['id']='B'.($i+1);$r['bills'][]=$x;}
 foreach((array)($s['carryForwardShipments']??[]) as $existing)if(($existing['id']??'')!==($b['id']??'')&&$existing['entity']===$e&&strcasecmp($existing['contractRef'],$r['contractRef'])===0&&strcasecmp($existing['lotRef'],$r['lotRef'])===0)throw new DomainException('This shipment/lot is already in the carry-forward register.');
 return $r;
}
function cf_opening(array &$s,array $u,string $e,string $account,string $party,array $b,string $side,string $key,string $record):array {
 $native=cf_number($b['outstanding']??0);if($native<=.005)return ['journalId'=>'','amount'=>0,'rate'=>0];cf_access($u,$e,true);if(($b['mode']==='LINK'||array_key_exists('rate',$b))&&($s['openingBalanceSettings'][$e]['enabled']??true)!==true)throw new DomainException('Opening entry is disabled for '.$e.'.');$cur=$b['currency'];$base=$e==='TG'?'AED':'PKR';$deferred=!array_key_exists('rate',$b);$rate=$cur===$base?1:($deferred?0:cf_rate($b['rate']));$amount=round($native*$rate,2);
 if($b['mode']==='LINK'){
  $jid=$b['journalId'];$j=$s['journals'][$jid]??[];$index=$b['lineIndex'];$line=$j['lines'][$index]??[];
  if(($j['entity']??'')!==$e||($j['status']??'')!=='Posted'||($j['date']??'')!==CF_CUTOFF||!in_array($j['sourceType']??'',['OPENING_BALANCE_BF','CARRY_FORWARD_OPENING'],true)||!empty($j['openingReversalId'])||($line['account']??'')!==$account||job_key(job_party_name($line,(array)($j['meta']??[])))!==job_key($party))throw new DomainException('Choose an unreversed opening line for the same company, account and party.');
  foreach((array)($s['journals']??[]) as $x)if(($x['reversalOf']??'')===$jid)throw new DomainException('This opening posting has been reversed.');
  $lcur=(string)($line['nativeCurrency']??$line['currency']??$base);$capacity=cf_number($line[$side==='Debit'?'nativeDebit':'nativeCredit']??($cur===$base?($line[strtolower($side)]??0):0));$book=cf_number($line[strtolower($side)]??0);if($lcur!==$cur||$capacity<=0)throw new DomainException('Currency must match the existing opening line.');$rate=$book/$capacity;$amount=round($native*$rate,2);
  $used=0;foreach((array)($s['carryForwardOpeningLinks']??[]) as $link)if($link['journalId']===$jid&&$link['lineIndex']===$index)$used+=(float)$link['nativeAmount'];if($used+$native>$capacity+.005)throw new DomainException('This opening line does not have enough unassigned balance.');
 }else{
  foreach((array)($s['journals']??[]) as $j)if(($j['entity']??'')===$e&&($j['status']??'')==='Posted'&&($j['date']??'')<=CF_CUTOFF&&($j['sourceType']??'')!=='CARRY_FORWARD_OPENING')foreach((array)($j['lines']??[]) as $l)if(($l['account']??'')===$account&&job_key(job_party_name($l,(array)($j['meta']??[])))===job_key($party)&&abs((float)($l['debit']??0)-(float)($l['credit']??0))>.005)throw new DomainException('An opening/earlier posting already exists for '.$party.'. Link its opening line instead of creating a duplicate.');
  if($deferred)return ['journalId'=>'','amount'=>0,'rate'=>0,'pendingValuation'=>true];
  $jid=cf_journal($s,$u,$e,CF_CUTOFF,'CARRY_FORWARD_OPENING',$record,$account,'3400',$amount,$side,['counterparty'=>$party,'subledger'=>$party,'currency'=>$cur,'nativeCurrency'=>$cur,'nativeDebit'=>$side==='Debit'?$native:0,'nativeCredit'=>$side==='Credit'?$native:0,'rate'=>$rate],['carryForwardShipmentId'=>$record,'openingBalance'=>true,'openingAccount'=>$account,'openingParty'=>$party]);$index=0;
 }
 $s['carryForwardOpeningLinks'][$key]=['shipmentId'=>$record,'journalId'=>$jid,'lineIndex'=>$index,'nativeAmount'=>$native,'currency'=>$cur,'entity'=>$e];return ['journalId'=>$jid,'amount'=>$amount,'rate'=>$rate];
}
function cf_journal(array &$s,array $u,string $e,string $date,string $type,string $ref,string $account,string $contra,float $amount,string $side,array $extra,array $meta):string {
 $cat=cf_catalog();if(!isset($cat[$account],$cat[$contra])||$amount<=0)throw new DomainException('The ledger mapping or amount is invalid.');$id=tt_next_post_id((array)($s['journals']??[]),'Accounts','Journal',$date);$debit=$side==='Debit';$now=gmdate('c');$by=(string)($u['full_name']??$u['username']??'Accounts');$narr=$type==='CARRY_FORWARD_OPENING'?'OPENING SHIPMENT BALANCE B/F':'CARRY-FORWARD SHIPMENT EXPENSE BILL';
 $s['journals'][$id]=['id'=>$id,'entity'=>$e,'date'=>$date,'sourceType'=>$type,'reference'=>$ref,'narration'=>$narr,'lines'=>[['account'=>$account,'accountName'=>$cat[$account],'debit'=>$debit?$amount:0,'credit'=>$debit?0:$amount]+$extra,['account'=>$contra,'accountName'=>$cat[$contra],'debit'=>$debit?0:$amount,'credit'=>$debit?$amount:0,'memo'=>$narr]+($type==='CARRY_FORWARD_OPENING'?[]:array_merge($extra,['nativeDebit'=>$extra['nativeCredit']??0,'nativeCredit'=>$extra['nativeDebit']??0]))],'totalDebit'=>$amount,'totalCredit'=>$amount,'status'=>'Posted','meta'=>$meta,'createdAt'=>$now,'createdBy'=>$by,'userId'=>(int)($u['id']??0),'approvedAt'=>$now,'approvedBy'=>$by,'approvedByUserId'=>(int)($u['id']??0),'reversalOf'=>null];return $id;
}
function cf_publish(array &$s,array &$r,array $u):void {
 $id=$r['id'];$cid=$id.'|BUYER';$pid=$id.'|PAKISTAN';$tid=$id.'|TG';$meta=['carryForwardShipmentId'=>$id,'sourceModule'=>'Carry-forward Shipments','contractRef'=>$r['contractRef'],'lotRef'=>$r['lotRef'],'customer'=>$r['customer'],'onBoardDate'=>$r['shipmentDate'],'blNo'=>$r['blNo'],'fiRefs'=>array_column($r['fiRefs'],'number'),'gdRefs'=>array_column($r['gdRefs'],'number'),'actualQtyMT'=>$r['quantityMT'],'product'=>$r['goods'],'invoiceStage'=>'Final','historicalCostExcluded'=>true];
 foreach(['BUYER'=>[$r['tgPack']?'TG':$r['entity'],'CUSTOMER_EXPORT_SALE',$r['buyerBalance']],'PAKISTAN'=>[$r['entity'],'TG_PAKISTAN_INTERCOMPANY',$r['pakistanBalance']??[]],'TG'=>['TG','TG_INTERCOMPANY_PAYABLE',$r['tgPayableBalance']??[]]] as $role=>[$entity,$type,$balance]){if(!$balance)continue;foreach((array)($s['exportCandidates']??[]) as $existingId=>$candidate)if(($candidate['entity']??'')===$entity&&($candidate['candidateType']??'')===$type&&(strcasecmp((string)($candidate['meta']['commercialInvoiceNo']??''),(string)$balance['invoiceNo'])===0||($role!=='BUYER'&&$r['operationalShipmentId']!==''&&($candidate['sourceKey']??'')===$r['operationalShipmentId']))&&strcasecmp((string)($candidate['meta']['contractRef']??''),$r['contractRef'])===0){if(!empty($candidate['journalId'])&&$balance['outstanding']>.005)throw new DomainException('This invoice is already posted. Use its existing receivable/payable rather than bringing it forward again.');if($role==='BUYER')$cid=(string)$existingId;elseif($role==='PAKISTAN')$pid=(string)$existingId;else $tid=(string)$existingId;}}
 $r['buyerCandidateId']=$cid;$r['pakistanCandidateId']=$pid;$r['tgPayableCandidateId']=$tid;
 $targets=[[$cid,$r['tgPack']?'TG':$r['entity'],'CUSTOMER_EXPORT_SALE','1210',$r['customer'],$r['buyerBalance'],'Debit']];
 if($r['tgPack']){$targets[]=[$pid,$r['entity'],'TG_PAKISTAN_INTERCOMPANY','1240','TG',$r['pakistanBalance'],'Debit'];$targets[]=[$tid,'TG','TG_INTERCOMPANY_PAYABLE','2500',$r['entity'],$r['tgPayableBalance'],'Credit'];}
 foreach($targets as [$key,$e,$type,$account,$party,$b,$side]){
  unset($b['rate']);$opening=cf_opening($s,$u,$e,$account,$party,$b,$side,$key,$id);if($b['outstanding']<=.005)continue;
  foreach((array)($s['exportCandidates']??[]) as $c)if(($c['id']??'')!==$key&&($c['entity']??'')===$e&&($c['candidateType']??'')===$type&&strcasecmp((string)($c['meta']['commercialInvoiceNo']??''),$b['invoiceNo'])===0&&strcasecmp((string)($c['meta']['contractRef']??''),$r['contractRef'])===0)throw new DomainException('This invoice already has an Accounts export source. Use that existing source.');
  $s['exportCandidates'][$key]=['id'=>$key,'entity'=>$e,'candidateType'=>$type,'sourceKey'=>$r['operationalShipmentId']?:$id,'reference'=>$b['invoiceNo'],'counterparty'=>$party,'transactionCurrency'=>$b['currency'],'transactionAmount'=>$b['outstanding'],'functionalCurrency'=>$e==='TG'?'AED':'PKR','pendingValuation'=>!empty($opening['pendingValuation']),'functionalRate'=>$opening['rate'],'currentCarryingRate'=>$opening['rate'],'currentCarryingAsOf'=>CF_CUTOFF,'functionalAmount'=>$opening['amount'],'journalId'=>$opening['journalId'],'recognitionDate'=>CF_CUTOFF,'suggestedRecognitionDate'=>CF_CUTOFF,'controlConfirmed'=>true,'status'=>!empty($opening['pendingValuation'])?'Registered in invoice currency — ready for settlement':'Opening receivable / payable linked','costOfSalesStatus'=>'Historical shipment — no stock or cost reposting','costAccount'=>$type==='TG_INTERCOMPANY_PAYABLE'?'5100':null,'meta'=>array_merge($meta,['commercialInvoiceNo'=>$b['invoiceNo'],'commercialInvoiceDate'=>$b['invoiceDate'],'customer'=>$party,'invoiceOriginalAmount'=>$b['invoiceAmount'],'receivedBeforeCutoff'=>$b['receivedBefore'],'sourcePakistanEntity'=>$r['entity']]),'createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??$u['username']??'Management')];
 }
 if(isset($s['exportCandidates'][$pid]))$s['exportCandidates'][$pid]+=['linkedCandidateId'=>$cid,'mirrorCandidateId'=>$tid];if(isset($s['exportCandidates'][$tid]))$s['exportCandidates'][$tid]+=['linkedCandidateId'=>$pid,'customerCandidateId'=>$cid];if(isset($s['exportCandidates'][$cid])&&$r['tgPack'])$s['exportCandidates'][$cid]['tgPayableCandidateId']=$tid;
 foreach($r['bills'] as &$b)if(in_array($b['treatment'],['NEW','LINK'],true)&&$b['outstanding']>.005){$key=$id.'|'.$b['id'];$opening=cf_opening($s,$u,$b['entity'],$b['payableAccount'],$b['vendor'],['outstanding'=>$b['outstanding'],'currency'=>$b['currency'],'rate'=>$b['rate'],'mode'=>$b['treatment'],'journalId'=>$b['journalId'],'lineIndex'=>$b['lineIndex']],'Credit',$key,$id);cf_register_bill($s,$r,$b,$opening['journalId'],$u);}elseif($b['treatment']==='PAID')$b['status']='Paid before opening — information only';unset($b);
 $r['status']='Ready for Accounts';$r['publishedAt']=gmdate('c');$r['publishedBy']=(string)($u['full_name']??$u['username']??'Management');
}
function cf_duplicate_bill(array $s,array $b):void {foreach(['supplierBills','freightBillsV1','transportBillsV1','exportServiceBillsV1','bagSupplierBills','otherPurchases','tgLiabilities'] as $list)foreach((array)($s[$list]??[]) as $x)if(($x['entity']??($list==='tgLiabilities'?'TG':''))===$b['entity']&&job_key((string)($x['vendor']??$x['counterparty']??$x['supplier']??''))===job_key($b['vendor'])&&job_key((string)($x['billNo']??$x['invoiceNo']??$x['reference']??$x['sellerInvoice']??''))===job_key($b['invoiceNo']))throw new DomainException('This party invoice is already registered. Use its existing payable.');}
function cf_register_bill(array &$s,array $r,array &$b,string $jid,array $u):void {
 cf_duplicate_bill($s,$b);$id=$r['id'].'-'.$b['id'];$native=$b['outstanding'];$book=round($native*$b['rate'],2);$by=(string)($u['full_name']??$u['username']??'Accounts');
 if($b['entity']==='TG')$s['tgLiabilities'][$id]=['id'=>$id,'entity'=>'TG','date'=>$b['billDate'],'dueDate'=>$b['dueDate'],'counterparty'=>$b['vendor'],'reference'=>$b['invoiceNo'],'currency'=>$b['currency'],'nativeAmount'=>$native,'recognitionRate'=>$b['rate'],'currentCarryingRate'=>$b['rate'],'currentCarryingAsOf'=>$b['treatment']==='CURRENT'?$b['billDate']:CF_CUTOFF,'payableAccount'=>$b['payableAccount'],'debitAccount'=>$b['expenseAccount'],'journalId'=>$jid,'carryForwardShipmentId'=>$r['id'],'createdAt'=>gmdate('c'),'createdBy'=>$by];
 else $s['supplierBills'][$id]=['id'=>$id,'entity'=>$b['entity'],'category'=>$b['kind'],'vendor'=>$b['vendor'],'broker'=>$b['vendor'],'billNo'=>$b['invoiceNo'],'billDate'=>$b['billDate'],'dueDate'=>$b['dueDate']?:$b['billDate'],'payableAccount'=>$b['payableAccount'],'expenseAccount'=>$b['expenseAccount'],'supplierPayableTotal'=>$book,'transactionCurrency'=>$b['currency'],'nativeAmount'=>$native,'receiptAllocations'=>[['sourceKey'=>'CARRY|'.$id,'supplierPayableShare'=>$book,'dueDate'=>$b['dueDate']?:$b['billDate'],'reference'=>$r['contractRef'].' / '.$r['lotRef']]],'sourceRecord'=>['shipmentId'=>$r['operationalShipmentId']?:$r['id'],'shipmentRef'=>$r['lotRef'],'kind'=>$b['kind']],'postingJournalIds'=>[$jid],'status'=>'Outstanding','carryForwardShipmentId'=>$r['id'],'createdAt'=>gmdate('c'),'createdBy'=>$by];
 $b['payableId']=$id;$b['postId']=$jid;$b['status']='Posted — available for payment';
}
function cf_action(array &$s,array $b,array $u):array {
 $action=(string)($b['action']??'');$request=cf_text($b['requestKey']??'',128);if(!preg_match('/^[a-zA-Z0-9._:-]{16,128}$/',$request))throw new DomainException('Reopen the form before saving.');$key=(string)($u['id']??0).'|'.$request;$hash=hash('sha256',json_encode($b));if(isset($s['carryForwardRequests'][$key])){if($s['carryForwardRequests'][$key]['hash']!==$hash)throw new DomainException('This request was already used with different details.');$old=$s['carryForwardRequests'][$key]['result'];cf_access($u,$s['carryForwardShipments'][$old['id']]['entity'],$action!=='post_bill'&&$action!=='add_bill');return $old+['replayed'=>true];}
 $id=cf_text($b['id']??'');$old=$id!==''?($s['carryForwardShipments'][$id]??null):null;if($id!==''&&!is_array($old))throw new DomainException('Shipment record not found.');
 if($action==='save'){
  if($old){cf_access($u,$old['entity'],true);if($old['status']!=='Draft')throw new DomainException('Published opening information is locked. Add later bills below; correct financial postings through Accounts.');if((int)($b['version']??0)!==(int)$old['version'])throw new DomainException('This shipment changed. Reopen before saving.');if(($b['entity']??'')!==$old['entity'])throw new DomainException('Company cannot be changed.');}
  $r=cf_clean($b,$s,$u);if($id==='')$id='CF-'.bin2hex(random_bytes(8));$r+=['id'=>$id,'status'=>'Draft','version'=>(int)($old['version']??0)+1,'createdAt'=>$old['createdAt']??gmdate('c'),'createdBy'=>$old['createdBy']??(string)($u['full_name']??$u['username']??'Management'),'files'=>$old['files']??[]];$s['carryForwardShipments'][$id]=$r;
 }elseif($action==='publish'){
  if(!$old||$old['status']!=='Draft')throw new DomainException('Select a saved draft.');cf_access($u,$old['entity'],true);if($old['tgPack'])cf_access($u,'TG',true);if((int)($b['version']??0)!==(int)$old['version'])throw new DomainException('The draft changed. Reopen before bringing forward.');$r=$old;cf_publish($s,$r,$u);$r['version']++;$s['carryForwardShipments'][$id]=$r;
 }elseif($action==='add_bill'||$action==='post_bill'){
  if(!$old||$old['status']!=='Ready for Accounts')throw new DomainException('Make the shipment available to Accounts first.');$r=$old;
  if($action==='add_bill'){$bill=cf_bill((array)($b['bill']??[]),$r);if($bill['treatment']!=='CURRENT')throw new DomainException('Later bills must use current-year posting.');if(!cf_bill_permission($u,$bill['entity'],$bill['kind']))throw new CfAccessException('Your bill icon and company posting permission are required.');$bill['id']='B'.(count($r['bills'])+1);$r['bills'][]=$bill;}
  else{$found=false;foreach($r['bills'] as &$bill)if($bill['id']===($b['billId']??'')){$found=true;if(!cf_bill_permission($u,$bill['entity'],$bill['kind']))throw new CfAccessException('Your bill icon and company posting permission are required.');if(!empty($bill['payableId'])||$bill['treatment']!=='CURRENT')throw new DomainException('This bill is already posted or is an opening item.');cf_duplicate_bill($s,$bill);$book=round($bill['outstanding']*$bill['rate'],2);$jid=cf_journal($s,$u,$bill['entity'],$bill['billDate'],'CARRY_FORWARD_EXPENSE_BILL',$bill['invoiceNo'],$bill['expenseAccount'],$bill['payableAccount'],$book,'Debit',['counterparty'=>$bill['vendor'],'subledger'=>$bill['vendor'],'currency'=>$bill['entity']==='TG'?$bill['currency']:'PKR','nativeCurrency'=>$bill['entity']==='TG'?$bill['currency']:'PKR','nativeDebit'=>$bill['entity']==='TG'?$bill['outstanding']:$book,'nativeCredit'=>0],['carryForwardShipmentId'=>$id,'supplierBillId'=>$id.'-'.$bill['id'],'kind'=>$bill['kind'],'shipmentId'=>$r['operationalShipmentId']?:$id,'contractRef'=>$r['contractRef'],'lotRef'=>$r['lotRef'],'transactionCurrency'=>$bill['currency'],'transactionAmount'=>$bill['outstanding']]);cf_register_bill($s,$r,$bill,$jid,$u);}unset($bill);if(!$found)throw new DomainException('Bill not found.');}
  $r['version']++;$s['carryForwardShipments'][$id]=$r;
 }else throw new DomainException('Unknown carry-forward action.');
 $s['carryForwardAudit'][]=['at'=>gmdate('c'),'by'=>(string)($u['full_name']??$u['username']??''),'userId'=>(int)($u['id']??0),'action'=>$action,'shipmentId'=>$id,'before'=>$old,'after'=>$s['carryForwardShipments'][$id]];$result=['id'=>$id,'status'=>$s['carryForwardShipments'][$id]['status']];$s['carryForwardRequests'][$key]=['hash'=>$hash,'result'=>$result];return $result;
}
function cf_projection(array $r,array $s,array $u,string $entity):array {
 $manage=cf_management($u,$r['entity'])&&(!$r['tgPack']||cf_management($u,'TG'));$r['bills']=array_values(array_filter($r['bills'],static fn($b)=>$manage||$b['entity']===$entity));foreach($r['bills'] as &$b){$paid=0;$pid=$b['payableId']??'';if($pid!==''){if($b['entity']==='TG'){foreach((array)($s['tgBankTransactions']??[]) as $x)if(($x['kind']??'')==='Payment'&&($x['status']??'')!=='Reversed for Amendment'){foreach((array)($x['liabilityAllocations']??[]) as $a)if(($a['id']??'')===$pid)$paid+=(float)($a['amountNative']??0);if(empty($x['liabilityAllocations'])&&($x['sourceLiabilityId']??'')===$pid)$paid+=(float)($x['amountNative']??0);}}else foreach((array)($s['supplierSettlements']??[]) as $x)if(in_array($x['status']??'',['Posted','Approved / Posted','Approved'],true))foreach((array)($x['allocations']??[]) as $a)if(($a['billId']??'')===$pid)$paid+=(float)($a['amount']??0);}$b['paidAfter']=round($paid,2);$b['paymentOutstanding']=max(0,round(($b['entity']==='TG'?$b['outstanding']:$b['outstanding']*$b['rate'])-$paid,2));$b['canPost']=cf_bill_permission($u,$b['entity'],$b['kind']);}unset($b);
 if(!in_array('TG',cf_entities($u),true)){if($entity!=='TG'){unset($r['tgPayableBalance']);if($r['tgPack'])unset($r['buyerBalance']);}}if($entity==='TG'&&!cf_management($u,$r['entity']))unset($r['pakistanBalance']);
 if(!cf_management($u,$entity)&&!tt_user_can_module_action($u,'Accounts','customer','View')&&!tt_user_can_module_action($u,'Accounts','cashbank','View'))unset($r['buyerBalance']);
 $r['files']=array_values(array_filter((array)($r['files']??[]),static fn($f)=>$manage||($f['entity']??$r['entity'])===$entity));
 $r['realizations']=[];$candidate=($r['tgPack']?$r['pakistanCandidateId']??'':$r['buyerCandidateId']??'')?:$r['id'].'|'.($r['tgPack']?'PAKISTAN':'BUYER');foreach((array)($s['exportReceipts']??[]) as $x)if(($x['entity']??'')===$r['entity']&&in_array($x['status']??'',['Posted','Accounts Approved / Posted'],true)&&empty($x['replacementReceiptId']))foreach((array)($x['allocations']??[]) as $a)if(($a['targetId']??'')===$candidate)$r['realizations'][]=['date'=>$x['date'],'creditAdvice'=>$x['bankAdviceRef']??'','currency'=>$x['transactionCurrency']??'','amount'=>$a['foreignAmount']??0];
 return $r;
}

function cf_value_pending_candidate(array &$s,array $u,string $id,string $entity,string $currency,float $rate):void {
 $c=$s['exportCandidates'][$id]??null;if(!$c||empty($c['pendingValuation']))return;
 if(($c['entity']??'')!==$entity||($c['transactionCurrency']??'')!==$currency)throw new DomainException('Settlement company and currency must match the registered invoice.');
 $rate=cf_rate($rate);$native=cf_number($c['transactionAmount'],false);$type=$c['candidateType'];$account=match($type){'CUSTOMER_EXPORT_SALE'=>'1210','TG_PAKISTAN_INTERCOMPANY'=>'1240','TG_INTERCOMPANY_PAYABLE'=>'2500',default=>throw new DomainException('Unsupported registered invoice.')};$side=$type==='TG_INTERCOMPANY_PAYABLE'?'Credit':'Debit';$amount=round($native*$rate,2);$meta=(array)$c['meta'];$record=$meta['carryForwardShipmentId'];$date=max(CF_CUTOFF,(string)($meta['commercialInvoiceDate']??CF_CUTOFF));
 $jid=cf_journal($s,$u,$entity,$date,'CARRY_FORWARD_OPENING',$c['reference'],$account,'3400',$amount,$side,['counterparty'=>$c['counterparty'],'subledger'=>$c['counterparty'],'candidateId'=>$id,'currency'=>$currency,'nativeCurrency'=>$currency,'nativeDebit'=>$side==='Debit'?$native:0,'nativeCredit'=>$side==='Credit'?$native:0,'rate'=>$rate],['carryForwardShipmentId'=>$record,'candidateId'=>$id,'openingBalance'=>true,'valuationFromSettlement'=>true]);
 $s['exportCandidates'][$id]=array_replace($c,['pendingValuation'=>false,'journalId'=>$jid,'functionalRate'=>$rate,'currentCarryingRate'=>$rate,'functionalAmount'=>$amount,'currentCarryingAsOf'=>$date,'recognitionDate'=>$date,'status'=>'Registered balance valued at settlement']);
}
