<?php
declare(strict_types=1);
require dirname(__DIR__).'/auth_store.php';
require_once __DIR__.'/carry_forward_core.php';
header('Content-Type: application/json; charset=UTF-8');header('Cache-Control: no-store');
function cf_out(array $v,int $status=200):never {http_response_code($status);echo json_encode($v,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function cf_read():array {$path=TT_DATA_DIR.'/accounts.json';if(!is_file($path))return []; $h=fopen($path,'r');if(!$h||!flock($h,LOCK_SH))throw new RuntimeException('Accounts storage unavailable.');try{$raw=stream_get_contents($h);return json_decode($raw?:'{}',true,512,JSON_THROW_ON_ERROR);}finally{flock($h,LOCK_UN);fclose($h);}}
try{
 $u=tt_require_login();$entities=cf_entities($u);if(!$entities)cf_out(['ok'=>false,'error'=>'Accounts or authorised management access is required.'],403);
 if($_SERVER['REQUEST_METHOD']==='GET'){
  $entity=strtoupper((string)($_GET['entity']??$entities[0]));if(!in_array($entity,$entities,true))cf_out(['ok'=>false,'error'=>'Company access required.'],403);$s=cf_read();$id=cf_text($_GET['id']??'');$rows=[];
  foreach((array)($s['carryForwardShipments']??[]) as $r)if(($r['entity']===$entity||($entity==='TG'&&$r['tgPack']))&&($r['status']==='Ready for Accounts'||cf_management($u,$r['entity']))&&($id===''||$id===$r['id']))$rows[]=cf_projection($r,$s,$u,$entity);
  if(isset($_GET['file'])){$fid=cf_text($_GET['file']);$file=null;foreach($rows as $r)foreach((array)($r['files']??[]) as $x)if($x['id']===$fid)$file=$x;if(!$file)cf_out(['ok'=>false,'error'=>'Document not found.'],404);$path=TT_DATA_DIR.'/carry-forward-files/'.$file['id'];if(!is_file($path))throw new RuntimeException('Document unavailable.');header('Content-Type: '.$file['mime']);header('X-Content-Type-Options: nosniff');header('Content-Disposition: attachment; filename="document.'.($file['mime']==='application/pdf'?'pdf':($file['mime']==='image/png'?'png':'jpg')).'"');readfile($path);exit;}
  $masters=tt_list_masters();$parties=[];foreach((array)($masters['business_parties']??[]) as $p)if(strcasecmp((string)($p['values'][10]??'Active'),'Inactive')!==0)$parties[]=['id'=>$p['id'],'name'=>$p['values'][0],'roles'=>tt_business_party_categories($p['values'][2]??'')];$customers=[];foreach((array)($masters['export_customers']??[]) as $p)if(strcasecmp((string)($p['values'][10]??'Active'),'Inactive')!==0)$customers[]=['id'=>$p['id'],'name'=>$p['values'][0]];
  $opening=[];if(cf_management($u,$entity))foreach((array)($s['journals']??[]) as $j)if(($j['entity']??'')===$entity&&($j['date']??'')===CF_CUTOFF&&($j['status']??'')==='Posted'&&in_array($j['sourceType']??'',['OPENING_BALANCE_BF','CARRY_FORWARD_OPENING'],true)&&empty($j['openingReversalId']))foreach((array)($j['lines']??[]) as $i=>$l)if(in_array($l['account']??'',['1210','1240','2500','2130','2140'],true))$opening[]=['journalId'=>$j['id'],'lineIndex'=>$i,'account'=>$l['account'],'party'=>job_party_name($l,(array)($j['meta']??[])),'currency'=>$l['nativeCurrency']??$l['currency']??($entity==='TG'?'AED':'PKR'),'debit'=>$l['debit']??0,'credit'=>$l['credit']??0,'nativeDebit'=>$l['nativeDebit']??$l['debit']??0,'nativeCredit'=>$l['nativeCredit']??$l['credit']??0];
  cf_out(['ok'=>true,'entity'=>$entity,'entities'=>$entities,'canManage'=>cf_management($u,$entity),'canManageTG'=>cf_management($u,'TG'),'canManagePakistan'=>array_values(array_filter(['TTI','BRM'],static fn($e)=>cf_management($u,$e))),'rows'=>$rows,'customers'=>$customers,'parties'=>$parties,'currencies'=>(array)(tt_master_options()['currencies']??[]),'openingLines'=>$opening,'cutoff'=>CF_CUTOFF,'billKinds'=>['FREIGHT','TRANSPORT','CLEARING','FUMIGATION','INSPECTION','BAGS','OTHER'],'canAddBills'=>array_values(array_filter(['FREIGHT','TRANSPORT','CLEARING','FUMIGATION','INSPECTION','BAGS','OTHER'],static fn($k)=>cf_bill_permission($u,$entity,$k)))]);
 }
 if($_SERVER['REQUEST_METHOD']!=='POST')cf_out(['ok'=>false,'error'=>'Method not allowed.'],405);
 $upload=isset($_POST['action'])&&$_POST['action']==='upload';$b=$upload?$_POST:json_decode((function_exists('tt_accounts_input')?tt_accounts_input():file_get_contents('php://input'))?:'{}',true);if(!is_array($b)||!tt_verify_csrf((string)($b['csrf']??'')))cf_out(['ok'=>false,'error'=>'Refresh your session before saving.'],419);
 tt_ensure_data_dir();$h=fopen(TT_DATA_DIR.'/accounts.json','c+');if(!$h||!flock($h,LOCK_EX))throw new RuntimeException('Accounts storage unavailable.');$newFile='';
 try{$raw=stream_get_contents($h);$s=json_decode($raw?:'{}',true,512,JSON_THROW_ON_ERROR);
  if($upload){$id=cf_text($b['id']??'');$r=$s['carryForwardShipments'][$id]??null;if(!$r)throw new DomainException('Save the shipment before adding documents.');cf_access($u,$r['entity'],true);$fileEntity=strtoupper(cf_text($b['entity']??$r['entity'],3));if(!in_array($fileEntity,$r['tgPack']?[$r['entity'],'TG']:[$r['entity']],true))throw new DomainException('Choose the document company.');cf_access($u,$fileEntity,true);if(count($r['files']??[])>=30)throw new DomainException('No more than 30 supporting documents.');$f=$_FILES['file']??[];if(($f['error']??-1)!==UPLOAD_ERR_OK||($f['size']??0)>10*1024*1024||!is_uploaded_file($f['tmp_name']??''))throw new DomainException('Choose a PDF, PNG or JPEG up to 10 MB.');$mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);if(!in_array($mime,['application/pdf','image/png','image/jpeg'],true))throw new DomainException('Only PDF, PNG and JPEG documents are allowed.');$dir=TT_DATA_DIR.'/carry-forward-files';if(!is_dir($dir)&&!mkdir($dir,0700,true))throw new RuntimeException('Document storage unavailable.');$fid=bin2hex(random_bytes(20));$newFile=$dir.'/'.$fid;if(!move_uploaded_file($f['tmp_name'],$newFile))throw new RuntimeException('Document could not be saved.');chmod($newFile,0600);$s['carryForwardShipments'][$id]['files'][]=['id'=>$fid,'entity'=>$fileEntity,'name'=>cf_text(basename($f['name']),200),'mime'=>$mime,'uploadedAt'=>gmdate('c'),'uploadedBy'=>(string)($u['full_name']??$u['username']??'')];$s['carryForwardShipments'][$id]['version']++;$result=['id'=>$id,'status'=>$r['status']];}
  else $result=cf_action($s,$b,$u);
  if(empty($result['replayed'])){$s['revision']=(int)($s['revision']??0)+1;$encoded=json_encode($s,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);rewind($h);if(!ftruncate($h,0)||fwrite($h,$encoded)!==strlen($encoded)||!fflush($h))throw new RuntimeException('Accounts save failed.');}$newFile='';
 }finally{flock($h,LOCK_UN);fclose($h);if($newFile!==''&&is_file($newFile))unlink($newFile);}
 cf_out(['ok'=>true,'result'=>$result]);
}catch(CfAccessException $e){cf_out(['ok'=>false,'error'=>$e->getMessage()],403);}catch(DomainException $e){cf_out(['ok'=>false,'error'=>$e->getMessage()],422);}catch(Throwable $e){error_log('Carry-forward shipments: '.$e->getMessage());cf_out(['ok'=>false,'error'=>'The operation could not be completed. Reopen and review before retrying.'],500);}
