<?php
declare(strict_types=1);
require dirname(__DIR__) . '/auth_store.php';
header('Content-Type: application/json; charset=UTF-8');
header('Cache-Control: no-store, no-cache, must-revalidate');

const DON_FILE = TT_DATA_DIR . '/accounts.json';
const DON_MASTER = __DIR__ . '/../accounts/accounting_master_v1.json';
function don_out(array $d,int $s=200):never{http_response_code($s);echo json_encode($d,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function don_can_write(array $u):bool{if(($u['role']??'')==='Super Admin')return true;$p=$u['permissions']['Accounts']??null;if($p==='all')return true;if(!is_array($p))return false;if(in_array('Create',$p,true)||in_array('Edit',$p,true))return true;foreach($p as $a)if(is_array($a)&&(in_array('Create',$a,true)||in_array('Edit',$a,true)))return true;return false;}
function don_def():array{return ['revision'=>0,'journals'=>[],'bankAccountSettings'=>[],'donations'=>[],'postingKeys'=>[]];}
function don_request_key(mixed $v):string{$key=trim((string)$v);if(!preg_match('/^[A-Za-z0-9._:-]{8,128}$/',$key))don_out(['ok'=>false,'error'=>'A valid request key is required. Refresh and try again.'],422);return $key;}
function don_fingerprint(array $v):string{ksort($v);return hash('sha256',json_encode($v,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));}
function don_read():array{tt_ensure_data_dir();if(!is_file(DON_FILE))return don_def();$h=fopen(DON_FILE,'r');if($h===false||!flock($h,LOCK_SH))throw new RuntimeException('Accounts storage unavailable.');try{$raw=stream_get_contents($h);}finally{flock($h,LOCK_UN);fclose($h);}$v=$raw?json_decode($raw,true):null;return is_array($v)?array_replace_recursive(don_def(),$v):don_def();}
function don_entity(string $v):string{$v=strtoupper(trim($v));if(!in_array($v,['TTI','BRM','TG'],true))don_out(['ok'=>false,'error'=>'Select a valid legal entity.'],422);return $v;}
function don_type(string $v):string{$v=strtoupper(trim($v));if(!in_array($v,['ZAKAT','SADQA','FI_SABILILLAH'],true))don_out(['ok'=>false,'error'=>'Select Zakat, Sadqa or Fi Sabilillah.'],422);return $v;}
function don_type_name(string $v):string{return match($v){'ZAKAT'=>'Zakat','SADQA'=>'Sadqa','FI_SABILILLAH'=>'Fi Sabilillah',default=>$v};}
function don_account(string $v):string{return match($v){'ZAKAT'=>'7210','SADQA'=>'7220','FI_SABILILLAH'=>'7230',default=>throw new RuntimeException('Donation account unavailable.')};}
function don_date(string $v):string{if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$v))don_out(['ok'=>false,'error'=>'Payment date is required.'],422);return $v;}
function don_amount(mixed $v):float{$n=round((float)$v,2);if($n<=0)don_out(['ok'=>false,'error'=>'Amount must be greater than zero.'],422);return $n;}
function don_names():array{$raw=is_file(DON_MASTER)?file_get_contents(DON_MASTER):false;$m=$raw?json_decode($raw,true):null;if(!is_array($m))throw new RuntimeException('Accounting master unavailable.');$o=[];foreach((array)($m['chart']??[])as$a)if(is_array($a)&&isset($a['code']))$o[(string)$a['code']]=(string)($a['name']??$a['code']);return $o;}
function don_line(string $a,float $dr,float $cr,array $names,array $extra=[]):array{if(!isset($names[$a]))don_out(['ok'=>false,'error'=>'Approved account '.$a.' is unavailable.'],422);return array_merge(['account'=>$a,'accountName'=>$names[$a],'debit'=>round($dr,2),'credit'=>round($cr,2)],$extra);}
function don_banks():array{$masters=tt_list_masters();$out=[];foreach((array)($masters['banks']??[])as$row){if(!is_array($row))continue;$v=array_values((array)($row['values']??[]));while(count($v)<14)$v[]='';$linked=strtoupper((string)$v[1]);$entity=str_contains($linked,'BRM')||str_contains($linked,'BUKSH RICE')?'BRM':(str_contains($linked,'TTI')||str_contains($linked,'TRANSTRADE INTERNATIONAL')?'TTI':(str_contains($linked,'TG')||str_contains($linked,'TRANS GRAINS')?'TG':''));if($entity==='')continue;$out[(string)($row['id']??'')]=['id'=>(string)($row['id']??''),'entity'=>$entity,'accountType'=>(string)$v[0],'accountTitle'=>(string)$v[3],'bankName'=>(string)$v[4],'currency'=>strtoupper(trim((string)$v[7])),'accountNumber'=>(string)$v[8]];}return $out;}
function don_balance(array $s,string $entity,string $account,string $bankId=''):float{$n=0;foreach((array)$s['journals']as$j){if(!is_array($j)||($j['status']??'')!=='Posted'||($j['entity']??'')!==$entity)continue;$jm=is_array($j['meta']??null)?$j['meta']:[];foreach((array)($j['lines']??[])as$l){if(!is_array($l)||($l['account']??'')!==$account)continue;if($bankId!==''&&(string)($l['bankAccountId']??$jm['bankAccountId']??'')!==$bankId)continue;$n+=(float)($l['debit']??0)-(float)($l['credit']??0);}}return round($n,2);}
function don_payment_accounts(array $s,string $entity):array{$o=[];foreach(don_banks()as$id=>$a){$expected=$entity==='TG'?'AED':'PKR';if(($a['entity']??'')!==$entity||($a['accountType']??'')!=='Company Account'||($a['currency']??'')!==$expected)continue;$set=is_array($s['bankAccountSettings'][$id]??null)?$s['bankAccountSettings'][$id]:[];if(empty($set['active'])||empty($set['allowPayments']))continue;$digits=preg_replace('/\D+/','',(string)$a['accountNumber'])??'';$o[]=['id'=>$id,'label'=>trim((string)$a['bankName']).($digits!==''?' — '.substr($digits,-5):''),'currency'=>$expected,'bookBalance'=>don_balance($s,$entity,'1110',$id)];}$cash='CASH|'.$entity;$set=is_array($s['bankAccountSettings'][$cash]??null)?$s['bankAccountSettings'][$cash]:['active'=>true,'allowPayments'=>true];if(!empty($set['active'])&&!empty($set['allowPayments']))$o[]=['id'=>$cash,'label'=>'Cash / Petty Cash','bookBalance'=>don_balance($s,$entity,'1120')];return $o;}
function don_pay_line(array $s,string $entity,string $id,float $amt,array $names):array{if($id==='CASH|'.$entity)return don_line('1120',0,$amt,$names,['paymentAccountId'=>$id,'paymentType'=>'Cash']);$a=don_banks()[$id]??null;$expected=$entity==='TG'?'AED':'PKR';if(!is_array($a)||($a['entity']??'')!==$entity||($a['accountType']??'')!=='Company Account'||($a['currency']??'')!==$expected)don_out(['ok'=>false,'error'=>'Select a valid '.$expected.' company bank account.'],422);$set=is_array($s['bankAccountSettings'][$id]??null)?$s['bankAccountSettings'][$id]:[];if(empty($set['active'])||empty($set['allowPayments']))don_out(['ok'=>false,'error'=>'This bank account is not enabled for payments.'],422);return don_line('1110',0,$amt,$names,['bankAccountId'=>$id,'bankName'=>$a['bankName'],'accountTitle'=>$a['accountTitle'],'currency'=>$expected]);}
function don_next(array $items,string $prefix):string{$n=count($items)+1;do{$id=$prefix.'-'.gmdate('Y').'-'.str_pad((string)$n,6,'0',STR_PAD_LEFT);$n++;}while(isset($items[$id]));return $id;}
function don_payload(array $s,string $entity):array{$rows=[];$totals=['ZAKAT'=>0.0,'SADQA'=>0.0,'FI_SABILILLAH'=>0.0];foreach((array)$s['donations']as$d){if(!is_array($d)||($d['entity']??'')!==$entity)continue;$rows[]=$d;$type=(string)($d['type']??'');if(isset($totals[$type]))$totals[$type]=round($totals[$type]+(float)($d['amount']??0),2);}usort($rows,static fn($a,$b)=>strcmp((string)($b['date']??''),(string)($a['date']??''))?:strcmp((string)($b['id']??''),(string)($a['id']??'')));return ['ok'=>true,'entity'=>$entity,'donations'=>$rows,'totals'=>$totals,'paymentAccounts'=>don_payment_accounts($s,$entity),'serverNow'=>gmdate('c')];}

try{
$u=tt_require_login();if(!tt_user_can_open_module($u,'Accounts'))don_out(['ok'=>false,'error'=>'Accounts permission required.'],403);$entity=don_entity((string)($_GET['entity']??'TTI'));if(!tt_user_can_access_entity($u,$entity,'View'))don_out(['ok'=>false,'error'=>'You do not have permission for this legal entity.'],403);if($_SERVER['REQUEST_METHOD']==='GET')don_out(don_payload(don_read(),$entity));if($_SERVER['REQUEST_METHOD']!=='POST')don_out(['ok'=>false,'error'=>'Method not allowed.'],405);if(!don_can_write($u))don_out(['ok'=>false,'error'=>'Accounts Create or Edit permission required.'],403);$b=json_decode(file_get_contents('php://input')?:'{}',true);if(!is_array($b)||!tt_verify_csrf((string)($b['csrf']??'')))don_out(['ok'=>false,'error'=>'Your session expired. Refresh and try again.'],419);$entity=don_entity((string)($b['entity']??$entity));if(!(tt_user_can_access_entity($u,$entity,'Create')||tt_user_can_access_entity($u,$entity,'Edit')))don_out(['ok'=>false,'error'=>'You do not have permission to update this legal entity.'],403);if(($b['action']??'')!=='record_donation')don_out(['ok'=>false,'error'=>'Unknown donation action.'],422);$type=don_type((string)($b['type']??''));$date=don_date((string)($b['date']??''));$amount=don_amount($b['amount']??0);$payee=trim((string)($b['payee']??''));if($payee==='')don_out(['ok'=>false,'error'=>'Beneficiary / payee is required.'],422);$paymentId=trim((string)($b['paymentAccountId']??''));$notes=trim((string)($b['notes']??''));$requestKey=don_request_key($b['requestKey']??'');$fingerprint=don_fingerprint(['entity'=>$entity,'type'=>$type,'date'=>$date,'amount'=>$amount,'payee'=>$payee,'paymentAccountId'=>$paymentId,'notes'=>$notes]);
tt_ensure_data_dir();$h=fopen(DON_FILE,'c+');if($h===false||!flock($h,LOCK_EX))throw new RuntimeException('Accounts storage unavailable.');try{rewind($h);$raw=stream_get_contents($h);$s=$raw?json_decode($raw,true):null;if(!is_array($s))$s=don_def();$s=array_replace_recursive(don_def(),$s);$postingKey=$entity.'|DONATION|'.$requestKey;$prior=is_array($s['postingKeys'][$postingKey]??null)?$s['postingKeys'][$postingKey]:null;if($prior!==null){if(!hash_equals((string)($prior['fingerprint']??''),$fingerprint))don_out(['ok'=>false,'error'=>'This request key was already used for a different donation.'],409);don_out(don_payload($s,$entity)+['result'=>['donationId'=>(string)($prior['donationId']??''),'journalId'=>(string)($prior['journalId']??''),'duplicate'=>true],'revision'=>(int)($s['revision']??0)]);}$names=don_names();$id=don_next((array)$s['donations'],'DON');$jid=don_next((array)$s['journals'],'AUTO');$meta=['donationId'=>$id,'donationType'=>$type,'beneficiary'=>$payee,'paymentAccountId'=>$paymentId];$lines=[don_line(don_account($type),$amount,0,$names,$meta),don_pay_line($s,$entity,$paymentId,$amount,$names)];$s['journals'][$jid]=['id'=>$jid,'entity'=>$entity,'date'=>$date,'sourceType'=>'DONATION_PAYMENT','reference'=>$id,'narration'=>don_type_name($type).' — '.$payee,'lines'=>$lines,'totalDebit'=>$amount,'totalCredit'=>$amount,'status'=>'Posted','meta'=>$meta,'createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??$u['username']??'Accounts'),'userId'=>(int)($u['id']??0),'reversalOf'=>null];$s['donations'][$id]=['id'=>$id,'entity'=>$entity,'type'=>$type,'typeName'=>don_type_name($type),'date'=>$date,'payee'=>$payee,'amount'=>$amount,'paymentAccountId'=>$paymentId,'notes'=>$notes,'requestKey'=>$requestKey,'journalId'=>$jid,'createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??$u['username']??'Accounts')];$s['postingKeys'][$postingKey]=['fingerprint'=>$fingerprint,'donationId'=>$id,'journalId'=>$jid,'createdAt'=>gmdate('c')];$s['revision']=(int)($s['revision']??0)+1;rewind($h);ftruncate($h,0);fwrite($h,json_encode($s,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($h);}finally{flock($h,LOCK_UN);fclose($h);}don_out(don_payload($s,$entity)+['result'=>['donationId'=>$id,'journalId'=>$jid],'revision'=>$s['revision']]);
}catch(Throwable $e){don_out(['ok'=>false,'error'=>'Donation update could not be completed.'],500);}

