<?php
declare(strict_types=1);
require dirname(__DIR__) . '/auth_store.php';
header('Content-Type: application/json; charset=UTF-8');
header('Cache-Control: no-store, no-cache, must-revalidate');

const EV1_FILE = TT_DATA_DIR . '/accounts.json';
const EV1_MASTER = __DIR__ . '/../accounts/accounting_master_v1.json';

function ev1_out(array $data,int $status=200):never{http_response_code($status);echo json_encode($data,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function ev1_def():array{return ['revision'=>0,'journals'=>[],'bankAccountSettings'=>[],'utilityMasters'=>[],'utilityPayments'=>[],'creditCardMasters'=>[],'creditCardStatements'=>[],'reimbursements'=>[],'generalExpenses'=>[],'postingKeys'=>[]];}
function ev1_request_key(mixed $v):string{$key=trim((string)$v);if(!preg_match('/^[A-Za-z0-9._:-]{8,128}$/',$key))ev1_out(['ok'=>false,'error'=>'A valid request key is required. Refresh and try again.'],422);return $key;}
function ev1_canonical(mixed $v):mixed{if(!is_array($v))return $v;foreach($v as $k=>$item)$v[$k]=ev1_canonical($item);ksort($v);return $v;}
function ev1_fingerprint(array $body):string{unset($body['csrf'],$body['requestKey']);return hash('sha256',json_encode(ev1_canonical($body),JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));}
function ev1_read():array{tt_ensure_data_dir();if(!is_file(EV1_FILE))return ev1_def();$h=fopen(EV1_FILE,'r');if($h===false||!flock($h,LOCK_SH))throw new RuntimeException('Accounts storage unavailable.');try{$raw=stream_get_contents($h);}finally{flock($h,LOCK_UN);fclose($h);}$s=$raw?json_decode($raw,true):null;return is_array($s)?array_replace_recursive(ev1_def(),$s):ev1_def();}
function ev1_can_write(array $u):bool{if(($u['role']??'')==='Super Admin')return true;$p=$u['permissions']['Accounts']??null;if($p==='all')return true;if(!is_array($p))return false;if(in_array('Create',$p,true)||in_array('Edit',$p,true)||in_array('Approve',$p,true))return true;foreach($p as $a)if(is_array($a)&&(in_array('Create',$a,true)||in_array('Edit',$a,true)||in_array('Approve',$a,true)))return true;return false;}
function ev1_require_entity(array $u,string $entity,bool $write=false):void{if(($u['role']??'')==='Super Admin')return;$allowed=$write?(tt_user_can_access_entity($u,$entity,'Create')||tt_user_can_access_entity($u,$entity,'Edit')||tt_user_can_access_entity($u,$entity,'Approve')):tt_user_can_access_entity($u,$entity,'View');if(!$allowed)ev1_out(['ok'=>false,'error'=>'You do not have permission for this legal entity.'],403);}
function ev1_entity(string $v):string{$v=strtoupper(trim($v));if(!in_array($v,['TTI','BRM','TG'],true))ev1_out(['ok'=>false,'error'=>'Select a valid legal entity.'],422);return $v;}
function ev1_date(string $v,string $label='Date'):string{$d=DateTimeImmutable::createFromFormat('!Y-m-d',$v);$e=DateTimeImmutable::getLastErrors();if(!$d||($e!==false&&(($e['warning_count']??0)>0||($e['error_count']??0)>0))||$d->format('Y-m-d')!==$v)ev1_out(['ok'=>false,'error'=>$label.' is invalid.'],422);return $v;}
function ev1_month(string $v):string{if(!preg_match('/^\d{4}-\d{2}$/',$v))ev1_out(['ok'=>false,'error'=>'Select a valid month.'],422);return $v;}
function ev1_amount(mixed $v,string $label='Amount'):float{$n=round((float)$v,2);if($n<=0)ev1_out(['ok'=>false,'error'=>$label.' must be greater than zero.'],422);return $n;}
function ev1_day(mixed $v,string $label='Due day'):int{$n=(int)$v;if($n<1||$n>31)ev1_out(['ok'=>false,'error'=>$label.' must be between 1 and 31.'],422);return $n;}
function ev1_id(array $items,string $prefix):string{$n=count($items)+1;do{$id=$prefix.'-'.gmdate('Y').'-'.str_pad((string)$n,6,'0',STR_PAD_LEFT);$n++;}while(isset($items[$id]));return $id;}
function ev1_names():array{$raw=is_file(EV1_MASTER)?file_get_contents(EV1_MASTER):false;$m=$raw?json_decode($raw,true):null;if(!is_array($m))throw new RuntimeException('Accounting master unavailable.');$out=[];foreach(array_merge((array)($m['chart']??[]),(array)($m['peopleSubledgers']??[]))as$a)if(is_array($a)&&isset($a['code']))$out[(string)$a['code']]=(string)($a['name']??$a['code']);return $out;}
function ev1_line(string $account,float $debit,float $credit,array $names,array $meta=[]):array{if(!isset($names[$account]))ev1_out(['ok'=>false,'error'=>'Approved account '.$account.' is unavailable.'],422);return array_merge(['account'=>$account,'accountName'=>$names[$account],'debit'=>round($debit,2),'credit'=>round($credit,2)],$meta);}
function ev1_utility_type(string $v):string{$v=strtoupper(trim($v));$ok=['ELECTRICITY','GAS','WATER','INTERNET','TELEPHONE_MOBILE','CLUB','OTHER_UTILITY'];if(!in_array($v,$ok,true))ev1_out(['ok'=>false,'error'=>'Select a valid recurring bill type.'],422);return $v;}
function ev1_utility_name(string $v):string{return match($v){'ELECTRICITY'=>'Electricity','GAS'=>'Gas','WATER'=>'Water','INTERNET'=>'Internet','TELEPHONE_MOBILE'=>'Telephone / Mobile','CLUB'=>'Club Bill','OTHER_UTILITY'=>'Other Utility',default=>$v};}
function ev1_utility_account(string $v):string{return match($v){'ELECTRICITY'=>'6110','GAS'=>'6120','WATER'=>'6130','INTERNET'=>'6140','TELEPHONE_MOBILE'=>'6150','CLUB','OTHER_UTILITY'=>'6190',default=>throw new RuntimeException('Utility account unavailable.')};}
function ev1_location(string $v):string{$v=strtoupper(trim($v));if(!in_array($v,['MILL','OFFICE','HOME','OTHER'],true))ev1_out(['ok'=>false,'error'=>'Select Mill, Office, Home or Other location.'],422);return $v;}
function ev1_person(string $v):string{$v=strtoupper(trim($v));$ok=['FAM-SALMAN','FAM-TALHA','FAM-ABU','FAM-TAYYAB'];if(!in_array($v,$ok,true))ev1_out(['ok'=>false,'error'=>'Select Salman, Talha, Abu or Tayyab for the personal allocation.'],422);return $v;}
function ev1_business_account(string $v):string{$ok=['6110','6120','6130','6140','6150','6190','6400','6500','6600','6700','6800','6900'];if(!in_array($v,$ok,true))ev1_out(['ok'=>false,'error'=>'Select an approved business expense account.'],422);return $v;}
function ev1_reimbursement_person(string $v):string{$v=strtoupper(trim($v));$ok=['REIMB-SALMAN','REIMB-TALHA','REIMB-ABU','REIMB-TAYYAB'];if(!in_array($v,$ok,true))ev1_out(['ok'=>false,'error'=>'Select Salman, Talha, Abu or Tayyab for reimbursement.'],422);return $v;}
function ev1_general_location(string $v):string{$v=strtoupper(trim($v));if(!in_array($v,['MILL','OFFICE','OTHER'],true))ev1_out(['ok'=>false,'error'=>'Select Mill, Office or Other business location.'],422);return $v;}
function ev1_banks():array{$masters=tt_list_masters();$out=[];foreach((array)($masters['banks']??[])as$row){if(!is_array($row))continue;$v=array_values((array)($row['values']??[]));while(count($v)<14)$v[]='';$linked=strtoupper((string)$v[1]);$entity=str_contains($linked,'BRM')||str_contains($linked,'BUKSH RICE')?'BRM':(str_contains($linked,'TTI')||str_contains($linked,'TRANSTRADE INTERNATIONAL')?'TTI':(str_contains($linked,'TG')||str_contains($linked,'TRANS GRAINS')?'TG':''));if($entity==='')continue;$out[(string)($row['id']??'')]=['id'=>(string)($row['id']??''),'entity'=>$entity,'accountType'=>(string)$v[0],'accountTitle'=>(string)$v[3],'bankName'=>(string)$v[4],'currency'=>strtoupper(trim((string)$v[7])),'accountNumber'=>(string)$v[8]];}return $out;}
function ev1_balance(array $s,string $entity,string $account,string $bankId=''):float{$n=0;foreach((array)$s['journals']as$j){if(!is_array($j)||($j['status']??'')!=='Posted'||($j['entity']??'')!==$entity)continue;$jm=is_array($j['meta']??null)?$j['meta']:[];foreach((array)($j['lines']??[])as$l){if(!is_array($l)||($l['account']??'')!==$account)continue;if($bankId!==''&&(string)($l['bankAccountId']??$jm['bankAccountId']??'')!==$bankId)continue;$n+=(float)($l['debit']??0)-(float)($l['credit']??0);}}return round($n,2);}
function ev1_payment_accounts(array $s,string $entity):array{$out=[];foreach(ev1_banks()as$id=>$a){if(($a['entity']??'')!==$entity||($a['accountType']??'')!=='Company Account')continue;$currency=(string)($a['currency']??'');$expected=$entity==='TG'?'AED':'PKR';if($currency!==$expected)continue;$set=is_array($s['bankAccountSettings'][$id]??null)?$s['bankAccountSettings'][$id]:[];if(empty($set['active'])||empty($set['allowPayments']))continue;$digits=preg_replace('/\D+/','',(string)$a['accountNumber'])??'';$out[]=['id'=>$id,'label'=>trim((string)$a['bankName']).($digits!==''?' — '.substr($digits,-5):''),'currency'=>$currency,'bookBalance'=>ev1_balance($s,$entity,'1110',$id)];}$cash='CASH|'.$entity;$set=is_array($s['bankAccountSettings'][$cash]??null)?$s['bankAccountSettings'][$cash]:['active'=>true,'allowPayments'=>true];if(!empty($set['active'])&&!empty($set['allowPayments']))$out[]=['id'=>$cash,'label'=>'Cash / Petty Cash','currency'=>$entity==='TG'?'AED':'PKR','bookBalance'=>ev1_balance($s,$entity,'1120')];return $out;}
function ev1_pay_line(array $s,string $entity,string $id,float $amount,array $names):array{if($id==='CASH|'.$entity)return ev1_line('1120',0,$amount,$names,['paymentAccountId'=>$id,'paymentType'=>'Cash']);$a=ev1_banks()[$id]??null;$expected=$entity==='TG'?'AED':'PKR';if(!is_array($a)||($a['entity']??'')!==$entity||($a['accountType']??'')!=='Company Account'||($a['currency']??'')!==$expected)ev1_out(['ok'=>false,'error'=>'Select a valid '.$expected.' company bank account.'],422);$set=is_array($s['bankAccountSettings'][$id]??null)?$s['bankAccountSettings'][$id]:[];if(empty($set['active'])||empty($set['allowPayments']))ev1_out(['ok'=>false,'error'=>'This bank account is not enabled for payments.'],422);return ev1_line('1110',0,$amount,$names,['bankAccountId'=>$id,'bankName'=>$a['bankName'],'accountTitle'=>$a['accountTitle'],'currency'=>$a['currency']]);}
function ev1_journal(array &$s,string $entity,string $date,string $source,string $reference,string $narration,array $lines,array $u,array $meta=[]):string{$dr=round(array_sum(array_map(static fn($l)=>(float)($l['debit']??0),$lines)),2);$cr=round(array_sum(array_map(static fn($l)=>(float)($l['credit']??0),$lines)),2);if($dr<=0||abs($dr-$cr)>.005)throw new RuntimeException('Journal did not balance.');$id=ev1_id((array)$s['journals'],'AUTO');$s['journals'][$id]=['id'=>$id,'entity'=>$entity,'date'=>$date,'sourceType'=>$source,'reference'=>$reference,'narration'=>$narration,'lines'=>$lines,'totalDebit'=>$dr,'totalCredit'=>$cr,'status'=>'Posted','meta'=>$meta,'createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??$u['username']??'Accounts'),'userId'=>(int)($u['id']??0),'reversalOf'=>null];return $id;}
function ev1_due_date(string $month,int $day):string{$first=new DateTimeImmutable($month.'-01');$last=(int)$first->modify('last day of this month')->format('d');return $month.'-'.str_pad((string)min($day,$last),2,'0',STR_PAD_LEFT);}
function ev1_allocations(mixed $input,float $total,array $names):array{if(!is_array($input)||$input===[])ev1_out(['ok'=>false,'error'=>'Allocate the complete credit-card statement.'],422);$out=[];$sum=0.0;foreach($input as$i=>$a){if(!is_array($a))continue;$kind=strtoupper(trim((string)($a['kind']??'')));$amount=ev1_amount($a['amount']??0,'Allocation amount');$detail=trim((string)($a['detail']??''));if($detail==='')ev1_out(['ok'=>false,'error'=>'Enter details for every card allocation.'],422);if($kind==='PERSONAL'){$account=ev1_person((string)($a['personAccount']??''));}elseif($kind==='BUSINESS'){$account=ev1_business_account((string)($a['expenseAccount']??''));}else ev1_out(['ok'=>false,'error'=>'Select Business Expense or Personal / Family Allocation.'],422);if(!isset($names[$account]))ev1_out(['ok'=>false,'error'=>'Allocation account '.$account.' is unavailable.'],422);$out[]=['line'=>(int)$i+1,'kind'=>$kind,'account'=>$account,'accountName'=>$names[$account],'detail'=>$detail,'amount'=>$amount];$sum=round($sum+$amount,2);}if(abs($sum-$total)>.005)ev1_out(['ok'=>false,'error'=>'Credit-card allocations must equal the full statement total.'],422);return $out;}
function ev1_payload(array $s,string $entity,string $month):array{$utilityMasters=[];$utilityPayments=[];$cards=[];$statements=[];$reimbursements=[];$generalExpenses=[];foreach((array)$s['utilityMasters']as$m)if(is_array($m)&&($m['entity']??'')===$entity)$utilityMasters[]=$m;foreach((array)$s['utilityPayments']as$p)if(is_array($p)&&($p['entity']??'')===$entity)$utilityPayments[]=$p;foreach((array)$s['creditCardMasters']as$c)if(is_array($c)&&($c['entity']??'')===$entity)$cards[]=$c;foreach((array)$s['creditCardStatements']as$st)if(is_array($st)&&($st['entity']??'')===$entity)$statements[]=$st;foreach((array)$s['reimbursements']as$r)if(is_array($r)&&($r['entity']??'')===$entity)$reimbursements[]=$r;foreach((array)$s['generalExpenses']as$g)if(is_array($g)&&($g['entity']??'')===$entity)$generalExpenses[]=$g;usort($utilityPayments,static fn($a,$b)=>strcmp((string)($b['paymentDate']??''),(string)($a['paymentDate']??''))?:strcmp((string)($b['id']??''),(string)($a['id']??'')));usort($statements,static fn($a,$b)=>strcmp((string)($b['dueDate']??''),(string)($a['dueDate']??''))?:strcmp((string)($b['id']??''),(string)($a['id']??'')));usort($reimbursements,static fn($a,$b)=>strcmp((string)($b['expenseDate']??''),(string)($a['expenseDate']??''))?:strcmp((string)($b['id']??''),(string)($a['id']??'')));usort($generalExpenses,static fn($a,$b)=>strcmp((string)($b['paymentDate']??''),(string)($a['paymentDate']??''))?:strcmp((string)($b['id']??''),(string)($a['id']??'')));$reminders=[];foreach($utilityMasters as$m){if(($m['status']??'Active')!=='Active')continue;$paid=false;foreach($utilityPayments as$p)if(($p['utilityMasterId']??'')===($m['id']??'')&&($p['billMonth']??'')===$month){$paid=true;break;}$due=ev1_due_date($month,(int)($m['dueDay']??1));$reminders[]=['type'=>'UTILITY','masterId'=>$m['id'],'label'=>ev1_utility_name((string)$m['utilityType']).' — '.(string)$m['locationName'],'dueDate'=>$due,'status'=>$paid?'Paid':($due<gmdate('Y-m-d')?'Overdue':'Due'),'paid'=>$paid];}foreach($statements as$st)if(($st['status']??'Pending')!=='Paid')$reminders[]=['type'=>'CREDIT_CARD','statementId'=>$st['id'],'label'=>(string)$st['cardName'].' — '.(string)$st['statementMonth'],'dueDate'=>$st['dueDate'],'status'=>$st['dueDate']<gmdate('Y-m-d')?'Overdue':'Due','paid'=>false,'amount'=>$st['total']];usort($reminders,static fn($a,$b)=>strcmp((string)$a['dueDate'],(string)$b['dueDate']));return ['ok'=>true,'entity'=>$entity,'month'=>$month,'utilityMasters'=>$utilityMasters,'utilityPayments'=>$utilityPayments,'creditCardMasters'=>$cards,'creditCardStatements'=>$statements,'reimbursements'=>$reimbursements,'generalExpenses'=>$generalExpenses,'reminders'=>$reminders,'paymentAccounts'=>ev1_payment_accounts($s,$entity),'serverNow'=>gmdate('c')];}

try{
$u=tt_require_login();if(!tt_user_can_open_module($u,'Accounts'))ev1_out(['ok'=>false,'error'=>'Accounts permission required.'],403);$entity=ev1_entity((string)($_GET['entity']??'TTI'));ev1_require_entity($u,$entity,false);$month=ev1_month((string)($_GET['month']??gmdate('Y-m')));if($_SERVER['REQUEST_METHOD']==='GET')ev1_out(ev1_payload(ev1_read(),$entity,$month));if($_SERVER['REQUEST_METHOD']!=='POST')ev1_out(['ok'=>false,'error'=>'Method not allowed.'],405);if(!ev1_can_write($u))ev1_out(['ok'=>false,'error'=>'Accounts Create, Edit or Approve permission required.'],403);$b=json_decode(file_get_contents('php://input')?:'{}',true);if(!is_array($b)||!tt_verify_csrf((string)($b['csrf']??'')))ev1_out(['ok'=>false,'error'=>'Your session expired. Refresh and try again.'],419);$entity=ev1_entity((string)($b['entity']??$entity));ev1_require_entity($u,$entity,true);$month=ev1_month((string)($b['month']??$month));$action=(string)($b['action']??'');tt_ensure_data_dir();$h=fopen(EV1_FILE,'c+');if($h===false||!flock($h,LOCK_EX))throw new RuntimeException('Accounts storage unavailable.');try{rewind($h);$raw=stream_get_contents($h);$s=$raw?json_decode($raw,true):null;if(!is_array($s))$s=ev1_def();$s=array_replace_recursive(ev1_def(),$s);$names=ev1_names();$result=[];$postingKey=null;$fingerprint=null;$postingActions=['pay_utility','capture_reimbursement','settle_reimbursement','pay_general_expense','pay_export_expense','pay_card_statement'];if(in_array($action,$postingActions,true)){$requestKey=ev1_request_key($b['requestKey']??'');$fingerprint=ev1_fingerprint($b);$postingKey=$entity.'|EXPENSES|'.$action.'|'.$requestKey;$prior=is_array($s['postingKeys'][$postingKey]??null)?$s['postingKeys'][$postingKey]:null;if($prior!==null){if(!hash_equals((string)($prior['fingerprint']??''),(string)$fingerprint))ev1_out(['ok'=>false,'error'=>'This request key was already used for a different expense transaction.'],409);ev1_out(ev1_payload($s,$entity,$month)+['result'=>(array)($prior['result']??[])+['duplicate'=>true],'revision'=>(int)($s['revision']??0)]);}}

if($action==='save_utility_master'){
$id=trim((string)($b['id']??''));$type=ev1_utility_type((string)($b['utilityType']??''));$location=ev1_location((string)($b['location']??''));$locationName=trim((string)($b['locationName']??''));$payee=trim((string)($b['payee']??''));$accountRef=trim((string)($b['accountReference']??''));$dueDay=ev1_day($b['dueDay']??0);if($locationName===''||$payee==='')ev1_out(['ok'=>false,'error'=>'Location name and utility provider are required.'],422);if($id==='')$id=ev1_id((array)$s['utilityMasters'],'UTM');$old=$s['utilityMasters'][$id]??null;if($old!==null&&(!is_array($old)||($old['entity']??'')!==$entity))ev1_out(['ok'=>false,'error'=>'Utility reminder not found in this legal entity.'],404);$s['utilityMasters'][$id]=array_merge(is_array($old)?$old:[],['id'=>$id,'entity'=>$entity,'utilityType'=>$type,'utilityTypeName'=>ev1_utility_name($type),'location'=>$location,'locationName'=>$locationName,'payee'=>$payee,'accountReference'=>$accountRef,'dueDay'=>$dueDay,'status'=>'Active','notes'=>trim((string)($b['notes']??'')),'updatedAt'=>gmdate('c'),'updatedBy'=>(string)($u['full_name']??'Accounts')]);if(!is_array($old)){$s['utilityMasters'][$id]['createdAt']=gmdate('c');$s['utilityMasters'][$id]['createdBy']=(string)($u['full_name']??'Accounts');}$result=['utilityMasterId'=>$id];
}
elseif($action==='deactivate_utility_master'){
$id=trim((string)($b['id']??''));$m=$s['utilityMasters'][$id]??null;if(!is_array($m)||($m['entity']??'')!==$entity)ev1_out(['ok'=>false,'error'=>'Utility reminder not found.'],404);$s['utilityMasters'][$id]['status']='Inactive';$s['utilityMasters'][$id]['updatedAt']=gmdate('c');$result=['utilityMasterId'=>$id,'status'=>'Inactive'];
}
elseif($action==='pay_utility'){
$type=ev1_utility_type((string)($b['utilityType']??''));$location=ev1_location((string)($b['location']??''));$locationName=trim((string)($b['locationName']??''));$payee=trim((string)($b['payee']??''));$billMonth=ev1_month((string)($b['billMonth']??$month));$date=ev1_date((string)($b['paymentDate']??''),'Payment date');$amount=ev1_amount($b['amount']??0);$paymentId=trim((string)($b['paymentAccountId']??''));$reference=trim((string)($b['reference']??''));$masterId=trim((string)($b['utilityMasterId']??''));$treatment=strtoupper(trim((string)($b['accountingTreatment']??($location==='HOME'?'FAMILY_ALLOCATION':'BUSINESS_EXPENSE'))));if($locationName===''||$payee==='')ev1_out(['ok'=>false,'error'=>'Location name and utility provider are required.'],422);if(!in_array($treatment,['BUSINESS_EXPENSE','FAMILY_ALLOCATION'],true))ev1_out(['ok'=>false,'error'=>'Select Business Expense or Personal / Family Allocation.'],422);if($masterId!==''){$m=$s['utilityMasters'][$masterId]??null;if(!is_array($m)||($m['entity']??'')!==$entity)ev1_out(['ok'=>false,'error'=>'Utility reminder not found in this legal entity.'],404);}if($reference!=='')foreach((array)$s['utilityPayments']as$old)if(is_array($old)&&($old['entity']??'')===$entity&&strcasecmp((string)($old['reference']??''),$reference)===0&&strcasecmp((string)($old['payee']??''),$payee)===0)ev1_out(['ok'=>false,'error'=>'This utility reference is already recorded for the provider.'],409);$account=$treatment==='FAMILY_ALLOCATION'?ev1_person((string)($b['personAccount']??'')):ev1_utility_account($type);$id=ev1_id((array)$s['utilityPayments'],'UTP');$meta=['utilityPaymentId'=>$id,'utilityMasterId'=>$masterId,'utilityType'=>$type,'location'=>$location,'locationName'=>$locationName,'billMonth'=>$billMonth,'payee'=>$payee,'accountingTreatment'=>$treatment];$jid=ev1_journal($s,$entity,$date,'UTILITY_PAYMENT',$reference!==''?$reference:$id,ev1_utility_name($type).' — '.$locationName.' — '.$payee,[ev1_line($account,$amount,0,$names,$meta),ev1_pay_line($s,$entity,$paymentId,$amount,$names)],$u,$meta);$s['utilityPayments'][$id]=['id'=>$id,'entity'=>$entity,'utilityMasterId'=>$masterId,'utilityType'=>$type,'utilityTypeName'=>ev1_utility_name($type),'location'=>$location,'locationName'=>$locationName,'billMonth'=>$billMonth,'paymentDate'=>$date,'payee'=>$payee,'amount'=>$amount,'accountingTreatment'=>$treatment,'expenseAccount'=>$account,'paymentAccountId'=>$paymentId,'reference'=>$reference,'notes'=>trim((string)($b['notes']??'')),'journalId'=>$jid,'createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??'Accounts')];$result=['utilityPaymentId'=>$id,'journalId'=>$jid];
}
elseif($action==='capture_reimbursement'){
$person=ev1_reimbursement_person((string)($b['personAccount']??''));$account=ev1_business_account((string)($b['expenseAccount']??''));$date=ev1_date((string)($b['expenseDate']??''),'Expense date');$amount=ev1_amount($b['amount']??0);$payee=trim((string)($b['payee']??''));$description=trim((string)($b['description']??''));$reference=trim((string)($b['reference']??''));$location=ev1_general_location((string)($b['location']??''));if($payee===''||$description==='')ev1_out(['ok'=>false,'error'=>'Payee and expense description are required.'],422);if($reference!=='')foreach((array)$s['reimbursements']as$old)if(is_array($old)&&($old['entity']??'')===$entity&&($old['personAccount']??'')===$person&&strcasecmp((string)($old['reference']??''),$reference)===0)ev1_out(['ok'=>false,'error'=>'This reimbursement reference is already recorded for the selected person.'],409);$id=ev1_id((array)$s['reimbursements'],'RMB');$meta=['reimbursementId'=>$id,'personAccount'=>$person,'expenseAccount'=>$account,'location'=>$location,'payee'=>$payee];$jid=ev1_journal($s,$entity,$date,'EXPENSE_REIMBURSEMENT_CAPTURE',$reference!==''?$reference:$id,$description.' — personally paid by '.$names[$person],[ev1_line($account,$amount,0,$names,$meta),ev1_line($person,0,$amount,$names,$meta)],$u,$meta);$s['reimbursements'][$id]=['id'=>$id,'entity'=>$entity,'personAccount'=>$person,'personName'=>$names[$person],'expenseAccount'=>$account,'expenseAccountName'=>$names[$account],'expenseDate'=>$date,'amount'=>$amount,'settled'=>0.0,'outstanding'=>$amount,'status'=>'Outstanding','payee'=>$payee,'description'=>$description,'reference'=>$reference,'location'=>$location,'captureJournalId'=>$jid,'settlements'=>[],'createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??'Accounts')];$result=['reimbursementId'=>$id,'journalId'=>$jid];
}
elseif($action==='settle_reimbursement'){
$id=trim((string)($b['reimbursementId']??''));$r=$s['reimbursements'][$id]??null;if(!is_array($r)||($r['entity']??'')!==$entity)ev1_out(['ok'=>false,'error'=>'Reimbursement not found in this legal entity.'],404);$outstanding=round((float)($r['outstanding']??0),2);if($outstanding<=0)ev1_out(['ok'=>false,'error'=>'This reimbursement is already fully settled.'],409);$amount=ev1_amount($b['amount']??0,'Settlement amount');if($amount-$outstanding>.005)ev1_out(['ok'=>false,'error'=>'Settlement cannot exceed the outstanding reimbursement.'],422);$date=ev1_date((string)($b['settlementDate']??''),'Settlement date');$paymentId=trim((string)($b['paymentAccountId']??''));$reference=trim((string)($b['reference']??''));$person=ev1_reimbursement_person((string)$r['personAccount']);$settlementId='RMS-'.str_pad((string)(count((array)($r['settlements']??[]))+1),3,'0',STR_PAD_LEFT);$meta=['reimbursementId'=>$id,'settlementId'=>$settlementId,'personAccount'=>$person];$jid=ev1_journal($s,$entity,$date,'EXPENSE_REIMBURSEMENT_SETTLE',$reference!==''?$reference:$id.'-'.$settlementId,'Settlement of '.$r['description'],[ev1_line($person,$amount,0,$names,$meta),ev1_pay_line($s,$entity,$paymentId,$amount,$names)],$u,$meta);$settled=round((float)($r['settled']??0)+$amount,2);$remaining=round((float)$r['amount']-$settled,2);$s['reimbursements'][$id]['settled']=$settled;$s['reimbursements'][$id]['outstanding']=max(0,$remaining);$s['reimbursements'][$id]['status']=$remaining<=.005?'Settled':'Partially Settled';$s['reimbursements'][$id]['settlements'][]=['id'=>$settlementId,'date'=>$date,'amount'=>$amount,'paymentAccountId'=>$paymentId,'reference'=>$reference,'journalId'=>$jid,'createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??'Accounts')];$result=['reimbursementId'=>$id,'settlementId'=>$settlementId,'journalId'=>$jid,'outstanding'=>max(0,$remaining)];
}
elseif($action==='pay_general_expense'||$action==='pay_export_expense'){
$exportExpense=$action==='pay_export_expense';$account=$exportExpense?'5550':ev1_business_account((string)($b['expenseAccount']??''));$date=ev1_date((string)($b['paymentDate']??''),'Payment date');$amount=ev1_amount($b['amount']??0);$payee=trim((string)($b['payee']??''));$description=trim((string)($b['description']??''));$reference=trim((string)($b['reference']??''));$location=$exportExpense?'EXPORTS':ev1_general_location((string)($b['location']??''));$paymentId=trim((string)($b['paymentAccountId']??''));if($payee===''||$description==='')ev1_out(['ok'=>false,'error'=>'Payee and expense description are required.'],422);if($reference!=='')foreach((array)$s['generalExpenses']as$old)if(is_array($old)&&($old['entity']??'')===$entity&&strcasecmp((string)($old['payee']??''),$payee)===0&&strcasecmp((string)($old['reference']??''),$reference)===0)ev1_out(['ok'=>false,'error'=>'This expense reference is already recorded for the payee.'],409);$id=ev1_id((array)$s['generalExpenses'],'GEX');$meta=['generalExpenseId'=>$id,'expenseAccount'=>$account,'location'=>$location,'payee'=>$payee];$jid=ev1_journal($s,$entity,$date,$exportExpense?'EXPORT_EXPENSE_PAYMENT':'GENERAL_EXPENSE_PAYMENT',$reference!==''?$reference:$id,$description.' — '.$location,[ev1_line($account,$amount,0,$names,$meta),ev1_pay_line($s,$entity,$paymentId,$amount,$names)],$u,$meta);$s['generalExpenses'][$id]=['id'=>$id,'entity'=>$entity,'expenseAccount'=>$account,'expenseAccountName'=>$names[$account],'paymentDate'=>$date,'amount'=>$amount,'payee'=>$payee,'description'=>$description,'reference'=>$reference,'location'=>$location,'expenseType'=>$exportExpense?'EXPORT':'GENERAL','paymentAccountId'=>$paymentId,'journalId'=>$jid,'createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??'Accounts')];$result=['generalExpenseId'=>$id,'journalId'=>$jid];
}
elseif($action==='save_card_master'){
$id=trim((string)($b['id']??''));$name=trim((string)($b['cardName']??''));$holder=trim((string)($b['holder']??''));$issuer=trim((string)($b['issuerBank']??''));$last4=preg_replace('/\D+/','',(string)($b['last4']??''))??'';$dueDay=ev1_day($b['dueDay']??0);if($name===''||$holder===''||$issuer===''||strlen($last4)!==4)ev1_out(['ok'=>false,'error'=>'Card name, holder, issuing bank and last four digits are required.'],422);foreach((array)$s['creditCardMasters']as$other)if(is_array($other)&&($other['entity']??'')===$entity&&($other['status']??'Active')==='Active'&&($other['id']??'')!==$id&&($other['last4']??'')===$last4)ev1_out(['ok'=>false,'error'=>'An active card with these last four digits already exists.'],409);if($id==='')$id=ev1_id((array)$s['creditCardMasters'],'CCM');$old=$s['creditCardMasters'][$id]??null;if($old!==null&&(!is_array($old)||($old['entity']??'')!==$entity))ev1_out(['ok'=>false,'error'=>'Credit card not found in this legal entity.'],404);$s['creditCardMasters'][$id]=array_merge(is_array($old)?$old:[],['id'=>$id,'entity'=>$entity,'cardName'=>$name,'holder'=>$holder,'issuerBank'=>$issuer,'last4'=>$last4,'dueDay'=>$dueDay,'status'=>'Active','notes'=>trim((string)($b['notes']??'')),'updatedAt'=>gmdate('c'),'updatedBy'=>(string)($u['full_name']??'Accounts')]);if(!is_array($old)){$s['creditCardMasters'][$id]['createdAt']=gmdate('c');$s['creditCardMasters'][$id]['createdBy']=(string)($u['full_name']??'Accounts');}$result=['cardMasterId'=>$id];
}
elseif($action==='deactivate_card_master'){
$id=trim((string)($b['id']??''));$m=$s['creditCardMasters'][$id]??null;if(!is_array($m)||($m['entity']??'')!==$entity)ev1_out(['ok'=>false,'error'=>'Credit card not found.'],404);foreach((array)$s['creditCardStatements']as$st)if(is_array($st)&&($st['entity']??'')===$entity&&($st['cardMasterId']??'')===$id&&($st['status']??'Pending')==='Pending')ev1_out(['ok'=>false,'error'=>'Pay or update the pending statement before removing this card.'],409);$s['creditCardMasters'][$id]['status']='Inactive';$s['creditCardMasters'][$id]['updatedAt']=gmdate('c');$result=['cardMasterId'=>$id,'status'=>'Inactive'];
}
elseif($action==='save_card_statement'){
$id=trim((string)($b['id']??''));$cardId=trim((string)($b['cardMasterId']??''));$card=$s['creditCardMasters'][$cardId]??null;if(!is_array($card)||($card['entity']??'')!==$entity||($card['status']??'Active')!=='Active')ev1_out(['ok'=>false,'error'=>'Select an active credit card for this legal entity.'],422);$statementMonth=ev1_month((string)($b['statementMonth']??$month));$statementDate=ev1_date((string)($b['statementDate']??''),'Statement date');$dueDate=ev1_date((string)($b['dueDate']??''),'Due date');if($dueDate<$statementDate)ev1_out(['ok'=>false,'error'=>'Due date cannot be before statement date.'],422);$total=ev1_amount($b['total']??0,'Statement total');$alloc=ev1_allocations($b['allocations']??null,$total,$names);foreach((array)$s['creditCardStatements']as$other)if(is_array($other)&&($other['entity']??'')===$entity&&($other['cardMasterId']??'')===$cardId&&($other['statementMonth']??'')===$statementMonth&&($other['id']??'')!==$id)ev1_out(['ok'=>false,'error'=>'A statement already exists for this card and month.'],409);if($id==='')$id=ev1_id((array)$s['creditCardStatements'],'CCS');$old=$s['creditCardStatements'][$id]??null;if(is_array($old)&&(($old['entity']??'')!==$entity||($old['status']??'Pending')==='Paid'))ev1_out(['ok'=>false,'error'=>'Paid statements cannot be edited.'],409);$s['creditCardStatements'][$id]=array_merge(is_array($old)?$old:[],['id'=>$id,'entity'=>$entity,'cardMasterId'=>$cardId,'cardName'=>$card['cardName'],'holder'=>$card['holder'],'last4'=>$card['last4'],'statementMonth'=>$statementMonth,'statementDate'=>$statementDate,'dueDate'=>$dueDate,'total'=>$total,'allocations'=>$alloc,'status'=>'Pending','notes'=>trim((string)($b['notes']??'')),'updatedAt'=>gmdate('c'),'updatedBy'=>(string)($u['full_name']??'Accounts')]);if(!is_array($old)){$s['creditCardStatements'][$id]['createdAt']=gmdate('c');$s['creditCardStatements'][$id]['createdBy']=(string)($u['full_name']??'Accounts');}$result=['statementId'=>$id,'status'=>'Pending','journalCreated'=>false];
}
elseif($action==='pay_card_statement'){
$id=trim((string)($b['statementId']??''));$st=$s['creditCardStatements'][$id]??null;if(!is_array($st)||($st['entity']??'')!==$entity)ev1_out(['ok'=>false,'error'=>'Credit-card statement not found.'],404);if(($st['status']??'Pending')==='Paid')ev1_out(['ok'=>false,'error'=>'This credit-card statement is already paid.'],409);$date=ev1_date((string)($b['paymentDate']??''),'Payment date');$paymentId=trim((string)($b['paymentAccountId']??''));$total=round((float)$st['total'],2);$lines=[];foreach((array)$st['allocations']as$a){if(!is_array($a))continue;$lines[]=ev1_line((string)$a['account'],(float)$a['amount'],0,$names,['statementId'=>$id,'allocationKind'=>$a['kind'],'detail'=>$a['detail']]);}$lines[]=ev1_pay_line($s,$entity,$paymentId,$total,$names);$meta=['statementId'=>$id,'cardMasterId'=>$st['cardMasterId'],'cardName'=>$st['cardName'],'statementMonth'=>$st['statementMonth'],'dueDate'=>$st['dueDate']];$jid=ev1_journal($s,$entity,$date,'CREDIT_CARD_PAYMENT',$id,'Credit-card payment — '.$st['cardName'].' — '.$st['statementMonth'],$lines,$u,$meta);$s['creditCardStatements'][$id]['status']='Paid';$s['creditCardStatements'][$id]['paymentDate']=$date;$s['creditCardStatements'][$id]['paymentAccountId']=$paymentId;$s['creditCardStatements'][$id]['journalId']=$jid;$s['creditCardStatements'][$id]['paidAt']=gmdate('c');$s['creditCardStatements'][$id]['paidBy']=(string)($u['full_name']??'Accounts');$result=['statementId'=>$id,'journalId'=>$jid,'status'=>'Paid'];
}
else ev1_out(['ok'=>false,'error'=>'Unknown Expenses action.'],422);

if($postingKey!==null)$s['postingKeys'][$postingKey]=['fingerprint'=>(string)$fingerprint,'result'=>$result,'createdAt'=>gmdate('c')];$s['revision']=(int)($s['revision']??0)+1;rewind($h);ftruncate($h,0);fwrite($h,json_encode($s,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($h);}finally{flock($h,LOCK_UN);fclose($h);}ev1_out(ev1_payload($s,$entity,$month)+['result'=>$result,'revision'=>$s['revision']]);
}catch(InvalidArgumentException $e){ev1_out(['ok'=>false,'error'=>$e->getMessage()],422);}catch(Throwable $e){ev1_out(['ok'=>false,'error'=>'Expenses could not be updated.'],500);}
