<?php
declare(strict_types=1);

require dirname(__DIR__) . '/auth_store.php';
header('Content-Type: application/json; charset=UTF-8');
header('Cache-Control: no-store, no-cache, must-revalidate');

const TT_EXPORT_RECEIPTS_FILE = TT_DATA_DIR . '/accounts.json';
const TT_EXPORT_OPS_FILE = TT_DATA_DIR . '/operations.json';
const TT_EXPORT_ACCOUNT_MASTER = __DIR__ . '/../accounts/accounting_master_v1.json';
const TT_EXPORT_REALIZATION_POLICY = __DIR__ . '/../accounts/export_realization_policy_v1.json';
const TT_EXPORT_SETTLEMENT_POLICY = __DIR__ . '/../accounts/settlement_policy_v1.json';
const TT_EXPORT_REALIZATION_MASTER_TYPE = 'export_realization_charges';

function er_respond(array $data,int $status=200): never {http_response_code($status);echo json_encode($data,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function er_json(string $path): array {$raw=is_file($path)?file_get_contents($path):false;$v=$raw?json_decode($raw,true):null;if(!is_array($v))throw new RuntimeException('Required Accounts configuration is unavailable.');return $v;}
function er_can_write(array $user): bool {
    if(($user['role']??'')==='Super Admin')return true;$p=$user['permissions']['Accounts']??null;if($p==='all')return true;if(!is_array($p))return false;
    if(in_array('Create',$p,true)||in_array('Edit',$p,true)||in_array('Approve',$p,true))return true;
    foreach($p as $a)if(is_array($a)&&(in_array('Create',$a,true)||in_array('Edit',$a,true)||in_array('Approve',$a,true)))return true;return false;
}
function er_default_store(): array {return ['revision'=>0,'journals'=>[],'exportCandidates'=>[],'exportReceipts'=>[],'bankAccountSettings'=>[]];}
function er_read_accounts(): array {
    tt_ensure_data_dir();if(!is_file(TT_EXPORT_RECEIPTS_FILE))return er_default_store();$h=fopen(TT_EXPORT_RECEIPTS_FILE,'r');if($h===false||!flock($h,LOCK_SH))throw new RuntimeException('Accounts storage unavailable.');
    try{$raw=stream_get_contents($h);}finally{flock($h,LOCK_UN);fclose($h);}$s=$raw?json_decode($raw,true):null;return is_array($s)?array_replace_recursive(er_default_store(),$s):er_default_store();
}
function er_entity(string $v): string {$v=strtoupper(trim($v));if(!in_array($v,['TTI','BRM'],true))er_respond(['ok'=>false,'error'=>'Pakistan export receipts are available for TTI or BRM books.'],422);return $v;}
function er_date(string $v): string {if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$v))er_respond(['ok'=>false,'error'=>'Valid bank credit date is required.'],422);return $v;}
function er_money(mixed $v,string $label,bool $zero=false): float {$n=round((float)$v,2);if($n<0||(!$zero&&$n<=0))er_respond(['ok'=>false,'error'=>$label.' must be '.($zero?'zero or greater':'greater than zero').'.'],422);return $n;}
function er_currency(string $v): string {$v=strtoupper(trim($v));if(!preg_match('/^[A-Z]{3}$/',$v))er_respond(['ok'=>false,'error'=>'Valid receipt currency required.'],422);return $v;}
function er_next_id(array $items,string $prefix): string {$n=count($items)+1;do{$id=$prefix.'-'.gmdate('Y').'-'.str_pad((string)$n,6,'0',STR_PAD_LEFT);$n++;}while(isset($items[$id]));return $id;}
function er_catalog(): array {
    $out=[];$m=er_json(TT_EXPORT_ACCOUNT_MASTER);foreach((array)($m['chart']??[]) as $a)if(is_array($a)&&isset($a['code']))$out[(string)$a['code']]=$a;
    $p=er_json(TT_EXPORT_REALIZATION_POLICY);foreach((array)($p['accounts']??[]) as $a)if(is_array($a)&&isset($a['code']))$out[(string)$a['code']]=$a;
    $s=er_json(TT_EXPORT_SETTLEMENT_POLICY);foreach((array)($s['accounts']??[]) as $a)if(is_array($a)&&isset($a['code']))$out[(string)$a['code']]=$a;return $out;
}
function er_line(string $account,float $dr,float $cr,array $catalog,array $extra=[]): array {if(!isset($catalog[$account]))er_respond(['ok'=>false,'error'=>'Accounting mapping '.$account.' is not configured.'],422);return array_merge(['account'=>$account,'accountName'=>(string)($catalog[$account]['name']??$account),'debit'=>round($dr,2),'credit'=>round($cr,2)],$extra);}
function er_post_journal(array &$store,array $user,string $entity,string $date,string $sourceType,string $reference,string $narration,array $lines,array $meta): array {
    $dr=round(array_sum(array_column($lines,'debit')),2);$cr=round(array_sum(array_column($lines,'credit')),2);if($dr<=0||abs($dr-$cr)>.01)throw new RuntimeException('Export receipt journal did not balance.');
    $id=er_next_id((array)$store['journals'],'AUTO');$store['journals'][$id]=['id'=>$id,'entity'=>$entity,'date'=>$date,'sourceType'=>$sourceType,'reference'=>$reference,'narration'=>$narration,'lines'=>$lines,'totalDebit'=>$dr,'totalCredit'=>$cr,'status'=>'Posted','meta'=>$meta,'createdAt'=>gmdate('c'),'createdBy'=>(string)($user['full_name']??$user['username']??'Accounts'),'userId'=>(int)($user['id']??0),'reversalOf'=>null];return $store['journals'][$id];
}
function er_operations_root(): array {
    if(!is_file(TT_EXPORT_OPS_FILE))return [];$h=fopen(TT_EXPORT_OPS_FILE,'r');if($h===false||!flock($h,LOCK_SH))return [];try{$raw=stream_get_contents($h);}finally{flock($h,LOCK_UN);fclose($h);} $s=$raw?json_decode($raw,true):null;if(!is_array($s))return [];$rootRaw=$s['values']['transtrade_export_v2_operational']??'';$root=is_string($rootRaw)?json_decode($rootRaw,true):null;return is_array($root)?$root:[];
}
function er_contract_value(array $c): float {if(isset($c['contractValue'])&&(float)$c['contractValue']>0)return round((float)$c['contractValue'],2);$n=0.0;foreach((array)($c['packings']??[]) as $p)if(is_array($p))$n+=(float)($p['containers']??0)*(float)($p['weightPer']??0)*(float)($p['price']??0);if($n<=0)$n=(float)($c['qty']??0)*(float)($c['price']??0);return round($n,2);}
function er_sources(array $accounts,string $entity): array {
    $root=er_operations_root();$contracts=[];$fis=[];$invoices=[];
    foreach((array)($root['contracts']??[]) as $c){if(!is_array($c))continue;$seller=strtoupper((string)($c['seller']??'TTI'));$pkExporter=$seller==='TG'?'TTI':$seller;if($pkExporter!==$entity)continue;$ref=trim((string)($c['ref']??$c['id']??''));if($ref==='')continue;$cur=strtoupper(trim((string)($c['currency']??'USD')))?:'USD';$val=er_contract_value($c);$pct=(float)($c['advancePct']??0);if((string)($c['paymentCode']??'')==='ADV100')$pct=100;$contracts[]=['id'=>(string)($c['id']??$ref),'ref'=>$ref,'seller'=>$seller,'pakistanExporter'=>$pkExporter,'customer'=>(string)($c['customer']??''),'currency'=>$cur,'contractValue'=>$val,'paymentCode'=>(string)($c['paymentCode']??''),'paymentText'=>(string)($c['paymentText']??''),'advancePct'=>$pct,'expectedAdvance'=>round($val*$pct/100,2),'status'=>(string)($c['status']??'')];}
    $receiptRows=(array)($accounts['exportReceipts']??[]);
    foreach((array)($root['fi']??[]) as $f){if(!is_array($f))continue;$cur=strtoupper(trim((string)($f['currency']??'USD')))?:'USD';$value=round((float)($f['value']??0),2);$realized=0.0;foreach($receiptRows as $r)if(is_array($r)&&($r['entity']??'')===$entity)foreach((array)($r['fiAllocations']??[]) as $a)if(is_array($a)&&(string)($a['fiId']??'')===(string)($f['id']??''))$realized+=round((float)($a['amount']??0),2);$fis[]=['id'=>(string)($f['id']??''),'number'=>(string)($f['number']??''),'date'=>(string)($f['date']??''),'type'=>(string)($f['type']??''),'customer'=>(string)($f['customer']??''),'contractRef'=>(string)($f['contractRef']??''),'paymentTerms'=>(string)($f['paymentTerms']??''),'bank'=>(string)($f['bank']??''),'currency'=>$cur,'value'=>$value,'realized'=>round($realized,2),'remainingToRealize'=>max(0,round($value-$realized,2)),'customsConsumed'=>round(array_sum(array_map(static fn($x)=>(float)($x['amount']??0),(array)($f['allocations']??[]))),2)];}
    foreach((array)($accounts['exportCandidates']??[]) as $cid=>$c){if(!is_array($c)||($c['entity']??'')!==$entity)continue;$meta=is_array($c['meta']??null)?$c['meta']:[];$type=(string)($c['candidateType']??'');if(!in_array($type,['CUSTOMER_EXPORT_SALE','TG_PAKISTAN_INTERCOMPANY'],true))continue;$foreign=round((float)($c['transactionAmount']??0),2);$received=0.0;foreach($receiptRows as $r)if(is_array($r)&&($r['entity']??'')===$entity)foreach((array)($r['allocations']??[]) as $a)if(is_array($a)&&(string)($a['targetId']??'')===(string)$cid)$received+=round((float)($a['foreignAmount']??0),2);$invoices[]=['id'=>(string)$cid,'reference'=>(string)($c['reference']??$cid),'candidateType'=>$type,'contractRef'=>(string)($meta['contractRef']??''),'customer'=>(string)($meta['customer']??($c['counterparty']??'')),'currency'=>(string)($c['transactionCurrency']??$meta['transactionCurrency']??'USD'),'foreignAmount'=>$foreign,'receivedForeign'=>round($received,2),'outstandingForeign'=>max(0,round($foreign-$received,2)),'recognized'=>!empty($c['journalId']),'recognitionStatus'=>(string)($c['status']??''),'functionalAmount'=>round((float)($c['functionalAmount']??0),2),'fiRefs'=>(array)($meta['fiRefs']??[]),'gdRefs'=>(array)($meta['gdRefs']??[]),'blNo'=>(string)($meta['blNo']??'')];}
    foreach((array)($root['shipments']??[]) as $s){if(!is_array($s))continue;$commercial=is_array($s['commercial']??null)?$s['commercial']:[];if(empty($commercial['saved']))continue;$ref=(string)($s['id']??$s['lotRef']??$s['contractRef']??'');$contractRef=(string)($s['contractRef']??'');$candidate=null;foreach($invoices as $iv)if($iv['reference']===$ref||($contractRef!==''&&$iv['contractRef']===$contractRef&&count($invoices)===1)){$candidate=$iv;break;}if($candidate)continue;$contract=null;foreach($contracts as $cc)if($cc['ref']===$contractRef){$contract=$cc;break;}if(!$contract)continue;$amount=round((float)($commercial['invoiceGross']??0),2);if($amount<=0)$amount=round((float)($commercial['netAmount']??0),2);$invoices[]=['id'=>'OPS|'.$ref,'reference'=>(string)($commercial['invoiceNo']??$ref),'candidateType'=>'UNRECOGNIZED_OPERATIONAL_INVOICE','contractRef'=>$contractRef,'customer'=>(string)($s['buyer']??$contract['customer']),'currency'=>$contract['currency'],'foreignAmount'=>$amount,'receivedForeign'=>0,'outstandingForeign'=>$amount,'recognized'=>false,'recognitionStatus'=>'Invoice exists in Exports — receivable not yet recognized','functionalAmount'=>0,'fiRefs'=>[],'gdRefs'=>[],'blNo'=>(string)(($s['bl']['blNo']??''))];}
    usort($contracts,static fn($a,$b)=>strcmp((string)$b['ref'],(string)$a['ref']));usort($fis,static fn($a,$b)=>strcmp((string)$b['date'],(string)$a['date']));usort($invoices,static fn($a,$b)=>strcmp((string)$b['reference'],(string)$a['reference']));return ['contracts'=>$contracts,'fis'=>$fis,'invoices'=>$invoices];
}
function er_entity_from_linked(string $linked): string {$u=strtoupper($linked);if(str_contains($u,'BRM')||str_contains($u,'BUKSH RICE'))return 'BRM';if(str_contains($u,'TTI')||str_contains($u,'TRANSTRADE INTERNATIONAL'))return 'TTI';if(str_contains($u,'TG')||str_contains($u,'TRANS GRAINS'))return 'TG';return '';}
function er_bank_master(string $id,string $entity): array {$masters=tt_list_masters();foreach((array)($masters['banks']??[]) as $row){if(!is_array($row)||(string)($row['id']??'')!==$id)continue;$v=array_values((array)($row['values']??[]));while(count($v)<14)$v[]='';if(er_entity_from_linked((string)$v[1])!==$entity)er_respond(['ok'=>false,'error'=>'Selected bank does not belong to these company books.'],422);return ['id'=>$id,'accountType'=>(string)$v[0],'entity'=>$entity,'accountTitle'=>(string)$v[3],'bankName'=>(string)$v[4],'currency'=>strtoupper(trim((string)$v[7])),'accountNumber'=>(string)$v[8],'iban'=>(string)$v[9]];}er_respond(['ok'=>false,'error'=>'Selected bank account was not found.'],404);}
function er_receipt_bank(array $store,string $id,string $entity,string $requiredCurrency): array {$b=er_bank_master($id,$entity);if(($b['accountType']??'')!=='Company Account')er_respond(['ok'=>false,'error'=>'A company bank account is required.'],422);if(($b['currency']??'')!==$requiredCurrency)er_respond(['ok'=>false,'error'=>'Selected bank must be a '.$requiredCurrency.' account for this receipt component.'],422);$s=is_array($store['bankAccountSettings'][$id]??null)?$store['bankAccountSettings'][$id]:[];if(empty($s['active'])||empty($s['allowReceipts']))er_respond(['ok'=>false,'error'=>'Selected bank is not active/enabled for receipts in Accounts.'],422);if($requiredCurrency!=='PKR'&&empty($s['retentionAccount']))er_respond(['ok'=>false,'error'=>'Foreign retention can only be credited to a bank marked Foreign Retention Account in Accounts.'],422);return $b;}
function er_master_rows(): array {$m=tt_list_masters();$out=[];foreach((array)($m[TT_EXPORT_REALIZATION_MASTER_TYPE]??[]) as $row){if(!is_array($row))continue;$v=array_values((array)($row['values']??[]));while(count($v)<15)$v[]='';$out[(string)$v[1]]=['id'=>(string)($row['id']??''),'name'=>(string)$v[0],'code'=>(string)$v[1],'category'=>(string)$v[2],'regime'=>(string)$v[3],'base'=>(string)$v[4],'rate'=>(string)$v[5],'effectiveFrom'=>(string)$v[6],'effectiveTo'=>(string)$v[7],'treatment'=>(string)$v[8],'account'=>(string)$v[9],'certificate'=>(string)$v[10],'entities'=>(string)$v[11],'status'=>(string)$v[12],'notes'=>(string)$v[13],'nature'=>(string)$v[14]];}return $out;}
function er_rule_active(array $r,string $date,string $entity): bool {$status=strtolower((string)($r['status']??''));if(str_contains($status,'inactive'))return false;$from=(string)($r['effectiveFrom']??'');$to=(string)($r['effectiveTo']??'');if($from!==''&&$date<$from)return false;if($to!==''&&$date>$to)return false;$entities=strtoupper((string)($r['entities']??''));if($entities!==''&&!str_contains($entities,$entity))return false;return true;}
function er_tax_family(string $code): string {$c=strtoupper(trim($code));if(str_starts_with($c,'EXP-AWT-NTR'))return 'EXP-AWT-NTR';if(str_starts_with($c,'EXP-WHT-FIXED'))return 'EXP-WHT-FIXED';if(str_starts_with($c,'EXP-WHT-FTR'))return 'EXP-WHT-FTR';return '';}
function er_prior_allocated(array $store,string $candidateId): float {$n=0.0;foreach((array)($store['exportReceipts']??[]) as $r)if(is_array($r))foreach((array)($r['allocations']??[]) as $a)if(is_array($a)&&(string)($a['targetId']??'')===$candidateId)$n+=(float)($a['foreignAmount']??0);return round($n,2);}
function er_prepare_allocations(array $store,string $entity,string $currency,float $foreign,float $grossPkr,array $raw): array {
    if(!$raw)er_respond(['ok'=>false,'error'=>'Allocate the foreign receipt to an invoice/intercompany receivable or an advance source.'],422);$out=[];$sum=0.0;$realizedAssigned=0.0;$candidates=(array)($store['exportCandidates']??[]);
    foreach($raw as $a){if(!is_array($a))continue;$fa=er_money($a['foreignAmount']??0,'Allocation amount');$sum+=$fa;$targetType=strtoupper(trim((string)($a['targetType']??'')));$targetId=trim((string)($a['targetId']??''));$contractRef=trim((string)($a['contractRef']??''));$invoiceRef=trim((string)($a['invoiceRef']??''));$customer=trim((string)($a['customer']??''));$realized=round($grossPkr*($fa/$foreign),2);$realizedAssigned+=$realized;
        if(in_array($targetType,['EXPORT_RECEIVABLE','INTERCOMPANY_RECEIVABLE'],true)){
            $c=$candidates[$targetId]??null;if(!is_array($c)||($c['entity']??'')!==$entity||empty($c['journalId']))er_respond(['ok'=>false,'error'=>'A selected receivable has not been recognized/posted yet. Use Contract / Unapplied Advance until recognition.'],422);$ccur=strtoupper((string)($c['transactionCurrency']??''));if($ccur!==$currency)er_respond(['ok'=>false,'error'=>'Receipt currency does not match one of the selected receivables.'],422);$total=(float)($c['transactionAmount']??0);$prior=er_prior_allocated($store,$targetId);if($fa>$total-$prior+.01)er_respond(['ok'=>false,'error'=>'Receipt allocation exceeds the outstanding foreign amount on '.$targetId.'.'],422);$carrying=round((float)($c['functionalAmount']??0)*($fa/max(.000001,$total)),2);$meta=is_array($c['meta']??null)?$c['meta']:[];$expectedType=(string)($c['candidateType']??'')==='TG_PAKISTAN_INTERCOMPANY'?'INTERCOMPANY_RECEIVABLE':'EXPORT_RECEIVABLE';if($targetType!==$expectedType)er_respond(['ok'=>false,'error'=>'Selected receivable type does not match the accounting source.'],422);$out[]=['targetType'=>$targetType,'targetId'=>$targetId,'foreignAmount'=>$fa,'realizedPkr'=>$realized,'carryingPkr'=>$carrying,'contractRef'=>(string)($meta['contractRef']??$contractRef),'invoiceRef'=>(string)($c['reference']??$invoiceRef),'customer'=>(string)($meta['customer']??$customer),'fiRefs'=>(array)($meta['fiRefs']??[])];
        }elseif($targetType==='UNAPPLIED_ADVANCE'){$out[]=['targetType'=>$targetType,'targetId'=>$targetId?:('ADV|'.$contractRef),'foreignAmount'=>$fa,'realizedPkr'=>$realized,'carryingPkr'=>$realized,'contractRef'=>$contractRef,'invoiceRef'=>$invoiceRef,'customer'=>$customer,'fiRefs'=>[]];}
        else er_respond(['ok'=>false,'error'=>'Select a valid receipt allocation type.'],422);
    }
    if(abs($sum-$foreign)>.01)er_respond(['ok'=>false,'error'=>'Invoice / advance allocations must equal the full foreign receipt amount.'],422);if($out){$delta=round($grossPkr-$realizedAssigned,2);$out[count($out)-1]['realizedPkr']=round($out[count($out)-1]['realizedPkr']+$delta,2);if($out[count($out)-1]['targetType']==='UNAPPLIED_ADVANCE')$out[count($out)-1]['carryingPkr']=$out[count($out)-1]['realizedPkr'];}return $out;
}
function er_prepare_fi(array $sources,string $currency,float $foreign,array $raw): array {$by=[];foreach((array)$sources['fis'] as $f)$by[(string)$f['id']]=$f;$out=[];$sum=0.0;foreach($raw as $a){if(!is_array($a))continue;$id=trim((string)($a['fiId']??''));$amt=er_money($a['amount']??0,'FI realization allocation');$f=$by[$id]??null;if(!is_array($f))er_respond(['ok'=>false,'error'=>'Selected FI is no longer available from Exports.'],422);if(strtoupper((string)$f['currency'])!==$currency)er_respond(['ok'=>false,'error'=>'FI currency does not match the receipt currency.'],422);if($amt>(float)$f['remainingToRealize']+.01)er_respond(['ok'=>false,'error'=>'FI realization exceeds the remaining FI amount for '.$f['number'].'.'],422);$sum+=$amt;$out[]=['fiId'=>$id,'fiNo'=>(string)$f['number'],'contractRef'=>(string)$f['contractRef'],'amount'=>$amt,'currency'=>$currency];}if($sum>$foreign+.01)er_respond(['ok'=>false,'error'=>'Total FI realization allocation cannot exceed the bank receipt foreign amount.'],422);return $out;}
function er_prepare_deductions(string $entity,string $date,array $raw,array $catalog): array {$masters=er_master_rows();$out=[];$deducted=0.0;$separate=0.0;$taxDeducted=[];$taxSeparate=[];foreach($raw as $d){if(!is_array($d))continue;$code=strtoupper(trim((string)($d['masterCode']??'')));$amount=er_money($d['amount']??0,'Deduction amount');$m=$masters[$code]??null;if(!is_array($m))er_respond(['ok'=>false,'error'=>'Selected export tax/charge master row was not found: '.$code],422);if(!er_rule_active($m,$date,$entity)&&!str_contains(strtolower((string)$m['status']),'historical'))er_respond(['ok'=>false,'error'=>$m['name'].' is not active for this receipt date/entity.'],422);$account=(string)($m['account']??'');if(!isset($catalog[$account]))er_respond(['ok'=>false,'error'=>'GL mapping '.$account.' for '.$m['name'].' is not configured in Accounts policy.'],422);$mode=strtoupper(trim((string)($d['mode']??'DEDUCTED')));if(!in_array($mode,['DEDUCTED','SEPARATE_DEBIT'],true))$mode='DEDUCTED';$row=['masterId'=>$m['id'],'masterCode'=>$code,'name'=>$m['name'],'category'=>$m['category'],'regime'=>$m['regime'],'amount'=>$amount,'account'=>$account,'mode'=>$mode,'taxSection'=>trim((string)($d['taxSection']??'')),'certificateRequired'=>str_starts_with(strtoupper((string)$m['certificate']),'YES')];$out[]=$row;if($mode==='DEDUCTED')$deducted+=$amount;else $separate+=$amount;if(er_tax_family($code)!==''){if($mode==='DEDUCTED')$taxDeducted[]=$row;else $taxSeparate[]=$row;}}
    return ['rows'=>$out,'deducted'=>round($deducted,2),'separate'=>round($separate,2),'taxDeducted'=>$taxDeducted,'taxSeparate'=>$taxSeparate];}
function er_tax_meta(array $rows,array $bank): array {return array_map(static fn($d)=>['taxCode'=>$d['masterCode'],'taxSection'=>$d['taxSection'],'amount'=>$d['amount'],'bankAccountId'=>$bank['id'],'bankName'=>$bank['bankName'],'regime'=>$d['regime']],$rows);}
function er_write_export_receipts_to_ops(array $receipt): void {
    if(!is_file(TT_EXPORT_OPS_FILE))return;$h=fopen(TT_EXPORT_OPS_FILE,'c+');if($h===false||!flock($h,LOCK_EX))return;try{rewind($h);$raw=stream_get_contents($h);$ops=$raw?json_decode($raw,true):null;if(!is_array($ops))return;$rootRaw=$ops['values']['transtrade_export_v2_operational']??'';$root=is_string($rootRaw)?json_decode($rootRaw,true):null;if(!is_array($root))return;$existing=[];foreach((array)($root['receipts']??[]) as $r)if(!is_array($r)||(string)($r['_accountsReceiptId']??'')!==(string)$receipt['id'])$existing[]=$r;foreach((array)$receipt['allocations'] as $i=>$a){$ref=(string)($a['contractRef']??'');if($ref==='')continue;$existing[]=['id'=>$receipt['id'].'-'.($i+1),'_accountsReceiptId'=>$receipt['id'],'contractRef'=>$ref,'invoiceRef'=>(string)($a['invoiceRef']??''),'date'=>$receipt['date'],'amount'=>(float)$a['foreignAmount'],'currency'=>$receipt['transactionCurrency'],'source'=>'Accounts Bank Receipt','bankAdviceRef'=>$receipt['bankAdviceRef']];}$root['receipts']=$existing;$ops['values']['transtrade_export_v2_operational']=json_encode($root,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);$ops['revision']=(int)($ops['revision']??0)+1;$ops['meta']['transtrade_export_v2_operational']=['updatedAt'=>gmdate('c'),'updatedBy'=>'Accounts Receipt Engine','userId'=>0];rewind($h);ftruncate($h,0);fwrite($h,json_encode($ops,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($h);}catch(Throwable $e){}finally{flock($h,LOCK_UN);fclose($h);}}

try{
    $user=tt_require_login();if(!tt_user_can_open_module($user,'Accounts'))er_respond(['ok'=>false,'error'=>'Accounts permission required.'],403);
    if($_SERVER['REQUEST_METHOD']==='GET'){$entity=er_entity((string)($_GET['entity']??'TTI'));$store=er_read_accounts();$sources=er_sources($store,$entity);$masters=array_values(er_master_rows());$receipts=[];foreach((array)$store['exportReceipts'] as $r)if(is_array($r)&&($r['entity']??'')===$entity)$receipts[]=$r;usort($receipts,static fn($a,$b)=>strcmp((string)($b['date']??''),(string)($a['date']??''))?:strcmp((string)($b['id']??''),(string)($a['id']??'')));er_respond(['ok'=>true,'entity'=>$entity,'sources'=>$sources,'deductionMaster'=>$masters,'receipts'=>$receipts,'serverNow'=>gmdate('c')]);}
    if($_SERVER['REQUEST_METHOD']!=='POST')er_respond(['ok'=>false,'error'=>'Method not allowed.'],405);if(!er_can_write($user))er_respond(['ok'=>false,'error'=>'Accounts Create / Edit / Approve permission required.'],403);
    $body=json_decode(file_get_contents('php://input')?:'{}',true);if(!is_array($body)||!tt_verify_csrf((string)($body['csrf']??'')))er_respond(['ok'=>false,'error'=>'Your session expired. Refresh and try again.'],419);if((string)($body['action']??'')!=='post_receipt')er_respond(['ok'=>false,'error'=>'Unknown export receipt action.'],422);
    $entity=er_entity((string)($body['entity']??''));$date=er_date((string)($body['date']??''));$currency=er_currency((string)($body['transactionCurrency']??''));$foreign=er_money($body['foreignAmount']??0,'Foreign receipt amount');$rate=er_money($body['realizationRate']??0,'Bank realization rate');$gross=er_money($body['grossPkrEquivalent']??($foreign*$rate),'Gross PKR equivalent');$bankCredit=er_money($body['pkrBankCredit']??0,'Actual PKR bank credit',true);$bankId=trim((string)($body['bankAccountId']??''));$bankRef=trim((string)($body['bankAdviceRef']??''));if($bankRef==='')er_respond(['ok'=>false,'error'=>'Bank advice / transaction reference is required to prevent duplicate posting.'],422);$retentionForeign=er_money($body['retentionForeignAmount']??0,'Retention foreign amount',true);if($retentionForeign>$foreign+.0001)er_respond(['ok'=>false,'error'=>'Retention amount cannot exceed the foreign receipt.'],422);$retentionPkr=round($retentionForeign*$rate,2);$retentionBankId=trim((string)($body['retentionBankAccountId']??''));$catalog=er_catalog();
    tt_ensure_data_dir();$h=fopen(TT_EXPORT_RECEIPTS_FILE,'c+');if($h===false||!flock($h,LOCK_EX))throw new RuntimeException('Accounts storage unavailable.');
    try{
        rewind($h);$raw=stream_get_contents($h);$store=$raw?json_decode($raw,true):null;if(!is_array($store))$store=er_default_store();$store=array_replace_recursive(er_default_store(),$store);
        foreach((array)$store['exportReceipts'] as $r)if(is_array($r)&&($r['entity']??'')===$entity&&(string)($r['bankAccountId']??'')===$bankId&&strcasecmp((string)($r['bankAdviceRef']??''),$bankRef)===0)er_respond(['ok'=>false,'error'=>'This bank advice/reference has already been posted for the selected bank.'],409);
        $bank=er_receipt_bank($store,$bankId,$entity,'PKR');$retentionBank=null;if($retentionForeign>0){if($retentionBankId==='')er_respond(['ok'=>false,'error'=>'Select the approved foreign-currency retention bank account.'],422);$retentionBank=er_receipt_bank($store,$retentionBankId,$entity,$currency);}
        $sources=er_sources($store,$entity);$alloc=er_prepare_allocations($store,$entity,$currency,$foreign,$gross,(array)($body['allocations']??[]));$fi=er_prepare_fi($sources,$currency,$foreign,(array)($body['fiAllocations']??[]));$ded=er_prepare_deductions($entity,$date,(array)($body['deductions']??[]),$catalog);
        $expected=round($gross-$retentionPkr-$ded['deducted'],2);if(abs($bankCredit-$expected)>2.0)er_respond(['ok'=>false,'error'=>'Bank advice does not balance: PKR credit + retention + deductions from proceeds must equal gross PKR realization. Difference: Rs '.number_format($bankCredit-$expected,2).'. Classify the missing charge or correct the bank figures.'],422);
        $id=er_next_id((array)$store['exportReceipts'],'ER');$lines=[];if($bankCredit>0)$lines[]=er_line('1110',$bankCredit,0,$catalog,['bankAccountId'=>$bank['id'],'bankName'=>$bank['bankName'],'bankAccountTitle'=>$bank['accountTitle'],'currency'=>'PKR']);if($retentionPkr>0&&$retentionBank)$lines[]=er_line('1110',$retentionPkr,0,$catalog,['bankAccountId'=>$retentionBank['id'],'bankName'=>$retentionBank['bankName'],'bankAccountTitle'=>$retentionBank['accountTitle'],'currency'=>$currency,'bankDebit'=>$retentionForeign,'bankCredit'=>0]);foreach($ded['rows'] as $d)if($d['mode']==='DEDUCTED')$lines[]=er_line($d['account'],$d['amount'],0,$catalog,['exportDeductionCode'=>$d['masterCode'],'taxSection'=>$d['taxSection']]);
        $realizedReceivable=0.0;$carryingReceivable=0.0;foreach($alloc as $a){if($a['targetType']==='EXPORT_RECEIVABLE'){$lines[]=er_line('1210',0,$a['carryingPkr'],$catalog,['candidateId'=>$a['targetId']]);$realizedReceivable+=$a['realizedPkr'];$carryingReceivable+=$a['carryingPkr'];}elseif($a['targetType']==='INTERCOMPANY_RECEIVABLE'){$lines[]=er_line('1240',0,$a['carryingPkr'],$catalog,['candidateId'=>$a['targetId']]);$realizedReceivable+=$a['realizedPkr'];$carryingReceivable+=$a['carryingPkr'];}else{$lines[]=er_line('2160',0,$a['realizedPkr'],$catalog,['contractRef'=>$a['contractRef'],'invoiceRef'=>$a['invoiceRef'],'customer'=>$a['customer']]);}}
        $fx=round($realizedReceivable-$carryingReceivable,2);if($fx>0)$lines[]=er_line('7100',0,$fx,$catalog,['fxDirection'=>'Gain']);elseif($fx<0)$lines[]=er_line('7100',abs($fx),0,$catalog,['fxDirection'=>'Loss']);
        $meta=['receiptId'=>$id,'transactionCurrency'=>$currency,'transactionAmount'=>$foreign,'realizationRate'=>$rate,'grossPkrEquivalent'=>$gross,'bankAccountId'=>$bank['id'],'bankName'=>$bank['bankName'],'pkrBankCredit'=>$bankCredit,'retentionBankAccountId'=>$retentionBank['id']??'','retentionForeignAmount'=>$retentionForeign,'retentionPkrEquivalent'=>$retentionPkr,'fiRefs'=>array_values(array_map(static fn($a)=>$a['fiNo'],$fi)),'fiAllocations'=>$fi,'invoiceRefs'=>array_values(array_filter(array_map(static fn($a)=>(string)($a['invoiceRef']??''),$alloc))),'allocations'=>$alloc,'deductions'=>array_values(array_filter($ded['rows'],static fn($d)=>$d['mode']==='DEDUCTED')),'exportTaxDeductions'=>er_tax_meta($ded['taxDeducted'],$bank),'bankAdviceFileRef'=>trim((string)($body['bankAdviceFileRef']??'')),'remitter'=>trim((string)($body['remitter']??''))];
        $journal=er_post_journal($store,$user,$entity,$date,'EXPORT_FOREIGN_RECEIPT',$bankRef,'Foreign export / intercompany realization — '.$bankRef,$lines,$meta);
        $separateJournal=null;if($ded['separate']>0){$sl=[];foreach($ded['rows'] as $d)if($d['mode']==='SEPARATE_DEBIT')$sl[]=er_line($d['account'],$d['amount'],0,$catalog,['exportDeductionCode'=>$d['masterCode'],'taxSection'=>$d['taxSection']]);$sl[]=er_line('1110',0,$ded['separate'],$catalog,['bankAccountId'=>$bank['id'],'bankName'=>$bank['bankName'],'bankAccountTitle'=>$bank['accountTitle'],'currency'=>'PKR']);$sm=['receiptId'=>$id,'linkedReceiptJournalId'=>$journal['id'],'bankAccountId'=>$bank['id'],'bankName'=>$bank['bankName'],'deductions'=>array_values(array_filter($ded['rows'],static fn($d)=>$d['mode']==='SEPARATE_DEBIT')),'exportTaxDeductions'=>er_tax_meta($ded['taxSeparate'],$bank),'bankAdviceFileRef'=>trim((string)($body['bankAdviceFileRef']??''))];$separateJournal=er_post_journal($store,$user,$entity,$date,'EXPORT_REALIZATION_BANK_DEBITS',$bankRef.'-CHG','Export realization charges / tax debited separately — '.$bankRef,$sl,$sm);}
        $receipt=['id'=>$id,'entity'=>$entity,'date'=>$date,'bankAdviceRef'=>$bankRef,'bankAdviceFileRef'=>trim((string)($body['bankAdviceFileRef']??'')),'remitter'=>trim((string)($body['remitter']??'')),'transactionCurrency'=>$currency,'foreignAmount'=>$foreign,'realizationRate'=>$rate,'grossPkrEquivalent'=>$gross,'bankAccountId'=>$bank['id'],'bankName'=>$bank['bankName'],'pkrBankCredit'=>$bankCredit,'retentionBankAccountId'=>$retentionBank['id']??'','retentionForeignAmount'=>$retentionForeign,'retentionPkrEquivalent'=>$retentionPkr,'fiAllocations'=>$fi,'allocations'=>$alloc,'deductions'=>$ded['rows'],'journalId'=>$journal['id'],'separateChargeJournalId'=>$separateJournal['id']??null,'status'=>'Accounts Approved / Posted','createdAt'=>gmdate('c'),'createdBy'=>(string)($user['full_name']??$user['username']??'Accounts')];$store['exportReceipts'][$id]=$receipt;$store['revision']=(int)($store['revision']??0)+1;rewind($h);ftruncate($h,0);fwrite($h,json_encode($store,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($h);
    }finally{flock($h,LOCK_UN);fclose($h);}
    er_write_export_receipts_to_ops($receipt);er_respond(['ok'=>true,'receipt'=>$receipt,'journal'=>$journal,'separateChargeJournal'=>$separateJournal,'revision'=>$store['revision']]);
}catch(Throwable $e){er_respond(['ok'=>false,'error'=>'The export receipt could not be posted.'],500);}
