<?php
declare(strict_types=1);

require dirname(__DIR__) . '/auth_store.php';
header('Content-Type: application/json; charset=UTF-8');
header('Cache-Control: no-store, no-cache, must-revalidate');

const TT_EXPORT_ACCOUNTS_FILE = TT_DATA_DIR . '/accounts.json';
const TT_EXPORT_MASTER_FILE = __DIR__ . '/../accounts/accounting_master_v1.json';
const TT_EXPORT_POLICY_FILE = __DIR__ . '/../accounts/revenue_policy_v1.json';

function exa_respond(array $data, int $status = 200): never {http_response_code($status);echo json_encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);exit;}
function exa_module_write(array $user, string $module): bool {if (($user['role'] ?? '') === 'Super Admin') return true;$p = $user['permissions'][$module] ?? null;if ($p === 'all') return true;if (!is_array($p)) return false;if (in_array('Create',$p,true) || in_array('Edit',$p,true)) return true;foreach ($p as $a) if (is_array($a) && (in_array('Create',$a,true) || in_array('Edit',$a,true))) return true;return false;}
function exa_json_file(string $path): array {$raw=is_file($path)?file_get_contents($path):false;$v=$raw?json_decode($raw,true):null;if(!is_array($v))throw new RuntimeException('Required Accounts configuration is unavailable.');return $v;}
function exa_default_store(): array {return ['revision'=>0,'journals'=>[],'events'=>[],'reminders'=>[],'masters'=>[],'commodityBills'=>[],'exportCandidates'=>[]];}
function exa_read(): array {tt_ensure_data_dir();if(!is_file(TT_EXPORT_ACCOUNTS_FILE))return exa_default_store();$h=fopen(TT_EXPORT_ACCOUNTS_FILE,'r');if($h===false||!flock($h,LOCK_SH))throw new RuntimeException('Accounts storage unavailable.');try{$raw=stream_get_contents($h);}finally{flock($h,LOCK_UN);fclose($h);} $s=$raw?json_decode($raw,true):null;return is_array($s)?array_replace_recursive(exa_default_store(),$s):exa_default_store();}
function exa_date(string $v,string $label='Date'): string {if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$v))exa_respond(['ok'=>false,'error'=>$label.' is required.'],422);return $v;}
function exa_positive(mixed $v,string $label): float {$n=round((float)$v,2);if($n<=0)exa_respond(['ok'=>false,'error'=>$label.' must be greater than zero.'],422);return $n;}
function exa_account_names(): array {$m=exa_json_file(TT_EXPORT_MASTER_FILE);$out=[];foreach((array)($m['chart']??[]) as $a)if(is_array($a)&&isset($a['code']))$out[(string)$a['code']]=(string)($a['name']??$a['code']);return $out;}
function exa_next_id(array $items,string $prefix): string {$n=count($items)+1;do{$id=$prefix.'-'.gmdate('Y').'-'.str_pad((string)$n,6,'0',STR_PAD_LEFT);$n++;}while(isset($items[$id]));return $id;}
function exa_line(string $account,float $dr,float $cr,array $names,array $extra=[]): array {if(!isset($names[$account]))exa_respond(['ok'=>false,'error'=>'Approved account '.$account.' is missing.'],422);return array_merge(['account'=>$account,'accountName'=>$names[$account],'debit'=>round($dr,2),'credit'=>round($cr,2)],$extra);}
function exa_require_entity(array $u,string $e,bool $write=false):void{if(!in_array($e,['TTI','BRM','TG'],true))exa_respond(['ok'=>false,'error'=>'Select a valid legal entity.'],422);if(($u['role']??'')==='Super Admin')return;$allowed=$write?(tt_user_can_access_entity($u,$e,'Create')||tt_user_can_access_entity($u,$e,'Edit')||tt_user_can_access_entity($u,$e,'Approve')):tt_user_can_access_entity($u,$e,'View');if(!$allowed)exa_respond(['ok'=>false,'error'=>'You do not have permission for this legal entity.'],403);}
function exa_candidate_id(string $entity,string $type,string $sourceKey): string {return $entity.'|'.$type.'|'.$sourceKey;}
function exa_clean_refs(mixed $v): array {if(!is_array($v))return [];return array_values(array_filter(array_map(static fn($x)=>trim((string)$x),$v),static fn($x)=>$x!==''));}

try {
    $user=tt_require_login();$policy=exa_json_file(TT_EXPORT_POLICY_FILE);
    if($_SERVER['REQUEST_METHOD']==='GET'){
        if(!tt_user_can_open_module($user,'Accounts'))exa_respond(['ok'=>false,'error'=>'Accounts permission required.'],403);
        $s=exa_read();$entity=strtoupper(trim((string)($_GET['entity']??'')));exa_require_entity($user,$entity,false);$rows=array_values(array_filter((array)$s['exportCandidates'],static fn($x)=>(string)($x['entity']??'')===$entity));usort($rows,static fn($a,$b)=>strcmp((string)($b['createdAt']??''),(string)($a['createdAt']??'')));exa_respond(['ok'=>true,'candidates'=>$rows,'policy'=>$policy,'accounts'=>exa_account_names(),'serverNow'=>gmdate('c')]);
    }
    if($_SERVER['REQUEST_METHOD']!=='POST')exa_respond(['ok'=>false,'error'=>'Method not allowed.'],405);
    $body=json_decode(file_get_contents('php://input')?:'',true);if(!is_array($body)||!tt_verify_csrf((string)($body['csrf']??'')))exa_respond(['ok'=>false,'error'=>'Your session expired. Refresh and try again.'],419);$action=(string)($body['action']??'');

    if($action==='queue_candidate'){
        if(!exa_module_write($user,'Exports'))exa_respond(['ok'=>false,'error'=>'Exports Create or Edit permission required.'],403);
        $seller=strtoupper(trim((string)($body['sellerEntity']??'')));if(!in_array($seller,['TTI','BRM','TG'],true))exa_respond(['ok'=>false,'error'=>'Unsupported selling entity.'],422);
        $sourceKey=trim((string)($body['sourceKey']??''));if($sourceKey===''||strlen($sourceKey)>180)exa_respond(['ok'=>false,'error'=>'Stable export lot reference required.'],422);
        $stage=ucfirst(strtolower(trim((string)($body['stage']??'Final'))));if(!in_array($stage,['Draft','Final','Reissued'],true))$stage='Final';$onBoard=trim((string)($body['onBoardDate']??''));$commercialDate=trim((string)($body['commercialInvoiceDate']??''));if($stage!=='Draft')$onBoard=exa_date($onBoard,'Final B/L shipped-on-board date');elseif($onBoard===''&&$commercialDate!=='')$onBoard=exa_date($commercialDate,'Commercial Invoice draft date');elseif($onBoard==='')$onBoard=gmdate('Y-m-d');$currency=strtoupper(trim((string)($body['currency']??'')));if(!preg_match('/^[A-Z]{3}$/',$currency))exa_respond(['ok'=>false,'error'=>'Valid transaction currency required.'],422);$amount=exa_positive($body['transactionAmount']??0,'Export transaction amount');$qty=round((float)($body['actualQtyMT']??0),3);if($qty<=0)exa_respond(['ok'=>false,'error'=>'Actual shipped quantity is required.'],422);
        $incoterm=strtoupper(trim((string)($body['incoterm']??'OTHER')))?:'OTHER';$customer=trim((string)($body['customer']??''));$contract=trim((string)($body['contractRef']??''));$lot=trim((string)($body['lotRef']??$sourceKey));$fi=exa_clean_refs($body['fiRefs']??[]);$gd=exa_clean_refs($body['gdRefs']??[]);$bl=trim((string)($body['blNo']??''));$tgInternal=round((float)($body['tgInternalValue']??0),2);$pakistanExporter=strtoupper(trim((string)($body['pakistanExporter']??'TTI')));if(!in_array($pakistanExporter,['TTI','BRM'],true))$pakistanExporter='TTI';
        $indentor=trim((string)($body['indentor']??''));$saleThrough=ucfirst(strtolower(trim((string)($body['saleThrough']??'Direct'))));if(!in_array($saleThrough,['Direct','Indentor'],true))$saleThrough='Direct';$indentorProfile=$indentor!==''?tt_indentor_profile($indentor):null;$indentorRate=round(max(0,(float)($body['indentorCommissionPerMT']??0)),4);if($saleThrough==='Indentor'&&!$indentorProfile)exa_respond(['ok'=>false,'error'=>'Select an active Indentor profile from Business Parties.'],422);if($saleThrough==='Indentor'&&$indentorRate<=0)exa_respond(['ok'=>false,'error'=>'Enter the Indentor commission per metric ton for this export deal.'],422);$bags=max(0,(float)($body['bags']??0));$indentorEstimate=round($qty*$indentorRate,2);$adjustments=[];$names=exa_account_names();foreach((array)($body['adjustments']??[]) as $row){if(!is_array($row))continue;$title=trim((string)($row['title']??''));$direction=ucfirst(strtolower(trim((string)($row['direction']??''))));$value=round(abs((float)($row['amount']??0)),2);if($title===''||$value<=0||!in_array($direction,['Add','Deduct'],true))continue;$matchedCode='';foreach($names as $code=>$name)if(strtolower(trim($name))===strtolower($title)){$matchedCode=(string)$code;break;}$adjustments[]=['id'=>(string)($row['id']??''),'title'=>$title,'direction'=>$direction,'amount'=>$value,'accountCode'=>$matchedCode,'accountReviewRequired'=>$matchedCode===''];}$meta=['actualQtyMT'=>$qty,'incoterm'=>$incoterm,'customer'=>$customer,'contractRef'=>$contract,'lotRef'=>$lot,'blNo'=>$bl,'onBoardDate'=>$onBoard,'commercialInvoiceDate'=>$commercialDate,'commercialInvoiceNo'=>trim((string)($body['commercialInvoiceNo']??'')),'invoiceStage'=>$stage,'fiRefs'=>$fi,'gdRefs'=>$gd,'adjustments'=>$adjustments,'product'=>trim((string)($body['product']??'')),'productIdentityCode'=>trim((string)($body['productIdentityCode']??'')),'baseVariety'=>trim((string)($body['baseVariety']??'')),'riceType'=>trim((string)($body['riceType']??'')),'productStage'=>strtoupper(trim((string)($body['productStage']??'FINISHED'))),'displayName'=>trim((string)($body['displayName']??$body['product']??'')),'saleThrough'=>$saleThrough,'indentor'=>(string)($indentorProfile['name']??''),'indentorCommissionPerMT'=>$indentorRate,'indentorCommissionCurrency'=>$currency,'indentorEstimatedAmount'=>$indentorEstimate,'indentorPayableStatus'=>$saleThrough==='Indentor'?'Estimated — awaiting full invoice payment':'Not applicable','bags'=>$bags,'transactionCurrency'=>$currency,'sourceModule'=>'Exports'];
        tt_ensure_data_dir();$h=fopen(TT_EXPORT_ACCOUNTS_FILE,'c+');if($h===false||!flock($h,LOCK_EX))throw new RuntimeException('Accounts storage unavailable.');
        try{
            rewind($h);$raw=stream_get_contents($h);$store=$raw?json_decode($raw,true):null;if(!is_array($store))$store=exa_default_store();$store=array_replace_recursive(exa_default_store(),$store);
            $id=exa_candidate_id($seller,'CUSTOMER_EXPORT_SALE',$sourceKey);
            $status=$stage==='Draft'?'Draft Estimate — Not Posted':'Pending Accounting Recognition';if(!isset($store['exportCandidates'][$id]))$store['exportCandidates'][$id]=['id'=>$id,'entity'=>$seller,'candidateType'=>'CUSTOMER_EXPORT_SALE','sourceKey'=>$sourceKey,'reference'=>$lot,'transactionCurrency'=>$currency,'transactionAmount'=>$amount,'suggestedRecognitionDate'=>$onBoard,'status'=>$status,'controlConfirmed'=>false,'journalId'=>null,'costOfSalesStatus'=>'Pending inventory-cost layer','meta'=>$meta,'createdAt'=>gmdate('c'),'createdBy'=>(string)($user['full_name']??$user['username']??'Export Staff')];elseif(empty($store['exportCandidates'][$id]['journalId'])){$store['exportCandidates'][$id]=array_merge($store['exportCandidates'][$id],['reference'=>$lot,'transactionCurrency'=>$currency,'transactionAmount'=>$amount,'suggestedRecognitionDate'=>$onBoard,'status'=>$status,'meta'=>$meta,'updatedAt'=>gmdate('c'),'updatedBy'=>(string)($user['full_name']??$user['username']??'Export Staff')]);}
            $linkedId=null;$tgPayableId=null;
            if($seller==='TG'&&$tgInternal>0&&$stage!=='Draft'){
                $linkedId=exa_candidate_id($pakistanExporter,'TG_PAKISTAN_INTERCOMPANY',$sourceKey);$tgPayableId=exa_candidate_id('TG','TG_INTERCOMPANY_PAYABLE',$sourceKey);
                if(!isset($store['exportCandidates'][$linkedId]))$store['exportCandidates'][$linkedId]=['id'=>$linkedId,'entity'=>$pakistanExporter,'candidateType'=>'TG_PAKISTAN_INTERCOMPANY','sourceKey'=>$sourceKey,'reference'=>$lot,'transactionCurrency'=>$currency,'transactionAmount'=>$tgInternal,'suggestedRecognitionDate'=>$onBoard,'status'=>'Pending Accounting Recognition','controlConfirmed'=>false,'journalId'=>null,'costOfSalesStatus'=>'Pending inventory-cost layer','linkedCandidateId'=>$id,'mirrorCandidateId'=>$tgPayableId,'counterparty'=>'TG','meta'=>array_merge($meta,['explicitTGInternalValue'=>$tgInternal]),'createdAt'=>gmdate('c'),'createdBy'=>(string)($user['full_name']??$user['username']??'Export Staff')];
                if(!isset($store['exportCandidates'][$tgPayableId]))$store['exportCandidates'][$tgPayableId]=['id'=>$tgPayableId,'entity'=>'TG','candidateType'=>'TG_INTERCOMPANY_PAYABLE','sourceKey'=>$sourceKey,'reference'=>$lot,'transactionCurrency'=>$currency,'transactionAmount'=>$tgInternal,'suggestedRecognitionDate'=>$onBoard,'status'=>'Pending Accounting Recognition','controlConfirmed'=>false,'journalId'=>null,'costOfSalesStatus'=>'Accounts cost classification required','linkedCandidateId'=>$linkedId,'customerCandidateId'=>$id,'counterparty'=>$pakistanExporter,'meta'=>array_merge($meta,['explicitTGInternalValue'=>$tgInternal,'sourcePakistanEntity'=>$pakistanExporter,'sourceRule'=>'Exact value from Exports; do not re-enter or infer']), 'createdAt'=>gmdate('c'),'createdBy'=>(string)($user['full_name']??$user['username']??'Export Staff')];
                $store['exportCandidates'][$id]['linkedCandidateId']=$linkedId;$store['exportCandidates'][$id]['tgPayableCandidateId']=$tgPayableId;$store['exportCandidates'][$linkedId]['mirrorCandidateId']=$tgPayableId;
            }
            // An AED TG PACK creates its AED supplier liability as soon as the
            // final documents are saved. Inventory is the provisional debit;
            // the eventual cost of sales classification remains an Accounts job.
            if($seller==='TG'&&$currency==='AED'&&$tgPayableId!==null&&empty($store['exportCandidates'][$tgPayableId]['journalId'])){
                $value=round((float)$store['exportCandidates'][$tgPayableId]['transactionAmount'],2);
                $jid=exa_next_id((array)($store['journals']??[]),'AUTO');$linked=$store['exportCandidates'][$tgPayableId];
                $store['journals'][$jid]=['id'=>$jid,'entity'=>'TG','date'=>$onBoard,'sourceType'=>'TG_INTERCOMPANY_PAYABLE_RECOGNIZED','reference'=>$lot,'narration'=>'TG AED PACK supplier payable — '.$lot,
                    'lines'=>[exa_line('1310',$value,0,$names,['sourceCandidateId'=>$tgPayableId,'costClassification'=>'1310']),exa_line('2500',0,$value,$names,['sourceCandidateId'=>$tgPayableId,'liabilityNativeAmount'=>$value,'liabilityCurrency'=>'AED','transactionCurrency'=>'AED','transactionAmount'=>$value,'nativeCurrency'=>'AED','nativeAmount'=>$value,'currentCarryingRate'=>1,'currentCarryingAsOf'=>$onBoard,'counterparty'=>$pakistanExporter])],
                    'totalDebit'=>$value,'totalCredit'=>$value,'status'=>'Posted','meta'=>array_merge((array)($linked['meta']??[]),['candidateId'=>$tgPayableId,'transactionCurrency'=>'AED','transactionAmount'=>$value,'functionalCurrency'=>'AED','functionalRate'=>1,'functionalAmount'=>$value,'costAccount'=>'1310','sourceRule'=>'Final AED TG PACK creates payable at 1:1']),
                    'createdAt'=>gmdate('c'),'createdBy'=>'Exports TG PACK','userId'=>(int)($user['id']??0),'reversalOf'=>null];
                $store['exportCandidates'][$tgPayableId]=array_merge($linked,['journalId'=>$jid,'status'=>'Recognized / Posted','controlConfirmed'=>true,'recognitionDate'=>$onBoard,'functionalCurrency'=>'AED','functionalRate'=>1,'functionalAmount'=>$value,'recognizedAt'=>gmdate('c'),'recognizedBy'=>'Exports TG PACK','costAccount'=>'1310','currentCarryingRate'=>1,'currentCarryingAsOf'=>$onBoard,'paidNative'=>0,'costOfSalesStatus'=>'Inventory recognized — COGS still pending when sold']);
            }
            $store['revision']=(int)($store['revision']??0)+1;rewind($h);if(!ftruncate($h,0))throw new RuntimeException('Accounts storage could not be updated.');$enc=json_encode($store,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);if(fwrite($h,$enc)===false)throw new RuntimeException('Accounts storage could not be written.');fflush($h);$candidate=$store['exportCandidates'][$id];$linked=$linkedId?$store['exportCandidates'][$linkedId]:null;$tgPayable=$tgPayableId?$store['exportCandidates'][$tgPayableId]:null;
        } finally {flock($h,LOCK_UN);fclose($h);}
        exa_respond(['ok'=>true,'candidate'=>$candidate,'linkedCandidate'=>$linked,'tgPayableCandidate'=>$tgPayable]);
    }

    if($action==='recognize_candidate'){
        if(!exa_module_write($user,'Accounts'))exa_respond(['ok'=>false,'error'=>'Accounts Create or Edit permission required.'],403);
        $id=trim((string)($body['candidateId']??''));if($id==='')exa_respond(['ok'=>false,'error'=>'Recognition candidate is required.'],422);$recognitionDate=exa_date((string)($body['recognitionDate']??''),'Recognition date');$functionalCurrency=strtoupper(trim((string)($body['functionalCurrency']??'')));if(!preg_match('/^[A-Z]{3}$/',$functionalCurrency))exa_respond(['ok'=>false,'error'=>'Functional / reporting currency is required.'],422);$rate=exa_positive($body['functionalRate']??0,'Functional-currency conversion rate');$names=exa_account_names();
        tt_ensure_data_dir();$h=fopen(TT_EXPORT_ACCOUNTS_FILE,'c+');if($h===false||!flock($h,LOCK_EX))throw new RuntimeException('Accounts storage unavailable.');
        try{
            rewind($h);$raw=stream_get_contents($h);$store=$raw?json_decode($raw,true):null;if(!is_array($store))$store=exa_default_store();$store=array_replace_recursive(exa_default_store(),$store);$c=$store['exportCandidates'][$id]??null;if(!is_array($c))exa_respond(['ok'=>false,'error'=>'Recognition candidate not found.'],404);if(!empty($c['journalId']))exa_respond(['ok'=>false,'error'=>'This candidate has already been recognized.'],409);
            $entity=(string)$c['entity'];exa_require_entity($user,$entity,true);$expected=$policy['entities'][$entity]['functionalCurrency']??null;if(is_string($expected)&&$expected!==''&&$functionalCurrency!==$expected)exa_respond(['ok'=>false,'error'=>'Functional / reporting currency for '.$entity.' is '.$expected.'.'],422);$functionalAmount=round((float)$c['transactionAmount']*$rate,2);if($functionalAmount<=0)exa_respond(['ok'=>false,'error'=>'Functional-currency amount is invalid.'],422);$type=(string)$c['candidateType'];$costAccount=null;
            if($type==='TG_INTERCOMPANY_PAYABLE'){
                if(($body['controlConfirmed']??false)!==true)exa_respond(['ok'=>false,'error'=>'Confirm the TG intercompany cost classification before posting.'],422);$costAccount=trim((string)($body['costAccount']??''));if(!in_array($costAccount,['1310','1320','5100'],true))exa_respond(['ok'=>false,'error'=>'Select TG Purchased Commodity Inventory, Finished Goods Inventory or Commodity Cost of Sales.'],422);$dr=$costAccount;$cr='2500';
            } else {
                if(($body['controlConfirmed']??false)!==true)exa_respond(['ok'=>false,'error'=>'Control-transfer confirmation is required before revenue can be recognized.'],422);
                if($type==='CUSTOMER_EXPORT_SALE'){$dr='1210';$cr='4100';}
                elseif($type==='TG_PAKISTAN_INTERCOMPANY'){$dr='1240';$cr='4500';}
                else exa_respond(['ok'=>false,'error'=>'Unsupported recognition candidate type.'],422);
            }
            $nativeMeta=['transactionCurrency'=>$c['transactionCurrency'],'transactionAmount'=>$c['transactionAmount'],'nativeCurrency'=>$c['transactionCurrency'],'nativeAmount'=>$c['transactionAmount'],'currentCarryingRate'=>$rate,'currentCarryingAsOf'=>$recognitionDate,'counterparty'=>(string)($c['counterparty']??($c['meta']['customer']??''))];$lines=[exa_line($dr,$functionalAmount,0,$names,$type==='TG_INTERCOMPANY_PAYABLE'?['sourceCandidateId'=>$id,'costClassification'=>$costAccount]:[]),exa_line($cr,0,$functionalAmount,$names,$type==='TG_INTERCOMPANY_PAYABLE'?array_merge(['sourceCandidateId'=>$id,'liabilityNativeAmount'=>$c['transactionAmount'],'liabilityCurrency'=>$c['transactionCurrency']],$nativeMeta):[])];$adjustmentTotal=0.0;$maps=is_array($body['adjustmentAccountMap']??null)?$body['adjustmentAccountMap']:[];if($type==='CUSTOMER_EXPORT_SALE')foreach((array)($c['meta']['adjustments']??[]) as $adj){if(!is_array($adj))continue;$adjId=(string)($adj['id']??'');$account=(string)($adj['accountCode']??'');if($account===''&&isset($maps[$adjId]))$account=trim((string)$maps[$adjId]);if($account===''||!isset($names[$account]))exa_respond(['ok'=>false,'error'=>'Select an approved Accounts ledger for adjustment: '.(string)($adj['title']??'Adjustment').'.'],422);$fa=round((float)($adj['amount']??0)*$rate,2);if($fa<=0)continue;$extra=['sourceCandidateId'=>$id,'exportAdjustmentId'=>$adjId,'exportAdjustmentTitle'=>(string)($adj['title']??''),'transactionCurrency'=>$c['transactionCurrency'],'transactionAmount'=>(float)($adj['amount']??0)];if(($adj['direction']??'')==='Add'){$lines[]=exa_line('1210',$fa,0,$names,$extra);$lines[]=exa_line($account,0,$fa,$names,$extra);}else{$lines[]=exa_line($account,$fa,0,$names,$extra);$lines[]=exa_line('1210',0,$fa,$names,$extra);}$adjustmentTotal+=$fa;}
            $jid=exa_next_id((array)$store['journals'],'AUTO');$meta=array_merge((array)($c['meta']??[]),['candidateId'=>$id,'transactionCurrency'=>$c['transactionCurrency'],'transactionAmount'=>$c['transactionAmount'],'functionalCurrency'=>$functionalCurrency,'functionalRate'=>$rate,'functionalAmount'=>$functionalAmount,'controlConfirmed'=>true,'controlConfirmationNote'=>trim((string)($body['controlConfirmationNote']??'')),'costAccount'=>$costAccount]);
            $sourceType=$type==='CUSTOMER_EXPORT_SALE'?'EXPORT_SALE_RECOGNIZED':($type==='TG_PAKISTAN_INTERCOMPANY'?'TG_INTERCOMPANY_PAKISTAN':'TG_INTERCOMPANY_PAYABLE_RECOGNIZED');$narration=$type==='CUSTOMER_EXPORT_SALE'?'Export sale recognized — '.(string)($c['reference']??''):($type==='TG_PAKISTAN_INTERCOMPANY'?'Pakistan → TG intercompany sale recognized — '.(string)($c['reference']??''):'TG intercompany payable recognized from Pakistan-linked Export — '.(string)($c['reference']??''));
            $store['journals'][$jid]=['id'=>$jid,'entity'=>$entity,'date'=>$recognitionDate,'sourceType'=>$sourceType,'reference'=>(string)($c['reference']??$id),'narration'=>$narration,'lines'=>$lines,'totalDebit'=>round($functionalAmount+$adjustmentTotal,2),'totalCredit'=>round($functionalAmount+$adjustmentTotal,2),'status'=>'Posted','meta'=>$meta,'createdAt'=>gmdate('c'),'createdBy'=>(string)($user['full_name']??$user['username']??'Accounts'),'userId'=>(int)($user['id']??0),'reversalOf'=>null];
            $store['exportCandidates'][$id]['journalId']=$jid;$store['exportCandidates'][$id]['status']='Recognized / Posted';$store['exportCandidates'][$id]['controlConfirmed']=true;$store['exportCandidates'][$id]['recognitionDate']=$recognitionDate;$store['exportCandidates'][$id]['functionalCurrency']=$functionalCurrency;$store['exportCandidates'][$id]['functionalRate']=$rate;$store['exportCandidates'][$id]['functionalAmount']=$functionalAmount;$store['exportCandidates'][$id]['recognizedAt']=gmdate('c');$store['exportCandidates'][$id]['recognizedBy']=(string)($user['full_name']??$user['username']??'Accounts');
            if($type==='TG_INTERCOMPANY_PAYABLE'){$store['exportCandidates'][$id]['costAccount']=$costAccount;$store['exportCandidates'][$id]['currentCarryingRate']=$rate;$store['exportCandidates'][$id]['currentCarryingAsOf']=$recognitionDate;$store['exportCandidates'][$id]['paidNative']=0;$store['exportCandidates'][$id]['costOfSalesStatus']=$costAccount==='5100'?'Cost of sales recognized':'Inventory recognized — COGS still pending when sold';}
            $store['revision']=(int)($store['revision']??0)+1;rewind($h);if(!ftruncate($h,0))throw new RuntimeException('Accounts storage could not be updated.');$enc=json_encode($store,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);if(fwrite($h,$enc)===false)throw new RuntimeException('Accounts storage could not be written.');fflush($h);$candidate=$store['exportCandidates'][$id];$journal=$store['journals'][$jid];
        } finally {flock($h,LOCK_UN);fclose($h);}
        exa_respond(['ok'=>true,'candidate'=>$candidate,'journal'=>$journal]);
    }
    exa_respond(['ok'=>false,'error'=>'Unknown export accounting action.'],422);
} catch(Throwable $e) {exa_respond(['ok'=>false,'error'=>'The export accounting update could not be completed.'],500);}
