<?php
declare(strict_types=1);

require dirname(__DIR__) . '/auth_store.php';
header('Content-Type: application/json; charset=UTF-8');
header('Cache-Control: no-store, no-cache, must-revalidate');

const TT_EXPORT_RECEIPTS_FILE = TT_DATA_DIR . '/accounts.json';
const TT_EXPORT_OPS_FILE = TT_DATA_DIR . '/operations.json';
const TT_EXPORT_STORE_KEY = 'transtrade_export_v3_operational';
const TT_EXPORT_ACCOUNT_MASTER = __DIR__ . '/../accounts/accounting_master_v1.json';
const TT_EXPORT_REALIZATION_POLICY = __DIR__ . '/../accounts/export_realization_policy_v1.json';
const TT_EXPORT_SETTLEMENT_POLICY = __DIR__ . '/../accounts/settlement_policy_v1.json';
const TT_EXPORT_REALIZATION_MASTER_TYPE = 'export_realization_charges';

function er_respond(array $data,int $status=200): never {http_response_code($status);echo json_encode($data,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function er_json(string $path): array {$raw=is_file($path)?file_get_contents($path):false;$v=$raw?json_decode($raw,true):null;if(!is_array($v))throw new RuntimeException('Required Accounts configuration is unavailable.');return $v;}
function er_can_write(array $user): bool {
    if(($user['role']??'')==='Super Admin')return true;$p=$user['permissions']['Accounts']??null;if($p==='all')return true;if(!is_array($p))return false;
    if(in_array('Create',$p,true)||in_array('Edit',$p,true)||in_array('Approve',$p,true))return true;
    foreach($p as $a)if(is_array($a)&&(in_array('Create',$a,true)||in_array('Edit',$a,true)||in_array('Approve',$a,true)))return true;return false;
}
function er_default_store(): array {return ['revision'=>0,'journals'=>[],'exportCandidates'=>[],'exportReceipts'=>[],'bankAccountSettings'=>[]];}
function er_read_accounts(): array {
    tt_ensure_data_dir();if(!is_file(TT_EXPORT_RECEIPTS_FILE))return er_default_store();$h=fopen(TT_EXPORT_RECEIPTS_FILE,'r');if($h===false||!flock($h,LOCK_SH))throw new RuntimeException('Accounts storage unavailable.');
    try{$raw=stream_get_contents($h);}finally{flock($h,LOCK_UN);fclose($h);}$s=$raw?json_decode($raw,true):null;return is_array($s)?array_replace_recursive(er_default_store(),$s):er_default_store();
}
function er_ops_env(string $name): string {$constant='TT_'.$name;if(defined($constant))return(string)constant($constant);$value=getenv($constant);return$value===false?'':(string)$value;}
function er_ops_db_configured(): bool {return er_ops_env('DB_HOST')!==''&&er_ops_env('DB_NAME')!==''&&er_ops_env('DB_USER')!=='';}
function er_ops_db(): PDO {return new PDO('mysql:host='.er_ops_env('DB_HOST').';dbname='.er_ops_env('DB_NAME').';charset=utf8mb4',er_ops_env('DB_USER'),er_ops_env('DB_PASS'),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);}
function er_decode_export_root(mixed $payload): array {$root=is_string($payload)&&$payload!==''?json_decode($payload,true):null;return is_array($root)?$root:[];}
function er_entity(string $v): string {$v=strtoupper(trim($v));if(!in_array($v,['TTI','BRM'],true))er_respond(['ok'=>false,'error'=>'Pakistan export receipts are available for TTI or BRM books.'],422);return $v;}
function er_date(string $v): string {if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$v))er_respond(['ok'=>false,'error'=>'Valid bank credit date is required.'],422);return $v;}
function er_money(mixed $v,string $label,bool $zero=false): float {$n=round((float)$v,2);if($n<0||(!$zero&&$n<=0))er_respond(['ok'=>false,'error'=>$label.' must be '.($zero?'zero or greater':'greater than zero').'.'],422);return $n;}
function er_currency(string $v): string {$v=strtoupper(trim($v));if(!preg_match('/^[A-Z]{3}$/',$v))er_respond(['ok'=>false,'error'=>'Valid receipt currency required.'],422);return $v;}
function er_next_id(array $items,string $prefix): string {$n=count($items)+1;do{$id=$prefix.'-'.gmdate('Y').'-'.str_pad((string)$n,6,'0',STR_PAD_LEFT);$n++;}while(isset($items[$id]));return $id;}
function er_catalog(): array {
    $out=[];$m=er_json(TT_EXPORT_ACCOUNT_MASTER);foreach((array)($m['chart']??[]) as $a)if(is_array($a)&&isset($a['code']))$out[(string)$a['code']]=$a;
    $p=er_json(TT_EXPORT_REALIZATION_POLICY);foreach((array)($p['accounts']??[]) as $a)if(is_array($a)&&isset($a['code']))$out[(string)$a['code']]=$a;
    $s=er_json(TT_EXPORT_SETTLEMENT_POLICY);foreach((array)($s['accounts']??[]) as $a)if(is_array($a)&&isset($a['code']))$out[(string)$a['code']]=$a;return $out;
}
function er_line(string $account,float $dr,float $cr,array $catalog,array $extra=[]): array {if(!isset($catalog[$account]))er_respond(['ok'=>false,'error'=>'Accounting mapping '.$account.' is not configured.'],422);return array_merge(['account'=>$account,'accountName'=>(string)($catalog[$account]['name']??$account),'debit'=>round($dr,2),'credit'=>round($cr,2)],$extra);}
function er_post_journal(array &$store,array $user,string $entity,string $date,string $sourceType,string $reference,string $narration,array $lines,array $meta): array {
    $dr=round(array_sum(array_column($lines,'debit')),2);$cr=round(array_sum(array_column($lines,'credit')),2);if($dr<=0||abs($dr-$cr)>.01)throw new RuntimeException('Export receipt journal did not balance.');
    $id=er_next_id((array)$store['journals'],'AUTO');$store['journals'][$id]=['id'=>$id,'entity'=>$entity,'date'=>$date,'sourceType'=>$sourceType,'reference'=>$reference,'narration'=>$narration,'lines'=>$lines,'totalDebit'=>$dr,'totalCredit'=>$cr,'status'=>'Posted','meta'=>$meta,'createdAt'=>gmdate('c'),'createdBy'=>(string)($user['full_name']??$user['username']??'Accounts'),'userId'=>(int)($user['id']??0),'reversalOf'=>null];return $store['journals'][$id];
}
function er_operations_root(): array {
    if(er_ops_db_configured()){$db=er_ops_db();$q=$db->prepare('SELECT payload FROM tt_operation_records WHERE storage_key=? LIMIT 1');$q->execute([TT_EXPORT_STORE_KEY]);return er_decode_export_root($q->fetchColumn());}
    if(!is_file(TT_EXPORT_OPS_FILE))return [];$h=fopen(TT_EXPORT_OPS_FILE,'r');if($h===false||!flock($h,LOCK_SH))throw new RuntimeException('Export operational storage unavailable.');try{$raw=stream_get_contents($h);}finally{flock($h,LOCK_UN);fclose($h);}$s=$raw?json_decode($raw,true):null;if(!is_array($s))return [];return er_decode_export_root($s['values'][TT_EXPORT_STORE_KEY]??'');
}
function er_contract_value(array $c): float {if(isset($c['contractValue'])&&(float)$c['contractValue']>0)return round((float)$c['contractValue'],2);$n=0.0;foreach((array)($c['packings']??[]) as $p)if(is_array($p))$n+=(float)($p['containers']??0)*(float)($p['weightPer']??0)*(float)($p['price']??0);if($n<=0)$n=(float)($c['qty']??0)*(float)($c['price']??0);return round($n,2);}
function er_sources(array $accounts,string $entity): array {
    $root=er_operations_root();$contracts=[];$invoices=[];$indentorPayables=[];$contractMap=[];
    foreach((array)($root['contracts']??[]) as $c){if(!is_array($c))continue;$seller=strtoupper((string)($c['seller']??'TTI'));$ref=trim((string)($c['ref']??$c['id']??''));$exporters=[$seller];if($seller==='TG'){$exporters=[];foreach((array)($root['shipments']??[]) as $linkedShipment){if(!is_array($linkedShipment)||($linkedShipment['contractRef']??'')!==$ref||($linkedShipment['kind']??'')!=='lot'||!empty($linkedShipment['cancelled']))continue;$actual=strtoupper((string)($linkedShipment['customs']['exporter']??''));if(in_array($actual,['TTI','BRM'],true))$exporters[$actual]=$actual;}if(!$exporters)$exporters=['TTI'];}if(!in_array($entity,$exporters,true))continue;$pkExporter=$entity;if($ref==='')continue;$cur=strtoupper(trim((string)($c['currency']??'USD')))?:'USD';$val=er_contract_value($c);$pct=(float)($c['advancePct']??0);if((string)($c['paymentCode']??'')==='ADV100')$pct=100;$contractRow=['id'=>(string)($c['id']??$ref),'ref'=>$ref,'seller'=>$seller,'pakistanExporter'=>$pkExporter,'customer'=>(string)($c['customer']??''),'currency'=>$cur,'contractValue'=>$val,'paymentCode'=>(string)($c['paymentCode']??''),'paymentText'=>(string)($c['paymentText']??''),'advancePct'=>$pct,'expectedAdvance'=>round($val*$pct/100,2),'status'=>(string)($c['status']??''),'saleThrough'=>(string)($c['saleThrough']??'Direct'),'indentor'=>(string)($c['indentor']??''),'indentorCommissionPerMT'=>round((float)($c['indentorCommissionPerMT']??0),4)];$contracts[]=$contractRow;$contractMap[$ref]=$contractRow;}
    $receiptRows=(array)($accounts['exportReceipts']??[]);
    $advanceReceived=[];
    foreach($receiptRows as $receipt){
        if(!is_array($receipt)||($receipt['entity']??'')!==$entity)continue;
        foreach((array)($receipt['allocations']??[]) as $allocation){
            if(!is_array($allocation)||($allocation['targetType']??'')!=='UNAPPLIED_ADVANCE')continue;
            $advanceRef=trim((string)($allocation['contractRef']??''));if($advanceRef==='')continue;
            $advanceReceived[$advanceRef]=round((float)($advanceReceived[$advanceRef]??0)+(float)($allocation['foreignAmount']??0),2);
        }
    }
    foreach($contracts as &$contract){$received=round((float)($advanceReceived[$contract['ref']]??0),2);$contract['receivedAdvance']=$received;$contract['outstandingAdvance']=max(0,round((float)$contract['expectedAdvance']-$received,2));$contractMap[$contract['ref']]=$contract;}unset($contract);
    foreach((array)($accounts['exportCandidates']??[]) as $cid=>$c){if(!is_array($c)||($c['entity']??'')!==$entity)continue;$meta=is_array($c['meta']??null)?$c['meta']:[];$type=(string)($c['candidateType']??'');if(!in_array($type,['CUSTOMER_EXPORT_SALE','TG_PAKISTAN_INTERCOMPANY'],true))continue;$foreign=round((float)($c['transactionAmount']??0),2);$received=0.0;foreach($receiptRows as $r)if(is_array($r)&&($r['entity']??'')===$entity)foreach((array)($r['allocations']??[]) as $a)if(is_array($a)&&(string)($a['targetId']??'')===(string)$cid)$received+=round((float)($a['foreignAmount']??0),2);$invoices[]=['id'=>(string)$cid,'reference'=>(string)($c['reference']??$cid),'candidateType'=>$type,'mirrorCandidateId'=>(string)($c['mirrorCandidateId']??''),'contractRef'=>(string)($meta['contractRef']??''),'customer'=>(string)($meta['customer']??($c['counterparty']??'')),'currency'=>(string)($c['transactionCurrency']??$meta['transactionCurrency']??'USD'),'foreignAmount'=>$foreign,'receivedForeign'=>round($received,2),'outstandingForeign'=>max(0,round($foreign-$received,2)),'recognized'=>!empty($c['journalId']),'recognitionStatus'=>(string)($c['status']??''),'functionalAmount'=>round((float)($c['functionalAmount']??0),2),'fiRefs'=>(array)($meta['fiRefs']??[]),'gdRefs'=>(array)($meta['gdRefs']??[]),'blNo'=>(string)($meta['blNo']??''),'indentor'=>(string)($meta['indentor']??''),'indentorCommissionPerMT'=>round((float)($meta['indentorCommissionPerMT']??0),4),'indentorPayableStatus'=>(string)($meta['indentorPayableStatus']??''),'indentorPayableJournalId'=>(string)($meta['indentorPayableJournalId']??'')];}
    foreach((array)($root['shipments']??[]) as $s){if(!is_array($s))continue;$commercial=is_array($s['commercial']??null)?$s['commercial']:[];if(empty($commercial['saved']))continue;$ref=(string)($s['id']??$s['lotRef']??$s['contractRef']??'');$contractRef=(string)($s['contractRef']??'');$candidate=null;foreach($invoices as $iv)if($iv['reference']===$ref||($contractRef!==''&&$iv['contractRef']===$contractRef&&count($invoices)===1)){$candidate=$iv;break;}if($candidate)continue;$contract=null;foreach($contracts as $cc)if($cc['ref']===$contractRef){$contract=$cc;break;}if(!$contract)continue;$amount=round((float)($commercial['invoiceGross']??0),2);if($amount<=0)$amount=round((float)($commercial['netAmount']??0),2);$invoices[]=['id'=>'OPS|'.$ref,'reference'=>(string)($commercial['invoiceNo']??$ref),'candidateType'=>'UNRECOGNIZED_OPERATIONAL_INVOICE','contractRef'=>$contractRef,'customer'=>(string)($s['buyer']??$contract['customer']),'currency'=>$contract['currency'],'foreignAmount'=>$amount,'receivedForeign'=>0,'outstandingForeign'=>$amount,'recognized'=>false,'recognitionStatus'=>'Invoice exists in Exports — receivable not yet recognized','functionalAmount'=>0,'fiRefs'=>[],'gdRefs'=>[],'blNo'=>(string)(($s['bl']['blNo']??''))];}
    foreach((array)($root['shipments']??[]) as $shipment){
        if(!is_array($shipment)||($shipment['kind']??'')!=='lot'||!empty($shipment['cancelled']))continue;$contractRef=trim((string)($shipment['contractRef']??''));$contract=$contractMap[$contractRef]??null;if(!is_array($contract)||($contract['saleThrough']??'')!=='Indentor'||trim((string)($contract['indentor']??''))===''||(float)($contract['indentorCommissionPerMT']??0)<=0)continue;
        $rows=is_array($shipment['millActuals']??null)?$shipment['millActuals']:[];$loaded=[];foreach($rows as $row)if(is_array($row)&&trim((string)($row['number']??''))!==''&&(float)($row['netKg']??0)>0)$loaded[]=$row;if(!$loaded)continue;$qtyMt=round(array_sum(array_map(static fn($row)=>(float)($row['netKg']??0),$loaded))/1000,3);if($qtyMt<=0)continue;
        $candidate=null;foreach((array)($accounts['exportCandidates']??[]) as $cid=>$entry){if(!is_array($entry)||($entry['entity']??'')!==$entity)continue;$meta=is_array($entry['meta']??null)?$entry['meta']:[];if((string)($meta['contractRef']??'')===$contractRef&&((string)($meta['lotRef']??'')===(string)($shipment['lotId']??'')||(string)($entry['reference']??'')===(string)($shipment['lotId']??''))){$candidate=['id'=>(string)$cid,'meta'=>$meta];break;}}
        $firmJournal=(string)($candidate['meta']['indentorPayableJournalId']??'');$indentorPayables[]=['contractRef'=>$contractRef,'lotRef'=>(string)($shipment['lotId']??$shipment['id']??''),'indentor'=>(string)$contract['indentor'],'currency'=>(string)$contract['currency'],'loadedQtyMT'=>$qtyMt,'commissionPerMT'=>(float)$contract['indentorCommissionPerMT'],'nativeAmount'=>round($qtyMt*(float)$contract['indentorCommissionPerMT'],2),'status'=>$firmJournal!==''?'Firm — awaiting contract closure':'Estimated — loaded, awaiting full invoice payment','journalId'=>$firmJournal];
    }
    usort($contracts,static fn($a,$b)=>strcmp((string)$b['ref'],(string)$a['ref']));usort($invoices,static fn($a,$b)=>strcmp((string)$b['reference'],(string)$a['reference']));usort($indentorPayables,static fn($a,$b)=>strcmp((string)$b['contractRef'],(string)$a['contractRef']));return ['contracts'=>$contracts,'invoices'=>$invoices,'indentorPayables'=>$indentorPayables];
}
function er_entity_from_linked(string $linked): string {$u=strtoupper($linked);if(str_contains($u,'BRM')||str_contains($u,'BUKSH RICE'))return 'BRM';if(str_contains($u,'TTI')||str_contains($u,'TRANSTRADE INTERNATIONAL'))return 'TTI';if(str_contains($u,'TG')||str_contains($u,'TRANS GRAINS'))return 'TG';return '';}
function er_bank_master(string $id,string $entity): array {$masters=tt_list_masters();foreach((array)($masters['banks']??[]) as $row){if(!is_array($row)||(string)($row['id']??'')!==$id)continue;$v=array_values((array)($row['values']??[]));while(count($v)<14)$v[]='';if(er_entity_from_linked((string)$v[1])!==$entity)er_respond(['ok'=>false,'error'=>'Selected bank does not belong to these company books.'],422);return ['id'=>$id,'accountType'=>(string)$v[0],'entity'=>$entity,'accountTitle'=>(string)$v[3],'bankName'=>(string)$v[4],'currency'=>strtoupper(trim((string)$v[7])),'accountNumber'=>(string)$v[8],'iban'=>(string)$v[9],'masterStatus'=>(string)$v[13]];}er_respond(['ok'=>false,'error'=>'Selected bank account was not found.'],404);}
function er_receipt_bank(array $store,string $id,string $entity,string $requiredCurrency,bool $requireRetention=true): array {$b=er_bank_master($id,$entity);if(($b['accountType']??'')!=='Company Account')er_respond(['ok'=>false,'error'=>'A company bank account is required.'],422);if(($b['currency']??'')!==$requiredCurrency)er_respond(['ok'=>false,'error'=>'Selected bank must be a '.$requiredCurrency.' account for this receipt component.'],422);if(strcasecmp((string)($b['masterStatus']??'Active'),'Active')!==0)er_respond(['ok'=>false,'error'=>'Selected bank is inactive in Company Master.'],422);$settings=$store['bankAccountSettings'][$id]??null;$complete=trim((string)$b['accountNumber'])!==''||trim((string)$b['iban'])!=='';if(!$complete)er_respond(['ok'=>false,'error'=>'Complete the account number or IBAN in Company Master before receiving money.'],422);$default=$entity!=='TG';$s=is_array($settings)?$settings:['active'=>$default,'allowReceipts'=>$default];if(empty($s['active'])||empty($s['allowReceipts']))er_respond(['ok'=>false,'error'=>'Selected bank is not active/enabled for receipts in Accounts.'],422);if($requireRetention&&$requiredCurrency!=='PKR'&&!tt_bank_is_retention($id,$store))er_respond(['ok'=>false,'error'=>'Foreign retention can only be credited to a bank marked Foreign Retention Account in Accounts.'],422);return $b;}
function er_master_rows(): array {$m=tt_list_masters();$out=[];foreach((array)($m[TT_EXPORT_REALIZATION_MASTER_TYPE]??[]) as $row){if(!is_array($row))continue;$v=array_values((array)($row['values']??[]));while(count($v)<15)$v[]='';$out[(string)$v[1]]=['id'=>(string)($row['id']??''),'name'=>(string)$v[0],'code'=>(string)$v[1],'category'=>(string)$v[2],'regime'=>(string)$v[3],'base'=>(string)$v[4],'rate'=>(string)$v[5],'effectiveFrom'=>(string)$v[6],'effectiveTo'=>(string)$v[7],'treatment'=>(string)$v[8],'account'=>(string)$v[9],'certificate'=>(string)$v[10],'entities'=>(string)$v[11],'status'=>(string)$v[12],'notes'=>(string)$v[13],'nature'=>(string)$v[14]];}return $out;}
function er_rule_active(array $r,string $date,string $entity): bool {$status=strtolower((string)($r['status']??''));if(str_contains($status,'inactive'))return false;$from=(string)($r['effectiveFrom']??'');$to=(string)($r['effectiveTo']??'');if($from!==''&&$date<$from)return false;if($to!==''&&$date>$to)return false;$entities=strtoupper((string)($r['entities']??''));if($entities!==''&&!str_contains($entities,$entity))return false;return true;}
function er_tax_family(string $code): string {$c=strtoupper(trim($code));if(str_starts_with($c,'EXP-AWT-NTR'))return 'EXP-AWT-NTR';if(str_starts_with($c,'EXP-WHT-FIXED'))return 'EXP-WHT-FIXED';if(str_starts_with($c,'EXP-WHT-FTR'))return 'EXP-WHT-FTR';return '';}
function er_prior_allocated(array $store,string $candidateId): float {$n=0.0;foreach((array)($store['exportReceipts']??[]) as $r)if(is_array($r))foreach((array)($r['allocations']??[]) as $a)if(is_array($a)&&(string)($a['targetId']??'')===$candidateId)$n+=(float)($a['foreignAmount']??0);return round($n,2);}
function er_pending_tg(array $store,string $entity): array {
    $linked=[];foreach((array)($store['exportReceipts']??[]) as $r)if(is_array($r)&&($r['entity']??'')===$entity&&($r['tgPaymentId']??'')!=='')$linked[(string)$r['tgPaymentId']]=true;
    $out=[];foreach((array)($store['tgBankTransactions']??[]) as $tx){
        if(!is_array($tx)||($tx['kind']??'')!=='Payment'||($tx['paymentType']??'')!=='LIABILITY'||str_starts_with((string)($tx['notes']??''),'Mirrored settlement for Pakistan receipt '))continue;
        $id=(string)($tx['id']??'');if($id===''||isset($linked[$id]))continue;
        $tg=$store['exportCandidates'][(string)($tx['sourceLiabilityId']??'')]??null;
        if(!is_array($tg)||($tg['entity']??'')!=='TG'||($tg['candidateType']??'')!=='TG_INTERCOMPANY_PAYABLE'||($tg['counterparty']??'')!==$entity)continue;
        $pkId=(string)($tg['linkedCandidateId']??'');$pk=$store['exportCandidates'][$pkId]??null;
        if(!is_array($pk)||($pk['entity']??'')!==$entity||($pk['candidateType']??'')!=='TG_PAKISTAN_INTERCOMPANY')continue;
        $out[]=['id'=>$id,'candidateId'=>$pkId,'amount'=>(float)($tx['amountNative']??0),'currency'=>(string)($tx['currency']??''),'date'=>(string)($tx['date']??''),'invoiceRef'=>(string)($tx['invoiceRef']??$tg['reference']??''),'gdRef'=>(string)($tx['gdRef']??''),'fiRef'=>(string)($tx['fiRef']??''),'bankReference'=>(string)($tx['bankReference']??''),'sourceBank'=>(string)($tx['bank']??''),'sourceBankId'=>(string)($tx['bankAccountId']??'')];
    }
    return $out;
}
function er_prepare_allocations(array $store,string $entity,string $currency,float $foreign,float $grossPkr,array $raw): array {
    if(!$raw)er_respond(['ok'=>false,'error'=>'Allocate the foreign receipt to an invoice/intercompany receivable or an advance source.'],422);$out=[];$sum=0.0;$realizedAssigned=0.0;$requestAllocated=[];$requestAdvances=[];$candidates=(array)($store['exportCandidates']??[]);$sourceData=er_sources($store,$entity);$contracts=[];foreach((array)($sourceData['contracts']??[]) as $contract)if(is_array($contract)&&isset($contract['ref']))$contracts[(string)$contract['ref']]=$contract;
    foreach($raw as $a){if(!is_array($a))continue;$fa=er_money($a['foreignAmount']??0,'Allocation amount');$sum+=$fa;$targetType=strtoupper(trim((string)($a['targetType']??'')));$targetId=trim((string)($a['targetId']??''));$contractRef=trim((string)($a['contractRef']??''));$invoiceRef=trim((string)($a['invoiceRef']??''));$customer=trim((string)($a['customer']??''));$realized=round($grossPkr*($fa/$foreign),2);$realizedAssigned+=$realized;
        if(in_array($targetType,['EXPORT_RECEIVABLE','INTERCOMPANY_RECEIVABLE'],true)){
            $c=$candidates[$targetId]??null;if(!is_array($c)||($c['entity']??'')!==$entity||empty($c['journalId']))er_respond(['ok'=>false,'error'=>'A selected receivable has not been recognized/posted yet. Use Contract / Unapplied Advance until recognition.'],422);$ccur=strtoupper((string)($c['transactionCurrency']??''));if($ccur!==$currency)er_respond(['ok'=>false,'error'=>'Receipt currency does not match one of the selected receivables.'],422);$total=(float)($c['transactionAmount']??0);$prior=er_prior_allocated($store,$targetId);$requestAllocated[$targetId]=round((float)($requestAllocated[$targetId]??0)+$fa,2);if($requestAllocated[$targetId]>$total-$prior+.01)er_respond(['ok'=>false,'error'=>'Combined receipt allocations exceed the outstanding foreign amount on '.$targetId.'.'],422);$carrying=round((float)($c['functionalAmount']??0)*($fa/max(.000001,$total)),2);$meta=is_array($c['meta']??null)?$c['meta']:[];$expectedType=(string)($c['candidateType']??'')==='TG_PAKISTAN_INTERCOMPANY'?'INTERCOMPANY_RECEIVABLE':'EXPORT_RECEIVABLE';if($targetType!==$expectedType)er_respond(['ok'=>false,'error'=>'Selected receivable type does not match the accounting source.'],422);$out[]=['targetType'=>$targetType,'targetId'=>$targetId,'foreignAmount'=>$fa,'realizedPkr'=>$realized,'carryingPkr'=>$carrying,'contractRef'=>(string)($meta['contractRef']??$contractRef),'invoiceRef'=>(string)($c['reference']??$invoiceRef),'customer'=>(string)($meta['customer']??$customer),'fiRefs'=>(array)($meta['fiRefs']??[])];
        }elseif($targetType==='UNAPPLIED_ADVANCE'){
            $contract=$contracts[$contractRef]??null;if(!is_array($contract)||strtoupper((string)($contract['seller']??''))!==$entity)er_respond(['ok'=>false,'error'=>'Select a valid direct export contract for this customer advance.'],422);
            if(strtoupper((string)($contract['currency']??''))!==$currency)er_respond(['ok'=>false,'error'=>'Advance currency does not match the selected contract.'],422);
            if($customer!==''&&strcasecmp(trim((string)($contract['customer']??'')),$customer)!==0)er_respond(['ok'=>false,'error'=>'Advance customer does not match the selected contract.'],422);
            $requestAdvances[$contractRef]=round((float)($requestAdvances[$contractRef]??0)+$fa,2);$outstanding=round((float)($contract['outstandingAdvance']??0),2);if($requestAdvances[$contractRef]>$outstanding+.01)er_respond(['ok'=>false,'error'=>'Combined receipt allocations exceed the outstanding advance on '.$contractRef.'.'],422);
            $out[]=['targetType'=>$targetType,'targetId'=>'ADV|'.$contractRef,'foreignAmount'=>$fa,'realizedPkr'=>$realized,'carryingPkr'=>$realized,'contractRef'=>$contractRef,'invoiceRef'=>'','customer'=>(string)($contract['customer']??$customer)];
        }
        else er_respond(['ok'=>false,'error'=>'Select a valid receipt allocation type.'],422);
    }
    if(abs($sum-$foreign)>.01)er_respond(['ok'=>false,'error'=>'Invoice / advance allocations must equal the full foreign receipt amount.'],422);if($out){$delta=round($grossPkr-$realizedAssigned,2);$out[count($out)-1]['realizedPkr']=round($out[count($out)-1]['realizedPkr']+$delta,2);if($out[count($out)-1]['targetType']==='UNAPPLIED_ADVANCE')$out[count($out)-1]['carryingPkr']=$out[count($out)-1]['realizedPkr'];}return $out;
}
function er_prepare_deductions(string $entity,string $date,array $raw,array $catalog): array {$masters=er_master_rows();$out=[];$deducted=0.0;$separate=0.0;$taxDeducted=[];$taxSeparate=[];foreach($raw as $d){if(!is_array($d))continue;$code=strtoupper(trim((string)($d['masterCode']??'')));$amount=er_money($d['amount']??0,'Deduction amount');$m=$masters[$code]??null;if(!is_array($m))er_respond(['ok'=>false,'error'=>'Selected export tax/charge master row was not found: '.$code],422);if(!er_rule_active($m,$date,$entity)&&!str_contains(strtolower((string)$m['status']),'historical'))er_respond(['ok'=>false,'error'=>$m['name'].' is not active for this receipt date/entity.'],422);$account=(string)($m['account']??'');if(!isset($catalog[$account]))er_respond(['ok'=>false,'error'=>'GL mapping '.$account.' for '.$m['name'].' is not configured in Accounts policy.'],422);$mode=strtoupper(trim((string)($d['mode']??'DEDUCTED')));if(!in_array($mode,['DEDUCTED','SEPARATE_DEBIT'],true))$mode='DEDUCTED';$row=['masterId'=>$m['id'],'masterCode'=>$code,'name'=>$m['name'],'category'=>$m['category'],'regime'=>$m['regime'],'amount'=>$amount,'account'=>$account,'mode'=>$mode,'taxSection'=>trim((string)($d['taxSection']??'')),'certificateRequired'=>str_starts_with(strtoupper((string)$m['certificate']),'YES')];$out[]=$row;if($mode==='DEDUCTED')$deducted+=$amount;else $separate+=$amount;if(er_tax_family($code)!==''){if($mode==='DEDUCTED')$taxDeducted[]=$row;else $taxSeparate[]=$row;}}
    return ['rows'=>$out,'deducted'=>round($deducted,2),'separate'=>round($separate,2),'taxDeducted'=>$taxDeducted,'taxSeparate'=>$taxSeparate];}
function er_tax_meta(array $rows,array $bank): array {return array_map(static fn($d)=>['taxCode'=>$d['masterCode'],'taxSection'=>$d['taxSection'],'amount'=>$d['amount'],'bankAccountId'=>$bank['id'],'bankName'=>$bank['bankName'],'regime'=>$d['regime']],$rows);}
function er_export_receipt_rows(array $receipt): array {
    $rows=[];
    foreach((array)($receipt['allocations']??[]) as $i=>$allocation){
        if(!is_array($allocation))continue;$contractRef=trim((string)($allocation['contractRef']??''));if($contractRef==='')continue;
        $rows[]=['id'=>(string)$receipt['id'].'-'.($i+1),'receiptNo'=>(string)$receipt['id'],'_accountsReceiptId'=>(string)$receipt['id'],'contractRef'=>$contractRef,'invoiceRef'=>(string)($allocation['invoiceRef']??''),'date'=>(string)$receipt['date'],'amount'=>(float)($allocation['foreignAmount']??0),'currency'=>(string)$receipt['transactionCurrency'],'status'=>'Posted','source'=>'Accounts Bank Receipt','bankAdviceRef'=>(string)$receipt['bankAdviceRef']];
    }
    return $rows;
}
function er_merge_export_receipt(array $root,array $receipt): array {
    $existing=[];foreach((array)($root['accountsReceipts']??[]) as $row)if(!is_array($row)||(string)($row['_accountsReceiptId']??'')!==(string)$receipt['id'])$existing[]=$row;
    $root['accountsReceipts']=array_values(array_merge($existing,er_export_receipt_rows($receipt)));return $root;
}
function er_write_export_receipts_to_ops(array $receipt): void {
    if(er_ops_db_configured()){
        $db=er_ops_db();$db->beginTransaction();
        try{
            $select=$db->prepare('SELECT payload,version FROM tt_operation_records WHERE storage_key=? FOR UPDATE');$select->execute([TT_EXPORT_STORE_KEY]);$record=$select->fetch();
            if(!is_array($record))throw new RuntimeException('Current Export V3 operational record was not found.');
            $root=er_merge_export_receipt(er_decode_export_root($record['payload']??''),$receipt);$payload=json_encode($root,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);$version=(int)($record['version']??0)+1;$now=gmdate('Y-m-d H:i:s.u');
            $update=$db->prepare('UPDATE tt_operation_records SET payload=?,version=?,updated_at=?,updated_by=?,updated_by_user=?,updated_by_module=? WHERE storage_key=?');$update->execute([$payload,$version,$now,'Accounts Receipt Engine',null,'Accounts',TT_EXPORT_STORE_KEY]);
            $history=$db->prepare('INSERT INTO tt_operation_history (storage_key,version,payload_sha256,updated_at,updated_by,updated_by_user,updated_by_module) VALUES (?,?,?,?,?,?,?)');$history->execute([TT_EXPORT_STORE_KEY,$version,hash('sha256',$payload),$now,'Accounts Receipt Engine',null,'Accounts']);$db->commit();return;
        }catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
    }
    tt_ensure_data_dir();$h=fopen(TT_EXPORT_OPS_FILE,'c+');if($h===false||!flock($h,LOCK_EX))throw new RuntimeException('Export operational storage unavailable.');
    try{
        rewind($h);$raw=stream_get_contents($h);$ops=$raw?json_decode($raw,true):null;if(!is_array($ops))$ops=['revision'=>0,'values'=>[],'meta'=>[]];$root=er_decode_export_root($ops['values'][TT_EXPORT_STORE_KEY]??'');if(!$root)throw new RuntimeException('Current Export V3 operational record was not found.');
        $root=er_merge_export_receipt($root,$receipt);$ops['values'][TT_EXPORT_STORE_KEY]=json_encode($root,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);$ops['revision']=(int)($ops['revision']??0)+1;$keyVersion=(int)($ops['meta'][TT_EXPORT_STORE_KEY]['version']??0)+1;$ops['meta'][TT_EXPORT_STORE_KEY]=['version'=>$keyVersion,'updatedAt'=>gmdate('c'),'updatedBy'=>'Accounts Receipt Engine','userId'=>0,'module'=>'Accounts'];
        rewind($h);if(!ftruncate($h,0))throw new RuntimeException('Export operational storage could not be updated.');if(fwrite($h,json_encode($ops,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR))===false)throw new RuntimeException('Export operational storage could not be updated.');fflush($h);
    }finally{flock($h,LOCK_UN);fclose($h);}
}

try{
    $user=tt_require_login();if(!tt_user_can_open_module($user,'Accounts'))er_respond(['ok'=>false,'error'=>'Accounts permission required.'],403);
    if($_SERVER['REQUEST_METHOD']==='GET'){$entity=er_entity((string)($_GET['entity']??'TTI'));$store=er_read_accounts();$sources=er_sources($store,$entity);$masters=array_values(er_master_rows());$receipts=[];foreach((array)$store['exportReceipts'] as $r)if(is_array($r)&&($r['entity']??'')===$entity)$receipts[]=$r;usort($receipts,static fn($a,$b)=>strcmp((string)($b['date']??''),(string)($a['date']??''))?:strcmp((string)($b['id']??''),(string)($a['id']??'')));er_respond(['ok'=>true,'entity'=>$entity,'sources'=>$sources,'deductionMaster'=>$masters,'receipts'=>$receipts,'pendingTg'=>er_pending_tg($store,$entity),'serverNow'=>gmdate('c')]);}
    if($_SERVER['REQUEST_METHOD']!=='POST')er_respond(['ok'=>false,'error'=>'Method not allowed.'],405);if(!er_can_write($user))er_respond(['ok'=>false,'error'=>'Accounts Create / Edit / Approve permission required.'],403);
    $body=json_decode(file_get_contents('php://input')?:'{}',true);if(!is_array($body)||!tt_verify_csrf((string)($body['csrf']??'')))er_respond(['ok'=>false,'error'=>'Your session expired. Refresh and try again.'],419);if((string)($body['action']??'')!=='post_receipt')er_respond(['ok'=>false,'error'=>'Unknown export receipt action.'],422);
    $entity=er_entity((string)($body['entity']??''));$date=er_date((string)($body['date']??''));$currency=er_currency((string)($body['transactionCurrency']??''));$foreign=er_money($body['foreignAmount']??0,'Foreign receipt amount');$rate=er_money($body['realizationRate']??0,'Bank realization rate');$gross=er_money($body['grossPkrEquivalent']??($foreign*$rate),'Gross PKR equivalent');$bankCredit=er_money($body['pkrBankCredit']??0,'Actual PKR bank credit',true);$bankId=trim((string)($body['bankAccountId']??''));$bankRef=trim((string)($body['bankAdviceRef']??''));if($bankRef==='')er_respond(['ok'=>false,'error'=>'Bank advice / transaction reference is required to prevent duplicate posting.'],422);$retentionForeign=er_money($body['retentionForeignAmount']??0,'Retention foreign amount',true);if($retentionForeign>$foreign+.0001)er_respond(['ok'=>false,'error'=>'Retention amount cannot exceed the foreign receipt.'],422);$retentionPkr=round($retentionForeign*$rate,2);$retentionBankId=trim((string)($body['retentionBankAccountId']??''));$shortfallClassification=strtoupper(trim((string)($body['shortfallClassification']??'')));$shortfallNote=trim((string)($body['shortfallNote']??''));if($shortfallClassification!==''&&!in_array($shortfallClassification,['PARTIAL','CORRESPONDENT','OTHER'],true))er_respond(['ok'=>false,'error'=>'Select a valid shortfall treatment.'],422);if($shortfallClassification==='OTHER'&&$shortfallNote==='')er_respond(['ok'=>false,'error'=>'Explain the other shortfall reason.'],422);$catalog=er_catalog();
    tt_ensure_data_dir();$h=fopen(TT_EXPORT_RECEIPTS_FILE,'c+');if($h===false||!flock($h,LOCK_EX))throw new RuntimeException('Accounts storage unavailable.');
    try{
        rewind($h);$raw=stream_get_contents($h);$store=$raw?json_decode($raw,true):null;if(!is_array($store))$store=er_default_store();$store=array_replace_recursive(er_default_store(),$store);
        foreach((array)$store['exportReceipts'] as $r)if(is_array($r)&&($r['entity']??'')===$entity&&(string)($r['bankAccountId']??'')===$bankId&&strcasecmp((string)($r['bankAdviceRef']??''),$bankRef)===0)er_respond(['ok'=>false,'error'=>'This bank advice/reference has already been posted for the selected bank.'],409);
        $tgPaymentId=trim((string)($body['tgPaymentId']??''));$tgPayment=null;
        if($tgPaymentId!==''){
            foreach(er_pending_tg($store,$entity) as $pending)if($pending['id']===$tgPaymentId){$tgPayment=$pending;break;}
            if(!$tgPayment)er_respond(['ok'=>false,'error'=>'The TG payment is not pending for this company or has already been received.'],409);
            if($tgPayment['currency']!==$currency||abs((float)$tgPayment['amount']-$foreign)>.01)er_respond(['ok'=>false,'error'=>'Receipt currency and amount must match the linked TG outgoing payment.'],422);
            $requested=(array)($body['allocations']??[]);if(count($requested)!==1||(string)($requested[0]['targetId']??'')!==$tgPayment['candidateId']||(string)($requested[0]['targetType']??'')!=='INTERCOMPANY_RECEIVABLE')er_respond(['ok'=>false,'error'=>'Select the exact linked intercompany invoice for this TG payment.'],422);
        }
        $bankMaster=er_bank_master($bankId,$entity);$bankCurrency=(string)$bankMaster['currency'];
        if($bankCurrency!=='PKR'&&$bankCurrency!==$currency)er_respond(['ok'=>false,'error'=>'The receiving bank must be PKR or match the payment currency.'],422);
        $bank=er_receipt_bank($store,$bankId,$entity,$bankCurrency,false);$nativeCredit=0.0;
        if($bankCurrency!== 'PKR'){
            $nativeCredit=er_money($body['nativeBankCredit']??0,'Foreign bank credit');
            if(abs($nativeCredit-$foreign)>.01||$bankCredit>0||$retentionForeign>0||(array)($body['deductions']??[]))er_respond(['ok'=>false,'error'=>'For direct foreign bank credit, enter the same-currency amount; handle any bank deductions separately.'],422);
            if(abs($gross-round($foreign*$rate,2))>2.0)er_respond(['ok'=>false,'error'=>'PKR equivalent must equal the foreign receipt multiplied by the recorded rate.'],422);
        }
        $retentionBank=null;if($retentionForeign>0){if($retentionBankId==='')er_respond(['ok'=>false,'error'=>'Select the approved foreign-currency retention bank account.'],422);$retentionBank=er_receipt_bank($store,$retentionBankId,$entity,$currency);}
        $alloc=er_prepare_allocations($store,$entity,$currency,$foreign,$gross,(array)($body['allocations']??[]));$ded=er_prepare_deductions($entity,$date,(array)($body['deductions']??[]),$catalog);
        $expected=round($gross-$retentionPkr-$ded['deducted'],2);if($bankCurrency==='PKR'&&abs($bankCredit-$expected)>2.0)er_respond(['ok'=>false,'error'=>'Bank advice does not balance: PKR credit + retention + deductions from proceeds must equal gross PKR realization. Difference: Rs '.number_format($bankCredit-$expected,2).'. Classify the missing charge or correct the bank figures.'],422);
        $id=er_next_id((array)$store['exportReceipts'],'ER');$lines=[];if($bankCredit>0)$lines[]=er_line('1110',$bankCredit,0,$catalog,['bankAccountId'=>$bank['id'],'bankName'=>$bank['bankName'],'bankAccountTitle'=>$bank['accountTitle'],'currency'=>'PKR']);if($nativeCredit>0)$lines[]=er_line('1110',$gross,0,$catalog,['bankAccountId'=>$bank['id'],'bankName'=>$bank['bankName'],'bankAccountTitle'=>$bank['accountTitle'],'currency'=>$currency,'bankDebit'=>$nativeCredit,'bankCredit'=>0]);if($retentionPkr>0&&$retentionBank)$lines[]=er_line('1110',$retentionPkr,0,$catalog,['bankAccountId'=>$retentionBank['id'],'bankName'=>$retentionBank['bankName'],'bankAccountTitle'=>$retentionBank['accountTitle'],'currency'=>$currency,'bankDebit'=>$retentionForeign,'bankCredit'=>0]);foreach($ded['rows'] as $d)if($d['mode']==='DEDUCTED')$lines[]=er_line($d['account'],$d['amount'],0,$catalog,['exportDeductionCode'=>$d['masterCode'],'taxSection'=>$d['taxSection']]);
        $realizedReceivable=0.0;$carryingReceivable=0.0;foreach($alloc as $a){if($a['targetType']==='EXPORT_RECEIVABLE'){$lines[]=er_line('1210',0,$a['carryingPkr'],$catalog,['candidateId'=>$a['targetId']]);$realizedReceivable+=$a['realizedPkr'];$carryingReceivable+=$a['carryingPkr'];}elseif($a['targetType']==='INTERCOMPANY_RECEIVABLE'){$lines[]=er_line('1240',0,$a['carryingPkr'],$catalog,['candidateId'=>$a['targetId']]);$realizedReceivable+=$a['realizedPkr'];$carryingReceivable+=$a['carryingPkr'];}else{$lines[]=er_line('2160',0,$a['realizedPkr'],$catalog,['contractRef'=>$a['contractRef'],'invoiceRef'=>$a['invoiceRef'],'customer'=>$a['customer']]);}}
        $fx=round($realizedReceivable-$carryingReceivable,2);if($fx>0)$lines[]=er_line('7100',0,$fx,$catalog,['fxDirection'=>'Gain']);elseif($fx<0)$lines[]=er_line('7100',abs($fx),0,$catalog,['fxDirection'=>'Loss']);
        $meta=['receiptId'=>$id,'transactionCurrency'=>$currency,'transactionAmount'=>$foreign,'realizationRate'=>$rate,'grossPkrEquivalent'=>$gross,'bankAccountId'=>$bank['id'],'bankName'=>$bank['bankName'],'pkrBankCredit'=>$bankCredit,'nativeBankCredit'=>$nativeCredit,'tgPaymentId'=>$tgPaymentId,'retentionBankAccountId'=>$retentionBank['id']??'','retentionForeignAmount'=>$retentionForeign,'retentionPkrEquivalent'=>$retentionPkr,'invoiceRefs'=>array_values(array_filter(array_map(static fn($a)=>(string)($a['invoiceRef']??''),$alloc))),'allocations'=>$alloc,'deductions'=>array_values(array_filter($ded['rows'],static fn($d)=>$d['mode']==='DEDUCTED')),'exportTaxDeductions'=>er_tax_meta($ded['taxDeducted'],$bank),'bankAdviceFileRef'=>trim((string)($body['bankAdviceFileRef']??'')),'remitter'=>trim((string)($body['remitter']??'')),'shortfallClassification'=>$shortfallClassification,'shortfallNote'=>$shortfallNote];
        $journal=er_post_journal($store,$user,$entity,$date,'EXPORT_FOREIGN_RECEIPT',$bankRef,'Foreign export / intercompany realization — '.$bankRef,$lines,$meta);
        $indentorPayableJournals=[];foreach($alloc as $allocation){if(($allocation['targetType']??'')!=='EXPORT_RECEIVABLE')continue;$candidateId=(string)($allocation['targetId']??'');$candidate=$store['exportCandidates'][$candidateId]??null;if(!is_array($candidate))continue;$candidateMeta=is_array($candidate['meta']??null)?$candidate['meta']:[];$indentor=trim((string)($candidateMeta['indentor']??''));$commissionRate=round((float)($candidateMeta['indentorCommissionPerMT']??0),4);$qtyMt=round((float)($candidateMeta['actualQtyMT']??0),3);if($indentor===''||$commissionRate<=0||$qtyMt<=0||!empty($candidateMeta['indentorPayableJournalId']))continue;$fullyPaid=er_prior_allocated($store,$candidateId)+(float)($allocation['foreignAmount']??0)>=(float)($candidate['transactionAmount']??0)-.01;if(!$fullyPaid)continue;$nativeAmount=round($qtyMt*$commissionRate,2);$pkrAmount=round($nativeAmount*$rate,2);if($pkrAmount<=0)continue;$indentorMeta=['sourceCandidateId'=>$candidateId,'indentor'=>$indentor,'contractRef'=>(string)($candidateMeta['contractRef']??''),'invoiceRef'=>(string)($candidate['reference']??''),'nativeCurrency'=>(string)($candidate['transactionCurrency']??$currency),'nativeAmount'=>$nativeAmount,'commissionPerMT'=>$commissionRate,'loadedQtyMT'=>$qtyMt,'creditAdviceRate'=>$rate,'receiptId'=>$id,'settlementStatus'=>'Awaiting contract closure','allowedSettlementRoutes'=>['Contract currency through TG or retention account','PKR at recorded credit-advice rate']];$payable=er_post_journal($store,$user,$entity,$date,'EXPORT_INDENTOR_COMMISSION_ACCRUAL',(string)($candidateMeta['contractRef']??$candidate['reference']??$candidateId),'Indentor commission firm after full invoice payment — '.$indentor,[er_line('5610',$pkrAmount,0,$catalog,$indentorMeta),er_line('2170',0,$pkrAmount,$catalog,$indentorMeta)],$indentorMeta);$candidateMeta['indentorPayableStatus']='Firm — awaiting contract closure';$candidateMeta['indentorPayableJournalId']=$payable['id'];$candidateMeta['indentorFirmNativeAmount']=$nativeAmount;$candidateMeta['indentorFirmPkrAmount']=$pkrAmount;$candidateMeta['indentorCreditAdviceRate']=$rate;$candidateMeta['indentorFirmReceiptId']=$id;$store['exportCandidates'][$candidateId]['meta']=$candidateMeta;$indentorPayableJournals[]=$payable;}
        $separateJournal=null;if($ded['separate']>0){$sl=[];foreach($ded['rows'] as $d)if($d['mode']==='SEPARATE_DEBIT')$sl[]=er_line($d['account'],$d['amount'],0,$catalog,['exportDeductionCode'=>$d['masterCode'],'taxSection'=>$d['taxSection']]);$sl[]=er_line('1110',0,$ded['separate'],$catalog,['bankAccountId'=>$bank['id'],'bankName'=>$bank['bankName'],'bankAccountTitle'=>$bank['accountTitle'],'currency'=>'PKR']);$sm=['receiptId'=>$id,'linkedReceiptJournalId'=>$journal['id'],'bankAccountId'=>$bank['id'],'bankName'=>$bank['bankName'],'deductions'=>array_values(array_filter($ded['rows'],static fn($d)=>$d['mode']==='SEPARATE_DEBIT')),'exportTaxDeductions'=>er_tax_meta($ded['taxSeparate'],$bank),'bankAdviceFileRef'=>trim((string)($body['bankAdviceFileRef']??''))];$separateJournal=er_post_journal($store,$user,$entity,$date,'EXPORT_REALIZATION_BANK_DEBITS',$bankRef.'-CHG','Export realization charges / tax debited separately — '.$bankRef,$sl,$sm);}
        $receipt=['id'=>$id,'entity'=>$entity,'date'=>$date,'bankAdviceRef'=>$bankRef,'bankAdviceFileRef'=>trim((string)($body['bankAdviceFileRef']??'')),'bankAdvicePaperRef'=>trim((string)($body['bankAdvicePaperRef']??'')),'remitter'=>trim((string)($body['remitter']??'')),'transactionCurrency'=>$currency,'foreignAmount'=>$foreign,'realizationRate'=>$rate,'grossPkrEquivalent'=>$gross,'bankAccountId'=>$bank['id'],'bankName'=>$bank['bankName'],'pkrBankCredit'=>$bankCredit,'nativeBankCredit'=>$nativeCredit,'tgPaymentId'=>$tgPaymentId,'retentionBankAccountId'=>$retentionBank['id']??'','retentionForeignAmount'=>$retentionForeign,'retentionPkrEquivalent'=>$retentionPkr,'allocations'=>$alloc,'deductions'=>$ded['rows'],'shortfallClassification'=>$shortfallClassification,'shortfallNote'=>$shortfallNote,'journalId'=>$journal['id'],'indentorPayableJournalIds'=>array_values(array_map(static fn($j)=>(string)$j['id'],$indentorPayableJournals)),'separateChargeJournalId'=>$separateJournal['id']??null,'status'=>'Accounts Approved / Posted','createdAt'=>gmdate('c'),'createdBy'=>(string)($user['full_name']??$user['username']??'Accounts')];$store['exportReceipts'][$id]=$receipt;$store['revision']=(int)($store['revision']??0)+1;rewind($h);ftruncate($h,0);fwrite($h,json_encode($store,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($h);
    }finally{flock($h,LOCK_UN);fclose($h);}
    er_write_export_receipts_to_ops($receipt);er_respond(['ok'=>true,'receipt'=>$receipt,'journal'=>$journal,'indentorPayableJournals'=>$indentorPayableJournals,'separateChargeJournal'=>$separateJournal,'revision'=>$store['revision']]);
}catch(Throwable $e){er_respond(['ok'=>false,'error'=>'The export receipt could not be posted.'],500);}
