<?php
declare(strict_types=1);
require dirname(__DIR__).'/auth_store.php';
header('Content-Type: application/json; charset=UTF-8');
header('Cache-Control: no-store');
const TT_INTERNAL_BANK_FILE=TT_DATA_DIR.'/accounts.json';
function ibt_out(array $body,int $status=200):never{http_response_code($status);echo json_encode($body,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function ibt_entity(string $value):string{$value=strtoupper(trim($value));if(!in_array($value,['TTI','BRM','TG'],true))ibt_out(['ok'=>false,'error'=>'Choose TTI, BRM or TG books.'],422);return $value;}
function ibt_can_write(array $user):bool{if(($user['role']??'')==='Super Admin')return true;$p=$user['permissions']['Accounts']??null;if($p==='all')return true;if(!is_array($p))return false;if(in_array('Create',$p,true)||in_array('Edit',$p,true)||in_array('Approve',$p,true))return true;foreach($p as $v)if(is_array($v)&&count(array_intersect(['Create','Edit','Approve'],$v)))return true;return false;}
function ibt_read():array{tt_ensure_data_dir();if(!is_file(TT_INTERNAL_BANK_FILE))return ['revision'=>0,'journals'=>[],'internalBankTransfers'=>[]];$h=fopen(TT_INTERNAL_BANK_FILE,'r');if(!$h||!flock($h,LOCK_SH))throw new RuntimeException('Accounts unavailable.');try{$raw=stream_get_contents($h);}finally{flock($h,LOCK_UN);fclose($h);}return array_replace_recursive(['revision'=>0,'journals'=>[],'internalBankTransfers'=>[]],(array)json_decode($raw?:'{}',true));}
function ibt_entity_of(string $linked):string{$v=strtoupper($linked);if(str_contains($v,'BRM')||str_contains($v,'BUKSH RICE'))return 'BRM';if(str_contains($v,'TRANS GRAINS')||preg_match('/(^|\W)TG($|\W)/',$v))return 'TG';if(str_contains($v,'TTI')||str_contains($v,'TRANSTRADE INTERNATIONAL'))return 'TTI';return '';}
function ibt_accounts():array{$out=[];foreach((array)(tt_list_masters()['banks']??[]) as $row){if(!is_array($row))continue;$v=array_values((array)($row['values']??[]));while(count($v)<14)$v[]='';$id=(string)($row['id']??'');if($id==='')continue;$out[$id]=['id'=>$id,'type'=>(string)$v[0],'entity'=>ibt_entity_of((string)$v[1]),'owner'=>trim((string)$v[2]),'title'=>(string)$v[3],'bank'=>(string)$v[4],'currency'=>strtoupper(trim((string)$v[7])),'number'=>(string)$v[8],'iban'=>(string)$v[9],'status'=>(string)$v[13]];}return $out;}
function ibt_bank_balance(array $store,string $entity,string $bankId,string $currency):array{$native=0.0;$functional=0.0;foreach((array)($store['journals']??[]) as $j){if(!is_array($j)||($j['status']??'')!=='Posted'||($j['entity']??'')!==$entity)continue;$meta=(array)($j['meta']??[]);foreach((array)($j['lines']??[]) as $line){if(!is_array($line)||($line['account']??'')!=='1110'||(string)($line['bankAccountId']??$meta['bankAccountId']??'')!==$bankId)continue;$functional+=(float)($line['debit']??0)-(float)($line['credit']??0);$native+=$currency==='PKR'?(float)($line['debit']??0)-(float)($line['credit']??0):(float)($line['bankDebit']??0)-(float)($line['bankCredit']??0);}}return ['native'=>round($native,2),'functional'=>round($functional,2),'carryingRate'=>$currency==='PKR'||$currency==='AED'?1:($native>0?round($functional/$native,8):0)];}
function ibt_catalog():array{$raw=json_decode((string)file_get_contents(__DIR__.'/../accounts/accounting_master_v1.json'),true);$out=[];foreach((array)($raw['chart']??[]) as $row)if(is_array($row)&&isset($row['code']))$out[(string)$row['code']]=(string)($row['name']??'');return $out;}
function ibt_line(string $account,float $dr,float $cr,array $catalog,array $meta=[]):array{if(!isset($catalog[$account]))ibt_out(['ok'=>false,'error'=>'Approved ledger '.$account.' is unavailable.'],422);return array_merge(['account'=>$account,'accountName'=>$catalog[$account],'debit'=>round($dr,2),'credit'=>round($cr,2)],$meta);}
function ibt_next(array $rows,string $prefix):string{$n=count($rows)+1;do{$id=$prefix.'-'.gmdate('Y').'-'.str_pad((string)$n++,6,'0',STR_PAD_LEFT);}while(isset($rows[$id]));return $id;}
function ibt_payload(array $store,string $entity):array{$accounts=ibt_accounts();$sources=[];$destinations=[];foreach($accounts as $row){$isCompany=$row['type']==='Company Account'&&$row['entity']===$entity;$isPersonal=$row['type']==='Personal Account'&&$row['owner']!==''&&in_array($row['entity'],['',$entity],true);if(!$isCompany&&!$isPersonal)continue;if(strcasecmp($row['status'],'Active')!==0||($row['number']===''&&$row['iban']===''))continue;if($entity!=='TG'&&$row['currency']!=='PKR')continue;$safe=['id'=>$row['id'],'type'=>$row['type'],'owner'=>$row['owner'],'title'=>$row['title'],'bank'=>$row['bank'],'currency'=>$row['currency']];if($isCompany){if(!tt_bank_can_transact($row['id']))continue;$safe['balance']=ibt_bank_balance($store,$entity,$row['id'],$row['currency']);$sources[]=$safe;}$destinations[]=$safe;}$history=array_values(array_filter((array)($store['internalBankTransfers']??[]),static fn($x)=>is_array($x)&&($x['entity']??'')===$entity));usort($history,static fn($a,$b)=>strcmp((string)$b['date'],(string)$a['date']));return ['ok'=>true,'entity'=>$entity,'sources'=>$sources,'destinations'=>$destinations,'history'=>array_slice($history,0,30)];}
try{
 $user=tt_require_login();if(!tt_user_can_open_module($user,'Accounts'))ibt_out(['ok'=>false,'error'=>'Accounts permission required.'],403);
 $entity=ibt_entity((string)($_GET['entity']??'TTI'));if(($user['role']??'')!=='Super Admin'&&!tt_user_can_access_entity($user,$entity,'View'))ibt_out(['ok'=>false,'error'=>'You cannot access these company books.'],403);
 if($_SERVER['REQUEST_METHOD']==='GET')ibt_out(ibt_payload(ibt_read(),$entity));
 if($_SERVER['REQUEST_METHOD']!=='POST')ibt_out(['ok'=>false,'error'=>'Method not allowed.'],405);if(!ibt_can_write($user))ibt_out(['ok'=>false,'error'=>'Accounts Create / Edit / Approve permission required.'],403);
 $body=json_decode(file_get_contents('php://input')?:'{}',true);if(!is_array($body)||!tt_verify_csrf((string)($body['csrf']??'')))ibt_out(['ok'=>false,'error'=>'Session expired. Refresh and try again.'],419);if(($body['action']??'')!=='post_transfer')ibt_out(['ok'=>false,'error'=>'Unknown transfer action.'],422);
 $date=trim((string)($body['date']??''));if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date))ibt_out(['ok'=>false,'error'=>'Transfer date required.'],422);$sourceId=trim((string)($body['sourceBankId']??''));$destinationId=trim((string)($body['destinationBankId']??''));$reference=trim((string)($body['reference']??''));$narration=trim((string)($body['narration']??''));$amount=round((float)($body['amount']??0),2);if($sourceId===$destinationId||$sourceId===''||$destinationId==='')ibt_out(['ok'=>false,'error'=>'Choose different source and destination accounts.'],422);if($reference===''||$narration===''||$amount<=0)ibt_out(['ok'=>false,'error'=>'Amount, bank reference and why the transfer is happening are required.'],422);
 tt_ensure_data_dir();$h=fopen(TT_INTERNAL_BANK_FILE,'c+');if(!$h||!flock($h,LOCK_EX))throw new RuntimeException('Accounts unavailable.');try{rewind($h);$raw=stream_get_contents($h);$store=array_replace_recursive(['revision'=>0,'journals'=>[],'internalBankTransfers'=>[]],(array)json_decode($raw?:'{}',true));$eligible=ibt_payload($store,$entity);$source=null;$destination=null;foreach($eligible['sources'] as $x)if($x['id']===$sourceId)$source=$x;foreach($eligible['destinations'] as $x)if($x['id']===$destinationId)$destination=$x;if(!$source||!$destination)ibt_out(['ok'=>false,'error'=>'Choose active accounts belonging to this company or an available personal account.'],422);if($source['currency']!==$destination['currency'])ibt_out(['ok'=>false,'error'=>'Use the TG USD ↔ AED conversion for a transfer between different currencies.'],422);if($amount>$source['balance']['native']+.0001)ibt_out(['ok'=>false,'error'=>'The source bank has insufficient book balance.'],422);foreach((array)$store['internalBankTransfers'] as $x)if(is_array($x)&&($x['entity']??'')===$entity&&$x['sourceBankId']===$sourceId&&strcasecmp((string)$x['reference'],$reference)===0)ibt_out(['ok'=>false,'error'=>'This source bank reference has already been posted.'],409);
 $rate=(float)$source['balance']['carryingRate'];if($rate<=0)ibt_out(['ok'=>false,'error'=>'The source account needs an AED carrying balance before its USD can be transferred.'],422);$functional=round($amount*$rate,2);$catalog=ibt_catalog();$srcMeta=['bankAccountId'=>$sourceId,'bankName'=>$source['bank'],'bankAccountTitle'=>$source['title'],'currency'=>$source['currency'],'bankDebit'=>0,'bankCredit'=>$amount];$lines=[ibt_line('1110',0,$functional,$catalog,$srcMeta)];if($destination['type']==='Company Account'){$dstMeta=['bankAccountId'=>$destinationId,'bankName'=>$destination['bank'],'bankAccountTitle'=>$destination['title'],'currency'=>$source['currency'],'bankDebit'=>$amount,'bankCredit'=>0];array_unshift($lines,ibt_line('1110',$functional,0,$catalog,$dstMeta));}else{array_unshift($lines,ibt_line('1230',$functional,0,$catalog,['counterparty'=>$destination['owner'],'personalBankId'=>$destinationId,'purpose'=>$narration]));}
 $id=ibt_next((array)$store['internalBankTransfers'],'IBT');$jid=ibt_next((array)$store['journals'],'AUTO');$record=['id'=>$id,'entity'=>$entity,'date'=>$date,'sourceBankId'=>$sourceId,'destinationBankId'=>$destinationId,'destinationType'=>$destination['type'],'personalOwner'=>$destination['owner'],'currency'=>$source['currency'],'amount'=>$amount,'functionalAmount'=>$functional,'reference'=>$reference,'narration'=>$narration,'journalId'=>$jid,'createdAt'=>gmdate('c'),'createdBy'=>(string)($user['full_name']??$user['username']??'Accounts')];$store['journals'][$jid]=['id'=>$jid,'entity'=>$entity,'date'=>$date,'sourceType'=>$destination['type']==='Personal Account'?'PERSONAL_BANK_ADVANCE':'INTERNAL_BANK_TRANSFER','reference'=>$reference,'narration'=>$narration,'lines'=>$lines,'totalDebit'=>$functional,'totalCredit'=>$functional,'status'=>'Posted','meta'=>$record,'createdAt'=>gmdate('c'),'createdBy'=>$record['createdBy'],'userId'=>(int)($user['id']??0),'reversalOf'=>null];$store['internalBankTransfers'][$id]=$record;$store['revision']=(int)($store['revision']??0)+1;rewind($h);ftruncate($h,0);fwrite($h,json_encode($store,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($h);
 }finally{flock($h,LOCK_UN);fclose($h);}ibt_out(ibt_payload($store,$entity)+['transfer'=>$record,'journal'=>$store['journals'][$jid]]);
}catch(Throwable $e){error_log('Internal bank transfer: '.$e->getMessage());ibt_out(['ok'=>false,'error'=>'Bank transfer could not be completed.'],500);}
