<?php
declare(strict_types=1);
require dirname(__DIR__).'/auth_store.php';
header('Content-Type: application/json; charset=UTF-8');
header('Cache-Control: no-store, no-cache, must-revalidate');

const JVW_FILE=TT_DATA_DIR.'/accounts.json';
const JVW_MASTER=__DIR__.'/../accounts/accounting_master_v1.json';

function jvw_out(array $d,int $s=200):never{http_response_code($s);echo json_encode($d,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function jvw_def():array{return ['revision'=>0,'journals'=>[],'jvDrafts'=>[]];}
function jvw_read():array{tt_ensure_data_dir();if(!is_file(JVW_FILE))return jvw_def();$h=fopen(JVW_FILE,'r');if($h===false||!flock($h,LOCK_SH))throw new RuntimeException('Accounts storage unavailable.');try{$raw=stream_get_contents($h);}finally{flock($h,LOCK_UN);fclose($h);}$s=$raw?json_decode($raw,true):null;return is_array($s)?array_replace_recursive(jvw_def(),$s):jvw_def();}
function jvw_perm(array $u,string $action):bool{if(($u['role']??'')==='Super Admin')return true;$p=$u['permissions']['Accounts']??null;if($p==='all')return true;if(!is_array($p))return false;if(in_array($action,$p,true))return true;foreach($p as$v)if(is_array($v)&&in_array($action,$v,true))return true;return false;}
function jvw_entity(string $v):string{$v=strtoupper(trim($v));if(!in_array($v,['TTI','BRM','TG'],true))jvw_out(['ok'=>false,'error'=>'Select a valid legal entity.'],422);return $v;}
function jvw_access(array $u,string $e,string $action='View'):void{if(($u['role']??'')==='Super Admin')return;if(!tt_user_can_access_entity($u,$e,$action))jvw_out(['ok'=>false,'error'=>'You do not have permission for this legal entity.'],403);}
function jvw_date(string $v,string $label='Date'):string{$d=DateTimeImmutable::createFromFormat('!Y-m-d',$v);$x=DateTimeImmutable::getLastErrors();if(!$d||($x!==false&&(($x['warning_count']??0)>0||($x['error_count']??0)>0))||$d->format('Y-m-d')!==$v)jvw_out(['ok'=>false,'error'=>$label.' is invalid.'],422);return $v;}
function jvw_text(mixed $v,int $max,string $label,bool $required=false):string{$s=trim((string)$v);if($required&&$s==='')jvw_out(['ok'=>false,'error'=>$label.' is required.'],422);if(mb_strlen($s)>$max)jvw_out(['ok'=>false,'error'=>$label.' is too long.'],422);return $s;}
function jvw_next(array $items,string $prefix):string{$n=count($items)+1;do{$id=$prefix.'-'.gmdate('Y').'-'.str_pad((string)$n,6,'0',STR_PAD_LEFT);$n++;}while(isset($items[$id]));return $id;}
function jvw_catalog():array{$raw=is_file(JVW_MASTER)?file_get_contents(JVW_MASTER):false;$m=$raw?json_decode($raw,true):null;if(!is_array($m))throw new RuntimeException('Accounting master unavailable.');$out=[];foreach((array)($m['chart']??[])as$a){if(!is_array($a)||empty($a['code']))continue;$level=(string)($a['level']??'');if($level==='heading'||($level==='control'&&empty($a['subledger'])))continue;$out[(string)$a['code']]=$a;}foreach((array)($m['peopleSubledgers']??[])as$a)if(is_array($a)&&!empty($a['code']))$out[(string)$a['code']]=array_merge(['level'=>'subledger','subledger'=>false],$a);ksort($out);return $out;}
function jvw_lines(mixed $raw,bool $mustBalance):array{if(!is_array($raw))jvw_out(['ok'=>false,'error'=>'Journal lines are required.'],422);$catalog=jvw_catalog();$lines=[];$dr=0.0;$cr=0.0;foreach($raw as$i=>$r){if(!is_array($r))continue;$code=trim((string)($r['account']??''));$debit=round((float)($r['debit']??0),2);$credit=round((float)($r['credit']??0),2);$sub=jvw_text($r['subledger']??'',120,'Line details');$memo=jvw_text($r['memo']??'',180,'Line memo');$billNo=jvw_text($r['billNo']??'',120,'Bill number');$lineReference=jvw_text($r['lineReference']??'',120,'Line reference');if($code===''&&$debit<=0&&$credit<=0&&$sub===''&&$memo===''&&$billNo===''&&$lineReference==='')continue;if(!isset($catalog[$code]))jvw_out(['ok'=>false,'error'=>'Line '.((int)$i+1).' must use an approved posting account.'],422);if(in_array($code,['1110','1120'],true))jvw_out(['ok'=>false,'error'=>'Bank and cash movements must use their dedicated payment, receipt or transfer workflow.'],422);if($debit<0||$credit<0||($debit>0&&$credit>0))jvw_out(['ok'=>false,'error'=>'Each line may contain either a debit or a credit, not both.'],422);if($mustBalance&&$debit<=0&&$credit<=0)jvw_out(['ok'=>false,'error'=>'Every submitted line requires a debit or credit amount.'],422);if($mustBalance&&!empty($catalog[$code]['subledger'])&&$sub==='')jvw_out(['ok'=>false,'error'=>'Line '.((int)$i+1).' requires subsidiary details.'],422);$lines[]=['account'=>$code,'accountName'=>(string)($catalog[$code]['name']??$code),'subledger'=>$sub,'memo'=>$memo,'billNo'=>$billNo,'lineReference'=>$lineReference,'debit'=>$debit,'credit'=>$credit];$dr+=$debit;$cr+=$credit;}if(count($lines)>100)jvw_out(['ok'=>false,'error'=>'A JV cannot exceed 100 lines.'],422);if($mustBalance&&(count($lines)<2||round($dr,2)<=0||abs(round($dr,2)-round($cr,2))>.005))jvw_out(['ok'=>false,'error'=>'Submitted JV must contain at least two lines and total debit must equal total credit.'],422);return [$lines,round($dr,2),round($cr,2)];}
function jvw_payload(array $s,string $e,array $u):array{$rows=[];foreach((array)$s['jvDrafts']as$r)if(is_array($r)&&($r['entity']??'')===$e)$rows[]=$r;usort($rows,static fn($a,$b)=>strcmp((string)($b['updatedAt']??$b['createdAt']??''),(string)($a['updatedAt']??$a['createdAt']??'')));$accounts=[];foreach(jvw_catalog()as$a)$accounts[]=['code'=>$a['code'],'name'=>$a['name'],'class'=>$a['class']??'','requiresSubledger'=>!empty($a['subledger'])];return ['ok'=>true,'entity'=>$e,'jvs'=>$rows,'accounts'=>$accounts,'canWrite'=>jvw_perm($u,'Create')||jvw_perm($u,'Edit'),'canApprove'=>jvw_perm($u,'Approve'),'serverNow'=>gmdate('c')];}
function jvw_duplicate(array $s,string $e,string $ref,string $exclude=''):void{if($ref==='')return;foreach((array)$s['jvDrafts']as$r)if(is_array($r)&&($r['entity']??'')===$e&&($r['id']??'')!==$exclude&&!in_array(($r['status']??''),['Cancelled'],true)&&strcasecmp((string)($r['reference']??''),$ref)===0)jvw_out(['ok'=>false,'error'=>'This JV reference already exists in these company books.'],409);}
function jvw_post(array &$s,array &$r,array $u):string{[$lines,$dr,$cr]=jvw_lines($r['lines']??[],true);$id=jvw_next((array)$s['journals'],'JV');$now=gmdate('c');$s['journals'][$id]=['id'=>$id,'entity'=>$r['entity'],'date'=>$r['date'],'sourceType'=>'JV','reference'=>$r['reference']!==''?$r['reference']:$r['id'],'narration'=>$r['narration'],'lines'=>$lines,'totalDebit'=>$dr,'totalCredit'=>$cr,'status'=>'Posted','meta'=>['jvDraftId'=>$r['id'],'supportingReference'=>$r['supportingReference']],'createdAt'=>$now,'createdBy'=>$r['createdBy'],'userId'=>(int)($r['createdByUserId']??0),'approvedAt'=>$now,'approvedBy'=>(string)($u['full_name']??$u['username']??'Approver'),'approvedByUserId'=>(int)($u['id']??0),'reversalOf'=>null];$r['status']='Posted';$r['journalId']=$id;$r['approvedAt']=$now;$r['approvedBy']=(string)($u['full_name']??$u['username']??'Approver');$r['approvedByUserId']=(int)($u['id']??0);$r['updatedAt']=$now;return $id;}

try{
$u=tt_require_login();if(!tt_user_can_open_module($u,'Accounts'))jvw_out(['ok'=>false,'error'=>'Accounts permission required.'],403);$e=jvw_entity((string)($_GET['entity']??'TTI'));jvw_access($u,$e,'View');if($_SERVER['REQUEST_METHOD']==='GET')jvw_out(jvw_payload(jvw_read(),$e,$u));if($_SERVER['REQUEST_METHOD']!=='POST')jvw_out(['ok'=>false,'error'=>'Method not allowed.'],405);
$b=json_decode(file_get_contents('php://input')?:'{}',true);if(!is_array($b)||!tt_verify_csrf((string)($b['csrf']??'')))jvw_out(['ok'=>false,'error'=>'Your session expired. Refresh and try again.'],419);$action=(string)($b['action']??'');$e=jvw_entity((string)($b['entity']??$e));jvw_access($u,$e,'View');
if(in_array($action,['save_draft','submit_jv','cancel_jv'],true)&&!(jvw_perm($u,'Create')||jvw_perm($u,'Edit')))jvw_out(['ok'=>false,'error'=>'Accounts Create or Edit permission is required.'],403);
if(in_array($action,['approve_jv','reject_jv','reverse_jv'],true)&&!jvw_perm($u,'Approve'))jvw_out(['ok'=>false,'error'=>'Accounts Approve permission is required.'],403);
tt_ensure_data_dir();$h=fopen(JVW_FILE,'c+');if($h===false||!flock($h,LOCK_EX))throw new RuntimeException('Accounts storage unavailable.');
try{rewind($h);$raw=stream_get_contents($h);$s=$raw?json_decode($raw,true):null;if(!is_array($s))$s=jvw_def();$s=array_replace_recursive(jvw_def(),$s);$result=[];
if($action==='save_draft'||$action==='submit_jv'){$id=trim((string)($b['id']??''));$old=$id!==''?($s['jvDrafts'][$id]??null):null;if($id!==''&&(!is_array($old)||($old['entity']??'')!==$e))jvw_out(['ok'=>false,'error'=>'JV draft was not found in these company books.'],404);if(is_array($old)&&!in_array(($old['status']??''),['Draft','Rejected'],true))jvw_out(['ok'=>false,'error'=>'Only Draft or Rejected JVs can be edited.'],409);$date=jvw_date((string)($b['date']??''),'JV date');$ref=jvw_text($b['reference']??'',120,'Reference');$narr=jvw_text($b['narration']??'',500,'Narration',true);$support=jvw_text($b['supportingReference']??'',180,'Supporting reference');jvw_duplicate($s,$e,$ref,$id);[$lines,$dr,$cr]=jvw_lines($b['lines']??[],$action==='submit_jv');if($id==='')$id=jvw_next((array)$s['jvDrafts'],'JVD');$now=gmdate('c');$base=is_array($old)?$old:['id'=>$id,'entity'=>$e,'createdAt'=>$now,'createdBy'=>(string)($u['full_name']??$u['username']??'Accounts'),'createdByUserId'=>(int)($u['id']??0)];$s['jvDrafts'][$id]=array_merge($base,['date'=>$date,'reference'=>$ref,'narration'=>$narr,'supportingReference'=>$support,'lines'=>$lines,'totalDebit'=>$dr,'totalCredit'=>$cr,'status'=>$action==='submit_jv'?'Pending Approval':'Draft','submittedAt'=>$action==='submit_jv'?$now:null,'submittedBy'=>$action==='submit_jv'?(string)($u['full_name']??$u['username']??'Accounts'):null,'updatedAt'=>$now,'updatedBy'=>(string)($u['full_name']??$u['username']??'Accounts')]);$result=['jvId'=>$id,'status'=>$s['jvDrafts'][$id]['status']];}
elseif($action==='approve_jv'){$id=trim((string)($b['id']??''));$r=&$s['jvDrafts'][$id];if(!is_array($r)||($r['entity']??'')!==$e||($r['status']??'')!=='Pending Approval')jvw_out(['ok'=>false,'error'=>'Pending JV was not found.'],404);if(($u['role']??'')!=='Super Admin'&&(int)($r['createdByUserId']??0)===(int)($u['id']??0))jvw_out(['ok'=>false,'error'=>'The preparer cannot approve their own JV.'],403);$jid=jvw_post($s,$r,$u);$result=['jvId'=>$id,'journalId'=>$jid,'status'=>'Posted'];unset($r);}
elseif($action==='reject_jv'){$id=trim((string)($b['id']??''));$reason=jvw_text($b['reason']??'',300,'Rejection reason',true);$r=$s['jvDrafts'][$id]??null;if(!is_array($r)||($r['entity']??'')!==$e||($r['status']??'')!=='Pending Approval')jvw_out(['ok'=>false,'error'=>'Pending JV was not found.'],404);$s['jvDrafts'][$id]['status']='Rejected';$s['jvDrafts'][$id]['rejectionReason']=$reason;$s['jvDrafts'][$id]['rejectedAt']=gmdate('c');$s['jvDrafts'][$id]['rejectedBy']=(string)($u['full_name']??$u['username']??'Approver');$s['jvDrafts'][$id]['updatedAt']=gmdate('c');$result=['jvId'=>$id,'status'=>'Rejected'];}
elseif($action==='cancel_jv'){$id=trim((string)($b['id']??''));$r=$s['jvDrafts'][$id]??null;if(!is_array($r)||($r['entity']??'')!==$e||!in_array(($r['status']??''),['Draft','Rejected'],true))jvw_out(['ok'=>false,'error'=>'Only Draft or Rejected JVs can be cancelled.'],409);$s['jvDrafts'][$id]['status']='Cancelled';$s['jvDrafts'][$id]['cancelledAt']=gmdate('c');$s['jvDrafts'][$id]['cancelledBy']=(string)($u['full_name']??$u['username']??'Accounts');$s['jvDrafts'][$id]['updatedAt']=gmdate('c');$result=['jvId'=>$id,'status'=>'Cancelled'];}
elseif($action==='reverse_jv'){$id=trim((string)($b['id']??''));$reason=jvw_text($b['reason']??'',300,'Reversal reason',true);$date=jvw_date((string)($b['date']??''),'Reversal date');$r=$s['jvDrafts'][$id]??null;if(!is_array($r)||($r['entity']??'')!==$e||($r['status']??'')!=='Posted')jvw_out(['ok'=>false,'error'=>'Posted JV was not found.'],404);$original=$s['journals'][$r['journalId']]??null;if(!is_array($original)||($original['status']??'')!=='Posted')jvw_out(['ok'=>false,'error'=>'Original posted journal was not found.'],404);foreach((array)$s['journals']as$j)if(is_array($j)&&($j['reversalOf']??null)===($r['journalId']??''))jvw_out(['ok'=>false,'error'=>'This JV has already been reversed.'],409);$lines=array_map(static fn($l)=>['account'=>$l['account'],'accountName'=>$l['accountName']??'','subledger'=>$l['subledger']??'','memo'=>$l['memo']??'','billNo'=>$l['billNo']??'','lineReference'=>$l['lineReference']??'','debit'=>(float)($l['credit']??0),'credit'=>(float)($l['debit']??0)],(array)$original['lines']);$jid=jvw_next((array)$s['journals'],'RV');$s['journals'][$jid]=['id'=>$jid,'entity'=>$e,'date'=>$date,'sourceType'=>'JV_REVERSAL','reference'=>$r['journalId'],'narration'=>'Reversal of '.$r['journalId'].' — '.$reason,'lines'=>$lines,'totalDebit'=>$original['totalCredit'],'totalCredit'=>$original['totalDebit'],'status'=>'Posted','meta'=>['reason'=>$reason,'jvDraftId'=>$id],'createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??$u['username']??'Approver'),'userId'=>(int)($u['id']??0),'reversalOf'=>$r['journalId']];$s['jvDrafts'][$id]['status']='Reversed';$s['jvDrafts'][$id]['reversalJournalId']=$jid;$s['jvDrafts'][$id]['reversalReason']=$reason;$s['jvDrafts'][$id]['reversedAt']=gmdate('c');$s['jvDrafts'][$id]['reversedBy']=(string)($u['full_name']??$u['username']??'Approver');$s['jvDrafts'][$id]['updatedAt']=gmdate('c');$result=['jvId'=>$id,'journalId'=>$jid,'status'=>'Reversed'];}
else jvw_out(['ok'=>false,'error'=>'Unknown JV action.'],422);
$s['revision']=(int)($s['revision']??0)+1;rewind($h);ftruncate($h,0);fwrite($h,json_encode($s,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($h);}finally{flock($h,LOCK_UN);fclose($h);}jvw_out(jvw_payload($s,$e,$u)+['result'=>$result,'revision'=>$s['revision']]);
}catch(Throwable $x){jvw_out(['ok'=>false,'error'=>'JV update could not be completed.'],500);}
