<?php
declare(strict_types=1);
require dirname(__DIR__) . '/auth_store.php';
header('Content-Type: application/json; charset=UTF-8');
header('Cache-Control: no-store, no-cache, must-revalidate');

const TT_LCR_FILE = TT_DATA_DIR . '/accounts.json';
const TT_LCR_MASTER = __DIR__ . '/../accounts/accounting_master_v1.json';

function lcr_out(array $d,int $s=200):never{http_response_code($s);echo json_encode($d,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function lcr_read():array{tt_ensure_data_dir();if(!is_file(TT_LCR_FILE))return []; $h=fopen(TT_LCR_FILE,'r');if($h===false||!flock($h,LOCK_SH))throw new RuntimeException('Accounts storage unavailable.');try{$raw=stream_get_contents($h);}finally{flock($h,LOCK_UN);fclose($h);} $v=$raw?json_decode($raw,true):null;return is_array($v)?$v:[];}
function lcr_can_write(array $u):bool{if(($u['role']??'')==='Super Admin')return true;$p=$u['permissions']['Accounts']??null;if($p==='all')return true;if(!is_array($p))return false;if(in_array('Create',$p,true)||in_array('Edit',$p,true)||in_array('Approve',$p,true))return true;foreach($p as $a)if(is_array($a)&&(in_array('Create',$a,true)||in_array('Edit',$a,true)||in_array('Approve',$a,true)))return true;return false;}
function lcr_names():array{$raw=file_get_contents(TT_LCR_MASTER);$m=$raw?json_decode($raw,true):null;if(!is_array($m))throw new RuntimeException('Accounting master unavailable.');$o=[];foreach((array)($m['chart']??[]) as $a)if(is_array($a)&&isset($a['code']))$o[(string)$a['code']]=(string)($a['name']??$a['code']);return $o;}
function lcr_line(string $a,float $dr,float $cr,array $names,array $extra=[]):array{if(!isset($names[$a]))lcr_out(['ok'=>false,'error'=>'Approved account '.$a.' is unavailable.'],422);return array_merge(['account'=>$a,'accountName'=>$names[$a],'debit'=>round($dr,2),'credit'=>round($cr,2)],$extra);}
function lcr_next(array $items,string $p):string{$n=count($items)+1;do{$id=$p.'-'.gmdate('Y').'-'.str_pad((string)$n,6,'0',STR_PAD_LEFT);$n++;}while(isset($items[$id]));return $id;}
function lcr_post_journal(array &$s,array $u,string $entity,string $date,string $reference,string $narration,array $lines,array $meta):array{$dr=round(array_sum(array_column($lines,'debit')),2);$cr=round(array_sum(array_column($lines,'credit')),2);if($dr<=0||abs($dr-$cr)>.005)throw new RuntimeException('Receipt journal did not balance.');$id=tt_next_post_id((array)($s['journals']??[]),'Accounts','Journal');$s['journals'][$id]=['id'=>$id,'entity'=>$entity,'date'=>$date,'sourceType'=>(string)($meta['sourceType']??'LOCAL_CUSTOMER_RECEIPT'),'reference'=>$reference,'narration'=>$narration,'lines'=>$lines,'totalDebit'=>$dr,'totalCredit'=>$cr,'status'=>'Posted','meta'=>$meta,'createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??$u['username']??'Accounts'),'userId'=>(int)($u['id']??0),'reversalOf'=>$meta['reversalOf']??null];return $s['journals'][$id];}
function lcr_entity_from_linked(string $v):string{$u=strtoupper($v);if(str_contains($u,'BRM')||str_contains($u,'BUKSH RICE'))return 'BRM';if(str_contains($u,'TTI')||str_contains($u,'TRANSTRADE INTERNATIONAL'))return 'TTI';return '';}
function lcr_banks(array $s):array{$m=tt_list_masters();$o=[];foreach((array)($m['banks']??[]) as $r){if(!is_array($r))continue;$v=array_values((array)($r['values']??[]));while(count($v)<14)$v[]='';$entity=lcr_entity_from_linked((string)$v[1]);$id=(string)($r['id']??'');if(!in_array($entity,['TTI','BRM'],true)||trim((string)$v[0])!=='Company Account'||strtoupper(trim((string)$v[7]))!=='PKR'||strcasecmp((string)$v[13],'Active')!==0||(trim((string)$v[8])===''&&trim((string)$v[9])===''))continue;$set=is_array($s['bankAccountSettings'][$id]??null)?$s['bankAccountSettings'][$id]:[];if(!tt_bank_can_transact($id))continue;$raw=preg_replace('/\W+/','',trim((string)($v[8]?:$v[9])))??'';$tail=$raw!==''?substr($raw,-5):'';$o[]=['id'=>$id,'entity'=>$entity,'bankName'=>(string)$v[4],'accountTitle'=>(string)$v[3],'display'=>trim((string)$v[4]).($tail!==''?' — •••••'.$tail:'')];}return $o;}
function lcr_line_soda(array $j,array $l):string{$m=is_array($j['meta']??null)?$j['meta']:[];return trim((string)($l['soda']??$m['soda']??$m['targetSoda']??$m['advanceSoda']??''));}
function lcr_open_rows(array $s):array{$map=[];foreach((array)($s['journals']??[]) as $j){if(!is_array($j)||($j['status']??'')!=='Posted')continue;$entity=(string)($j['entity']??'');if(!in_array($entity,['TTI','BRM'],true))continue;$meta=is_array($j['meta']??null)?$j['meta']:[];foreach((array)($j['lines']??[]) as $l){if(!is_array($l)||(string)($l['account']??'')!=='1220')continue;$soda=lcr_line_soda($j,$l);if($soda==='')continue;$k=$entity.'|'.$soda;if(!isset($map[$k]))$map[$k]=['entity'=>$entity,'soda'=>$soda,'party'=>(string)($l['party']??$meta['party']??''),'product'=>(string)($meta['product']??''),'openReceivable'=>0.0,'customerAdvance'=>0.0];$map[$k]['openReceivable']+=(float)($l['debit']??0)-(float)($l['credit']??0);}}
foreach((array)($s['journals']??[]) as $j){if(!is_array($j)||($j['status']??'')!=='Posted')continue;$entity=(string)($j['entity']??'');if(!in_array($entity,['TTI','BRM'],true))continue;$meta=is_array($j['meta']??null)?$j['meta']:[];foreach((array)($j['lines']??[]) as $l){if(!is_array($l)||(string)($l['account']??'')!=='2510')continue;$soda=lcr_line_soda($j,$l);if($soda==='')continue;$k=$entity.'|'.$soda;if(!isset($map[$k]))$map[$k]=['entity'=>$entity,'soda'=>$soda,'party'=>(string)($l['party']??$meta['party']??''),'product'=>(string)($meta['product']??''),'openReceivable'=>0.0,'customerAdvance'=>0.0];$map[$k]['customerAdvance']+=(float)($l['credit']??0)-(float)($l['debit']??0);}}
$out=[];foreach($map as $x){$x['openReceivable']=round(max(0,(float)$x['openReceivable']),2);$x['customerAdvance']=round(max(0,(float)$x['customerAdvance']),2);if($x['openReceivable']>.005||$x['customerAdvance']>.005)$out[]=$x;}usort($out,static fn($a,$b)=>strcasecmp((string)$a['party'],(string)$b['party'])?:strcasecmp((string)$a['soda'],(string)$b['soda']));return $out;}
function lcr_cheque_bank_lines(float $amount,array $names,array $bank,bool $returned=false):array{
 $bankLine=lcr_line('1110',$returned?0:$amount,$returned?$amount:0,$names,['bankAccountId'=>$bank['id'],'bankName'=>$bank['bankName'],'bankAccountTitle'=>$bank['accountTitle'],'currency'=>'PKR']);
 $handLine=lcr_line('1130',$returned?$amount:0,$returned?0:$amount,$names);
 return $returned?[$handLine,$bankLine]:[$bankLine,$handLine];
}
function lcr_date(string $date):string{$d=DateTimeImmutable::createFromFormat('!Y-m-d',$date);if(!$d||$d->format('Y-m-d')!==$date)lcr_out(['ok'=>false,'error'=>'Valid cheque event date required.'],422);return $date;}
function lcr_find_bank(array $banks,string $id):array{foreach($banks as $b)if(($b['id']??'')===$id)return $b;lcr_out(['ok'=>false,'error'=>'Select an active PKR receipt bank.'],422);}

if(defined('TT_LCR_FUNCTIONS_ONLY'))return;
try{
 $u=tt_require_login();if(!tt_user_can_open_module($u,'Accounts'))lcr_out(['ok'=>false,'error'=>'Accounts permission required.'],403);$s=lcr_read();
 if($_SERVER['REQUEST_METHOD']==='GET'){$entity=strtoupper(trim((string)($_GET['entity']??'')));lcr_out(['ok'=>true,'rows'=>array_values(array_filter(lcr_open_rows($s),fn($row)=>($row['entity']??'')===$entity)),'banks'=>array_values(array_filter(lcr_banks($s),fn($bank)=>($bank['entity']??'')===$entity)),'cheques'=>array_values(array_filter((array)($s['localCustomerCheques']??[]),fn($item)=>is_array($item)&&($item['entity']??'')===$entity))]);}
 if($_SERVER['REQUEST_METHOD']!=='POST')lcr_out(['ok'=>false,'error'=>'Method not allowed.'],405);if(!lcr_can_write($u))lcr_out(['ok'=>false,'error'=>'Accounts Create / Edit / Approve permission required.'],403);
 $b=json_decode((function_exists('tt_accounts_input')?tt_accounts_input():file_get_contents('php://input'))?:'{}',true);if(!is_array($b)||!tt_verify_csrf((string)($b['csrf']??'')))lcr_out(['ok'=>false,'error'=>'Your session expired. Refresh and try again.'],419);
 $chequeAction=(string)($b['action']??'');
 if(in_array($chequeAction,['clear_customer_cheque','bounce_customer_cheque','cancel_customer_cheque'],true)){
  $entity=strtoupper(trim((string)($b['entity']??'')));if(!in_array($entity,['TTI','BRM'],true)||!tt_user_can_access_entity($u,$entity,'Edit'))lcr_out(['ok'=>false,'error'=>'Company permission required.'],403);
  $date=lcr_date((string)($b['date']??''));$id=trim((string)($b['chequeId']??''));$names=lcr_names();
  tt_ensure_data_dir();$h=fopen(TT_LCR_FILE,'c+');if($h===false||!flock($h,LOCK_EX))throw new RuntimeException('Accounts storage unavailable.');
  try{
   rewind($h);$raw=stream_get_contents($h);$store=$raw?json_decode($raw,true):null;if(!is_array($store))$store=[];$cheque=$store['localCustomerCheques'][$id]??null;
   if(!is_array($cheque)||($cheque['entity']??'')!==$entity)lcr_out(['ok'=>false,'error'=>'Customer cheque was not found in these books.'],404);
   $status=(string)($cheque['status']??'');$amount=(float)$cheque['amount'];$bank=['id'=>(string)$cheque['bankAccountId'],'bankName'=>(string)($cheque['bankName']??''),'accountTitle'=>(string)($cheque['bankAccountTitle']??''),'entity'=>$entity];
   if(($bank['entity']??'')!==$entity)lcr_out(['ok'=>false,'error'=>'Cheque bank belongs to another company.'],403);
   if($chequeAction==='clear_customer_cheque'){
    if($status!=='Issued')lcr_out(['ok'=>false,'error'=>'Only an issued cheque can clear once.'],409);
    if($date<(string)$cheque['chequeDate'])lcr_out(['ok'=>false,'error'=>'Bank clearance cannot predate the cheque date.'],422);
    $reference=trim((string)($b['bankReference']??''));if($reference==='')lcr_out(['ok'=>false,'error'=>'Bank statement reference required.'],422);
    $journal=lcr_post_journal($store,$u,$entity,$date,$reference,'Local customer cheque cleared — '.$cheque['party'],lcr_cheque_bank_lines($amount,$names,$bank),['sourceType'=>'LOCAL_CUSTOMER_CHEQUE_CLEARED','chequeId'=>$id,'bankAccountId'=>$bank['id']]);
    $cheque['status']='Cleared';$cheque['clearanceJournalId']=$journal['id'];$cheque['clearedAt']=$date;$cheque['bankReference']=$reference;
   }else{
    $reason=trim((string)($b['reason']??''));if($reason==='')lcr_out(['ok'=>false,'error'=>'Reason for returned or cancelled cheque required.'],422);
    if(!in_array($status,['Issued','Cleared'],true))lcr_out(['ok'=>false,'error'=>'Cheque was already resolved.'],409);
    if($chequeAction==='cancel_customer_cheque'&&$status==='Cleared')lcr_out(['ok'=>false,'error'=>'A cleared cheque must be recorded as bounced.'],409);
    if($date<(string)($status==='Cleared'?$cheque['clearedAt']:$cheque['date']))lcr_out(['ok'=>false,'error'=>'Resolution cannot predate issue or clearance.'],422);
    $ids=[];if($status==='Cleared'){$j=lcr_post_journal($store,$u,$entity,$date,(string)$cheque['chequeNo'],'Bank returned local customer cheque — '.$reason,lcr_cheque_bank_lines($amount,$names,$bank,true),['sourceType'=>'LOCAL_CUSTOMER_CHEQUE_BANK_REVERSAL','chequeId'=>$id,'reversalOf'=>$cheque['clearanceJournalId'],'bankAccountId'=>$bank['id']]);$ids[]=$j['id'];}
    $j=lcr_post_journal($store,$u,$entity,$date,(string)$cheque['chequeNo'],'Local receivable restored — '.$reason,[lcr_line('1220',$amount,0,$names,['soda'=>$cheque['soda'],'party'=>$cheque['party']]),lcr_line('1130',0,$amount,$names)],['sourceType'=>'LOCAL_CUSTOMER_CHEQUE_RECEIVABLE_REOPENED','chequeId'=>$id,'soda'=>$cheque['soda'],'party'=>$cheque['party'],'reversalOf'=>$cheque['issueJournalId']]);$ids[]=$j['id'];
    $cheque['status']=$chequeAction==='bounce_customer_cheque'?'Bounced':'Cancelled / Stopped';$cheque['resolutionReason']=$reason;$cheque['resolvedAt']=$date;$cheque['resolutionJournalIds']=$ids;
   }
   $store['localCustomerCheques'][$id]=$cheque;$store['revision']=(int)($store['revision']??0)+1;rewind($h);ftruncate($h,0);fwrite($h,json_encode($store,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($h);
  }finally{flock($h,LOCK_UN);fclose($h);}lcr_out(['ok'=>true,'cheque'=>$cheque]);
 }
 $soda=trim((string)($b['soda']??''));$party=trim((string)($b['party']??''));$product=trim((string)($b['product']??''));$date=trim((string)($b['date']??''));$amount=round((float)($b['amount']??0),2);$type=strtoupper(trim((string)($b['receiptType']??'')));if($soda===''||$party===''||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)||$amount<=0)lcr_out(['ok'=>false,'error'=>'Customer, Soda, date and receipt amount are required.'],422);if(!in_array($type,['BANK','CASH','ADJUSTMENT','CHEQUE'],true))lcr_out(['ok'=>false,'error'=>'Receipt type must be Bank, Cash, Cheque or Adjustment.'],422);
 $rows=lcr_open_rows($s);$matches=array_values(array_filter($rows,static fn($x)=>strcasecmp((string)$x['soda'],$soda)===0&&strcasecmp((string)$x['party'],$party)===0));if(!$matches)lcr_out(['ok'=>false,'error'=>'This customer / Soda is not available for receipt posting.'],404);$sale=$matches[0];$entity=(string)$sale['entity'];if(strtoupper(trim((string)($b['entity']??'')))!==$entity||!tt_user_can_access_entity($u,$entity,'Create'))lcr_out(['ok'=>false,'error'=>'Selected Soda belongs to another company.'],403);$banks=lcr_banks($s);$bank=null;
 if(in_array($type,['BANK','CHEQUE'],true)){$bank=lcr_find_bank($banks,trim((string)($b['bankAccountId']??'')));$bankEntity=(string)$bank['entity'];if($bankEntity!==$entity){lcr_out(['ok'=>false,'error'=>'This Soda is currently posted under '.$entity.' but the selected bank belongs to '.$bankEntity.'. The Local Sale company must be corrected first so one Soda never mixes TTI and BRM.'],409);}}
 if(in_array($type,['CASH','ADJUSTMENT'],true)&&$entity!=='BRM')$entity='TTI';
 $open=round((float)$sale['openReceivable'],2);if($type==='CHEQUE'&&$amount>$open+.005)lcr_out(['ok'=>false,'error'=>'A customer cheque must be allocated to the open Soda receivable; enter the amount up to the current balance.'],422);$toAr=min($amount,$open);$extra=round($amount-$toAr,2);$names=lcr_names();$lines=[];$meta=['soda'=>$soda,'party'=>$party,'product'=>$product,'receiptType'=>$type,'receivableApplied'=>$toAr,'customerAdvance'=>$extra];
 if($type==='BANK'){$lines[]=lcr_line('1110',$amount,0,$names,['bankAccountId'=>$bank['id'],'bankName'=>$bank['bankName'],'bankAccountTitle'=>$bank['accountTitle'],'currency'=>'PKR']);$meta['bankAccountId']=$bank['id'];$meta['bankName']=$bank['bankName'];}
 elseif($type==='CHEQUE'){$chequeNo=trim((string)($b['chequeNo']??''));$date=lcr_date($date);$chequeDate=lcr_date((string)($b['chequeDate']??''));if($chequeNo===''||$chequeDate<$date)lcr_out(['ok'=>false,'error'=>'Cheque number and a date on or after receipt are required.'],422);$lines[]=lcr_line('1130',$amount,0,$names);$meta['bankAccountId']=$bank['id'];$meta['bankName']=$bank['bankName'];$meta['chequeNo']=$chequeNo;$meta['chequeDate']=$chequeDate;$meta['sourceType']='LOCAL_CUSTOMER_CHEQUE_ISSUED';}
 elseif($type==='CASH'){$lines[]=lcr_line('1120',$amount,0,$names);}
 else{$src=trim((string)($b['sourceSoda']??''));if($src===''||$src===$soda)lcr_out(['ok'=>false,'error'=>'Choose a different Soda with available customer advance.'],422);$available=0.0;foreach($rows as $r)if((string)$r['entity']===$entity&&strcasecmp((string)$r['soda'],$src)===0)$available=max($available,(float)$r['customerAdvance']);if($amount>$available+.005)lcr_out(['ok'=>false,'error'=>'The selected source Soda does not have enough customer advance.'],422);$lines[]=lcr_line('2510',$amount,0,$names,['soda'=>$src,'advanceMove'=>'From']);$meta['sourceSoda']=$src;}
 if($toAr>.005)$lines[]=lcr_line('1220',0,$toAr,$names,['soda'=>$soda,'party'=>$party]);if($extra>.005)$lines[]=lcr_line('2510',0,$extra,$names,['soda'=>$soda,'party'=>$party,'advanceMove'=>'To']);
 tt_ensure_data_dir();$h=fopen(TT_LCR_FILE,'c+');if($h===false||!flock($h,LOCK_EX))throw new RuntimeException('Accounts storage unavailable.');try{rewind($h);$raw=stream_get_contents($h);$store=$raw?json_decode($raw,true):null;if(!is_array($store))$store=[];if($type==='CHEQUE'){$fresh=array_values(array_filter(lcr_open_rows($store),fn($row)=>($row['entity']??'')===$entity&&strcasecmp((string)($row['soda']??''),$soda)===0&&strcasecmp((string)($row['party']??''),$party)===0));if(!$fresh||$amount>(float)$fresh[0]['openReceivable']+.005)lcr_out(['ok'=>false,'error'=>'Customer receivable changed; refresh and try again.'],409);foreach((array)($store['localCustomerCheques']??[]) as $prior)if(is_array($prior)&&($prior['entity']??'')===$entity&&strcasecmp((string)($prior['party']??''),$party)===0&&strcasecmp((string)($prior['chequeNo']??''),$chequeNo)===0)lcr_out(['ok'=>false,'error'=>'This customer cheque number was already recorded.'],409);$chequeId=lcr_next((array)($store['localCustomerCheques']??[]),'LCH');$meta['chequeId']=$chequeId;}$ref=trim((string)($b['reference']??''));$journal=lcr_post_journal($store,$u,$entity,$date,$ref?:('LCR-'.$soda),'Local customer receipt — '.$party.' — '.$soda,$lines,$meta);if($type==='CHEQUE')$store['localCustomerCheques'][$chequeId]=['id'=>$chequeId,'entity'=>$entity,'soda'=>$soda,'party'=>$party,'amount'=>$amount,'date'=>$date,'chequeNo'=>$chequeNo,'chequeDate'=>$chequeDate,'bankAccountId'=>$bank['id'],'bankName'=>$bank['bankName'],'bankAccountTitle'=>$bank['accountTitle'],'status'=>'Issued','issueJournalId'=>$journal['id'],'createdAt'=>gmdate('c')];$store['revision']=(int)($store['revision']??0)+1;rewind($h);ftruncate($h,0);fwrite($h,json_encode($store,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($h);}finally{flock($h,LOCK_UN);fclose($h);}lcr_out(['ok'=>true,'journal'=>$journal,'entity'=>$entity,'receivableApplied'=>$toAr,'customerAdvance'=>$extra]);
}catch(Throwable $e){lcr_out(['ok'=>false,'error'=>'Local customer receipt could not be completed.'],500);}

