<?php
declare(strict_types=1);

require dirname(__DIR__) . '/auth_store.php';
header('Content-Type: application/json; charset=UTF-8');
header('Cache-Control: no-store, no-cache, must-revalidate');

const TT_LSC_FILE = TT_DATA_DIR . '/accounts.json';
const TT_LSC_MASTER = __DIR__ . '/../accounts/accounting_master_v1.json';

function lsc_out(array $d,int $s=200):never{http_response_code($s);echo json_encode($d,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function lsc_can_write(array $u):bool{if(($u['role']??'')==='Super Admin')return true;$p=$u['permissions']['Accounts']??null;if($p==='all')return true;if(!is_array($p))return false;if(in_array('Create',$p,true)||in_array('Edit',$p,true)||in_array('Approve',$p,true))return true;foreach($p as $a)if(is_array($a)&&(in_array('Create',$a,true)||in_array('Edit',$a,true)||in_array('Approve',$a,true)))return true;return false;}
function lsc_def():array{return ['revision'=>0,'journals'=>[],'localSalesCandidates'=>[],'inventoryCostRates'=>[],'localSalesCostRates'=>[]];}
function lsc_read():array{tt_ensure_data_dir();if(!is_file(TT_LSC_FILE))return lsc_def();$h=fopen(TT_LSC_FILE,'r');if($h===false||!flock($h,LOCK_SH))throw new RuntimeException('Accounts storage unavailable.');try{$raw=stream_get_contents($h);}finally{flock($h,LOCK_UN);fclose($h);}$v=$raw?json_decode($raw,true):null;return is_array($v)?array_replace_recursive(lsc_def(),$v):lsc_def();}
function lsc_names():array{$raw=is_file(TT_LSC_MASTER)?file_get_contents(TT_LSC_MASTER):false;$m=$raw?json_decode($raw,true):null;if(!is_array($m))throw new RuntimeException('Accounting master unavailable.');$o=[];foreach((array)($m['chart']??[]) as $a)if(is_array($a)&&isset($a['code']))$o[(string)$a['code']]=(string)($a['name']??$a['code']);return $o;}
function lsc_line(string $a,float $dr,float $cr,array $names,array $extra=[]):array{if(!isset($names[$a]))lsc_out(['ok'=>false,'error'=>'Approved account '.$a.' is unavailable.'],422);return array_merge(['account'=>$a,'accountName'=>$names[$a],'debit'=>round($dr,2),'credit'=>round($cr,2)],$extra);}
function lsc_date(string $v):string{if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$v))lsc_out(['ok'=>false,'error'=>'Valid date required.'],422);return $v;}
function lsc_entity(string $v):string{$v=strtoupper(trim($v));if(!in_array($v,['TTI','BRM'],true))lsc_out(['ok'=>false,'error'=>'Company must be TTI or BRM.'],422);return $v;}
function lsc_next(array $items,string $p):string{$n=count($items)+1;do{$id=$p.'-'.gmdate('Y').'-'.str_pad((string)$n,6,'0',STR_PAD_LEFT);$n++;}while(isset($items[$id]));return $id;}
function lsc_norm(string $v):string{return strtoupper(trim(preg_replace('/\s+/',' ',$v)??$v));}
function lsc_rates(array $s):array{$rows=[];foreach((array)($s['localSalesCostRates']??[]) as $r)if(is_array($r))$rows[]=array_merge($r,['rateSource'=>'Legacy Local Cost']);foreach((array)($s['inventoryCostRates']??[]) as $r)if(is_array($r))$rows[]=array_merge($r,['rateSource'=>'Shared Stock Cost']);return $rows;}
function lsc_rate_for(array $s,string $entity,string $product,string $date):?array{$best=null;$pn=lsc_norm($product);foreach(lsc_rates($s) as $r){if(($r['status']??'Active')!=='Active'||($r['entity']??'')!==$entity||lsc_norm((string)($r['product']??''))!==$pn)continue;$from=(string)($r['effectiveFrom']??'');if($from===''||$from>$date)continue;$rank=($r['rateSource']??'')==='Shared Stock Cost'?2:1;$bestRank=$best?(int)($best['_rank']??0):0;if($best===null||$from>(string)$best['effectiveFrom']||($from===(string)$best['effectiveFrom']&&$rank>$bestRank)){$best=$r;$best['_rank']=$rank;}}return $best;}
function lsc_waiting(array $s,?string $entity=null):array{$o=[];foreach((array)($s['localSalesCandidates']??[]) as $c){if(!is_array($c)||empty($c['journalId'])||!empty($c['costJournalId']))continue;if($entity!==null&&($c['entity']??'')!==$entity)continue;$rate=lsc_rate_for($s,(string)$c['entity'],(string)$c['product'],(string)$c['saleDate']);$c['costRateAvailable']=$rate!==null;$c['suggestedCostPerKg']=$rate?(float)$rate['costPerKg']:null;$c['costInventoryAccount']=$rate?(string)$rate['inventoryAccount']:null;$c['costStatus']=$rate?'Ready to Post':'Cost Waiting';$o[]=$c;}usort($o,static fn($a,$b)=>strcmp((string)($b['saleDate']??''),(string)($a['saleDate']??''))?:strcmp((string)($b['soda']??''),(string)($a['soda']??'')));return $o;}
function lsc_recent(array $s,?string $entity=null):array{$o=[];foreach((array)($s['localSalesCandidates']??[]) as $c){if(!is_array($c)||empty($c['costJournalId']))continue;if($entity!==null&&($c['entity']??'')!==$entity)continue;$o[]=$c;}usort($o,static fn($a,$b)=>strcmp((string)($b['saleDate']??''),(string)($a['saleDate']??'')));return array_slice($o,0,30);}
function lsc_payload(array $s,?string $entity=null):array{$rates=array_values(array_filter(lsc_rates($s),static fn($r)=>is_array($r)&&($entity===null||($r['entity']??'')===$entity)));usort($rates,static fn($a,$b)=>strcmp((string)($b['effectiveFrom']??''),(string)($a['effectiveFrom']??'')));return ['ok'=>true,'waiting'=>lsc_waiting($s,$entity),'recent'=>lsc_recent($s,$entity),'rates'=>$rates,'serverNow'=>gmdate('c')];}
function lsc_post_costs(array &$s,array $names,array $user,?string $onlyId=null):array{$posted=[];$skipped=[];foreach((array)$s['localSalesCandidates'] as $id=>$c){if(!is_array($c)||empty($c['journalId'])||!empty($c['costJournalId']))continue;if($onlyId!==null&&$id!==$onlyId)continue;$entity=(string)($c['entity']??'');$date=(string)($c['saleDate']??'');$product=(string)($c['product']??'');$kg=round((float)($c['loadedKg']??0),3);$rate=lsc_rate_for($s,$entity,$product,$date);if(!$rate){$skipped[]=['id'=>$id,'reason'=>'No stock cost for '.$product.' on '.$date];continue;}if($kg<=0){$skipped[]=['id'=>$id,'reason'=>'Loaded quantity is missing.'];continue;}$costPerKg=round((float)($rate['costPerKg']??0),6);if($costPerKg<=0){$skipped[]=['id'=>$id,'reason'=>'Stock cost is zero.'];continue;}$inventory=(string)($rate['inventoryAccount']??'');if(!in_array($inventory,['1310','1320','1330'],true)){$skipped[]=['id'=>$id,'reason'=>'Stock cost has an invalid stock type.'];continue;}$amount=round($kg*$costPerKg,2);if($amount<=0)continue;$jid=lsc_next((array)$s['journals'],'AUTO');$extra=['soda'=>(string)($c['soda']??''),'party'=>(string)($c['party']??''),'product'=>$product,'gatePass'=>(string)($c['gatePass']??''),'loadedKg'=>$kg,'costPerKg'=>$costPerKg,'costRateId'=>(string)($rate['id']??'')];$lines=[lsc_line('5100',$amount,0,$names,$extra),lsc_line($inventory,0,$amount,$names,$extra)];$s['journals'][$jid]=['id'=>$jid,'entity'=>$entity,'date'=>$date,'sourceType'=>'LOCAL_SALE_COGS','reference'=>(string)($c['gatePass']?:$c['soda']),'narration'=>'Local Sale stock cost — '.(string)($c['soda']??'').' — '.$product,'lines'=>$lines,'totalDebit'=>$amount,'totalCredit'=>$amount,'status'=>'Posted','meta'=>['localSaleCandidateId'=>$id,'saleJournalId'=>(string)$c['journalId'],'soda'=>(string)($c['soda']??''),'party'=>(string)($c['party']??''),'product'=>$product,'loadedKg'=>$kg,'costPerKg'=>$costPerKg,'costAmount'=>$amount,'inventoryAccount'=>$inventory,'costRateId'=>(string)($rate['id']??''),'rateSource'=>(string)($rate['rateSource']??''),'rule'=>'Shared Accounts stock cost. Mill quantity is not changed by this journal.'],'createdAt'=>gmdate('c'),'createdBy'=>(string)($user['full_name']??$user['username']??'Accounts'),'userId'=>(int)($user['id']??0),'reversalOf'=>null];$s['localSalesCandidates'][$id]['costJournalId']=$jid;$s['localSalesCandidates'][$id]['costStatus']='Cost Posted';$s['localSalesCandidates'][$id]['costPerKg']=$costPerKg;$s['localSalesCandidates'][$id]['costAmount']=$amount;$s['localSalesCandidates'][$id]['costInventoryAccount']=$inventory;$s['localSalesCandidates'][$id]['costRateId']=(string)($rate['id']??'');$s['localSalesCandidates'][$id]['costPostedAt']=gmdate('c');$posted[]=['candidateId'=>$id,'journalId'=>$jid,'amount'=>$amount];}return ['posted'=>$posted,'skipped'=>$skipped];}

try{
 $u=tt_require_login();if(!tt_user_can_open_module($u,'Accounts'))lsc_out(['ok'=>false,'error'=>'Accounts permission required.'],403);
 if($_SERVER['REQUEST_METHOD']==='GET'){$entity=strtoupper(trim((string)($_GET['entity']??'')));if($entity!==''&&!in_array($entity,['TTI','BRM'],true))lsc_out(['ok'=>false,'error'=>'Invalid company.'],422);lsc_out(lsc_payload(lsc_read(),$entity?:null));}
 if($_SERVER['REQUEST_METHOD']!=='POST')lsc_out(['ok'=>false,'error'=>'Method not allowed.'],405);if(!lsc_can_write($u))lsc_out(['ok'=>false,'error'=>'Accounts Create, Edit or Approve permission required.'],403);$b=json_decode(file_get_contents('php://input')?:'{}',true);if(!is_array($b)||!tt_verify_csrf((string)($b['csrf']??'')))lsc_out(['ok'=>false,'error'=>'Your session expired. Refresh and try again.'],419);$action=(string)($b['action']??'');
 tt_ensure_data_dir();$h=fopen(TT_LSC_FILE,'c+');if($h===false||!flock($h,LOCK_EX))throw new RuntimeException('Accounts storage unavailable.');try{rewind($h);$raw=stream_get_contents($h);$s=$raw?json_decode($raw,true):null;if(!is_array($s))$s=lsc_def();$s=array_replace_recursive(lsc_def(),$s);$names=lsc_names();
  if($action==='save_rate'){$entity=lsc_entity((string)($b['entity']??''));$product=trim((string)($b['product']??''));if($product==='')lsc_out(['ok'=>false,'error'=>'Product is required.'],422);$from=lsc_date((string)($b['effectiveFrom']??''));$cost=round((float)($b['costPerKg']??0),6);if($cost<=0)lsc_out(['ok'=>false,'error'=>'Cost per kg must be greater than zero.'],422);$inventory=(string)($b['inventoryAccount']??'');if(!in_array($inventory,['1310','1320','1330'],true))lsc_out(['ok'=>false,'error'=>'Select Raw Stock, Ready Rice or By-product stock.'],422);foreach((array)$s['inventoryCostRates'] as $r)if(is_array($r)&&($r['entity']??'')===$entity&&lsc_norm((string)($r['product']??''))===lsc_norm($product)&&(string)($r['effectiveFrom']??'')===$from&&($r['status']??'Active')==='Active')lsc_out(['ok'=>false,'error'=>'A stock cost already starts on this date for this product. Use a new effective date.'],409);$id='ICR-'.gmdate('YmdHis').'-'.substr(hash('sha256',$entity.'|'.$product.'|'.$from.'|'.microtime(true)),0,6);$s['inventoryCostRates'][$id]=['id'=>$id,'entity'=>$entity,'product'=>$product,'effectiveFrom'=>$from,'costPerKg'=>$cost,'inventoryAccount'=>$inventory,'status'=>'Active','notes'=>trim((string)($b['notes']??'')),'createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??$u['username']??'Accounts')];$result=lsc_post_costs($s,$names,$u,null);
  }elseif($action==='post_waiting'){$only=trim((string)($b['candidateId']??''));$result=lsc_post_costs($s,$names,$u,$only!==''?$only:null);
  }else lsc_out(['ok'=>false,'error'=>'Unknown Local Sales costing action.'],422);
  $s['revision']=(int)($s['revision']??0)+1;rewind($h);ftruncate($h,0);fwrite($h,json_encode($s,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($h);
 }finally{flock($h,LOCK_UN);fclose($h);}lsc_out(lsc_payload($s,null)+['result'=>$result,'revision'=>$s['revision']]);
}catch(Throwable $e){lsc_out(['ok'=>false,'error'=>'Local Sales stock cost could not be completed.'],500);}
