<?php
declare(strict_types=1);
require dirname(__DIR__) . '/auth_store.php';
header('Content-Type: application/json; charset=UTF-8');
header('Cache-Control: no-store, no-cache, must-revalidate');

const TT_LCR_FILE = TT_DATA_DIR . '/accounts.json';
const TT_LCR_MASTER = __DIR__ . '/../accounts/accounting_master_v1.json';

function lcr_out(array $d,int $s=200):never{http_response_code($s);echo json_encode($d,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function lcr_read():array{tt_ensure_data_dir();if(!is_file(TT_LCR_FILE))return []; $h=fopen(TT_LCR_FILE,'r');if($h===false||!flock($h,LOCK_SH))throw new RuntimeException('Accounts storage unavailable.');try{$raw=stream_get_contents($h);}finally{flock($h,LOCK_UN);fclose($h);} $v=$raw?json_decode($raw,true):null;return is_array($v)?$v:[];}
function lcr_can_write(array $u):bool{if(($u['role']??'')==='Super Admin')return true;$p=$u['permissions']['Accounts']??null;if($p==='all')return true;if(!is_array($p))return false;if(in_array('Create',$p,true)||in_array('Edit',$p,true)||in_array('Approve',$p,true))return true;foreach($p as $a)if(is_array($a)&&(in_array('Create',$a,true)||in_array('Edit',$a,true)||in_array('Approve',$a,true)))return true;return false;}
function lcr_names():array{$raw=file_get_contents(TT_LCR_MASTER);$m=$raw?json_decode($raw,true):null;if(!is_array($m))throw new RuntimeException('Accounting master unavailable.');$o=[];foreach((array)($m['chart']??[]) as $a)if(is_array($a)&&isset($a['code']))$o[(string)$a['code']]=(string)($a['name']??$a['code']);return $o;}
function lcr_line(string $a,float $dr,float $cr,array $names,array $extra=[]):array{if(!isset($names[$a]))lcr_out(['ok'=>false,'error'=>'Approved account '.$a.' is unavailable.'],422);return array_merge(['account'=>$a,'accountName'=>$names[$a],'debit'=>round($dr,2),'credit'=>round($cr,2)],$extra);}
function lcr_next(array $items,string $p):string{$n=count($items)+1;do{$id=$p.'-'.gmdate('Y').'-'.str_pad((string)$n,6,'0',STR_PAD_LEFT);$n++;}while(isset($items[$id]));return $id;}
function lcr_post_journal(array &$s,array $u,string $entity,string $date,string $reference,string $narration,array $lines,array $meta):array{$dr=round(array_sum(array_column($lines,'debit')),2);$cr=round(array_sum(array_column($lines,'credit')),2);if($dr<=0||abs($dr-$cr)>.005)throw new RuntimeException('Receipt journal did not balance.');$id=lcr_next((array)($s['journals']??[]),'AUTO');$s['journals'][$id]=['id'=>$id,'entity'=>$entity,'date'=>$date,'sourceType'=>'LOCAL_CUSTOMER_RECEIPT','reference'=>$reference,'narration'=>$narration,'lines'=>$lines,'totalDebit'=>$dr,'totalCredit'=>$cr,'status'=>'Posted','meta'=>$meta,'createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??$u['username']??'Accounts'),'userId'=>(int)($u['id']??0),'reversalOf'=>null];return $s['journals'][$id];}
function lcr_entity_from_linked(string $v):string{$u=strtoupper($v);if(str_contains($u,'BRM')||str_contains($u,'BUKSH RICE'))return 'BRM';if(str_contains($u,'TTI')||str_contains($u,'TRANSTRADE INTERNATIONAL'))return 'TTI';return '';}
function lcr_banks(array $s):array{$m=tt_list_masters();$o=[];foreach((array)($m['banks']??[]) as $r){if(!is_array($r))continue;$v=array_values((array)($r['values']??[]));while(count($v)<14)$v[]='';$entity=lcr_entity_from_linked((string)$v[1]);$id=(string)($r['id']??'');if(!in_array($entity,['TTI','BRM'],true)||trim((string)$v[0])!=='Company Account'||strtoupper(trim((string)$v[7]))!=='PKR')continue;$set=is_array($s['bankAccountSettings'][$id]??null)?$s['bankAccountSettings'][$id]:[];if(empty($set['active'])||empty($set['allowReceipts']))continue;$raw=preg_replace('/\W+/','',trim((string)($v[8]?:$v[9])))??'';$tail=$raw!==''?substr($raw,-5):'';$o[]=['id'=>$id,'entity'=>$entity,'bankName'=>(string)$v[4],'accountTitle'=>(string)$v[3],'display'=>trim((string)$v[4]).($tail!==''?' — •••••'.$tail:'')];}return $o;}
function lcr_line_soda(array $j,array $l):string{$m=is_array($j['meta']??null)?$j['meta']:[];return trim((string)($l['soda']??$m['soda']??$m['targetSoda']??$m['advanceSoda']??''));}
function lcr_open_rows(array $s):array{$map=[];foreach((array)($s['journals']??[]) as $j){if(!is_array($j)||($j['status']??'')!=='Posted')continue;$entity=(string)($j['entity']??'');if(!in_array($entity,['TTI','BRM'],true))continue;$meta=is_array($j['meta']??null)?$j['meta']:[];foreach((array)($j['lines']??[]) as $l){if(!is_array($l)||(string)($l['account']??'')!=='1220')continue;$soda=lcr_line_soda($j,$l);if($soda==='')continue;$k=$entity.'|'.$soda;if(!isset($map[$k]))$map[$k]=['entity'=>$entity,'soda'=>$soda,'party'=>(string)($l['party']??$meta['party']??''),'product'=>(string)($meta['product']??''),'openReceivable'=>0.0,'customerAdvance'=>0.0];$map[$k]['openReceivable']+=(float)($l['debit']??0)-(float)($l['credit']??0);}}
foreach((array)($s['journals']??[]) as $j){if(!is_array($j)||($j['status']??'')!=='Posted')continue;$entity=(string)($j['entity']??'');if(!in_array($entity,['TTI','BRM'],true))continue;$meta=is_array($j['meta']??null)?$j['meta']:[];foreach((array)($j['lines']??[]) as $l){if(!is_array($l)||(string)($l['account']??'')!=='2510')continue;$soda=lcr_line_soda($j,$l);if($soda==='')continue;$k=$entity.'|'.$soda;if(!isset($map[$k]))$map[$k]=['entity'=>$entity,'soda'=>$soda,'party'=>(string)($l['party']??$meta['party']??''),'product'=>(string)($meta['product']??''),'openReceivable'=>0.0,'customerAdvance'=>0.0];$map[$k]['customerAdvance']+=(float)($l['credit']??0)-(float)($l['debit']??0);}}
$out=[];foreach($map as $x){$x['openReceivable']=round(max(0,(float)$x['openReceivable']),2);$x['customerAdvance']=round(max(0,(float)$x['customerAdvance']),2);if($x['openReceivable']>.005||$x['customerAdvance']>.005)$out[]=$x;}usort($out,static fn($a,$b)=>strcasecmp((string)$a['party'],(string)$b['party'])?:strcasecmp((string)$a['soda'],(string)$b['soda']));return $out;}
function lcr_find_bank(array $banks,string $id):array{foreach($banks as $b)if(($b['id']??'')===$id)return $b;lcr_out(['ok'=>false,'error'=>'Select an active PKR receipt bank.'],422);}

try{
 $u=tt_require_login();if(!tt_user_can_open_module($u,'Accounts'))lcr_out(['ok'=>false,'error'=>'Accounts permission required.'],403);$s=lcr_read();
 if($_SERVER['REQUEST_METHOD']==='GET')lcr_out(['ok'=>true,'rows'=>lcr_open_rows($s),'banks'=>lcr_banks($s)]);
 if($_SERVER['REQUEST_METHOD']!=='POST')lcr_out(['ok'=>false,'error'=>'Method not allowed.'],405);if(!lcr_can_write($u))lcr_out(['ok'=>false,'error'=>'Accounts Create / Edit / Approve permission required.'],403);
 $b=json_decode(file_get_contents('php://input')?:'{}',true);if(!is_array($b)||!tt_verify_csrf((string)($b['csrf']??'')))lcr_out(['ok'=>false,'error'=>'Your session expired. Refresh and try again.'],419);
 $soda=trim((string)($b['soda']??''));$party=trim((string)($b['party']??''));$product=trim((string)($b['product']??''));$date=trim((string)($b['date']??''));$amount=round((float)($b['amount']??0),2);$type=strtoupper(trim((string)($b['receiptType']??'')));if($soda===''||$party===''||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)||$amount<=0)lcr_out(['ok'=>false,'error'=>'Customer, Soda, date and receipt amount are required.'],422);if(!in_array($type,['BANK','CASH','ADJUSTMENT'],true))lcr_out(['ok'=>false,'error'=>'Receipt type must be Bank, Cash or Adjustment.'],422);
 $rows=lcr_open_rows($s);$matches=array_values(array_filter($rows,static fn($x)=>strcasecmp((string)$x['soda'],$soda)===0&&strcasecmp((string)$x['party'],$party)===0));if(!$matches)lcr_out(['ok'=>false,'error'=>'This customer / Soda is not available for receipt posting.'],404);$sale=$matches[0];$entity=(string)$sale['entity'];$banks=lcr_banks($s);$bank=null;
 if($type==='BANK'){$bank=lcr_find_bank($banks,trim((string)($b['bankAccountId']??'')));$bankEntity=(string)$bank['entity'];if($bankEntity!==$entity){lcr_out(['ok'=>false,'error'=>'This Soda is currently posted under '.$entity.' but the selected bank belongs to '.$bankEntity.'. The Local Sale company must be corrected first so one Soda never mixes TTI and BRM.'],409);}}
 if($type!=='BANK'&&$entity!=='BRM')$entity='TTI';
 $open=round((float)$sale['openReceivable'],2);$toAr=min($amount,$open);$extra=round($amount-$toAr,2);$names=lcr_names();$lines=[];$meta=['soda'=>$soda,'party'=>$party,'product'=>$product,'receiptType'=>$type,'receivableApplied'=>$toAr,'customerAdvance'=>$extra];
 if($type==='BANK'){$lines[]=lcr_line('1110',$amount,0,$names,['bankAccountId'=>$bank['id'],'bankName'=>$bank['bankName'],'bankAccountTitle'=>$bank['accountTitle'],'currency'=>'PKR']);$meta['bankAccountId']=$bank['id'];$meta['bankName']=$bank['bankName'];}
 elseif($type==='CASH'){$lines[]=lcr_line('1120',$amount,0,$names);}
 else{$src=trim((string)($b['sourceSoda']??''));if($src===''||$src===$soda)lcr_out(['ok'=>false,'error'=>'Choose a different Soda with available customer advance.'],422);$available=0.0;foreach($rows as $r)if((string)$r['entity']===$entity&&strcasecmp((string)$r['soda'],$src)===0)$available=max($available,(float)$r['customerAdvance']);if($amount>$available+.005)lcr_out(['ok'=>false,'error'=>'The selected source Soda does not have enough customer advance.'],422);$lines[]=lcr_line('2510',$amount,0,$names,['soda'=>$src,'advanceMove'=>'From']);$meta['sourceSoda']=$src;}
 if($toAr>.005)$lines[]=lcr_line('1220',0,$toAr,$names,['soda'=>$soda,'party'=>$party]);if($extra>.005)$lines[]=lcr_line('2510',0,$extra,$names,['soda'=>$soda,'party'=>$party,'advanceMove'=>'To']);
 tt_ensure_data_dir();$h=fopen(TT_LCR_FILE,'c+');if($h===false||!flock($h,LOCK_EX))throw new RuntimeException('Accounts storage unavailable.');try{rewind($h);$raw=stream_get_contents($h);$store=$raw?json_decode($raw,true):null;if(!is_array($store))$store=[];$ref=trim((string)($b['reference']??''));$journal=lcr_post_journal($store,$u,$entity,$date,$ref?:('LCR-'.$soda),'Local customer receipt — '.$party.' — '.$soda,$lines,$meta);$store['revision']=(int)($store['revision']??0)+1;rewind($h);ftruncate($h,0);fwrite($h,json_encode($store,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($h);}finally{flock($h,LOCK_UN);fclose($h);}lcr_out(['ok'=>true,'journal'=>$journal,'entity'=>$entity,'receivableApplied'=>$toAr,'customerAdvance'=>$extra]);
}catch(Throwable $e){lcr_out(['ok'=>false,'error'=>'Local customer receipt could not be completed.'],500);}

