<?php
declare(strict_types=1);

require dirname(__DIR__) . '/auth_store.php';
header('Content-Type: application/json; charset=UTF-8');
header('Cache-Control: no-store, no-cache, must-revalidate');

const TT_LS_ACCOUNTS_FILE = TT_DATA_DIR . '/accounts.json';
const TT_LS_MASTER_FILE = __DIR__ . '/../accounts/accounting_master_v1.json';
const TT_LS_POLICY_FILE = __DIR__ . '/../accounts/local_sales_policy_v1.json';

function ls_respond(array $data,int $status=200):never{http_response_code($status);echo json_encode($data,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function ls_json(string $path):array{$raw=is_file($path)?file_get_contents($path):false;$v=$raw?json_decode($raw,true):null;if(!is_array($v))throw new RuntimeException('Required configuration is unavailable.');return $v;}
function ls_module_write(array $u,string $m):bool{if(($u['role']??'')==='Super Admin')return true;$p=$u['permissions'][$m]??null;if($p==='all')return true;if(!is_array($p))return false;if(in_array('Create',$p,true)||in_array('Edit',$p,true)||in_array('Approve',$p,true))return true;foreach($p as $a)if(is_array($a)&&(in_array('Create',$a,true)||in_array('Edit',$a,true)||in_array('Approve',$a,true)))return true;return false;}
function ls_default_store():array{return ['revision'=>0,'journals'=>[],'events'=>[],'reminders'=>[],'alerts'=>[],'masters'=>[],'commodityBills'=>[],'exportCandidates'=>[],'localSalesCandidates'=>[],'localSalesPaymentCandidates'=>[]];}
function ls_read():array{tt_ensure_data_dir();if(!is_file(TT_LS_ACCOUNTS_FILE))return ls_default_store();$h=fopen(TT_LS_ACCOUNTS_FILE,'r');if($h===false||!flock($h,LOCK_SH))throw new RuntimeException('Accounts storage unavailable.');try{$raw=stream_get_contents($h);}finally{flock($h,LOCK_UN);fclose($h);}$s=$raw?json_decode($raw,true):null;return is_array($s)?array_replace_recursive(ls_default_store(),$s):ls_default_store();}
function ls_valid_entity(string $v):string{$v=strtoupper(trim($v));if(!in_array($v,['TTI','BRM'],true))ls_respond(['ok'=>false,'error'=>'Selling Company must be TTI or BRM.'],422);return $v;}
function ls_date(string $v):string{if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$v))ls_respond(['ok'=>false,'error'=>'Valid sale date required.'],422);return $v;}
function ls_positive(mixed $v,string $label):float{$n=round((float)$v,2);if($n<=0)ls_respond(['ok'=>false,'error'=>$label.' must be greater than zero.'],422);return $n;}
function ls_fy_bounds(string $date,array $policy):array{$d=new DateTimeImmutable($date.' 00:00:00',new DateTimeZone('Asia/Karachi'));[$m,$day]=array_map('intval',explode('-',str_pad((string)($policy['financialYearEnd']??'06-30'),5,'0',STR_PAD_LEFT)));$year=(int)$d->format('Y');$end=DateTimeImmutable::createFromFormat('!Y-n-j',$year.'-'.$m.'-'.$day,new DateTimeZone('Asia/Karachi'));if(!$end)throw new RuntimeException('Financial year configuration is invalid.');if($d>$end)$end=$end->modify('+1 year');$start=$end->modify('-1 year')->modify('+1 day');return [$start->format('Y-m-d'),$end->format('Y-m-d')];}
function ls_revenue_sum(array $s,array $entities,string $account,string $from,string $to):float{$n=0;foreach((array)($s['journals']??[]) as $j){if(!is_array($j)||($j['status']??'')!=='Posted'||!in_array((string)($j['entity']??''),$entities,true))continue;$d=(string)($j['date']??'');if($d<$from||$d>$to)continue;foreach((array)($j['lines']??[]) as $l)if(is_array($l)&&(string)($l['account']??'')===$account)$n+=(float)($l['credit']??0)-(float)($l['debit']??0);}return round($n,2);}
function ls_summary(array $s,string $asOf,array $policy,float $pendingAdd=0):array{[$from,$to]=ls_fy_bounds($asOf,$policy);$scope=(array)($policy['scope']??[]);$localEntities=array_values((array)($scope['localSaleEntities']??['TTI','BRM']));$exportEntities=array_values((array)($scope['exportSaleEntities']??['TTI','BRM']));$localAccount=(string)($scope['localRevenueAccount']??'4200');$exportAccount=(string)($scope['exportRevenueAccount']??'4100');$local=ls_revenue_sum($s,$localEntities,$localAccount,$from,$to);$export=ls_revenue_sum($s,$exportEntities,$exportAccount,$from,$to);$ratio=$export>0?round($local/$export*100,4):($local>0?INF:0);$projectedLocal=round($local+$pendingAdd,2);$projected=$export>0?round($projectedLocal/$export*100,4):($projectedLocal>0?INF:0);$warning=(float)($policy['warningPercent']??4.8);$critical=(float)($policy['criticalPercent']??5);$criticalAmount=round($export*$critical/100,2);$byProduct=[];foreach((array)($s['journals']??[]) as $j){if(!is_array($j)||($j['status']??'')!=='Posted'||!in_array((string)($j['entity']??''),$localEntities,true))continue;$d=(string)($j['date']??'');if($d<$from||$d>$to)continue;$amt=0;foreach((array)($j['lines']??[]) as $l)if(is_array($l)&&(string)($l['account']??'')===$localAccount)$amt+=(float)($l['credit']??0)-(float)($l['debit']??0);if(abs($amt)<.005)continue;$m=is_array($j['meta']??null)?$j['meta']:[];$p=trim((string)($m['product']??$m['byProduct']??'Unspecified'))?:'Unspecified';$byProduct[$p]=round(($byProduct[$p]??0)+$amt,2);}arsort($byProduct);$status='OK';if(!is_finite($ratio)||$ratio>=$critical)$status='CRITICAL';elseif($ratio>=$warning)$status='WARNING';return ['financialYearFrom'=>$from,'financialYearTo'=>$to,'asOf'=>$asOf,'localSales'=>$local,'exportSales'=>$export,'ratioPercent'=>is_finite($ratio)?$ratio:null,'projectedLocalSales'=>$projectedLocal,'projectedRatioPercent'=>is_finite($projected)?$projected:null,'warningPercent'=>$warning,'criticalPercent'=>$critical,'criticalAmount'=>$criticalAmount,'remainingHeadroom'=>round($criticalAmount-$local,2),'status'=>$status,'byProduct'=>$byProduct];}
function ls_account_names():array{$m=ls_json(TT_LS_MASTER_FILE);$out=[];foreach((array)($m['chart']??[]) as $a)if(is_array($a)&&isset($a['code']))$out[(string)$a['code']]=(string)($a['name']??$a['code']);return $out;}
function ls_line(string $a,float $dr,float $cr,array $names,array $extra=[]):array{if(!isset($names[$a]))ls_respond(['ok'=>false,'error'=>'Approved account '.$a.' is missing from Chart of Accounts.'],422);return array_merge(['account'=>$a,'accountName'=>$names[$a],'debit'=>round($dr,2),'credit'=>round($cr,2)],$extra);}
function ls_next_id(array $items,string $p):string{$n=count($items)+1;do{$id=$p.'-'.gmdate('Y').'-'.str_pad((string)$n,6,'0',STR_PAD_LEFT);$n++;}while(isset($items[$id]));return $id;}
function ls_is_critical(?float $p,float $c):bool{return $p===null||$p>=$c;}
function ls_line_soda(array $j,array $l):string{$m=is_array($j['meta']??null)?$j['meta']:[];return trim((string)($l['soda']??$m['soda']??$m['targetSoda']??$m['advanceSoda']??''));}
function ls_balance(array $s,string $entity,string $account,string $soda,bool $creditNormal=false):float{$n=0;foreach((array)($s['journals']??[]) as $j){if(!is_array($j)||($j['status']??'')!=='Posted'||($j['entity']??'')!==$entity)continue;foreach((array)($j['lines']??[]) as $l){if(!is_array($l)||(string)($l['account']??'')!==$account||ls_line_soda($j,$l)!==$soda)continue;$n+=$creditNormal?((float)($l['credit']??0)-(float)($l['debit']??0)):((float)($l['debit']??0)-(float)($l['credit']??0));}}return round(max(0,$n),2);}

try{
 $user=tt_require_login();$policy=ls_json(TT_LS_POLICY_FILE);
 if($_SERVER['REQUEST_METHOD']==='GET'){
  if(!tt_user_can_open_module($user,'Accounts'))ls_respond(['ok'=>false,'error'=>'Accounts permission required.'],403);$asOf=ls_date((string)($_GET['asOf']??(new DateTimeImmutable('now',new DateTimeZone('Asia/Karachi')))->format('Y-m-d')));$s=ls_read();$summary=ls_summary($s,$asOf,$policy);$pending=array_values(array_filter((array)$s['localSalesCandidates'],static fn($x)=>is_array($x)&&($x['status']??'')==='Pending Accounts Approval'));usort($pending,static fn($a,$b)=>strcmp((string)($b['createdAt']??''),(string)($a['createdAt']??'')));ls_respond(['ok'=>true,'summary'=>$summary,'pending'=>$pending,'policy'=>$policy,'serverNow'=>gmdate('c')]);
 }
 if($_SERVER['REQUEST_METHOD']!=='POST')ls_respond(['ok'=>false,'error'=>'Method not allowed.'],405);$body=json_decode(file_get_contents('php://input')?:'',true);if(!is_array($body)||!tt_verify_csrf((string)($body['csrf']??'')))ls_respond(['ok'=>false,'error'=>'Your session expired. Refresh and try again.'],419);$action=(string)($body['action']??'');
 if($action==='preflight'){
  if(!ls_module_write($user,'Mill')&&!ls_module_write($user,'Accounts'))ls_respond(['ok'=>false,'error'=>'Mill or Accounts permission required.'],403);$date=ls_date((string)($body['saleDate']??''));$amount=ls_positive($body['amount']??0,'Local sale amount');$summary=ls_summary(ls_read(),$date,$policy,$amount);$projected=$summary['projectedRatioPercent'];$criticalAlarm=ls_is_critical($projected,(float)$summary['criticalPercent']);$warn=$criticalAlarm||($projected!==null&&$projected>=(float)$summary['warningPercent']);$message=$criticalAlarm?'Critical Local Sales alarm. The sale can still be recorded, but Accounts must review it.':($warn?'Local Sales are at or above the warning level.':'Local Sales are within the current monitoring range.');ls_respond(['ok'=>true,'blocked'=>false,'warning'=>$warn,'critical'=>$criticalAlarm,'summary'=>$summary,'message'=>$message]);
 }
 if($action==='queue_candidate'){
  if(!ls_module_write($user,'Mill'))ls_respond(['ok'=>false,'error'=>'Mill Create or Edit permission required.'],403);$entity=ls_valid_entity((string)($body['entity']??''));$date=ls_date((string)($body['saleDate']??''));$amount=ls_positive($body['amount']??0,'Local sale amount');$sourceKey=trim((string)($body['sourceKey']??''));if($sourceKey===''||strlen($sourceKey)>180)ls_respond(['ok'=>false,'error'=>'Local Sale reference is required.'],422);$product=trim((string)($body['product']??''));if($product==='')ls_respond(['ok'=>false,'error'=>'Product is required.'],422);$party=trim((string)($body['party']??''));$soda=trim((string)($body['soda']??''));$kg=round((float)($body['loadedKg']??0),3);$rate=round((float)($body['ratePerKg']??0),4);$record=['id'=>'','entity'=>$entity,'sourceKey'=>$sourceKey,'soda'=>$soda,'saleDate'=>$date,'party'=>$party,'product'=>$product,'loadedKg'=>$kg,'ratePerKg'=>$rate,'amount'=>$amount,'truck'=>trim((string)($body['truck']??'')),'gatePass'=>trim((string)($body['gatePass']??'')),'stockLocation'=>trim((string)($body['stockLocation']??'')),'stockReference'=>trim((string)($body['stockReference']??'')),'status'=>'Pending Accounts Approval','journalId'=>null,'costStatus'=>'Stock quantity moved in Mill; Accounts cost is waiting for the approved costing rule.','createdAt'=>gmdate('c'),'createdBy'=>(string)($user['full_name']??$user['username']??'Mill Staff')];
  tt_ensure_data_dir();$h=fopen(TT_LS_ACCOUNTS_FILE,'c+');if($h===false||!flock($h,LOCK_EX))throw new RuntimeException('Accounts storage unavailable.');try{rewind($h);$raw=stream_get_contents($h);$s=$raw?json_decode($raw,true):null;if(!is_array($s))$s=ls_default_store();$s=array_replace_recursive(ls_default_store(),$s);$id=$entity.'|LOCAL_SALE|'.$sourceKey;$record['id']=$id;$old=$s['localSalesCandidates'][$id]??null;if(!is_array($old))$s['localSalesCandidates'][$id]=$record;elseif(!empty($old['journalId']))ls_respond(['ok'=>false,'error'=>'This Gate Pass sale is already approved in Accounts and cannot be changed from Mill.','existing'=>$old],409);else{$record['createdAt']=$old['createdAt']??$record['createdAt'];$record['createdBy']=$old['createdBy']??$record['createdBy'];$s['localSalesCandidates'][$id]=$record;}$s['revision']=(int)($s['revision']??0)+1;rewind($h);ftruncate($h,0);fwrite($h,json_encode($s,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($h);$candidate=$s['localSalesCandidates'][$id];}finally{flock($h,LOCK_UN);fclose($h);}ls_respond(['ok'=>true,'candidate'=>$candidate]);
 }
 if($action==='approve_candidate'||$action==='reject_candidate'){
  if(!ls_module_write($user,'Accounts'))ls_respond(['ok'=>false,'error'=>'Accounts approval permission required.'],403);$id=trim((string)($body['candidateId']??''));if($id==='')ls_respond(['ok'=>false,'error'=>'Select a Local Sale.'],422);
  tt_ensure_data_dir();$h=fopen(TT_LS_ACCOUNTS_FILE,'c+');if($h===false||!flock($h,LOCK_EX))throw new RuntimeException('Accounts storage unavailable.');try{rewind($h);$raw=stream_get_contents($h);$store=$raw?json_decode($raw,true):null;if(!is_array($store))$store=ls_default_store();$store=array_replace_recursive(ls_default_store(),$store);$c=$store['localSalesCandidates'][$id]??null;if(!is_array($c))ls_respond(['ok'=>false,'error'=>'Local Sale was not found.'],404);if(($c['status']??'')!=='Pending Accounts Approval')ls_respond(['ok'=>false,'error'=>'This Local Sale is no longer waiting for approval.'],409);$advanceJournal=null;
   if($action==='reject_candidate'){$store['localSalesCandidates'][$id]['status']='Returned / Rejected by Accounts';$store['localSalesCandidates'][$id]['reviewNote']=trim((string)($body['note']??''));$store['localSalesCandidates'][$id]['reviewedAt']=gmdate('c');$store['localSalesCandidates'][$id]['reviewedBy']=(string)($user['full_name']??$user['username']??'Accounts');$journal=null;$summary=null;}
   else{
    $before=ls_summary($store,(string)$c['saleDate'],$policy,0);$summary=ls_summary($store,(string)$c['saleDate'],$policy,(float)$c['amount']);$critical=(float)$summary['criticalPercent'];$isCritical=ls_is_critical($summary['projectedRatioPercent'],$critical);$exceptionNote=trim((string)($body['exceptionNote']??''));if($isCritical&&$exceptionNote==='')ls_respond(['ok'=>false,'error'=>'Please enter a reason because this sale is at or above the critical Local Sales warning. The sale itself is not blocked.','summary'=>$summary],422);
    $names=ls_account_names();$amount=(float)$c['amount'];$soda=(string)($c['soda']??'');$party=(string)($c['party']??'');$product=(string)($c['product']??'');$lineMeta=['soda'=>$soda,'party'=>$party,'product'=>$product,'truck'=>$c['truck']??'','gatePass'=>$c['gatePass']??''];$lines=[ls_line('1220',$amount,0,$names,$lineMeta),ls_line('4200',0,$amount,$names,$lineMeta)];$jid=ls_next_id((array)$store['journals'],'AUTO');$meta=array_merge($lineMeta,['localSaleCandidateId'=>$id,'loadedKg'=>$c['loadedKg']??0,'ratePerKg'=>$c['ratePerKg']??0,'stockLocation'=>$c['stockLocation']??'','stockReference'=>$c['stockReference']??'','costStatus'=>$c['costStatus']??'Cost posting pending','localSalesControlBefore'=>$before,'localSalesControlProjected'=>$summary,'criticalException'=>$isCritical,'exceptionNote'=>$exceptionNote]);$store['journals'][$jid]=['id'=>$jid,'entity'=>$c['entity'],'date'=>$c['saleDate'],'sourceType'=>'LOCAL_SALE_RECOGNIZED','reference'=>$c['gatePass']?:($soda?:$c['sourceKey']),'narration'=>'Local Sale — '.$product.' — '.$party,'lines'=>$lines,'totalDebit'=>$amount,'totalCredit'=>$amount,'status'=>'Posted','meta'=>$meta,'createdAt'=>gmdate('c'),'createdBy'=>(string)($user['full_name']??$user['username']??'Accounts'),'userId'=>(int)($user['id']??0),'reversalOf'=>null];
    $availableAdvance=ls_balance($store,(string)$c['entity'],'2510',$soda,true);$openAr=ls_balance($store,(string)$c['entity'],'1220',$soda,false);$apply=min($availableAdvance,$openAr);if($apply>.005){$ajid=ls_next_id((array)$store['journals'],'AUTO');$alines=[ls_line('2510',$apply,0,$names,['soda'=>$soda,'party'=>$party,'advanceApplied'=>true]),ls_line('1220',0,$apply,$names,['soda'=>$soda,'party'=>$party,'advanceApplied'=>true])];$store['journals'][$ajid]=['id'=>$ajid,'entity'=>$c['entity'],'date'=>$c['saleDate'],'sourceType'=>'LOCAL_SALE_ADVANCE_APPLIED','reference'=>$soda,'narration'=>'Apply Local Sale advance — '.$soda.' — '.$party,'lines'=>$alines,'totalDebit'=>$apply,'totalCredit'=>$apply,'status'=>'Posted','meta'=>['soda'=>$soda,'party'=>$party,'saleCandidateId'=>$id,'advanceApplied'=>$apply],'createdAt'=>gmdate('c'),'createdBy'=>(string)($user['full_name']??$user['username']??'Accounts'),'userId'=>(int)($user['id']??0),'reversalOf'=>null];$advanceJournal=$store['journals'][$ajid];}
    $store['localSalesCandidates'][$id]['status']=$isCritical?'Approved / Posted — Critical Control Exception':'Approved / Posted';$store['localSalesCandidates'][$id]['journalId']=$jid;$store['localSalesCandidates'][$id]['advanceApplied']=round($apply,2);$store['localSalesCandidates'][$id]['reviewNote']=$exceptionNote;$store['localSalesCandidates'][$id]['reviewedAt']=gmdate('c');$store['localSalesCandidates'][$id]['reviewedBy']=(string)($user['full_name']??$user['username']??'Accounts');if($isCritical){$alertId='LSCTRL-'.gmdate('YmdHis').'-'.substr(hash('sha256',$id),0,6);$store['alerts'][$alertId]=['id'=>$alertId,'type'=>'LOCAL_SALES_CRITICAL','entity'=>$c['entity'],'date'=>$c['saleDate'],'reference'=>$c['gatePass']?:($soda?:$c['sourceKey']),'message'=>'Local Sales ratio is at or above the critical control after an Accounts-approved posting.','ratioPercent'=>$summary['projectedRatioPercent'],'criticalPercent'=>$critical,'exceptionNote'=>$exceptionNote,'status'=>'Open','createdAt'=>gmdate('c'),'createdBy'=>(string)($user['full_name']??$user['username']??'Accounts'),'audience'=>['Accounts','Director','Owner']];}$journal=$store['journals'][$jid];
   }
   $store['revision']=(int)($store['revision']??0)+1;rewind($h);ftruncate($h,0);fwrite($h,json_encode($store,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($h);
  }finally{flock($h,LOCK_UN);fclose($h);}ls_respond(['ok'=>true,'candidate'=>$store['localSalesCandidates'][$id],'journal'=>$journal,'advanceJournal'=>$advanceJournal,'summary'=>$summary,'revision'=>(int)$store['revision']]);
 }
 ls_respond(['ok'=>false,'error'=>'Unknown Local Sales action.'],422);
}catch(Throwable $e){ls_respond(['ok'=>false,'error'=>'The Local Sales action could not be completed.'],500);}

