<?php
declare(strict_types=1);
require dirname(__DIR__) . '/auth_store.php';
header('Content-Type: application/json; charset=UTF-8');
header('Cache-Control: no-store, no-cache, must-revalidate');
const TT_LSP_FILE=TT_DATA_DIR.'/accounts.json';
const TT_LSP_MASTER=__DIR__.'/../accounts/accounting_master_v1.json';
function lsp_out(array $d,int $s=200):never{http_response_code($s);echo json_encode($d,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function lsp_can_write(array $u,string $m):bool{if(($u['role']??'')==='Super Admin')return true;$p=$u['permissions'][$m]??null;if($p==='all')return true;if(!is_array($p))return false;if(in_array('Create',$p,true)||in_array('Edit',$p,true)||in_array('Approve',$p,true))return true;foreach($p as $a)if(is_array($a)&&(in_array('Create',$a,true)||in_array('Edit',$a,true)||in_array('Approve',$a,true)))return true;return false;}
function lsp_def():array{return ['revision'=>0,'journals'=>[],'bankAccountSettings'=>[],'localSalesCandidates'=>[],'localSalesPaymentCandidates'=>[]];}
function lsp_read():array{tt_ensure_data_dir();if(!is_file(TT_LSP_FILE))return lsp_def();$h=fopen(TT_LSP_FILE,'r');if($h===false||!flock($h,LOCK_SH))throw new RuntimeException('Accounts storage unavailable.');try{$raw=stream_get_contents($h);}finally{flock($h,LOCK_UN);fclose($h);}$v=$raw?json_decode($raw,true):null;return is_array($v)?array_replace_recursive(lsp_def(),$v):lsp_def();}
function lsp_names():array{$raw=file_get_contents(TT_LSP_MASTER);$m=$raw?json_decode($raw,true):null;if(!is_array($m))throw new RuntimeException('Accounting master unavailable.');$o=[];foreach((array)($m['chart']??[]) as $a)if(is_array($a)&&isset($a['code']))$o[(string)$a['code']]=(string)($a['name']??$a['code']);return $o;}
function lsp_line(string $a,float $dr,float $cr,array $names,array $extra=[]):array{if(!isset($names[$a]))lsp_out(['ok'=>false,'error'=>'Approved account '.$a.' is unavailable.'],422);return array_merge(['account'=>$a,'accountName'=>$names[$a],'debit'=>round($dr,2),'credit'=>round($cr,2)],$extra);}
function lsp_entity(string $v):string{$v=strtoupper(trim($v));if(!in_array($v,['TTI','BRM'],true))lsp_out(['ok'=>false,'error'=>'Selling Company must be TTI or BRM.'],422);return $v;}
function lsp_date(string $v):string{if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$v))lsp_out(['ok'=>false,'error'=>'Valid payment date required.'],422);return $v;}
function lsp_next(array $items,string $p):string{$n=count($items)+1;do{$id=$p.'-'.gmdate('Y').'-'.str_pad((string)$n,6,'0',STR_PAD_LEFT);$n++;}while(isset($items[$id]));return $id;}
function lsp_entity_from_linked(string $v):string{$u=strtoupper($v);if(str_contains($u,'BRM')||str_contains($u,'BUKSH RICE'))return 'BRM';if(str_contains($u,'TTI')||str_contains($u,'TRANSTRADE INTERNATIONAL'))return 'TTI';return '';}
function lsp_banks(array $store):array{$masters=tt_list_masters();$o=[];foreach((array)($masters['banks']??[]) as $r){if(!is_array($r))continue;$v=array_values((array)($r['values']??[]));while(count($v)<14)$v[]='';$id=(string)($r['id']??'');$entity=lsp_entity_from_linked((string)$v[1]);if(!in_array($entity,['TTI','BRM'],true)||trim((string)$v[0])!=='Company Account'||strtoupper(trim((string)$v[7]))!=='PKR')continue;$s=is_array($store['bankAccountSettings'][$id]??null)?$store['bankAccountSettings'][$id]:[];if(!tt_bank_can_transact($id))continue;$raw=preg_replace('/\W+/','',trim((string)($v[8]?:$v[9])))??'';$tail=$raw!==''?substr($raw,-5):'';$o[$id]=['id'=>$id,'entity'=>$entity,'bankName'=>(string)$v[4],'accountTitle'=>(string)$v[3],'display'=>trim((string)$v[4]).($tail!==''?' — •••••'.$tail:'')];}return $o;}
function lsp_line_soda(array $j,array $l):string{$m=is_array($j['meta']??null)?$j['meta']:[];return trim((string)($l['soda']??$m['soda']??$m['targetSoda']??$m['advanceSoda']??''));}
function lsp_ar(array $store,string $entity,string $soda):float{$n=0;foreach((array)($store['journals']??[]) as $j){if(!is_array($j)||($j['status']??'')!=='Posted'||($j['entity']??'')!==$entity)continue;foreach((array)($j['lines']??[]) as $l)if(is_array($l)&&(string)($l['account']??'')==='1220'&&lsp_line_soda($j,$l)===$soda)$n+=(float)($l['debit']??0)-(float)($l['credit']??0);}return round(max(0,$n),2);}
function lsp_advance(array $store,string $entity,string $soda):float{$n=0;foreach((array)($store['journals']??[]) as $j){if(!is_array($j)||($j['status']??'')!=='Posted'||($j['entity']??'')!==$entity)continue;foreach((array)($j['lines']??[]) as $l)if(is_array($l)&&(string)($l['account']??'')==='2510'&&lsp_line_soda($j,$l)===$soda)$n+=(float)($l['credit']??0)-(float)($l['debit']??0);}return round(max(0,$n),2);}
function lsp_payload(array $s):array{$pending=[];foreach((array)($s['localSalesPaymentCandidates']??[]) as $x)if(is_array($x)&&empty($x['journalId'])&&!in_array((string)($x['status']??''),['Returned to Mill','Cancelled'],true)){$x['openReceivable']=lsp_ar($s,(string)$x['entity'],(string)$x['soda']);$x['advanceOnSoda']=lsp_advance($s,(string)$x['entity'],(string)$x['soda']);$pending[]=$x;}usort($pending,static fn($a,$b)=>strcmp((string)($b['paymentDate']??''),(string)($a['paymentDate']??''))?:strcmp((string)($b['createdAt']??''),(string)($a['createdAt']??'')));$banks=array_values(lsp_banks($s));$statuses=[];foreach((array)($s['localSalesPaymentCandidates']??[]) as $x)if(is_array($x))$statuses[]=['sourceKey'=>(string)($x['sourceKey']??''),'soda'=>(string)($x['soda']??''),'status'=>(string)($x['status']??''),'journalId'=>(string)($x['journalId']??''),'note'=>(string)($x['reviewNote']??'')];$saleStatuses=[];foreach((array)($s['localSalesCandidates']??[]) as $x)if(is_array($x))$saleStatuses[]=['sourceKey'=>(string)($x['sourceKey']??''),'soda'=>(string)($x['soda']??''),'gatePass'=>(string)($x['gatePass']??''),'status'=>(string)($x['status']??''),'journalId'=>(string)($x['journalId']??'')];return ['ok'=>true,'pending'=>$pending,'banks'=>$banks,'paymentStatuses'=>$statuses,'saleStatuses'=>$saleStatuses,'serverNow'=>gmdate('c')];}
try{
 $u=tt_require_login();$canAccounts=tt_user_can_open_module($u,'Accounts');$canMill=tt_user_can_open_module($u,'Mill');if(!$canAccounts&&!$canMill)lsp_out(['ok'=>false,'error'=>'You do not have access to Local Sales payments.'],403);
 if($_SERVER['REQUEST_METHOD']==='GET')lsp_out(lsp_payload(lsp_read()));
 if($_SERVER['REQUEST_METHOD']!=='POST')lsp_out(['ok'=>false,'error'=>'Method not allowed.'],405);
 $b=json_decode(file_get_contents('php://input')?:'{}',true);if(!is_array($b)||!tt_verify_csrf((string)($b['csrf']??'')))lsp_out(['ok'=>false,'error'=>'Your session expired. Refresh and try again.'],419);$action=(string)($b['action']??'');
 if($action==='queue_payment'){
  if(!lsp_can_write($u,'Mill')&&!lsp_can_write($u,'Accounts'))lsp_out(['ok'=>false,'error'=>'Mill or Accounts entry permission required.'],403);$entity=lsp_entity((string)($b['entity']??''));$sourceKey=trim((string)($b['sourceKey']??''));$soda=trim((string)($b['soda']??''));$party=trim((string)($b['party']??''));$product=trim((string)($b['product']??''));$date=lsp_date((string)($b['paymentDate']??''));$amount=round((float)($b['amount']??0),2);$type=trim((string)($b['paymentType']??''));if($sourceKey===''||$soda===''||$party===''||$amount<=0)lsp_out(['ok'=>false,'error'=>'Local Soda, party and payment amount are required.'],422);if(!in_array($type,['Cash','Transtrade Bank','Third-Party Account','Other Adjustment'],true))lsp_out(['ok'=>false,'error'=>'Select a valid Local Sale payment type.'],422);$id=$entity.'|LOCAL_PAYMENT|'.$sourceKey;$rec=['id'=>$id,'entity'=>$entity,'sourceKey'=>$sourceKey,'soda'=>$soda,'party'=>$party,'product'=>$product,'paymentDate'=>$date,'amount'=>$amount,'paymentType'=>$type,'reference'=>trim((string)($b['reference']??'')),'bankAccountId'=>trim((string)($b['bankAccountId']??'')),'sourceSoda'=>trim((string)($b['sourceSoda']??'')),'sourceProduct'=>trim((string)($b['sourceProduct']??'')),'sourceParty'=>trim((string)($b['sourceParty']??'')),'status'=>$type==='Third-Party Account'?'Needs Settlement Details':'Pending Accounts Approval','journalId'=>null,'reviewNote'=>'','createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??$u['username']??'Mill Staff')];tt_ensure_data_dir();$h=fopen(TT_LSP_FILE,'c+');if($h===false||!flock($h,LOCK_EX))throw new RuntimeException('Accounts storage unavailable.');try{rewind($h);$raw=stream_get_contents($h);$s=$raw?json_decode($raw,true):null;if(!is_array($s))$s=lsp_def();$s=array_replace_recursive(lsp_def(),$s);$old=$s['localSalesPaymentCandidates'][$id]??null;if(is_array($old)&&!empty($old['journalId']))lsp_out(['ok'=>false,'error'=>'This payment has already been approved in Accounts and cannot be changed from Mill.','existing'=>$old],409);if(is_array($old))$rec['createdAt']=$old['createdAt']??$rec['createdAt'];$s['localSalesPaymentCandidates'][$id]=$rec;$s['revision']=(int)($s['revision']??0)+1;rewind($h);ftruncate($h,0);fwrite($h,json_encode($s,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($h);}finally{flock($h,LOCK_UN);fclose($h);}lsp_out(lsp_payload($s)+['payment'=>$rec]);
 }
 if(!lsp_can_write($u,'Accounts'))lsp_out(['ok'=>false,'error'=>'Accounts approval permission required.'],403);
 $id=trim((string)($b['paymentId']??''));if($id==='')lsp_out(['ok'=>false,'error'=>'Select a payment.'],422);
 tt_ensure_data_dir();$h=fopen(TT_LSP_FILE,'c+');if($h===false||!flock($h,LOCK_EX))throw new RuntimeException('Accounts storage unavailable.');try{rewind($h);$raw=stream_get_contents($h);$s=$raw?json_decode($raw,true):null;if(!is_array($s))$s=lsp_def();$s=array_replace_recursive(lsp_def(),$s);$p=$s['localSalesPaymentCandidates'][$id]??null;if(!is_array($p))lsp_out(['ok'=>false,'error'=>'Payment was not found.'],404);if(!empty($p['journalId']))lsp_out(['ok'=>false,'error'=>'This payment is already approved.'],409);
  if($action==='reject_payment'){$p['status']='Returned to Mill';$p['reviewNote']=trim((string)($b['note']??''));$p['reviewedAt']=gmdate('c');$p['reviewedBy']=(string)($u['full_name']??$u['username']??'Accounts');$s['localSalesPaymentCandidates'][$id]=$p;$s['revision']=(int)($s['revision']??0)+1;rewind($h);ftruncate($h,0);fwrite($h,json_encode($s,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($h);lsp_out(lsp_payload($s)+['payment'=>$p]);}
  if($action!=='approve_payment')lsp_out(['ok'=>false,'error'=>'Unknown Local Sales payment action.'],422);$type=(string)$p['paymentType'];if($type==='Third-Party Account'){lsp_out(['ok'=>false,'error'=>'This is a third-party payment. Accounts must first confirm how the money was actually settled. No bank or cash entry has been made.'],422);} $entity=(string)$p['entity'];$soda=(string)$p['soda'];$amount=(float)$p['amount'];$party=(string)$p['party'];$date=(string)$p['paymentDate'];$names=lsp_names();$lines=[];$meta=['localSalesPaymentId'=>$id,'soda'=>$soda,'party'=>$party,'product'=>$p['product']??'','paymentType'=>$type,'sourceKey'=>$p['sourceKey']??''];
  if($type==='Other Adjustment'){$src=trim((string)($p['sourceSoda']??''));if($src===''||$src===$soda)lsp_out(['ok'=>false,'error'=>'Select a different Local Soda with available excess payment.'],422);$available=lsp_advance($s,$entity,$src);if($amount>$available+.01)lsp_out(['ok'=>false,'error'=>'The selected source Soda no longer has enough approved excess payment. Available: Rs '.number_format($available,2).'.'],422);$open=lsp_ar($s,$entity,$soda);$toAr=min($amount,$open);$toAdvance=round($amount-$toAr,2);$lines[]=lsp_line('2510',$amount,0,$names,['soda'=>$src,'party'=>$p['sourceParty']??'','advanceMove'=>'From']);if($toAr>.005)$lines[]=lsp_line('1220',0,$toAr,$names,['soda'=>$soda,'party'=>$party]);if($toAdvance>.005)$lines[]=lsp_line('2510',0,$toAdvance,$names,['soda'=>$soda,'party'=>$party,'advanceMove'=>'To']);$meta['sourceSoda']=$src;$meta['receivableApplied']=$toAr;$meta['customerAdvance']=$toAdvance;
  }else{$open=lsp_ar($s,$entity,$soda);$toAr=min($amount,$open);$advance=round($amount-$toAr,2);if($type==='Transtrade Bank'){$bankId=trim((string)($b['bankAccountId']??$p['bankAccountId']??''));$banks=lsp_banks($s);$bank=$banks[$bankId]??null;if(!is_array($bank)||($bank['entity']??'')!==$entity)lsp_out(['ok'=>false,'error'=>'Select the correct active '.$entity.' PKR bank account.'],422);$lines[]=lsp_line('1110',$amount,0,$names,['bankAccountId'=>$bankId,'bankName'=>$bank['bankName'],'bankAccountTitle'=>$bank['accountTitle'],'currency'=>'PKR']);$meta['bankAccountId']=$bankId;$p['bankAccountId']=$bankId;}else{$lines[]=lsp_line('1120',$amount,0,$names,['cashAccount'=>'Company Cash','currency'=>'PKR']);}if($toAr>.005)$lines[]=lsp_line('1220',0,$toAr,$names,['soda'=>$soda,'party'=>$party]);if($advance>.005)$lines[]=lsp_line('2510',0,$advance,$names,['soda'=>$soda,'party'=>$party,'advanceSource'=>'Local Sale Payment']);$meta['receivableApplied']=$toAr;$meta['customerAdvance']=$advance;}
  $dr=round(array_sum(array_column($lines,'debit')),2);$cr=round(array_sum(array_column($lines,'credit')),2);if(abs($dr-$cr)>.01)throw new RuntimeException('Local payment journal did not balance.');$jid=lsp_next((array)$s['journals'],'AUTO');$s['journals'][$jid]=['id'=>$jid,'entity'=>$entity,'date'=>$date,'sourceType'=>'LOCAL_SALE_PAYMENT_APPROVED','reference'=>(string)($p['reference']?:$soda),'narration'=>'Local Sale payment approved — '.$soda.' — '.$party,'lines'=>$lines,'totalDebit'=>$dr,'totalCredit'=>$cr,'status'=>'Posted','meta'=>$meta,'createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??$u['username']??'Accounts'),'userId'=>(int)($u['id']??0),'reversalOf'=>null];$p['status']='Accounts Approved / Posted';$p['journalId']=$jid;$p['reviewNote']=trim((string)($b['note']??''));$p['reviewedAt']=gmdate('c');$p['reviewedBy']=(string)($u['full_name']??$u['username']??'Accounts');$s['localSalesPaymentCandidates'][$id]=$p;$s['revision']=(int)($s['revision']??0)+1;rewind($h);ftruncate($h,0);fwrite($h,json_encode($s,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($h);
 }finally{flock($h,LOCK_UN);fclose($h);}lsp_out(lsp_payload($s)+['payment'=>$p,'journal'=>$s['journals'][$jid]??null,'revision'=>$s['revision']]);
}catch(Throwable $e){lsp_out(['ok'=>false,'error'=>'The Local Sales payment could not be completed.'],500);}

