<?php
declare(strict_types=1);
require dirname(__DIR__) . '/auth_store.php';
header('Content-Type: application/json; charset=UTF-8');
header('Cache-Control: no-store, no-cache, must-revalidate');
const TT_MCA_FILE=TT_DATA_DIR.'/accounts.json';
function mca_out(array $d,int $s=200):never{http_response_code($s);echo json_encode($d,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function mca_can_write(array $u):bool{if(($u['role']??'')==='Super Admin')return true;$p=$u['permissions']['Accounts']??null;if($p==='all')return true;if(!is_array($p))return false;if(in_array('Create',$p,true)||in_array('Edit',$p,true)||in_array('Approve',$p,true))return true;foreach($p as $a)if(is_array($a)&&(in_array('Create',$a,true)||in_array('Edit',$a,true)||in_array('Approve',$a,true)))return true;return false;}
function mca_def():array{return ['revision'=>0,'localSalesCandidates'=>[],'exportCandidates'=>[],'localSalesCostRates'=>[],'inventoryCostRates'=>[],'managementCostingSheets'=>[]];}
function mca_norm(string $v):string{$v=preg_replace('/[^A-Z0-9]+/i',' ',trim($v))??trim($v);return strtoupper(trim(preg_replace('/\s+/',' ',$v)??$v));}
function mca_variety(string $v):string{$u=mca_norm($v);if(str_contains($u,'IRRI 6'))$b='IRRI-6';elseif(str_contains($u,'1121'))$b='1121';elseif(str_contains($u,'PK 386'))$b='PK-386';elseif(str_contains($u,'SUPER KERNEL'))$b='SUPER KERNEL';elseif(str_contains($u,'D 98'))$b='D-98';elseif(preg_match('/(^| )C 9( |$)/',$u))$b='C-9';else$b='';if($b!==''&&(str_contains($u,'PARBOIL')||str_contains($u,'SELLA')))$b.=' PARBOIL';return $b;}
function mca_product(string $v):string{$u=mca_norm($v);if(str_starts_with($u,'B2')||str_contains($u,'B2 SORTEX')||str_contains($u,'BROKEN B2'))return 'B2';if($u==='CSR'||str_starts_with($u,'CSR '))return 'CSR';if($u==='POWDER'||str_contains($u,' POWDER'))return 'POWDER';if($u==='PADDY'||str_contains($u,' PADDY'))return 'PADDY';if($u==='B3'||str_starts_with($u,'B3 '))return 'B3';if($u==='OTHER')return 'OTHER';return '';}
function mca_match_rate(array $r,string $product):bool{$pn=mca_norm($product);if(mca_norm((string)($r['product']??''))===$pn)return true;foreach((array)($r['aliases']??[]) as $a)if(mca_norm((string)$a)===$pn)return true;return false;}
function mca_final_rate(array $s,string $entity,string $product,string $date):?array{$best=null;foreach((array)$s['inventoryCostRates'] as $r){if(!is_array($r)||($r['status']??'Active')!=='Active'||($r['entity']??'')!==$entity||!mca_match_rate($r,$product))continue;$from=(string)($r['effectiveFrom']??'');if($from===''||$from>$date)continue;if($best===null||$from>(string)$best['effectiveFrom'])$best=$r;}if($best)return $best;foreach((array)$s['localSalesCostRates'] as $r){if(!is_array($r)||($r['status']??'Active')!=='Active'||($r['entity']??'')!==$entity||!mca_match_rate($r,$product))continue;if(in_array((string)($r['source']??''),['MANAGEMENT_COSTING_SHEET','ACTUAL_COST_ALIAS_PROXY'],true))continue;$from=(string)($r['effectiveFrom']??'');if($from===''||$from>$date)continue;if($best===null||$from>(string)$best['effectiveFrom'])$best=$r;}return $best;}
function mca_sheet_rate(array $sheets,string $entity,string $product,string $date):?array{$bp=mca_product($product);$vk=mca_variety($product);$genericReady=mca_norm($product)==='READY RICE';$best=null;foreach($sheets as $sh){if(!is_array($sh)||empty($sh['ready'])||($sh['entity']??'')!==$entity||($sh['date']??'')>$date)continue;$rate=null;$inv='';if($bp!==''){foreach((array)($sh['byProducts']??[]) as $x)if(is_array($x)&&mca_product((string)($x['product']??''))===$bp&&$x['rate']!==null){$rate=(float)$x['rate'];$inv='1330';break;}}else{if($vk!==''&&($sh['varietyKey']??'')!==$vk)continue;$rate=(float)($sh['estimatedReadyRiceCostPerKg']??0);$inv='1320';}if($rate===null||$rate<=0)continue;if($genericReady){$sameDate=array_filter($sheets,static fn($z)=>is_array($z)&&!empty($z['ready'])&&($z['entity']??'')===$entity&&($z['date']??'')===($sh['date']??''));if(count($sameDate)>1)continue;}if($best===null||($sh['date']??'')>($best['date']??''))$best=['sheet'=>$sh,'rate'=>$rate,'inventoryAccount'=>$inv,'date'=>$sh['date']];}return $best;}
function mca_rate_id(string $prefix,string $entity,string $product,string $sheetOrRate):string{return $prefix.'-'.substr(hash('sha256',$entity.'|'.mca_norm($product).'|'.$sheetOrRate),0,20);}
function mca_attach(array &$s,string $entity):array{$sheets=array_values((array)$s['managementCostingSheets']);$active=[];$attached=0;$actualProxy=0;$estimated=0;$attachOne=function(array &$c,string $product,string $date,float $kg)use(&$s,$sheets,$entity,&$active,&$attached,&$actualProxy,&$estimated){if($product===''||$date===''||$kg<=0)return;$est=mca_sheet_rate($sheets,$entity,$product,$date);if($est){$sh=$est['sheet'];$c['managementCostingSheetId']=$sh['id'];$c['managementEstimatedCostPerKg']=round((float)$est['rate'],6);$c['managementEstimatedCostAmount']=round($kg*(float)$est['rate'],2);$c['managementCostStatus']='Live Estimate';$attached++;}$final=mca_final_rate($s,$entity,$product,$date);if($final){if(isset($s['inventoryCostRates'][(string)($final['id']??'')])){$id=mca_rate_id('ACP',$entity,$product,(string)$final['id']);$active[$id]=true;$s['localSalesCostRates'][$id]=['id'=>$id,'entity'=>$entity,'product'=>$product,'effectiveFrom'=>(string)$final['effectiveFrom'],'costPerKg'=>(float)$final['costPerKg'],'inventoryAccount'=>(string)$final['inventoryAccount'],'status'=>'Active','source'=>'ACTUAL_COST_ALIAS_PROXY','actualRateId'=>(string)$final['id'],'estimateOnly'=>false,'notes'=>'Exact product alias for approved stock cost.','updatedAt'=>gmdate('c')];$actualProxy++;}return;}if($est)$estimated++;};foreach($s['localSalesCandidates'] as &$c){if(!is_array($c)||($c['entity']??'')!==$entity)continue;$attachOne($c,(string)($c['product']??''),(string)($c['saleDate']??''),(float)($c['loadedKg']??0));}unset($c);foreach($s['exportCandidates'] as &$c){if(!is_array($c)||($c['entity']??'')!==$entity||!in_array((string)($c['candidateType']??''),['CUSTOMER_EXPORT_SALE','TG_PAKISTAN_INTERCOMPANY'],true))continue;$attachOne($c,(string)($c['meta']['product']??''),(string)($c['recognitionDate']??$c['suggestedRecognitionDate']??''),(float)($c['meta']['actualQtyMT']??0)*1000);}unset($c);foreach($s['localSalesCostRates'] as $id=>&$r){if(!is_array($r)||!in_array((string)($r['source']??''),['MANAGEMENT_COSTING_SHEET','ACTUAL_COST_ALIAS_PROXY'],true))continue;if(($r['entity']??'')===$entity&&!isset($active[$id]))$r['status']='Superseded';}unset($r);return ['attached'=>$attached,'liveEstimates'=>$estimated,'actualAliasRates'=>$actualProxy];}
try{$u=tt_require_login();if(!tt_user_can_open_module($u,'Accounts'))mca_out(['ok'=>false,'error'=>'Accounts permission required.'],403);if($_SERVER['REQUEST_METHOD']!=='POST')mca_out(['ok'=>false,'error'=>'Method not allowed.'],405);if(!mca_can_write($u))mca_out(['ok'=>false,'error'=>'Accounts Create, Edit or Approve permission required.'],403);$b=json_decode(file_get_contents('php://input')?:'{}',true);if(!is_array($b)||!tt_verify_csrf((string)($b['csrf']??'')))mca_out(['ok'=>false,'error'=>'Your session expired. Refresh and try again.'],419);$entity=strtoupper(trim((string)($b['entity']??'')));if(!in_array($entity,['TTI','BRM'],true))mca_out(['ok'=>false,'error'=>'Company must be TTI or BRM.'],422);tt_ensure_data_dir();$h=fopen(TT_MCA_FILE,'c+');if($h===false||!flock($h,LOCK_EX))throw new RuntimeException('Accounts storage unavailable.');try{rewind($h);$raw=stream_get_contents($h);$s=$raw?json_decode($raw,true):null;if(!is_array($s))$s=mca_def();$s=array_replace_recursive(mca_def(),$s);$result=mca_attach($s,$entity);$s['revision']=(int)($s['revision']??0)+1;rewind($h);ftruncate($h,0);fwrite($h,json_encode($s,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($h);}finally{flock($h,LOCK_UN);fclose($h);}mca_out(['ok'=>true,'entity'=>$entity,'result'=>$result,'revision'=>$s['revision']]);}catch(Throwable $e){mca_out(['ok'=>false,'error'=>'Costing sheet could not be attached to sale costs.'],500);}

