<?php
declare(strict_types=1);

require dirname(__DIR__) . '/auth_store.php';
header('Content-Type: application/json; charset=UTF-8');
header('Cache-Control: no-store, no-cache, must-revalidate');

function mps_out(array $payload,int $status=200): never {http_response_code($status);echo json_encode($payload,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function mps_store():array{return ['revision'=>0,'purchaseSodas'=>[],'purchaseSodasV2'=>[],'purchaseSodaLiftings'=>[],'journals'=>[],'events'=>[],'commodityBills'=>[]];}
function mps_date(mixed $value):string{$v=trim((string)$value);$d=DateTimeImmutable::createFromFormat('!Y-m-d',$v);if(!$d||$d->format('Y-m-d')!==$v)throw new InvalidArgumentException('A valid lifting date is required.');return $v;}
function mps_num(mixed $value,string $label,bool $positive=true):float{if(!is_numeric($value))throw new InvalidArgumentException($label.' must be numeric.');$n=(float)$value;if(!is_finite($n)||($positive?$n<=0:$n<0))throw new InvalidArgumentException($label.' must be '.($positive?'greater than zero.':'zero or greater.'));return $n;}
function mps_id(array $rows,string $prefix):string{do{$id=$prefix.'-'.gmdate('YmdHis').'-'.strtoupper(bin2hex(random_bytes(3)));}while(isset($rows[$id]));return $id;}
function mps_sodas(array $s):array{$out=[];foreach(['purchaseSodas','purchaseSodasV2']as $c)foreach((array)($s[$c]??[])as$id=>$r){if(!is_array($r))continue;$key=(string)($r['id']??$id);if(!isset($out[$key]))$out[$key]=$r+['id'=>$key];}return $out;}
function mps_soda(array $s,string $id):?array{$all=mps_sodas($s);if(isset($all[$id]))return $all[$id];foreach($all as$r)if((string)($r['sodaNo']??'')===$id)return $r;return null;}
function mps_billed(array $s,string $sourceKey):string{foreach((array)($s['events']??[])as$e)if(is_array($e)&&(string)($e['sourceKey']??'')===$sourceKey&&!empty($e['billId']))return (string)$e['billId'];return '';}
function mps_can_handoff(array $user,string $entity):bool{return tt_user_can_access_entity($user,$entity,'Create')||tt_user_can_access_entity($user,$entity,'Edit')||tt_user_can_open_module($user,'Mill');}

try {
    $user=tt_require_login();
    $canMill=tt_user_can_open_module($user,'Mill');$canAccounts=tt_user_can_open_module($user,'Accounts');$canExports=tt_user_can_open_module($user,'Exports');
    if($_SERVER['REQUEST_METHOD']==='POST'&&!$canMill&&!$canAccounts)mps_out(['ok'=>false,'error'=>'Mill or Accounts permission required.'],403);
    if($_SERVER['REQUEST_METHOD']==='GET'&&!$canMill&&!$canAccounts&&!$canExports)mps_out(['ok'=>false,'error'=>'Mill, Accounts or Exports permission required.'],403);
    $file=TT_DATA_DIR.'/accounts.json';$store=mps_store();
    if($_SERVER['REQUEST_METHOD']==='POST'){
        $body=json_decode(file_get_contents('php://input')?:'',true);if(!is_array($body)||!tt_verify_csrf((string)($body['csrf']??'')))mps_out(['ok'=>false,'error'=>'Session expired. Refresh and try again.'],419);
        if((string)($body['action']??'')!=='sync_lifting')mps_out(['ok'=>false,'error'=>'Unknown action.'],422);
        $sourceSodaId=trim((string)($body['sourceSodaId']??''));$liftingId=trim((string)($body['liftingId']??''));if($sourceSodaId===''||$liftingId===''||strlen($liftingId)>180)mps_out(['ok'=>false,'error'=>'Stable Soda and lifting identities are required.'],422);
        tt_ensure_data_dir();$handle=fopen($file,'c+');if($handle===false||!flock($handle,LOCK_EX))throw new RuntimeException('store');
        try{
            rewind($handle);$raw=stream_get_contents($handle);$decoded=$raw?json_decode($raw,true):null;$store=is_array($decoded)?array_replace_recursive(mps_store(),$decoded):mps_store();
            $soda=mps_soda($store,$sourceSodaId);if(!is_array($soda)||(string)($soda['readyRoute']??'')!=='EX_MILL')throw new InvalidArgumentException('The linked Ex-Mill purchase Soda was not found.');
            $entity=strtoupper((string)($soda['entity']??''));if(!in_array($entity,['TTI','BRM'],true)||!mps_can_handoff($user,$entity))mps_out(['ok'=>false,'error'=>'You do not have permission to hand this lifting to Accounts.'],403);
            $claimed=strtoupper(trim((string)($body['entity']??'')));if($claimed!==''&&$claimed!==$entity)throw new InvalidArgumentException('The legal entity must come from the approved Soda.');
            $date=mps_date($body['date']??'');if(isset($body['qualityStatus'])&&strtoupper(trim((string)$body['qualityStatus']))!=='OK')throw new InvalidArgumentException('Only quality-approved loaded containers can create an Ex-Mill purchase liability.');$kg=round(mps_num($body['kg']??null,'Container weighbridge weight'),3);$bags=(int)round(mps_num($body['bags']??0,'Bags',false));$container=trim((string)($body['container']??''));if($container==='')throw new InvalidArgumentException('Container number is required before the Ex-Mill liability can be recognized.');
            $key=$entity.'|'.$sourceSodaId.'|'.$liftingId;$sourceKey='EXMILL|'.$sourceSodaId.'|'.$liftingId;$old=$store['purchaseSodaLiftings'][$key]??null;$billId=mps_billed($store,$sourceKey);
            foreach((array)$store['purchaseSodaLiftings']as$otherKey=>$other)if($otherKey!==$key&&is_array($other)&&empty($other['reversed'])&&strtoupper(trim((string)($other['container']??'')))===strtoupper($container))throw new InvalidArgumentException('This container is already linked to another Ex-Mill lifting.');
            $received=0.0;foreach((array)$store['purchaseSodaLiftings']as$otherKey=>$other)if($otherKey!==$key&&is_array($other)&&empty($other['reversed'])&&(string)($other['sourceSodaId']??'')===$sourceSodaId)$received+=(float)($other['kg']??0);
            $maximum=(float)($soda['qtyToKg']??0);if($maximum>0&&$received+$kg>$maximum*1.05+.001)throw new InvalidArgumentException('The lifting exceeds the contracted Ex-Mill quantity by more than 5%. Amend the Soda before posting additional weight.');
            $reversed=!empty($body['reversed']);if($billId!==''&&(!is_array($old)||round((float)($old['kg']??0),3)!==$kg||(string)($old['container']??'')!==$container||!empty($old['reversed'])!==$reversed))mps_out(['ok'=>false,'error'=>'This lifting is already included in supplier bill '.$billId.'. Amend or reverse the bill first.'],409);
            $rate=mps_num($soda['ratePerKg']??$soda['rate']??0,'Approved Soda rate');$amount=round($kg*$rate,2);$jid=(string)($old['journalId']??'');if($jid===''||!isset($store['journals'][$jid]))$jid=mps_id((array)$store['journals'],'AUTO');
            $record=['key'=>$key,'entity'=>$entity,'sourceSodaId'=>(string)($soda['id']??$sourceSodaId),'soda'=>(string)($soda['sodaNo']??''),'liftingId'=>$liftingId,'sourceKey'=>$sourceKey,'date'=>$date,'container'=>$container,'truck'=>trim((string)($body['truck']??'')),'kg'=>$kg,'bags'=>$bags,'shipmentId'=>trim((string)($body['shipmentId']??'')),'contractRef'=>trim((string)($body['contractRef']??'')),'lotRef'=>trim((string)($body['lotRef']??'')),'journalId'=>$jid,'provisionalAmount'=>$reversed?0:$amount,'reversed'=>$reversed,'updatedAt'=>gmdate('c'),'updatedBy'=>(string)($user['full_name']??$user['username']??'Mill')];
            if(is_array($old)){$history=is_array($old['versions']??null)?$old['versions']:[];$snapshot=$old;unset($snapshot['versions']);$history[]=['at'=>gmdate('c'),'before'=>$snapshot,'by'=>$record['updatedBy']];$record['versions']=$history;$record['createdAt']=$old['createdAt']??gmdate('c');$record['createdBy']=$old['createdBy']??$record['updatedBy'];}else{$record['createdAt']=gmdate('c');$record['createdBy']=$record['updatedBy'];}
            $meta=['sourceKey'=>$sourceKey,'sourceSodaId'=>$record['sourceSodaId'],'soda'=>$record['soda'],'pohanch'=>$container,'container'=>$container,'truck'=>$record['truck'],'payableWeightKg'=>$kg,'weighbridgeWeightKg'=>$kg,'bags'=>$bags,'ratePerKg'=>$rate,'grossRatePerKg'=>$rate,'katPaisaPerKg'=>0,'provisionalNetRatePerKg'=>$rate,'supplierId'=>(string)($soda['supplierId']??''),'supplier'=>(string)($soda['party']??''),'party'=>(string)($soda['party']??''),'broker'=>(string)($soda['broker']??''),'locationId'=>(string)($soda['locationId']??$soda['exMillId']??''),'locationName'=>(string)($soda['locationName']??$soda['location']??''),'shipmentId'=>$record['shipmentId'],'contractRef'=>$record['contractRef'],'lotRef'=>$record['lotRef'],'productIdentityCode'=>(string)($soda['productIdentityCode']??''),'commodity'=>(string)($soda['commodity']??'RICE'),'baseVariety'=>(string)($soda['baseVariety']??$soda['variety']??''),'variety'=>(string)($soda['displayName']??$soda['variety']??''),'riceType'=>(string)($soda['riceType']??''),'brokenGrade'=>(string)($soda['brokenGrade']??''),'displayName'=>(string)($soda['displayName']??''),'productStage'=>(string)($soda['productStage']??'READY'),'readyRoute'=>'EX_MILL'];
            $oldJournal=$store['journals'][$jid]??null;$journal=['id'=>$jid,'entity'=>$entity,'date'=>$date,'sourceType'=>'EX_MILL_PURCHASE_LIABILITY','reference'=>$container,'narration'=>($reversed?'Reversed — ':'').'Ex-Mill purchase liability — Soda '.$record['soda'],'lines'=>$reversed?[]:[['account'=>'1310','accountName'=>'Inventory / Purchases','debit'=>$amount,'credit'=>0],['account'=>'2210','accountName'=>'Goods Received Not Invoiced','debit'=>0,'credit'=>$amount]],'totalDebit'=>$reversed?0:$amount,'totalCredit'=>$reversed?0:$amount,'status'=>$reversed?'Reversed':'Posted / Bill Pending','meta'=>$meta,'createdAt'=>(string)($oldJournal['createdAt']??gmdate('c')),'createdBy'=>(string)($oldJournal['createdBy']??$record['createdBy']),'updatedAt'=>gmdate('c'),'updatedBy'=>$record['updatedBy'],'reversalOf'=>null];if(is_array($oldJournal)){$jhist=is_array($oldJournal['versions']??null)?$oldJournal['versions']:[];$copy=$oldJournal;unset($copy['versions']);$jhist[]=['at'=>gmdate('c'),'before'=>$copy];$journal['versions']=$jhist;}
            $eventId=$entity.'|COMMODITY_RECEIPT_ACCEPTED|'.$sourceKey;$event=['id'=>$eventId,'eventType'=>'COMMODITY_RECEIPT_ACCEPTED','entity'=>$entity,'sourceKey'=>$sourceKey,'journalId'=>$jid,'billId'=>$billId,'status'=>$reversed?'Reversed':'Accepted / Liability Posted','occurredAt'=>$date,'updatedAt'=>gmdate('c')];
            $store['purchaseSodaLiftings'][$key]=$record;$store['journals'][$jid]=$journal;$store['events'][$eventId]=$event;$store['revision']=(int)($store['revision']??0)+1;rewind($handle);ftruncate($handle,0);fwrite($handle,json_encode($store,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($handle);
        }finally{flock($handle,LOCK_UN);fclose($handle);}mps_out(['ok'=>true,'lifting'=>$record,'journal'=>$journal,'event'=>$event,'revision'=>(int)$store['revision']]);
    }
    if($_SERVER['REQUEST_METHOD']!=='GET')mps_out(['ok'=>false,'error'=>'Method not allowed.'],405);
    if(is_file($file)){$handle=fopen($file,'r');if($handle===false||!flock($handle,LOCK_SH))throw new RuntimeException('store');try{$raw=stream_get_contents($handle);}finally{flock($handle,LOCK_UN);fclose($handle);}$decoded=$raw?json_decode($raw,true):null;if(is_array($decoded))$store=array_replace_recursive($store,$decoded);}
    $seen=[];$rows=[];foreach(mps_sodas($store)as$id=>$row){$status=(string)($row['status']??$row['manualStatus']??'Open');if(in_array($status,['Cancelled','Completed','Short Closed','Manual Closed'],true))continue;$number=(string)($row['sodaNo']??'');$key=strtoupper((string)($row['entity']??'TTI')).'|'.$number;if($number===''||isset($seen[$key]))continue;$stage=tt_product_stage((string)($row['productStage']??''));if($stage===''){$identity=tt_product_identity((string)($row['commodity']??'RICE'),(string)($row['displayName']??$row['variety']??''));$stage=$identity['productStage'];$row=array_replace($identity,$row);}$route=strtoupper((string)($row['readyRoute']??''));if($stage==='READY'&&!in_array($route,['EX_MILL','DELIVER_TO_STOCK'],true))$route=(string)($row['movementRole']??'')==='LIFT_FROM'?'EX_MILL':'DELIVER_TO_STOCK';if($stage==='RAW')$route='DELIVER_TO_STOCK';$seen[$key]=true;$rows[]=['id'=>(string)($row['id']??$id),'entity'=>(string)($row['entity']??'TTI'),'sodaNo'=>$number,'sodaDate'=>(string)($row['sodaDate']??''),'purchaseProductId'=>(string)($row['purchaseProductId']??''),'commodity'=>(string)($row['commodity']??'RICE'),'baseVariety'=>(string)($row['baseVariety']??$row['variety']??''),'riceType'=>(string)($row['riceType']??''),'brokenGrade'=>(string)($row['brokenGrade']??''),'productStage'=>$stage,'displayName'=>(string)($row['displayName']??tt_product_display((string)($row['commodity']??'RICE'),(string)($row['baseVariety']??$row['variety']??''),$stage,(string)($row['riceType']??''))),'katProfile'=>$route==='EX_MILL'?'':(string)($row['katProfile']??''),'broker'=>(string)($row['broker']??''),'supplierId'=>(string)($row['supplierId']??''),'party'=>(string)($row['party']??''),'readyRoute'=>$route,'locationId'=>(string)($row['locationId']??$row['exMillId']??''),'locationName'=>(string)($row['locationName']??$row['location']??''),'locationType'=>(string)($row['locationType']??''),'locationAddress'=>(string)($row['locationAddress']??''),'qtyFromKg'=>(float)($row['qtyFromKg']??0),'qtyToKg'=>(float)($row['qtyToKg']??0),'expectedTrucks'=>(int)($row['expectedTrucks']??0),'ratePerKg'=>(float)($row['ratePerKg']??$row['rate']??0),'arrivalDueDate'=>(string)($row['arrivalDueDate']??''),'remarks'=>(string)($row['remarks']??''),'updatedAt'=>(string)($row['amendedAt']??$row['updatedAt']??$row['createdAt']??'')];}
    mps_out(['ok'=>true,'revision'=>(int)($store['revision']??0),'sodas'=>$rows]);
} catch(InvalidArgumentException $error){mps_out(['ok'=>false,'error'=>$error->getMessage()],422);} catch(Throwable $error){error_log('milling_purchase_sodas: '.$error->getMessage());mps_out(['ok'=>false,'error'=>'Purchase Sodas are temporarily unavailable.'],500);}
