<?php
declare(strict_types=1);
require dirname(__DIR__).'/auth_store.php';
header('Content-Type: application/json; charset=UTF-8');
header('Cache-Control: no-store, no-cache, must-revalidate');
const F=TT_DATA_DIR.'/accounts.json';
const M=__DIR__.'/../accounts/accounting_master_v1.json';
function o(array $d,int $s=200):never{http_response_code($s);echo json_encode($d,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function def():array{return ['revision'=>0,'journals'=>[],'bagPurchaseOrders'=>[],'nonWovenBagSupplierBills'=>[],'nonWovenBagSupplierPayments'=>[],'bankAccountSettings'=>[]];}
function rd():array{tt_ensure_data_dir();if(!is_file(F))return def();$h=fopen(F,'r');if(!$h||!flock($h,LOCK_SH))throw new RuntimeException();try{$r=stream_get_contents($h);}finally{flock($h,LOCK_UN);fclose($h);} $v=$r?json_decode($r,true):null;return is_array($v)?array_replace_recursive(def(),$v):def();}
function canw(array $u):bool{if(($u['role']??'')==='Super Admin')return true;$p=$u['permissions']['Accounts']??null;if($p==='all')return true;if(!is_array($p))return false;if(in_array('Create',$p,true)||in_array('Edit',$p,true)||in_array('Approve',$p,true))return true;foreach($p as $a)if(is_array($a)&&(in_array('Create',$a,true)||in_array('Edit',$a,true)||in_array('Approve',$a,true)))return true;return false;}
function cana(array $u):bool{return ($u['role']??'')==='Super Admin'||stripos((string)($u['role']??''),'director')!==false;}
function ent(string $v):string{$v=strtoupper(trim($v));if(!in_array($v,['TTI','BRM'],true))o(['ok'=>false,'error'=>'Non-Woven bag bills are available for TTI or BRM books.'],422);return $v;}
function dt(string $v,string $n='date'):string{if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$v))o(['ok'=>false,'error'=>'Valid '.$n.' required.'],422);return $v;}
function nw(string $t):bool{$u=strtoupper(trim($t));return str_contains($u,'NON')&&str_contains($u,'WOVEN');}
function names():array{$r=is_file(M)?file_get_contents(M):false;$m=$r?json_decode($r,true):null;if(!is_array($m))throw new RuntimeException();$x=[];foreach((array)$m['chart'] as $a)if(is_array($a)&&isset($a['code']))$x[(string)$a['code']]=(string)$a['name'];return $x;}
function ln(string $a,float $d,float $c,array $n,array $x=[]):array{if(!isset($n[$a]))o(['ok'=>false,'error'=>'Required account '.$a.' is not configured.'],422);return array_merge(['account'=>$a,'accountName'=>$n[$a],'debit'=>round($d,2),'credit'=>round($c,2)],$x);}
function nid(array $a,string $p):string{$n=count($a)+1;do{$id=$p.'-'.gmdate('Y').'-'.str_pad((string)$n,6,'0',STR_PAD_LEFT);$n++;}while(isset($a[$id]));return $id;}
function fl(array $po,string $lk):?array{foreach((array)($po['lines']??[]) as $l)if(is_array($l)&&($l['lineKey']??'')===$lk)return $l;return null;}
function billed(array $s,string $po,string $lk,string $ex=''):int{$n=0;foreach((array)$s['nonWovenBagSupplierBills'] as $id=>$b){if(!is_array($b)||$id===$ex||($b['status']??'')==='Cancelled')continue;if(($b['poNo']??'')===$po&&($b['lineKey']??'')===$lk)$n+=(int)$b['bags'];}return $n;}
function paid(array $s,string $id):float{$n=0;foreach((array)$s['nonWovenBagSupplierPayments'] as $p)if(is_array($p)&&($p['status']??'')!=='Cancelled'&&($p['billId']??'')===$id)$n+=(float)$p['amount'];return round($n,2);}
function bank(string $id,string $e,array $s):array{$ms=tt_list_masters();foreach((array)($ms['banks']??[]) as $r){if(!is_array($r)||(string)($r['id']??'')!==$id)continue;$v=array_values((array)($r['values']??[]));while(count($v)<14)$v[]='';$z=strtoupper((string)$v[1]);$be=str_contains($z,'BRM')||str_contains($z,'BUKSH RICE')?'BRM':(str_contains($z,'TTI')||str_contains($z,'TRANSTRADE INTERNATIONAL')?'TTI':'');if($be!==$e)o(['ok'=>false,'error'=>'Selected bank does not belong to these company books.'],422);if(trim((string)$v[0])!=='Company Account'||strtoupper(trim((string)$v[7]))!=='PKR')o(['ok'=>false,'error'=>'Select an approved PKR company bank account.'],422);$set=is_array($s['bankAccountSettings'][$id]??null)?$s['bankAccountSettings'][$id]:[];if(empty($set['active'])||empty($set['allowPayments']))o(['ok'=>false,'error'=>'Selected bank is not enabled for payments.'],422);return ['id'=>$id,'bankName'=>(string)$v[4],'accountTitle'=>(string)$v[3]];}o(['ok'=>false,'error'=>'Selected bank account was not found.'],404);}
function banks(array $s,string $e):array{$out=[];$ms=tt_list_masters();foreach((array)($ms['banks']??[]) as $r){if(!is_array($r))continue;$v=array_values((array)($r['values']??[]));while(count($v)<14)$v[]='';$z=strtoupper((string)$v[1]);$be=str_contains($z,'BRM')||str_contains($z,'BUKSH RICE')?'BRM':(str_contains($z,'TTI')||str_contains($z,'TRANSTRADE INTERNATIONAL')?'TTI':'');$id=(string)($r['id']??'');$set=is_array($s['bankAccountSettings'][$id]??null)?$s['bankAccountSettings'][$id]:[];if($be===$e&&trim((string)$v[0])==='Company Account'&&strtoupper(trim((string)$v[7]))==='PKR'&&!empty($set['active'])&&!empty($set['allowPayments']))$out[]=['id'=>$id,'display'=>trim((string)$v[4]).' — '.trim((string)$v[3])];}return $out;}
function postBill(array &$s,array $u,string $id):array{$b=$s['nonWovenBagSupplierBills'][$id]??null;if(!is_array($b))o(['ok'=>false,'error'=>'Non-Woven bag bill not found.'],404);if(!empty($b['journalId']))return $b;$po=$s['bagPurchaseOrders'][$b['poNo']]??null;$l=is_array($po)?fl($po,(string)$b['lineKey']):null;if(!$l)o(['ok'=>false,'error'=>'Linked PO packing line is unavailable.'],409);$before=billed($s,(string)$b['poNo'],(string)$b['lineKey'],$id);if($before+(int)$b['bags']>(int)$l['orderedQty'])o(['ok'=>false,'error'=>'Posting blocked: billed bags exceed the PO quantity for this packing size.'],409);if($before+(int)$b['bags']>(int)($l['receivedQty']??0))o(['ok'=>false,'error'=>'Posting held: supplier invoice quantity is above bags received at Mill.'],409);$pr=(float)($l['ratePerBag']??0);if($pr>0&&abs((float)$b['ratePerBag']-$pr)>.0001&&empty($b['rateExceptionApprovedAt']))o(['ok'=>false,'error'=>'Posting held: invoice rate differs from PO rate and needs Director approval.'],409);$n=names();$amt=(float)$b['totalAmount'];$j=[ln('1340',$amt,0,$n,['poNo'=>$b['poNo'],'lineKey'=>$b['lineKey'],'packingSize'=>$b['packingSize'],'bagType'=>$b['bagType'],'salesTaxRecoverable'=>false]),ln('2140',0,$amt,$n,['subledger'=>'Packaging Supplier Payable','supplier'=>$b['supplier']])];$jid=nid((array)$s['journals'],'AUTO');$s['journals'][$jid]=['id'=>$jid,'entity'=>$b['entity'],'date'=>$b['sellerInvoiceDate'],'sourceType'=>'NON_WOVEN_BAG_SUPPLIER_BILL','reference'=>$b['sellerInvoice'],'narration'=>'Non-Woven bag purchase — '.$b['supplier'].' — PO '.$b['poNo'].' — '.$b['packingSize'],'lines'=>$j,'totalDebit'=>$amt,'totalCredit'=>$amt,'status'=>'Posted','meta'=>['bagBillId'=>$id,'poNo'=>$b['poNo'],'lineKey'=>$b['lineKey'],'bags'=>$b['bags'],'bagType'=>$b['bagType'],'packingSize'=>$b['packingSize'],'brand'=>$b['brand'],'salesTaxRecoverable'=>false],'createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??$u['username']??'Accounts')];$s['nonWovenBagSupplierBills'][$id]['journalId']=$jid;$s['nonWovenBagSupplierBills'][$id]['status']='Posted';$s['nonWovenBagSupplierBills'][$id]['postedAt']=gmdate('c');return $s['nonWovenBagSupplierBills'][$id];}
function payload(array $s,string $e):array{$ls=[];foreach((array)$s['bagPurchaseOrders'] as $po){if(!is_array($po)||($po['entity']??'TTI')!==$e)continue;foreach((array)($po['lines']??[]) as $l)if(is_array($l)&&nw((string)($l['bagType']??'')))$ls[]=['po'=>$po]+$l;}$bs=[];$ps=[];foreach((array)$s['nonWovenBagSupplierBills'] as $id=>$b)if(is_array($b)&&($b['entity']??'')===$e){$p=paid($s,(string)$id);$x=$b;$x['paid']=$p;$x['outstanding']=max(0,round((float)$b['totalAmount']-$p,2));$bs[]=$x;if(($b['status']??'')==='Posted'&&$x['outstanding']>.005)$ps[]=$x;}return ['ok'=>true,'entity'=>$e,'lines'=>$ls,'bills'=>$bs,'payables'=>$ps,'banks'=>banks($s,$e),'serverNow'=>gmdate('c')];}
try{$u=tt_require_login();if(!tt_user_can_open_module($u,'Accounts'))o(['ok'=>false,'error'=>'Accounts permission required.'],403);$e=ent((string)($_GET['entity']??'TTI'));if($_SERVER['REQUEST_METHOD']==='GET')o(payload(rd(),$e));if($_SERVER['REQUEST_METHOD']!=='POST')o(['ok'=>false,'error'=>'Method not allowed.'],405);if(!canw($u))o(['ok'=>false,'error'=>'Accounts Create / Edit / Approve permission required.'],403);$b=json_decode(file_get_contents('php://input')?:'{}',true);if(!is_array($b)||!tt_verify_csrf((string)($b['csrf']??'')))o(['ok'=>false,'error'=>'Your session expired. Refresh and try again.'],419);$a=(string)($b['action']??'');$s=rd();$e=ent((string)($b['entity']??''));
if($a==='create_bill'){$poNo=trim((string)($b['poNo']??''));$lk=trim((string)($b['lineKey']??''));$po=$s['bagPurchaseOrders'][$poNo]??null;$l=is_array($po)?fl($po,$lk):null;if(!$l||($po['entity']??'')!==$e||!nw((string)($l['bagType']??'')))o(['ok'=>false,'error'=>'Select a valid Non-Woven PO packing line.'],422);$sup=trim((string)($b['supplier']??$po['supplier']??''));$inv=trim((string)($b['sellerInvoice']??''));$date=dt((string)($b['sellerInvoiceDate']??''),'seller invoice date');$qty=(int)round((float)($b['bags']??0));$rate=round((float)($b['ratePerBag']??0),4);if(!$sup||!$inv||$qty<=0||$rate<=0)o(['ok'=>false,'error'=>'Supplier, seller invoice, number of bags and rate are required.'],422);foreach((array)$s['nonWovenBagSupplierBills'] as $x)if(is_array($x)&&($x['entity']??'')===$e&&strcasecmp((string)$x['supplier'],$sup)===0&&strcasecmp((string)$x['sellerInvoice'],$inv)===0)o(['ok'=>false,'error'=>'This supplier invoice is already entered.'],409);$al=billed($s,$poNo,$lk);if($al+$qty>(int)$l['orderedQty'])o(['ok'=>false,'error'=>'Bill rejected: cumulative billed bags exceed the PO quantity.'],409);$amt=round($qty*$rate,2);$id=nid((array)$s['nonWovenBagSupplierBills'],'NWB');$st=$al+$qty>(int)($l['receivedQty']??0)?'Hold - Billed Above Received':(((float)($l['ratePerBag']??0)>0&&abs($rate-(float)$l['ratePerBag'])>.0001)?'Hold - Rate Approval Required':'Ready to Post');$s['nonWovenBagSupplierBills'][$id]=['id'=>$id,'entity'=>$e,'poNo'=>$poNo,'lineKey'=>$lk,'supplier'=>$sup,'sellerInvoice'=>$inv,'sellerInvoiceDate'=>$date,'bagType'=>$l['bagType'],'packingSize'=>$l['packingSize'],'brand'=>$l['brand'],'bags'=>$qty,'ratePerBag'=>$rate,'poRatePerBag'=>$l['ratePerBag'],'baseAmount'=>$amt,'gstRate'=>0,'gstAmount'=>0,'totalAmount'=>$amt,'salesTaxRecoverable'=>false,'status'=>$st,'journalId'=>null,'rateExceptionApprovedAt'=>null,'createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??$u['username']??'Accounts')];if($st==='Ready to Post')$s['nonWovenBagSupplierBills'][$id]=postBill($s,$u,$id);$res=$s['nonWovenBagSupplierBills'][$id];}
elseif($a==='try_post_bill'){$res=postBill($s,$u,trim((string)($b['billId']??'')));}
elseif($a==='approve_rate_exception'){if(!cana($u))o(['ok'=>false,'error'=>'Director approval is required.'],403);$id=trim((string)($b['billId']??''));if(!isset($s['nonWovenBagSupplierBills'][$id]))o(['ok'=>false,'error'=>'Non-Woven bag bill not found.'],404);$s['nonWovenBagSupplierBills'][$id]['rateExceptionApprovedAt']=gmdate('c');$s['nonWovenBagSupplierBills'][$id]['rateExceptionApprovedBy']=(string)($u['full_name']??$u['username']??'Director');$res=postBill($s,$u,$id);}
elseif($a==='pay_bill'){$id=trim((string)($b['billId']??''));$x=$s['nonWovenBagSupplierBills'][$id]??null;if(!is_array($x)||($x['entity']??'')!==$e||($x['status']??'')!=='Posted')o(['ok'=>false,'error'=>'Non-Woven bag bill is not available for payment.'],404);$out=max(0,round((float)$x['totalAmount']-paid($s,$id),2));$amt=round((float)($b['amount']??0),2);if(abs($amt-$out)>.005)o(['ok'=>false,'error'=>'Non-Woven bag supplier bills must be paid in full. Partial payment is not allowed.'],422);$bid=trim((string)($b['bankId']??''));$bk=bank($bid,$e,$s);$date=dt((string)($b['date']??''),'payment date');$n=names();$j=[ln('2140',$amt,0,$n,['subledger'=>'Packaging Supplier Payable','supplier'=>$x['supplier'],'bagBillId'=>$id]),ln('1110',0,$amt,$n,['method'=>'Bank','bankAccountId'=>$bid,'bank'=>$bk])];$jid=nid((array)$s['journals'],'AUTO');$s['journals'][$jid]=['id'=>$jid,'entity'=>$e,'date'=>$date,'sourceType'=>'NON_WOVEN_BAG_SUPPLIER_PAYMENT','reference'=>trim((string)($b['reference']??''))?:$x['sellerInvoice'],'narration'=>'Non-Woven bag supplier payment — '.$x['supplier'].' — '.$x['sellerInvoice'],'lines'=>$j,'totalDebit'=>$amt,'totalCredit'=>$amt,'status'=>'Posted','meta'=>['billId'=>$id,'poNo'=>$x['poNo'],'supplier'=>$x['supplier'],'paymentMethod'=>'Bank','bankAccountId'=>$bid],'createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??$u['username']??'Accounts')];$pid=nid((array)$s['nonWovenBagSupplierPayments'],'NWBPAY');$s['nonWovenBagSupplierPayments'][$pid]=['id'=>$pid,'entity'=>$e,'billId'=>$id,'supplier'=>$x['supplier'],'sellerInvoice'=>$x['sellerInvoice'],'poNo'=>$x['poNo'],'date'=>$date,'amount'=>$amt,'method'=>'Bank','bankId'=>$bid,'journalId'=>$jid,'status'=>'Posted'];$res=$s['nonWovenBagSupplierPayments'][$pid];}
else o(['ok'=>false,'error'=>'Unknown Non-Woven bag action.'],422);$s['revision']=(int)($s['revision']??0)+1;tt_ensure_data_dir();$h=fopen(F,'c+');if(!$h||!flock($h,LOCK_EX))throw new RuntimeException();try{rewind($h);ftruncate($h,0);fwrite($h,json_encode($s,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($h);}finally{flock($h,LOCK_UN);fclose($h);}o(['ok'=>true,'result'=>$res,'revision'=>$s['revision']]);}catch(Throwable $x){o(['ok'=>false,'error'=>'The Non-Woven bag action could not be completed.'],500);}