<?php
declare(strict_types=1);
require dirname(__DIR__).'/auth_store.php';
header('Content-Type: application/json; charset=UTF-8');
header('Cache-Control: no-store, no-cache, must-revalidate');
const TT_OP_FILE=TT_DATA_DIR.'/accounts.json';
const TT_OP_MASTER=__DIR__.'/../accounts/accounting_master_v1.json';
function op_out(array $d,int $s=200):never{http_response_code($s);echo json_encode($d,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function op_def():array{return ['revision'=>0,'journals'=>[],'otherPurchases'=>[],'fixedAssets'=>[],'bankAccountSettings'=>[]];}
function op_read():array{tt_ensure_data_dir();if(!is_file(TT_OP_FILE))return op_def();$h=fopen(TT_OP_FILE,'r');if($h===false||!flock($h,LOCK_SH))throw new RuntimeException('Accounts storage unavailable.');try{$raw=stream_get_contents($h);}finally{flock($h,LOCK_UN);fclose($h);} $v=$raw?json_decode($raw,true):null;return is_array($v)?array_replace_recursive(op_def(),$v):op_def();}
function op_write(array $s):void{tt_ensure_data_dir();$h=fopen(TT_OP_FILE,'c+');if($h===false||!flock($h,LOCK_EX))throw new RuntimeException('Accounts storage unavailable.');try{rewind($h);ftruncate($h,0);fwrite($h,json_encode($s,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($h);}finally{flock($h,LOCK_UN);fclose($h);}}
function op_can(array $u):bool{if(($u['role']??'')==='Super Admin')return true;$p=$u['permissions']['Accounts']??null;if($p==='all')return true;if(!is_array($p))return false;if(in_array('Create',$p,true)||in_array('Edit',$p,true)||in_array('Approve',$p,true))return true;foreach($p as $a)if(is_array($a)&&(in_array('Create',$a,true)||in_array('Edit',$a,true)||in_array('Approve',$a,true)))return true;return false;}
function op_ent(string $v):string{$v=strtoupper(trim($v));if(!in_array($v,['TTI','BRM','TG'],true))op_out(['ok'=>false,'error'=>'Select valid company books.'],422);return $v;}
function op_require_entity(array $u,string $e,bool $write=false):void{if(($u['role']??'')==='Super Admin')return;$allowed=$write?(tt_user_can_access_entity($u,$e,'Create')||tt_user_can_access_entity($u,$e,'Edit')||tt_user_can_access_entity($u,$e,'Approve')):tt_user_can_access_entity($u,$e,'View');if(!$allowed)op_out(['ok'=>false,'error'=>'You do not have permission for this legal entity.'],403);}
function op_location(string $v):string{$v=strtoupper(trim($v));if(!in_array($v,['MILL','OFFICE','OTHER'],true))op_out(['ok'=>false,'error'=>'Select Mill, Office or Other business location.'],422);return $v;}
function op_years(mixed $v):int{$n=(int)$v;if($n<1||$n>50)op_out(['ok'=>false,'error'=>'Useful life must be between 1 and 50 years.'],422);return $n;}
function op_date(string $v,string $n='date'):string{if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$v))op_out(['ok'=>false,'error'=>'Valid '.$n.' required.'],422);return $v;}
function op_money(mixed $v):float{$n=round((float)$v,2);if($n<=0)op_out(['ok'=>false,'error'=>'Amount must be greater than zero.'],422);return $n;}
function op_names():array{$raw=is_file(TT_OP_MASTER)?file_get_contents(TT_OP_MASTER):false;$m=$raw?json_decode($raw,true):null;if(!is_array($m))throw new RuntimeException('Accounting master unavailable.');$o=[];foreach((array)($m['chart']??[]) as $a)if(is_array($a)&&isset($a['code']))$o[(string)$a['code']]=(string)($a['name']??$a['code']);return $o;}
function op_line(string $a,float $dr,float $cr,array $n,array $x=[]):array{if(!isset($n[$a]))op_out(['ok'=>false,'error'=>'Required account '.$a.' is not configured.'],422);return array_merge(['account'=>$a,'accountName'=>$n[$a],'debit'=>round($dr,2),'credit'=>round($cr,2)],$x);}
function op_next(array $a,string $p):string{$n=count($a)+1;do{$id=$p.'-'.gmdate('Y').'-'.str_pad((string)$n,6,'0',STR_PAD_LEFT);$n++;}while(isset($a[$id]));return $id;}
function op_account(string $type,string $sub):string{if($type==='FIXED_ASSET'){$map=['VEHICLE'=>'1520','FURNITURE'=>'1530','COMPUTER'=>'1540','PLANT'=>'1510'];}else{$map=['REPAIRS'=>'6400','TRAVEL'=>'6500','FUEL'=>'6600','PROFESSIONAL'=>'6700','OFFICE'=>'6900','CONSUMABLE'=>'6900','SERVICE'=>'6900'];}if(!isset($map[$sub]))op_out(['ok'=>false,'error'=>'Select a valid purchase classification.'],422);return $map[$sub];}
function op_bank_master(string $id,string $entity):array{$masters=tt_list_masters();foreach((array)($masters['banks']??[]) as $r){if(!is_array($r)||(string)($r['id']??'')!==$id)continue;$v=array_values((array)($r['values']??[]));while(count($v)<14)$v[]='';$linked=strtoupper((string)$v[1]);$be=str_contains($linked,'BRM')||str_contains($linked,'BUKSH RICE')?'BRM':(str_contains($linked,'TG')||str_contains($linked,'TRANS GRAINS')?'TG':(str_contains($linked,'TTI')||str_contains($linked,'TRANSTRADE INTERNATIONAL')?'TTI':''));if($be!==$entity)op_out(['ok'=>false,'error'=>'Selected bank account does not belong to these company books.'],422);return ['id'=>$id,'name'=>(string)$v[4],'title'=>(string)$v[3],'currency'=>strtoupper(trim((string)$v[7]))];}op_out(['ok'=>false,'error'=>'Selected bank account was not found.'],404);}
function op_banks(array $s,string $e):array{$masters=tt_list_masters();$o=[];foreach((array)($masters['banks']??[]) as $r){if(!is_array($r))continue;$v=array_values((array)($r['values']??[]));while(count($v)<14)$v[]='';$linked=strtoupper((string)$v[1]);$be=str_contains($linked,'BRM')||str_contains($linked,'BUKSH RICE')?'BRM':(str_contains($linked,'TG')||str_contains($linked,'TRANS GRAINS')?'TG':(str_contains($linked,'TTI')||str_contains($linked,'TRANSTRADE INTERNATIONAL')?'TTI':''));$id=(string)($r['id']??'');$set=is_array($s['bankAccountSettings'][$id]??null)?$s['bankAccountSettings'][$id]:[];if($be!==$e||trim((string)$v[0])!=='Company Account'||empty($set['active'])||empty($set['allowPayments']))continue;$o[]=['id'=>$id,'display'=>trim((string)$v[4]).' — '.trim((string)$v[3]),'currency'=>strtoupper(trim((string)$v[7]))];}return $o;}
function op_payload(array $s,string $e):array{$rows=array_values(array_filter((array)($s['otherPurchases']??[]),static fn($x)=>is_array($x)&&($x['entity']??'')===$e));$assets=array_values(array_filter((array)($s['fixedAssets']??[]),static fn($x)=>is_array($x)&&($x['entity']??'')===$e));usort($rows,static fn($a,$b)=>strcmp((string)($b['date']??''),(string)($a['date']??''))?:strcmp((string)($b['id']??''),(string)($a['id']??'')));usort($assets,static fn($a,$b)=>strcmp((string)($b['acquisitionDate']??''),(string)($a['acquisitionDate']??'')));return ['ok'=>true,'entity'=>$e,'rows'=>$rows,'fixedAssets'=>$assets,'banks'=>op_banks($s,$e),'serverNow'=>gmdate('c')];}
try{
$u=tt_require_login();if(!tt_user_can_open_module($u,'Accounts'))op_out(['ok'=>false,'error'=>'Accounts permission required.'],403);
$e=op_ent((string)($_GET['entity']??'TTI'));op_require_entity($u,$e,false);
if($_SERVER['REQUEST_METHOD']==='GET')op_out(op_payload(op_read(),$e));
if($_SERVER['REQUEST_METHOD']!=='POST')op_out(['ok'=>false,'error'=>'Method not allowed.'],405);
if(!op_can($u))op_out(['ok'=>false,'error'=>'Accounts Create / Edit / Approve permission required.'],403);
$b=json_decode(file_get_contents('php://input')?:'{}',true);if(!is_array($b)||!tt_verify_csrf((string)($b['csrf']??'')))op_out(['ok'=>false,'error'=>'Your session expired. Refresh and try again.'],419);
if(($b['action']??'')!=='post_purchase')op_out(['ok'=>false,'error'=>'Unknown other-purchase action.'],422);
$e=op_ent((string)($b['entity']??''));op_require_entity($u,$e,true);
$date=op_date((string)($b['date']??''),'purchase date');$type=strtoupper(trim((string)($b['type']??'')));if(!in_array($type,['FIXED_ASSET','OPERATING'],true))op_out(['ok'=>false,'error'=>'Select Fixed Asset or Operating Purchase.'],422);
$sub=strtoupper(trim((string)($b['subtype']??'')));$supplier=trim((string)($b['supplier']??''));$desc=trim((string)($b['description']??''));$inv=trim((string)($b['invoiceNo']??''));$invDate=trim((string)($b['invoiceDate']??''));if($invDate!=='')op_date($invDate,'supplier invoice date');$amount=op_money($b['amount']??0);$location=op_location((string)($b['location']??''));if($supplier===''||$desc==='')op_out(['ok'=>false,'error'=>'Supplier / payee and description are required.'],422);
$settlement=strtoupper(trim((string)($b['settlement']??'')));if(!in_array($settlement,['BANK','CASH','CREDIT'],true))op_out(['ok'=>false,'error'=>'Select Bank, Cash or Supplier Bill Due.'],422);
$assetName=trim((string)($b['assetName']??''));$assetTag=strtoupper(trim((string)($b['assetTag']??'')));$custodian=trim((string)($b['custodian']??''));$inServiceDate=trim((string)($b['inServiceDate']??''));$usefulLife=0;
if($type==='FIXED_ASSET'){if($assetName===''||$assetTag===''||$inServiceDate==='')op_out(['ok'=>false,'error'=>'Asset name, unique asset tag and in-service date are required.'],422);op_date($inServiceDate,'in-service date');$usefulLife=op_years($b['usefulLifeYears']??0);}
tt_ensure_data_dir();$h=fopen(TT_OP_FILE,'c+');if($h===false||!flock($h,LOCK_EX))throw new RuntimeException('Accounts storage unavailable.');
try{
rewind($h);$raw=stream_get_contents($h);$s=$raw?json_decode($raw,true):null;if(!is_array($s))$s=op_def();$s=array_replace_recursive(op_def(),$s);
if($inv!=='')foreach((array)$s['otherPurchases']as$old)if(is_array($old)&&($old['entity']??'')===$e&&strcasecmp((string)($old['supplier']??''),$supplier)===0&&strcasecmp((string)($old['invoiceNo']??''),$inv)===0)op_out(['ok'=>false,'error'=>'This supplier invoice is already recorded in these company books.'],409);
if($type==='FIXED_ASSET')foreach((array)$s['fixedAssets']as$old)if(is_array($old)&&($old['entity']??'')===$e&&strcasecmp((string)($old['assetTag']??''),$assetTag)===0)op_out(['ok'=>false,'error'=>'This asset tag already exists in these company books.'],409);
$names=op_names();$debit=op_account($type,$sub);$purchaseId=op_next((array)$s['otherPurchases'],'OP');$meta=['otherPurchaseId'=>$purchaseId,'purchaseType'=>$type,'purchaseSubtype'=>$sub,'supplier'=>$supplier,'invoiceNo'=>$inv,'description'=>$desc,'location'=>$location];
if($settlement==='BANK'){$bankId=trim((string)($b['bankId']??''));$bank=op_bank_master($bankId,$e);$set=is_array($s['bankAccountSettings'][$bankId]??null)?$s['bankAccountSettings'][$bankId]:[];if(empty($set['active'])||empty($set['allowPayments']))op_out(['ok'=>false,'error'=>'Selected bank is not enabled for payments.'],422);$credit='1110';$creditExtra=['bankAccountId'=>$bankId,'bank'=>$bank];$status='Paid';}
elseif($settlement==='CASH'){$bankId='CASH|'.$e;$set=is_array($s['bankAccountSettings'][$bankId]??null)?$s['bankAccountSettings'][$bankId]:['active'=>true,'allowPayments'=>true];if(empty($set['active'])||empty($set['allowPayments']))op_out(['ok'=>false,'error'=>'Cash is not enabled for payments.'],422);$credit='1120';$creditExtra=['paymentAccountId'=>$bankId];$status='Paid';}
else{$bankId='';$credit='2140';$creditExtra=['subledger'=>'Other Supplier / Expense Payable','supplier'=>$supplier];$status='Outstanding';}
$lines=[op_line($debit,$amount,0,$names,$meta),op_line($credit,0,$amount,$names,$creditExtra)];$jid=op_next((array)$s['journals'],'AUTO');$source=$type==='FIXED_ASSET'?'FIXED_ASSET_PURCHASE':'OTHER_PURCHASE';
$s['journals'][$jid]=['id'=>$jid,'entity'=>$e,'date'=>$date,'sourceType'=>$source,'reference'=>$inv!==''?$inv:$purchaseId,'narration'=>($type==='FIXED_ASSET'?'Fixed asset purchase — ':'Other purchase — ').$supplier.' — '.$desc,'lines'=>$lines,'totalDebit'=>$amount,'totalCredit'=>$amount,'status'=>'Posted','meta'=>$meta+['settlement'=>$settlement],'createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??$u['username']??'Accounts'),'userId'=>(int)($u['id']??0)];
$s['otherPurchases'][$purchaseId]=['id'=>$purchaseId,'entity'=>$e,'date'=>$date,'type'=>$type,'subtype'=>$sub,'supplier'=>$supplier,'description'=>$desc,'invoiceNo'=>$inv,'invoiceDate'=>$invDate,'amount'=>$amount,'location'=>$location,'settlement'=>$settlement,'paymentAccountId'=>$bankId,'status'=>$status,'journalId'=>$jid,'createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??$u['username']??'Accounts')];
$assetId='';
if($type==='FIXED_ASSET'){$assetId=op_next((array)$s['fixedAssets'],'FA');$s['fixedAssets'][$assetId]=['id'=>$assetId,'entity'=>$e,'assetTag'=>$assetTag,'assetName'=>$assetName,'category'=>$sub,'assetAccount'=>$debit,'assetAccountName'=>$names[$debit],'acquisitionDate'=>$date,'inServiceDate'=>$inServiceDate,'cost'=>$amount,'location'=>$location,'custodian'=>$custodian,'usefulLifeYears'=>$usefulLife,'depreciationMethod'=>'STRAIGHT_LINE','residualValue'=>0,'accumulatedDepreciation'=>0,'netBookValue'=>$amount,'status'=>'Active','purchaseId'=>$purchaseId,'journalId'=>$jid,'createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??$u['username']??'Accounts')];$s['otherPurchases'][$purchaseId]['assetId']=$assetId;}
$s['revision']=(int)($s['revision']??0)+1;rewind($h);ftruncate($h,0);fwrite($h,json_encode($s,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($h);
}finally{flock($h,LOCK_UN);fclose($h);}
op_out(op_payload($s,$e)+['saved'=>$s['otherPurchases'][$purchaseId],'assetId'=>$assetId,'revision'=>$s['revision']]);
}catch(Throwable $x){op_out(['ok'=>false,'error'=>'Other purchase could not be posted.'],500);}
