<?php
declare(strict_types=1);
require dirname(__DIR__).'/auth_store.php';
header('Content-Type: application/json; charset=UTF-8');
header('Cache-Control: no-store, no-cache, must-revalidate');
const TT_OSP_FILE=TT_DATA_DIR.'/accounts.json';
const TT_OSP_MASTER=__DIR__.'/../accounts/accounting_master_v1.json';
function os_out(array $d,int $s=200):never{http_response_code($s);echo json_encode($d,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function os_def():array{return ['revision'=>0,'journals'=>[],'otherPurchases'=>[],'otherSupplierPayments'=>[],'bankAccountSettings'=>[]];}
function os_read():array{tt_ensure_data_dir();if(!is_file(TT_OSP_FILE))return os_def();$h=fopen(TT_OSP_FILE,'r');if($h===false||!flock($h,LOCK_SH))throw new RuntimeException('Accounts storage unavailable.');try{$raw=stream_get_contents($h);}finally{flock($h,LOCK_UN);fclose($h);} $v=$raw?json_decode($raw,true):null;return is_array($v)?array_replace_recursive(os_def(),$v):os_def();}
function os_write(array $s):void{tt_ensure_data_dir();$h=fopen(TT_OSP_FILE,'c+');if($h===false||!flock($h,LOCK_EX))throw new RuntimeException('Accounts storage unavailable.');try{rewind($h);ftruncate($h,0);fwrite($h,json_encode($s,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($h);}finally{flock($h,LOCK_UN);fclose($h);}}
function os_can(array $u):bool{if(($u['role']??'')==='Super Admin')return true;$p=$u['permissions']['Accounts']??null;if($p==='all')return true;if(!is_array($p))return false;if(in_array('Create',$p,true)||in_array('Edit',$p,true)||in_array('Approve',$p,true))return true;foreach($p as $a)if(is_array($a)&&(in_array('Create',$a,true)||in_array('Edit',$a,true)||in_array('Approve',$a,true)))return true;return false;}
function os_ent(string $v):string{$v=strtoupper(trim($v));if(!in_array($v,['TTI','BRM','TG'],true))os_out(['ok'=>false,'error'=>'Select valid company books.'],422);return $v;}
function os_date(string $v):string{if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$v))os_out(['ok'=>false,'error'=>'Valid payment date required.'],422);return $v;}
function os_money(mixed $v,string $label='Amount'):float{$n=round((float)$v,2);if($n<=0)os_out(['ok'=>false,'error'=>$label.' must be greater than zero.'],422);return $n;}
function os_names():array{$raw=is_file(TT_OSP_MASTER)?file_get_contents(TT_OSP_MASTER):false;$m=$raw?json_decode($raw,true):null;if(!is_array($m))throw new RuntimeException('Accounting master unavailable.');$o=[];foreach((array)($m['chart']??[]) as $a)if(is_array($a)&&isset($a['code']))$o[(string)$a['code']]=(string)($a['name']??$a['code']);return $o;}
function os_line(string $a,float $dr,float $cr,array $n,array $x=[]):array{if(!isset($n[$a]))os_out(['ok'=>false,'error'=>'Required account '.$a.' is not configured.'],422);return array_merge(['account'=>$a,'accountName'=>$n[$a],'debit'=>round($dr,2),'credit'=>round($cr,2)],$x);}
function os_next(array $a,string $p):string{$n=count($a)+1;do{$id=$p.'-'.gmdate('Y').'-'.str_pad((string)$n,6,'0',STR_PAD_LEFT);$n++;}while(isset($a[$id]));return $id;}
function os_paid(array $s,string $purchaseId):float{$n=0.0;foreach((array)($s['otherSupplierPayments']??[]) as $p){if(!is_array($p)||($p['status']??'')==='Cancelled')continue;if((string)($p['purchaseId']??'')===$purchaseId)$n+=(float)($p['amount']??0);}return round($n,2);}
function os_rows(array $s,string $e):array{$rows=[];foreach((array)($s['otherPurchases']??[]) as $id=>$p){if(!is_array($p)||($p['entity']??'')!==$e||($p['settlement']??'')!=='CREDIT')continue;$total=round((float)($p['amount']??0),2);$paid=os_paid($s,(string)$id);$out=max(0,round($total-$paid,2));if($out<=.005)continue;$rows[]=['purchaseId'=>(string)$id,'supplier'=>(string)($p['supplier']??''),'invoiceNo'=>(string)($p['invoiceNo']??''),'invoiceDate'=>(string)($p['invoiceDate']??''),'date'=>(string)($p['date']??''),'description'=>(string)($p['description']??''),'subtype'=>(string)($p['subtype']??''),'totalAmount'=>$total,'paid'=>$paid,'outstanding'=>$out];}usort($rows,static fn($a,$b)=>strcmp($a['supplier'],$b['supplier'])?:strcmp($a['date'],$b['date']));return $rows;}
function os_bank_master(string $id,string $entity):array{$masters=tt_list_masters();foreach((array)($masters['banks']??[]) as $r){if(!is_array($r)||(string)($r['id']??'')!==$id)continue;$v=array_values((array)($r['values']??[]));while(count($v)<14)$v[]='';$linked=strtoupper((string)$v[1]);$be=str_contains($linked,'BRM')||str_contains($linked,'BUKSH RICE')?'BRM':(str_contains($linked,'TG')||str_contains($linked,'TRANS GRAINS')?'TG':(str_contains($linked,'TTI')||str_contains($linked,'TRANSTRADE INTERNATIONAL')?'TTI':''));if($be!==$entity)os_out(['ok'=>false,'error'=>'Selected bank account does not belong to these company books.'],422);return ['id'=>$id,'name'=>(string)$v[4],'title'=>(string)$v[3],'currency'=>strtoupper(trim((string)$v[7]))];}os_out(['ok'=>false,'error'=>'Selected bank account was not found.'],404);}
function os_banks(array $s,string $e):array{$masters=tt_list_masters();$o=[];foreach((array)($masters['banks']??[]) as $r){if(!is_array($r))continue;$v=array_values((array)($r['values']??[]));while(count($v)<14)$v[]='';$linked=strtoupper((string)$v[1]);$be=str_contains($linked,'BRM')||str_contains($linked,'BUKSH RICE')?'BRM':(str_contains($linked,'TG')||str_contains($linked,'TRANS GRAINS')?'TG':(str_contains($linked,'TTI')||str_contains($linked,'TRANSTRADE INTERNATIONAL')?'TTI':''));$id=(string)($r['id']??'');$set=is_array($s['bankAccountSettings'][$id]??null)?$s['bankAccountSettings'][$id]:[];if($be!==$e||trim((string)$v[0])!=='Company Account'||!tt_bank_can_transact($id))continue;$o[]=['id'=>$id,'display'=>trim((string)$v[4]).' — '.trim((string)$v[3]),'currency'=>strtoupper(trim((string)$v[7]))];}return $o;}
function os_payload(array $s,string $e):array{return ['ok'=>true,'entity'=>$e,'payables'=>os_rows($s,$e),'banks'=>os_banks($s,$e),'history'=>array_values(array_filter((array)($s['otherSupplierPayments']??[]),static fn($p)=>is_array($p)&&($p['entity']??'')===$e)),'serverNow'=>gmdate('c')];}
try{$u=tt_require_login();if(!tt_user_can_open_module($u,'Accounts'))os_out(['ok'=>false,'error'=>'Accounts permission required.'],403);$e=os_ent((string)($_GET['entity']??'TTI'));if($_SERVER['REQUEST_METHOD']==='GET')os_out(os_payload(os_read(),$e));if($_SERVER['REQUEST_METHOD']!=='POST')os_out(['ok'=>false,'error'=>'Method not allowed.'],405);if(!os_can($u))os_out(['ok'=>false,'error'=>'Accounts Create / Edit / Approve permission required.'],403);$b=json_decode(file_get_contents('php://input')?:'{}',true);if(!is_array($b)||!tt_verify_csrf((string)($b['csrf']??'')))os_out(['ok'=>false,'error'=>'Your session expired. Refresh and try again.'],419);if(($b['action']??'')!=='pay')os_out(['ok'=>false,'error'=>'Unknown supplier-payment action.'],422);$e=os_ent((string)($b['entity']??''));$purchaseId=trim((string)($b['purchaseId']??''));$date=os_date((string)($b['date']??''));$amount=os_money($b['amount']??0);$method=strtoupper(trim((string)($b['method']??'')));if(!in_array($method,['BANK','CASH','THIRD_PARTY','ADJUSTMENT'],true))os_out(['ok'=>false,'error'=>'Select Bank, Cash, Third Party or Adjustment.'],422);$s=os_read();$p=$s['otherPurchases'][$purchaseId]??null;if(!is_array($p)||($p['entity']??'')!==$e||($p['settlement']??'')!=='CREDIT')os_out(['ok'=>false,'error'=>'Supplier payable not found.'],404);$outstanding=max(0,round((float)$p['amount']-os_paid($s,$purchaseId),2));if($amount>$outstanding+.005)os_out(['ok'=>false,'error'=>'Payment exceeds the outstanding amount.'],422);$names=os_names();$source=[];if($method==='BANK'){$bankId=trim((string)($b['bankId']??''));$bank=os_bank_master($bankId,$e);$set=is_array($s['bankAccountSettings'][$bankId]??null)?$s['bankAccountSettings'][$bankId]:[];if(!tt_bank_can_transact($bankId))os_out(['ok'=>false,'error'=>'Selected bank is not enabled for payments.'],422);$credit='1110';$source=['method'=>'Bank','bankAccountId'=>$bankId,'bank'=>$bank];}elseif($method==='CASH'){$credit='1120';$source=['method'=>'Cash'];}elseif($method==='THIRD_PARTY'){$credit='2520';$name=trim((string)($b['otherParty']??''));if($name==='')os_out(['ok'=>false,'error'=>'Enter the third-party payer name.'],422);$source=['method'=>'Third Party','otherParty'=>$name];}else{$credit='1230';$reason=trim((string)($b['reason']??''));if($reason==='')os_out(['ok'=>false,'error'=>'Reason is required for an adjustment.'],422);$source=['method'=>'Adjustment','reason'=>$reason];}
$lines=[os_line('2140',$amount,0,$names,['subledger'=>'Other Supplier / Expense Payable','supplier'=>$p['supplier'],'purchaseId'=>$purchaseId]),os_line($credit,0,$amount,$names,$source)];$jid=os_next((array)$s['journals'],'AUTO');$ref=trim((string)($b['reference']??''));$s['journals'][$jid]=['id'=>$jid,'entity'=>$e,'date'=>$date,'sourceType'=>'OTHER_SUPPLIER_PAYMENT','reference'=>$ref?:($p['invoiceNo']?:$purchaseId),'narration'=>'Other supplier payment — '.($p['supplier']?:$p['description']),'lines'=>$lines,'totalDebit'=>$amount,'totalCredit'=>$amount,'status'=>'Posted','meta'=>['purchaseId'=>$purchaseId,'supplier'=>$p['supplier'],'paymentMethod'=>$method]+$source,'createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??$u['username']??'Accounts')];$pid=os_next((array)$s['otherSupplierPayments'],'OSPAY');$s['otherSupplierPayments'][$pid]=['id'=>$pid,'entity'=>$e,'purchaseId'=>$purchaseId,'supplier'=>$p['supplier'],'invoiceNo'=>$p['invoiceNo'],'date'=>$date,'amount'=>$amount,'method'=>$method,'reference'=>$ref,'journalId'=>$jid,'status'=>'Posted','createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??$u['username']??'Accounts')]+$source;$s['revision']=(int)($s['revision']??0)+1;os_write($s);os_out(os_payload($s,$e)+['payment'=>$s['otherSupplierPayments'][$pid],'revision'=>$s['revision']]);}catch(Throwable $x){os_out(['ok'=>false,'error'=>'Supplier payment could not be completed.'],500);}
