<?php
declare(strict_types=1);

function pl_key(array $r):string{return (string)$r['billId'].'|'.(string)$r['sourceKey'];}
function pl_group(array $bill):string{return trim((string)($bill['broker']??''))?:trim((string)($bill['relationshipName']??$bill['vendor']??$bill['supplier']??$bill['party']??''));}
function pl_live_journal(array $s,string $id):bool{
 $j=$s['journals'][$id]??null;if(!is_array($j)||($j['status']??'')!=='Posted'||!empty($j['reversalOf']))return false;
 foreach((array)($s['journals']??[]) as $r)if(is_array($r)&&($r['reversalOf']??'')===$id)return false;return true;
}
/** Adapt standalone brokerage without changing its original liability or bill identity. */
function pl_broker_bill(array $s,string $entity,string $id):?array{
 $b=$s['brokerageBills'][$id]??null;if(!is_array($b)||($b['entity']??'')!==$entity||in_array($b['status']??'Posted',['Cancelled','Deleted','Reversed'],true))return null;
 $net=round((float)($b['acceptedBrokerage']??$b['grossBrokerage']??0)-(float)($b['whtAmount']??0),2);$legacy=0.0;
 foreach((array)($s['brokeragePayments']??[]) as $p)if(is_array($p)&&empty($p['settlementId'])&&($p['entity']??'')===$entity&&($p['brokerageSourceId']??'')==='SEPARATE|'.$id&&in_array($p['status']??'Posted',['Posted','Approved / Posted','Approved'],true))$legacy+=(float)($p['amount']??0);
 return ['id'=>$id,'entity'=>$entity,'broker'=>$b['broker']??'','billNo'=>$b['billNo']??$id,'billDate'=>$b['billDate']??'','journalId'=>$b['journalId']??'','category'=>'BROKERAGE','payableAccount'=>'2120','supplierPayableTotal'=>$net,'receiptAllocations'=>[['sourceKey'=>'BROKERAGE|'.$id,'payee'=>$b['broker']??'','supplierPayableShare'=>max(0,round($net-$legacy,2)),'dueDate'=>$b['dueDate']??$b['billDate']??'','truck'=>$b['truck']??'','pohanch'=>$b['pohanch']??'']]];
}
function pl_raw_rows(array $s,string $e,string $mode):array{
 $rows=[];
 if($mode==='PARTY'){
  foreach(pp_rows($s,$e) as $r){if(!isset($s['commodityBills'][$r['billId']])&&!isset($s['supplierBills'][$r['billId']]))continue;$b=$s['commodityBills'][$r['billId']]??$s['supplierBills'][$r['billId']];if(in_array($b['status']??'Posted',['Cancelled','Deleted','Reversed','Draft'],true))continue;$r['group']=pl_group($b);$r['postId']=$b['journalId']??(array_slice((array)($b['postingJournalIds']??[]),-1)[0]??$b['postingNumber']??$r['billId']);$r['component']='';foreach((array)($b['receiptAllocations']??[]) as $a)if(($a['sourceKey']??'')===$r['sourceKey']){$r['component']=$a['component']??'';break;}$r['rowKey']=pl_key($r);$rows[]=$r;}
  foreach(ss_simple_payables($s,$e) as $r){if(isset($s['supplierBills'][$r['billId']]))continue;$b=ss_external_bill($s,$e,$r['billId']);if(!$b)continue;$due=(string)($b['dueDate']??$b['billDate']??'');$rows[]=['entity'=>$e,'billId'=>$r['billId'],'billNo'=>$r['billNo'],'sourceKey'=>$r['sourceKey'],'rowKey'=>pl_key($r),'group'=>$r['supplier'],'broker'=>$r['supplier'],'component'=>'SERVICE','postId'=>($s['bagSupplierBills'][$r['billId']]['journalId']??$s['otherPurchases'][$r['billId']]['journalId']??$r['billId']),'dueDate'=>$due,'receiptDate'=>$r['billDate'],'truck'=>'','outstanding'=>$r['outstanding'],'held'=>false];}
 }else foreach((array)($s['brokerageBills']??[]) as $id=>$b){$b=pl_broker_bill($s,$e,(string)$id);if(!$b)continue;$a=$b['receiptAllocations'][0];$cap=ss_component_capacity($s,$e,$b,$a);if($cap['total']<=.005)continue;$rows[]=['entity'=>$e,'billId'=>$b['id'],'billNo'=>$b['billNo'],'sourceKey'=>$a['sourceKey'],'rowKey'=>$b['id'].'|'.$a['sourceKey'],'group'=>$b['broker'],'broker'=>$b['broker'],'component'=>'BROKERAGE','postId'=>$b['journalId']?:$b['id'],'dueDate'=>$a['dueDate'],'receiptDate'=>$b['billDate'],'truck'=>$a['truck'],'outstanding'=>$cap['total'],'held'=>false];}
 usort($rows,static fn($a,$b)=>strcmp((string)$a['dueDate'],(string)$b['dueDate'])?:strcmp((string)($a['receiptDate']??''),(string)($b['receiptDate']??''))?:strcmp(pl_key($a),pl_key($b)));return $rows;
}
function pl_prepare(array $s,string $e,array $raw):array{
 $parts=[];$total=0.0;$net=0.0;$wht=0.0;$debits=[];$rows=[];$used=[];
 foreach($raw as $r){$k=pl_key($r);if(isset($used[$k]))throw new DomainException('A truck allocation was repeated.');$used[$k]=true;$p=ss_prepare_allocations($s,$e,[$r]);$total+=$p['total'];$net+=$p['netPayment'];$wht+=$p['withholding'];foreach($p['debits'] as $a=>$v)$debits[$a]=round(($debits[$a]??0)+$v,2);$rows=array_merge($rows,$p['rows']);}
 if(!$rows)throw new DomainException('Select an outstanding bill.');return ['rows'=>$rows,'total'=>round($total,2),'netPayment'=>round($net,2),'withholding'=>round($wht,2),'debits'=>$debits];
}
/** JV payable debits have already moved the ledger. Link them once, oldest first, without another journal. */
function pl_link_round_journals(array &$s,string $e):void{
 foreach((array)($s['supplierSettlements']??[]) as $id=>$set)if(($set['type']??'')==='Round JV Allocation'&&($set['entity']??'')===$e&&!pl_live_journal($s,(string)$set['journalId']))$s['supplierSettlements'][$id]['status']='Reversed';
 $journals=(array)($s['journals']??[]);uasort($journals,static fn($a,$b)=>strcmp((string)($a['date']??''),(string)($b['date']??'')));
 foreach($journals as $jid=>$j){if(($j['entity']??'')!==$e||!in_array($j['meta']['originalSourceType']??$j['sourceType']??'',['JV','SUPPLIER_PAYMENT'],true)||!empty($j['meta']['settlementId'])||!pl_live_journal($s,(string)$jid))continue;
  foreach((array)($j['lines']??[]) as $i=>$line){$account=(string)($line['account']??'');$amount=round((float)($line['debit']??0)-(float)($line['credit']??0),2);$party=trim((string)($line['counterparty']??$line['subledger']??$line['party']??$j['meta']['broker']??$j['meta']['supplier']??''));if(!in_array($account,['2110','2120'],true)||$amount<=.005||$party==='')continue;
   $id='ROUND|'.$jid.'|'.$i;$prior=$s['supplierSettlements'][$id]??[];$applied=($prior['status']??'')==='Posted'?round((float)($prior['amount']??0),2):0.0;$left=round($amount-$applied,2);if($left<=.005)continue;$alloc=[];
   $modes=$account==='2110'?['PARTY']:['PARTY','BROKER'];foreach($modes as $mode)foreach(pl_raw_rows($s,$e,$mode) as $r){if($left<=.005)break;$matches=strcasecmp($party,(string)$r['broker'])===0||strcasecmp($party,(string)$r['group'])===0;if(!$matches||!empty($r['held'])||($account==='2110'&&$r['component']==='BROKERAGE')||($account==='2120'&&$r['component']!=='BROKERAGE'))continue;$part=min($left,(float)$r['outstanding']);$p=pl_prepare($s,$e,[['billId'=>$r['billId'],'sourceKey'=>$r['sourceKey'],'amount'=>$part]]);$alloc=array_merge($alloc,$p['rows']);$left=round($left-$part,2);}
   if($alloc){$creditParties=[];foreach((array)($j['lines']??[]) as $credit)if((float)($credit['credit']??0)>0)$creditParties[]=trim((string)($credit['counterparty']??$credit['subledger']??$credit['party']??$credit['accountName']??$credit['account']??''));$s['supplierSettlements'][$id]=['id'=>$id,'entity'=>$e,'date'=>$j['date'],'type'=>'Round JV Allocation','broker'=>$party,'amount'=>round($applied+array_sum(array_column($alloc,'amount')),2),'netPayment'=>round($applied+array_sum(array_column($alloc,'amount')),2),'journalId'=>$jid,'status'=>'Posted','payer'=>implode(' / ',array_unique($creditParties)),'allocations'=>array_merge((array)($prior['allocations']??[]),$alloc),'createdAt'=>$j['createdAt']??gmdate('c')];}
  }
 }
}
function pl_bank_rows(array $s,string $e):array{
 $rows=array_values(array_filter(ba_payload($s,$e)['accounts'],static fn($b)=>!empty($b['settings']['active'])&&$b['currency']==='PKR'));$pending=[];
 foreach((array)($s['supplierSettlements']??[]) as $p)if(($p['entity']??'')===$e&&($p['chequeStatus']??'')==='Issued'&&($p['status']??'')==='Posted')$pending[$p['bankAccountId']]=round(($pending[$p['bankAccountId']]??0)+(float)$p['netPayment'],2);
 foreach($rows as &$b){$b['pendingCheques']=$pending[$b['id']]??0.0;$b['availableBalance']=round((float)$b['availableBalance']-$b['pendingCheques'],2);}unset($b);return $rows;
}
function pl_funds(array $s,string $e,array $ids):float{
 $all=[];foreach(pl_bank_rows($s,$e) as $b)$all[$b['id']]=$b;$sum=0.0;if(count($ids)!==count(array_unique($ids))||count($ids)>20)throw new DomainException('Select each bank only once.');
 foreach($ids as $id){if(!is_string($id)||!isset($all[$id]))throw new DomainException('A selected bank is inactive, foreign currency or belongs to another company.');$sum+=max(0,(float)$all[$id]['availableBalance']);}return round($sum,2);
}
function pl_allocations(array $s,string $e,string $mode,array $keys,string $group='',?float $amount=null):array{
 $keys=array_values(array_unique(array_map('strval',$keys)));if(!$keys||count($keys)>1000)throw new DomainException('Select one or more truck bills.');$map=[];foreach(pl_raw_rows($s,$e,$mode) as $r)$map[$r['rowKey']]=$r;$out=[];$left=$amount;
 foreach($keys as $key){$r=$map[$key]??null;if(!$r||!empty($r['held'])||($group!==''&&$r['group']!==$group))throw new DomainException('A selected payable changed, is held or belongs to another party. Reopen the plan.');if($left!==null&&$left<=.005)break;$use=$left===null?(float)$r['outstanding']:min($left,(float)$r['outstanding']);if($use>.005)$out[]=['billId'=>$r['billId'],'sourceKey'=>$r['sourceKey'],'amount'=>round($use,2)];if($left!==null)$left=round($left-$use,2);}
 if($left!==null&&$left>.005)throw new DomainException('Payment exceeds the selected outstanding bills.');return $out;
}
function pl_native_register(array &$s,array $set):void{
 foreach($set['allocations'] as $a){$category=$a['category']??'';if(!in_array($category,['BAGS','OTHER'],true))continue;$collection=$category==='BAGS'?'bagSupplierPayments':'otherSupplierPayments';$id=ss_next_id((array)($s[$collection]??[]),$category==='BAGS'?'BAGPAY':'OSPAY');$s[$collection][$id]=['id'=>$id,'entity'=>$set['entity'],$category==='BAGS'?'billId':'purchaseId'=>$a['billId'],'supplier'=>$set['broker'],'date'=>$set['date'],'amount'=>$a['amount'],'reference'=>$set['id'],'journalId'=>$set['journalId'],'settlementId'=>$set['id'],'method'=>$set['type'],'status'=>'Posted'];}
}
function pl_actor(array $u):string{return (string)($u['full_name']??$u['username']??'Accounts');}
function pl_audit(array &$s,array $u,string $action,array $details):void{$s['workflowAudit'][]=['at'=>gmdate('c'),'action'=>$action,'by'=>pl_actor($u),'userId'=>$u['id']??0,'details'=>$details];}
function pl_apply_advances(array &$s,array $u,string $e,string $mode,array $keys,string $group,string $date):array{
 $applied=[];$adv=(array)($s['supplierAdvances']??[]);uasort($adv,static fn($a,$b)=>strcmp((string)($a['date']??''),(string)($b['date']??'')));
 foreach($adv as $aid=>$a){if(($a['entity']??'')!==$e||in_array($a['status']??'',['Cancelled','Reversed'],true))continue;$available=round((float)($a['amount']??0)-(float)($a['allocatedAmount']??0),2);if($available<=.005)continue;$eligible=[];
  foreach(pl_raw_rows($s,$e,$mode) as $r)if(in_array($r['rowKey'],$keys,true)&&$r['group']===$group&&!$r['held']&&strcasecmp((string)$a['supplier'],(string)$r['broker'])===0&&(empty($a['soda'])||($r['soda']??'')===$a['soda']))$eligible[]=$r;
  $alloc=[];$left=$available;foreach($eligible as $r){if($left<=.005)break;$use=min($left,(float)$r['outstanding']);$alloc[]=['billId'=>$r['billId'],'sourceKey'=>$r['sourceKey'],'amount'=>$use];$left=round($left-$use,2);}if(!$alloc)continue;$p=pl_prepare($s,$e,$alloc);$lines=[];$names=ss_catalog();foreach($p['debits'] as $code=>$v)$lines[]=ss_line((string)$code,$v,0,$names,['counterparty'=>$group]);$lines[]=ss_line('1250',0,$p['total'],$names,['counterparty'=>$a['supplier']]);$id=ss_next_id((array)($s['supplierSettlements']??[]),'SAAP');$j=ss_post_journal($s,$u,$e,$date,'SUPPLIER_ADVANCE_APPLIED',$id,'Round advance through '.($a['payer']??$a['bankName']??$a['payerRelationship']??'').' allocated to '.$group,$lines,['settlementId'=>$id,'advanceId'=>$aid,'allocations'=>$p['rows']]);
  $s['supplierSettlements'][$id]=['id'=>$id,'entity'=>$e,'date'=>$date,'type'=>'Supplier Advance Applied','broker'=>$group,'amount'=>$p['total'],'netPayment'=>0.0,'advanceId'=>$aid,'payer'=>$a['payer']??$a['bankName']??$a['payerRelationship']??'','journalId'=>$j['id'],'status'=>'Posted','allocations'=>$p['rows'],'createdAt'=>gmdate('c')];$s['supplierAdvances'][$aid]['allocatedAmount']=round((float)($a['allocatedAmount']??0)+$p['total'],2);$s['supplierAdvances'][$aid]['availableAmount']=round($available-$p['total'],2);$s['supplierAdvances'][$aid]['status']=$available-$p['total']>.005?'Partly Applied':'Fully Applied';$applied[]=$id;pl_native_register($s,$s['supplierSettlements'][$id]);
 }return $applied;
}
function pl_reverse(array &$s,array $u,string $e,string $sid,string $date,string $reason):void{
 $set=$s['supplierSettlements'][$sid]??null;if(!$set||($set['entity']??'')!==$e||($set['status']??'')!=='Posted'||($set['type']??'')==='Round JV Allocation')throw new DomainException('This payment cannot be corrected here. Correct a round JV from its original voucher.');
 if($reason==='')throw new DomainException('A correction reason is required.');$j=$s['journals'][$set['journalId']]??null;if(!$j||!pl_live_journal($s,(string)$set['journalId']))throw new DomainException('Payment was already reversed or changed.');if($date<(string)$j['date'])throw new DomainException('Correction cannot predate the payment.');
 $ids=[$set['journalId']];if(!empty($set['clearanceJournalId']))$ids[]=$set['clearanceJournalId'];foreach($ids as $jid){$old=$s['journals'][$jid];$rev=ss_post_journal($s,$u,$e,$date,'SUPPLIER_PAYMENT_REVERSAL',$jid,'Payment correction — '.$reason,ss_cheque_reversal_lines($old),['reversalOf'=>$jid,'settlementId'=>$sid,'reason'=>$reason]);$s['journals'][$jid]['meta']['reversedByPostId']=$rev['id'];}
 $s['supplierSettlements'][$sid]['status']='Reversed';$s['supplierSettlements'][$sid]['correctionReason']=$reason;
 if(!empty($set['advanceId'])){$aid=$set['advanceId'];$s['supplierAdvances'][$aid]['allocatedAmount']=max(0,round((float)$s['supplierAdvances'][$aid]['allocatedAmount']-(float)$set['amount'],2));$s['supplierAdvances'][$aid]['availableAmount']=round((float)$s['supplierAdvances'][$aid]['amount']-(float)$s['supplierAdvances'][$aid]['allocatedAmount'],2);$s['supplierAdvances'][$aid]['status']='Available / Unallocated';}
 foreach(['bagSupplierPayments','otherSupplierPayments'] as $collection)foreach((array)($s[$collection]??[]) as $id=>$p)if(($p['settlementId']??'')===$sid){$s[$collection][$id]['status']='Cancelled';$s[$collection][$id]['correctionReason']=$reason;}
 foreach((array)($s['brokeragePayments']??[]) as $id=>$p)if(($p['settlementId']??'')===$sid)$s['brokeragePayments'][$id]['status']='Reversed';pl_audit($s,$u,'PAYMENT_PLAN_CORRECTION',['settlement'=>$set,'reason'=>$reason]);
}
function pl_post(array &$s,array $u,array &$plan,array $b):array{
 $e=$plan['entity'];$group=trim((string)($b['group']??''));$saved=$plan['groups'][$group]??null;if(!$saved||!empty($saved['settlementId']))throw new DomainException('Select an unpaid party in this plan.');$date=ss_date((string)($b['date']??''));
 $keys=(array)($b['rowKeys']??$saved['rowKeys']);$allowed=[];foreach(pl_raw_rows($s,$e,$plan['mode']) as $r)if($r['group']===$group&&!$r['held'])$allowed[]=$r['rowKey'];foreach($keys as $k)if(!in_array($k,$allowed,true))throw new DomainException('A selected truck changed. Review the current dues.');
 $ordered=[];foreach(pl_raw_rows($s,$e,$plan['mode']) as $r)if(in_array($r['rowKey'],$keys,true))$ordered[]=$r['rowKey'];$keys=$ordered;if(!$keys)throw new DomainException('Select a truck bill to pay.');$raw=pl_allocations($s,$e,$plan['mode'],$keys,$group);$p=pl_prepare($s,$e,$raw);$sources=(array)($b['sources']??[]);if(!$sources||count($sources)>20)throw new DomainException('Add at least one payment source.');$lines=[];$total=0.0;$sourceRows=[];$cheques=[];$banks=pl_bank_rows($s,$e);$byId=array_column($banks,null,'id');$reserved=[];$catalog=ss_catalog();
 foreach($sources as $source){$amount=ss_money($source['amount']??0);$type=(string)($source['type']??'BANK');$extra=[];$credit='';$reference=trim((string)($source['reference']??''));$label='';
  if($type==='BANK'){$bid=(string)($source['bankAccountId']??'');if(!in_array($bid,$plan['bankIds'],true)||!isset($byId[$bid]))throw new DomainException('Choose a selected, active bank from this company.');$bank=$byId[$bid];$method=(string)($source['method']??'CHEQUE');if(!in_array($method,['CHEQUE','ONLINE_BANKING'],true))throw new DomainException('Choose Cheque or Online Banking.');if($method==='CHEQUE'&&$reference==='')throw new DomainException('Enter the cheque number.');if($method==='CHEQUE'){$ck=$bid.'|'.strtoupper($reference);if(isset($cheques[$ck]))throw new DomainException('Combine amounts for the same cheque into one payment source.');$cheques[$ck]=true;}$reserved[$bid]=round(($reserved[$bid]??0)+$amount,2);if($reserved[$bid]>(float)$bank['availableBalance']+.005)throw new DomainException('Selected bank funds changed or are insufficient. Review the plan.');if($method==='CHEQUE')foreach((array)$s['journals'] as $j)if(($j['entity']??'')===$e)foreach((array)($j['lines']??[]) as $l)if(($l['bankAccountId']??'')===$bid&&strcasecmp((string)($l['chequeNo']??$j['meta']['chequeNo']??''),$reference)===0&&$reference!==''&&pl_live_journal($s,(string)($j['id']??'')))throw new DomainException('This cheque number has already been used on this bank.');$credit='1110';$extra=['bankAccountId'=>$bid,'bankName'=>$bank['bankName'],'bankAccountTitle'=>$bank['accountTitle'],'currency'=>'PKR','bankCredit'=>$amount,'bankDebit'=>0.0,'bankPaymentMethod'=>$method,'chequeNo'=>$method==='CHEQUE'?$reference:'','chequeDate'=>$method==='CHEQUE'?$date:'','bankReference'=>$reference];$label=$bank['bankName'].' · '.substr(preg_replace('/\W/','',$bank['accountNumber']?:$bank['iban']),-6);}
  elseif($type==='THIRD_PARTY'){$payer=trim((string)($source['payer']??''));$rel=(string)($source['relationship']??'');if($payer===''||!in_array($rel,['CUSTOMER_RECEIVABLE','CUSTOMER_ADVANCE','OTHER_THIRD_PARTY','FAMILY_STAFF'],true))throw new DomainException('Enter the third-party payer and relationship.');$credit=ss_advance_credit_account($rel,$payer);$extra=['counterparty'=>$payer,'subledger'=>$payer,'payerRelationship'=>$rel];$label=$payer;}
  else throw new DomainException('Use a bank or third-party payment source.');$lines[]=ss_line($credit,0,$amount,$catalog,$extra);$total+=$amount;$sourceRows[]=array_merge($source,['amount'=>$amount,'label'=>$label]);
 }
 if(abs(round($total,2)-$p['netPayment'])>.005)throw new DomainException('Payment sources must equal the selected bills net payment of PKR '.number_format($p['netPayment'],2).'.');
 foreach($p['debits'] as $a=>$v)$lines[]=ss_line((string)$a,$v,0,$catalog,['counterparty'=>$group]);if($p['withholding']>0)$lines[]=ss_line('2300',0,$p['withholding'],$catalog);
 $id=ss_next_id((array)($s['supplierSettlements']??[]),'SP');$j=ss_post_journal($s,$u,$e,$date,'SUPPLIER_PAYMENT',$id,'Payment plan '.$plan['id'].' — '.$group,$lines,['settlementId'=>$id,'planId'=>$plan['id'],'broker'=>$group,'allocations'=>$p['rows'],'sources'=>$sourceRows]);$set=['id'=>$id,'entity'=>$e,'date'=>$date,'type'=>'Planned Party Payment','broker'=>$group,'amount'=>$p['total'],'netPayment'=>$p['netPayment'],'withholding'=>$p['withholding'],'status'=>'Posted','journalId'=>$j['id'],'allocations'=>$p['rows'],'sources'=>$sourceRows,'planId'=>$plan['id'],'createdAt'=>gmdate('c'),'createdBy'=>pl_actor($u)];$s['supplierSettlements'][$id]=$set;pl_native_register($s,$set);
 if($plan['mode']==='BROKER')foreach($p['rows'] as $a){$pid=ss_next_id((array)($s['brokeragePayments']??[]),'BRPAY');$s['brokeragePayments'][$pid]=['id'=>$pid,'entity'=>$e,'brokerageSourceId'=>'SEPARATE|'.$a['billId'],'amount'=>$a['amount'],'date'=>$date,'journalId'=>$j['id'],'settlementId'=>$id,'status'=>'Posted'];}
 $plan['groups'][$group]['rowKeys']=$keys;$plan['groups'][$group]['settlementId']=$id;$plan['groups'][$group]['postedAt']=gmdate('c');$plan['groups'][$group]['voucher']=$set;pl_audit($s,$u,'PAYMENT_PLAN_POST',['planId'=>$plan['id'],'settlementId'=>$id]);return $set;
}
function pl_payload(array $s,string $e):array{
 pl_link_round_journals($s,$e);$plans=[];foreach((array)($s['paymentPlans']??[]) as $p)if($p['entity']===$e&&$p['status']==='Open')$plans[]=$p;
 $original=['PARTY'=>pl_raw_rows($s,$e,'PARTY'),'BROKER'=>pl_raw_rows($s,$e,'BROKER')];$preview=$s;
 foreach($original as $mode=>$rows){$groups=[];foreach($rows as $r)if(!$r['held'])$groups[$r['group']][]=$r['rowKey'];foreach($groups as $group=>$keys)pl_apply_advances($preview,['username'=>'Advance allocation preview'],$e,$mode,$keys,$group,(new DateTimeImmutable('now',new DateTimeZone('Asia/Karachi')))->format('Y-m-d'));}
 foreach($original as $mode=>&$rows){$left=array_column(pl_raw_rows($preview,$e,$mode),'outstanding','rowKey');foreach($rows as &$r){$r['beforeAdvance']=$r['outstanding'];$r['advanceApplied']=round($r['outstanding']-(float)($left[$r['rowKey']]??0),2);$r['outstanding']=$left[$r['rowKey']]??0.0;}unset($r);}unset($rows);
 return ['ok'=>true,'entity'=>$e,'banks'=>pl_bank_rows($s,$e),'rows'=>$original['PARTY'],'brokerRows'=>$original['BROKER'],'plans'=>$plans,'adjustments'=>array_values(array_filter((array)($s['supplierSettlements']??[]),static fn($x)=>($x['entity']??'')===$e&&($x['status']??'')==='Posted'&&in_array($x['type']??'',['Round JV Allocation','Supplier Advance Applied'],true))),'advances'=>array_values(array_filter((array)($s['supplierAdvances']??[]),static fn($a)=>($a['entity']??'')===$e&&!in_array($a['status']??'',['Cancelled','Reversed'],true)&&(float)($a['amount']??0)>(float)($a['allocatedAmount']??0)+.005)),'revision'=>$s['revision']??0];
}
