<?php
declare(strict_types=1);
define('TT_SETTLEMENTS_FUNCTIONS_ONLY',true);require_once __DIR__.'/supplier_settlements.php';
define('TT_PAYABLES_FUNCTIONS_ONLY',true);require_once __DIR__.'/payables_planning.php';
define('TT_BANK_FUNCTIONS_ONLY',true);require_once __DIR__.'/bank_accounts.php';
require_once __DIR__.'/payment_plan_core.php';
try{
 $u=tt_require_login();if(!tt_user_can_open_module($u,'Accounts'))ss_respond(['ok'=>false,'error'=>'Accounts access required.'],403);
 $method=$_SERVER['REQUEST_METHOD'];$b=$method==='POST'?json_decode((function_exists('tt_accounts_input')?tt_accounts_input():file_get_contents('php://input'))?:'',true):[];$e=ss_entity((string)($method==='POST'?($b['entity']??''):($_GET['entity']??'')));
 if($method==='GET'&&!tt_user_can_access_entity($u,$e,'View'))ss_respond(['ok'=>false,'error'=>'Company permission required.'],403);
 if($method==='GET'){if(!tt_user_can_module_action($u,'Accounts','supplier','View')&&!tt_user_can_module_action($u,'Accounts','supplier','Create')&&!tt_user_can_module_action($u,'Accounts','supplier','Edit'))ss_respond(['ok'=>false,'error'=>'Party Payment icon access required.'],403);tt_release_read_session();ss_respond(pl_payload(ss_read(),$e));}
 if($method!=='POST')ss_respond(['ok'=>false,'error'=>'Method not allowed.'],405);if(!is_array($b)||!tt_verify_csrf((string)($b['csrf']??'')))ss_respond(['ok'=>false,'error'=>'Session expired.'],419);
 $action=(string)($b['action']??'');$right=in_array($action,['correct','reopen'],true)?'Edit':'Create';if(!tt_user_can_module_action($u,'Accounts','supplier',$right)||!tt_user_can_access_entity($u,$e,$right))ss_respond(['ok'=>false,'error'=>'Party Payment '.$right.' permission required.'],403);
 $key=(string)($b['requestKey']??'');if(!preg_match('/^[a-zA-Z0-9-]{16,80}$/',$key))throw new DomainException('Payment request ID is required.');$fingerprint=hash('sha256',json_encode($b,JSON_THROW_ON_ERROR));
 tt_ensure_data_dir();$h=fopen(TT_SETTLEMENT_FILE,'c+');if(!$h||!flock($h,LOCK_EX))throw new RuntimeException('Accounts storage unavailable.');
 try{rewind($h);$raw=stream_get_contents($h);$s=$raw?json_decode($raw,true):[];if(!is_array($s))throw new RuntimeException('Accounts storage unreadable.');$s=array_replace_recursive(ss_default_store(),$s);$saved=$s['paymentPlanRequests'][$e.'|'.$key]??null;if($saved){if($saved['fingerprint']!==$fingerprint)throw new DomainException('This request was already committed with different details. Reopen the plan.');ss_respond($saved['response']);}pl_link_round_journals($s,$e);
  if($action==='create'){
   $mode=(string)($b['mode']??'PARTY');if(!in_array($mode,['PARTY','BROKER'],true))throw new DomainException('Choose Party Payment or Pay Broker.');foreach((array)($s['paymentPlans']??[]) as $existing)if($existing['entity']===$e&&$existing['mode']===$mode&&$existing['status']==='Open')throw new DomainException('An open payment plan already exists. Resume it from Home.');$banks=(array)($b['bankIds']??[]);if(!$banks)throw new DomainException('Select the banks funding this plan.');$funds=pl_funds($s,$e,$banks);$keys=(array)($b['rowKeys']??[]);$alloc=pl_allocations($s,$e,$mode,$keys);$groups=[];foreach(pl_raw_rows($s,$e,$mode) as $r)if(in_array($r['rowKey'],$keys,true))$groups[$r['group']]['rowKeys'][]=$r['rowKey'];$date=ss_date((string)($b['date']??''));$adjusted=[];
   foreach($groups as $group=>&$g){$g['settlementId']='';$g['adjustmentIds']=pl_apply_advances($s,$u,$e,$mode,$g['rowKeys'],$group,$date);$adjusted=array_merge($adjusted,$g['adjustmentIds']);} unset($g);$remaining=0.0;foreach(pl_raw_rows($s,$e,$mode) as $r)if(in_array($r['rowKey'],$keys,true))$remaining+=(float)$r['outstanding'];if($remaining>$funds+.005)throw new DomainException('Selected dues exceed available bank funds. Untick bills or select more banks.');foreach($groups as &$g){$live=[];foreach(pl_raw_rows($s,$e,$mode) as $r)if(in_array($r['rowKey'],$g['rowKeys'],true))$live[]=$r['rowKey'];$g['originalRowKeys']=$g['rowKeys'];$g['rowKeys']=$live;}unset($g);
   $id=ss_next_id((array)($s['paymentPlans']??[]),'PLAN');$plan=['id'=>$id,'entity'=>$e,'mode'=>$mode,'bankIds'=>$banks,'groups'=>$groups,'status'=>'Open','version'=>1,'createdAt'=>gmdate('c'),'createdBy'=>pl_actor($u)];$s['paymentPlans'][$id]=$plan;pl_audit($s,$u,'PAYMENT_PLAN_CONFIRM',['planId'=>$id,'bankIds'=>$banks,'rowKeys'=>$keys,'adjustments'=>$adjusted]);$result=['plan'=>$plan];
  }else{
   $id=(string)($b['planId']??'');$plan=$s['paymentPlans'][$id]??null;if(!$plan||$plan['entity']!==$e||($plan['status']!=='Open'&&$action!=='reopen'))throw new DomainException('Open payment plan not found.');if((int)($b['version']??0)!==$plan['version'])throw new DomainException('This plan was changed by another user. Reopen it before continuing.');
   if(isset($b['drafts'])){$drafts=$b['drafts'];if(!is_array($drafts)||strlen(json_encode($drafts))>100000)throw new DomainException('Payment drafts are too large.');foreach($drafts as $group=>$draft)if(!isset($plan['groups'][$group])||!is_array($draft)||count((array)($draft['sources']??[]))>20)throw new DomainException('Invalid party draft.');$plan['drafts']=$drafts;}
   if($action==='reopen'){if($plan['status']!=='Closed')throw new DomainException('This plan is already open.');$reason=trim((string)($b['reason']??''));if($reason==='')throw new DomainException('Enter a reason for reopening this payment plan.');foreach((array)($s['paymentPlans']??[]) as $other)if($other['entity']===$e&&$other['mode']===$plan['mode']&&$other['status']==='Open')throw new DomainException('Finish the currently open payment plan before reopening this one.');$plan['status']='Open';$plan['reopenedAt']=gmdate('c');$plan['reopenedBy']=pl_actor($u);pl_audit($s,$u,'PAYMENT_PLAN_REOPEN',['planId'=>$id,'reason'=>$reason]);$result=[];}
   elseif($action==='post'){$set=pl_post($s,$u,$plan,$b);$result=['settlement'=>$set];unset($plan['drafts'][(string)$b['group']]);}
   elseif($action==='change'){$group=(string)($b['group']??'');$g=$plan['groups'][$group]??null;if(!$g||!empty($g['settlementId']))throw new DomainException('Correct a posted payment before changing its bills.');$keys=(array)($b['rowKeys']??[]);if($keys)pl_allocations($s,$e,$plan['mode'],$keys,$group);if(!$keys){if(!empty($g['adjustmentIds']))throw new DomainException('Correct applied advances before removing this party.');unset($plan['groups'][$group]);}else $plan['groups'][$group]['rowKeys']=$keys;pl_audit($s,$u,'PAYMENT_PLAN_SELECTION',['planId'=>$id,'group'=>$group,'rowKeys'=>$keys]);$result=[];}
   elseif($action==='correct'){$group=(string)($b['group']??'');$g=$plan['groups'][$group]??null;if(!$g)throw new DomainException('Party not found in this plan.');$reason=trim((string)($b['reason']??''));$date=ss_date((string)($b['date']??''));if(!empty($g['settlementId']))pl_reverse($s,$u,$e,$g['settlementId'],$date,$reason);foreach((array)($g['adjustmentIds']??[]) as $sid)if(($s['supplierSettlements'][$sid]['status']??'')==='Posted')pl_reverse($s,$u,$e,$sid,$date,$reason);$plan['groups'][$group]['settlementId']='';$plan['groups'][$group]['adjustmentIds']=[];unset($plan['groups'][$group]['voucher'],$plan['drafts'][$group]);$result=[];}
   elseif($action==='close'){foreach($plan['groups'] as $g){if(!empty($g['settlementId']))continue;$remaining=[];foreach(pl_raw_rows($s,$e,$plan['mode']) as $r)if(in_array($r['rowKey'],$g['rowKeys'],true))$remaining[]=$r;if($remaining)throw new DomainException('Post each selected party before closing this plan.');}$plan['status']='Closed';$plan['closedAt']=gmdate('c');$plan['closedBy']=pl_actor($u);pl_audit($s,$u,'PAYMENT_PLAN_CLOSE',['planId'=>$id]);$result=[];}
   else throw new DomainException('Unknown payment-plan action.');$plan['version']++;$s['paymentPlans'][$id]=$plan;$result['plan']=$plan;
  }
  $s['revision']=(int)($s['revision']??0)+1;$response=['ok'=>true,'result'=>$result,'revision'=>$s['revision']];$s['paymentPlanRequests'][$e.'|'.$key]=['fingerprint'=>$fingerprint,'response'=>$response];$encoded=json_encode($s,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);rewind($h);ftruncate($h,0);if(fwrite($h,$encoded)!==strlen($encoded))throw new RuntimeException('Payment storage write failed.');fflush($h);
 }finally{flock($h,LOCK_UN);fclose($h);}ss_respond($response);
}catch(DomainException $x){ss_respond(['ok'=>false,'error'=>$x->getMessage()],409);}catch(Throwable $x){error_log('Payment plan: '.$x->getMessage());ss_respond(['ok'=>false,'error'=>'Payment plan could not be committed.'],500);}
