<?php
declare(strict_types=1);
require dirname(__DIR__).'/auth_store.php';
header('Content-Type: application/json; charset=UTF-8');
header('Cache-Control: no-store, no-cache, must-revalidate');
const PS_FILE=TT_DATA_DIR.'/accounts.json';
function ps_out(array $x,int $s=200):never{http_response_code($s);echo json_encode($x,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function ps_can_write(array $u):bool{if(($u['role']??'')==='Super Admin')return true;$p=$u['permissions']['Accounts']??null;if($p==='all')return true;if(!is_array($p))return false;if(in_array('Create',$p,true)||in_array('Edit',$p,true)||in_array('Approve',$p,true))return true;foreach($p as $a)if(is_array($a)&&(in_array('Create',$a,true)||in_array('Edit',$a,true)||in_array('Approve',$a,true)))return true;return false;}
function ps_default():array{return ['revision'=>0,'events'=>[],'journals'=>[],'commodityBills'=>[],'supplierSettlements'=>[],'purchaseSodas'=>[]];}
function ps_read():array{tt_ensure_data_dir();if(!is_file(PS_FILE))return ps_default();$h=fopen(PS_FILE,'r');if($h===false||!flock($h,LOCK_SH))throw new RuntimeException('store');try{$raw=stream_get_contents($h);}finally{flock($h,LOCK_UN);fclose($h);} $s=$raw?json_decode($raw,true):null;return is_array($s)?array_replace_recursive(ps_default(),$s):ps_default();}
function ps_date(string $v,string $label):string{if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$v))ps_out(['ok'=>false,'error'=>$label.' is required.'],422);return $v;}
function ps_num(mixed $v,string $label,bool $zero=false):float{$n=round((float)$v,3);if($n<0||(!$zero&&$n<=0))ps_out(['ok'=>false,'error'=>$label.' is invalid.'],422);return $n;}
function ps_next_no(array $sodas):string{$yy=gmdate('y');$max=0;foreach($sodas as $s){$n=(string)($s['sodaNo']??'');if(preg_match('/^'.preg_quote($yy,'/').'(\d{3})$/',$n,$m))$max=max($max,(int)$m[1]);}return $yy.str_pad((string)($max+1),3,'0',STR_PAD_LEFT);}
function ps_paid_for_bill(array $store,string $billId):float{$t=0.0;foreach((array)($store['supplierSettlements']??[]) as $s){if(!is_array($s)||!in_array((string)($s['status']??''),['Posted','Approved / Posted'],true))continue;foreach((array)($s['allocations']??[]) as $a)if(is_array($a)&&(string)($a['billId']??'')===$billId)$t+=round((float)($a['amount']??0),2);}return round($t,2);}
function ps_rows(array $store,string $entity='TTI'):array{$out=[];foreach((array)($store['purchaseSodas']??[]) as $id=>$s){if(!is_array($s)||($s['entity']??'')!==$entity||($s['commodity']??'RICE')!=='RICE')continue;$no=(string)($s['sodaNo']??'');$receipts=[];$received=0.0;$unbilled=0;$billed=0.0;$paid=0.0;foreach((array)($store['events']??[]) as $ev){if(!is_array($ev)||($ev['eventType']??'')!=='COMMODITY_RECEIPT_ACCEPTED'||($ev['entity']??'')!==$entity)continue;$j=$store['journals'][$ev['journalId']??'']??null;if(!is_array($j))continue;$m=is_array($j['meta']??null)?$j['meta']:[];$commodity=strtoupper((string)($m['commodity']??''));if($commodity!==''&&$commodity!=='RICE')continue;if((string)($m['soda']??'')!==$no)continue;$kg=(float)($m['payableWeightKg']??0);$received+=$kg;$billId=(string)($ev['billId']??'');if($billId==='')$unbilled++;$receipts[]=['date'=>(string)($j['date']??''),'truck'=>(string)($m['truck']??''),'pohanch'=>(string)($m['pohanch']??$j['reference']??''),'kg'=>$kg,'billed'=>$billId!=='','billId'=>$billId];}
foreach((array)($store['commodityBills']??[]) as $bid=>$b){if(!is_array($b)||($b['entity']??'')!==$entity||!in_array($no,(array)($b['sodas']??[]),true))continue;$c=strtoupper((string)($b['commodity']??'RICE'));if($c!=='RICE')continue;$amt=(float)($b['supplierPayableTotal']??$b['finalCommodityValue']??0);$billed+=$amt;$paid+=ps_paid_for_bill($store,(string)$bid);} $from=(float)($s['qtyFromKg']??0);$to=(float)($s['qtyToKg']??$from);$status=(string)($s['status']??'Open');if(!in_array($status,['Completed','Short Closed','Cancelled'],true)){$status=$received<=0?'Open':($received<$from?'Part Received':($unbilled>0?'Received / Bill Pending':'Ready to Complete'));}$out[]=$s+['id'=>$id,'receivedKg'=>round($received,3),'balanceToMinKg'=>round(max(0,$from-$received),3),'balanceToMaxKg'=>round(max(0,$to-$received),3),'trucksReceived'=>count($receipts),'unbilledArrivals'=>$unbilled,'billedAmount'=>round($billed,2),'paidAmount'=>round($paid,2),'payableOutstanding'=>round(max(0,$billed-$paid),2),'calculatedStatus'=>$status,'receipts'=>$receipts];}usort($out,static fn($a,$b)=>strcmp((string)($b['sodaDate']??''),(string)($a['sodaDate']??''))?:strcmp((string)($b['sodaNo']??''),(string)($a['sodaNo']??'')));return $out;}
try{$u=tt_require_login();if(!tt_user_can_open_module($u,'Accounts'))ps_out(['ok'=>false,'error'=>'Accounts permission required.'],403);if($_SERVER['REQUEST_METHOD']==='GET'){$e=strtoupper(trim((string)($_GET['entity']??'TTI')));if(!in_array($e,['TTI','BRM'],true))ps_out(['ok'=>false,'error'=>'Invalid entity.'],422);$s=ps_read();ps_out(['ok'=>true,'sodas'=>ps_rows($s,$e),'nextSodaNo'=>ps_next_no((array)$s['purchaseSodas'])]);}
if($_SERVER['REQUEST_METHOD']!=='POST')ps_out(['ok'=>false,'error'=>'Method not allowed.'],405);if(!ps_can_write($u))ps_out(['ok'=>false,'error'=>'Accounts Create/Edit permission required.'],403);$b=json_decode(file_get_contents('php://input')?:'',true);if(!is_array($b)||!tt_verify_csrf((string)($b['csrf']??'')))ps_out(['ok'=>false,'error'=>'Session expired. Refresh and try again.'],419);$action=(string)($b['action']??'');$entity=strtoupper(trim((string)($b['entity']??'TTI')));if(!in_array($entity,['TTI','BRM'],true))ps_out(['ok'=>false,'error'=>'Invalid entity.'],422);
tt_ensure_data_dir();$h=fopen(PS_FILE,'c+');if($h===false||!flock($h,LOCK_EX))throw new RuntimeException('store');try{rewind($h);$raw=stream_get_contents($h);$store=$raw?json_decode($raw,true):null;if(!is_array($store))$store=ps_default();$store=array_replace_recursive(ps_default(),$store);if($action==='create'){$date=ps_date((string)($b['sodaDate']??''),'Soda date');$broker=trim((string)($b['broker']??''));$party=trim((string)($b['party']??''));$variety=trim((string)($b['variety']??''));if($broker===''||$variety==='')ps_out(['ok'=>false,'error'=>'Broker and Rice variety are required.'],422);$from=ps_num($b['qtyFromMT']??0,'Quantity from')*1000;$to=ps_num($b['qtyToMT']??$b['qtyFromMT']??0,'Quantity to')*1000;if($to<$from)ps_out(['ok'=>false,'error'=>'Maximum Soda quantity cannot be below minimum quantity.'],422);$trucks=(int)($b['expectedTrucks']??0);if($trucks<1||$trucks>999)ps_out(['ok'=>false,'error'=>'Expected trucks are required.'],422);$rate=ps_num($b['ratePerKg']??0,'Rate per kg');$deadline=ps_date((string)($b['deliveryDeadline']??''),'Delivery deadline');$credit=(int)($b['creditDays']??0);if($credit<0||$credit>120)ps_out(['ok'=>false,'error'=>'Credit days must be between 0 and 120.'],422);$no=ps_next_no((array)$store['purchaseSodas']);$id='PS-RICE-'.$no;$store['purchaseSodas'][$id]=['id'=>$id,'entity'=>$entity,'commodity'=>'RICE','sodaNo'=>$no,'sodaDate'=>$date,'broker'=>$broker,'party'=>$party,'variety'=>$variety,'qtyFromKg'=>$from,'qtyToKg'=>$to,'expectedTrucks'=>$trucks,'ratePerKg'=>$rate,'creditDays'=>$credit,'deliveryDeadline'=>$deadline,'terms'=>trim((string)($b['terms']??'')),'remarks'=>trim((string)($b['remarks']??'')),'status'=>'Open','createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??$u['username']??'Accounts')];}
elseif($action==='set_status'){$id=(string)($b['id']??'');$new=(string)($b['status']??'');if(!in_array($new,['Open','Completed','Short Closed','Cancelled'],true))ps_out(['ok'=>false,'error'=>'Invalid Soda status.'],422);$row=$store['purchaseSodas'][$id]??null;if(!is_array($row)||($row['entity']??'')!==$entity||($row['commodity']??'')!=='RICE')ps_out(['ok'=>false,'error'=>'Rice Soda not found.'],404);if($new==='Completed'){foreach(ps_rows($store,$entity) as $r)if(($r['id']??'')===$id){if(($r['unbilledArrivals']??0)>0)ps_out(['ok'=>false,'error'=>'This Soda still has unbilled arrivals.'],422);if(($r['receivedKg']??0)<($r['qtyFromKg']??0))ps_out(['ok'=>false,'error'=>'Received quantity is below the Soda minimum. Use Short Close if approved.'],422);}}$store['purchaseSodas'][$id]['status']=$new;$store['purchaseSodas'][$id]['statusChangedAt']=gmdate('c');$store['purchaseSodas'][$id]['statusChangedBy']=(string)($u['full_name']??$u['username']??'Accounts');}
else ps_out(['ok'=>false,'error'=>'Unknown action.'],422);$store['revision']=(int)($store['revision']??0)+1;rewind($h);ftruncate($h,0);fwrite($h,json_encode($store,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($h);}finally{flock($h,LOCK_UN);fclose($h);}ps_out(['ok'=>true,'sodas'=>ps_rows($store,$entity),'nextSodaNo'=>ps_next_no((array)$store['purchaseSodas'])]);}catch(Throwable $e){ps_out(['ok'=>false,'error'=>'Rice Soda control is temporarily unavailable.'],500);}