<?php
declare(strict_types=1);
require dirname(__DIR__) . '/auth_store.php';
header('Content-Type: application/json; charset=UTF-8');
header('Cache-Control: no-store, no-cache, must-revalidate');

const RSV2_FILE = TT_DATA_DIR . '/accounts.json';
const RSV2_MASTER = __DIR__ . '/../accounts/accounting_master_v1.json';

function rsv2_out(array $d,int $s=200):never{http_response_code($s);echo json_encode($d,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function rsv2_can_write(array $u):bool{if(($u['role']??'')==='Super Admin')return true;$p=$u['permissions']['Accounts']??null;if($p==='all')return true;if(!is_array($p))return false;if(in_array('Create',$p,true)||in_array('Edit',$p,true)||in_array('Approve',$p,true))return true;foreach($p as $a)if(is_array($a)&&(in_array('Create',$a,true)||in_array('Edit',$a,true)||in_array('Approve',$a,true)))return true;return false;}
function rsv2_def():array{return ['revision'=>0,'journals'=>[],'bankAccountSettings'=>[],'salaryMasters'=>[],'rentMasters'=>[],'salaryPeriods'=>[],'rentPeriods'=>[],'salaryAdvances'=>[],'rentPrepayments'=>[],'rentSalaryPayments'=>[]];}
function rsv2_read():array{tt_ensure_data_dir();if(!is_file(RSV2_FILE))return rsv2_def();$h=fopen(RSV2_FILE,'r');if($h===false||!flock($h,LOCK_SH))throw new RuntimeException('Accounts storage unavailable.');try{$raw=stream_get_contents($h);}finally{flock($h,LOCK_UN);fclose($h);}$v=$raw?json_decode($raw,true):null;return is_array($v)?array_replace_recursive(rsv2_def(),$v):rsv2_def();}
function rsv2_entity(string $v):string{$v=strtoupper(trim($v));if(!in_array($v,['TTI','BRM'],true))rsv2_out(['ok'=>false,'error'=>'Salary and mill rent are available for TTI / BRM.'],422);return $v;}
function rsv2_date(string $v,string $label='Date'):string{if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$v))rsv2_out(['ok'=>false,'error'=>$label.' is required.'],422);return $v;}
function rsv2_month(string $v):string{if(!preg_match('/^\d{4}-\d{2}$/',$v))rsv2_out(['ok'=>false,'error'=>'Select a valid month.'],422);return $v;}
function rsv2_amt(mixed $v,string $label='Amount'):float{$n=round((float)$v,2);if($n<=0)rsv2_out(['ok'=>false,'error'=>$label.' must be greater than zero.'],422);return $n;}
function rsv2_mstart(string $m):string{return $m.'-01';}
function rsv2_mend(string $m):string{return (new DateTimeImmutable($m.'-01'))->modify('last day of this month')->format('Y-m-d');}
function rsv2_prev_day(string $d):string{return (new DateTimeImmutable($d))->modify('-1 day')->format('Y-m-d');}
function rsv2_next(array $items,string $p):string{$n=count($items)+1;do{$id=$p.'-'.gmdate('Y').'-'.str_pad((string)$n,6,'0',STR_PAD_LEFT);$n++;}while(isset($items[$id]));return $id;}
function rsv2_norm(string $v):string{return strtoupper(trim(preg_replace('/\s+/',' ',trim($v))??$v));}
function rsv2_names():array{$raw=is_file(RSV2_MASTER)?file_get_contents(RSV2_MASTER):false;$m=$raw?json_decode($raw,true):null;if(!is_array($m))throw new RuntimeException('Accounting master unavailable.');$o=[];foreach((array)($m['chart']??[]) as $a)if(is_array($a)&&isset($a['code']))$o[(string)$a['code']]=(string)($a['name']??$a['code']);return $o;}
function rsv2_line(string $a,float $dr,float $cr,array $names,array $extra=[]):array{if(!isset($names[$a]))rsv2_out(['ok'=>false,'error'=>'Approved account '.$a.' is unavailable.'],422);return array_merge(['account'=>$a,'accountName'=>$names[$a],'debit'=>round($dr,2),'credit'=>round($cr,2)],$extra);}
function rsv2_active(array $m,string $month):bool{if(($m['status']??'Active')!=='Active')return false;$from=(string)($m['effectiveFrom']??'');$to=(string)($m['effectiveTo']??'');$ms=rsv2_mstart($month);$me=rsv2_mend($month);return ($from===''||$from<=$me)&&($to===''||$to>=$ms);}
function rsv2_cat(string $v):string{$v=strtoupper(trim($v));$ok=['MILL_STAFF','OFFICE_STAFF','HOME_STAFF','DIRECTOR_REMUNERATION','HOME_MONTHLY_GIVE'];if(!in_array($v,$ok,true))rsv2_out(['ok'=>false,'error'=>'Select a valid salary category.'],422);return $v;}
function rsv2_cat_name(string $v):string{return match($v){'MILL_STAFF'=>'Mill Staff','OFFICE_STAFF'=>'Office Staff','HOME_STAFF'=>'Home Staff','DIRECTOR_REMUNERATION'=>'Director Remuneration','HOME_MONTHLY_GIVE'=>'Home Monthly Give',default=>$v};}
function rsv2_default_treatment(string $cat):string{return match($cat){'MILL_STAFF','OFFICE_STAFF','HOME_STAFF'=>'STAFF_COST','HOME_MONTHLY_GIVE'=>'FAMILY_ALLOCATION',default=>'TO_CONFIRM'};}
function rsv2_treatment(string $v,string $cat):string{$v=strtoupper(trim($v));if($v==='')$v=rsv2_default_treatment($cat);if(!in_array($v,['STAFF_COST','FAMILY_ALLOCATION','TO_CONFIRM'],true))rsv2_out(['ok'=>false,'error'=>'Select a valid accounting treatment.'],422);return $v;}
function rsv2_expense_account(string $t):string{return $t==='FAMILY_ALLOCATION'?'3200':'6200';}
function rsv2_banks():array{$masters=tt_list_masters();$out=[];foreach((array)($masters['banks']??[]) as $row){if(!is_array($row))continue;$v=array_values((array)($row['values']??[]));while(count($v)<14)$v[]='';$linked=strtoupper((string)$v[1]);$entity=str_contains($linked,'BRM')||str_contains($linked,'BUKSH RICE')?'BRM':(str_contains($linked,'TTI')||str_contains($linked,'TRANSTRADE INTERNATIONAL')?'TTI':'');if($entity==='')continue;$out[(string)($row['id']??'')]=['id'=>(string)($row['id']??''),'entity'=>$entity,'accountType'=>(string)$v[0],'accountTitle'=>(string)$v[3],'bankName'=>(string)$v[4],'currency'=>strtoupper(trim((string)$v[7])),'accountNumber'=>(string)$v[8]];}return $out;}
function rsv2_bank_bal(array $s,string $entity,string $id):float{$n=0;foreach((array)$s['journals'] as $j){if(!is_array($j)||($j['status']??'')!=='Posted'||($j['entity']??'')!==$entity)continue;$jm=is_array($j['meta']??null)?$j['meta']:[];foreach((array)($j['lines']??[]) as $l){if(!is_array($l)||($l['account']??'')!=='1110')continue;if((string)($l['bankAccountId']??$jm['bankAccountId']??'')===$id)$n+=(float)($l['debit']??0)-(float)($l['credit']??0);}}return round($n,2);}
function rsv2_cash_bal(array $s,string $entity):float{$n=0;foreach((array)$s['journals'] as $j){if(!is_array($j)||($j['status']??'')!=='Posted'||($j['entity']??'')!==$entity)continue;foreach((array)($j['lines']??[]) as $l)if(is_array($l)&&($l['account']??'')==='1120')$n+=(float)($l['debit']??0)-(float)($l['credit']??0);}return round($n,2);}
function rsv2_payment_accounts(array $s,string $entity):array{$o=[];foreach(rsv2_banks() as $id=>$a){if(($a['entity']??'')!==$entity||($a['accountType']??'')!=='Company Account'||($a['currency']??'')!=='PKR')continue;$set=is_array($s['bankAccountSettings'][$id]??null)?$s['bankAccountSettings'][$id]:[];if(empty($set['active'])||empty($set['allowPayments']))continue;$digits=preg_replace('/\D+/','',(string)$a['accountNumber'])??'';$o[]=['id'=>$id,'type'=>'BANK','label'=>trim((string)$a['bankName']).($digits!==''?' — '.substr($digits,-5):''),'bookBalance'=>rsv2_bank_bal($s,$entity,$id)];}$cash='CASH|'.$entity;$set=is_array($s['bankAccountSettings'][$cash]??null)?$s['bankAccountSettings'][$cash]:['active'=>true,'allowPayments'=>true];if(!empty($set['active'])&&!empty($set['allowPayments']))$o[]=['id'=>$cash,'type'=>'CASH','label'=>'Cash / Petty Cash','bookBalance'=>rsv2_cash_bal($s,$entity)];return $o;}
function rsv2_pay_line(array $s,string $entity,string $id,float $amt,array $names):array{if($id==='CASH|'.$entity)return rsv2_line('1120',0,$amt,$names,['paymentAccountId'=>$id,'paymentType'=>'Cash']);$a=rsv2_banks()[$id]??null;if(!is_array($a)||($a['entity']??'')!==$entity||($a['accountType']??'')!=='Company Account'||($a['currency']??'')!=='PKR')rsv2_out(['ok'=>false,'error'=>'Select a valid PKR company bank account.'],422);$set=is_array($s['bankAccountSettings'][$id]??null)?$s['bankAccountSettings'][$id]:[];if(empty($set['active'])||empty($set['allowPayments']))rsv2_out(['ok'=>false,'error'=>'This bank account is not enabled for payments.'],422);return rsv2_line('1110',0,$amt,$names,['bankAccountId'=>$id,'bankName'=>$a['bankName'],'accountTitle'=>$a['accountTitle'],'currency'=>'PKR']);}
function rsv2_journal(array &$s,string $entity,string $date,string $source,string $ref,string $narr,array $lines,array $u,array $meta=[]):string{$dr=round(array_sum(array_map(static fn($l)=>(float)($l['debit']??0),$lines)),2);$cr=round(array_sum(array_map(static fn($l)=>(float)($l['credit']??0),$lines)),2);if(abs($dr-$cr)>.005)throw new RuntimeException('Journal did not balance.');$id=rsv2_next((array)$s['journals'],'AUTO');$s['journals'][$id]=['id'=>$id,'entity'=>$entity,'date'=>$date,'sourceType'=>$source,'reference'=>$ref,'narration'=>$narr,'lines'=>$lines,'totalDebit'=>$dr,'totalCredit'=>$cr,'status'=>'Posted','meta'=>$meta,'createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??$u['username']??'Accounts'),'userId'=>(int)($u['id']??0),'reversalOf'=>null];return $id;}
function rsv2_pid(string $entity,string $month,string $master):string{return $entity.'|'.$month.'|'.$master;}
function rsv2_advances(array $s,string $master,string $month):array{$o=[];foreach((array)$s['salaryAdvances'] as $id=>$a)if(is_array($a)&&($a['salaryMasterId']??'')===$master&&($a['month']??'')===$month)$o[$id]=$a;return $o;}
function rsv2_advance_remaining(array $s,string $master,string $month):float{$n=0;foreach(rsv2_advances($s,$master,$month) as $a)$n+=(float)($a['remaining']??($a['applied']??false?0:$a['amount']??0));return round($n,2);}
function rsv2_salary_row(array $s,array $m,string $month):array{$pid=rsv2_pid((string)$m['entity'],$month,(string)$m['id']);$p=is_array($s['salaryPeriods'][$pid]??null)?$s['salaryPeriods'][$pid]:null;$paidAdv=0;foreach(rsv2_advances($s,(string)$m['id'],$month) as $a)$paidAdv+=(float)($a['amount']??0);return ['periodId'=>$pid,'masterId'=>$m['id'],'name'=>$m['name'],'category'=>$m['category'],'categoryName'=>rsv2_cat_name((string)$m['category']),'accountingTreatment'=>$m['accountingTreatment']??rsv2_default_treatment((string)$m['category']),'month'=>$month,'gross'=>(float)$m['monthlyAmount'],'advancePaid'=>round($paidAdv,2),'prepared'=>$p!==null,'appliedAdvance'=>(float)($p['appliedAdvance']??0),'paidAfterPrepare'=>(float)($p['paidAfterPrepare']??0),'outstanding'=>(float)($p['outstanding']??0),'productionCostEligible'=>(bool)($m['productionCostEligible']??false),'status'=>$p['status']??(($m['accountingTreatment']??'')==='TO_CONFIRM'?'Treatment Required':'Not Prepared')];}
function rsv2_rent_row(array $s,array $m,string $month):array{$pid=rsv2_pid((string)$m['entity'],$month,(string)$m['id']);$p=is_array($s['rentPeriods'][$pid]??null)?$s['rentPeriods'][$pid]:null;return ['periodId'=>$pid,'masterId'=>$m['id'],'mill'=>$m['mill'],'payee'=>$m['payee'],'month'=>$month,'monthlyAmount'=>(float)$m['monthlyAmount'],'paymentPattern'=>$m['paymentPattern'],'prepared'=>$p!==null,'prepaidUsed'=>(float)($p['prepaidUsed']??0),'paidAfterPrepare'=>(float)($p['paidAfterPrepare']??0),'outstanding'=>(float)($p['outstanding']??0),'productionCostEligible'=>(bool)($m['productionCostEligible']??true),'status'=>$p['status']??'Not Prepared'];}
function rsv2_payload(array $s,string $entity,string $month):array{$sal=[];$rent=[];foreach((array)$s['salaryMasters'] as $m)if(is_array($m)&&($m['entity']??'')===$entity&&rsv2_active($m,$month))$sal[]=rsv2_salary_row($s,$m,$month);foreach((array)$s['rentMasters'] as $m)if(is_array($m)&&($m['entity']??'')===$entity&&rsv2_active($m,$month))$rent[]=rsv2_rent_row($s,$m,$month);usort($sal,static fn($a,$b)=>strcmp((string)$a['categoryName'],(string)$b['categoryName'])?:strcmp((string)$a['name'],(string)$b['name']));usort($rent,static fn($a,$b)=>strcmp((string)$a['mill'],(string)$b['mill']));return ['ok'=>true,'entity'=>$entity,'month'=>$month,'salaryMasters'=>array_values(array_filter((array)$s['salaryMasters'],static fn($m)=>is_array($m)&&($m['entity']??'')===$entity)),'rentMasters'=>array_values(array_filter((array)$s['rentMasters'],static fn($m)=>is_array($m)&&($m['entity']??'')===$entity)),'salaryRows'=>$sal,'rentRows'=>$rent,'paymentAccounts'=>rsv2_payment_accounts($s,$entity),'serverNow'=>gmdate('c')];}
function rsv2_close_old_salary(array &$s,string $entity,string $name,string $cat,string $from):void{foreach($s['salaryMasters'] as &$m){if(!is_array($m)||($m['entity']??'')!==$entity||rsv2_norm((string)($m['name']??''))!==rsv2_norm($name)||($m['category']??'')!==$cat||($m['status']??'Active')!=='Active')continue;$oldFrom=(string)($m['effectiveFrom']??'');$oldTo=(string)($m['effectiveTo']??'');if($oldFrom!==''&&$oldFrom<$from&&($oldTo===''||$oldTo>=$from))$m['effectiveTo']=rsv2_prev_day($from);}unset($m);}
function rsv2_close_old_rent(array &$s,string $entity,string $mill,string $payee,string $from):void{foreach($s['rentMasters'] as &$m){if(!is_array($m)||($m['entity']??'')!==$entity||rsv2_norm((string)($m['mill']??''))!==rsv2_norm($mill)||rsv2_norm((string)($m['payee']??''))!==rsv2_norm($payee)||($m['status']??'Active')!=='Active')continue;$oldFrom=(string)($m['effectiveFrom']??'');$oldTo=(string)($m['effectiveTo']??'');if($oldFrom!==''&&$oldFrom<$from&&($oldTo===''||$oldTo>=$from))$m['effectiveTo']=rsv2_prev_day($from);}unset($m);}
function rsv2_prepare(array &$s,string $entity,string $month,array $u,array $names):array{$date=rsv2_mend($month);$sc=0;$rc=0;$warnings=[];foreach((array)$s['salaryMasters'] as $mid=>$m){if(!is_array($m)||($m['entity']??'')!==$entity||!rsv2_active($m,$month))continue;$pid=rsv2_pid($entity,$month,(string)$mid);if(isset($s['salaryPeriods'][$pid]))continue;$t=(string)($m['accountingTreatment']??rsv2_default_treatment((string)$m['category']));if($t==='TO_CONFIRM'){$warnings[]='Choose accounting treatment for '.(string)$m['name'];continue;}$gross=round((float)$m['monthlyAmount'],2);if($gross<=0)continue;$meta=['salaryMasterId'=>$mid,'month'=>$month,'person'=>$m['name'],'category'=>$m['category'],'accountingTreatment'=>$t,'productionCostEligible'=>(bool)($m['productionCostEligible']??false)];$expense=rsv2_expense_account($t);$jid=rsv2_journal($s,$entity,$date,'SALARY_MONTHLY_ACCRUAL','SAL-'.$month.'-'.$mid,(string)$m['name'].' — '.$month,[rsv2_line($expense,$gross,0,$names,$meta),rsv2_line('2140',0,$gross,$names,$meta)],$u,$meta);$apply=0;$ids=[];foreach(rsv2_advances($s,(string)$mid,$month) as $aid=>$a){$remaining=(float)($a['remaining']??($a['applied']??false?0:$a['amount']??0));if($remaining<=.005)continue;$use=min($remaining,max(0,$gross-$apply));if($use<=.005)break;$apply=round($apply+$use,2);$s['salaryAdvances'][$aid]['remaining']=round($remaining-$use,2);$s['salaryAdvances'][$aid]['appliedAmount']=round((float)($a['appliedAmount']??0)+$use,2);$s['salaryAdvances'][$aid]['applied']=$s['salaryAdvances'][$aid]['remaining']<=.005;$ids[]=$aid;}$clear=null;if($apply>0)$clear=rsv2_journal($s,$entity,$date,'SALARY_ADVANCE_APPLIED','SALADV-'.$month.'-'.$mid,'Apply advance — '.(string)$m['name'].' — '.$month,[rsv2_line('2140',$apply,0,$names,$meta),rsv2_line('1230',0,$apply,$names,$meta)],$u,$meta+['advanceIds'=>$ids]);$out=round($gross-$apply,2);$s['salaryPeriods'][$pid]=['id'=>$pid,'entity'=>$entity,'month'=>$month,'salaryMasterId'=>$mid,'name'=>$m['name'],'category'=>$m['category'],'accountingTreatment'=>$t,'gross'=>$gross,'appliedAdvance'=>$apply,'paidAfterPrepare'=>0,'outstanding'=>$out,'journalId'=>$jid,'advanceClearJournalId'=>$clear,'productionCostEligible'=>(bool)($m['productionCostEligible']??false),'status'=>$out>.005?'Payable':'Paid / Cleared','preparedAt'=>gmdate('c'),'preparedBy'=>(string)($u['full_name']??'Accounts')];$sc++;}
foreach((array)$s['rentMasters'] as $mid=>$m){if(!is_array($m)||($m['entity']??'')!==$entity||!rsv2_active($m,$month))continue;$pid=rsv2_pid($entity,$month,(string)$mid);if(isset($s['rentPeriods'][$pid]))continue;$gross=round((float)$m['monthlyAmount'],2);if($gross<=0)continue;$key=$mid.'|'.$month;$pre=is_array($s['rentPrepayments'][$key]??null)?$s['rentPrepayments'][$key]:null;$avail=(float)($pre['remaining']??0);$use=min($gross,max(0,$avail));$payable=round($gross-$use,2);$meta=['rentMasterId'=>$mid,'month'=>$month,'mill'=>$m['mill'],'payee'=>$m['payee'],'productionCostEligible'=>(bool)($m['productionCostEligible']??true)];$lines=[rsv2_line('6300',$gross,0,$names,$meta)];if($use>0)$lines[]=rsv2_line('1400',0,$use,$names,$meta+['prepaidRent'=>true]);if($payable>0)$lines[]=rsv2_line('2140',0,$payable,$names,$meta);$jid=rsv2_journal($s,$entity,$date,'RENT_MONTHLY_ACCRUAL','RENT-'.$month.'-'.$mid,'Mill rent — '.$month.' — '.(string)$m['mill'],$lines,$u,$meta);if($use>0){$s['rentPrepayments'][$key]['remaining']=round($avail-$use,2);$s['rentPrepayments'][$key]['used']=round((float)($pre['used']??0)+$use,2);}$s['rentPeriods'][$pid]=['id'=>$pid,'entity'=>$entity,'month'=>$month,'rentMasterId'=>$mid,'mill'=>$m['mill'],'payee'=>$m['payee'],'gross'=>$gross,'prepaidUsed'=>$use,'paidAfterPrepare'=>0,'outstanding'=>$payable,'journalId'=>$jid,'productionCostEligible'=>(bool)($m['productionCostEligible']??true),'status'=>$payable>.005?'Payable':'Paid / Prepaid','preparedAt'=>gmdate('c'),'preparedBy'=>(string)($u['full_name']??'Accounts')];$rc++;}return ['salaryPrepared'=>$sc,'rentPrepared'=>$rc,'warnings'=>$warnings];}
function rsv2_months(string $from,string $to):array{rsv2_month($from);rsv2_month($to);if($to<$from)rsv2_out(['ok'=>false,'error'=>'Rent To Month cannot be before From Month.'],422);$o=[];$d=new DateTimeImmutable($from.'-01');$end=new DateTimeImmutable($to.'-01');while($d<=$end&&count($o)<60){$o[]=$d->format('Y-m');$d=$d->modify('+1 month');}return $o;}

try{
$u=tt_require_login();if(!tt_user_can_open_module($u,'Accounts'))rsv2_out(['ok'=>false,'error'=>'Accounts permission required.'],403);$entity=rsv2_entity((string)($_GET['entity']??'TTI'));$month=rsv2_month((string)($_GET['month']??gmdate('Y-m')));if($_SERVER['REQUEST_METHOD']==='GET')rsv2_out(rsv2_payload(rsv2_read(),$entity,$month));if($_SERVER['REQUEST_METHOD']!=='POST')rsv2_out(['ok'=>false,'error'=>'Method not allowed.'],405);if(!rsv2_can_write($u))rsv2_out(['ok'=>false,'error'=>'Accounts Create, Edit or Approve permission required.'],403);$b=json_decode(file_get_contents('php://input')?:'{}',true);if(!is_array($b)||!tt_verify_csrf((string)($b['csrf']??'')))rsv2_out(['ok'=>false,'error'=>'Your session expired. Refresh and try again.'],419);$action=(string)($b['action']??'');tt_ensure_data_dir();$h=fopen(RSV2_FILE,'c+');if($h===false||!flock($h,LOCK_EX))throw new RuntimeException('Accounts storage unavailable.');try{rewind($h);$raw=stream_get_contents($h);$s=$raw?json_decode($raw,true):null;if(!is_array($s))$s=rsv2_def();$s=array_replace_recursive(rsv2_def(),$s);$names=rsv2_names();$entity=rsv2_entity((string)($b['entity']??$entity));$month=rsv2_month((string)($b['month']??$month));
if($action==='save_salary_master'){$name=trim((string)($b['name']??''));if($name==='')rsv2_out(['ok'=>false,'error'=>'Name is required.'],422);$cat=rsv2_cat((string)($b['category']??''));$amt=rsv2_amt($b['monthlyAmount']??0,'Monthly amount');$from=rsv2_date((string)($b['effectiveFrom']??''),'Start date');$to=trim((string)($b['effectiveTo']??''));if($to!=='')$to=rsv2_date($to,'End date');$t=rsv2_treatment((string)($b['accountingTreatment']??''),$cat);rsv2_close_old_salary($s,$entity,$name,$cat,$from);$id=rsv2_next((array)$s['salaryMasters'],'SALM');$s['salaryMasters'][$id]=['id'=>$id,'entity'=>$entity,'name'=>$name,'category'=>$cat,'monthlyAmount'=>$amt,'effectiveFrom'=>$from,'effectiveTo'=>$to,'accountingTreatment'=>$t,'productionCostEligible'=>$cat==='MILL_STAFF'&&$t==='STAFF_COST'?(bool)($b['productionCostEligible']??true):false,'status'=>'Active','notes'=>trim((string)($b['notes']??'')),'createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??'Accounts')];$result=['masterId'=>$id,'accountingTreatment'=>$t];}
elseif($action==='save_rent_master'){$mill=trim((string)($b['mill']??''));$payee=trim((string)($b['payee']??''));if($mill===''||$payee==='')rsv2_out(['ok'=>false,'error'=>'Mill / location and payee are required.'],422);$amt=rsv2_amt($b['monthlyAmount']??0,'Monthly rent');$from=rsv2_date((string)($b['effectiveFrom']??''),'Start date');$to=trim((string)($b['effectiveTo']??''));if($to!=='')$to=rsv2_date($to,'End date');$pattern=(string)($b['paymentPattern']??'Monthly');if(!in_array($pattern,['Monthly','Quarterly','Half-Yearly','Twice-Yearly','Other'],true))$pattern='Other';rsv2_close_old_rent($s,$entity,$mill,$payee,$from);$id=rsv2_next((array)$s['rentMasters'],'RENTM');$s['rentMasters'][$id]=['id'=>$id,'entity'=>$entity,'mill'=>$mill,'payee'=>$payee,'monthlyAmount'=>$amt,'paymentPattern'=>$pattern,'effectiveFrom'=>$from,'effectiveTo'=>$to,'productionCostEligible'=>(bool)($b['productionCostEligible']??true),'status'=>'Active','notes'=>trim((string)($b['notes']??'')),'createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??'Accounts')];$result=['masterId'=>$id];}
elseif($action==='prepare_month'){$result=rsv2_prepare($s,$entity,$month,$u,$names);}
elseif($action==='salary_advance'){$mid=trim((string)($b['masterId']??''));$m=$s['salaryMasters'][$mid]??null;if(!is_array($m)||($m['entity']??'')!==$entity)rsv2_out(['ok'=>false,'error'=>'Select a salary master.'],422);$amt=rsv2_amt($b['amount']??0);$date=rsv2_date((string)($b['date']??''));$payId=trim((string)($b['paymentAccountId']??''));$pid=rsv2_pid($entity,$month,$mid);$p=$s['salaryPeriods'][$pid]??null;$meta=['salaryMasterId'=>$mid,'month'=>$month,'person'=>$m['name'],'category'=>$m['category']];if(is_array($p)){if($amt>(float)$p['outstanding']+.005)rsv2_out(['ok'=>false,'error'=>'Amount is more than the salary balance for this month.'],422);$jid=rsv2_journal($s,$entity,$date,'SALARY_PAYMENT','SALPAY-'.$pid,'Salary payment — '.$m['name'].' — '.$month,[rsv2_line('2140',$amt,0,$names,$meta),rsv2_pay_line($s,$entity,$payId,$amt,$names)],$u,$meta);$s['salaryPeriods'][$pid]['paidAfterPrepare']=round((float)$p['paidAfterPrepare']+$amt,2);$s['salaryPeriods'][$pid]['outstanding']=round((float)$p['outstanding']-$amt,2);$s['salaryPeriods'][$pid]['status']=$s['salaryPeriods'][$pid]['outstanding']>.005?'Part Paid':'Paid / Cleared';$type='PAYMENT';}else{$existing=rsv2_advance_remaining($s,$mid,$month);if($existing+$amt>(float)$m['monthlyAmount']+.005)rsv2_out(['ok'=>false,'error'=>'Advance would be more than this month’s salary amount.'],422);$jid=rsv2_journal($s,$entity,$date,'SALARY_ADVANCE','SALADV-'.$mid.'-'.$month,'Salary advance — '.$m['name'].' — '.$month,[rsv2_line('1230',$amt,0,$names,$meta+['staffAdvance'=>true]),rsv2_pay_line($s,$entity,$payId,$amt,$names)],$u,$meta);$aid=rsv2_next((array)$s['salaryAdvances'],'SADV');$s['salaryAdvances'][$aid]=['id'=>$aid,'entity'=>$entity,'salaryMasterId'=>$mid,'month'=>$month,'date'=>$date,'amount'=>$amt,'remaining'=>$amt,'appliedAmount'=>0,'journalId'=>$jid,'applied'=>false,'createdAt'=>gmdate('c')];$type='ADVANCE';}$result=['journalId'=>$jid,'type'=>$type];}
elseif($action==='pay_rent'){$mid=trim((string)($b['masterId']??''));$m=$s['rentMasters'][$mid]??null;if(!is_array($m)||($m['entity']??'')!==$entity)rsv2_out(['ok'=>false,'error'=>'Select a rent master.'],422);$months=rsv2_months((string)($b['fromMonth']??''),(string)($b['toMonth']??''));$amt=rsv2_amt($b['amount']??0);$date=rsv2_date((string)($b['date']??''));$payId=trim((string)($b['paymentAccountId']??''));$cover=0;foreach($months as $mo){$pid=rsv2_pid($entity,$mo,$mid);$p=$s['rentPeriods'][$pid]??null;if(is_array($p))$cover+=max(0,(float)($p['outstanding']??0));else{$key=$mid.'|'.$mo;$pre=(float)($s['rentPrepayments'][$key]['remaining']??0);$cover+=max(0,(float)$m['monthlyAmount']-$pre);}}$cover=round($cover,2);if($amt>$cover+.005)rsv2_out(['ok'=>false,'error'=>'Payment is more than the remaining rent for the selected months. Add the additional month(s) it covers.'],422);$left=$amt;$pd=0;$preD=0;$alloc=[];foreach($months as $mo){if($left<=.005)break;$pid=rsv2_pid($entity,$mo,$mid);$p=$s['rentPeriods'][$pid]??null;if(is_array($p)){$use=min($left,max(0,(float)$p['outstanding']));if($use<=.005)continue;$pd+=$use;$s['rentPeriods'][$pid]['paidAfterPrepare']=round((float)$p['paidAfterPrepare']+$use,2);$s['rentPeriods'][$pid]['outstanding']=round((float)$p['outstanding']-$use,2);$s['rentPeriods'][$pid]['status']=$s['rentPeriods'][$pid]['outstanding']>.005?'Part Paid':'Paid / Cleared';$alloc[]=['month'=>$mo,'payable'=>$use,'prepaid'=>0,'amount'=>$use];$left=round($left-$use,2);}else{$key=$mid.'|'.$mo;$existing=(float)($s['rentPrepayments'][$key]['remaining']??0);$space=max(0,(float)$m['monthlyAmount']-$existing);$use=min($left,$space);if($use<=.005)continue;$preD+=$use;if(!isset($s['rentPrepayments'][$key]))$s['rentPrepayments'][$key]=['id'=>$key,'entity'=>$entity,'rentMasterId'=>$mid,'month'=>$mo,'amount'=>0,'remaining'=>0,'used'=>0];$s['rentPrepayments'][$key]['amount']=round((float)$s['rentPrepayments'][$key]['amount']+$use,2);$s['rentPrepayments'][$key]['remaining']=round((float)$s['rentPrepayments'][$key]['remaining']+$use,2);$alloc[]=['month'=>$mo,'payable'=>0,'prepaid'=>$use,'amount'=>$use];$left=round($left-$use,2);}}if($left>.005)rsv2_out(['ok'=>false,'error'=>'Rent payment could not be fully allocated.'],422);$meta=['rentMasterId'=>$mid,'mill'=>$m['mill'],'payee'=>$m['payee'],'allocations'=>$alloc];$lines=[];if($pd>0)$lines[]=rsv2_line('2140',$pd,0,$names,$meta);if($preD>0)$lines[]=rsv2_line('1400',$preD,0,$names,$meta+['prepaidRent'=>true]);$lines[]=rsv2_pay_line($s,$entity,$payId,$amt,$names);$jid=rsv2_journal($s,$entity,$date,'RENT_PAYMENT','RENTPAY-'.$mid.'-'.$months[0].'-'.end($months),'Rent payment — '.$m['mill'],$lines,$u,$meta);$rid=rsv2_next((array)$s['rentSalaryPayments'],'RSP');$s['rentSalaryPayments'][$rid]=['id'=>$rid,'type'=>'RENT','entity'=>$entity,'masterId'=>$mid,'date'=>$date,'amount'=>$amt,'journalId'=>$jid,'allocations'=>$alloc];$result=['journalId'=>$jid,'paymentId'=>$rid];}
else rsv2_out(['ok'=>false,'error'=>'Unknown salary / rent action.'],422);
$s['revision']=(int)($s['revision']??0)+1;rewind($h);ftruncate($h,0);fwrite($h,json_encode($s,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($h);}finally{flock($h,LOCK_UN);fclose($h);}rsv2_out(rsv2_payload($s,$entity,$month)+['result'=>$result,'revision'=>$s['revision']]);
}catch(Throwable $e){rsv2_out(['ok'=>false,'error'=>'Salary / rent update could not be completed.'],500);}
