<?php
declare(strict_types=1);

require dirname(__DIR__) . '/auth_store.php';
header('Content-Type: application/json; charset=UTF-8');
header('Cache-Control: no-store, no-cache, must-revalidate');

const TT_RS_FILE = TT_DATA_DIR . '/accounts.json';
const TT_RS_MASTER = __DIR__ . '/../accounts/accounting_master_v1.json';

function rs_out(array $d,int $s=200):never{http_response_code($s);echo json_encode($d,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function rs_can_write(array $u):bool{if(($u['role']??'')==='Super Admin')return true;$p=$u['permissions']['Accounts']??null;if($p==='all')return true;if(!is_array($p))return false;if(in_array('Create',$p,true)||in_array('Edit',$p,true)||in_array('Approve',$p,true))return true;foreach($p as $a)if(is_array($a)&&(in_array('Create',$a,true)||in_array('Edit',$a,true)||in_array('Approve',$a,true)))return true;return false;}
function rs_def():array{return ['revision'=>0,'journals'=>[],'bankAccountSettings'=>[],'salaryMasters'=>[],'rentMasters'=>[],'salaryPeriods'=>[],'rentPeriods'=>[],'salaryAdvances'=>[],'rentPrepayments'=>[],'rentSalaryPayments'=>[]];}
function rs_read():array{tt_ensure_data_dir();if(!is_file(TT_RS_FILE))return rs_def();$h=fopen(TT_RS_FILE,'r');if($h===false||!flock($h,LOCK_SH))throw new RuntimeException('Accounts storage unavailable.');try{$raw=stream_get_contents($h);}finally{flock($h,LOCK_UN);fclose($h);}$v=$raw?json_decode($raw,true):null;return is_array($v)?array_replace_recursive(rs_def(),$v):rs_def();}
function rs_entity(string $v):string{$v=strtoupper(trim($v));if(!in_array($v,['TTI','BRM'],true))rs_out(['ok'=>false,'error'=>'Salary and mill rent masters are available for TTI / BRM.'],422);return $v;}
function rs_date(string $v,string $label='Date'):string{if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$v))rs_out(['ok'=>false,'error'=>$label.' is required.'],422);return $v;}
function rs_month(string $v):string{if(!preg_match('/^\d{4}-\d{2}$/',$v))rs_out(['ok'=>false,'error'=>'Select a valid month.'],422);return $v;}
function rs_amount(mixed $v,string $label='Amount',bool $allowZero=false):float{$n=round((float)$v,2);if($allowZero?$n<0:$n<=0)rs_out(['ok'=>false,'error'=>$label.' must be '.($allowZero?'zero or more':'greater than zero').'.'],422);return $n;}
function rs_month_start(string $m):string{return $m.'-01';}
function rs_month_end(string $m):string{return (new DateTimeImmutable($m.'-01'))->modify('last day of this month')->format('Y-m-d');}
function rs_next(array $items,string $p):string{$n=count($items)+1;do{$id=$p.'-'.gmdate('Y').'-'.str_pad((string)$n,6,'0',STR_PAD_LEFT);$n++;}while(isset($items[$id]));return $id;}
function rs_names():array{$raw=is_file(TT_RS_MASTER)?file_get_contents(TT_RS_MASTER):false;$m=$raw?json_decode($raw,true):null;if(!is_array($m))throw new RuntimeException('Accounting master unavailable.');$o=[];foreach((array)($m['chart']??[]) as $a)if(is_array($a)&&isset($a['code']))$o[(string)$a['code']]=(string)($a['name']??$a['code']);return $o;}
function rs_line(string $a,float $dr,float $cr,array $names,array $extra=[]):array{if(!isset($names[$a]))rs_out(['ok'=>false,'error'=>'Approved account '.$a.' is unavailable.'],422);return array_merge(['account'=>$a,'accountName'=>$names[$a],'debit'=>round($dr,2),'credit'=>round($cr,2)],$extra);}
function rs_active_for(array $m,string $month):bool{if(($m['status']??'Active')!=='Active')return false;$start=(string)($m['effectiveFrom']??'');$end=(string)($m['effectiveTo']??'');$ms=rs_month_start($month);$me=rs_month_end($month);return ($start===''||$start<=$me)&&($end===''||$end>=$ms);}
function rs_cat(string $v):string{$v=strtoupper(trim($v));$ok=['MILL_STAFF','OFFICE_STAFF','HOME_STAFF','DIRECTOR_REMUNERATION','HOME_MONTHLY_GIVE'];if(!in_array($v,$ok,true))rs_out(['ok'=>false,'error'=>'Select a valid salary category.'],422);return $v;}
function rs_cat_name(string $v):string{return match($v){'MILL_STAFF'=>'Mill Staff','OFFICE_STAFF'=>'Office Staff','HOME_STAFF'=>'Home Staff','DIRECTOR_REMUNERATION'=>'Director Remuneration','HOME_MONTHLY_GIVE'=>'Home Monthly Give',default=>$v};}
function rs_master_banks():array{$masters=tt_list_masters();$out=[];foreach((array)($masters['banks']??[]) as $row){if(!is_array($row))continue;$v=array_values((array)($row['values']??[]));while(count($v)<14)$v[]='';$linked=strtoupper((string)$v[1]);$entity=str_contains($linked,'BRM')||str_contains($linked,'BUKSH RICE')?'BRM':(str_contains($linked,'TTI')||str_contains($linked,'TRANSTRADE INTERNATIONAL')?'TTI':'');if($entity==='')continue;$out[(string)($row['id']??'')]=['id'=>(string)($row['id']??''),'entity'=>$entity,'accountType'=>(string)$v[0],'accountTitle'=>(string)$v[3],'bankName'=>(string)$v[4],'currency'=>strtoupper(trim((string)$v[7])),'accountNumber'=>(string)$v[8],'iban'=>(string)$v[9]];}return $out;}
function rs_payment_accounts(array $s,string $entity):array{$rows=[];foreach(rs_master_banks() as $id=>$a){if(($a['entity']??'')!==$entity||($a['accountType']??'')!=='Company Account'||($a['currency']??'')!=='PKR')continue;$set=is_array($s['bankAccountSettings'][$id]??null)?$s['bankAccountSettings'][$id]:[];if(empty($set['active'])||empty($set['allowPayments']))continue;$digits=preg_replace('/\D+/','',(string)$a['accountNumber'])??'';$last=substr($digits,-5);$rows[]=['id'=>$id,'type'=>'BANK','label'=>trim((string)$a['bankName']).($last!==''?' — '.$last:''),'bookBalance'=>rs_bank_balance($s,$entity,$id)];}$cash='CASH|'.$entity;$set=is_array($s['bankAccountSettings'][$cash]??null)?$s['bankAccountSettings'][$cash]:['active'=>true,'allowPayments'=>true];if(!empty($set['active'])&&!empty($set['allowPayments']))$rows[]=['id'=>$cash,'type'=>'CASH','label'=>'Cash / Petty Cash','bookBalance'=>rs_cash_balance($s,$entity)];return $rows;}
function rs_bank_balance(array $s,string $entity,string $bankId):float{$n=0;foreach((array)($s['journals']??[]) as $j){if(!is_array($j)||($j['status']??'')!=='Posted'||($j['entity']??'')!==$entity)continue;$jm=is_array($j['meta']??null)?$j['meta']:[];foreach((array)($j['lines']??[]) as $l){if(!is_array($l)||($l['account']??'')!=='1110')continue;$bid=(string)($l['bankAccountId']??$jm['bankAccountId']??'');if($bid===$bankId)$n+=(float)($l['debit']??0)-(float)($l['credit']??0);}}return round($n,2);}
function rs_cash_balance(array $s,string $entity):float{$n=0;foreach((array)($s['journals']??[]) as $j){if(!is_array($j)||($j['status']??'')!=='Posted'||($j['entity']??'')!==$entity)continue;foreach((array)($j['lines']??[]) as $l)if(is_array($l)&&($l['account']??'')==='1120')$n+=(float)($l['debit']??0)-(float)($l['credit']??0);}return round($n,2);}
function rs_pay_line(array $s,string $entity,string $id,float $amount,array $names):array{if($id==='CASH|'.$entity)return rs_line('1120',0,$amount,$names,['paymentAccountId'=>$id,'paymentType'=>'Cash']);$a=rs_master_banks()[$id]??null;if(!is_array($a)||($a['entity']??'')!==$entity||($a['accountType']??'')!=='Company Account'||($a['currency']??'')!=='PKR')rs_out(['ok'=>false,'error'=>'Select a valid PKR company bank account.'],422);$set=is_array($s['bankAccountSettings'][$id]??null)?$s['bankAccountSettings'][$id]:[];if(empty($set['active'])||empty($set['allowPayments']))rs_out(['ok'=>false,'error'=>'This bank account is not enabled for payments.'],422);return rs_line('1110',0,$amount,$names,['bankAccountId'=>$id,'bankName'=>(string)$a['bankName'],'accountTitle'=>(string)$a['accountTitle'],'currency'=>'PKR']);}
function rs_journal(array &$s,string $entity,string $date,string $source,string $ref,string $narr,array $lines,array $user,array $meta=[]):string{$dr=round(array_sum(array_map(static fn($l)=>(float)($l['debit']??0),$lines)),2);$cr=round(array_sum(array_map(static fn($l)=>(float)($l['credit']??0),$lines)),2);if(abs($dr-$cr)>.005)throw new RuntimeException('Journal did not balance.');$id=rs_next((array)$s['journals'],'AUTO');$s['journals'][$id]=['id'=>$id,'entity'=>$entity,'date'=>$date,'sourceType'=>$source,'reference'=>$ref,'narration'=>$narr,'lines'=>$lines,'totalDebit'=>$dr,'totalCredit'=>$cr,'status'=>'Posted','meta'=>$meta,'createdAt'=>gmdate('c'),'createdBy'=>(string)($user['full_name']??$user['username']??'Accounts'),'userId'=>(int)($user['id']??0),'reversalOf'=>null];return $id;}
function rs_period_id(string $entity,string $month,string $master):string{return $entity.'|'.$month.'|'.$master;}
function rs_salary_advances_for(array $s,string $masterId,string $month):array{$rows=[];foreach((array)($s['salaryAdvances']??[]) as $id=>$a)if(is_array($a)&&($a['salaryMasterId']??'')===$masterId&&($a['month']??'')===$month)$rows[$id]=$a;return $rows;}
function rs_salary_row(array $s,array $m,string $month):array{$id=rs_period_id((string)$m['entity'],$month,(string)$m['id']);$p=is_array($s['salaryPeriods'][$id]??null)?$s['salaryPeriods'][$id]:null;$adv=0;foreach(rs_salary_advances_for($s,(string)$m['id'],$month) as $a)$adv+=(float)($a['amount']??0);return ['periodId'=>$id,'masterId'=>$m['id'],'name'=>$m['name'],'category'=>$m['category'],'categoryName'=>rs_cat_name((string)$m['category']),'month'=>$month,'gross'=>(float)$m['monthlyAmount'],'advancePaid'=>round($adv,2),'prepared'=>$p!==null,'appliedAdvance'=>(float)($p['appliedAdvance']??0),'paidAfterPrepare'=>(float)($p['paidAfterPrepare']??0),'outstanding'=>(float)($p['outstanding']??0),'productionCostEligible'=>(bool)($m['productionCostEligible']??false),'status'=>$p['status']??'Not Prepared'];}
function rs_rent_row(array $s,array $m,string $month):array{$id=rs_period_id((string)$m['entity'],$month,(string)$m['id']);$p=is_array($s['rentPeriods'][$id]??null)?$s['rentPeriods'][$id]:null;return ['periodId'=>$id,'masterId'=>$m['id'],'mill'=>$m['mill'],'payee'=>$m['payee'],'month'=>$month,'monthlyAmount'=>(float)$m['monthlyAmount'],'paymentPattern'=>$m['paymentPattern'],'prepared'=>$p!==null,'prepaidUsed'=>(float)($p['prepaidUsed']??0),'paidAfterPrepare'=>(float)($p['paidAfterPrepare']??0),'outstanding'=>(float)($p['outstanding']??0),'productionCostEligible'=>(bool)($m['productionCostEligible']??true),'status'=>$p['status']??'Not Prepared'];}
function rs_payload(array $s,string $entity,string $month):array{$salary=[];$rent=[];foreach((array)$s['salaryMasters'] as $m)if(is_array($m)&&($m['entity']??'')===$entity&&rs_active_for($m,$month))$salary[]=rs_salary_row($s,$m,$month);foreach((array)$s['rentMasters'] as $m)if(is_array($m)&&($m['entity']??'')===$entity&&rs_active_for($m,$month))$rent[]=rs_rent_row($s,$m,$month);usort($salary,static fn($a,$b)=>strcmp((string)$a['categoryName'],(string)$b['categoryName'])?:strcmp((string)$a['name'],(string)$b['name']));usort($rent,static fn($a,$b)=>strcmp((string)$a['mill'],(string)$b['mill']));$salaryMasters=array_values(array_filter((array)$s['salaryMasters'],static fn($m)=>is_array($m)&&($m['entity']??'')===$entity));$rentMasters=array_values(array_filter((array)$s['rentMasters'],static fn($m)=>is_array($m)&&($m['entity']??'')===$entity));return ['ok'=>true,'entity'=>$entity,'month'=>$month,'salaryMasters'=>$salaryMasters,'rentMasters'=>$rentMasters,'salaryRows'=>$salary,'rentRows'=>$rent,'paymentAccounts'=>rs_payment_accounts($s,$entity),'serverNow'=>gmdate('c')];}
function rs_prepare_month(array &$s,string $entity,string $month,array $user,array $names):array{$salaryCount=0;$rentCount=0;$date=rs_month_end($month);foreach((array)$s['salaryMasters'] as $mid=>$m){if(!is_array($m)||($m['entity']??'')!==$entity||!rs_active_for($m,$month))continue;$pid=rs_period_id($entity,$month,(string)$mid);if(isset($s['salaryPeriods'][$pid]))continue;$gross=round((float)$m['monthlyAmount'],2);if($gross<=0)continue;$meta=['salaryMasterId'=>$mid,'month'=>$month,'person'=>(string)$m['name'],'category'=>(string)$m['category'],'productionCostEligible'=>(bool)($m['productionCostEligible']??false)];$jid=rs_journal($s,$entity,$date,'SALARY_MONTHLY_ACCRUAL','SAL-'.$month.'-'.$mid,'Salary — '.$month.' — '.(string)$m['name'],[rs_line('6200',$gross,0,$names,$meta),rs_line('2140',0,$gross,$names,$meta)],$user,$meta);$advanceTotal=0;$appliedIds=[];foreach(rs_salary_advances_for($s,(string)$mid,$month) as $aid=>$a){if(!empty($a['applied']))continue;$available=max(0,$gross-$advanceTotal);if($available<=0)break;$use=min($available,(float)$a['amount']);if($use<=0)continue;$advanceTotal=round($advanceTotal+$use,2);$appliedIds[]=$aid;$s['salaryAdvances'][$aid]['applied']=true;$s['salaryAdvances'][$aid]['appliedAmount']=$use;}$clearJid=null;if($advanceTotal>0)$clearJid=rs_journal($s,$entity,$date,'SALARY_ADVANCE_APPLIED','SALADV-'.$month.'-'.$mid,'Apply salary advances — '.$month.' — '.(string)$m['name'],[rs_line('2140',$advanceTotal,0,$names,$meta),rs_line('1230',0,$advanceTotal,$names,$meta)],$user,$meta+['advanceIds'=>$appliedIds]);$out=round($gross-$advanceTotal,2);$s['salaryPeriods'][$pid]=['id'=>$pid,'entity'=>$entity,'month'=>$month,'salaryMasterId'=>$mid,'name'=>$m['name'],'category'=>$m['category'],'gross'=>$gross,'appliedAdvance'=>$advanceTotal,'paidAfterPrepare'=>0,'outstanding'=>$out,'journalId'=>$jid,'advanceClearJournalId'=>$clearJid,'productionCostEligible'=>(bool)($m['productionCostEligible']??false),'status'=>$out>.005?'Payable':'Paid / Cleared','preparedAt'=>gmdate('c'),'preparedBy'=>(string)($user['full_name']??'Accounts')];$salaryCount++;}
foreach((array)$s['rentMasters'] as $mid=>$m){if(!is_array($m)||($m['entity']??'')!==$entity||!rs_active_for($m,$month))continue;$pid=rs_period_id($entity,$month,(string)$mid);if(isset($s['rentPeriods'][$pid]))continue;$gross=round((float)$m['monthlyAmount'],2);if($gross<=0)continue;$preKey=$mid.'|'.$month;$pre=is_array($s['rentPrepayments'][$preKey]??null)?$s['rentPrepayments'][$preKey]:null;$preAvail=(float)($pre['remaining']??0);$use=min($gross,max(0,$preAvail));$payable=round($gross-$use,2);$meta=['rentMasterId'=>$mid,'month'=>$month,'mill'=>(string)$m['mill'],'payee'=>(string)$m['payee'],'productionCostEligible'=>(bool)($m['productionCostEligible']??true)];$lines=[rs_line('6300',$gross,0,$names,$meta)];if($use>0)$lines[]=rs_line('1400',0,$use,$names,$meta+['prepaidRent'=>true]);if($payable>0)$lines[]=rs_line('2140',0,$payable,$names,$meta);$jid=rs_journal($s,$entity,$date,'RENT_MONTHLY_ACCRUAL','RENT-'.$month.'-'.$mid,'Mill rent — '.$month.' — '.(string)$m['mill'],$lines,$user,$meta);if($use>0){$s['rentPrepayments'][$preKey]['remaining']=round($preAvail-$use,2);$s['rentPrepayments'][$preKey]['used']=round((float)($pre['used']??0)+$use,2);}$s['rentPeriods'][$pid]=['id'=>$pid,'entity'=>$entity,'month'=>$month,'rentMasterId'=>$mid,'mill'=>$m['mill'],'payee'=>$m['payee'],'gross'=>$gross,'prepaidUsed'=>$use,'paidAfterPrepare'=>0,'outstanding'=>$payable,'journalId'=>$jid,'productionCostEligible'=>(bool)($m['productionCostEligible']??true),'status'=>$payable>.005?'Payable':'Paid / Prepaid','preparedAt'=>gmdate('c'),'preparedBy'=>(string)($user['full_name']??'Accounts')];$rentCount++;}return ['salaryPrepared'=>$salaryCount,'rentPrepared'=>$rentCount];}
function rs_months_between(string $from,string $to):array{rs_month($from);rs_month($to);if($to<$from)rs_out(['ok'=>false,'error'=>'Rent To Month cannot be before From Month.'],422);$out=[];$d=new DateTimeImmutable($from.'-01');$end=new DateTimeImmutable($to.'-01');while($d<=$end&&count($out)<60){$out[]=$d->format('Y-m');$d=$d->modify('+1 month');}return $out;}

try{$u=tt_require_login();if(!tt_user_can_open_module($u,'Accounts'))rs_out(['ok'=>false,'error'=>'Accounts permission required.'],403);$entity=rs_entity((string)($_GET['entity']??'TTI'));$month=(string)($_GET['month']??gmdate('Y-m'));$month=rs_month($month);if($_SERVER['REQUEST_METHOD']==='GET')rs_out(rs_payload(rs_read(),$entity,$month));if($_SERVER['REQUEST_METHOD']!=='POST')rs_out(['ok'=>false,'error'=>'Method not allowed.'],405);if(!rs_can_write($u))rs_out(['ok'=>false,'error'=>'Accounts Create, Edit or Approve permission required.'],403);$b=json_decode(file_get_contents('php://input')?:'{}',true);if(!is_array($b)||!tt_verify_csrf((string)($b['csrf']??'')))rs_out(['ok'=>false,'error'=>'Your session expired. Refresh and try again.'],419);$action=(string)($b['action']??'');tt_ensure_data_dir();$h=fopen(TT_RS_FILE,'c+');if($h===false||!flock($h,LOCK_EX))throw new RuntimeException('Accounts storage unavailable.');try{rewind($h);$raw=stream_get_contents($h);$s=$raw?json_decode($raw,true):null;if(!is_array($s))$s=rs_def();$s=array_replace_recursive(rs_def(),$s);$names=rs_names();$entity=rs_entity((string)($b['entity']??$entity));$month=rs_month((string)($b['month']??$month));
if($action==='save_salary_master'){$name=trim((string)($b['name']??''));if($name==='')rs_out(['ok'=>false,'error'=>'Name is required.'],422);$cat=rs_cat((string)($b['category']??''));$amt=rs_amount($b['monthlyAmount']??0,'Monthly amount');$from=rs_date((string)($b['effectiveFrom']??''),'Start date');$to=trim((string)($b['effectiveTo']??''));if($to!=='')$to=rs_date($to,'End date');$id=trim((string)($b['id']??''));if($id===''||!isset($s['salaryMasters'][$id]))$id=rs_next((array)$s['salaryMasters'],'SALM');$s['salaryMasters'][$id]=['id'=>$id,'entity'=>$entity,'name'=>$name,'category'=>$cat,'monthlyAmount'=>$amt,'effectiveFrom'=>$from,'effectiveTo'=>$to,'productionCostEligible'=>$cat==='MILL_STAFF'?(bool)($b['productionCostEligible']??true):false,'status'=>(string)($b['status']??'Active'),'notes'=>trim((string)($b['notes']??'')),'updatedAt'=>gmdate('c'),'updatedBy'=>(string)($u['full_name']??'Accounts')];$result=['masterId'=>$id];}
elseif($action==='save_rent_master'){$mill=trim((string)($b['mill']??''));$payee=trim((string)($b['payee']??''));if($mill===''||$payee==='')rs_out(['ok'=>false,'error'=>'Mill / location and payee are required.'],422);$amt=rs_amount($b['monthlyAmount']??0,'Monthly rent');$from=rs_date((string)($b['effectiveFrom']??''),'Start date');$to=trim((string)($b['effectiveTo']??''));if($to!=='')$to=rs_date($to,'End date');$pattern=(string)($b['paymentPattern']??'Monthly');if(!in_array($pattern,['Monthly','Quarterly','Half-Yearly','Twice-Yearly','Other'],true))$pattern='Other';$id=trim((string)($b['id']??''));if($id===''||!isset($s['rentMasters'][$id]))$id=rs_next((array)$s['rentMasters'],'RENTM');$s['rentMasters'][$id]=['id'=>$id,'entity'=>$entity,'mill'=>$mill,'payee'=>$payee,'monthlyAmount'=>$amt,'paymentPattern'=>$pattern,'effectiveFrom'=>$from,'effectiveTo'=>$to,'productionCostEligible'=>(bool)($b['productionCostEligible']??true),'status'=>(string)($b['status']??'Active'),'notes'=>trim((string)($b['notes']??'')),'updatedAt'=>gmdate('c'),'updatedBy'=>(string)($u['full_name']??'Accounts')];$result=['masterId'=>$id];}
elseif($action==='prepare_month'){$result=rs_prepare_month($s,$entity,$month,$u,$names);}
elseif($action==='salary_advance'){$mid=trim((string)($b['masterId']??''));$m=$s['salaryMasters'][$mid]??null;if(!is_array($m)||($m['entity']??'')!==$entity)rs_out(['ok'=>false,'error'=>'Select a salary master.'],422);$amt=rs_amount($b['amount']??0);$date=rs_date((string)($b['date']??''));$payId=trim((string)($b['paymentAccountId']??''));$pid=rs_period_id($entity,$month,$mid);$p=$s['salaryPeriods'][$pid]??null;$meta=['salaryMasterId'=>$mid,'month'=>$month,'person'=>(string)$m['name'],'category'=>(string)$m['category']];if(is_array($p)&&((float)($p['outstanding']??0))>0){if($amt>(float)$p['outstanding']+.005)rs_out(['ok'=>false,'error'=>'Amount is more than the salary balance for this month.'],422);$jid=rs_journal($s,$entity,$date,'SALARY_PAYMENT','SALPAY-'.$pid,'Salary payment — '.(string)$m['name'].' — '.$month,[rs_line('2140',$amt,0,$names,$meta),rs_pay_line($s,$entity,$payId,$amt,$names)],$u,$meta);$s['salaryPeriods'][$pid]['paidAfterPrepare']=round((float)$p['paidAfterPrepare']+$amt,2);$s['salaryPeriods'][$pid]['outstanding']=round((float)$p['outstanding']-$amt,2);$s['salaryPeriods'][$pid]['status']=$s['salaryPeriods'][$pid]['outstanding']>.005?'Part Paid':'Paid / Cleared';$type='PAYMENT';}else{$jid=rs_journal($s,$entity,$date,'SALARY_ADVANCE','SALADV-'.$mid.'-'.$month,'Salary advance — '.(string)$m['name'].' — '.$month,[rs_line('1230',$amt,0,$names,$meta+['staffAdvance'=>true]),rs_pay_line($s,$entity,$payId,$amt,$names)],$u,$meta);$aid=rs_next((array)$s['salaryAdvances'],'SADV');$s['salaryAdvances'][$aid]=['id'=>$aid,'entity'=>$entity,'salaryMasterId'=>$mid,'month'=>$month,'date'=>$date,'amount'=>$amt,'journalId'=>$jid,'applied'=>false,'createdAt'=>gmdate('c')];$type='ADVANCE';}$result=['journalId'=>$jid,'type'=>$type];}
elseif($action==='pay_salary'){$pid=trim((string)($b['periodId']??''));$p=$s['salaryPeriods'][$pid]??null;if(!is_array($p)||($p['entity']??'')!==$entity)rs_out(['ok'=>false,'error'=>'Select a prepared salary month.'],422);$amt=rs_amount($b['amount']??0);if($amt>(float)$p['outstanding']+.005)rs_out(['ok'=>false,'error'=>'Amount is more than the outstanding salary balance.'],422);$date=rs_date((string)($b['date']??''));$payId=trim((string)($b['paymentAccountId']??''));$meta=['salaryMasterId'=>$p['salaryMasterId'],'month'=>$p['month'],'person'=>$p['name'],'category'=>$p['category']];$jid=rs_journal($s,$entity,$date,'SALARY_PAYMENT','SALPAY-'.$pid,'Salary payment — '.$p['name'].' — '.$p['month'],[rs_line('2140',$amt,0,$names,$meta),rs_pay_line($s,$entity,$payId,$amt,$names)],$u,$meta);$s['salaryPeriods'][$pid]['paidAfterPrepare']=round((float)$p['paidAfterPrepare']+$amt,2);$s['salaryPeriods'][$pid]['outstanding']=round((float)$p['outstanding']-$amt,2);$s['salaryPeriods'][$pid]['status']=$s['salaryPeriods'][$pid]['outstanding']>.005?'Part Paid':'Paid / Cleared';$result=['journalId'=>$jid];}
elseif($action==='pay_rent'){$mid=trim((string)($b['masterId']??''));$m=$s['rentMasters'][$mid]??null;if(!is_array($m)||($m['entity']??'')!==$entity)rs_out(['ok'=>false,'error'=>'Select a rent master.'],422);$from=rs_month((string)($b['fromMonth']??''));$to=rs_month((string)($b['toMonth']??''));$months=rs_months_between($from,$to);$amt=rs_amount($b['amount']??0);$expected=round(count($months)*(float)$m['monthlyAmount'],2);if($amt>$expected+.005)rs_out(['ok'=>false,'error'=>'Payment is more than the rent for the selected months. Select the additional months it covers.'],422);$date=rs_date((string)($b['date']??''));$payId=trim((string)($b['paymentAccountId']??''));$left=$amt;$payableDebit=0.0;$prepaidDebit=0.0;$alloc=[];foreach($months as $mo){if($left<=.005)break;$target=min((float)$m['monthlyAmount'],$left);$pid=rs_period_id($entity,$mo,$mid);$p=$s['rentPeriods'][$pid]??null;$toPay=0.0;if(is_array($p)&&((float)($p['outstanding']??0))>0){$toPay=min($target,(float)$p['outstanding']);$payableDebit+= $toPay;$s['rentPeriods'][$pid]['paidAfterPrepare']=round((float)$p['paidAfterPrepare']+$toPay,2);$s['rentPeriods'][$pid]['outstanding']=round((float)$p['outstanding']-$toPay,2);$s['rentPeriods'][$pid]['status']=$s['rentPeriods'][$pid]['outstanding']>.005?'Part Paid':'Paid / Cleared';}$pre=$target-$toPay;if($pre>.005){$prepaidDebit+=$pre;$key=$mid.'|'.$mo;if(!isset($s['rentPrepayments'][$key]))$s['rentPrepayments'][$key]=['id'=>$key,'entity'=>$entity,'rentMasterId'=>$mid,'month'=>$mo,'amount'=>0,'remaining'=>0,'used'=>0];$s['rentPrepayments'][$key]['amount']=round((float)$s['rentPrepayments'][$key]['amount']+$pre,2);$s['rentPrepayments'][$key]['remaining']=round((float)$s['rentPrepayments'][$key]['remaining']+$pre,2);}$alloc[]=['month'=>$mo,'payable'=>$toPay,'prepaid'=>$pre,'amount'=>$target];$left=round($left-$target,2);}if($left>.005)rs_out(['ok'=>false,'error'=>'Rent payment could not be fully allocated to the selected months.'],422);$meta=['rentMasterId'=>$mid,'mill'=>$m['mill'],'payee'=>$m['payee'],'allocations'=>$alloc];$lines=[];if($payableDebit>0)$lines[]=rs_line('2140',$payableDebit,0,$names,$meta);if($prepaidDebit>0)$lines[]=rs_line('1400',$prepaidDebit,0,$names,$meta+['prepaidRent'=>true]);$lines[]=rs_pay_line($s,$entity,$payId,$amt,$names);$jid=rs_journal($s,$entity,$date,'RENT_PAYMENT','RENTPAY-'.$mid.'-'.$from.'-'.$to,'Rent payment — '.$m['mill'].' — '.$from.' to '.$to,$lines,$u,$meta);$rid=rs_next((array)$s['rentSalaryPayments'],'RSP');$s['rentSalaryPayments'][$rid]=['id'=>$rid,'type'=>'RENT','entity'=>$entity,'masterId'=>$mid,'date'=>$date,'amount'=>$amt,'journalId'=>$jid,'allocations'=>$alloc];$result=['journalId'=>$jid,'paymentId'=>$rid];}
else rs_out(['ok'=>false,'error'=>'Unknown salary / rent action.'],422);$s['revision']=(int)($s['revision']??0)+1;rewind($h);ftruncate($h,0);fwrite($h,json_encode($s,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($h);}finally{flock($h,LOCK_UN);fclose($h);}rs_out(rs_payload($s,$entity,$month)+['result'=>$result,'revision'=>$s['revision']]);}catch(Throwable $e){rs_out(['ok'=>false,'error'=>'Salary / rent update could not be completed.'],500);}
