<?php
declare(strict_types=1);
require dirname(__DIR__).'/auth_store.php';
header('Content-Type: application/json; charset=UTF-8');
header('Cache-Control: no-store, no-cache, must-revalidate');
const TT_STR_FILE=TT_DATA_DIR.'/accounts.json';
function sr_out(array $d,int $s=200):never{http_response_code($s);echo json_encode($d,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function sr_def():array{return ['revision'=>0,'journals'=>[],'salesTaxRefundReceipts'=>[]];}
function sr_read():array{tt_ensure_data_dir();if(!is_file(TT_STR_FILE))return sr_def();$h=fopen(TT_STR_FILE,'r');if($h===false||!flock($h,LOCK_SH))throw new RuntimeException('Accounts storage unavailable.');try{$raw=stream_get_contents($h);}finally{flock($h,LOCK_UN);fclose($h);}$v=$raw?json_decode($raw,true):null;return is_array($v)?array_replace_recursive(sr_def(),$v):sr_def();}
function sr_can_write(array $u):bool{if(($u['role']??'')==='Super Admin')return true;$p=$u['permissions']['Accounts']??null;if($p==='all')return true;if(!is_array($p))return false;if(in_array('Create',$p,true)||in_array('Edit',$p,true)||in_array('Approve',$p,true))return true;foreach($p as $a)if(is_array($a)&&(in_array('Create',$a,true)||in_array('Edit',$a,true)||in_array('Approve',$a,true)))return true;return false;}
function sr_entity(string $v):string{$v=strtoupper(trim($v));if(!in_array($v,['TTI','BRM'],true))sr_out(['ok'=>false,'error'=>'Sales tax refund receipt is available for TTI or BRM books.'],422);return $v;}
function sr_date(string $v):string{if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$v))sr_out(['ok'=>false,'error'=>'Valid receipt date required.'],422);return $v;}
function sr_next(array $a,string $p):string{$n=count($a)+1;do{$id=$p.'-'.gmdate('Y').'-'.str_pad((string)$n,6,'0',STR_PAD_LEFT);$n++;}while(isset($a[$id]));return $id;}
function sr_payload(array $s,string $e):array{$rows=[];$total=0.0;foreach((array)$s['salesTaxRefundReceipts'] as $r){if(!is_array($r)||($r['entity']??'')!==$e)continue;$rows[]=$r;$total+=(float)($r['amount']??0);}usort($rows,static fn($a,$b)=>strcmp((string)$b['receiptDate'],(string)$a['receiptDate']));return ['ok'=>true,'entity'=>$e,'receipts'=>$rows,'totalReceived'=>round($total,2)];}
try{$u=tt_require_login();if(!tt_user_can_open_module($u,'Accounts'))sr_out(['ok'=>false,'error'=>'Accounts permission required.'],403);$e=sr_entity((string)($_GET['entity']??'TTI'));if($_SERVER['REQUEST_METHOD']==='GET')sr_out(sr_payload(sr_read(),$e));if($_SERVER['REQUEST_METHOD']!=='POST')sr_out(['ok'=>false,'error'=>'Method not allowed.'],405);if(!sr_can_write($u))sr_out(['ok'=>false,'error'=>'Accounts Create / Edit / Approve permission required.'],403);$b=json_decode(file_get_contents('php://input')?:'{}',true);if(!is_array($b)||!tt_verify_csrf((string)($b['csrf']??'')))sr_out(['ok'=>false,'error'=>'Your session expired. Refresh and try again.'],419);$e=sr_entity((string)($b['entity']??''));$date=sr_date((string)($b['receiptDate']??''));$amount=round((float)($b['amount']??0),2);if($amount<=0)sr_out(['ok'=>false,'error'=>'Refund amount must be greater than zero.'],422);$bankId=trim((string)($b['bankAccountId']??''));if($bankId==='')sr_out(['ok'=>false,'error'=>'Select the bank account receiving the refund.'],422);$reference=trim((string)($b['reference']??''));tt_ensure_data_dir();$h=fopen(TT_STR_FILE,'c+');if($h===false||!flock($h,LOCK_EX))throw new RuntimeException('Accounts storage unavailable.');try{rewind($h);$raw=stream_get_contents($h);$s=$raw?json_decode($raw,true):null;if(!is_array($s))$s=sr_def();$s=array_replace_recursive(sr_def(),$s);$rid=sr_next((array)$s['salesTaxRefundReceipts'],'STR');$jid=sr_next((array)$s['journals'],'AUTO');$receipt=['id'=>$rid,'entity'=>$e,'receiptDate'=>$date,'amount'=>$amount,'bankAccountId'=>$bankId,'reference'=>$reference,'note'=>trim((string)($b['note']??'')),'createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??$u['username']??'Accounts'),'journalId'=>$jid];$s['salesTaxRefundReceipts'][$rid]=$receipt;$s['journals'][$jid]=['id'=>$jid,'entity'=>$e,'date'=>$date,'sourceType'=>'SALES_TAX_REFUND_RECEIPT','reference'=>$reference?:$rid,'narration'=>'Sales tax refund received from Government','lines'=>[['account'=>'1110','accountName'=>'Bank Accounts','debit'=>$amount,'credit'=>0,'bankAccountId'=>$bankId],['account'=>'1230','accountName'=>'Other Receivables / Advances','debit'=>0,'credit'=>$amount,'subledger'=>'Sales Tax Recoverable / Refund Receivable']],'totalDebit'=>$amount,'totalCredit'=>$amount,'status'=>'Posted','meta'=>['salesTaxRefundReceiptId'=>$rid,'bankAccountId'=>$bankId],'createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??$u['username']??'Accounts')];$s['revision']=(int)($s['revision']??0)+1;rewind($h);ftruncate($h,0);fwrite($h,json_encode($s,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($h);}finally{flock($h,LOCK_UN);fclose($h);}sr_out(sr_payload($s,$e)+['receipt'=>$receipt,'journalId'=>$jid]);}catch(Throwable $x){sr_out(['ok'=>false,'error'=>'Sales tax refund receipt could not be posted.'],500);}