<?php
declare(strict_types=1);

require dirname(__DIR__) . '/auth_store.php';
header('Content-Type: application/json; charset=UTF-8');
header('Cache-Control: no-store, no-cache, must-revalidate');

const TT_TGTX_FILE = TT_DATA_DIR . '/accounts.json';
const TT_TGTX_ACCOUNT_MASTER = __DIR__ . '/../accounts/accounting_master_v1.json';
const TT_TGTX_RATE_TYPE = 'tg_currency_rates';

function tgtx_out(array $d,int $s=200): never {http_response_code($s);echo json_encode($d,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function tgtx_can(array $u): bool {if(($u['role']??'')==='Super Admin')return true;$p=$u['permissions']['Accounts']??null;if($p==='all')return true;if(!is_array($p))return false;if(in_array('Create',$p,true)||in_array('Edit',$p,true)||in_array('Approve',$p,true))return true;foreach($p as $a)if(is_array($a)&&(in_array('Create',$a,true)||in_array('Edit',$a,true)||in_array('Approve',$a,true)))return true;return false;}
function tgtx_defaults(): array {return ['revision'=>0,'journals'=>[],'bankAccountSettings'=>[],'exportCandidates'=>[],'tgBankTransactions'=>[],'tgLiabilities'=>[]];}
function tgtx_read(): array {tt_ensure_data_dir();if(!is_file(TT_TGTX_FILE))return tgtx_defaults();$h=fopen(TT_TGTX_FILE,'r');if($h===false||!flock($h,LOCK_SH))throw new RuntimeException('Accounts storage unavailable.');try{$raw=stream_get_contents($h);}finally{flock($h,LOCK_UN);fclose($h);}$v=$raw?json_decode($raw,true):null;return is_array($v)?array_replace_recursive(tgtx_defaults(),$v):tgtx_defaults();}
function tgtx_catalog(): array {$raw=file_get_contents(TT_TGTX_ACCOUNT_MASTER);$m=$raw?json_decode($raw,true):null;if(!is_array($m))throw new RuntimeException('Accounting master unavailable.');$out=[];foreach((array)($m['chart']??[]) as $a)if(is_array($a)&&isset($a['code']))$out[(string)$a['code']]=$a;return $out;}
function tgtx_entity(string $v): bool {$u=strtoupper($v);return str_contains($u,'TRANS GRAINS')||preg_match('/(^|\W)TG($|\W)/',$u)===1;}
function tgtx_banks(array $store): array {$m=(array)(tt_read_store()['masters']??[]);$out=[];foreach((array)($m['banks']??[]) as $r){if(!is_array($r))continue;$v=array_values((array)($r['values']??[]));while(count($v)<14)$v[]='';if(!tgtx_entity((string)$v[1]))continue;$id=(string)($r['id']??'');$s=is_array($store['bankAccountSettings'][$id]??null)?$store['bankAccountSettings'][$id]:[];$out[$id]=['id'=>$id,'accountType'=>(string)$v[0],'title'=>(string)$v[3],'bank'=>(string)$v[4],'currency'=>strtoupper(trim((string)$v[7])),'accountNumber'=>(string)$v[8],'iban'=>(string)$v[9],'masterStatus'=>(string)$v[13],'settings'=>$s];}return $out;}
function tgtx_balance(array $store,string $id,string $currency): array {$native=0.0;$aed=0.0;foreach((array)($store['journals']??[]) as $j){if(!is_array($j)||($j['status']??'')!=='Posted'||($j['entity']??'')!=='TG')continue;$jm=is_array($j['meta']??null)?$j['meta']:[];foreach((array)($j['lines']??[]) as $l){if(!is_array($l)||(string)($l['account']??'')!=='1110')continue;$bid=(string)($l['bankAccountId']??$jm['bankAccountId']??'');if($bid!==$id)continue;$native+=(float)($l['bankDebit']??0)-(float)($l['bankCredit']??0);$aed+=(float)($l['debit']??0)-(float)($l['credit']??0);}}if($currency==='AED'&&abs($native)<.0001)$native=$aed;return ['native'=>round($native,2),'aedCarrying'=>round($aed,2),'carryingRate'=>$native>0?round($aed/$native,8):($currency==='AED'?1.0:0.0)];}
function tgtx_rates(string $date,bool $required=true): ?array {$m=(array)(tt_read_store()['masters']??[]);$best=null;foreach((array)($m[TT_TGTX_RATE_TYPE]??[]) as $r){if(!is_array($r))continue;$v=array_values((array)($r['values']??[]));while(count($v)<12)$v[]='';$status=strtolower((string)$v[10]);if(str_contains($status,'inactive')||str_contains($status,'historical'))continue;$from=(string)$v[6];$to=(string)$v[7];if($from!==''&&$date<$from)continue;if($to!==''&&$date>$to)continue;if($best===null||$from>(string)$best['effectiveFrom'])$best=['id'=>(string)($r['id']??''),'code'=>(string)$v[1],'sellUsdToAed'=>(float)$v[3],'buyUsdWithAed'=>(float)$v[4],'closingTax'=>(float)$v[5],'effectiveFrom'=>$from,'effectiveTo'=>$to,'yearEnd'=>(string)$v[8],'closingCurrency'=>(string)$v[9]];}if(!$best&&$required)tgtx_out(['ok'=>false,'error'=>'No active TG Currency & Closing rate applies to this date. Set or activate the effective rate in Directors → TG Master → Currency & Closing.'],422);return $best;}
function tgtx_line(string $a,float $dr,float $cr,array $cat,array $x=[]): array {if(!isset($cat[$a]))tgtx_out(['ok'=>false,'error'=>'Approved account '.$a.' is unavailable.'],422);return array_merge(['account'=>$a,'accountName'=>(string)($cat[$a]['name']??$a),'debit'=>round($dr,2),'credit'=>round($cr,2)],$x);}
function tgtx_next(array $items,string $prefix): string {$n=count($items)+1;do{$id=$prefix.'-'.gmdate('Y').'-'.str_pad((string)$n,6,'0',STR_PAD_LEFT);$n++;}while(isset($items[$id]));return $id;}
function tgtx_date(string $v): string {if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$v))tgtx_out(['ok'=>false,'error'=>'Valid transaction date required.'],422);return $v;}
function tgtx_pos(mixed $v,string $label): float {$n=round((float)$v,2);if($n<=0)tgtx_out(['ok'=>false,'error'=>$label.' must be greater than zero.'],422);return $n;}
function tgtx_open_export_receivables(array $store): array {$used=[];foreach((array)($store['tgBankTransactions']??[]) as $x){if(!is_array($x)||($x['kind']??'')!=='Receipt'||($x['receiptType']??'')!=='EXPORT_RECEIVABLE')continue;$cid=(string)($x['sourceCandidateId']??'');if($cid!=='')$used[$cid]=($used[$cid]??0)+(float)($x['settlementAmountNative']??0);}$rows=[];foreach((array)($store['exportCandidates']??[]) as $c){if(!is_array($c)||($c['entity']??'')!=='TG'||($c['candidateType']??'')!=='CUSTOMER_EXPORT_SALE'||empty($c['journalId']))continue;$amt=(float)($c['transactionAmount']??0);$out=round($amt-($used[(string)($c['id']??'')]??0),2);if($out<=.0001)continue;$m=is_array($c['meta']??null)?$c['meta']:[];$rows[]=['id'=>(string)$c['id'],'reference'=>(string)($c['reference']??$c['sourceKey']??''),'customer'=>(string)($m['customer']??''),'contractRef'=>(string)($m['contractRef']??''),'currency'=>strtoupper((string)($c['transactionCurrency']??'')),'originalAmount'=>$amt,'outstandingNative'=>$out,'functionalCurrency'=>(string)($c['functionalCurrency']??'AED'),'functionalRate'=>(float)($c['functionalRate']??0),'currentCarryingRate'=>(float)($c['currentCarryingRate']??$c['functionalRate']??0),'currentCarryingAsOf'=>(string)($c['currentCarryingAsOf']??''),'functionalAmount'=>(float)($c['functionalAmount']??0),'journalId'=>(string)$c['journalId']];}usort($rows,static fn($a,$b)=>strcmp((string)$a['reference'],(string)$b['reference']));return $rows;}
function tgtx_liability_paid(array $store,string $id): float {$n=0.0;foreach((array)($store['tgBankTransactions']??[]) as $x){if(!is_array($x)||($x['kind']??'')!=='Payment'||(string)($x['sourceLiabilityId']??'')!==$id)continue;$n+=(float)($x['amountNative']??0);}return round($n,2);}
function tgtx_open_liabilities(array $store): array {$rows=[];foreach((array)($store['tgLiabilities']??[]) as $x){if(!is_array($x))continue;$id=(string)($x['id']??'');$orig=(float)($x['nativeAmount']??0);$paid=tgtx_liability_paid($store,$id);$open=round($orig-$paid,2);if($open<=.0001)continue;$rate=(float)($x['currentCarryingRate']??$x['recognitionRate']??0);$rows[]=['id'=>$id,'source'=>'Supplier / Service Bill','counterparty'=>(string)($x['counterparty']??''),'reference'=>(string)($x['reference']??''),'currency'=>strtoupper((string)($x['currency']??'')),'outstandingNative'=>$open,'currentCarryingRate'=>$rate,'outstandingAed'=>round($open*$rate,2),'payableAccount'=>(string)($x['payableAccount']??'2140'),'dueDate'=>(string)($x['dueDate']??''),'journalId'=>(string)($x['journalId']??'')];}
 foreach((array)($store['exportCandidates']??[]) as $c){if(!is_array($c)||($c['entity']??'')!=='TG'||($c['candidateType']??'')!=='TG_INTERCOMPANY_PAYABLE'||empty($c['journalId']))continue;$id=(string)($c['id']??'');$orig=(float)($c['transactionAmount']??0);$paid=tgtx_liability_paid($store,$id);$open=round($orig-$paid,2);if($open<=.0001)continue;$rate=(float)($c['currentCarryingRate']??$c['functionalRate']??0);$meta=(array)($c['meta']??[]);$rows[]=['id'=>$id,'source'=>'Exports — TG Intercompany','counterparty'=>(string)($c['counterparty']??'TTI'),'reference'=>(string)($c['reference']??$c['sourceKey']??''),'currency'=>strtoupper((string)($c['transactionCurrency']??'USD')),'outstandingNative'=>$open,'currentCarryingRate'=>$rate,'outstandingAed'=>round($open*$rate,2),'payableAccount'=>'2500','dueDate'=>'','journalId'=>(string)$c['journalId'],'fiRefs'=>(array)($meta['fiRefs']??[]),'gdRefs'=>(array)($meta['gdRefs']??[]),'pakistanCandidateId'=>(string)($c['linkedCandidateId']??'')];}
 usort($rows,static fn($a,$b)=>strcmp((string)($a['dueDate']?:'9999-12-31'),(string)($b['dueDate']?:'9999-12-31'))?:strcmp((string)$a['counterparty'],(string)$b['counterparty']));return $rows;}
function tgtx_payload(array $store,string $date): array {$banks=tgtx_banks($store);$rows=[];foreach($banks as $id=>$b){if(($b['accountType']??'')!=='Company Account'||!in_array($b['currency'],(array)(tt_master_options()['currencies']??[]),true))continue;if(strcasecmp((string)($b['masterStatus']??'Active'),'Active')!==0||((string)$b['accountNumber']===''&&(string)$b['iban']===''))continue;$rows[]=array_merge($b,['balance'=>tgtx_balance($store,$id,$b['currency'])]);}usort($rows,static fn($a,$b)=>strcmp((string)$a['currency'],(string)$b['currency'])?:strcmp((string)$a['bank'],(string)$b['bank']));$hist=[];foreach((array)($store['tgBankTransactions']??[]) as $x)if(is_array($x))$hist[]=$x;usort($hist,static fn($a,$b)=>strcmp((string)($b['date']??''),(string)($a['date']??''))?:strcmp((string)($b['createdAt']??''),(string)($a['createdAt']??'')));return ['ok'=>true,'entity'=>'TG','rates'=>tgtx_rates($date,false),'banks'=>$rows,'openExportReceivables'=>tgtx_open_export_receivables($store),'openLiabilities'=>tgtx_open_liabilities($store),'history'=>array_slice($hist,0,50),'expenseAccounts'=>['6100'=>'Utilities','6300'=>'Rent & Occupancy','6400'=>'Repairs & Maintenance','6500'=>'Travel & Conveyance','6600'=>'Company Cars / Fuel','6700'=>'Inspection, Certification & Professional Fees','6800'=>'Bank & Finance Charges','6900'=>'Office & General Administration'],'assetAccounts'=>['1250'=>'Supplier / Service Advances','1510'=>'Plant & Machinery','1520'=>'Motor Vehicles','1530'=>'Furniture & Fixtures','1540'=>'Computers & Office Equipment']];}
function tgtx_unique_ref(array $store,string $bankId,string $ref): void {foreach((array)($store['tgBankTransactions']??[]) as $x)if(is_array($x)&&(string)($x['bankAccountId']??'')===$bankId&&strcasecmp((string)($x['bankReference']??''),$ref)===0)tgtx_out(['ok'=>false,'error'=>'This bank reference is already posted for the selected TG account.'],409);}

try{
  $u=tt_require_login();if(!tt_user_can_open_module($u,'Accounts'))tgtx_out(['ok'=>false,'error'=>'Accounts permission required.'],403);
  if($_SERVER['REQUEST_METHOD']==='GET'){$date=(string)($_GET['date']??(new DateTimeImmutable('now',new DateTimeZone('Asia/Dubai')))->format('Y-m-d'));if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date))$date=(new DateTimeImmutable('now',new DateTimeZone('Asia/Dubai')))->format('Y-m-d');tgtx_out(tgtx_payload(tgtx_read(),$date));}
  if($_SERVER['REQUEST_METHOD']!=='POST')tgtx_out(['ok'=>false,'error'=>'Method not allowed.'],405);if(!tgtx_can($u))tgtx_out(['ok'=>false,'error'=>'Accounts Create / Edit / Approve permission required.'],403);
  $b=json_decode(file_get_contents('php://input')?:'{}',true);if(!is_array($b)||!tt_verify_csrf((string)($b['csrf']??'')))tgtx_out(['ok'=>false,'error'=>'Your session expired. Refresh and try again.'],419);$action=(string)($b['action']??'');if(!in_array($action,['post_receipt','post_payment'],true))tgtx_out(['ok'=>false,'error'=>'Unknown TG bank action.'],422);
  $date=tgtx_date(trim((string)($b['date']??'')));$bankId=trim((string)($b['bankAccountId']??''));$bankRef=trim((string)($b['bankReference']??''));if($bankRef==='')tgtx_out(['ok'=>false,'error'=>'Bank reference is required.'],422);$counterparty=trim((string)($b['counterparty']??''));if($counterparty==='')tgtx_out(['ok'=>false,'error'=>'Customer / payee / counterparty is required.'],422);$notes=trim((string)($b['notes']??''));
  tt_ensure_data_dir();$h=fopen(TT_TGTX_FILE,'c+');if($h===false||!flock($h,LOCK_EX))throw new RuntimeException('Accounts storage unavailable.');
  try{rewind($h);$raw=stream_get_contents($h);$store=$raw?json_decode($raw,true):null;if(!is_array($store))$store=tgtx_defaults();$store=array_replace_recursive(tgtx_defaults(),$store);$banks=tgtx_banks($store);$bank=$banks[$bankId]??null;if(!is_array($bank)||($bank['accountType']??'')!=='Company Account'||!in_array($bank['currency'],(array)(tt_master_options()['currencies']??[]),true))tgtx_out(['ok'=>false,'error'=>'Select an active TG company bank account in the transaction currency.'],422);$settings=(array)($bank['settings']??[]);if(strcasecmp((string)($bank['masterStatus']??'Active'),'Active')!==0||((string)$bank['accountNumber']===''&&(string)$bank['iban']===''))tgtx_out(['ok'=>false,'error'=>'Complete and activate this TG bank account in TG Master.'],422);tgtx_unique_ref($store,$bankId,$bankRef);$currency=$bank['currency'];$rate=round((float)($b['rate']??($currency==='AED'?1:0)),8);if($rate<=0)tgtx_out(['ok'=>false,'error'=>'Enter the AED accounting rate for this TG bank transaction.'],422);$rateOverride=false;$cat=tgtx_catalog();$lines=[];$row=[];
    if($action==='post_receipt'){
      $type=strtoupper(trim((string)($b['receiptType']??'')));if(!in_array($type,['EXPORT_RECEIVABLE','CUSTOMER_ADVANCE','INTERCOMPANY_RECEIVABLE','OTHER_RECEIVABLE'],true))tgtx_out(['ok'=>false,'error'=>'Select a valid TG receipt type.'],422);$settlement=tgtx_pos($b['settlementAmountNative']??0,'Receipt / settlement amount');$charge=round(max(0,(float)($b['bankChargeNative']??0)),2);if($charge>$settlement)tgtx_out(['ok'=>false,'error'=>'Bank charge cannot exceed the gross settlement amount.'],422);$bankNative=round($settlement-$charge,2);$bankAed=round($bankNative*$rate,2);$chargeAed=round($charge*$rate,2);$sourceId=trim((string)($b['sourceCandidateId']??''));$target='';$settlementAed=0.0;
      if($type==='EXPORT_RECEIVABLE'){$cand=$store['exportCandidates'][$sourceId]??null;if(!is_array($cand)||($cand['entity']??'')!=='TG'||empty($cand['journalId']))tgtx_out(['ok'=>false,'error'=>'Select a recognized TG export receivable.'],422);$ccy=strtoupper((string)($cand['transactionCurrency']??''));if($ccy!==$currency)tgtx_out(['ok'=>false,'error'=>'Receipt bank currency must match the selected TG export receivable currency. Convert between TG USD/AED accounts separately when needed.'],422);$open=null;foreach(tgtx_open_export_receivables($store) as $o)if($o['id']===$sourceId){$open=$o;break;}if(!$open)tgtx_out(['ok'=>false,'error'=>'Selected TG export receivable has no open balance.'],409);if($settlement>(float)$open['outstandingNative']+.0001)tgtx_out(['ok'=>false,'error'=>'Receipt exceeds the open export receivable balance.'],422);$fr=(float)($cand['currentCarryingRate']??$cand['functionalRate']??0);if($fr<=0)tgtx_out(['ok'=>false,'error'=>'Selected export receivable has no approved AED carrying rate.'],422);$settlementAed=round($settlement*$fr,2);$target='1210';$counterparty=trim((string)(($cand['meta']['customer']??'')?:$counterparty));}
      elseif($type==='CUSTOMER_ADVANCE'){$target='2510';$settlementAed=round($settlement*$rate,2);}
      elseif($type==='INTERCOMPANY_RECEIVABLE'){$target='1240';$settlementAed=round((float)($b['settlementAed']??($settlement*$rate)),2);if($settlementAed<=0)tgtx_out(['ok'=>false,'error'=>'Enter the AED carrying amount of the intercompany receivable being cleared.'],422);}
      else{$target='1230';$settlementAed=round((float)($b['settlementAed']??($settlement*$rate)),2);if($settlementAed<=0)tgtx_out(['ok'=>false,'error'=>'Enter the AED carrying amount of the receivable being cleared.'],422);}
      $lines[]=tgtx_line('1110',$bankAed,0,$cat,['bankAccountId'=>$bankId,'bankName'=>$bank['bank'],'bankAccountTitle'=>$bank['title'],'currency'=>$currency,'bankDebit'=>$bankNative,'bankCredit'=>0]);if($chargeAed>0)$lines[]=tgtx_line('6800',$chargeAed,0,$cat,['chargeType'=>'TG incoming bank charge','chargeNative'=>$charge,'currency'=>$currency]);$lines[]=tgtx_line($target,0,$settlementAed,$cat,['counterparty'=>$counterparty,'sourceCandidateId'=>$sourceId]);$otherDebit=round($bankAed+$chargeAed,2);$diff=round($settlementAed-$otherDebit,2);if($diff>0)$lines[]=tgtx_line('7100',$diff,0,$cat,['fxDirection'=>'Loss']);elseif($diff<0)$lines[]=tgtx_line('7100',0,abs($diff),$cat,['fxDirection'=>'Gain']);$kind='Receipt';$sourceType=$type==='CUSTOMER_ADVANCE'?'TG_CUSTOMER_ADVANCE_RECEIVED':'TG_BANK_RECEIPT';$row=['receiptType'=>$type,'sourceCandidateId'=>$sourceId,'settlementAmountNative'=>$settlement,'bankChargeNative'=>$charge,'bankCreditNative'=>$bankNative,'settlementAed'=>$settlementAed,'targetAccount'=>$target];
    } else {
      $type=strtoupper(trim((string)($b['paymentType']??'')));if(!in_array($type,['LIABILITY','PAYABLE','INTERCOMPANY','DIRECT_EXPENSE','SUPPLIER_ADVANCE','FIXED_ASSET'],true))tgtx_out(['ok'=>false,'error'=>'Select a valid TG payment type.'],422);$amount=tgtx_pos($b['amountNative']??0,'Payment amount');$charge=round(max(0,(float)($b['bankChargeNative']??0)),2);$totalNative=round($amount+$charge,2);$bal=tgtx_balance($store,$bankId,$currency);if($totalNative>(float)$bal['native']+.0001)tgtx_out(['ok'=>false,'error'=>'Insufficient '.$currency.' book balance. Required '.$currency.' '.number_format($totalNative,2).' including charges; available '.$currency.' '.number_format((float)$bal['native'],2).'.'],422);$carryingRate=$currency==='AED'?1.0:(float)$bal['carryingRate'];if($carryingRate<=0)tgtx_out(['ok'=>false,'error'=>'Selected USD bank has no AED carrying value. Reconcile/open the TG USD balance before payment.'],422);$bankCreditAed=round($totalNative*$carryingRate,2);$chargeAed=round($charge*$rate,2);$target='';$targetAed=0.0;$requested=trim((string)($b['targetAccount']??''));$sourceLiabilityId='';
      if($type==='LIABILITY'){$sourceLiabilityId=trim((string)($b['sourceLiabilityId']??''));$liability=null;foreach(tgtx_open_liabilities($store) as $x)if((string)$x['id']===$sourceLiabilityId){$liability=$x;break;}if(!$liability)tgtx_out(['ok'=>false,'error'=>'Select an open TG liability.'],422);if((string)$liability['currency']!==$currency)tgtx_out(['ok'=>false,'error'=>'Payment bank currency must match the selected liability currency. Convert TG funds between USD/AED first if needed.'],422);if($amount>(float)$liability['outstandingNative']+.0001)tgtx_out(['ok'=>false,'error'=>'Payment exceeds the selected liability outstanding balance.'],422);$target=(string)$liability['payableAccount'];$targetAed=round($amount*(float)$liability['currentCarryingRate'],2);$counterparty=(string)$liability['counterparty'];if(($liability['source']??'')==='Exports — TG Intercompany'){$invoiceRef=(string)$liability['reference'];$fiRef=trim((string)($b['fiRef']??''));$gdRef=trim((string)($b['gdRef']??''));$otherRef=trim((string)($b['otherRef']??''));$referenceType=strtoupper(trim((string)($b['referenceType']??'')));if($referenceType===''&&$fiRef===''&&$gdRef==='')$referenceType='UNALLOCATED';if($referenceType===''&&$fiRef!==''&&$gdRef==='')$referenceType='FI';if($referenceType===''&&$gdRef!==''&&$fiRef==='')$referenceType='GD';if(!in_array($referenceType,['FI','GD','OTHER','UNALLOCATED'],true))tgtx_out(['ok'=>false,'error'=>'Select FI, GD, Other or Unallocated for the Exports payment reference.'],422);if($referenceType==='FI'&&($fiRef===''||$gdRef!==''||$otherRef!==''))tgtx_out(['ok'=>false,'error'=>'Select one linked FI for this TG payment.'],422);if($referenceType==='GD'&&($gdRef===''||$fiRef!==''||$otherRef!==''))tgtx_out(['ok'=>false,'error'=>'Select one linked GD for this TG payment.'],422);if($referenceType==='OTHER'&&($otherRef===''||$fiRef!==''||$gdRef!==''))tgtx_out(['ok'=>false,'error'=>'Enter the other Exports payment reference.'],422);if($referenceType==='UNALLOCATED'&&($fiRef!==''||$gdRef!==''||$otherRef!==''))tgtx_out(['ok'=>false,'error'=>'An unallocated payment cannot have an FI, GD or other reference.'],422);if($fiRef!==''&&!in_array($fiRef,(array)$liability['fiRefs'],true))tgtx_out(['ok'=>false,'error'=>'Selected FI is not linked to this intercompany invoice in Exports.'],422);if($gdRef!==''&&!in_array($gdRef,(array)$liability['gdRefs'],true))tgtx_out(['ok'=>false,'error'=>'Selected GD is not linked to this intercompany invoice in Exports.'],422);$row['invoiceRef']=$invoiceRef;$row['referenceType']=$referenceType;$row['otherRef']=$otherRef;$row['fiRef']=$fiRef;$row['gdRef']=$gdRef;$row['pakistanCandidateId']=(string)$liability['pakistanCandidateId'];}}
      elseif($type==='DIRECT_EXPENSE'){$allowed=['6100','6300','6400','6500','6600','6700','6800','6900'];if(!in_array($requested,$allowed,true))tgtx_out(['ok'=>false,'error'=>'Select an approved TG expense account.'],422);$target=$requested;$targetAed=round($amount*$rate,2);}
      elseif($type==='SUPPLIER_ADVANCE'){$target='1250';$targetAed=round($amount*$rate,2);}
      elseif($type==='FIXED_ASSET'){$allowed=['1510','1520','1530','1540'];if(!in_array($requested,$allowed,true))tgtx_out(['ok'=>false,'error'=>'Select an approved fixed asset account.'],422);$target=$requested;$targetAed=round($amount*$rate,2);}
      elseif($type==='INTERCOMPANY'){$target='2500';$targetAed=round((float)($b['settlementAed']??0),2);if($targetAed<=0)tgtx_out(['ok'=>false,'error'=>'Enter the AED carrying amount of the intercompany payable being cleared.'],422);}
      else{$allowed=['2130','2140'];if(!in_array($requested,$allowed,true))tgtx_out(['ok'=>false,'error'=>'Select the payable being settled.'],422);$target=$requested;$targetAed=round((float)($b['settlementAed']??0),2);if($targetAed<=0)tgtx_out(['ok'=>false,'error'=>'Enter the AED carrying amount of the payable being cleared.'],422);}
      $lines[]=tgtx_line($target,$targetAed,0,$cat,['counterparty'=>$counterparty,'sourceLiabilityId'=>$sourceLiabilityId]);if($chargeAed>0)$lines[]=tgtx_line('6800',$chargeAed,0,$cat,['chargeType'=>'TG outgoing bank charge','chargeNative'=>$charge,'currency'=>$currency]);$lines[]=tgtx_line('1110',0,$bankCreditAed,$cat,['bankAccountId'=>$bankId,'bankName'=>$bank['bank'],'bankAccountTitle'=>$bank['title'],'currency'=>$currency,'bankDebit'=>0,'bankCredit'=>$totalNative]);$otherDebit=round($targetAed+$chargeAed,2);$fx=round($bankCreditAed-$otherDebit,2);if($fx>0)$lines[]=tgtx_line('7100',$fx,0,$cat,['fxDirection'=>'Loss']);elseif($fx<0)$lines[]=tgtx_line('7100',0,abs($fx),$cat,['fxDirection'=>'Gain']);$kind='Payment';$sourceType=$type==='SUPPLIER_ADVANCE'?'TG_SUPPLIER_ADVANCE':($type==='LIABILITY'?'TG_LIABILITY_PAYMENT':'TG_BANK_PAYMENT');$row=array_merge($row,['paymentType'=>$type,'targetAccount'=>$target,'sourceLiabilityId'=>$sourceLiabilityId,'amountNative'=>$amount,'bankChargeNative'=>$charge,'bankDebitNative'=>$totalNative,'settlementAed'=>$targetAed,'bankCarryingRate'=>$carryingRate]);
    }
    $dr=round(array_sum(array_column($lines,'debit')),2);$cr=round(array_sum(array_column($lines,'credit')),2);if(abs($dr-$cr)>.01)throw new RuntimeException('TG bank journal did not balance.');$id=tgtx_next((array)$store['tgBankTransactions'],'TGBK');$jid=tgtx_next((array)$store['journals'],'AUTO');$meta=array_merge($row,['tgBankTransactionId'=>$id,'kind'=>$kind,'bankAccountId'=>$bankId,'bankReference'=>$bankRef,'counterparty'=>$counterparty,'currency'=>$currency,'rate'=>$rate,'rateOverride'=>$rateOverride,'rateOverrideNote'=>trim((string)($b['rateOverrideNote']??'')),'notes'=>$notes]);$store['journals'][$jid]=['id'=>$jid,'entity'=>'TG','date'=>$date,'sourceType'=>$sourceType,'reference'=>$bankRef,'narration'=>'TG '.$kind.' — '.$counterparty.' — '.$bankRef,'lines'=>$lines,'totalDebit'=>$dr,'totalCredit'=>$cr,'status'=>'Posted','meta'=>$meta,'createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??$u['username']??'Accounts'),'userId'=>(int)($u['id']??0),'reversalOf'=>null];$tx=array_merge(['id'=>$id,'kind'=>$kind,'date'=>$date,'bankAccountId'=>$bankId,'bank'=>$bank['bank'],'bankTitle'=>$bank['title'],'currency'=>$currency,'bankReference'=>$bankRef,'counterparty'=>$counterparty,'rate'=>$rate,'journalId'=>$jid,'notes'=>$notes,'status'=>'Accounts Approved / Posted','createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??$u['username']??'Accounts')],$row);$store['tgBankTransactions'][$id]=$tx;$store['revision']=(int)($store['revision']??0)+1;rewind($h);ftruncate($h,0);fwrite($h,json_encode($store,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($h);
  }finally{flock($h,LOCK_UN);fclose($h);}tgtx_out(tgtx_payload($store,$date)+['transaction'=>$tx,'journal'=>$store['journals'][$jid],'revision'=>$store['revision']]);
}catch(Throwable $e){tgtx_out(['ok'=>false,'error'=>'The TG bank transaction could not be completed.'],500);}
