<?php
declare(strict_types=1);

require dirname(__DIR__) . '/auth_store.php';
header('Content-Type: application/json; charset=UTF-8');
header('Cache-Control: no-store, no-cache, must-revalidate');

const TT_TGC_FILE = TT_DATA_DIR . '/accounts.json';
const TT_TGC_MASTER = __DIR__ . '/../accounts/accounting_master_v1.json';
const TT_TGC_RATE_TYPE = 'tg_currency_rates';

function tgc_out(array $d,int $s=200): never {http_response_code($s);echo json_encode($d,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function tgc_can(array $u): bool {if(($u['role']??'')==='Super Admin')return true;$p=$u['permissions']['Accounts']??null;if($p==='all')return true;if(!is_array($p))return false;if(in_array('Approve',$p,true)||in_array('Edit',$p,true))return true;foreach($p as $a)if(is_array($a)&&(in_array('Approve',$a,true)||in_array('Edit',$a,true)))return true;return false;}
function tgc_defaults(): array {return ['revision'=>0,'journals'=>[],'bankAccountSettings'=>[],'exportCandidates'=>[],'tgBankTransactions'=>[],'tgLiabilities'=>[],'tgYearEndRevaluations'=>[]];}
function tgc_read(): array {tt_ensure_data_dir();if(!is_file(TT_TGC_FILE))return tgc_defaults();$h=fopen(TT_TGC_FILE,'r');if($h===false||!flock($h,LOCK_SH))throw new RuntimeException('Accounts storage unavailable.');try{$raw=stream_get_contents($h);}finally{flock($h,LOCK_UN);fclose($h);}$v=$raw?json_decode($raw,true):null;return is_array($v)?array_replace_recursive(tgc_defaults(),$v):tgc_defaults();}
function tgc_catalog(): array {$raw=file_get_contents(TT_TGC_MASTER);$m=$raw?json_decode($raw,true):null;if(!is_array($m))throw new RuntimeException('Accounting master unavailable.');$o=[];foreach((array)($m['chart']??[]) as $a)if(is_array($a)&&isset($a['code']))$o[(string)$a['code']]=$a;return $o;}
function tgc_line(string $a,float $dr,float $cr,array $cat,array $x=[]): array {if(!isset($cat[$a]))tgc_out(['ok'=>false,'error'=>'Approved account '.$a.' unavailable.'],422);return array_merge(['account'=>$a,'accountName'=>(string)($cat[$a]['name']??$a),'debit'=>round($dr,2),'credit'=>round($cr,2)],$x);}
function tgc_rates(string $date): array {$m=(array)(tt_read_store()['masters']??[]);$best=null;foreach((array)($m[TT_TGC_RATE_TYPE]??[]) as $r){if(!is_array($r))continue;$v=array_values((array)($r['values']??[]));while(count($v)<12)$v[]='';$st=strtolower((string)$v[10]);if(str_contains($st,'inactive')||str_contains($st,'historical'))continue;$from=(string)$v[6];$to=(string)$v[7];if($from!==''&&$date<$from)continue;if($to!==''&&$date>$to)continue;if($best===null||$from>(string)$best['effectiveFrom'])$best=['id'=>(string)($r['id']??''),'code'=>(string)$v[1],'sellUsdToAed'=>(float)$v[3],'buyUsdWithAed'=>(float)$v[4],'closingTax'=>(float)$v[5],'effectiveFrom'=>$from,'effectiveTo'=>$to,'yearEnd'=>(string)$v[8],'closingCurrency'=>(string)$v[9]];}if(!$best)tgc_out(['ok'=>false,'error'=>'No active TG Master rate applies to this date.'],422);return $best;}
function tgc_tg_bank_rows(array $store): array {$m=(array)(tt_read_store()['masters']??[]);$out=[];foreach((array)($m['banks']??[]) as $r){if(!is_array($r))continue;$v=array_values((array)($r['values']??[]));while(count($v)<14)$v[]='';$linked=strtoupper((string)$v[1]);if(!str_contains($linked,'TG')&&!str_contains($linked,'TRANS GRAINS'))continue;$id=(string)($r['id']??'');$s=is_array($store['bankAccountSettings'][$id]??null)?$store['bankAccountSettings'][$id]:[];if(empty($s['active'])||strtoupper((string)$v[7])!=='USD')continue;$out[$id]=['id'=>$id,'bank'=>(string)$v[4],'title'=>(string)$v[3],'currency'=>'USD'];}return $out;}
function tgc_bank_asof(array $store,string $id,string $date): array {$native=0.0;$aed=0.0;foreach((array)($store['journals']??[]) as $j){if(!is_array($j)||($j['status']??'')!=='Posted'||($j['entity']??'')!=='TG'||(string)($j['date']??'')>$date)continue;$jm=is_array($j['meta']??null)?$j['meta']:[];foreach((array)($j['lines']??[]) as $l){if(!is_array($l)||(string)($l['account']??'')!=='1110')continue;$bid=(string)($l['bankAccountId']??$jm['bankAccountId']??'');if($bid!==$id)continue;$native+=(float)($l['bankDebit']??0)-(float)($l['bankCredit']??0);$aed+=(float)($l['debit']??0)-(float)($l['credit']??0);}}return ['native'=>round($native,4),'carryingAed'=>round($aed,2),'carryingRate'=>$native>0?round($aed/$native,8):0.0];}
function tgc_receipt_used_asof(array $store,string $candidateId,string $date): float {$n=0.0;foreach((array)($store['tgBankTransactions']??[]) as $x){if(!is_array($x)||($x['kind']??'')!=='Receipt'||($x['receiptType']??'')!=='EXPORT_RECEIVABLE'||(string)($x['date']??'')>$date||(string)($x['sourceCandidateId']??'')!==$candidateId)continue;$n+=(float)($x['settlementAmountNative']??0);}return round($n,4);}
function tgc_liability_paid_asof(array $store,string $liabilityId,string $date): float {$n=0.0;foreach((array)($store['tgBankTransactions']??[]) as $x){if(!is_array($x)||($x['kind']??'')!=='Payment'||(string)($x['date']??'')>$date||(string)($x['sourceLiabilityId']??'')!==$liabilityId)continue;$n+=(float)($x['amountNative']??0);}return round($n,4);}
function tgc_historical_rate(array $store,string $kind,string $id,float $base,string $date): float {$rate=$base;$best='';foreach((array)($store['tgYearEndRevaluations']??[]) as $r){if(!is_array($r))continue;$rd=(string)($r['date']??'');if($rd===''||$rd>$date||$rd<$best)continue;$items=$kind==='receivable'?(array)($r['receivableItems']??[]):(array)($r['liabilityItems']??[]);foreach($items as $x){if(!is_array($x))continue;$key=$kind==='receivable'?(string)($x['candidateId']??''):(string)($x['liabilityId']??'');if($key===$id){$rate=(float)($r['closingRate']??$x['closingRate']??$rate);$best=$rd;break;}}}return $rate;}
function tgc_receivables_asof(array $store,string $date,float $closingRate): array {$rows=[];foreach((array)($store['exportCandidates']??[]) as $c){if(!is_array($c)||($c['entity']??'')!=='TG'||($c['candidateType']??'')!=='CUSTOMER_EXPORT_SALE'||empty($c['journalId']))continue;$recognition=(string)($c['recognitionDate']??$c['suggestedRecognitionDate']??'');if($recognition!==''&&$recognition>$date)continue;if(strtoupper((string)($c['transactionCurrency']??''))!=='USD')continue;$orig=(float)($c['transactionAmount']??0);$used=tgc_receipt_used_asof($store,(string)$c['id'],$date);$open=round($orig-$used,4);if($open<=.0001)continue;$base=(float)($c['functionalRate']??0);$rate=tgc_historical_rate($store,'receivable',(string)$c['id'],$base,$date);if($rate<=0)continue;$carrying=round($open*$rate,2);$target=round($open*$closingRate,2);$adj=round($target-$carrying,2);$m=is_array($c['meta']??null)?$c['meta']:[];$rows[]=['candidateId'=>(string)$c['id'],'reference'=>(string)($c['reference']??$c['sourceKey']??''),'customer'=>(string)($m['customer']??''),'outstandingUsd'=>$open,'carryingRate'=>$rate,'carryingAed'=>$carrying,'closingRate'=>$closingRate,'targetAed'=>$target,'adjustmentAed'=>$adj];}usort($rows,static fn($a,$b)=>strcmp((string)$a['reference'],(string)$b['reference']));return $rows;}
function tgc_liabilities_asof(array $store,string $date,float $closingRate): array {$rows=[];
 foreach((array)($store['tgLiabilities']??[]) as $x){if(!is_array($x)||strtoupper((string)($x['currency']??''))!=='USD')continue;$posted=(string)($x['date']??'');if($posted!==''&&$posted>$date)continue;$id=(string)($x['id']??'');$orig=(float)($x['nativeAmount']??0);$paid=tgc_liability_paid_asof($store,$id,$date);$open=round($orig-$paid,4);if($open<=.0001)continue;$base=(float)($x['recognitionRate']??0);$rate=tgc_historical_rate($store,'liability',$id,$base,$date);if($rate<=0)continue;$carrying=round($open*$rate,2);$target=round($open*$closingRate,2);$rows[]=['liabilityId'=>$id,'source'=>'Supplier / Service Bill','reference'=>(string)($x['reference']??''),'counterparty'=>(string)($x['counterparty']??''),'payableAccount'=>(string)($x['payableAccount']??'2140'),'outstandingUsd'=>$open,'carryingRate'=>$rate,'carryingAed'=>$carrying,'closingRate'=>$closingRate,'targetAed'=>$target,'adjustmentAed'=>round($target-$carrying,2)];}
 foreach((array)($store['exportCandidates']??[]) as $c){if(!is_array($c)||($c['entity']??'')!=='TG'||($c['candidateType']??'')!=='TG_INTERCOMPANY_PAYABLE'||empty($c['journalId'])||strtoupper((string)($c['transactionCurrency']??''))!=='USD')continue;$posted=(string)($c['recognitionDate']??$c['suggestedRecognitionDate']??'');if($posted!==''&&$posted>$date)continue;$id=(string)($c['id']??'');$orig=(float)($c['transactionAmount']??0);$paid=tgc_liability_paid_asof($store,$id,$date);$open=round($orig-$paid,4);if($open<=.0001)continue;$base=(float)($c['functionalRate']??0);$rate=tgc_historical_rate($store,'liability',$id,$base,$date);if($rate<=0)continue;$carrying=round($open*$rate,2);$target=round($open*$closingRate,2);$rows[]=['liabilityId'=>$id,'source'=>'Exports — TG Intercompany','reference'=>(string)($c['reference']??$c['sourceKey']??''),'counterparty'=>(string)($c['counterparty']??'TTI'),'payableAccount'=>'2500','outstandingUsd'=>$open,'carryingRate'=>$rate,'carryingAed'=>$carrying,'closingRate'=>$closingRate,'targetAed'=>$target,'adjustmentAed'=>round($target-$carrying,2)];}
 usort($rows,static fn($a,$b)=>strcmp((string)$a['counterparty'],(string)$b['counterparty'])?:strcmp((string)$a['reference'],(string)$b['reference']));return $rows;}
function tgc_preview(array $store,string $date): array {$rates=tgc_rates($date);$mmdd=substr($date,5,5);$yearEnd=(string)($rates['yearEnd']??'12-31');$rate=(float)$rates['closingTax'];$banks=[];foreach(tgc_tg_bank_rows($store) as $id=>$b){$bal=tgc_bank_asof($store,$id,$date);if(abs((float)$bal['native'])<.0001&&abs((float)$bal['carryingAed'])<.01)continue;$target=round((float)$bal['native']*$rate,2);$banks[]=array_merge($b,$bal,['closingRate'=>$rate,'targetAed'=>$target,'adjustmentAed'=>round($target-(float)$bal['carryingAed'],2)]);}usort($banks,static fn($a,$b)=>strcmp((string)$a['bank'],(string)$b['bank']));$receivables=tgc_receivables_asof($store,$date,$rate);$liabilities=tgc_liabilities_asof($store,$date,$rate);$assetAdj=round(array_sum(array_column($banks,'adjustmentAed'))+array_sum(array_column($receivables,'adjustmentAed')),2);$liabilityAdj=round(array_sum(array_column($liabilities,'adjustmentAed')),2);$net=round($assetAdj-$liabilityAdj,2);$existing=null;foreach((array)($store['tgYearEndRevaluations']??[]) as $x)if(is_array($x)&&(string)($x['date']??'')===$date){$existing=$x;break;}$today=(new DateTimeImmutable('now',new DateTimeZone('Asia/Dubai')))->format('Y-m-d');return ['ok'=>true,'date'=>$date,'yearEnd'=>$yearEnd,'isYearEndDate'=>$mmdd===$yearEnd,'isFuture'=>$date>$today,'rates'=>$rates,'banks'=>$banks,'receivables'=>$receivables,'liabilities'=>$liabilities,'assetAdjustmentAed'=>$assetAdj,'liabilityAdjustmentAed'=>$liabilityAdj,'netMonetaryAdjustmentAed'=>$net,'estimatedFxEffect'=>$net>0?['direction'=>'Gain','amount'=>abs($net)]:($net<0?['direction'=>'Loss','amount'=>abs($net)]:['direction'=>'Nil','amount'=>0]),'existing'=>$existing,'limitations'=>['This routine remeasures supported TG USD monetary assets and liabilities: active TG USD banks, open recognized TG USD export receivables, TG USD supplier/service liabilities and recognized TG↔Pakistan USD intercompany payables.','Native USD balances do not change during revaluation; only the AED carrying value is adjusted.','This is an FX remeasurement control, not the final statutory/tax close, cutoff review or period lock.']];}
function tgc_next(array $items,string $prefix): string {$n=count($items)+1;do{$id=$prefix.'-'.gmdate('Y').'-'.str_pad((string)$n,6,'0',STR_PAD_LEFT);$n++;}while(isset($items[$id]));return $id;}

try{
 $u=tt_require_login();if(!tt_user_can_open_module($u,'Accounts'))tgc_out(['ok'=>false,'error'=>'Accounts permission required.'],403);$date=(string)($_GET['date']??$_POST['date']??'');
 if($_SERVER['REQUEST_METHOD']==='GET'){if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date))$date=(new DateTimeImmutable('now',new DateTimeZone('Asia/Dubai')))->format('Y').'-12-31';tgc_out(tgc_preview(tgc_read(),$date));}
 if($_SERVER['REQUEST_METHOD']!=='POST')tgc_out(['ok'=>false,'error'=>'Method not allowed.'],405);if(!tgc_can($u))tgc_out(['ok'=>false,'error'=>'Accounts Edit / Approve permission required.'],403);$b=json_decode(file_get_contents('php://input')?:'{}',true);if(!is_array($b)||!tt_verify_csrf((string)($b['csrf']??'')))tgc_out(['ok'=>false,'error'=>'Your session expired. Refresh and try again.'],419);if((string)($b['action']??'')!=='post_revaluation')tgc_out(['ok'=>false,'error'=>'Unknown TG year-end action.'],422);$date=(string)($b['date']??'');if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date))tgc_out(['ok'=>false,'error'=>'Valid year-end date required.'],422);$note=trim((string)($b['note']??''));
 tt_ensure_data_dir();$h=fopen(TT_TGC_FILE,'c+');if($h===false||!flock($h,LOCK_EX))throw new RuntimeException('Accounts storage unavailable.');
 try{
   rewind($h);$raw=stream_get_contents($h);$store=$raw?json_decode($raw,true):null;if(!is_array($store))$store=tgc_defaults();$store=array_replace_recursive(tgc_defaults(),$store);$p=tgc_preview($store,$date);if(!$p['isYearEndDate'])tgc_out(['ok'=>false,'error'=>'TG FX remeasurement can only be posted on the TG Master year-end date '.$p['yearEnd'].'.'],422);if($p['isFuture'])tgc_out(['ok'=>false,'error'=>'Future year-end remeasurement cannot be posted. Preview is allowed, posting is not.'],422);if(is_array($p['existing'])&&!empty($p['existing']['status']))tgc_out(['ok'=>false,'error'=>'TG year-end remeasurement for '.$date.' is already recorded. Use a controlled reversal/adjustment if it must be corrected.'],409);
   $cat=tgc_catalog();$lines=[];$assetAdj=0.0;$liabilityAdj=0.0;
   foreach((array)$p['banks'] as $x){$adj=round((float)$x['adjustmentAed'],2);if(abs($adj)<.01)continue;$extra=['bankAccountId'=>$x['id'],'bankName'=>$x['bank'],'bankAccountTitle'=>$x['title'],'currency'=>'USD','bankDebit'=>0,'bankCredit'=>0,'revaluationOnly'=>true,'nativeBalance'=>(float)$x['native'],'closingRate'=>(float)$p['rates']['closingTax']];if($adj>0)$lines[]=tgc_line('1110',$adj,0,$cat,$extra);else $lines[]=tgc_line('1110',0,abs($adj),$cat,$extra);$assetAdj=round($assetAdj+$adj,2);}
   foreach((array)$p['receivables'] as $x){$adj=round((float)$x['adjustmentAed'],2);if(abs($adj)>=.01){$extra=['sourceCandidateId'=>$x['candidateId'],'customer'=>$x['customer'],'currency'=>'USD','revaluationOnly'=>true,'outstandingUsd'=>(float)$x['outstandingUsd'],'closingRate'=>(float)$p['rates']['closingTax']];if($adj>0)$lines[]=tgc_line('1210',$adj,0,$cat,$extra);else $lines[]=tgc_line('1210',0,abs($adj),$cat,$extra);$assetAdj=round($assetAdj+$adj,2);}$cid=(string)$x['candidateId'];if(isset($store['exportCandidates'][$cid])&&is_array($store['exportCandidates'][$cid])){$store['exportCandidates'][$cid]['currentCarryingRate']=(float)$p['rates']['closingTax'];$store['exportCandidates'][$cid]['currentCarryingAsOf']=$date;}}
   foreach((array)$p['liabilities'] as $x){$adj=round((float)$x['adjustmentAed'],2);$account=(string)$x['payableAccount'];if(abs($adj)>=.01){$extra=['sourceLiabilityId'=>$x['liabilityId'],'counterparty'=>$x['counterparty'],'currency'=>'USD','revaluationOnly'=>true,'outstandingUsd'=>(float)$x['outstandingUsd'],'closingRate'=>(float)$p['rates']['closingTax']];if($adj>0)$lines[]=tgc_line($account,0,$adj,$cat,$extra);else $lines[]=tgc_line($account,abs($adj),0,$cat,$extra);$liabilityAdj=round($liabilityAdj+$adj,2);} $lid=(string)$x['liabilityId'];if(isset($store['tgLiabilities'][$lid])&&is_array($store['tgLiabilities'][$lid])){$store['tgLiabilities'][$lid]['currentCarryingRate']=(float)$p['rates']['closingTax'];$store['tgLiabilities'][$lid]['currentCarryingAsOf']=$date;}elseif(isset($store['exportCandidates'][$lid])&&is_array($store['exportCandidates'][$lid])){$store['exportCandidates'][$lid]['currentCarryingRate']=(float)$p['rates']['closingTax'];$store['exportCandidates'][$lid]['currentCarryingAsOf']=$date;}}
   $net=round($assetAdj-$liabilityAdj,2);$jid=null;if(abs($net)>=.01){if($net>0)$lines[]=tgc_line('7100',0,$net,$cat,['fxDirection'=>'Gain','yearEndRevaluation'=>true]);else $lines[]=tgc_line('7100',abs($net),0,$cat,['fxDirection'=>'Loss','yearEndRevaluation'=>true]);$dr=round(array_sum(array_column($lines,'debit')),2);$cr=round(array_sum(array_column($lines,'credit')),2);if(abs($dr-$cr)>.01)throw new RuntimeException('TG year-end revaluation journal did not balance.');$jid=tgc_next((array)$store['journals'],'AUTO');$store['journals'][$jid]=['id'=>$jid,'entity'=>'TG','date'=>$date,'sourceType'=>'TG_YEAR_END_FX_REVALUATION','reference'=>'TG-FX-CLOSE-'.$date,'narration'=>'TG '.$date.' USD monetary assets and liabilities remeasured to AED closing/tax rate','lines'=>$lines,'totalDebit'=>$dr,'totalCredit'=>$cr,'status'=>'Posted','meta'=>['closingRate'=>$p['rates']['closingTax'],'rateMasterId'=>$p['rates']['id'],'rateMasterCode'=>$p['rates']['code'],'yearEnd'=>$p['yearEnd'],'closingCurrency'=>'AED','assetAdjustmentAed'=>$assetAdj,'liabilityAdjustmentAed'=>$liabilityAdj,'netMonetaryAdjustmentAed'=>$net,'note'=>$note],'createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??$u['username']??'Accounts'),'userId'=>(int)($u['id']??0),'reversalOf'=>null];}
   $id=tgc_next((array)$store['tgYearEndRevaluations'],'TGYE');$rec=['id'=>$id,'date'=>$date,'closingRate'=>$p['rates']['closingTax'],'rateMasterId'=>$p['rates']['id'],'rateMasterCode'=>$p['rates']['code'],'bankItems'=>$p['banks'],'receivableItems'=>$p['receivables'],'liabilityItems'=>$p['liabilities'],'assetAdjustmentAed'=>$assetAdj,'liabilityAdjustmentAed'=>$liabilityAdj,'netMonetaryAdjustmentAed'=>$net,'fxEffect'=>$net>0?'Gain':($net<0?'Loss':'Nil'),'journalId'=>$jid,'status'=>$jid?'Accounts Approved / Posted':'Reviewed — No Revaluation Entry Required','note'=>$note,'createdAt'=>gmdate('c'),'createdBy'=>(string)($u['full_name']??$u['username']??'Accounts')];$store['tgYearEndRevaluations'][$id]=$rec;$store['revision']=(int)($store['revision']??0)+1;rewind($h);ftruncate($h,0);fwrite($h,json_encode($store,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));fflush($h);
 }finally{flock($h,LOCK_UN);fclose($h);} $out=tgc_preview($store,$date);$out['revaluation']=$rec;$out['journal']=$jid?$store['journals'][$jid]:null;$out['revision']=$store['revision'];tgc_out($out);
}catch(Throwable $e){tgc_out(['ok'=>false,'error'=>'The TG year-end revaluation could not be completed.'],500);}
